### ISSUE TITLE
Discovery around adding performance profiling/testing

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1017]
In light of #993 it is clear we need more performance profiling in place for the plugin.

- [ ] Using the scripts used to populate a site with test content, generate a post fully populated with embeds, widgets, and comments, with enough lorem ipsum text to count as a long-form post. Then with the [“AMP Conf” theme](https://github.com/xwp/ampconf) active, capture the source of the page. Then save the output to `tests` directory for use in testing.
- [ ] Run Xdebug profiler and do a sanity check for performance bottlenecks.
- [ ] Add a PHPUnit test for performance, loading up the captured HTML output and making sure the processing of the HTML does not take more than a reasonable amount of time.
- [ ] Ensure that external HTTP requests are mocked to prevent network requests from causing periodic failures. (Aside: Make sure all other requests in tests are also mocked to prevent any external requests from hitting the network when running tests.)
- [ ] Add a new test suite that includes the performance testing and also the slow `runInSeparateProcess` tests. Let this test suite be run with all the others on Travis CI, but exclude it by default on the local environment. Or rather, as in the case of Gutenberg, use environment variable for this same purpose. A separate testsuite/group seems better.

See also #990 for sending back server timings via HTTP response headers.

**Comment by westonruter** [comment]
For one approach, consider: https://github.com/WordPress/gutenberg/blob/master/phpunit/class-performance-test.php

**Comment by schlessera** [comment]
I talked about this with @amedina and suggested to look into the [Blackfire profiler](https://blackfire.io/) I had already mentioned. This has built-in support for CI integration, and although this is only provided in the paid edition, it is probably still cheaper than building such a system from scratch using Xdebug.

**Comment by archon810** [comment]
https://github.com/ampproject/amp-wp/issues/2069#issuecomment-530590423 shows just how bad validation could get. 3s normal WP functions after pressing Update, then a 9s AMP validation.

**Comment by schlessera** [comment]
Added #3361 as a result of this discovery ticket. Closing this for now. If we decide not to proceed with Blackfire, we can reopen again.
