### ISSUE TITLE
Set up tests using the validator

### ISSUE THREAD

**Issue by mjangda** [ampproject/amp-wp#114]
Since it's now public: https://github.com/ampproject/amphtml/tree/master/validator

**Comment by mjangda** [comment]
Alternate validator projects/approaches:
https://github.com/dorightdigital/amp-validator
https://jsfiddle.net/4yoxog13/5/

**Comment by rudygalfi** [comment]
cc @cramforce @gregable

**Comment by cramforce** [comment]
Should this run in browser or on the command line? If the latter, is this an option: https://www.npmjs.com/package/amp-validator
