### ISSUE TITLE
Utilize new data-amp-bind-* alternative syntax for amp-bind attributes

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1162]
There is a new XHTML-compatible amp-bind attribute syntax: https://github.com/ampproject/amphtml/issues/11115 via https://github.com/ampproject/amphtml/pull/15408

Instead of:

```html
<span class="foo" [class]="foo ? 'foo' : 'bar'">
```

We can now do:

```html
<span class="foo" data-amp-bind-class="foo ? 'foo' : 'bar'">
```

What this means is that we now have an official way of representing amp-bind attributes in PHP's DOM internals. We can now eliminate `AMP_DOM_Utils::get_amp_bind_placeholder_prefix()` and `AMP_DOM_Utils::restore_amp_bind_attributes()` entirely, and [`AMP_DOM_Utils::convert_amp_bind_attributes()`](https://github.com/Automattic/amp-wp/blob/927b07ca926582fd0a2be585bf8f12a16fae0a49/includes/utils/class-amp-dom-utils.php#L191-L269) can be modified to just convert the bracketed syntax into the `data-amp-bind-*` syntax. There would be no need to restore the bracketed syntax when re-serializing. The result will be improved performance.

**Comment by lucky42890** [comment]
Is this issue solved ?

**Comment by westonruter** [comment]
No

**Comment by westonruter** [comment]
We need to update the whitelist sanitizer to automatically enqueue amp-bind when `data-amp-bind-*` attributes are found. Currently it is only doing so for bracketed attributes:

https://github.com/ampproject/amp-wp/blob/efd1d0759d000a82a48ae0a0dd1fca9bdbcf1d8d/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L550-L558

This should also be done in the `process_alternate_names` method.

**Comment by westonruter** [comment]
We also need to make sure that the alternative syntax is supported in places like:

https://github.com/ampproject/amp-wp/blob/437c335b84106a8099fb3929c8d6faeaa6d7fb7b/includes/sanitizers/class-amp-style-sanitizer.php#L441-L446

Anywhere that `AMP_DOM_Utils::get_amp_bind_placeholder_prefix()` occurs we'd need to also supply `'data-amp-bind-'` as an alternative prefix.

Alternatively, we could just rewrite all bracketed-syntax attributes with `data-amp-bind-*` ones, which is what I suggested above 😄

**Comment by conwaydev** [comment]
Glad I found this, we recently found out about the wonderful `data-amp-bind-class` attribute, however the AMP plugin's UnCSS will strip out the classes we pass to it whereas `[class]` will work just fine.

**Comment by westonruter** [comment]
I started work on this.

@conwaydev Initial PR ready for testing: #2974

**Comment by westonruter** [comment]
Also reported on support forum: https://wordpress.org/support/topic/hambuger-menu-no-opening-on-static-version-of-website/

**Comment by westonruter** [comment]
@conwaydev Please test: https://github.com/ampproject/amp-wp/pull/2974
