### ISSUE TITLE
Improve object cache warning notice with host-specific instructions

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1216]
There is currently a notice on the AMP settings page that links to the [Persistent Caching](https://codex.wordpress.org/Class_Reference/WP_Object_Cache#Persistent_Caching) page on the Codex:

![image](https://user-images.githubusercontent.com/134745/41514034-ed7556c8-72a3-11e8-8df1-f6d1bd3eee4d.png)

The codex page is not very informative. It would be best if we detected the hosting environment and linked off to their respective support docs on enabling object caching, for example:

* [WP Engine](https://wpengine.com/support/wp-engines-object-caching/)
* [Pantheon](https://pantheon.io/docs/redis/)
* [Kinsta](https://kinsta.com/knowledgebase/redis-cache/)
* [SiteGround](https://www.siteground.com/tutorials/supercacher/wordpress-memcached/)
* ...

This information should be exposed in the Site Health check.

**Comment by postphotos** [comment]
@westonruter, Are you aware of a way for a plugin or theme to surface the hosting platform? Agreed, that could be extremely useful for us here!

**Comment by westonruter** [comment]
No, but usually there are some signals that can move looked at to sniff out the hosting platform. For example on Pantheon the `$_ENV['PANTHEON_ENVIRONMENT'` variable is defined. On WP Engine there is a certain mu-plugin installed. And so on.

**Comment by westonruter** [comment]
As @schlessera suggested, it would be good to engage with the WordPress hosting community to put an authoritative documentation in the handbook.

**Comment by westonruter** [comment]
Another resource to refer to: https://scalewp.io/object-caching/

**Comment by kmyram** [comment]
Documentation here: https://make.wordpress.org/hosting/handbook/handbook/performance/

**Comment by westonruter** [comment]
The handbook performance page is missing the guidance on which specific plugins to use, and what object caching is available on each host. So that would be a natural next step for that [Object Cache section](https://make.wordpress.org/hosting/handbook/handbook/performance/#object-cache).

**Comment by westonruter** [comment]
@schlessera Do you know if the hosting team has this on their roadmap?

**Comment by schlessera** [comment]
@westonruter:

<img width="529" alt="Image 2020-03-18 at 6 54 55 AM" src="https://user-images.githubusercontent.com/83631/76929836-68024480-68e5-11ea-91b9-9ab6ef919942.png">

**Comment by My1** [comment]
another question would be whether or not this is even possible on for example a plain webhoster and if not just let the user supress the notification as there's nothing the user can do anyway

**Comment by westonruter** [comment]
We've agreed this is not feasible to do in a general way. It is up to hosts to add this information via `mu-plugins` on their respective platforms. 

Here's an example for how a host can override the test actions to include not only host-specific documentation link but also a button that could be used to enable object caching on their platform:

```php
add_filter(
	'site_status_test_result',
	function ( $test_result ) {
		if (
			isset( $test_result['test'], $test_result['status'] )
			&& 'amp_persistent_object_cache' === $test_result['test']
			&& 'recommended' === $test_result['status']
		) {
			$enable_button = sprintf(
				'<button class="button button-secondary" id="foo-host-enable-object-caching" type="button">%s</button>',
				esc_html__( 'Enable Object Caching', 'foo-host-object-caching' )
			);

			$learn_more_link = sprintf(
				'<a href="%1$s" target="_blank" rel="noopener noreferrer">%2$s <span class="screen-reader-text">%3$s</span><span aria-hidden="true" class="dashicons dashicons-external"></span></a>',
				esc_url( 'https://foo-host.example.com/object-cache/' ),
				esc_html__( 'Learn more about persistent object caching', 'foo-host-object-cache' ),
				/* translators: The accessibility text. */
				esc_html__( '(opens in a new tab)', 'foo-host-object-cache' )
			);

			$test_result['actions'] = "<p>$enable_button</p> <p>$learn_more_link</p>";
		}
		return $test_result;
	},
	20
);

add_action( 'admin_enqueue_scripts', function ( $hook_suffix ) {
	if ( 'site-health.php' !== $hook_suffix ) {
		return;
	}
	wp_enqueue_script( 'foo-host-enable-object-caching', 'https://foo-host.example.com/enable-object-caching.js', [], '0.1', true );
} );
```

The recommended site test result then looks like this:

![image](https://user-images.githubusercontent.com/134745/88086080-a2058080-cb3b-11ea-8f82-1a19641c6811.png)

**Comment by westonruter** [comment]
I've opened a new issue for this and re-scoped it: https://github.com/ampproject/amp-wp/issues/5780
