### ISSUE TITLE
Toggle special effects & animations for AMP Gutenberg blocks

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-wp#1257]
There are a handful of special effects in AMP that can be applied to near-arbitrary divs to enhance the experience on a web page.

This feature request is to include a kind of toggle (maybe a checkbox to start?) for relevant Gutenberg blocks for AMP pages that apply these effects to those blocks.

Effects
- [amp-fx-collection](https://ampbyexample.com/components/amp-fx-collection/) (parallax, fade in, slide in)
- [amp-fx-flying-carpet](https://ampbyexample.com/components/amp-fx-flying-carpet/)

If this needs to be done one at a time, the best blocks to start with would be images and text.

/cc @amedina @westonruter

**Comment by westonruter** [comment]
We currently are decorating core blocks with controls to opt-in to `amp-fit-text`. We could take a similar approach to decorate blocks for other effects.

**Comment by westonruter** [comment]
This came up again in the support forums: https://wordpress.org/support/topic/adding-amp-fx-to-block/

We may want to revisit this when amp-fx is available in a Bento context.
