### ISSUE TITLE
Update amp-mathml block to allow for inline use

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1260]
Gutenberg 3.2 includes support for inline blocks: https://make.wordpress.org/core/2018/07/06/whats-new-in-gutenberg-6th-july/

We can now use this for `amp-mathml` since it supports an `inline` mode.

**Comment by amedina** [comment]
Closing: Stale.

**Comment by westonruter** [comment]
I think we should consider deprecating the `amp-mathml` block entirely. It would make more sense in a blocks plugin.

**Comment by amedina** [comment]
Agree. Separation of concerns  is good and that is block plugins territory.
