### ISSUE TITLE
Add support for inline styles as long as they aren't !important

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1313]
As noted in #1312, [AMP now allows inline `style` attributes](https://www.ampproject.org/docs/design/responsive_amp#add-styles-to-a-page) as long as they do not include `!important` qualifiers. Nevertheless, the AMP plugin continues to have the style sanitizer extract inline styles to combine into `style[amp-custom]`. The reason is that we need to preserve the `!important` styles, which we have to continue extracting to create the higher-specificity selector rules. And if we selectively move such non-important inline styles to `style[amp-custom]` there could be unintended side effects with the cascade. This is something to look into after the 1.0 release.

**Comment by westonruter** [comment]
> The reason is that we need to preserve the `!important` styles, which we have to continue extracting to create the higher-specificity selector rules.

Consider an input HTML document that looks like this:

```html
<style>
p#para {
    color: red !important;
    font-weight: normal !important;
    text-decoration: underline;
}
</style>
<p id="para" style="color: green !important; font-weight: bold; text-decoration: overline;">I should still be green, not bold, and overlined!</p>
```

At the moment, this would get converted into AMP as follows:

```html
<style amp-custom>
:root:not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_) .amp-wp-27ad0ad {
    color: green;
}
:root:not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_) p#para {
    color: red;
    font-weight: normal;
}
:root:not(#_):not(#_):not(#_):not(#_):not(#_) .amp-wp-27ad0ad {
    font-weight: bold;
    text-decoration: overline;
}
p#para {
    text-decoration: underline;
}
</style>
<p id="para" class="amp-wp-27ad0ad">I should still be green, not bold, and overlined!</p>
```

This renders in AMP identically as non-AMP:

![image](https://user-images.githubusercontent.com/134745/65732715-fce75c00-e07f-11e9-8640-7788a82d75ae.png)

However, what if instead of extracting the inline style, we just removed the `!important` qualifier, since the property in a `style` attribute should override any non-important rule, regardless of the selector specificity? So consider this output instead:

```html
<style amp-custom>
:root:not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_) p#para {
    color: red;
    font-weight: normal;
}
p#para {
    text-decoration: underline;
}
</style>
<p id="para" style="color: green; font-weight: bold; text-decoration: overline;">I should still be green, not bold, and overlined!</p>
```

This renders almost right:

![image](https://user-images.githubusercontent.com/134745/65732894-d1b13c80-e080-11e9-865b-e49d93863170.png)

Problem: it should not be bold. The problem is that the transformed `p#para { font-weight: normal !important }` is failing to override the inline style for `font-weight: bold;`.

I was thinking that if all `!important` qualifiers get converted to higher-specificity selectors in the stylesheets, an inline `style` attribute will always override it. And this is true, and this is a problem for when a style rule's `!important` is intended to override a style attribute's non-`!important` property.

**Comment by schlessera** [comment]
The above example is very straight-forward, and we could actually solve this by calculating the "applied CSS" for the `#para` ID.

However, I see no obvious way of completely solving this if we take styles into account that are targeting a more dynamic selector, like a class that gets removed or something like `::hover`.

Would it be worthwhile to look into this for partially solving it where we can reliably deduce the "applied CSS"?

**Comment by westonruter** [comment]
I don't think calculating the applied CSS is feasible for a couple reasons:

1. The reason you shared for dynamic selectors.
2. The performance cost of evaluating a selector to query the document to find the element(s) to apply the styles to.

**Comment by schlessera** [comment]
Well, browsers do this in near real-time, so I'd expect us to be able to at least make partial improvements possible in a cached way in PHP.

I'm fully aware that we won't build a 100% solution, but I think it might be reasonable to expect getting rid of half of the elements we are currently adding to `<style amp-custom>` at least. Given that `<style amp-custom>` has a maximum size, every property we can omit helps make it work on more complex sites.

**Comment by schlessera** [comment]
Also, I think the main problem is indeed the `!important` flag. In case where this is neither in a stylesheet nor an inline style, I assume we can make safe deductions...?

**Comment by westonruter** [comment]
> Well, browsers do this in near real-time, so I'd expect us to be able to at least make partial improvements possible in a cached way in PHP.

Maybe, but I remain skeptical. I'm open to being enlightened.

> Also, I think the main problem is indeed the `!important` flag. In case where this is neither in a stylesheet nor an inline style, I assume we can make safe deductions...?

This is very true. If there is no `!important` in the stylesheets, then this simplifies things. However, unfortunately it is very commonly used, including in WordPress core.

If AMP would just make the 50KB limit flexible based on the actual usage, then this would be a huge help. See https://github.com/ampproject/amphtml/issues/4555. If this were possible, then we could just omit all `.amp-wp-*` style rules from being included in the sum total bytes of the `amp-custom` style, since we now that 100% of them will appear in the page.

**Comment by westonruter** [comment]
Unless AMP beings to allow for certain CSS properties to have `!important`, I don't see this as being feasible in the near future. So I'm closing as maybe later.
