### ISSUE TITLE
Rename phpcs.xml

### ISSUE THREAD

**Issue by GaryJones** [ampproject/amp-wp#1324]
The PHPCS ruleset file distributed with the plugin should be called `phpcs.xml.dist`, or if PHPCS 3.1+ is supported, it can be `.phpcs.xml.dist`.

The `phpcs.xml` (and `.phpcs.xml`) can then be added to the `.gitignore`, so that they can be created locally by contributors who need to override the PHPCS configuration for whatever reason, without them being accidentally committed.

Aside: `phpunit.xml` can also be renamed to `phpunit.xml.dist` as well for the same reason.

**Comment by hellofromtonya** [comment]
Thank you @GaryJones. Would you like to submit a PR to take care of this?

**Comment by GaryJones** [comment]
I've not got time to get the codebase checked and a PR created I'm afraid. `phpcs.xml.dist` support was [added](https://github.com/squizlabs/PHP_CodeSniffer/commit/1e0a8bef8b3386419db9dda93bf62e1f125e3dd4) in PHPCS 3.0, so unless you still need to support PHPCS 2.9 it should be a fairly easy change.

**Comment by hellofromtonya** [comment]
Not a problem @GaryJones.  We’ll take care of it by using the model you laid out in the PWA repo.
