### ISSUE TITLE
Add ability to specify varying template modes (paired vs native) for specific templates

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1355]
At the moment we have a universal setting for paired template mode vs native template mode. However, in some cases there could be a scenario where a site wants to use native AMP mode for all singular posts, but then they want to use paired AMP other content types that do not have 100% parity with AMP, but where the paired mode is still preferable to disabling AMP entirely. 

I envision this ability would only be used on very large sites with a lot of content to help with the transition to AMP. I doubt it would be used by the vast majority of users. The added UI complexity of being able to specify for each template whether AMP should be disabled/paired/native would be a violation of [decisions not options](https://wordpress.org/about/philosophy/), I feel. So exposing this UI could be hidden behind a filter that allows for the additional granularity on sites that need it.

**Comment by amedina** [comment]
@westonruter I think supporting this scenario would be neat as it will offer flexibility to move towards AMP-first content strategies progressively. This is issue is almost 2 years old. What is your current thinking on this?

**Comment by westonruter** [comment]
Nobody has asked for this in 2 years, and the complexity to manage it doesn't seem worth it.
