### ISSUE TITLE
Source Filtering Discovery

### ISSUE THREAD

**Issue by postphotos** [ampproject/amp-wp#1368]
As XWP, I should Investigate and understand the level of effort to filter the error index views by “source” (e.g. listing URLs that have validation errors for a specific plugin). 

_Formal ACs to come._

**Comment by westonruter** [comment]
Thinking more about the level of effort here… if filtering by means of fulltext search of the `post_content` for the plugin source information in the same way that #1373 is looking at the term `description` for a given error `type`.

**Comment by westonruter** [comment]
Doing a `post_content LIKE '%"type":"plugin","name":"jetpack",%'`, for example, should include results that are explicitly identified as coming from Jetpack.
