### ISSUE TITLE
Integrate documentation links to Validation Error details

### ISSUE THREAD

**Issue by postphotos** [ampproject/amp-wp#1401]
**As a developer debugging a surfaced AMP error caught by the plugin, I should the ability to understand what clearly caused this and should have links to relevant documentation (to the new product site, to ampproject.org or ampbyexample.com).** 

Based on the listing in #1360, to appear on the screen in #1364. Shown in mockup [here](https://sketch.cloud/s/xQRzx/all/page-1/isolated-error). Intended to link the product site to the plugin wherever relevant.

- [ ] AC1: Create a way to link the error taxonomy to a given specific URL per error, to be managed by the plugin in a way that can be updated on a per-release basis.
- [ ] AC2: Decide which errors from #1360 already have content for in-depth reading. Similarly, if an error doesn't have a given URL, link them to a fallback URL that explains more about the AMP project and WordPress (perhaps ton the product site.)
- [ ] AC3: As AC1 and AC2 are met, prepare the documentation links for `v1.0`.

**Comment by postphotos** [comment]
The initial user story has been updated here.

**Comment by westonruter** [comment]
Depends on #3817 as we need each tag spec to have a discrete spec name. We will be able to automatically link off to the documentation on amp.dev once the validator spec has been fleshed out with `spec_url` fields for each tag spec.

**Comment by westonruter** [comment]
This really depends on https://github.com/ampproject/amphtml/issues/26033

Each tag spec in AMP should have a URL associated with it. This will help both the AMP validator and the AMP plugin.

**Comment by westonruter** [comment]
> Depends on #3817 as we need each tag spec to have a discrete spec name. We will be able to automatically link off to the documentation on amp.dev once the validator spec has been fleshed out with `spec_url` fields for each tag spec.

Closing that in favor of #4566.
