### ISSUE TITLE
Periodically delete amp_validation_error terms which no longer appear on the site

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1415]
We need to add a cronjob to delete `amp_validation_error` terms that have zero URLs associated with them.

See #1413

**Comment by westonruter** [comment]
Actually, this isn't really obsolete. For trashed posts, they can be deleted with a button or they will be removed after a month via WP Cron. Something similar should be done for `amp_validation_error` taxonomy terms.

There is still a code comment that references this:

https://github.com/ampproject/amp-wp/blob/2984fc9315bbd7c430598c9c75c0148b6527fe27/includes/validation/class-amp-validation-error-taxonomy.php#L1580

**Comment by swissspidy** [comment]
Makes sense to implement 👍 It's annoying to manually clear empty results every so often.

**Comment by amedina** [comment]
Can this be achieved at the time the counter reaches 0? I mean, at the very moment when the 0 value is computed, the orphan error is removed.

**Comment by westonruter** [comment]
That's possible but I think we'd lose out on something important: keeping track of validation errors that contain attributes with variable attributes. For example, if there is a `script` that contains a random string, this will generate a different validation error every time the page is checked and as soon as it is re-checked then the previous errors would have 0 found URLs. Being able to see a list of many such validation errors is important for debugging as it indicates the need for an `amp_validation_error` to normalize the variable bits.
