### ISSUE TITLE
Expose reason for why a validation error is raised

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1420]
When there is a validation error causing an element such as the following to be removed:

```php
<link rel="manifest" href="http://example.com/wp-json/app/v1/web-manifest">
```

There is no corresponding reason _why_ it has been removed. The developer currently has to figure it out on their own. This us unfortunate because the plugin has the reason as part of the validation logic. So in the above example, the validation error is raised due to an illegal protocol being used. The validation error would be detected here:

https://github.com/Automattic/amp-wp/blob/b3e1b4d07dda70c5070d30f7426f849eb3a39823/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L983-L985

And this is due to the spec mandating the `https` protocol for `manifest` links:

https://github.com/Automattic/amp-wp/blob/b3e1b4d07dda70c5070d30f7426f849eb3a39823/includes/sanitizers/class-amp-allowed-tags-generated.php#L7111-L7119

We need to surface this reason when a validation error happens.

We should be reusing the same error codes (and [messages](https://github.com/ampproject/amphtml/blob/5348681bd1a75916bed605495538dd996348133b/validator/validator-main.protoascii#L7061-L7550)) that the validator itself uses.

Compare/contrast with what the plugin is using today:

https://github.com/ampproject/amp-wp/blob/980375ca2eaabad974b1602ab0291645eb0e0f78/includes/validation/class-amp-validation-error-taxonomy.php#L2872-L2949

# Validation Error Codes

Status | Code
---------|------
? | ATTR_DISALLOWED_BY_IMPLIED_LAYOUT
? | ATTR_DISALLOWED_BY_SPECIFIED_LAYOUT
? | ATTR_MISSING_REQUIRED_EXTENSION
? | ATTR_REQUIRED_BUT_MISSING
? | ATTR_VALUE_REQUIRED_BY_LAYOUT
? | BASE_TAG_MUST_PRECEED_ALL_URLS
? | CDATA_VIOLATES_BLACKLIST
? | CHILD_TAG_DOES_NOT_SATISFY_REFERENCE_POINT
? | CHILD_TAG_DOES_NOT_SATISFY_REFERENCE_POINT_SINGULAR
? | CSS_EXCESSIVELY_NESTED
? | CSS_SYNTAX_BAD_URL
? | CSS_SYNTAX_DISALLOWED_DOMAIN
? | CSS_SYNTAX_DISALLOWED_KEYFRAME_INSIDE_KEYFRAME
? | CSS_SYNTAX_DISALLOWED_MEDIA_FEATURE
? | CSS_SYNTAX_DISALLOWED_MEDIA_TYPE
? | CSS_SYNTAX_DISALLOWED_PROPERTY_VALUE
? | CSS_SYNTAX_DISALLOWED_PROPERTY_VALUE_WITH_HINT
? | CSS_SYNTAX_DISALLOWED_QUALIFIED_RULE_MUST_BE_INSIDE_KEYFRAME
? | CSS_SYNTAX_DISALLOWED_RELATIVE_URL
? | CSS_SYNTAX_EOF_IN_PRELUDE_OF_QUALIFIED_RULE
? | CSS_SYNTAX_ERROR_IN_PSEUDO_SELECTOR
? | CSS_SYNTAX_INCOMPLETE_DECLARATION
? | CSS_SYNTAX_INVALID_ATTR_SELECTOR
? | CSS_SYNTAX_INVALID_AT_RULE
? | CSS_SYNTAX_INVALID_DECLARATION
? | CSS_SYNTAX_INVALID_PROPERTY
? | CSS_SYNTAX_INVALID_PROPERTY_NOLIST
? | CSS_SYNTAX_INVALID_URL
? | CSS_SYNTAX_INVALID_URL_PROTOCOL
? | CSS_SYNTAX_MALFORMED_MEDIA_QUERY
? | CSS_SYNTAX_MISSING_SELECTOR
? | CSS_SYNTAX_MISSING_URL
? | CSS_SYNTAX_NOT_A_SELECTOR_START
? | CSS_SYNTAX_PROPERTY_DISALLOWED_TOGETHER_WITH
? | CSS_SYNTAX_PROPERTY_DISALLOWED_WITHIN_AT_RULE
? | CSS_SYNTAX_PROPERTY_REQUIRES_QUALIFICATION
? | CSS_SYNTAX_QUALIFIED_RULE_HAS_NO_DECLARATIONS
? | CSS_SYNTAX_STRAY_TRAILING_BACKSLASH
? | CSS_SYNTAX_UNPARSED_INPUT_REMAINS_IN_SELECTOR
? | CSS_SYNTAX_UNTERMINATED_COMMENT
? | CSS_SYNTAX_UNTERMINATED_STRING
? | DEPRECATED_ATTR
? | DEPRECATED_TAG
? | DEV_MODE_ONLY
? | DISALLOWED_ATTR
? | DISALLOWED_CHILD_TAG_NAME
? | DISALLOWED_DOMAIN
? | DISALLOWED_FIRST_CHILD_TAG_NAME
? | DISALLOWED_MANUFACTURED_BODY
? | DISALLOWED_PROPERTY_IN_ATTR_VALUE
? | DISALLOWED_RELATIVE_URL
? | DISALLOWED_SCRIPT_TAG
? | DISALLOWED_STYLE_ATTR
? | DISALLOWED_TAG
? | DISALLOWED_TAG_ANCESTOR
? | DOCUMENT_SIZE_LIMIT_EXCEEDED
? | DOCUMENT_TOO_COMPLEX
? | DUPLICATE_ATTRIBUTE
? | DUPLICATE_DIMENSION
? | DUPLICATE_REFERENCE_POINT
? | DUPLICATE_UNIQUE_TAG
? | DUPLICATE_UNIQUE_TAG_WARNING
? | EXTENSION_UNUSED
? | GENERAL_DISALLOWED_TAG
? | IMPLIED_LAYOUT_INVALID
? | INCONSISTENT_UNITS_FOR_WIDTH_AND_HEIGHT
? | INCORRECT_MIN_NUM_CHILD_TAGS
? | INCORRECT_NUM_CHILD_TAGS
? | INLINE_STYLE_TOO_LONG
? | INVALID_ATTR_VALUE
? | INVALID_JSON_CDATA
? | INVALID_PROPERTY_VALUE_IN_ATTR_VALUE
? | INVALID_URL
? | INVALID_URL_PROTOCOL
? | INVALID_UTF8
? | MANDATORY_ANYOF_ATTR_MISSING
? | MANDATORY_ATTR_MISSING
? | MANDATORY_CDATA_MISSING_OR_INCORRECT
? | MANDATORY_LAST_CHILD_TAG
? | MANDATORY_ONEOF_ATTR_MISSING
? | MANDATORY_PROPERTY_MISSING_FROM_ATTR_VALUE
? | MANDATORY_REFERENCE_POINT_MISSING
? | MANDATORY_TAG_ANCESTOR
? | MANDATORY_TAG_ANCESTOR_WITH_HINT
? | MANDATORY_TAG_MISSING
? | MISSING_LAYOUT_ATTRIBUTES
? | MISSING_REQUIRED_EXTENSION
? | MISSING_URL
? | MUTUALLY_EXCLUSIVE_ATTRS
? | NON_WHITESPACE_CDATA_ENCOUNTERED
? | SPECIFIED_LAYOUT_INVALID
? | STYLESHEET_AND_INLINE_STYLE_TOO_LONG
? | STYLESHEET_TOO_LONG
? | TAG_EXCLUDED_BY_TAG
? | TAG_NOT_ALLOWED_TO_HAVE_SIBLINGS
? | TAG_REFERENCE_POINT_CONFLICT
? | TAG_REQUIRED_BY_MISSING
? | TEMPLATE_IN_ATTR_NAME
? | TEMPLATE_PARTIAL_IN_ATTR_VALUE
? | UNESCAPED_TEMPLATE_IN_ATTR_VALUE
? | UNKNOWN_CODE
? | VALUE_SET_MISMATCH
? | WARNING_EXTENSION_DEPRECATED_VERSION
? | WARNING_EXTENSION_UNUSED
? | WARNING_TAG_REQUIRED_BY_MISSING
? | WRONG_PARENT_TAG

**Comment by postphotos** [comment]
Related #1360.

**Comment by postphotos** [comment]
@westonruter - Thanks for the suggestion. This is closely related (duplicate?) To AC2 of #1364. 

A few questions:

1) What format do you think this "reasoning" should be? Do you envision this being surfaced in the UI, in the WP-CLI tooling, both?

2) Rereading #1360, I see that @kienstra prepared a list of what the current caught errors are (based on CSS/HTML/JS rules of AMP) - are there additional errors we should be concerned about? FWIW, `https` is not on his list.

3) And would there be a listing somewhere that would explain both all the possible errors?

**Comment by westonruter** [comment]
> This is closely related (duplicate?)

It's not quite a duplicate. This issue is more for the underlying plumbing to get the information to surface. It's not about showing it per se. The reason could be stored in the validation error properties under a `reason` field, alongside `code` and `error_type` (aside: maybe this should just be `type`). Then with this `reason` in hand, the UI could display it.

**Comment by westonruter** [comment]
A reason could be `illegal_protocol`, for example.

**Comment by kienstra** [comment]
**Moving To v1.1 Board**

If it's alright, I'm moving this to the `v1.1` board, as it looks like this won't be part of `v1.0-RC1`.

**Comment by amedina** [comment]
It would be great to have strings a-la Lighthouse audit results, providing information/advice in the context of each error type.

**Comment by westonruter** [comment]
I've started prototyping this.

**Comment by westonruter** [comment]
@schlessera points point, as part of this and #3730, we should capture the validation error messages and wrap them in translation functions as part of the spec PHP generator process, so that the strings can all be translated in WordPress.

**Comment by westonruter** [comment]
With #4401 these error messages (titles) are also displayed in the block editor warnings.
