### ISSUE TITLE
On single error URL page, integrate sources in expanded 'Error' section with 'Sources' column

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#1450]
As @westonruter mentioned, the sources appear in 2 places on the single error URL page:

<img width="1120" alt="sources-2-places" src="https://user-images.githubusercontent.com/4063887/45903357-d2552a00-bdbf-11e8-904e-70930b9d26f9.png">

This can be confusing. 

How can we make this clearer? Maybe expand the `sources` in the 'Error' column on expanding the summary 'Sources' column?

**Comment by kienstra** [comment]
Hi @westonruter,
>If we only had one toggle at the top and this caused all of them to be expanded, then it could also be responsible for inserting the new row for the source information.

Thanks, that's interesting.

Is this roughly what you had in mind?

<img width="1397" alt="expanding" src="https://user-images.githubusercontent.com/4063887/45905160-c66c6680-bdc5-11e8-8769-843ea01e269a.png">

**Comment by kienstra** [comment]
Thanks, @westonruter. Do you think this is something that could wait until the next Beta version?

This might need a similar approach to [the expandable error column](https://github.com/Automattic/amp-wp/pull/1418#issuecomment-420696790), where this added a new `<tr>` below the actual error `<tr>` in the list table, and conditionally displayed it.

**Comment by westonruter** [comment]
Yes, this can wait for the next release.

**Comment by westonruter** [comment]
It will be particularly helpful to be able to use the double-arrow in the table header to expand all the sources to be able to do a quick browser find. Likewise it would be helpful to have the same expansion ability for the error column so you can see all details at once.

Maybe what I suggested where expanding details should collapse sources, and vice-versa, isn't great because maybe you'd want to have all the data spit out onto the page at once.

**Comment by westonruter** [comment]
Additionally: On the error detail view, when we list the single validation error and the associated URLs, we should show the detailed source information as well. I've filed this as #1459.

**Comment by westonruter** [comment]
Part of #2316.

**Comment by jwold** [comment]
Weston > We have a summary of the source validation error and also have the full details. Those are not connected and should be combined. This is a low priority item, and is part of tightening up and improving design of validated URL screen.
