### ISSUE TITLE
Show detailed source(s) on error detail view

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1459]
When looking at an error detail view, where there there are the details for a given error shown followed by the URLs that contain that specific error, and with each URL there is the abbreviated list of sources. Given that we have this information, we should also obtain the full source stack information as is shown with each validation error on the Invalid URL screen:

<img width="1024" alt="untitled 12" src="https://user-images.githubusercontent.com/134745/45964942-f3926200-bfdb-11e8-9cd5-1bf0ec0c5cb9.png">

The list of sources should be a unique list based on the sources for the URLs shown on the current screen.

**Comment by westonruter** [comment]
To be tackled as part of #2316.

**Comment by westonruter** [comment]
This issue is about adding the Source Stack to the single Validation Error screen, whereas currently it is only on the Validated URL screen. The reason why it is only on the latter is that source stacks need the URL context to determine where they came from. Source stack information is only stored with the validated URLs.

If the source stacks from a validation error on multiple URLs are not the same, instead of trying to merge them into one stack, we can instead show a message to say that the user needs to go to the validated URLs to see the source stack in context.

**Comment by jwold** [comment]
Weston > The source info for an error is only captured in the context of a url where the error occurs. So this ticket was about trying to add the sources for all instances to this screen. However, we now are directing users always to go to the validated url screen to do any actions on the validation errors. You go to the validated urls screen to see source, mark as reviewed, remove or keep, so this screen may not be worth it. Let's close it.
