### ISSUE TITLE
Add a way to specify if content is BlogPosting or NewsArticle

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amp-wp#148]
The Google markup spec (https://developers.google.com/structured-data/rich-snippets/articles) requires either of these types. The publisher should be able to choose which one is most relevant to their content.

**Comment by mjangda** [comment]
Added some docs for this as it can be done at a code-level. Will keep it open to consider adding as a setting.

**Comment by westonruter** [comment]
I think this is going to be best handled at the code level, or in a plugin/theme that exposes a setting.
