### ISSUE TITLE
Create new whitelist of AMP component CSS classes used to style based on state

### ISSUE THREAD

**Issue by davisshaver** [ampproject/amp-wp#1490]
`<amp-form>` for example has an `.amp-form-submit-success` selector, any blocks with this selector get shaken out. This is a bit different from the dynamic element whitelist (`dynamic_element_selectors`) as we want the parent selector to be ignored, not the child selector as in the dynamic element whitelist. 

E.g. `.amp-form-submit-success p { display: none }` should have a reduced version as `p { display: none; }` so it doesn't get shaken out.

`<amp-form>` classes include:
- .amp-form-initial
- .amp-form-verify
- .amp-form-verify-error
- .amp-form-submitting
- .amp-form-submit-success
- .amp-form-submit-error

**Comment by davisshaver** [comment]
@weston One clarification, I don't think they can be added to the existing list, as the regex function will be different to reduce the selector. I got hung up trying to get the preg_replace function correct. Whereas `[submit-success]` is in the DOM just hidden, `.amp-form-submit-success` gets added dynamically. So rather than dropping the child and keeping the parent like with the dynamic element selectors, we want to drop the parent and keep the child.

**Comment by westonruter** [comment]
Another class that we need to account for is `amp-viewer`. See #1946.

**Comment by westonruter** [comment]
@davisshaver Please give this a try: #1959.

**Comment by davisshaver** [comment]
@westonruter Sorry it took me some time to respond to this, but I have confirmed the fix using the build in #1959. Thank you!
