### ISSUE TITLE
Native AMP mode error acceptance issue

### ISSUE THREAD

**Issue by fthead9** [ampproject/amp-wp#1508]
It seems there is a disconnect in the description of native AMP or a process isn't working correctly. When checking native AMP in RC1 you are presented with this message: 

"Reuses active theme's templates to display AMP responses but does not use separate URLs for AMP. Your canonical URLs are AMP. AMP-specific blocks are available for inserting into content. Any AMP validation errors are automatically sanitized. "

The assumption is all errors are automatically sanitized and the pages will run in AMP by default without doing anything else. We installed RC1 on 3 test sites (note: previously were running beta.3) and the pages get shaken out, AMP JS components are called but the pages aren't getting served as AMP. 

Only after going into the errors console and manually accepting the sanitizations does the page get served as AMP. It seems like that is how it should work in paired mode but not in native. New pages/posts seem to be automatically sanitized based on the previous acceptance. 

Not sure if this is an actual bug or just a confusing description "Any AMP validation errors are automatically sanitized" but want to point it out as it is not a good user experience.

**Comment by amedina** [comment]
Thanks for raising  this issue; the new documentation for the plugin (in the works) should definitely better explain this kind of scenario. 

If you had a prior version of  the plugin active before, the posts that had been validated already do not get automatically re-validated. This means if those posts have validation errors, they will not be served as AMP until the are re-checked and any existing errors are accepted (sanitized).

**Comment by fthead9** [comment]
I had a feeling it might be related to having the previous plugins installed. Thanks for confirming and agreed, new documentation would be helpful.
