### ISSUE TITLE
Fix default text in Paragraph in the AMP Stories editor

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1523]
**As an editor creating an AMP story, I'd like the default text to appear inside the dashed border that’s shown by default**
- [  ]  _AC1:_  In the interface to add text in a paragraph, the dashed border should be made bigger to fit in the default text or the text content should be made shorter so that the default text content that shows fits within the dashed border
 -  ![screen shot 2018-10-16 at 10 13 46](https://user-images.githubusercontent.com/18579988/47391736-9ed02d00-d6e8-11e8-9305-4a1f5832ddb5.png)

**Comment by jwold** [comment]
Mike will take a stab at this on his own.

**Comment by mehigh** [comment]
This was actually changed due to a Gutenberg update - http://cloud.urldocs.com/9999eb79f633
gutenberg/build/editor/style.css has increased the size of the dotted outline and now it's respecting the size of the element as well.
I suggest this to be closed @alcurrie

**Comment by alcurrie** [comment]
Confirmed: The border now goes around all text, and is the blue 'selected' text as shown here: https://cl.ly/8da2559e0382
