### ISSUE TITLE
Address core AMP plugin Compatibility for AMP stories

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1569]
**As an AMP story creator, I would like to ensure my AMP stories are validated, and error free, and the interface provides me with feedback or validation information, to update my stories to include all required elements for AMP.**
 - [ ] _AC 1:_ Surface AMP Errors and Validation inside the Stories Editor
 - [ ] _AC 2:_  Add conditional validation to meet the AMP Stories spec. e.g.
   - [ ] _AC 3:_ Featured image (validation to require this)
   - [ ] _AC 4:_ Missing properties inside tags
   - [ ] _AC 4:_ Poster image in Video
   - [ ] _AC 4:_ Disallowing Illegal HTML elements
 - [ ] _AC 5:_  Show AMP errors inside the editor to match other post editing. (Note: Currently, the sanitizer errors are not reported in the interface.)
 - [ ] _AC 6:_  Published AMP stories should suppress validation errors, e.g. refine the AMP plugin sanitizers to add missing elements, strip the content that fails validation and alert the user.
    - [ ] _AC 7:_  An author should be able to save and publish AMP stories that have caught errors (as is handled by Gutenberg currently), but content should be sanitized to prevent validation errors from leaking to the front end.

**Comment by miina** [comment]
Dev note: leaving this ticket for continuing later (next week) since this should not directly influence #1571.

**Comment by alcurrie** [comment]
@miina  - I know you're still working on this but in testing last night, the good news is that the AMP stories processes are looking good, but in testing different blocks and embed, etc (ie. YouTube) there were definitely some AMP errors being generated: https://cl.ly/36050d3aa8ca
Just thought ^ some extra egs. might help with troubleshooting.

**Comment by miina** [comment]
Thank you for the additional details, @alcurrie. All these should get fixed within the current PR.

**Comment by westonruter** [comment]
I believe this has been completed.
