### ISSUE TITLE
Preview should display all elements

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1570]
**As an author building an AMP story, I want to be able to preview my progress as I go along**
 ~- [ ] _AC 1:_ Force Cold Cache for preview~ (see discussion below re this issue working in local but not Pantheon test environment) 
 - [x] _AC 2:_  Currently some elements are not showing on preview. Fix Preview so that all elements that are should be visible on the AMP story page/layout are shown in the Preview
- [x]  _AC 3:_  New interface elements added as part of AMP stories should be also shown on preview

**Comment by alcurrie** [comment]
@miina  - this issue's is complete and could be moved into 'to do' but would it be helpful for your dev work to list out the new elements added to make sure that they display in preview, or, can you work on this without the final list of the new elements to be added?

**Comment by miina** [comment]
@alcurrie Thanks for checking.

On new elements: we'll be adding the following new blocks:
- Background Image Grid Layer;
- Background Video Grid Layer;
- Vertical Grid Layer;
- Thirds Grid Layer;

Note that these shouldn't actually change the content of the post and would mainly change the user interface in the editor, meaning that there wouldn't be any new elements added to the source / post content that didn't exist before. However, these should still all work without issues.

**Comment by westonruter** [comment]
Is preview an issue for regular posts as well? This seems like it could be an environment issue. Is it reproducible on a local testing environment?

**Comment by miina** [comment]
@jacobschweitzer I'm also not seeing any issues with the preview at this moment -- the thirds layer seems to display just fine; also the CTA button is displaying as expected. So it looks like the mentioned issues do not exist at this moment. Did you try testing it with assigning different values as well, for example the placement of the blocks within Thirds layer etc.? I tried it briefly and it seemed to work as expected but I didn't do a thorough testing with all the blocks with different settings.

**Comment by jacobschweitzer** [comment]
@alcurrie I did some testing locally again and didn't notice any issues. I'll pass this along and hopefully it gets through QA without any trouble for you.

**Comment by alcurrie** [comment]
@jacobschweitzer  - @cathibosco is seeing an issue with having to clear cache after every preview.  I'm moving this back to in progress, and will try to get some specifics or a screen cast to show issue. 

Cathi can you add any specifics here?

**Comment by westonruter** [comment]
On which environment(s) is the issue being observed?

**Comment by miina** [comment]
@westonruter:
@cathibosco was testing this on the amp-stories development environment. Also, as far as I understood the issue came out well with adding and modifying animation settings for blocks/layers.

For example if you add an Animation type and preview it; and then change the animation type and click preview again, it still shows the previous animation type.

The environment has `amp-stories` branch; Gutenberg 4.5.1 and WP 4.9.8.

**Comment by westonruter** [comment]
But which _server_ environments is this being observed? Only on Pantheon? Also on local?

**Comment by miina** [comment]
Just tested -- locally it's refreshing correctly and displaying as expected!

**Comment by alcurrie** [comment]
@cathibosco  -can you provide some more examples/screencasts of where preview is not working for you?

**Comment by alcurrie** [comment]
I'm definitely still seeing issue with caching in preview, ie. I make changes, update, and go to preview.  On preview, the changes don't display.  I reload the page and the updates display on preview.

**Comment by westonruter** [comment]
I'm gonna confused as to why this would be. I don't believe that Varnish cache is active on the multidev environments. Also, the the user is logged in anyway, so it should pass through everything. Only thing I can think of is a database latency issue, but we haven't noticed that being a problem elsewhere on this env, have we? /cc @ataylorme

**Comment by ataylorme** [comment]
> I'm gonna confused as to why this would be. I don't believe that Varnish cache is active on the multidev environments. 

Varnish is active but in a less aggressive way than test/live. For example, CSS and JS are not cached.

> Also, the the user is logged in anyway, so it should pass through everything

Correct, Varnish is not active for authenticated users

**Comment by alcurrie** [comment]
I have confirmed with @cathibosco and also found in my testing in the demo site, that the Preview is accurate, and as long as the user clears cache the preview is accurate.  Also, as noted this is not repeatable in a local environment but only on the Pantheon demo site. 

@westonruter  / @miina Based on that, we are recommending marking this issue as 'done' for the 'display all Elements' core deliverable and creating a backlog issue to iterate further on caching in a future scope if it is determined to be more than a Pantheon issue.
