### ISSUE TITLE
Advanced AMP Stories Demo

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1571]
**As a potential new AMP stories user I would like to see an Advanced AMP Stories Demo highlighting the new features and improvements and showcasing the improved user workflow.**
 - [ ] _AC 1:_ Demonstrate the engaging and nice looking story-telling experience
 - [ ] _AC 2:_ Showcase what can be done with the new AMP Stories workflow and features.

**Comment by jwold** [comment]
The primary thing we should showcase is the work shown here: https://github.com/Automattic/amp-wp/issues/1564

**Comment by alcurrie** [comment]
@jwold @cathibosco and I met last and talked about a high level outline for what could be included in the demo and Joshua captured notes on some initial ideas: 
For discussion, here are some elements that could be part of the demo
1. **Background and context of AMP Stories prior to the 1.5 update**
2. **AMP 1.5 Improvements to the Story Creation workflow**
Demo the new workflow using Block Navigation from Gutenberg as the foundation for layer and block management, and the interface improvements to make the process of building AMP stories clearer and more intuitive
Here are some initial areas that we could demo 
- Parent/child relationship is easier to see and navigate
- Seeing  what's on layers is easier now (selected state and blurring of non-active content) 
- Selecting and moving layers forward and back
- Easier to Add a new page or a new layer
- Quick start creating AMP stories with default layer
- New layer types with default content
