### ISSUE TITLE
Essential User Manual (wiki page)

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1572]
**As a new AMP stories user I want a user manual that will introduce and provide help for understanding the capabilities of AMP stories and getting started using the tool**

 - [ ] _AC 1:_  Create an Essential User Manual (wiki page) which includes content in the following sections: 
     - [ ] _AC 2:_  Introduction to the tool
     - [ ] _AC 3:_  Brief Gutenberg context
     - [ ] _AC 4:_  References to Gutenberg docs
     - [ ] _AC 5:_  Summary of capabilities
     - [ ] _AC 6:_  Getting started guide
     - [ ] _AC 7:_  Examples of how to use each of the features (i.e. how to add a background image, etc).

**Comment by jwold** [comment]
Work on this has begun here: https://github.com/Automattic/amp-wp/wiki/Essential-user-manual

**Comment by jwold** [comment]
I believe this is good for now.
