### ISSUE TITLE
Add a filter that to ensure that other plugins won't be able to turn off the Gutenberg for AMP Stories post type

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1573]
**As a site owner using AMP stories on my site, I want to make sure that other plugins won't be able to turn off Gutenberg for the AMP stories post type**
 - [ ] _AC 1:_  Add a filter to ensure other plugins won't be able to turn off Gutenberg for the AMP stories post type  see. https://make.wordpress.org/core/2018/10/30/block-editor-filters/
     - i.e.  
```
add_filter( 'use_block_editor_for_post_type', function( $use_block_editor, $post_type ) {
    if ( 'amp_story' === $post_type ) {
        $use_block_editor = true;
    }
    return $use_block_editor;
}, PHP_INT_MAX );
```
 - [ ] _AC 2:_   Add a similar `use_block_editor_for_post_type` filter as well

**Comment by swissspidy** [comment]
There's no option for Classic Editor anymore 💪 👍
<img width="451" alt="Screenshot 2019-05-14 at 11 40 51" src="https://user-images.githubusercontent.com/841956/57723295-2ce81280-763d-11e9-9670-7195ee3c133a.png">
