### ISSUE TITLE
Add custom category for AMP-specific editor blocks.

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#1598]
It's now possible to add custom categories to editor (Gutenberg) blocks in addition to the default categories ("Common", "Widgets", etc.):

https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#managing-block-categories

Would be useful to add a separate category for AMP blocks so that they would be grouped more appropriately within Inserter.

**Comment by westonruter** [comment]
Is this still relevant?

**Comment by amedina** [comment]
It seems this would this serve general AMP content creation for the case when a site is in Transitional or Native mode and the content creator wants to add only AMP compatible blocks.

**Comment by miina** [comment]
Not sure if this is still relevant, most of the AMP blocks are embed blocks and these are under the Embeds Category which seems to be accurate.

There are two blocks under the Common Category: MathML and Timeago, and one under widgets (Latest Stories, which suit be good under the widgets).

If it's okay to leave MathML and Timeago under the Common Category then we could close this issue.

**Comment by swissspidy** [comment]
> the case when a site is in Transitional or Native mode and the content creator wants to add only AMP compatible blocks

If you are in Transitional mode, the AMP blocks are not available for insertion at all.

If you are in Native mode, then as a user I don't care about AMP or non-AMP blocks. They're just blocks I can insert.

> If it's okay to leave MathML and Timeago under the Common Category then we could close this issue.

Agreed.
