### ISSUE TITLE
Add more color options to blocks

### ISSUE THREAD

**Issue by jwold** [ampproject/amp-wp#1617]
Currently in the AMP Stories editor there is no way to add gradients to the block color options. We may want to investigate ways to do this, and see if that should be included in AMP Stories, or whether the task best belongs to a custom plugin, for example: https://github.com/lubusIN/block-background.

**Comment by jwold** [comment]
@alcurrie this would be a great one for our next phase!

**Comment by swissspidy** [comment]
Closing as we now have basic gradient support in AMP stories.
