### ISSUE TITLE
Unused variable warning in add_twentynineteen_image_styles

### ISSUE THREAD

**Issue by paulschreiber** [ampproject/amp-wp#1653]
In `add_twentynineteen_image_styles()`, the `$args` variable is passed to the anonymous function, but never used in that function.
https://github.com/Automattic/amp-wp/blob/develop/includes/sanitizers/class-amp-core-theme-sanitizer.php#L1094

**Comment by westonruter** [comment]
@paulschreiber a PHP warning or a PHPCS warning?

**Comment by paulschreiber** [comment]
PHPCS unusued variable warning.

**Comment by westonruter** [comment]
Feel free to open a PR to the `1.0` branch. Please make sure to branch off of `1.0`.
