### ISSUE TITLE
AMP stories pages should default to show all blocks/layers unblurred both when page is selected and when no blocks/elements are selected

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1696]
**_Issue:_ When the user views scrolls/views through viewing multiple AMP Story pages in an unpublished AMP story, any unselected AMP stories pages show as blurred**

_Test Steps_
See screencast: https://v.usetapes.com/iAcIOMPTKP

**Expected**
AMP stories pages should default to show all blocks/layers unblurred both when page is selected and when no blocks/elements are selected

_Actual_
Prior to publishing the AMP Story, any story page not currently selected shows as blurred. See screencast: https://v.usetapes.com/iAcIOMPTKP

**Comment by alcurrie** [comment]
@mehigh @miina  - not sure if this is a FE or BE fix, but as this is a demo-blocker issue it would be great if this could be prioritized for AMP stories.

**Comment by miina** [comment]
Thanks @alcurrie -- looking into it now.

**Comment by alcurrie** [comment]
Thanks @miina  - I've taken Mike off the assigned list.

**Comment by miina** [comment]
This was fixed within #1702.
