### ISSUE TITLE
Add layer interface is no longer appearing above block navigation for when editing 'published' AMP stories being edited

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1698]
Issue: After the latest update to AMP stories, I'm no longer seeing the Add Layer interface appearing above the Block Navigation when going back in to edit 'published' stories

*Test Steps*
Published Story, that is being edited:   https://cl.ly/4785c167f5f0

*Expected*
Add Layer should appear above the Block navigation in the edit interface, when any story page is selected when a user is editing a new unpublished, or a previously published AMP story

*Actual*
Add Layer interface does not appear when editing an AMP story that has previously been published.   https://cl.ly/4785c167f5f0

**Comment by alcurrie** [comment]
@cathibosco  @jwold - just a heads up that this may impact demo.  

@miina  and @mehigh  - I'm not sure whether this will need a FE or BE fix, so I've assigned you bot. Please let me know if I should re-assign to someone else.

**Comment by miina** [comment]
@alcurrie Thanks for the issue, this is related to #1696 and seems to come from the same problem. Looks like checking for inner selected blocks isn't working properly in Gutenberg anymore.

**Comment by alcurrie** [comment]
Thanks for the update @miina  - should I leave this with you then and take Mike off the assigned list?

**Comment by miina** [comment]
@alcurrie Yes, sounds good, thanks.
