### ISSUE TITLE
compatible themes/plugins

### ISSUE THREAD

**Issue by ineagu** [ampproject/amp-wp#1718]
@westonruter there is any plans for listing themes/plugins that work by default with ampwp, besides the core ones that have been bundled?  We added this on https://wordpress.org/themes/neve/, and wondering :)

**Comment by westonruter** [comment]
Yes, there is! We will be adding a submission form to amp-wp.org to submit additional themes and plugins to be featured. It looks like your theme is compatible at a basic level, but I encountered problems when I tried to apply the "pre-built websites with 1-click installation". When trying to apply Neve 2018, for example, there was too much CSS being added to the page from Elementor, causing the page layout to break. I should think that all of the theme's features should be AMP compatible. Nevertheless, I suppose it could be argued that your theme is compatible but the plugins it depends on are not. While we want to work with plugins in the ecosystem to add AMP compatibly, perhaps you should mark these the sites as not being AMP-compatible if the non-classic mode is active.

**Comment by ineagu** [comment]
Hey, thanks for feedback, got your point, some people use the as blog only ( quite a lot), while others use the landing pages, next weeks we should have a gutenberg based primary landing page that should work with AMP.

Either way we'll submit the form and work from there :). btw we are working on our most popular theme to have the frontpage AMP compatible too, however the css tree-shaking cause some problems, there are ways to disable it for some pages/scripts? If you can point me to the doc would be great, thanks a lot !

**Comment by westonruter** [comment]
What problem is caused by tree shaking? May be a bug that needs to be fixed.
