### ISSUE TITLE
Plugin Conflict: Also using Give plugin currently creates 500 server error when viewing /wp-admin/

### ISSUE THREAD

**Issue by KZeni** [ampproject/amp-wp#1720]
I’m getting a 500 server error when trying to access the site admin after updating AMP to the latest version while also running the current version of https://wordpress.org/plugins/give/. Turns out that there’s a conflict with Give which my sites were running into. I also believe the issue could be specific to PHP 7.x (a matter of the number of variables provided to a function vs. what was expected).

I’ve opted to disable AMP to avoid this error until this is fixed since Give is more important to the site than AMP is.

This issue has also been reported at https://wordpress.org/support/topic/http-error-500-after-updating/ (topic was marked as resolved by the topic author after finding they could disable Give, but that doesn't mean the underlying issue has been resolved & those that want to use Give and AMP together are still having the issue.)

**Comment by Jany-M** [comment]
Same here, but it might look like this needs a better fallback/failsafe, not just Give conflicting.

```
[11-Dec-2018 15:24:30 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function AMP_Validated_URL_Post_Type::filter_the_title_in_post_list_table(), 1 passed in /var/www/vhosts/site.com/httpdocs/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /var/www/vhosts/site.com/httpdocs/wp-content/plugins/amp/includes/validation/class-amp-validated-url-post-type.php:1897
Stack trace:
#0 /var/www/vhosts/site.com/httpdocs/wp-includes/class-wp-hook.php(286): AMP_Validated_URL_Post_Type::filter_the_title_in_post_list_table('#20SECONDS')
#1 /var/www/vhosts/site.com/httpdocs/wp-includes/plugin.php(203): WP_Hook->apply_filters('#20SECONDS', Array)
#2 /var/www/vhosts/site.com/httpdocs/wp-content/plugins/give/includes/admin/shortcodes/abstract-shortcode-generator.php(301): apply_filters('the_title', '#20SECONDS')
#3 /var/www/vhosts/site.com/httpdocs/wp-content/plugins/give/includes/admin/shortcodes/abstract-shortcode-generator.php(153): Give_Shortcode_Generator->generate_post(Array)
#4 /va in /var/www/vhosts/site.com/httpdocs/wp-content/plugins/amp/includes/validation/class-amp-validated-url-post-type.php on line 1897
```

**Comment by kienstra** [comment]
Hi @KZeni,
Thanks for bringing this up, and for opening #1725. I've also opened https://github.com/impress-org/give/pull/3899.

**Comment by westonruter** [comment]
Closing since PRs merged for AMP plugin.
