### ISSUE TITLE
Jetpack/Wordpress Pixel for AMP page is not added, after the last update

### ISSUE THREAD

**Issue by bantilan** [ampproject/amp-wp#1722]
Hi,

It seems the pixel for tracking the views for jetpack is not added on the latest update for AMP. when i check the google cache amp, there is no wordpress pixel added.

**Comment by dartiss** [comment]
This may explain what I'm seeing - Jetpack stats are not tracking AMP pages anymore

**Comment by bantilan** [comment]
@dartiss , I temporarily fix it by adding this code in the templates/footer.php

`<?php
/**
 * Footer template part.
 *
 * @package AMP
 */
function jetpack_amp_build_stats_pixel_url() {
	global $wp_the_query;
	if ( function_exists( 'stats_build_view_data' ) ) { // Added in <https://github.com/Automattic/jetpack/pull/3445>.
		$data = stats_build_view_data();
	} else {
		$blog     = Jetpack_Options::get_option( 'id' );
		$tz       = get_option( 'gmt_offset' );
		$v        = 'ext';
		$blog_url = wp_parse_url( site_url() );
		$srv      = $blog_url['host'];
		$j        = sprintf( '%s:%s', JETPACK__API_VERSION, JETPACK__VERSION );
		$post     = $wp_the_query->get_queried_object_id();
		$data     = compact( 'v', 'j', 'blog', 'post', 'tz', 'srv' );
	}

	$data['host'] = isset( $_SERVER['HTTP_HOST'] ) ? sanitize_text_field( wp_unslash( $_SERVER['HTTP_HOST'] ) ) : ''; // input var ok.
	$data['rand'] = 'RANDOM'; // AMP placeholder.
	$data['ref']  = 'DOCUMENT_REFERRER'; // AMP placeholder.
	$data         = array_map( 'rawurlencode', $data );
	return add_query_arg( $data, 'https://pixel.wp.com/g.gif' );
}
/**
 * Context.
 *
 * @var AMP_Post_Template $this
 */
?>
<footer class="amp-wp-footer">
	<div>
		<h2><?php echo esc_html( wptexturize( $this->get( 'blog_name' ) ) ); ?></h2>
		<p>
			<a href="<?php echo esc_url( esc_html__( 'https://wordpress.org/', 'amp' ) ); ?>">
				<?php
				// translators: %s is WordPress.
				//echo esc_html( sprintf( __( 'Powereds by %s', 'amp' ), 'WordPress' ) );
				?>
			</a>
		</p>
		<a href="#top" class="back-to-top"><?php esc_html_e( 'Back to top', 'amp' ); ?></a>
	</div>
</footer>
<amp-pixel src="<?php echo esc_url( jetpack_amp_build_stats_pixel_url() ); ?>"></amp-pixel>`

**Comment by dartiss** [comment]
Continuation of discussion at https://wordpress.org/support/topic/v1-0-has-broken-jetpack-stats-tracking/

**Comment by westonruter** [comment]
I can see what the problem is. The `Jetpack_AMP_Support::jetpack_is_amp_request()` method is defective.

A quick workaround until it is fixed is to add this to your plugin or theme:

```php
add_filter( 'jetpack_is_amp_request', function() {
    return did_action( 'parse_query' ) && function_exists( 'is_amp_endpoint' ) && is_amp_endpoint();
} );
```

I'll open a PR in Jetpack with a permanent fix.

**Comment by dartiss** [comment]
I've applied it to one of my sites and I'll let you know if it resolves the issue.

If this is applied to Jetpack will having this patch as well cause problems?

**Comment by westonruter** [comment]
PR has been opened for Jetpack: https://github.com/Automattic/jetpack/pull/10918

Please test and provide feedback there.
