### ISSUE TITLE
Amp included bbpress ?

### ISSUE THREAD

**Issue by tryazi** [ampproject/amp-wp#1724]
![amp](https://user-images.githubusercontent.com/45657726/49718474-3f63b780-fc6b-11e8-8d65-f7f3cac763e6.png)

Amp plugin supports for bbress topics. However, we want to view the topics and responses.

It doesn't make it your plugin. The screenshot is better than the plugin. We expect you to update your plugin this way.

The response and the subject amp should also be displayed.

**Comment by kienstra** [comment]
Hi @tryazi,
Thanks for bringing this up.

>The screenshot is better than the plugin. We expect you to update your plugin this way.

Is that screenshot from this AMP plugin? I haven't seen it.

**Comment by tryazi** [comment]
The image of this better amp plugin. Your plugin contains only the subject. No response.

If the better amp plugin provided a neat view, I would use it. My expectation from your plugin is to resolve this issue and make it available.
![adfsf](https://user-images.githubusercontent.com/45657726/49786285-50c4c680-fd34-11e8-8d90-6db3fc978f83.png)

**Comment by kienstra** [comment]
>The image of this better amp plugin
OK, so the image is from another AMP plugin?

And it sounds like our plugin does have the subject, and you'd like it to also have a response?

**Comment by tryazi** [comment]
The first image is yes.

**Comment by westonruter** [comment]
We haven't yet looked into plugin compatibility with bbPress. Improving support with themes and plugins is something we'll be moving into now in the new year.

**Comment by tryazi** [comment]
Okay, I'il be waiting for new developments. Can be inspired by the other plugin.

We can close the subject

@kienstra @westonruter
