### ISSUE TITLE
For Thirds template the block placement in the editor does not reflect the actual placement of the block

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1729]
**The block placement for blocks in the thirds template in the editor does not reflect the actual placement of the block as it will be in preview and on publication**

_Test Steps/issue_
https://cl.ly/90312a375eca

**Expected**
The block position on AMP story editor  the layer/story should be accurate ie. a block set to bottom third should show in the bottom third of the page in the editor as well as 

**Actual**
For Thirds template in AMP Stories  the block placement in the editor does not reflect the actual placement of the block in the story page. NB: The placement of the Thirds blocks in Preview and on publish is correct per the settings.

**Comment by miina** [comment]
@alcurrie This ticket should be ready for QA as well now.

**Comment by alcurrie** [comment]
In retesting today, the issue with the positioning of elements within the thirds template, based on Upper third, Middle Third, Lower Third is confirmed resolved. https://cl.ly/3158c77184c2
