### ISSUE TITLE
Create a tool/user flow for a new user installing the AMP Plugin for the First time

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1730]
Consider developing a workflow to take a new user through installing the plugin for the first time, and give them guidance about their theme, installed plugins and how to interpret and handle issues. 

_Some ideas/examples_: 
If there are JS errors, there’s a good chance the theme just won’t work. Offer feedback/recommendations i.e.  “Hey there! We took a look at your theme and it looks like there are some issues.. You can use the validation tool to fix the issues or check out themes that provide AMP compatibility out of the box”

**Comment by alcurrie** [comment]
This recommendation was based on feedback from @sirjonathan based on his initial experience installing the plugin on his own site.

**Comment by westonruter** [comment]
Closing as @jwold is creating new issues for this.
