### ISSUE TITLE
Add a notice that informs users that their active theme and plugins may not be fully compatible with the new native/paired modes

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1732]
**As a site owner installing the AMP plugin for the first time, I'd like to see a notice that lets me know if my active theme and/or plugins may not be fully compatible with the new native/paired mode**

- [ ] _AC 1:_ After that AMP 1.0 plugin is installed, check whether the current active theme and all active plugins, are compatible with native/paired AMP modes
- [ ] _AC 2:_ If the active theme and/or 1 or more installed plugins are not confirmed to be compatible, display a notice prominently in the WP Admin informing the user that their active theme and/or plugins may not be fully compatible with the new native/paired mode
    - [ ]  _AC 3:_ Notice should specify theme name, and all plugins not confirmed to be compatible.

**Comment by alcurrie** [comment]
@westonruter  - as discussed I added issue and  high level AC to v 1.0.2 milestone

**Comment by westonruter** [comment]
We should also add a notice to the readme that makes clear that custom JavaScript will be stripped from AMP responses. So if they have ads that require JS, then they'll need to use `amp-ad` wherever an ad placement occurs.

**Comment by westonruter** [comment]
Related: #2313. We should highlight the AMP-compatible themes and plugins from the start prior to installation.

Also related is building a compatibility database of plugins that are known to be compatible or incompatible.

**Comment by jwold** [comment]
@westonruter is this still a relevant issue with the new work we've done on the onboarding wizard?

**Comment by westonruter** [comment]
Correct. This is obsolete, or it will be obsolete when the site scanning features are implemented in #4719/#4795.
