### ISSUE TITLE
AMP errors on Google Search Console

### ISSUE THREAD

**Issue by otpidusprime** [ampproject/amp-wp#1739]
I had a user report Google Search Console giving this error:

`The tag 'head > style[amp-boilerplate]' is missing or incorrect, but required by 'noscript > style[amp-boilerplate]`

Digging into that it – came across this: https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md

I gave the code mentioned in that GitHub page to them and suggested them to use the insert headers and footers plugin: https://wordpress.com/plugins/insert-headers-and-footers on their WordPress.com site, to add it to the header area.

After adding that, they got these bunch of errors on the Search Console:

```
The tag 'head > style[amp-boilerplate]' is missing or incorrect, but required by 'noscript > style[amp-boilerplate]'.

Not Started
1
Error	Wrong parent tag 'body' of javascript tag 'amp-social-share extension .js script'

Not Started
1
Error	Wrong parent tag 'body' of javascript tag 'amp-iframe extension .js script'

Not Started
1
Error	The mandatory tag 'noscript enclosure for boilerplate' is missing or incorrect.

Not Started
1
Error	The mandatory tag 'head > style[amp-boilerplate]' is missing or incorrect.

Not Started
1
Error	The tag 'iframe' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-iframe'?

Not Started
1
Error	Wrong parent HTML tag 'body' of tag 'link rel=canonical'

Not Started
1
Error	Wrong parent HTML tag 'body' of tag 'style amp-custom'

Not Started
1
Error	Wrong parent tag 'body' of javascript tag 'amphtml engine v0.js script'

Not Started
1
Error	The tag 'noscript > style[amp-boilerplate]' may only appear as a descendant of tag 'head'.
```

Any advice on this is appreciated.

Thanks in advance for looking.

**Comment by amedina** [comment]
How is this related to the use of this plugin?

**Comment by otpidusprime** [comment]
Since the errors mentioned `amp` I thought it might be related to the use of the plugin.

I also thought it might be due to a plugin conflict, but wasn't sure about it and therefore wanted to ask here.

So this is Search Console then and not the plugin?

**Comment by amedina** [comment]
Correct; this is not related to the use of this plugin.
