### ISSUE TITLE
Change label of Error Index page "Status" column

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#1741]
Feedback from the AMP team suggests that we should change the label of the status for validation errors from "Status" to "Sanitization Status" reflecting the fact that actions taken by the user refer to the sanitization actions of the plugin, and not the error themselves. 

/cc @pbakaus

**Comment by westonruter** [comment]
That string is a bit long for the column. Can we just do "Sanitization"?

**Comment by alcurrie** [comment]
Should this task be added to the 1.0.2 milestone?

**Comment by westonruter** [comment]
If @amedina confirms the shorter column label.

**Comment by amedina** [comment]
Confirmed. Let's go with 'Sanitization' as a replacement for 'Status'

**Comment by westonruter** [comment]
What would we do with the Status dropdown?

![image](https://user-images.githubusercontent.com/134745/50021063-bca16c00-ff8c-11e8-9c18-3b7356d2f07b.png)

“All Sanitizations” no me cae bien.

**Comment by westonruter** [comment]
Done in #3630.
