### ISSUE TITLE
Resolve issue re.  1.0.1 update release notice not displaying on sites using the AMP plugin

### ISSUE THREAD

**Issue by alcurrie** [ampproject/amp-wp#1744]
**Issue: There is no notification of the available plugin 1.0.1 release update for the AMP Plugin**

*Expected*
For a site running the AMP plugin 1.0 release, the admin user should see a notification, ie on the plugins listing page that there is an update version of the plugin available

*Actual*
The notification is not displaying:
<img width="1091" alt="screen shot 2018-12-14 at 1 37 05 am" src="https://user-images.githubusercontent.com/18579988/50003797-e77ec680-ff72-11e8-9fec-80568dac45f7.png">

**Comment by alcurrie** [comment]
@amedina  - I added this issue to the v1.0.2 milestone

**Comment by westonruter** [comment]
@alcurrie on which site was this seen? The prompt for plugin update is not part of the AMP plugin. It is part of WordPress core. There's nothing special that the AMP plugin should be doing here.

**Comment by kienstra** [comment]
Using the `amp.zip` file from the [1.0-RC3 release](https://github.com/ampproject/amp-wp/releases/tag/1.0-RC3), like in the screenshot above, this notice appeared as expected locally:

<img width="1286" alt="update-notice-appearing" src="https://user-images.githubusercontent.com/4063887/50018258-4143b880-ff94-11e8-89db-ce1a4cfe8031.png">

**Comment by westonruter** [comment]
It could be that the environment had a read-only filesystem due to being in Git mode. In this case I believe the update prompts are not presented. Or that they aren't presented in non-dev environments on Pantheon.
