### ISSUE TITLE
How to disable Gravatar author image?

### ISSUE THREAD

**Issue by nabtron** [ampproject/amp-wp#1751]
How can we prevent amp from loading the gravatar image for the author? 

P.S. is it necessary for amp to have the author image? If yes then how can we replace it with a custom one.

Thanks.

**Comment by westonruter** [comment]
The gravatar is being output in this template partial: https://github.com/ampproject/amp-wp/blob/1.0.1/templates/meta-author.php

So you can override `templates/meta-author.php` in your theme, by defining an empty file `amp/meta-author.php`.

Note that this only applies to [classic templates](https://amp-wp.org/documentation/how-the-plugin-works/classic-templates/) and not the new [native/paired modes](https://amp-wp.org/documentation/how-the-plugin-works/amp-plugin-serving-strategies/).
