### ISSUE TITLE
Plugin incompatibility  Cache

### ISSUE THREAD

**Issue by tryazi** [ampproject/amp-wp#1771]
Hello there
I'm using the Premium Fastest cache plugin. This plugin works properly with the amp plugin.

But when the two work together, wp-admin is too bad. Very slow. I need to deactivate one of the two.

I reported the status to the add-on maker. I think you should take a look at this.

**Comment by westonruter** [comment]
Please share the URL to the caching plugin.

**Comment by tryazi** [comment]
https://tr.wordpress.org/plugins/wp-fastest-cache/

**Comment by tryazi** [comment]
Where can I find this code? I want to convert to automatic ads

https://cdn.ampproject.org/v0/amp-ad-0.1.js

@westonruter

**Comment by westonruter** [comment]
I don't understand. If you want to use [`amp-auto-ads`](https://www.ampproject.org/docs/reference/components/amp-auto-ads), then use `<amp-auto-ads>` in your template instead of `<amp-ad>`.

**Comment by tryazi** [comment]
Thank you. I did this.
