### ISSUE TITLE
How to add Custom Menu or Related Posts?

### ISSUE THREAD

**Issue by nabtron** [ampproject/amp-wp#1772]
How can we add related posts or custom menu at the end of the post content? 

Add a widget sidebar hook for AMP pages to show them or anything else.

**Comment by westonruter** [comment]
The easiest way is to switch from Classic to Paired mode or Native mode. You can then use your normal theme in AMP, and the menus and widgets that are shown in your normal theme's templates. You can do this using the Twenty Fifteen through Twenty Nineteen core themes which have been tested. Other themes should work as well, but some functionality won't work (in particular, themes that depend on custom JavaScript). 

You can see an example of Twenty Fifteen with menus and related posts at: https://make.xwp.co/2018/12/01/amp-plugin-release-v1-0-rc4/?amp

The related posts are powered by Jetpack's Related Posts module with this additional helper plugin to add AMP compatibility (which should eventually be merged into Jetpack as well): https://gist.github.com/westonruter/1515ce1bae788e6d52d1a94ddd61fb59

**Comment by nabtron** [comment]
I've added related posts by using hook in the pure amp theme anyway. I'll support it as a free plugin on github for anyone who needs it (along with few other required tweaks like removing "powered by wordpress" from footer and gravatar removal.

Here is the override plugin: https://github.com/nabtron/wp-amp-override
