### ISSUE TITLE
Jetpack sharing buttons displaying as links.

### ISSUE THREAD

**Issue by RealCarFax** [ampproject/amp-wp#1779]
I have two examples of the issue at hand:

**First example**
When the post is viewed normally, the sharing buttons appear like this:
<img width="576" alt="screen-shot-2018-12-09-at-1-15-05-pm" src="https://user-images.githubusercontent.com/7827472/50406858-5d1c3b00-079a-11e9-9326-3c81dcfa3e5f.png">

When we view the post via AMP, they appear as links instead of icons/buttons:
<img width="293" alt="screen-shot-2018-12-09-at-1-14-53-pm" src="https://user-images.githubusercontent.com/7827472/50406860-69a09380-079a-11e9-84b2-1e0b2200b74c.png">

**Second example**
When the post is viewed normally, the sharing buttons appear like this:
<img width="399" alt="screen shot 2018-12-24 at 4 39 34 pm" src="https://user-images.githubusercontent.com/7827472/50406869-850b9e80-079a-11e9-8d72-de30695f5d81.png">

When we view the post via AMP, they appear as links instead of icons/buttons:
<img width="128" alt="screen shot 2018-12-24 at 4 36 18 pm" src="https://user-images.githubusercontent.com/7827472/50406871-889f2580-079a-11e9-9a77-80ca57660f16.png">

It appears the issue is present regardless of the type of Jetpack sharing buttons they're using on the site (official buttons, icon only, icon and text, text only).

**Comment by westonruter** [comment]
Jetpack sharing buttons are working as expected for me: https://weston.ruter.net/2018/12/18/creating-gutenberg-blocks-without-a-build-step-via-htm/

However, I have a patch applied to fix a bug in the current version of Jetpack. You may want to try applying the changes from this PR: https://github.com/Automattic/jetpack/pull/10945
