### ISSUE TITLE
Normal Pages being redirected to amp pages automatically

### ISSUE THREAD

**Issue by myleshyson** [ampproject/amp-wp#1783]
For some reason my normal pages are being automatically redirected to the amp version using paired mode. I should only be taken to the amp version using the ?amp or /amp/ url in paired mode correct? I have the default twentynineteen theme installed and have tried to reinstall the plugin with no avail. 

My guess is there is some post meta data set for some reason that automatically redirects all my pages to the amp version regardless of the url.

Even weirder, on the live site it actually redirects to a completely different ampproject cdn url. I couldn't find where to change that or remove that. 

Again the setting is paired mode, which by description should only redirect if given the /amp or ?amp at the end of the url.

What do I need to change in order to get these pages to route like normal? Thanks.

**Comment by westonruter** [comment]
In the paired mode there should never be a redirect from the non-AMP version to the AMP version. Also, the plugin never redirects away from your origin, so you should not see the AMP CDN when accessing your normal site URLs.

Perhaps there is a conflict with another of your plugins?

**Comment by myleshyson** [comment]
Hmm ok. I just deactivated every other plugin except for amp and it's still doing it.  And it does it regardless of whether its in paired mode or classic mode. The only way to stop it for now is to just disable the amp plugin.

**Comment by westonruter** [comment]
Ok, thanks for testing that. 

What is an example non-AMP URL that shows this problem?

I suggest looking for instances of calls to redirect functions like:

https://github.com/ampproject/amp-wp/blob/19f1f246c613814d86498d30c8ee05e7f5c277fe/includes/class-amp-theme-support.php#L292

And for each one, replace them with something like `die( __FILE__ . ':' . __LINE__ )`. This will then indicate where the plugin is doing the redirect.

**Comment by westonruter** [comment]
Of better, add a new snippet to your theme's `functions.php` like this:

```php
add_filter( 'wp_redirect', function() {
    debug_print_backtrace();
    exit();
} );
```

That will tell you more easily where in the plugin it is happening or if it is coming from core or a theme.

**Comment by myleshyson** [comment]
Haha ok I'm sorry about this. It was a Firefox AMP extension that was causing the issue. Once I removed it everything worked great.
