### ISSUE TITLE
AMP Verification notice on post updates

### ISSUE THREAD

**Issue by desnum** [ampproject/amp-wp#1785]
**Issue**: Every time a post is updated, there is a pop notice: "There are 2 issues from AMP validation which need review. But none are directly due to content here. However, your site is configured to automatically accept sanitization of the offending markup."

**Steps taken**: Site caches were cleared and AMP settings are set to Paired. Site appears fine, but the notice shows up with every post update. 

**Issue raised in**: HC-9099260
**Follow-up**: zen-1673817

**Screenshot**: 
<img width="1323" alt="screen shot 2018-12-28 at 2 42 44 pm" src="https://user-images.githubusercontent.com/43796228/50526571-e55b5280-0ab0-11e9-878f-3ac50195a2d0.png">

**Comment by westonruter** [comment]
Please go to “Review Issues” and share a screenshot of what the issues are.

**Comment by desnum** [comment]
For the latest post, when updated, the Review Issues link takes you here: 

![amp-errors](https://user-images.githubusercontent.com/43796228/50541171-df777700-0b6d-11e9-95b5-357b0d2b7b14.png)

**Comment by desnum** [comment]
Updating the errors from New Accepted to just Accepted does initially clear the errors from that page (removing the red highlight color from that line), however when the Update button is clicked on that page, the errors return.

**Comment by westonruter** [comment]
@desnum Please expand the details of the two validation errors to reveal their properties.

**Comment by desnum** [comment]
I tried updating a newer post that had the same errors. Here's a screenshot of them expanded:

![amp-errors-expanded](https://user-images.githubusercontent.com/43796228/50873540-7920fe80-138e-11e9-8220-d8b5ce364c52.png)

**Comment by westonruter** [comment]
OK, the issue is with Jetpack comments. You can see that there is variable data being added to the `iframe`'s `src` attribute and the `script` text. If you deactivate the [Jetpack Comments module](https://jetpack.com/support/comments/) module does that cause the issue to go away?

We need to patch the Comments module in Jetpack itself to fix this problem fundamentally: https://github.com/Automattic/jetpack/issues/9730

**Comment by jenlynnemc** [comment]
@westonruter I deactivated the Jetpack Comments Module, updated the errors from New Accepted to Accepted and this time they did not return with the Jetpack Comments Module off.

I have turned it back on for the user in the meantime.

**Comment by westonruter** [comment]
Please follow https://github.com/Automattic/jetpack/issues/9730 for updates to Jetpack's Comments module.
