### ISSUE TITLE
Comment reply not working with umlauts

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#1791]
To reproduce:

1. Install AMP plugin
2. Activate Twenty Nineteen or any other theme that works well in native or paired mode
3. Write comment using a name with umlauts, e.g. "Max Müller".
4. Reload page, click on "Reply" to reply to that specific comment
5. Notice that "Max Müller" is displayed as "Max M\u00fcller".

Screenshot:

<img width="762" alt="screenshot 2019-01-02 at 16 16 30" src="https://user-images.githubusercontent.com/841956/50598207-5c765980-0eaa-11e9-9f1f-5d6519577516.png">

**Comment by westonruter** [comment]
Max Muoofcller is a cool name.

**Comment by westonruter** [comment]
Here is where that `comemnt_author` is coming from:

https://github.com/ampproject/amp-wp/blob/511a8b1d8f81f79ec6968a48637d22091e8ce700/includes/class-amp-theme-support.php#L1067-L1081

One fix could be to do:

```diff
- esc_attr( sprintf( 'tap:AMP.setState( %s )', wp_json_encode( $tap_state ) ) ),
+ esc_attr( sprintf( 'tap:AMP.setState( %s )', wp_json_encode( $tap_state, JSON_UNESCAPED_UNICODE ) ) ),
```

Perhaps amp-bind doesn't support unicode escape sequences.

**Comment by swissspidy** [comment]
`JSON_UNESCAPED_UNICODE` works. Just noting that it's PHP 5.4+ only.

**Comment by westonruter** [comment]
We should probably consider bumping the minimum PHP version requirement at some point anyway.
