### ISSUE TITLE
Please consider namespace for the styles!

### ISSUE THREAD

**Issue by geminorum** [ampproject/amp-wp#1796]
https://github.com/ampproject/amp-wp/blob/19f1f246c613814d86498d30c8ee05e7f5c277fe/assets/css/amp-validation-single-error-url.css#L108-L112

seriously?

**Comment by westonruter** [comment]
@geminorum Please elaborate on what the problem is. Is this causing elements on the post list table to be erroneously hidden? Please share a screenshot.

The underlying problem may be that the condition for enqueueing the stylesheet is not properly being limited to the `amp_validated_url` post type:

https://github.com/ampproject/amp-wp/blob/32703d696fdcba9b1511fbfb7c3a2366d6ebd999/includes/validation/class-amp-validation-error-taxonomy.php#L870-L877

**Comment by geminorum** [comment]
@westonruter The style is based on the assumption that only List-table on post screen belongs to amp plugin. So it hides every `.tablenav` on the post editor.  This is not a good practice to expect the end user running a site only, just to use our plugin. All additional styles should be limited to the scope of targeted elements.

**Comment by westonruter** [comment]
@geminorum I think the problem is that the stylesheet is incorrectly being enqueued on post types other than `amp_validated_url`. Please confirm.

**Comment by westonruter** [comment]
In other words, I think a patch like this is needed:

```diff
--- a/includes/validation/class-amp-validation-error-taxonomy.php
+++ b/includes/validation/class-amp-validation-error-taxonomy.php
@@ -867,7 +867,7 @@ class AMP_Validation_Error_Taxonomy {
 				);
 			}
 
-			if ( 'post.php' === $pagenow ) {
+			if ( 'post.php' === $pagenow && AMP_Validated_URL_Post_Type::POST_TYPE_SLUG === get_current_screen()->post_type ) {
 				wp_enqueue_style(
 					'amp-validation-single-error-url',
 					amp_get_asset_url( 'css/amp-validation-single-error-url.css' ),
```

**Comment by geminorum** [comment]
confirming, the styles and the scripts are enqueued on all post-types.

**Comment by westonruter** [comment]
@geminorum Thanks. Please test #1798.

**Comment by geminorum** [comment]
works fine.

before:
![chrome_2019-01-07_22-34-05](https://user-images.githubusercontent.com/150718/50787817-bc1a9d80-12cc-11e9-944f-ec405a082abf.png)

after:
![chrome_2019-01-07_22-35-11](https://user-images.githubusercontent.com/150718/50787833-c472d880-12cc-11e9-92c0-f5b4fa0375a4.png)
