### ISSUE TITLE
Automatically disable admin bar in AMP when theme has too much CSS

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1800]
The admin bar accounts for about 20KB of CSS when it is displayed. This is 40% of the total 50KB CSS budget (😱). Very frequently themes have more than 30KB of CSS meaning that some CSS has to be excluded to remain valid AMP. Since the admin bar gets added early, its stylesheets end up being enqueued first and this can have the effect of causing the theme's own stylesheet to be excluded. This is very bad. Because the admin bar has so much CSS, there is an admin setting to disable it in AMP:

![image](https://user-images.githubusercontent.com/134745/50848372-f31e9c80-1328-11e9-81ec-2a6b2e87bc91.png)

Since it is very common for the admin bar to incur too much CSS when it is added, the AMP plugin should _automatically_ enable this setting to disable the admin bar when an `excessive_css` validation error happens.

**Comment by westonruter** [comment]
This setting should even be theme-specific. When switching to another theme, the available space for the admin bar should be re-checked.

**Comment by swissspidy** [comment]
I wonder if we could additionally make some contributions to core to reduce admin bar CSS in general. This would benefit everyone.

**Comment by westonruter** [comment]
That would be excellent. 👍

**Comment by swissspidy** [comment]
New ticket opened here: https://core.trac.wordpress.org/ticket/46003

**Comment by westonruter** [comment]
See #1921 for an alternative proposal.

**Comment by westonruter** [comment]
Closing in favor of #1921.
