### ISSUE TITLE
Show notice on frontend when there is excessive CSS

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1801]
In addition to automatically disabling the admin bar when there is excessive CSS (#1800), there should be an additional message displayed to the logged-in site administrator on the frontend when there is still excessive CSS. At the moment the ways for a user to know that there is excessive CSS are:

* Notice broken styling.
* See an AMP validation error when saving a post.
* Look at the page source for the `amp-custom` style manifest to see the excessive CSS message.

In addition to these, the plugin could display a message about the excessive CSS along with some suggestions for how to fix. For developers, fixing may involve rewriting CSS. For implementors, fixing may involving switching to a different theme or using alternative plugins. For other users, the fix may be to switch back to Classic/Legacy mode until the ecosystem better supports AMP.

The admin bar would be a good location to show this message:

![image](https://user-images.githubusercontent.com/134745/57810367-72c7d800-771c-11e9-8e3e-fdcb3e814b1d.png)

**Comment by westonruter** [comment]
It would also be useful to show a `progress` meter indicating the percentage of how much of the CSS budget they've used on the current page. Clicking the progress bar can then take the user to view the CSS manifest in the Validated URL screen (#2169).

**Comment by pierlon** [comment]
Would the progress meter be a top-level menu item in the admin bar?

**Comment by schlessera** [comment]
In my opinion, it should be a submenu under the main AMP top-level entry. Otherwise, we'll take up too much space to show a metric that will often be irrelevant.

**Comment by westonruter** [comment]
> It would also be useful to show a `<meter>` element indicating the percentage of how much of the CSS budget they've used on the current page. Clicking the progress bar can then take the user to view the CSS manifest in the Validated URL screen (#2169).

I think `optimum="50" low="75" high="99"` attributes work well for `meter` works:

```html
<meter min="0" optimum="50" low="75" high="100" max="101" value="50">50%</meter>
<meter min="0" optimum="50" low="75" high="100" max="101" value="80">80%</meter>
<meter min="0" optimum="50" low="75" high="100" max="101" value="101">100%</meter>
```

![image](https://user-images.githubusercontent.com/134745/71953469-28a5d200-3197-11ea-856d-81ebe2915768.png)

* If the CSS on the page is using 75% or less of the 50KB budget used, then the color is green.
* If more than 75% is used, then the color is yellow.
* If more than 100% is used, then the color is red.

**Comment by westonruter** [comment]
While I like the idea of the `meter` element:

![image](https://user-images.githubusercontent.com/134745/72043152-4b9eb780-3265-11ea-8fe1-c28a9e84e8a2.png)

In practice I think just plain text will be more clear:

![image](https://user-images.githubusercontent.com/134745/72043201-683aef80-3265-11ea-9c48-90ccfc8f0e8c.png)

When using 80% or more:

![image](https://user-images.githubusercontent.com/134745/72043250-89034500-3265-11ea-8061-5292b89f6ede.png)

vs.

![image](https://user-images.githubusercontent.com/134745/72043271-9a4c5180-3265-11ea-8352-4e45c6269c0b.png)

And when using more than 100%:

![image](https://user-images.githubusercontent.com/134745/72043324-ba7c1080-3265-11ea-994a-ccfd81234383.png)

vs.

![image](https://user-images.githubusercontent.com/134745/72043297-a89a6d80-3265-11ea-84a3-5509ea11d623.png)

There's probably some way to combine the `meter` with the text label, but then that would seem to just be getting verbose.

Code for `meter` if we decide to revisit:

```php
$meter_element = $this->dom->createElement( 'meter' );
$meter_element->setAttribute( 'min', '0' );
$meter_element->setAttribute( 'optimum', $this->style_custom_cdata_spec['max_bytes'] * 0.5 );
$meter_element->setAttribute( 'low', $this->style_custom_cdata_spec['max_bytes'] * 0.75 );
$meter_element->setAttribute( 'high', $this->style_custom_cdata_spec['max_bytes'] );
$meter_element->setAttribute( 'max', $this->style_custom_cdata_spec['max_bytes'] + 1 );
$meter_element->setAttribute( 'value', $total_size );
$meter_element->setAttribute( 'style', 'height:1em; width:100%;' );
```

**Comment by csossi** [comment]
Verified in QA
