### ISSUE TITLE
Account for toggleClass in CSS tree shaker

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1820]
Consider the following code:

```php
<style amp-custom>
#concealer {
    display:none;
}
#concealer.expanded {
    display:block;
}
</style>
...
<button on="tap:concealer.toggleClass(class='expanded')" type=button>Toggle Expanded</button>
<div id="concealer">Some Content</div>
```

The tree shaker will currently purge this CSS rule:

```css
#concealer.expanded {
    display:block;
}
```

The reason is because there is no DOM element with the `expanded` class.

Note that the tree shaker _does_ handle a related case, where amp-bind is used to toggle the class. It does this by extracting the string literals in `[class]` contained inside of it and using these as additional class names: 

https://github.com/ampproject/amp-wp/blob/732f789d5bbb73b0487ca0534ec28d2fec4e38a7/includes/sanitizers/class-amp-style-sanitizer.php#L364-L369

So with the above `style`, the CSS rule will not be shaken out in the equivalent amp-bind code:

```html
<amp-state id="expanded">false</amp-state>
<button on="tap:AMP.setState({expanded: ! expanded})" type=button>Toggle Expanded</button>
<div id="concealer" [class]="expanded ? 'expanded' : '' ">Some Content</div>
```

We need to add similar logic for the `toggleClass` case. This will require looking for `on` attributes to find ones that contain `toggleClass` and then considering its argument to be among the class names on the target element.

**Comment by davisshaver** [comment]
@westonruter I think this is similar to https://github.com/ampproject/amp-wp/issues/1490?

**Comment by westonruter** [comment]
It's definitely related.
