### ISSUE TITLE
Remove deprecated wpcom/shortcodes.php file

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#1824]
`wpcom/shortcodes.php` (containing `wpcom_amp_add_custom_embeds()`) was deprecated in 0.6.

We should consider just removing that file at some point, perhaps even in 1.1. I don't know the history of that WordPress.com / Jetpack integration though.

**Comment by westonruter** [comment]
> I don't know the history of that WordPress.com / Jetpack integration though.

Indeed. It's all supposed to be extracted from the AMP plugin and moved over to Jetpack and WPCOM. See #1021 and #1149.
