### ISSUE TITLE
AMP paired mode: missing top navigation and two JetPack features

### ISSUE THREAD

**Issue by nicopujol** [ampproject/amp-wp#1853]
Hi, 

Thanks for your help transitioning from custom AMP theme to paired mode. Pages now validate and look very similar to canonical URLs. We love the concept. 

The following elements are missing: 
- AMP top navigation menu shows in desktop view, but disappears on mobile.
- JetPack v7.0 launched today (good timing), advertising 100% AMP compatibility. But at the moment Related Posts and the Cookies Consent banner are not loading on AMP pages. Noted this on the support forum here, for reference: https://wordpress.org/support/topic/jetpack-v7-0-100-amp-compatible-missing-2-features/.

URL: https://www.laylita.com/recettes/oeuf-cocotte-au-roquefort-lardons-et-champignons/?amp

**Comment by westonruter** [comment]
I'm not sure about Jetpack mentioning 100% AMP compatibility because there are known issues with AMP compatibility: https://github.com/Automattic/jetpack/issues/9730

Please follow that GitHub issue for support for those features. Also, I did make a shim to enable Related Posts in AMP: https://github.com/Automattic/jetpack/issues/9556#issuecomment-455718389

Additionally, for a cookie consent banner, consider @felixarntz‘s plugin: https://github.com/felixarntz/wp-gdpr-cookie-notice

> AMP top navigation menu shows in desktop view, but disappears on mobile.

You'll need to implement an AMP solution for the hamburger menu to work. You can find docs on this at https://amp-wp.org/documentation/playbooks/toggling-hamburger-menus/

**Comment by nicopujol** [comment]
Re: Jetpack's AMP compatibility, did I dream reading the changelog stating this in v7.0 an hour ago? It no longer says so. Anyway...

- Re: consent, @felixarntz 's plugin works on AMP. Nicely done!
- For Related posts, your tweet points to a PHP file. Is there a plugin version of it or should I add the PHP code somewhere in the theme?
- Same question for the menu, the doc you reference suggests we can place the code in functions.php with `if ( example_is_amp() )` as a wrapper. Does this look correct?
`if ( example_is_amp(

<amp-state id="navMenuExpanded">
        <script type="application/json">false</script>
</amp-state>


<button
        class="menu-toggle"
        on="tap:AMP.setState( { navMenuExpanded: ! navMenuExpanded } )"
        [class]="'menu-toggle' + ( navMenuExpanded ? ' toggled-on' : '' )"
        aria-expanded="false"
        [aria-expanded]="navMenuExpanded ? 'true' : 'false'"
>
        <?php _e( 'Menu', 'example' ); ?>
</button>


<nav
        class="site-header-menu"
        [class]="'site-header-menu' + ( navMenuExpanded ? ' toggled-on' : '' )"
        aria-expanded="false"
        [aria-expanded]="navMenuExpanded ? 'true' : 'false'"
>
        <?php wp_nav_menu( /* ... */ ); ?>
</nav>
) )`

**Comment by westonruter** [comment]
> * For Related posts, your tweet points to a PHP file. Is there a plugin version of it or should I add the PHP code somewhere in the theme?

It's actually two PHP files. The second one is a plugin file:

https://gist.github.com/westonruter/1515ce1bae788e6d52d1a94ddd61fb59#file-jetpack-related-posts-amplified-php

So yeah, you can download the ZIP of that Gist and install it as a plugin.

The code you pasted is the right code from the docs, but you'll need to adapt it to your theme.

**Comment by nicopujol** [comment]
Thanks @westonruter. Almost there with getting paired mode to work. 

We're seeing intermittent loss of CSS or formatting with recipe card on the two plugins we use, WP Recipe Maker, and Zip Recipes. The code base for these plugins should be completely different, and the issue comes and goes (transients again?).

For Zip Recipes, the page output when I visited it yesterday showed plain text. No formatting, no structured data markup either. https://gist.github.com/nicopujol/5054acbcaeafe93ec23659e452d3d9b6. Today for some reason it seems to be mostly loading: https://www.laylita.com/recettes/riz-aux-crevettes/?amp
![ziprecipes plain text on new amp paired mode](https://user-images.githubusercontent.com/1319146/52427849-a2c86500-2ab5-11e9-9a69-6bd823ae90d6.jpg)

For WP Recipe Maker, it seems to work when logged out, but when I logged in the recipe formatting also vanished from the recipe card: 
https://www.nicolaspujol.com/oatmeal-chocolate-fruit-cakes-strawberry-raisins/?amp
https://gist.github.com/nicopujol/b533f47e8775e3719fb3d94d528aed5f. 
![amp cutout template glitch](https://user-images.githubusercontent.com/1319146/52427877-af4cbd80-2ab5-11e9-85fb-a841006a643d.jpg)

Is there something I can do on my end, or ask the plugin developers to tweak on their plugins to get AMP paired mode to work more consistently?

**Comment by westonruter** [comment]
@nicolastruchi If the formatting disappears when you log-in, then it is likely that the admin bar stylesheet is causing a CSS overage. I suggest going to AMP settings in the plugin and turning off the admin bar in AMP pages. That will give you more consistency.
