### ISSUE TITLE
npm run build failed with errors

### ISSUE THREAD

**Issue by amjad-eremnews** [ampproject/amp-wp#1856]
Running "shell:readme" (shell) task
/bin/sh: 1: ./dev-lib/generate-markdown-readme: not found
Warning: Command failed: ./dev-lib/generate-markdown-readme
/bin/sh: 1: ./dev-lib/generate-markdown-readme: not found
 Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! amp-wp@ build: `grunt build && grunt create-build-zip`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the amp-wp@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by westonruter** [comment]
@amjad-eremnews Could you please pull down the latest from the `develop` branch and do both `npm install` and `composer install`? I believe the error you're seeing is related to out of date dependencies.

**Comment by westonruter** [comment]
Oh, you need to initialize the git submodules. This is no longer needed in the `develop` branch.

**Comment by amjad-eremnews** [comment]
when you guys will release tags/1.0.3?

**Comment by westonruter** [comment]
Probably will go straight to 1.1. I want to tag an alpha pre-release soon.
