### ISSUE TITLE
Wrong template types are being used on *_template_hierarchy filter frontpage

### ISSUE THREAD

**Issue by pentatonicfunk** [ampproject/amp-wp#1874]
AMP version : 1.0.2
WP Version : 4.9.9
Config : 
```
add_theme_support(
			'amp',
			array(
'template_dir' => 'amp-2019-blog',
			)
		);
```
Issue : front-page.php on template_dir is being ignored

Solution: use `frontpage` instead of `front-page`
AMP WP vars : 
https://github.com/ampproject/amp-wp/blob/develop/includes/class-amp-theme-support.php#L87
WP PHPDOC
https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/template.php#L36

**Comment by amedina** [comment]
@swissspidy, could you take a quick look at this?

**Comment by swissspidy** [comment]
Seems legit.

`get_query_template()` strips underscores:

https://github.com/WordPress/wordpress-develop/blob/9179db7c66f7849ecf2b551195cdfd54445e4d21/src/wp-includes/template.php#L24

Probably makes sense to use the same regex in our code as well.
