### ISSUE TITLE
Use own comment Walker

### ISSUE THREAD

**Issue by TimoE93** [ampproject/amp-wp#1877]
Hi guys,

you added a comment walker in class AMP_Theme_Support (wp_list_comments_args filter).

Unfortunately it's not possible to remove the function you added and use my own comment walker.

It would be great, if i could use a custom comment walker.

Could you add that feature please.

Thanks in advance!

Greetings

Timo

**Comment by westonruter** [comment]
@TimoE93 Please test the build of the plugin found here: https://github.com/ampproject/amp-wp/pull/1878#issuecomment-465730598

**Comment by TimoE93** [comment]
Hello @westonruter,
it works perfect. Thank you very much!
