### ISSUE TITLE
Setting background image/video

### ISSUE THREAD

**Issue by ThierryA** [ampproject/amp-wp#1879]
- [x] Add field to sidebar for the page block to allow user to select an image or video for the background (beware YouTube)
- [x] Add focal point picker for background image
~~- [ ] Auto-cropping of excessive pixels~~ moved [here](https://github.com/ampproject/amp-wp/projects/10#card-18223712)

**Comment by westonruter** [comment]
@swissspidy This will depend on reworking how layers are done. So hold off on this one until I get to that.

**Comment by swissspidy** [comment]
> Auto-cropping of excessive pixels

Need some UX feedback for that I think.

Using the focal point picker component would basically mean re-cropping the image on every save when the focal point changes. Or we add a "Crop" button underneath the component so users can do the cropping manually.

**Comment by westonruter** [comment]
What about doing the crop at the moment the post is published or updated?

**Comment by ThierryA** [comment]
> What about doing the crop at the moment the post is published or updated?
+1 and as @swissspidy just brought up during our sync (at the office), probably on preview too since it is using image positioning the admin but AMP image on preview.

**Comment by csossi** [comment]
verified in QA
