### ISSUE TITLE
Semantic meaning of text block

### ISSUE THREAD

**Issue by ThierryA** [ampproject/amp-wp#1881]
* [x] Implement semantic meaning estimation algorithm to solve multi-variate optimization problem (e.g. font size, paragraph size, element location)
* [x] Take font size into account
* [x] Take word count into account
* [x] Take element position into account

**Comment by swissspidy** [comment]
Related: #1883.

Element location depends on #1897 I guess.

**Comment by csossi** [comment]
Verified in QA
