### ISSUE TITLE
Follow Gutenberg Design Principles

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#1887]
There's definitely room for improvement.

See https://wordpress.org/gutenberg/handbook/designers-developers/designers/block-design/ for do's and don'ts.

Take the current state of the AMP embed blocks as an example:

![screenshot 2019-02-20 at 16 38 58](https://user-images.githubusercontent.com/841956/53103500-0d55b800-352e-11e9-9842-4b249dd0803d.png)

**Comment by miina** [comment]
Good callout, definitely would be good to review and perhaps test _any_ editor-related code and make improvements, some pieces have probably been there from the first half of the last year without having too much attention.

**Comment by westonruter** [comment]
Note that in #4556 I propose we deprecate these blocks.
