### ISSUE TITLE
WordPress 5.1 Compatibility

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#1906]
Previously: #1604

* Verify that everything still works as expected
* Bump 'Tested up to' value in readme to 5.1.

If we can verify that 1.0.2 works fine with WordPress 5.1, we can just bump the version number on WordPress.org without having to release a new version of the plugin.

This would reassure our users that the plugin is safe to use with WordPress 5.1.

**Comment by westonruter** [comment]
Bump it just by making a new commit on the latest SVN tag?

**Comment by swissspidy** [comment]
Yep, the commit would be for the readme in the 1.0.2 tag

**Comment by westonruter** [comment]
I've been doing all development of the plugin using `trunk`, and I'm using the plugin on my own blog which is on WP 5.1, so it has indeed been tested in 5.1. I'll bump it.

**Comment by westonruter** [comment]
Done: https://plugins.trac.wordpress.org/changeset/2044249/amp
