### ISSUE TITLE
Reordering of pages

### ISSUE THREAD

**Issue by ThierryA** [ampproject/amp-wp#1907]
- [ ] Add reorder mode that shrinks story pages via CSS transform so that all pages can be shown in the viewport at once, and allow them to be drag-n-dropped to new positions via jQuery UI (FTW)

**Comment by dawidmlynarz** [comment]
👋 Hello! I have worked on the interactions for the *reordering pages*. Again I have produced Principle prototype to show you more interactions and flows. Please take a look at the prototype attached and share your thoughts.

![amp stories - reordering](https://user-images.githubusercontent.com/8026823/53569339-42808c80-3b64-11e9-87b1-97d37a64fbf9.gif)

🙌 Looking forward to your feedback!

**Comment by jwold** [comment]
This looks really good @dawidmlynarz! One thing I want to callout is that from an accessibility perspective there also needs to be a way to do this without mouse support. Great work :)

**Comment by dawidmlynarz** [comment]
🙏 Thanks! Good point with accessibility! I guess that adding some simple arrows while interacting with any Page in this view could be handy. 

I’m happy to explore that but I would like to know if this could be in the scope. Snother thing is if it should be done within the same ticket or as some separate enhancement for this feature?🙂

**Comment by ThierryA** [comment]
Awesome work @dawidmlynarz, will drop a few comments on Invision shortly.

> I’m happy to explore that but I would like to know if this could be in the scope. Snother thing is if it should be done within the same ticket or as some separate enhancement for this feature?🙂

Accessibility is definitely part of the scope of v1.0.0 stable but not a P0 for the beta version, so we can revisit when we move to the v.1.0.0 stable version.

**Comment by csossi** [comment]
Verified in QA
