### ISSUE TITLE
Shortcuts for most commonly used elements

### ISSUE THREAD

**Issue by ThierryA** [ampproject/amp-wp#1908]
- [x] Add shortcut buttons for adding common blocks (image, text +2)
- [x] Ensure that a page is always selected (when it is in the viewport) so that insertion of blocks can always be done

**Comment by swissspidy** [comment]
> Ensure that a page is always selected (when it is in the viewport) so that insertion of blocks can always be done

This is covered/resolved by #1903.

**Comment by miina** [comment]
Notes for QA:

These are the shortcuts:
![Screen Shot 2019-04-10 at 11 35 11 PM](https://user-images.githubusercontent.com/3294597/55915208-64e8d980-5be9-11e9-8972-f48be1570045.png)

**Comment by csossi** [comment]
Verified in QA
