### ISSUE TITLE
AMP Stories (carousel/list) can be embedded in WordPress posts in an excerpt/preview form

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#1910]
- [ ] Create a block similar to the Latest Posts block in Gutenberg that lists stories. Bundle AMP Stories with an embeddable “Latest Stories” widget (dynamic block) that shows a list of stories in preview/excerpt form

**Comment by kienstra** [comment]
Maybe this should have a label `[AMP-Stories] Discoverability`

**Comment by csossi** [comment]
Verified in QA

**Comment by kienstra** [comment]
Thanks, @csossi!
