### ISSUE TITLE
Streamline JS build tooling

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#1912]
The [@wordpress/scripts](https://www.npmjs.com/package/@wordpress/scripts) package contains some neat scripts that can be used for our Webpack / Babel setup.  

Especially with the upcoming 3.0.0 release, we can ditch lots of our custom configuration and re-use what the Gutenberg team uses. For example, that package already provides the `camelCaseDash` function and a default Webpack config we can build upon. Plus, having a good foundation to make our code testable can't be bad either :-)

This would also be a good opportunity to improve the JS folder structure a bit. I'd like to explore using at least parts of the hot module replacement solution Human Made came up with at https://humanmade.com/2018/11/26/hot-module-replacement-for-gutenberg-blocks/. Using Webpack’s `require.context` to load all the blocks would be really neat already.

In the same process, this could be a great opportunity to move the relevant CSS closer to the source. Development becomes easier when the CSS would live right next to important JS components.

During build, Webpack could extract and bundle the CSS files so the end result would be the same as now.

https://github.com/webpack-contrib/mini-css-extract-plugin is a Webpack plugin that can be leveraged for this.

**Comment by miina** [comment]
@swissspidy Can this ticket be closed as fixed within #2000?

**Comment by swissspidy** [comment]
There‘s a follow-up PR related to this: #2056. After that we can close this for now.
