### ISSUE TITLE
[AMP Stories] Text Block: Autocomplete broken

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#1919]
When typing `/` (slash) to open the autocomplete, you'll see a menu like this:\

![screenshot 2019-03-01 at 16 07 33](https://user-images.githubusercontent.com/841956/53646767-4b449180-3c3c-11e9-9f6d-ff270fdc8b82.png)

At the moment, clicking on these options is not possible. The following error appears in the console on click:

![screenshot 2019-03-01 at 16 09 07](https://user-images.githubusercontent.com/841956/53646801-6911f680-3c3c-11e9-8efd-0957b3eb5298.png)

This might be an issue with the text block we added.

**Comment by swissspidy** [comment]
Now the Autocomplete doesn't seem to work at all anymore 🤔 

@miina Do you perhaps know what might have changed here off the top of your head?

**Comment by miina** [comment]
@swissspidy Don't know top of my head, I checked a few PR-s back and at a first glance it looks like it hasn't been working already for some time.

I'm happy to debug this after updating #1965 (unless you get to it first).

**Comment by miina** [comment]
FI: Starting looking into this now.

**Comment by westonruter** [comment]
This issue seems to have regressed. I'm not able to get slash command completions anymore for the Text block:

![image](https://user-images.githubusercontent.com/134745/55992263-0101f780-5c61-11e9-8a96-dc29d851ae2b.png)

**Comment by swissspidy** [comment]
I just noticed that today. It seems to work with a completely fresh text block, but not after you have edited it already.

**Comment by westonruter** [comment]
Oh, good observation. It doesn't work for the initial Text block that appears in the page, but it does work for Text blocks that are added thereafter.

**Comment by westonruter** [comment]
Moving to v1.2.1

**Comment by swissspidy** [comment]
Hmm I cannot reproduce this error anymore.

**Comment by miina** [comment]
@swissspidy I think that you fixed it within https://github.com/ampproject/amp-wp/pull/2633. If I understood correctly.

**Comment by swissspidy** [comment]
Ah, well then this is actually a duplicate of #2632 then.
