### ISSUE TITLE
Deprecation notices in AMP_Post_Template

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#1927]
First reported here: https://wordpress.org/support/topic/depreciated-notice-when-using-template-new-amp_post_template-get_the_id/

At first it seems like a legit issue we might need to investigate further.

**Comment by westonruter** [comment]
I think the usage is incorrect. It seems the user is adding `amp` theme support _and_ trying to use the classic templates. I'll follow up on the support topic.
