### ISSUE TITLE
Sanitizer Flagging Facebook Components Inappropriately 

### ISSUE THREAD

**Issue by Hoodlum-Z** [ampproject/amp-wp#1928]
My website has two problems regarding Facebook Likes and Comments. https://gossiplolly.com

The site is running in Native Mode and posts and homepage are using AMP template.

Each post has both Facebook likes and comments, using AMP components, and work okay, until.

1. My homepage is also an archive page hosting my blog posts. The sanitizer says I'm using a Facebook script, but none is needed. This is technically true, because the Facebook items are on the posts not the page. My workaround is to have a Facebook comment box on the homepage, not ideal, but liveable. 

How can I remove it without upsetting the sanitizer?

2. The Facebook elements are working fine on my posts, but when I go into a post to edit a gallery, then save it they are removed.

Again, this isn't critical, but is a nuisance if I need to edit a post.

Thanks for any advice.

----

For previous context on the support forum, see https://wordpress.org/support/topic/validation-errors-unnecessary/

**Comment by westonruter** [comment]
@Hoodlum-Z What is the URL specifically for the page that has the problem? 

Is the sanitizer reporting the issue about the Facebook script, or is it the AMP validator? The AMP plugin's sanitizer does not report scripts being included but unused, AFAIK.

Are you manually adding the AMP component scripts for Facebook? You actually should not do this because the AMP plugin will automatically add them for you, only when they are present on the page.

**Comment by Hoodlum-Z** [comment]
@westonruter it happened on a few pages where I had a gallery. For example: https://gossiplolly.com/el-mencho-the-worlds-deadliest-cartel-boss/

It's both I think. 

The sanitizer from the plugin was removing the code after I edited my gallery and updated the post. It will be absolutely fine until I edit the page again and switch between Visual and Text tabs on the classic WordPress editor then update.

The error for the homepage with the Facebook elements being on the posts and not the actual archive/home page was of course being shown in the browser validator. Thanks.

**Comment by westonruter** [comment]
Both? I see no validation error on the AMP validator: https://validator.ampproject.org/#url=https%3A%2F%2Fgossiplolly.com%2Fel-mencho-the-worlds-deadliest-cartel-boss%2F

Please share a screenshot of the validation error as reported by the plugin.

**Comment by Hoodlum-Z** [comment]
I have taken a screenshot off my staging site, but the issue is the same. 

https://gossiplolly.com/gossip-lolly-amp/

As mentioned, I got around it on my main site by adding a Facebook comment box on my page.

![gossip-lolly-staging-site-validation-error](https://user-images.githubusercontent.com/5571357/53840538-4eb87f80-3f92-11e9-8a53-ef4d9cb2651a.jpg)

**Comment by westonruter** [comment]
And are you manually adding the `amp-facebook-comments` extension script to the page?

Are there any validation errors being reported _inside_ the AMP plugin, like in the Validated URLs screen?

**Comment by Hoodlum-Z** [comment]
Yes I am manually adding the components to each page I want the like box and comment box on.

It seems that the script is being applied site wide - please look at this latest example. Ideally I want my full site to be AMP for simplicity rather than running two systems that conflict.

There are errors being flagged in the plugin as well. Would you like to see a screen shot of them also?

https://gossiplolly.com/contact/

![gossip-lolly-news-sweets-amp-error](https://user-images.githubusercontent.com/5571357/53841103-d6eb5480-3f93-11e9-847e-2a2d14cf39a1.jpg)

**Comment by Hoodlum-Z** [comment]
What I think I need to know is how to white-list pages from the various scripts, please?

**Comment by westonruter** [comment]
> Yes I am manually adding the components to each page I want the like box and comment box on.

Do you mean that you are manually adding scripts like:

```html
<script async custom-element="amp-facebook-comments" src="https://cdn.ampproject.org/v0/amp-facebook-comments-0.1.js"></script>
```

If so, do not do this. The plugin will add them automatically.

**Comment by Hoodlum-Z** [comment]
What I was confused about was that it has a URL field so how do I change that for each post if say I only put one script in the single.php file for example?

**Comment by westonruter** [comment]
Don't put the script anywhere on the page. The AMP plugin will add it automatically.

**Comment by Hoodlum-Z** [comment]
Thanks!
