### ISSUE TITLE
 Leverage WordPress post embeds for embedding AMP stories into posts

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#1931]
* Make sure Post Embed block can embed AMP Story post type. 
* Use featured image, title, and excerpt in preview.

(Issue copied from [this card](https://github.com/ampproject/amp-wp/projects/10#card-17824838))

**Comment by kienstra** [comment]
**Copied and Created Issue**

Hi @MackenzieHartung,
If it's alright, I copied this issue from [this card](https://github.com/ampproject/amp-wp/projects/10#card-17824838)) and moved it into Sprint 2, for me to work on soon.

**Comment by kienstra** [comment]
**Question About Story Display**

Hi @westonruter,
Would it be alright if the embedded story here looks really similar to the story in the Latest Stories block (#1916)?

<img width="1050" alt="example-amp-story" src="https://user-images.githubusercontent.com/4063887/53876719-04082900-3fcd-11e9-8f0f-94f8950518df.png">

Thanks, Weston 😄

**Comment by westonruter** [comment]
@kienstra yes exactly. Embedding a single story should be just one slide of the carousel.

**Comment by westonruter** [comment]
@kienstra FYI: I've opened a PR for your review to fix an issue that may closely relate to your work here: #1934.

**Comment by swissspidy** [comment]
@kienstra Can this be closed?

**Comment by csossi** [comment]
verified in QA
