### ISSUE TITLE
Re-brand Classic mode as Reader mode

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1943]
The Classic mode isn't going anywhere, but we don't want to encourage users to use it unless they explicitly understand that it provides a stripped-down basic template. (At least it allows their potentially-heavy site content to still be consumed on bandwidth-constrained devices.) To this end, we can re-purpose the Classic mode as if it is a mobile “Reader” mode similar to what some browsers offer today. The key difference about the Reader mode offered by the plugin, however, is that ads would still be possible (via `amp-ad`).

We may need to make it clear that this reader mode would not be presented to desktop visitors. Only visitors from services that surface AMP content would present users with this mode.

As a first step, the “Leave Comment” link in the Classic template could be just renamed to “Exit Reader Mode”.

**Comment by amedina** [comment]
AMP Reader's mode entails enhancing to the classic mode so that the corresponding templates have an "exit reader's mode" functionality, which will trigger a navigation to the canonical version of the page. Likewise, there can be a functional button/link that takes the user from the canonical page to the Reader mode. 

In this modality, Reader-mode AMP pages are served from the cache, and users can navigate "back" to the non-AMP site by clicking on links in the AMP page, or by the exit reader mode function.

**Comment by amedina** [comment]
In principle this task should be relatively simple, modulo the design work that would be needed to add the above requirements.

**Comment by felixarntz** [comment]
To me this task mostly sounds it needs renaming of several labels and strings. Is that correct?

> The key difference about the Reader mode offered by the plugin, however, is that ads would still be possible (via `amp-ad`).

So the current classic mode doesn't support ads? I haven't looked at it in a while. Where would those ads come from?

> Likewise, there can be a functional button/link that takes the user from the canonical page to the Reader mode.

Should we try inserting this automatically into the page or only make this a function that theme authors can use? Theme layout is mostly unpredictable, so it would be hard to generally decide where to add it in the theme frontend without causing visual issues.

**Comment by westonruter** [comment]
> To me this task mostly sounds it needs renaming of several labels and strings. Is that correct?

Yes, I think so. So not actually much dev effort, if we only have the Exit Reader Mode link. If we decide to add a link on the non-AMP page to _enter_ the AMP version, then there would be more to work out. But I don't think we should really go down that road.

> So the current classic mode doesn't support ads? I haven't looked at it in a while. Where would those ads come from?

The ads would be _possible_. The plugin wouldn't be supplying them, however. So site owners would still be able to include ads in their reader mode as long as they add `amp-ad` to the content.

> Should we try inserting this automatically into the page or only make this a function that theme authors can use? Theme layout is mostly unpredictable, so it would be hard to generally decide where to add it in the theme frontend without causing visual issues.

Agreed. If someone wants to add a link to the AMP version, they can do that, but I won't think we should do it for them automatically.

**Comment by felixarntz** [comment]
> Agreed. If someone wants to add a link to the AMP version, they can do that, but I won't think we should do it for them automatically.

SGTM. After conversation with @amedina yesterday, I think there is value in providing a link from canonical page to reader mode, however that should be opt-in. I think we could address this in the following way:
* Provide a setting like "Show link to reader mode in the frontend" that is available on sites that have Reader mode enabled.
* Have a function `amp_render_reader_mode_link()` that can be called from a theme. It will only render something if the user has enabled the above setting.
* If the user has enabled the setting, but the theme never calls `amp_render_reader_mode_link()` anywhere in its markup, the fallback is to render the link as a fixed overlay, for example at the bottom right corner of the screen.

**Comment by westonruter** [comment]
A couple other points we discussed this morning:

* Should we rebrand Paired mode as Transitional mode? Paired mode is ambiguous because Classic is also paired.
* We should default to Paired/Transitional plugin activation once we detect that they have a compatible theme active and mostly-compatible plugins. See #1384.

**Comment by swissspidy** [comment]
Can we perhaps revisit adding some features for Reader Mode like the possibility to have a custom menu? It comes up again from time to time, most recently in https://wordpress.org/support/topic/nothing-except-converting-to-amp/.

**Comment by felixarntz** [comment]
@westonruter I wanted to follow up on the `amp-ad` part. I worked on the PR and tested adding an `amp-ad` to my post content as a "Custom HTML" block in Gutenberg, and it just worked without any change. I'm still not sure I understand what you said earlier:

> The key difference about the Reader mode offered by the plugin, however, is that ads would still be possible (via `amp-ad`).

**Comment by westonruter** [comment]
> Can we perhaps revisit adding some features for Reader Mode like the possibility to have a custom menu?

See #2044.

> I wanted to follow up on the `amp-ad` part. I worked on the PR and tested adding an `amp-ad` to my post content as a "Custom HTML" block in Gutenberg, and it just worked without any change.

@felixarntz The point here is that reader modes in Browsers typically would strip out any advertisements. The AMP plugin's Reader mode would not, as long as they are `amp-ad`.
