### ISSUE TITLE
AMP consent for analytics configuration

### ISSUE THREAD

**Issue by p2er** [ampproject/amp-wp#1949]
## What's the issue?

AMP Consent can not be bound to analytics config defined via plugin page. Should supply interface as described here: https://www.ampproject.org/docs/reference/components/amp-consent#promptifunknownforgeogroup

## How do we reproduce the issue?

1. Open analytics config page (wp-admin/admin.php?page=amp-analytics-options)
2. Enter config
3. Should provide field for consent configuration

## Info

AMP may support more advanced pre-defined blocking behaviors in the future. Because of this, the value of data-block-on-consent is reserved only for the following supported pre-defined attributes:

**_till_responded** : Unblock the component until the user has responded to the consent prompt, or the consent prompt has been skipped.
**_till_accepted** : Default basic blocking behavior, expect that when _till_accepted is explicitly added, individual components cannot override the blocking behavior.
**_auto_reject** : Always reject the consent automatically if consent is required but unknown. The reject consent decision will not be stored. It is recommended not to specify a consent prompt UI when auto rejecting consent for every components.

**Comment by westonruter** [comment]
In other words, you're looking for a UI to supply the `data-block-on-consent` attribute of the `amp-analytics` element, correct?

Related: https://github.com/ampproject/amp-wp/issues/775#issuecomment-458752732

**Comment by p2er** [comment]
Yes, correct. Right now tracking starts with and without consent unless I implement the analytics configuration template wise.

**Comment by westonruter** [comment]
Adding the `<amp-analytics>` element in the template is a good approach in the mean time.

**Comment by p2er** [comment]
Is there a way to override the function hook and use the configuration passed through including the JSON and analytics type? That would also be helpful to parse the document and remove config parts that use unavailable selectors on that rendered page. For instance: Admin configures hook to amp image in order to check if teaser has been seen by the user. But some templates do and some do not contain said teaser. Adding the selector in the configured JSON would cause JS Errors on pages where the image is missing. Maybe there is a way for you guys to integrate this in the css sanitizer at some point.

**Comment by westonruter** [comment]
Do you mean the [`amp_print_analytics`](https://github.com/ampproject/amp-wp/blob/756c35475982e36eeb28511e96e82a4f68941372/includes/amp-helper-functions.php#L647) function? It is not currently overridable. 

I am not sure I understand, but I'm not very well familiar with consent in AMP. It would certainly be possible to add a sanitizer specific to analytics and consent that would detect the presence of elements on the page and modify the `amp-analytics` as required.

It seems like a first step may be to add a filter for the `$amp_analytics_attr` attributes array so that the `data-block-on-consent` attribute could be added:

https://github.com/ampproject/amp-wp/blob/756c35475982e36eeb28511e96e82a4f68941372/includes/amp-helper-functions.php#L691

**Comment by westonruter** [comment]
See #2925 for a PR which would make this possible.

**Comment by westonruter** [comment]
#3095 is now merged, so you can add these attributes using a filter like this:

```php
add_filter(
	'amp_analytics_entries',
	function ( $entries ) {
		foreach ( $entries as &$entry ) {
			$entry['attributes']['data-block-on-consent'] = '_till_responded';
		}
		return $entries;
	}
);
```

As opposed to adding new UI to the AMP plugin for this, we intend to discourage the use of the Analytics admin screen in favor of an analytics provider's own plugin, such as [Google's Site Kit](https://sitekit.withgoogle.com/) for Google Analytics, which will be able to provide tailored UIs for their respective products. 

Now that the capability is available (via filter), I think we can just close this for now.

The other option is to use the new `amp_print_analytics` action to render the complete `<amp-analytics>` tag yourself. See #3106.
