### ISSUE TITLE
units in amp-img width and height

### ISSUE THREAD

**Issue by flowl** [ampproject/amp-wp#1950]
The `amp-img` tag is different from the `img` (HTML) tag as in the amp version we can specify a ratio which scales up to natural size of the image or up to a boundary like `max-width` (CSS) [1].
HTML5 img allows `%` or no unit only (*), otherwise it uses px by default [2].
It is unclear to me which units in `amp-img` are valid.

Please make it clear on [1] which units are allowed or at least how exactly the values differ from HTML5.

Thanks in advance

*) The German and English page of [2] and [3] differ heavily concerning attributes. The English version only mentions px, the German version also mentions `%`.

[1] https://www.ampproject.org/docs/reference/components/amp-img
[2] https://developer.mozilla.org/de/docs/Web/HTML/Element/img
[3] https://developer.mozilla.org/en/docs/Web/HTML/Element/img

----

My guess is that those formats are invalid:

    <amp-img width="200px" ....

    <amp-img width="50%" ....

    <amp-img width="50em" ....

**Comment by westonruter** [comment]
@flowl Hi, this seems like a question for the AMP project itself? In other words, are you identifying a deficiency in the docs at https://www.ampproject.org/docs/reference/components/amp-img ?

This amp-wp repo isn't really the place to file general issues about AMP. For that, there is https://github.com/ampproject/amphtml

**Comment by flowl** [comment]
@westonruter sorry, you are right, I didn't notice  that I landed on here instead of where you point me to :-)

Closed / Moved to https://github.com/ampproject/amphtml/issues/21352
