### ISSUE TITLE
Featured image handling and warning

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#1954]
From [this card](https://github.com/ampproject/amp-wp/projects/10#card-17824838):
- [x] Leverage WordPress post embeds for embedding AMP stories into posts. Make sure Post Embed block can embed AMP Story post type. Use featured image, title, and excerpt in preview. (Converted to #1931)
- [x] Set fallback default image in amp_story template when none is provided so that validation of the story is preserved. The warning should remain.
- [x] Show warning notice under the featured image control when no image is selected. Remove the global notice.
- [x] Extend Gutenberg pre-publish panel to block publishing while featured image is not set.

From [this card](https://github.com/ampproject/amp-wp/projects/10#card-18511617):
- [ ] Determine if "automatically" is the correct approach
Either or...
- [ ] Background media assigned to the first page to automatically populate featured image, if empty
- [ ] Instead of automatically being set in the postmeta, add a `get_post_metadata` filter for `_thumbnail_id` to supply image if it will be empty

**Comment by kienstra** [comment]
Hi @MackenzieHartung, if it's alright, I opened this issue by copying the 2 cards [shown above](https://github.com/ampproject/amp-wp/issues/1954#issue-420112782).

**Comment by kienstra** [comment]
**Could I Work On This?**

Hi @westonruter,
Thanks for merging #1957. Could I work on this issue next?

**Comment by westonruter** [comment]
@kienstra go for it

**Comment by kienstra** [comment]
Per our discussion, the first image that a user adds to an AMP Story will automatically be set as the featured image.
