### ISSUE TITLE
[AMP Stories] Fix styling for TwentyNineteen theme

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#1958]
Looks like the AMP Stories editor interface breaks with TwentyNinenteen theme due to the theme applying custom styles to the editor.
![Screen Shot 2019-03-13 at 11 43 16 AM](https://user-images.githubusercontent.com/3294597/54273959-43afb180-4587-11e9-97b6-165fb5ec84ed.png)

**Comment by swissspidy** [comment]
We can try making sure our custom CSS always takes precedence here, but ideally we would prevent all theme-specific editor CSS from being enqueued for AMP stories.

**Comment by swissspidy** [comment]
@westonruter In https://github.com/ampproject/amp-wp/pull/1962#issuecomment-473013281 you mentioned that we might want to allow themes to enqueue styles for AMP stories at some point. What's your take on how to handle a case like this one here?

I'm thinking that we might want to disallow all theme stylesheets (editor + frontend) by default, unless they explicitly target AMP stories (e.g. by hooking into an `enqueue_amp_stories_assets` / `enqueue_amp_stories_editor_assets` action, or perhaps by declaring theme support).

**Comment by westonruter** [comment]
@swissspidy yes, I'm thinking something similar. Currently we have this bit of code in the `amp_story-single.php` template to limit the stylesheets that are included:

https://github.com/ampproject/amp-wp/blob/d6cd963a617e90a125ecc4b1e4c14205586b21c0/includes/templates/single-amp_story.php#L19

and

https://github.com/ampproject/amp-wp/blob/d6cd963a617e90a125ecc4b1e4c14205586b21c0/includes/templates/single-amp_story.php#L57-L58

So what we could so perhaps is eliminate both of these with:

* `wp_styles()->do_items()` in the `head`
* `print_late_styles()` in the footer

Then we can modify `filter_frontend_print_styles_array`:

https://github.com/ampproject/amp-wp/blob/d6cd963a617e90a125ecc4b1e4c14205586b21c0/includes/class-amp-story-post-type.php#L197-L222

To do the following:

* Allow `wp-block-library`
* Allow [any stylesheet from a font CDN](https://www.ampproject.org/docs/design/responsive/custom_fonts#1.-using-%3Clink%3E).
* The `amp-stories.css` stylesheet.
* Any other stylesheet that has `amp-stories.css` marked as a dependency. This is how themes would add custom styles for their themes. (Alternatively, the handles for AMP Stories stylesheets could be defined in `amp` theme support as well.)
* Any other stylesheet we could exclude from being printing.

**Comment by miina** [comment]
@swissspidy @westonruter I can see that the editor seems to display without issues now with twentynineteen. Did this get fixed -- should we close this issue and open another one separately for allowing custom styles?

**Comment by swissspidy** [comment]
For Twenty Nineteen, I did only a minor fix in ac0e57eec4594f86117882b7478ae219390d1479, but most likely the recent PRs had some influence there (#1980, #1953). 

I think we can investigate the custom style issue as part of this one.

**Comment by miina** [comment]
Fixed within #2001.
