### ISSUE TITLE
[AMP Stories] Autoplay/Slide Duration

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#1964]
**To do:**

* [x] Add field to the AMP Story Page block for the duration of the slide. Allow auto duration to inherit from video/audio that is in the story, as well as inheriting from sum of all elements' animations.

**Reference:**

https://www.ampproject.org/docs/reference/components/amp-story#pages:-amp-story-page

This is handled by the `auto-advance-after` attribute:

> Specifies when to auto-advance to the next page. If omitted, the page will not automatically advance. The value for auto-advance-after must be either:
>
> * A positive amount of time to wait before automatically advancing to the next page
> * An ID of an `HTMLMediaElement` or video-interface video whose completion will trigger the auto-advance

Example:

```html
<amp-story-page id="tokyo" auto-advance-after="1s">
```

**Comment by swissspidy** [comment]
> Allow auto duration to inherit from video/audio that is in the story

@westonruter @miina Should we just pick the first video/audio block we encounter in a page? Thoughts?

**Comment by westonruter** [comment]
@swissspidy yes, exactly. I would be extremely surprised if someone adds more than one video to a page. Normally it would be a background video I'd assume. This is good at least for the first iteration. Maybe in the future there should be a way to pick which video/audio that should be used for the duration, but that seems overkill for now.

**Comment by swissspidy** [comment]
IIRC we also talked about taking reading time into account for the time calculation. That would make it slightly more complex though, but could be a nice addition.

**Comment by miina** [comment]
Notes for QA.

AC: The user should be able to set Advance to Next Page setting for each Page. If the setting is "Automatic" or "After a certain time" then it should not advance to a next Page earlier than all the animations have finished (each block on a Page can have animation set which can last different amount of time).

See more details under the related PR: https://github.com/ampproject/amp-wp/pull/1970

**Comment by csossi** [comment]
Set story to advance automatically at 3 seconds. Did not see this advance when Previewing

**Comment by csossi** [comment]
my bad - all good - Verified in QA
