### ISSUE TITLE
[AMP Stories] Fix default Inserter in the Toolbar

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#1966]
Currently, the Inserter in the upper Toolbar doesn't seem to work as expected. It seems to allow adding a Page within a Page and not allow the allowed child blocks.
Steps to reproduce:
- Add a Page and a block (or some blocks);
- Select a block within the Page;
- Click on the default Inserter in the toolbar.

**Comment by swissspidy** [comment]
There was a recent bug fix in Gutenberg for the global inserter in the toolbar: https://github.com/WordPress/gutenberg/pull/14020. It will be included in 5.3.

Let's test this with the current development version to see if anything changed for us. After all we do some on-the-fly filtering there.

**Comment by swissspidy** [comment]
I just installed 5.3 RC 1 and it seems to work fine now!

1. Add page
2. Select block within page
3. Click on global inserter in the toolbar
4. See the full list of allowed child blocks (no pages or anything.

When a page or no block at all is selected, then the global inserter only allows you to insert pages.

**Comment by amedina** [comment]
The flow when editing a page and I want to insert components to it does not work as expected. 

For example: I am on a blank page, click on the inserter on the top left corner, and only the page block is available. The expected scenario is for the user to see all the blocks that can be inserted, and also the possibility of adding a new page.

**Comment by miina** [comment]
@amedina That's the default behavior of the Inserter of Gutenberg -- it always shows what you can insert after the currently selected block. For example, if a Page is selected then you can insert only another Page after it and that's why only a Page shows, since the other blocks can't be inserter _after_ the Page, they could only be inserter _inside_ the Page.

On a blank page by default no block is selected, that's why the inserter shows only the Page -- this would insert a new Page. If it would show other blocks there, too, then it wouldn't be clear where they could be inserter. By default to the root element, but these are not allowed there.

Perhaps ideally if a Page is selected then other blocks would also be displayed and if a non-Page block would be inserted, it would be inserted as the last block of the selected Page.
However, not sure how easy it would be to change the default behavior. Thoughts, @swissspidy?

**Comment by swissspidy** [comment]
> Perhaps ideally if a Page is selected then other blocks would also be displayed and if a non-Page block would be inserted, it would be inserted as the last block of the selected Page.

Agreed. We turn Gutenberg a bit on its head with the way stories are edited, so changing the behavior here makes sense.

> However, not sure how easy it would be to change the default behavior.

Neither am I. There are some issues surrounding the inserter, e.g. https://github.com/WordPress/gutenberg/issues/14515, so we'd have to take a deeper look.

**Comment by amedina** [comment]
We need to devise a solution because the flow is broken. One approach would be to have always a page selected, either explicitly by the user or by default following some heuristic (e.g.  the leftmost page, the most recent, etc).

**Comment by swissspidy** [comment]
For clarification, we already have a page that is always the "current" page. It's the one in the center of the screen. Having this block always _selected_ (i.e. block toolbar and drag handles are always shown)  sounds a bit odd, and as Miina said, wouldn't solve the issue anyway:

> If a Page is selected then you can insert only another Page after it and that's why only a Page shows

**Comment by swissspidy** [comment]
QA: Access the inserter via the top left "+" (plus) icon button:

![Screenshot 2019-04-11 at 14 22 21](https://user-images.githubusercontent.com/841956/55956884-46282880-5c65-11e9-8542-9488c60ba57d.png)

Verify that, no matter what block is currently selected in the editor, you are able to insert all blocks using that inserter. Call-to-Action blocks should not be shown when editing the first page.

**Comment by csossi** [comment]
Verified in QA
