### ISSUE TITLE
[AMP Stories] Make sure that the frontend and editor view match

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#1967]
AC: All the allowed blocks in the editor look visually the same (or very similar) to how they look like in the frontend. This does _not_ include animations.

- [x] Make sure that all the text containing blocks' font sizes in the editor match the sizes in frontend;
- [x] Make sure that the margins and paddings in the editor match the frontend. For example, the AMP Story Grid Layer seems to have padding but this is not reflected in the editor;
- [x] Make sure that the Text block displays similarly in the editor as in the frontend. At this moment a Text block might display 2 rows in the editor but just one in the frontend.
- [x] Verify other blocks not mentioned here separately.
- [x] Make sure the ratio of the Page is correct (currently per Weston's comment Frontend story is: 390.141/650.250 = 0.59998615917, however, Editor is: 338/553 = 0.61121157323)
- [x] Add basic editor style (e.g. max-width).

**Comment by westonruter** [comment]
See also discussion about how we should include styles on the frontend: https://github.com/ampproject/amp-wp/issues/1958#issuecomment-473082141

**Comment by swissspidy** [comment]
> Make sure the ratio of the Page is correct

Note that this also affects the reordering UI.

**Comment by miina** [comment]
I'm wondering what would be the best approach for font sizes -- for example if the default font size is 16px in the editor and is displayed in two rows then the same font size in the frontend might still be in one row -- since the font size is not responsive. We could add some different sizes based on the screen width for the default font sizes, however, what if the user selects a specific font size? 

@swissspidy @westonruter Thoughts?

**Comment by westonruter** [comment]
@miina What if the specific font sizes were stored in `vh` units instead of `px` units? That would make them responsive. They'd perhaps have to remain `px` in the editor since the the viewport is not fully contained by the story, but when rendered on the frontend they could be replaced with some computed equivalent using `vh`. This would make the font size scale based on the height of the viewport, and thus it would be responsive.

**Comment by miina** [comment]
@westonruter: Just updated the PR to use `vw` units instead of `px` for the font size in the frontend, the editor still displays in `px`.

**Comment by miina** [comment]
Closed within #2015.

**Comment by csossi** [comment]
verified in QA
