### ISSUE TITLE
Prevent escaping Unicode characters in Schema.org JSON data

### ISSUE THREAD

**Issue by ziodave** [ampproject/amp-wp#1969]
The JSON-LD metadata written by `amp_post_template_metadata` uses character encoding, e.g. [1]

```
{ "headline":"\u039d\u03ad\u03b1 \u0396\u03b7\u03bb\u03b1\u03bd\u03b4\u03af\u03b1: \u0391\u03c5\u03c4\u03cc\u03c2 \u03b5\u03af\u03bd\u03b1\u03b9 \u03bf \u03bc\u03b1\u03ba\u03b5\u03bb\u03ac\u03c1\u03b7\u03c2! \u039c\u03b5\u03c4\u03ad\u03b4\u03b9\u03b4\u03b5 live \u03c3\u03c4\u03bf...", ...
```

Being the web site UTF-8, would it be possible not to encode the characters, e.g. [2]:

```
{ "headline":"Νέα Ζηλανδία: Αυτός είναι ο μακελάρης! Μετέδιδε live στο...", ...
```

Can I contribute a patch so that, if the charset is UTF-8, the characters do not get encoded?

[1] https://www.newsit.gr/kosmos/nea-zilandia-aytos-einai-o-makelaris-metedide-live-sto-facebook-to-makeleio/2738206/amp/
[2] https://www.newsit.gr/kosmos/nea-zilandia-aytos-einai-o-makelaris-metedide-live-sto-facebook-to-makeleio/2738206/

**Comment by westonruter** [comment]
Is the reason to just improve readability? I think that is fine. I assume you would use `JSON_UNESCAPED_UNICODE`?

**Comment by ziodave** [comment]
> Is the reason to just improve readability?

Yes (I believe that it doesn't have any effect in terms of Google parsing the structured data).

> I assume you would use JSON_UNESCAPED_UNICODE?

Yes, as well as `JSON_UNESCAPED_SLASHES` to avoid escaping slashes and `JSON_NUMERIC_CHECK` to print numeric strings as numbers, if that's all right.

**Comment by westonruter** [comment]
Why `JSON_NUMERIC_CHECK`? That seems like it could lead to unpredictable data. If something should be a number, we should be casting it in `amp_get_schemaorg_metadata()`.

**Comment by ziodave** [comment]
Ok, I was thinking about numeric values stored in post meta that people "forget" to cast explicitily. I am

**Comment by westonruter** [comment]
Cool. I await your PR!
