### ISSUE TITLE
 [AMP Stories] Draggable Block Navigation

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#1974]
Add drag/drop reordering of elements in table of contents (contribute via Gutenberg).

This would allow us to get rid of the up/down errors in the BlockMover component. Since the drag handle in the BlockMover looks a bit odd on its own, and because it's not the best UX, I suggest instead exploring making the whole block element draggable and not just the handle.

Previously: #1897

**Comment by westonruter** [comment]
Should this be closed? The other issues in QA are closed.

**Comment by swissspidy** [comment]
Yeah I reopened but then realized it's best to create a new issue for the draggable block part.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create new story with a couple of pages
2. Create a bunch of blocks on each page, including CTA blocks where applicable (CTA blocks are not enabled on the first page)
3. Optional: Add background colors to blocks to more easily see visual differences
4. Drag and drop blocks in the block navigation
5. Verify that dragging the blocks affects their visual hierarchy in the editor and also on the frontend)
6. Verify that the CTA block is not visible in the block navigation, so its visual hierarchy cannot be changed

**Comment by csossi** [comment]
All good except one clarification. When CTA block is clicked on, shouldn't all of the "Block Position" buttons be disabled (as per instruction 6 above)
![image](https://user-images.githubusercontent.com/16945664/58036353-e68d2a80-7af8-11e9-9844-1458cf872ce7.png)

**Comment by miina** [comment]
@csossi Thank you for testing.

As it works currently, we do need the Block Position controls in the sidebar, although it's not in the Block Navigation.

That's because when we add the CTA block, depending on when we add it, it could stay under or on top of other blocks and the user might still need to change that.

An alternative would be forcing the CTA always to be on top, however, not sure if we want that, perhaps we do want to sometimes cover it with something else, e.g. another block with opacity 🤷‍♀ 

I'll mark this issue as resolved, @swissspidy let me know your thoughts on if CTA block should always be forced to be the top block.

**Comment by swissspidy** [comment]
> perhaps we do want to sometimes cover it with something else, e.g. another block with opacity

@miina How can someone click on the CTA if it's covered by another block?

I originally removed the CTA block from the block navigation because it must always be the last layer on a page:

> If specified, the `<amp-story-cta-layer>` element must be the last layer within an `<amp-story-page>`. As a result, effectively every `<amp-story-page>` can have exactly one or exactly zero of the `<amp-story-cta-layer>` element.

[Source](https://amp.dev/documentation/components/amp-story#amp-story-cta-layer)

On the frontend we automatically enforce this already. In the editor, we can enforce this by hiding the block position controls for that block and by setting a high enough z-index. Or even by automatically moving to the bottom, but that's a bit more complex. I'll create a separate issue for it.

**Comment by miina** [comment]
> @miina How can someone click on the CTA if it's covered by another block?

I was actually thinking of only partly covering and not the full button, however, not really sure if that would be a common use case, probably not.

> I'll create a separate issue for it.

Yep, adding this in a separate issue makes sense 👍
