### ISSUE TITLE
Warning triggered when filtering kses allowed attributes

### ISSUE THREAD

**Issue by fumikito** [ampproject/amp-wp#1975]
Amp plugin throws warning on `wp_kses_post` function.

The filter function `whitelist_block_atts_in_wp_kses_allowed_html` assumes `$tags` are always an associative array, but sometimes they could be like below:

```php
$tags = [
    'form' => [
        'action' => true,
    ],
    'strong' => true,
];
```

As a result, amp plugin triggers warnings.

```
( ! ) Warning: Cannot use a scalar value as an array in /var/www/wordpress/wp-content/plugins/amp/includes/admin/class-amp-editor-blocks.php on line 83
```

**Comment by westonruter** [comment]
Good catch.

**Comment by fumikito** [comment]
Oops, the error message displays line **83**, but actually they are **80**. That difference is because of my debugging code.
