### ISSUE TITLE
[AMP Stories] Flush rewrite rules it AMP Stories rules don't exist

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#1978]

**Comment by miina** [comment]
@westonruter Does this include adding a setting for enabling/disabling AMP Stories?

**Comment by westonruter** [comment]
Oh, right. No 😄 

So for now then I suppose the `AMP_Stories_Post_Type` should just check the current rewrite rules to see if the `stories` rule exists, and if not, flush the rules.
