### ISSUE TITLE
Composer: Declare PHP Extension dependencies

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#1985]
While looking at #1834 I noticed that we currently don't declare PHP extension and library requirements in `composer.json`.

Off the top of my head, we'd need the following platform dependencies:

```json
{
  "require": {
    "ext-intl": "*",
    "ext-libxml": "*",
    "ext-dom": "*"
  }
}
```

Perhaps even `"lib-icu": "*"`, since that's being used by `ext-intl`.

**Comment by westonruter** [comment]
Excellent. I didn't know those could be formalized as such.

Also required is `iconv`.

Relates to this code:

https://github.com/ampproject/amp-wp/blob/401a4e9c8bbf1c661546ab21db93ed8bd704eae0/amp.php#L41-L89
