### ISSUE TITLE
Global / per Story Slide Duration Options

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#1995]
AC: User can set the slide duration options either globally or per story.
AC: The global / per story setting can be overridden per slide.

Investigate options for setting the slide duration per story or globally. This way the user wouldn't have to set each slide separately in the likely use case of wanting to use `auto` or `media` for all slides.

**Comment by swissspidy** [comment]
Note that it's finally possible to actually extend the document sidebar with the upcoming new Gutenberg version.

See https://github.com/WordPress/gutenberg/pull/13361 / https://github.com/WordPress/gutenberg/issues/13357

**Comment by swissspidy** [comment]
@dero The PR is still set to draft – it's not clear to me whether this is now ready for review or still WIP. Can you clarify?

**Comment by dero** [comment]
**Summary for QA:**

This PR introduces a concept of global settings and story settings. 

- Global settings: set on AMP plugin settings page, applied as defaults to every new story.
- Story settings: set on a story post, applied as defaults to every new page.
- Page settings: set on a page block, applied to that block only.

**Test instructions:**

1. Go to AMP plugin settings page and enable the Stories experience.
2. Change the values in the Stories Settings field and check the values persist upon saving.
3. Create a new story and notice a "Story Settings" panel in the "Document" tab.
4. Verify that values in that panel match what was set globally in step 2.
5. Click the first page and on the "Block" tab verify that the values in the "Page Settings" box match the "Story Settings".
6. Change the "Story Settings" to something else in the "Document" tab.
7. Verify that the "Page Settings" in the "Block" tab did not change.
8. Create a new page.
9. Verify that the "Page Settings" in the "Block" tab are equal to what was set in step 6.
10. Create a new page.
11. Change the "Page Settings" in the "Block" tab for that page to something else.
12. Check that other pages were not affected and their "Page Settings" stayed intact.
13. Check that the "Story Settings" in the "Document" tab remained unchanged.
14. Finish the story and publish it.
15. Verify that the advancement options are applied correctly on the front-end.

**Screencast:** https://www.youtube.com/watch?v=TppJ96XE-qU

**Comment by csossi** [comment]
Verified in QA
