### ISSUE TITLE
[AMP Stories] Element rotation

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2005]
AC: User can rotate any block in the editor and this is accurately reflected in the frontend view.

- [x] Add rotation grab handle to text block

**Comment by swissspidy** [comment]
QA:

Blocks can be rotated using the blue rotation handle below a block (click & drag):

![Screenshot 2019-04-11 at 14 16 27](https://user-images.githubusercontent.com/841956/55956518-71f6de80-5c64-11e9-8737-7e3632ef507a.png)

When selecting a rotated block, it goes back to its initial position to make editing easier. In this state, you should also be able to drag blocks around.

Some early limited keyboard interaction is possible as you can press ESC to cancel rotation.

**Comment by kienstra** [comment]
It would probably be best to wait to test this until #2097 is deployed to the testing environment.

**Comment by kienstra** [comment]
It looks like #2097 is deployed.

**Comment by csossi** [comment]
Verified in QA
