### ISSUE TITLE
Change AMP permalink

### ISSUE THREAD

**Issue by rnbjunk** [ampproject/amp-wp#2008]
Hello, i want to know how can i change amp permalink in my site

https://www.rnbjunk.com/amp/jennifer-lopez-french-montana-medicine-testo-traduzione-video/
Now

https://www.rnbjunk.com/jennifer-lopez-french-montana-medicine-testo-traduzione-video/amp/
Before

I changed the amp plugin on my WP, and not i get a new url permalink. I want to go back to the before permalink /amp/ at the end.

Someone can help me?

**Comment by swissspidy** [comment]
If you want your `rnbjunk.com/amp/jennifer-lopez-french-montana-medicine-testo-traduzione-video` URL to be AMP, then I recommend you to use the **Native** mode offered by the plugin.

In Paired mode, the URL would be `/my-blog-post/?amp`, and in Classic mode it would be `/my-blog-post/amp/`

**Comment by rnbjunk** [comment]
Thank u, but I just want to have only url with /amp/ ad the end, and not in the middle of the post, and i don't know where to modify the setting.
Also would like to redirect mobile visitors to amp pages.

**Comment by westonruter** [comment]
@rnbjunk This plugin already puts `/amp/` at the end. You don't appear to be using this AMP plugin, but rather “penci-pennews-amp”.

**Comment by rnbjunk** [comment]
yeah i'm using penci pennews amp version.
