### ISSUE TITLE
[AMP Stories] Create the base templates for Travel and Fandom

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2010]
AC: User can select between X (to be selected from the designs) single-page templates which are pre-populated with blocks, images and other data, so that they make sense in the context of Travel / Fandom;

- [x] Create templates in the editor based on design, use the HTML source to create templates for the "Template Inserter";
- [x] Auto-import pre-existing templates if the templates have never been imported before.

**Comment by amedina** [comment]
Follow up from team meeting...

The goal here would be to **abstract the components** that would form a Fandom template. This encompasses:

- Consider the case of **multi-page templates** (used when starting a story), and **single-page templates** (used at any point during story creation, possibly with special cases for first page, middle page, last page (bookend)
- For Travel/Fandom, what would the **building blocks** commonly found in travel or fandom stories
- Which **combinations of them** would make sense from a UX POV? Each of these combinations would form a template page.
- Which **combination of template pages** would go well together? Each of these sets of pages would form a multi-page templates.

@miina @swissspidy @westonruter @dawidmlynarz @kienstra

**Comment by csossi** [comment]
Any instructions re: testing for this? Not sure what I'm looking at here

**Comment by miina** [comment]
**Testing Instructions**

- When clicking on the Template Inserter, 4 templates have to be available. Template Inserter:
![Screen Shot 2019-05-09 at 9 49 11 AM](https://user-images.githubusercontent.com/3294597/57436354-cb403680-723f-11e9-8edd-9a2c6ccfb17d.png)

- It has to be possible to insert a blank page from the template inserter, too.
- When clicking on any of the templates in the template inserter, the template with all the blocks that can be seen in template inserter have to be inserted to the editor.
- The placement of the blocks should be the same as in the preview within the template inserter, however, no images should be inserted, and there should be placeholders instead of the texts.

Let me know if there are any doubts. cc @csossi

**Comment by csossi** [comment]
Thanks, @miina 

Can anything be done regarding these two templates? There's a purple vertical bar and copy overlapping it that looks confusing:
![image](https://user-images.githubusercontent.com/16945664/57665567-574cb800-75ca-11e9-918b-37426a1ded04.png)

![image](https://user-images.githubusercontent.com/16945664/57665588-69c6f180-75ca-11e9-9ca6-69503004ccf6.png)




- 4 templates available plus blank page:
![image](https://user-images.githubusercontent.com/16945664/57665393-b0681c00-75c9-11e9-9f35-d94e6a4b58a2.png)

**Comment by miina** [comment]
@csossi Could you test again?

**Comment by csossi** [comment]
Verified in QA:
![image](https://user-images.githubusercontent.com/16945664/57800674-f46d3500-771f-11e9-8c08-b8438dea6c6c.png)
![image](https://user-images.githubusercontent.com/16945664/57800707-08b13200-7720-11e9-8bb0-fc0405657c2a.png)
![image](https://user-images.githubusercontent.com/16945664/57800731-16ff4e00-7720-11e9-8683-fc92e8d0f62d.png)
