### ISSUE TITLE
Allow searching templates

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2012]
AC: User can search the templates and see results for both predefined templates and custom templates created by the user.

**Comment by westonruter** [comment]
And maybe templates are just a `wp_block` with a special postmeta or taxonomy?

**Comment by kienstra** [comment]
**Question About Searching**

Hi @ThierryA,
Good to see you today.

How would you like be able to search for templates? 

Would it be like how in the Post editor (not `amp_story` editor) you can search reusable block?

<img width="974" alt="post-ui" src="https://user-images.githubusercontent.com/4063887/56934190-c2699b00-6ab0-11e9-93e0-ec1cba0ca73b.png">

Maybe search could be part of the template inserter UI. But I'm not sure if that'd be useful, unless there are many more than the 4 templates there are now:

<img width="1179" alt="template-inserter" src="https://user-images.githubusercontent.com/4063887/56934167-acf47100-6ab0-11e9-90e3-389c0f88ebe4.png">

**Comment by miina** [comment]
@kienstra Here is the design that was created for searching templates: https://projects.invisionapp.com/d/main#/console/16842485/349221833/preview

The search could probably be based on the title and it would make more sense if the user would also be able to create templates (a feature that has been implemented but is currently disabled because it's not possible to edit templates, see #2011 ) and assign titles to the created templates (a feature not implemented, could be implemented within #2011 or in a separate issue).

**Comment by ThierryA** [comment]
@miina the search would be the same as when searching a re-usable block (by title).

> (a feature that has been implemented but is currently disabled because it's not possible to edit templates, see #2011 )

This feature should make it to 1.0 but it requires more discussion (on Thursday).
