### ISSUE TITLE
[AMP Stories] Add any missing features necessary for templates

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2013]
AC: All the features needed for the templates exist.

- [x] Look through the templates and log the features that we need to add for templates.
- [x] Implement any missing features.

Features needed:
- [x] Add border radius setting to Text block and Image block [Done, see #2055].
- [x] Add alignment options for the Text block.
- [x] Add gradient setting for Page. [Done, see #2046]

~~Add opacity Range control to allowed (child) blocks which use background color.~~ Moved to a separate issue:  #2058

**Comment by miina** [comment]
Based on the template designs the following features seem to be missing:
- Adding opacity to block (this would also be useful with a Color Fill block -- a resizable block which can be just filled with color and then placed on top of an image or background image is 100% size with opacity setting);
- Gradient (would also be useful with a Color Fill block).
- Aligning text to center;
- Rotation (is already logged in #2005.)

cc @swissspidy @westonruter

**Comment by swissspidy** [comment]
Color Fill block: My immediate thought was https://github.com/WordPress/gutenberg/issues/4900. The PR for that, https://github.com/WordPress/gutenberg/pull/13964, is still in the works, but according to the comments there it might be ready soon.

**Comment by swissspidy** [comment]
> Aligning text to center

Should be as easy as setting `supports: { align: true }` and adding the necessary `text-align` CSS.

**Comment by westonruter** [comment]
As I'm sure you're aware, also related to Section block is the Cover Image as a proto block: it allows you to add additional children to it. The Overlay has a color and opacity setting:

![image](https://user-images.githubusercontent.com/134745/54842882-5bc2b780-4c90-11e9-9787-407b5fd757cd.png)

**Comment by westonruter** [comment]
> * Adding opacity to block

What about adding opacity to a block as a whole, and not just the background color? I know this was done for layers in the previous incarnation of AMP Stories. Maybe that is just asking for trouble.

**Comment by miina** [comment]
> What about adding opacity to a block as a whole, and not just the background color? I know this was done for layers in the previous incarnation of AMP Stories. Maybe that is just asking for trouble.

Unless there is a reason why not to then seems like we could add it generally for other blocks, too, or at least to Image and Text Block.

Another style-related thing that occurs frequently in the templates is having rounded corners for images and Text blocks with background color. Maybe that'd also be something necessary?

**Comment by westonruter** [comment]
It would indeed be useful if background colors _everywhere_ in Gutenberg had the ability to specify the opacity. It's not currently provided normal Color Settings:

> ![image](https://user-images.githubusercontent.com/134745/54845458-9e878e00-4c96-11e9-97fd-d1a3f590b981.png)

The Overlay has the opacity as a separate slider for Background Opacity as shown above:

> ![image](https://user-images.githubusercontent.com/134745/54845553-db538500-4c96-11e9-944b-7fadd626687c.png)

By it would be cool if all color pickers just had opacity as a standard parameter.

> Another style-related thing that occurs frequently in the templates is having rounded corners for images and Text blocks with background color. Maybe that'd also be something necessary?

Oh yeah, a border radius setting for the text block and image block would be very nice!

**Comment by miina** [comment]
Ticket description is now updated based on the discussion.

**Comment by swissspidy** [comment]
> a border radius setting for the text block and image block would be very nice

Could this be a block style instead? Then one could choose between "Default" and "Rounded" without having to worry about the block radius always being consistent between blocks. Or is there a strong use case for a block radius range control?

**Comment by miina** [comment]
"Default" and "Rounded" should be sufficient, we can adjust later if it should become necessary.

**Comment by miina** [comment]
Will start working on adding the gradient/scrim setting to Page. cc @swissspidy

**Comment by csossi** [comment]
verified in QA
