### ISSUE TITLE
How to edit AMP Facebook Share appid?

### ISSUE THREAD

**Issue by bantilan** [ampproject/amp-wp#2020]
Hi Guys,

Where can I edit the appid for the facebook share button? When clicking the share button in the AMP page. it gives an error message saying

"App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions."

Been looking on the source file but couldn't find it.

Best Regards,

- Erwin

**Comment by bantilan** [comment]
By the way, I am using Classic Mode.

**Comment by westonruter** [comment]
How are you adding the Facebook share button? Are you using `amp-social-share` or `amp-facebook-like[data-share]`? The AMP plugin has not built-in configuration for adding these components. It may be up to the plugin you are using to add the share button.
