### ISSUE TITLE
Background Audio

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2021]
As discussed at https://github.com/ampproject/amp-wp/pull/2015#issuecomment-475820596, we should support background audio on AMP Stories pages

**Comment by Amanrazdan** [comment]
Have we added this request or not ?

**Comment by swissspidy** [comment]
Hi @Amanrazdan, we haven't implemented this yet. We are currently focusing on more important enhancements, but will eventually get to this one.

We'd of course also accept pull requests from interested contributors :-)
