### ISSUE TITLE
Re-brand Paired mode as Transitional mode

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2022]
The paired mode is actually a transitional mode aimed at helping developers traverse the path from no AMP to native AMP in an easier way. 

This issue addresses this by rebranding the `Paired Mode` to `Transitional Mode`.

/cc @westonruter

**Comment by westonruter** [comment]
See also https://github.com/ampproject/amp-wp/issues/1943#issuecomment-473099414

**Comment by amedina** [comment]
+1. Good idea.  Will do.

**Comment by westonruter** [comment]
Note that #2034 includes the rebrand.

**Comment by westonruter** [comment]
@amedina Is this targeted for 1.1? I assume so.

**Comment by amedina** [comment]
Correct. Ideally we would have the rebranding of the modes, and the updates to the Compatibility Tool error status handling.
