### ISSUE TITLE
Consider adding global font family option

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2028]
AC: User can set the font family setting either globally or per story.
AC: The global / per story setting can be overridden per block.

See also #1995.

**Comment by swissspidy** [comment]
Note that it's finally possible to actually extend the document sidebar with the upcoming new Gutenberg version.

See https://github.com/WordPress/gutenberg/pull/13361 / https://github.com/WordPress/gutenberg/issues/13357

**Comment by ithinkihaveacat** [comment]
One manifestation of this bug (I think): no font is selected if a new text block is added in the AMP Story editor.

<img width="1302" alt="Screenshot 2019-07-05 at 16 49 58" src="https://user-images.githubusercontent.com/51244/60810536-47de8b00-a185-11e9-81bb-8d73a075abb0.png">

**Comment by swissspidy** [comment]
@ithinkihaveacat Not really a bug as we haven't implemented this yet. Once we implement this, it would show the globally set default instead of "None"
