### ISSUE TITLE
Review Existing Travel Site for Gutenberg Incompatibilities

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#2033]
- [x] Confirm that the [travel theme](https://github.com/xwp/travel) doesn't have incompatibilities that could block using it

**Comment by kienstra** [comment]
**No Concern On Single Adventure Template**

The single travel template looks fine with WordPress `5.1.1` and Gutenberg `5.3.0`.

For example, I built [this page](https://travel-theme.amp-wp.org/adventure/skateboard-around-the-city/) locally, using those versions. It looked good:

![travel-theme-compatiblitiy](https://user-images.githubusercontent.com/4063887/55095647-1d593e00-507e-11e9-97f7-628594939032.gif)

**Comment by kienstra** [comment]
**Home Page Looks Fine When Copying In Rendered Content**

The custom blocks for the theme don't appear in the editor anymore. But the homepage still looks alright if I copy the [rendered content](https://travel-theme.amp-wp.org/wp-json/wp/v2/pages/81) of the [homepage](https://travel-theme.amp-wp.org/) in a page's Custom HTML block:

![home-page-demo](https://user-images.githubusercontent.com/4063887/55096792-2a772c80-5080-11e9-82fb-e99e07f61b06.gif)

**Comment by kienstra** [comment]
This theme should be fine to use for front-end demos. The only concern would be if we needed to show the editor of the homepage.

**Comment by kienstra** [comment]
I'll work on fixing the Travel theme for the API changes in Gutenberg.

**Comment by amedina** [comment]
Once you have it working with the latest Gutenberg, let's set up a staging site to play with it.

**Comment by kienstra** [comment]
Sounds good!

**Comment by kienstra** [comment]
Now that https://github.com/xwp/travel/pull/86/ is merged, the breaking changes from Gutenberg should be fixed.
