### ISSUE TITLE
Support SVG camelCase elements and attributes

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2045]
When attempting to add an inline SVG like the following:

```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">...</svg>
```

When I did so, I got an `invalid_attribute` validation error for the `viewBox` attribute.

This is apparently due to the tag-and-attribute sanitizer expecting all attributes to be lower-case, and so it is not normalizing the attribute names to be lower case.

I did find a workaround which can be used in a sanitizer in the mean time:

```php
if ( $svg_element->hasAttribute( 'viewBox' ) ) {
	$svg_element->setAttribute( 'viewbox', $svg_element->getAttribute( 'viewBox' ) );
	$svg_element->removeAttribute( 'viewBox' );
}
```

**Comment by westonruter** [comment]
Need to confirm whether element/attribute casing is significant in an HTML context, whether lower-casing all attributes matters.

Also, rather than going to the effort of lower-casing all attribute names during validation, I think it may be preferable to simply add `viewBox` as an alternate name for `viewbox`. I'll investigate.

**Comment by pierlon** [comment]
Also see Mozilla's wiki on [SVG:Language:Regrets](https://wiki.mozilla.org/SVG:Language:Regrets#Mixed_case_element_and_attribute_names).

**Comment by westonruter** [comment]
Using this code:

```php
<?php
$dom = new DOMDocument();
$svg = '<svg width="391" height="391" viewBox="-70.5 -70.5 391 391" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"></svg>';
$dom->loadHTML( "<html><body>$svg</body></html>" );
echo $dom->saveHTML( $dom->getElementsByTagName( 'svg' )->item(0) );
```

The output:

```
Warning: DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 1 in /in/AGBMj on line 5
<svg width="391" height="391" viewbox="-70.5 -70.5 391 391" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"></svg>
```

Notice the warning that the `svg` element is not recognized. Notice also that even though `viewBox` is provided as input, the serialized output is `viewbox`. This must be because libxml isn't super up-to-date for HTML5 (and the fact that SVG can now be embedded in HTML), and since HTML attributes are case-insensitive, they are getting normalized as being lower case.

**Comment by westonruter** [comment]
Also, I can see actually that when the original HTML document being parsed contains `<svg viewBox="…">`, it will get serialized lower-case `<svg viewbox="…">`. Nevertheless, for the [AMP-IMG SVG Inliner](https://gist.github.com/westonruter/e0545fcd2dcc18c9263dff6ec0ac055d) plugin, this is resulting in the SVG referenced by `<img>` getting serialized as with the original camelCase: `<svg viewBox="…">`. The reason is that the plugin fetches the XML and parses it via `loadXML()` and then imports those XML elements into the _HTML_ document by the sanitizer. This allows the original camelCase attribute to be retained and not be normalized to lower-case.

This being the case, the issue here is actually not a big deal. I'm actually puzzled about how this error was first able to be produced.

**Comment by westonruter** [comment]
I can't remember the context from when I first opened this issue. So I may have been trying to do the very thing I just did today 😛

**Comment by westonruter** [comment]
The easy fix here is simply to use `loadHTML()` to parse SVG files, even though they are technically XML:

```diff
--- a/Sanitizer.php
+++ b/Sanitizer.php
@@ -83,17 +83,19 @@ class Sanitizer extends AMP_Base_Sanitizer {
 				continue;
 			}
 
-			// Work around viewBox attribute problem. See https://github.com/ampproject/amp-wp/issues/2045.
-			$svg_doc = preg_replace( '/(?<=\s)viewBox(?==)/', 'viewbox', $svg_doc );
-
 			$svg_dom = new DOMDocument();
-			if ( ! $svg_dom->loadXML( $svg_doc ) ) {
+			if ( ! @$svg_dom->loadHTML( $svg_doc ) ) { // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
 				$this->set_error_attribute( $img_element, 'xml_parse_error' );
 				continue;
 			}
 
-			/** @var DOMElement $svg_element */
-			$svg_element = $this->dom->importNode( $svg_dom->documentElement, true );
+			$svg_element = $svg_dom->getElementsByTagName( 'svg' )->item( 0 );
+			if ( ! $svg_element instanceof DOMElement ) {
+				$this->set_error_attribute( $img_element, 'svg_element_not_found' );
+				continue;
+			}
+
+			$svg_element = $this->dom->importNode( $svg_element, true );
 
 			/** @var DOMAttr $attribute */
 			foreach ( $img_element->attributes as $attribute ) {
```

This ensures that all the element names and attribute names are lower-cased. Pushed that patch up as part of https://gist.github.com/westonruter/e0545fcd2dcc18c9263dff6ec0ac055d

This being the case, and given that SVG that is originally in the HTML document will be normalized with lower-case from the start, this issue is of very low importance and we might even consider closing this issue as wontfix.
