### ISSUE TITLE
Failing validation manager test

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2053]
`Test_AMP_Validation_Manager::test_add_block_source_comments` seems to be failing on Travis with the `latest_posts` data set. The tests are now running against the newly released 5.4 version of Gutenberg, so maybe that's the reason.

Opening this issue here to track this.

Noticed while working on #2046.

**Comment by westonruter** [comment]
@swissspidy This should be fixed in https://github.com/ampproject/amp-wp/pull/2051/commits/dc3d6c4b341f40c7830a6168355fe4d152cc9ce6 as part of https://github.com/ampproject/amp-wp/pull/2051. I merged it into `amp-stories-redux`.
