### ISSUE TITLE
[AMP Stories] Reverse Bring Forward / Send Backward Logic

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2057]
Scenario:

1. Insert Text block
2. Insert image block

Expected result: Text block is shown below image block in block navigation, because it is visually underneath the image as well.

Next, click on Up arrow, assuming that it brings the Text block up in the visual hierarchy.

Actual result: Text block is sent backward.

Take this screenshot as an example:

<img width="818" alt="Screenshot 2019-04-03 at 17 44 36" src="https://user-images.githubusercontent.com/841956/55497207-c7196b80-5638-11e9-95cb-520dac2e518a.png">

On the left, the text is on top. On the right, the image is on top.

Suggested change:

1. Reverse list in the block navigation.
2. Reverse action of Bring Forward / Send Backward arrows. Clicking on the Up arrow should bring the block up, clicking on the Down arrow should move the block behind the other one

These are only visual changes for the users, as I think these are more clear.

**Comment by swissspidy** [comment]
For Bring Forward and Send Backward, I like how tools like Keynote or Google Slides are offering these options:

<img width="273" alt="Screenshot 2019-04-04 at 15 55 44" src="https://user-images.githubusercontent.com/841956/55572495-9cdeb100-56ff-11e9-9a33-08368d47e9d7.png">
<img width="274" alt="Screenshot 2019-04-04 at 15 55 33" src="https://user-images.githubusercontent.com/841956/55572498-9cdeb100-56ff-11e9-8cf6-9cff79139f72.png">

**Comment by dawidmlynarz** [comment]
@swissspidy I agree with your point. Elements that are in the Editor and exist above other elememnts should be shown in the Block navigation on the top.

Here is how the icons look in Sketch as well for moving Forward/Backward.

<img width="148" alt="Sketch icons" src="https://user-images.githubusercontent.com/8026823/55610790-f7b9ec00-5783-11e9-9306-5a92851ee7a1.png">

I like the Keynote icons though much better but these are a little bit more complex to fir in small areas!

**Comment by swissspidy** [comment]
Thanks for chiming in @dawidmlynarz! I was thinking about eventually adding icons similar to the Keynote ones the block sidebar on the right side of the screen. There we would have similar amount of space for that like in Keynote. Something for another iteration though :-)

**Comment by dawidmlynarz** [comment]
@swissspidy Awesome! Do you want me to explore the possible look of the icon (Keynote style) ?

**Comment by swissspidy** [comment]
Sure! I imagine they could look well in a Gutenberg-like black & white design.

**Comment by csossi** [comment]
Verified in QA

**Comment by dawidmlynarz** [comment]
@swissspidy I have managed to create icons for moving Backward / Forward. Let me know if that works and I will send you SVGs.

![backward-forward-icons](https://user-images.githubusercontent.com/8026823/56357852-2b156580-61dd-11e9-9dfd-026b06a4e4d1.png)
