### ISSUE TITLE
[AMP Stories] Style the quote block to match template designs.

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2065]
Add style to the quote block based on this template design:
- https://projects.invisionapp.com/share/8QR858KUNWK#/screens/355151903

**Comment by miina** [comment]
Notes for QA.

Every block can have additional block styles, for seeing the available block styles, this icon is used:
![Screen Shot 2019-04-11 at 12 09 26 AM](https://user-images.githubusercontent.com/3294597/55917043-61a41c80-5bee-11e9-9c3a-621ea621feae.png)

**Comment by csossi** [comment]
Icon revealing other block styles. Verified in QA
