### ISSUE TITLE
Expand/collapse all header arrows are not aligned properly

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2078]
![image](https://user-images.githubusercontent.com/134745/55676840-c16a9280-5891-11e9-8cda-1e616e6e6623.png)

![image](https://user-images.githubusercontent.com/134745/55676834-aac43b80-5891-11e9-9d97-9952aae2ca3a.png)

The issue is more pronounced when focus styles are applied:

![image](https://user-images.githubusercontent.com/134745/55676848-d1827200-5891-11e9-9c36-02025471c832.png)

![image](https://user-images.githubusercontent.com/134745/55676851-d8a98000-5891-11e9-8f83-cae9433e29b2.png)

**Comment by csossi** [comment]
Verified in QA
