### ISSUE TITLE
Add ability to opt-in to a beta release channel

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2084]
In order to facilitate testing beta versions of the plugin, we should consider allowing a user to opt-in to a beta channel which would pull updates from pre-releases on GitHub.

**Comment by swissspidy** [comment]
Downloading from GitHub is against the [plugin directory guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#8-plugins-may-not-send-executable-code-via-third-party-systems). Quote:

> Executing outside code within a plugin when not acting as a service is not allowed, for example:
> 
>  * Serving updates or otherwise installing plugins, themes, or add-ons from servers other than WordPress.org’s

We should probably just use `trunk` for pre-releases, which is commonly done anyway. Plus, this way people can already translate pre-release versions, which is quite useful too.

**Comment by westonruter** [comment]
Good point. But we could have the plugin updater configured to pull from `trunk` on WordPress.org? Just wanting to avoid manual ZIP file wrangling.

**Comment by swissspidy** [comment]
We'd have to check what http://api.wordpress.org/plugins/update-check/1.1/ supports.

Most probably we'd just have to filter some transients to point to the trunk ZIP file, and then probably provide a way to downgrade.

**Comment by westonruter** [comment]
I recently used the [Jetpack Beta Tester](https://jetpack.com/download-jetpack-beta/) plugin which was really slick, but it is perhaps overkill for the AMP plugin. It allows selecting a feature branch from which to automatically install build.

**Comment by jdelia** [comment]
Are they any instructions on how we should update the plugin on our installs when testing the beta and RC versions? So far, I've just been deleting the existing plugin, installing the new from the built zip and then renaming the plugin folder to `amp`.

**Comment by swissspidy** [comment]
At the moment that's the recommended and most common approach. Although there should be no need to rename the plugin because a) you deleted the old one and b) the new one should be named `amp` already.

We want to make this process easier though, which this issue here is for.

**Comment by jdelia** [comment]
Thank you. The beta and RC zips when installed are not creating an `amp` folder. You'll see this message in the dashboard for example: `You appear to have installed the AMP plugin incorrectly. It is currently installed in the amp-wp-1.2.1-RC1-built directory, but it needs to be placed in a directory named amp. Please rename the directory. This is important for WordPress plugin auto-updates.`

**Comment by swissspidy** [comment]
Does this also happen when downloading `amp.zip` from https://github.com/ampproject/amp-wp/releases/tag/1.2.1-RC1? Because that should be the go-to resource for downloading the pre-release version.

**Comment by jdelia** [comment]
It does not happen when I use the link you provided. I was using this zip file here before. https://cl.ly/afc69f45e481
That also solves my issue in #3063 with the story templates not displaying correctly.

**Comment by westonruter** [comment]
Right, you should only use the `amp.zip` on the 1.2.1-RC1 release. The *-built tags are only for use with git submodules or perhaps composer. It is actually the same as `amp.zip` but you just need to rename the ZIP file to also be `amp.zip`.

**Comment by pierlon** [comment]
Perhaps this could be an option on the settings page, for example:

![image](https://user-images.githubusercontent.com/16200219/67117949-7a971700-f1a9-11e9-94af-a2c62201a6f1.png)

**Comment by westonruter** [comment]
> Perhaps this could be an option on the settings page, with the date of the last successful retrieval being displayed.

I think the opt-in can simply be the activation of the AMP Beta Tester plugin.

The AMP Beta Tester plugin itself could be developed as part of the AMP plugin repo, for example it could be located next to `amp.php` as `amp-beta-tester.php` which we then exclude from the build that is pushed to WordPress.org, but we could perhaps include it in non-stable release builds. Maybe that would be a convenient place for it to live.  This would allow for AMP and AMP Beta Tester to be listed in the list of WordPress.org plugins when someone installs a non-stable build, and they could activate “AMP Beta Tester” to automatically download new pre-release versions. This plugin, when active, should enable auto-updates for the AMP plugin.

**Comment by pierlon** [comment]
I'm on-board with that idea. I think some sort of notification should be shown as well to let remind them that they are using an unstable version of the plugin.

**Comment by swissspidy** [comment]
Uploading betas or at least RCs to `trunk` on WordPress.org would be nice in order to give translators some additional time to  translate. At least in the long term.

**Comment by westonruter** [comment]
@adamsilverstein Given your current work doing something similar to Site Kit (https://github.com/google/site-kit-wp/pull/1172) could you please review #3560 and provide insights? I'm not familiar with GitHub Actions, so it's difficult for me to evaluate. I'm also curious if the approaches taken in the AMP plugin and the Site Kit plugin can be harmonized/reused.

**Comment by pierlon** [comment]
@westonruter I think you meant #3799. #3560 is the AMP Beta Tester plugin.

The GitHub Actions added in https://github.com/google/site-kit-wp/pull/1172 are similar to what I was working on in #3799; I'll copy some of @adamsilverstein's work since its been reviewed and tested already, if he doesn't mind :smile:.

**Comment by westonruter** [comment]
I think it's both. He's also done work on a beta tester plugin.

**Comment by pierlon** [comment]
Oh that's great, feedback is welcome on both!

**Comment by adamsilverstein** [comment]
@pierlon Yes, please take advantage of what we built there, it got quite refined from my initial approach. 

For our needs, we decided to leverage the built in wiki repository each GitHub repository gets to store our build artifacts (installable wp plugin zips), (we considered several other approaches including a secondary "build" repository, or using "GitHub build artifacts").

Let me know if you have any questions.

**Comment by westonruter** [comment]
@pierlon This is now available via the AMP QA Tester plugin, with the exception that if you choose the `develop` branch, there won't be auto-updates, correct?

**Comment by pierlon** [comment]
Correct, I'll open an issue to track that functionality. This issue can be closed too.
