### ISSUE TITLE
[AMP Stories] Focal point of the background image is not right.

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2085]
Steps to reproduce:
- Add a story Page with background image and set focal point.
- Compare the results in the front-end versus editor:

Editor:
![Screen Shot 2019-04-08 at 7 32 51 PM](https://user-images.githubusercontent.com/3294597/55744406-214d6e80-5a35-11e9-876f-05e77c1bf8d0.png)

FE: 
![Screen Shot 2019-04-08 at 7 33 16 PM](https://user-images.githubusercontent.com/3294597/55744425-362a0200-5a35-11e9-90c4-be8ce3d57900.png)

**Comment by swissspidy** [comment]
Leaving this open for a moment as per https://github.com/ampproject/amp-wp/pull/2104#issuecomment-481618142

**Comment by westonruter** [comment]
@swissspidy Was this closed because it you fixed the issue in https://github.com/ampproject/amp-wp/pull/2104#issuecomment-481618142?

**Comment by swissspidy** [comment]
@westonruter I closed it because that bug apparently was not related to this issue/PR, as it looks like it has already happened before. I thought I created a separate issue for it, but I suppose not. I created #2112 now.
