### ISSUE TITLE
[AMP Stories] Page preview when reordering is not displaying correct view

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2086]
Page in the editor:
![Screen Shot 2019-04-08 at 7 36 51 PM](https://user-images.githubusercontent.com/3294597/55744639-b51f3a80-5a35-11e9-923d-bdb1fc1902e9.png)

Template preview:
![Screen Shot 2019-04-08 at 7 36 35 PM](https://user-images.githubusercontent.com/3294597/55744640-b51f3a80-5a35-11e9-87ea-5a961371cfe6.png)

**Comment by swissspidy** [comment]
So this is basically a follow-up to #2050?

**Comment by miina** [comment]
Hmm, I guess so. That's something that @westonruter noted as an issue -- that the reordering preview was not displaying correctly, as seen on the screenshots in the description.

The screenshots were taken yesterday so I'm assuming that the issue didn't get fully resolved within #2050.

The related PR is #2099, however, that's still not getting a 1-1 match. Also, it's likely that with adding the templates some issues will come out in the template preview, too.

If that's something you prefer to look at yourself to make it ideal then feel free to continue :)

**Comment by westonruter** [comment]
Closing as I merged #2099

**Comment by miina** [comment]
Notes for QA.
For reordering the Pages, this icon is used:
![Screen Shot 2019-04-11 at 12 06 01 AM](https://user-images.githubusercontent.com/3294597/55916809-b2ffdc00-5bed-11e9-9915-d07c5fa639dd.png)

**Comment by csossi** [comment]
I added an image to a new Story. On selecting the image from the media library, I was returned to the post.  The + and reordering icons were no longer appearing.

Noticed that the click areas are still there, but user can't see them

![image](https://user-images.githubusercontent.com/16945664/55990468-b9d23180-5c75-11e9-85fb-0c60cc2b6a87.png)

**Comment by westonruter** [comment]
@csossi I observed this as well on an older state of the plugin. However, with the latest deploy the phantom white overlay seems to have gone away. Please check again.

**Comment by csossi** [comment]
Verified in QA
