### ISSUE TITLE
[AMP Stories] Text Block: Allowed HTML is being escaped

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2087]
Steps to reproduce:
- Add a Text block with italic.
- Save and refresh the page.

**Comment by miina** [comment]
@swissspidy I'm assigning it to you and moving into In Progress since you mentioned investigating this. Feel free to undo this if that's not correct information.

**Comment by swissspidy** [comment]
I am also going to tackle issues with `<br>` validation errors in this ticket.

**Comment by csossi** [comment]
<em> tags still appearing here:
![image](https://user-images.githubusercontent.com/16945664/55990784-9d82c480-5c76-11e9-8f05-fc3e4e1208e3.png)

**Comment by csossi** [comment]
Site updated and fix is visible. Verified in QA
