### ISSUE TITLE
[AMP Stories] CTA block not displaying correctly.

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2098]
CTA block should appear as the last 20% of the Page, at this moment this doesn't seem to be happening. Also, the button styling seems to be off.

![Screen Shot 2019-04-09 at 5 59 55 PM](https://user-images.githubusercontent.com/3294597/55815881-6df67f80-5af1-11e9-838f-97f8c8e14895.png)

**Comment by miina** [comment]
Perhaps something got lost with the CSS changes?
cc @swissspidy

**Comment by swissspidy** [comment]
Most probably, yes. Will look into it as soon as possible.
