### ISSUE TITLE
Video blocks can cause validation errors in AMP Stories

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2109]
When adding a video block to an AMP Story page and hitting Save an AMP validation error appears:

> <img width="1164" alt="Screen Shot 2019-04-11 at 09 52 25" src="https://user-images.githubusercontent.com/134745/55976301-b07aa200-5c40-11e9-9b37-6d1e8f0154d2.png">

This is due to the video not having:

* `autoplay`
* `poster`

When supplying these the validation error goes away:

> ![image](https://user-images.githubusercontent.com/134745/55976406-f2a3e380-5c40-11e9-86bb-9ef706bf2f13.png)

When a video is shown in an AMP Stories context, the `autoplay` toggle should be enabled by default and either disabled or hidden entirely.

Also, the `playsinline` toggle needs to be removed in the stories context since it is not allowed:

> ![image](https://user-images.githubusercontent.com/134745/55976552-7a89ed80-5c41-11e9-94be-1f28e7db9c9a.png)

Additionally, since we don't currently automatically extract a poster image from a video (see #903) there should be a warning displayed with either the poster field to indicate it is required.

**Comment by swissspidy** [comment]
To verify:

* When a video is shown in an AMP Stories context, the autoplay toggle should be enabled by default
* The "plays inline" option defaults to `false`
* When inserting a video, and the video has a featured image set, the featured image is automatically used as a poster image

**Comment by westonruter** [comment]
> * When a video is shown in an AMP Stories context, the autoplay toggle should be enabled by default
> * The "plays inline" option defaults to `false`

Note that the “autoplay” and “plays inline” options actually shouldn't be displayed at all:

![image](https://user-images.githubusercontent.com/134745/57672424-eeb30a80-75cc-11e9-881c-a538061a7ea6.png)

The video should automatically be autoplaying when you preview on the frontend.

**Comment by csossi** [comment]
On selecting a video from media Library and returning to editor, the controls that should be hidden appear (Weston's note above):
![image](https://user-images.githubusercontent.com/16945664/57780813-ff5f9f80-76f6-11e9-977a-98c641ad978f.png)

Note that if I remove focus from video (click somewhere else) and THEN click on the video, THEN the controls are removed:
![image](https://user-images.githubusercontent.com/16945664/57780968-451c6800-76f7-11e9-804f-4d54143c173a.png)

**Comment by swissspidy** [comment]
Thanks for testing! Given that we have #2283 for this specific issue with the hidden controls and focus, I am inclined to move this one to "Ready for merge" and continue testing on #2283 once that issue has been fixed.
