### ISSUE TITLE
[AMP Stories] Impossible to click on controls that overlap another page

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2110]
As reported by Alberto:

The controls of a block sometimes overlay the next page, and it is not possible to click on them without going to the next page

<img width="870" alt="Screen Shot 2019-04-11 at 9 41 35 AM" src="https://user-images.githubusercontent.com/841956/55978864-2c9cd600-5c91-11e9-9f09-b7b4065dc4ac.png">

Let's verify & fix it.

**Comment by westonruter** [comment]
Merged #2120.

**Comment by csossi** [comment]
Verified in QA

Block controls are at top of page

Example re: Text Block
![image](https://user-images.githubusercontent.com/16945664/57665037-63377a80-75c8-11e9-9620-550bbef5363c.png)

Example re: Image Block
![image](https://user-images.githubusercontent.com/16945664/57665072-86622a00-75c8-11e9-9b6c-1d29e26dea7e.png)
