### ISSUE TITLE
NaN warning for focal point picker

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2112]
I am now getting "Received NaN for the value attribute. If this is expected, cast the value to a string." warnings in the console when adding a background image.

Originally mentioned in https://github.com/ampproject/amp-wp/pull/2104#issuecomment-481618142, but apparently not caused by that PR.

**Comment by westonruter** [comment]
See also https://github.com/ampproject/amp-wp/pull/2038#issuecomment-482429194. Perhaps we actually should not use the focal point after all, and instead use cropping?

**Comment by kienstra** [comment]
**Maybe A Gutenberg Issue, Not This Plugin**

Hi @swissspidy,
This might be related to Gutenberg, not this plugin specifically. The same issue occurs with the [CoBlocks plugin](https://wordpress.org/plugins/coblocks/).

I opened https://github.com/WordPress/gutenberg/issues/15136 for this.

**Comment by swissspidy** [comment]
#2238 might have a fix for this.

**Comment by westonruter** [comment]
I've identified the fix needing to be in Gutenberg. This patch fixes the problem:

```diff
diff --git a/packages/components/src/focal-point-picker/index.js b/packages/components/src/focal-point-picker/index.js
index 85f8f3745..b0fca8c2c 100644
--- a/packages/components/src/focal-point-picker/index.js
+++ b/packages/components/src/focal-point-picker/index.js
@@ -27,7 +27,7 @@ export class FocalPointPicker extends Component {
 		this.state = {
 			isDragging: false,
 			bounds: {},
-			percentages: {},
+			percentages: FocalPointPicker.defaultProps.value,
 		};
 		this.containerRef = createRef();
 		this.imageRef = createRef();
```

I'll open a PR to Gutenberg.

**Comment by westonruter** [comment]
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/15400
