### ISSUE TITLE
[AMP Stories] Initial attachment caption for image block unexpectedly appears in story on frontend when unmodified

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2113]
Given an image that has a caption populated in the media library:

![image](https://user-images.githubusercontent.com/134745/55997960-3e6e8100-5c71-11e9-9b4f-6442ca55dbef.png)

In the editor this caption is not displayed and the caption toggle is turned off (by default):

![image](https://user-images.githubusercontent.com/134745/55998012-580fc880-5c71-11e9-96db-f5b92fda792b.png)

Nevertheless, on the frontend the caption is being displayed:

![image](https://user-images.githubusercontent.com/134745/55998580-af169d00-5c73-11e9-9dea-d3c0263d14e3.png)

If I toggle the caption on and off then it is truly removed as expected.

It seems that when adding an image from the media library, the caption's `figcaption` is present in the markup even though the toggle is off, so it is hidden. Toggling the caption on and off again seems to clear out the underlying `figcaption`.

**Comment by swissspidy** [comment]
Does this also happen in the default post editor?

**Comment by westonruter** [comment]
Inside the regular post editor, I see the caption from the DB when the image is first inserted. I can then empty it out manually to clear it out on the frontend. However, in the story editor, the caption is hidden by default in the editor, but this is not causing the caption to be hidden on the frontend by default.

**Comment by swissspidy** [comment]
Verified that the caption is hidden in both the story editor and on the front end.
