### ISSUE TITLE
Image caption is centered in story editor but appears left-justified on frontend

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2114]
![image](https://user-images.githubusercontent.com/134745/55998670-1df3f600-5c74-11e9-8338-e3bfb02cc0c3.png)

![image](https://user-images.githubusercontent.com/134745/55998679-277d5e00-5c74-11e9-8c96-f5412756dffd.png)

**Comment by swissspidy** [comment]
Caption position is identical on frontend and backend 👍
