### ISSUE TITLE
[AMP Stories] Disable Alignment for Image Block

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2115]
I tried changing the alignment options for an image in AMP Stories:

![image](https://user-images.githubusercontent.com/134745/55998782-95c22080-5c74-11e9-89fd-169e7f98c147.png)

But they had no effect on the image in the frontend. This is entirely expected, since the image is not inline with other blocks, being that it is absolutely positioned. So the alignment options should just be eliminated. This goes for other blocks as well.

**Comment by swissspidy** [comment]
Unfortunately the `core/image` block does not use the `align` option in `supports`, so the block alignment toolbar is pretty much hardcoded.

Otherwise we could use the `registerBlockType` filter to disable alignment for the block.

Related upstream issue: https://github.com/WordPress/gutenberg/issues/13780

**Comment by westonruter** [comment]
This is particularly confusing when a theme supports wide images, as there are even more buttons:

![image](https://user-images.githubusercontent.com/134745/56053451-f3a04800-5d08-11e9-8662-a8ba05cad5f4.png)

**Comment by swissspidy** [comment]
Looks like the alignment options are back now because of #2179.

But that screenshot doesn't show the current state of the stories editor either way...

**Comment by miina** [comment]
@swissspidy I think that the test environment wasn't updated, it should be now, however, this issue still needs addressing again.

**Comment by swissspidy** [comment]
Hmm there aren't really any good CSS selectors for the top toolbar to know which block is currently selected...

**Comment by miina** [comment]
Maybe one option could be adding an additional class name ourselves if an image block is selected?

**Comment by swissspidy** [comment]
Yeah I was thinking the same, as this would be needed for #2283 as well.

**Comment by swissspidy** [comment]
@csossi Can you test this again? Thanks!

**Comment by csossi** [comment]
Verified in QA:
Alignment disabled

![image](https://user-images.githubusercontent.com/16945664/57777001-cf140300-76ee-11e9-859d-2964cdbc4390.png)
