### ISSUE TITLE
Recipe schema - A value for the image field is required.

### ISSUE THREAD

**Issue by laserjobs** [ampproject/amp-wp#2124]
Not sure if this is a Google Structured Data issue or something to do with the AMP Recipe schema?

The issue started showing up Apr 7, 2019 in Google Search Console

image	A value for the image field is required.

Here is sample URL:
https://www.godairyfree.org/recipes/dairy-free-roasted-carrot-bisque-soup/amp

and the amp-img code in the Recipe Schema:

`<amp-img itemprop="image" src="https://www.godairyfree.org/wp-content/uploads/2019/04/pics-edf-roasted-carrot-bisque-small.jpg" width="205" height="205" class="amp-wp-enforced-sizes" layout="intrinsic"></amp-img>`

https://search.google.com/structured-data/testing-tool

**Comment by westonruter** [comment]
The `image` field in your Schema.org metadata in the head looks good:

```
"image":{"@type":"ImageObject","url":"https:\/\/www.godairyfree.org\/wp-content\/uploads\/2019\/04\/pics-edf-roasted-carrot-bisque-feature.jpg","width":1200,"height":800}
```

**Comment by westonruter** [comment]
The image for the recipe does look properly identified on the non-AMP page, so it may be an issue with the AMP plugin. I'll investigate further.

**Comment by westonruter** [comment]
Actually, it seems the issue may be the rich snippets doesn't understand the use of `itemprop=image` on an `amp-img`, as it doesn't understand that `amp-img` is an `img`.

But if you update to `1.1-beta2` you will see the original `img` will be added under the `amp-img` inside a `noscript` element with that `itemprop=image` retained. See #1832.

 I checked and this seems to fix the rich snippet, since there is an `img[itemprop=image]` again.

**Comment by westonruter** [comment]
You can find the latest 1.1 prerelease at https://github.com/ampproject/amp-wp/releases

Please test and confirm that it fixes your issue.

Thanks!

**Comment by laserjobs** [comment]
Thanks! It does fix the issue.

**Comment by equilibriumxco** [comment]
Hello, I just read this thread and I am having a similar issue with www.equilibriumx.com/amp
There are 2 errors reported but I don't understand why, cause It seems to be OK. Can you help me out?
Cheers

**Comment by westonruter** [comment]
@equilibriumxco It doesn't appear you are using  this AMP plugin. Also, this is not really an AMP question but a general Google Search question. Better ask at https://www.google.com/webmasters/support/
