### ISSUE TITLE
[Carousel] on desktop, only showing one image

### ISSUE THREAD

**Issue by vanlong441** [ampproject/amp-wp#2132]
### **This is the example of two images on initiation**

![image](https://user-images.githubusercontent.com/1689356/56107693-dcb05e80-5f71-11e9-8583-18e3c6f3b155.png)

### **This is my twenty nineteen using native AMP setting:**
![image](https://user-images.githubusercontent.com/1689356/56107711-fd78b400-5f71-11e9-8398-be2760f30f2b.png)

**Comment by westonruter** [comment]
What version of WordPress and which version of the plugin?

Please share the URL where the issue can be seen, or at least go to "view source" and copy the page source to share the markup that was output on the page.

Please also share the markup that you added and how you added it (e.g. in post content?)

**Comment by vanlong441** [comment]
@westonruter 

URL: https://207.148.65.206/lazy-image-test/

![image](https://user-images.githubusercontent.com/1689356/56111799-53a22300-5f83-11e9-9a10-4a047b287d28.png)

![image](https://user-images.githubusercontent.com/1689356/56111764-3ff6bc80-5f83-11e9-9622-9ce1a11a945f.png)

**Comment by westonruter** [comment]
So you are adding the photos via a Gallery block and then enabling the carousel option?

**Comment by vanlong441** [comment]
@westonruter 

yes

**Comment by westonruter** [comment]
OK, it looks to be behaving as expected actually. In your page I see the `amp-carousel` is defined as:

```html
<amp-carousel height="400" type="slides" layout="fixed-height">
```

Notice the `type=slides`. The example you pasted above is with `type=carousel`.

**Comment by vanlong441** [comment]
@westonruter 

All I did was tick the option "Display as carousel" but it somehow showed the wrong _type_. How is it on your side? 
I did a test using this example and it's working fine here: https://207.148.65.206/image-test/

`<amp-carousel height="300"
  layout="fixed-height"
  type="carousel">
  <amp-img src="/static/samples/img/image1.jpg"
    width="400"
    height="300"
    alt="a sample image"></amp-img>
  <amp-img src="/static/samples/img/image2.jpg"
    width="400"
    height="300"
    alt="another sample image"></amp-img>
  <amp-img src="/static/samples/img/image3.jpg"
    width="400"
    height="300"
    alt="and another sample image"></amp-img>
</amp-carousel>`

**Comment by westonruter** [comment]
It is _supposed_ to be a `slides` type. This is how it has always been. The `carousel` type has not been implemented for the gallery, so far.

**Comment by vanlong441** [comment]
I'm gonna manually add carousels for now. Any suggestion will be appreciated. If not, please feel free to close this issue.
Thanks @westonruter .

**Comment by westonruter** [comment]
Ok, perhaps we should provide a way to configure which type is used. We'll keep that in mind for the future.
