### ISSUE TITLE
[AMP Stories] Add opt-in toggle for enabling AMP stories

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2136]

**Comment by csossi** [comment]
still seems to just be refreshing page rather than opening in a new window

**Comment by swissspidy** [comment]
@csossi With refreshing page you mean open in the same tab? I believe the reason is just that this hasn't been deployed to the test environment yet.

**Comment by swissspidy** [comment]
Closing directly as this was such a tiny fix
