### ISSUE TITLE
Replace from data-src to src

### ISSUE THREAD

**Issue by GorobetsUA** [ampproject/amp-wp#2144]
I use data-src for img tags to defer images loading with the script. But it doesn't work with AMP. That's why I want AMP plugin to replace from data-src to src attribute. I tried to edit class-amp-iframe-sanitizer.php. But I had no success.
I need to have something like that:
`
		return array(
			'data-src' => array(
				'src',
			),`
But I don't know how to build in this code.

**Comment by westonruter** [comment]
How are you getting images to be generated with `data-src` in the first place? You should rather be preventing this from happening when `is_amp_endpoint()` returns true.

**Comment by GorobetsUA** [comment]
I added this script to my site. It duplicate url with src attribute.
`document.addEventListener("DOMContentLoaded", function() {
  var lazyloadImages;    
  if ("IntersectionObserver" in window) {
    lazyloadImages = document.querySelectorAll(".lazy");
    var imageObserver = new IntersectionObserver(function(entries, observer) {
      entries.forEach(function(entry) {
        if (entry.isIntersecting) {
          var image = entry.target;
          image.src = image.dataset.src;
          image.classList.remove("lazy");
          imageObserver.unobserve(image);
        }
      });
    });
    lazyloadImages.forEach(function(image) {
      imageObserver.observe(image);
    });
  } else {  
    var lazyloadThrottleTimeout;
    lazyloadImages = document.querySelectorAll(".lazy");
    function lazyload () {
      if(lazyloadThrottleTimeout) {
        clearTimeout(lazyloadThrottleTimeout);
      }    
      lazyloadThrottleTimeout = setTimeout(function() {
        var scrollTop = window.pageYOffset;
        lazyloadImages.forEach(function(img) {
            if(img.offsetTop < (window.innerHeight + scrollTop)) {
              img.src = img.dataset.src;
              img.classList.remove('lazy');
            }
        });
        if(lazyloadImages.length == 0) { 
          document.removeEventListener("scroll", lazyload);
          window.removeEventListener("resize", lazyload);
          window.removeEventListener("orientationChange", lazyload);
        }
      }, 20);
    }
    document.addEventListener("scroll", lazyload);
    window.addEventListener("resize", lazyload);
    window.addEventListener("orientationChange", lazyload);
  }
})`

**Comment by westonruter** [comment]
@GorobetsUA I mean the PHP code. What is the PHP code that is causing `img` to be output at `data-src` instead of `src`?

**Comment by GorobetsUA** [comment]
I do it manually ))

**Comment by westonruter** [comment]
In the template or in the post content?

**Comment by GorobetsUA** [comment]
In the post content. But I already understood that I move wrong way. It's better to use php to replace src to data-src. Using php I have no need to customize AMP plugin. I added the code below to function.php and everything works perfectly.

`add_filter('the_content', 'filter');
function filter($content) {
    return str_replace('src="', 'data-src="', $content);
}`

Thank you for your answers!
