### ISSUE TITLE
Percentage units and bogus values are erroneously permitted for width/height attributes

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2146]
Reported on the [support forum](https://wordpress.org/support/topic/pages-not-converting-to-amp-after-last-update/), when someone adds the normal Facebook Comments embed:

```html
<div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-width="100%" data-numposts="5"></div>
```

The AMP plugin currently outputs this as:

```html
<amp-facebook-comments layout="responsive" width="100%" height="400" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-numposts="5"></amp-facebook-comments>
```

The AMP validator then flags this as a validation error:

> The attribute 'width' in tag 'amp-facebook-comments' is set to the invalid value '100%'.

It's surprising that this is leaking through the sanitizers, but when looking at the PHP-generated spec data it's not surprising:

https://github.com/ampproject/amp-wp/blob/621a0502f56c8d8e00b4ddbd61bc5ff013307a40/includes/sanitizers/class-amp-allowed-tags-generated.php#L15997-L16005

There are no constraints on the `width` and `height` attributes as defined in the [Validator protoascii](https://github.com/ampproject/amphtml/blob/568e45a548dd8b4aead0ca2088b238247670820c/validator/validator-main.protoascii#L5183-L5197):

```
# AMP Layout attributes: implied for TagSpecs with amp_layout field
# set. Note that while these attributes are defined as optional here,
# depending on amp layout the validator will examine these fields and
# their values.
attr_lists: {
  name: "$AMP_LAYOUT_ATTRS"
  attrs: { name: "height" }
  attrs: { name: "heights" }
  attrs: { name: "layout" }
  attrs: { name: "sizes" }
  attrs: { name: "width" }
  # <amp-bind>
  attrs: { name: "[height]" }
  attrs: { name: "[width]" }
}
```

It appears that this is done because the validation constraints require conditional logic that is not feasible for the protoascii format. Instead, the [`validator.js`](https://github.com/ampproject/amphtml/blob/568e45a548dd8b4aead0ca2088b238247670820c/validator/engine/validator.js) has imperative logic in its [`CssLength`](https://github.com/ampproject/amphtml/blob/568e45a548dd8b4aead0ca2088b238247670820c/validator/engine/validator.js#L3246-L3314). In particular, it has this logic:

```js
    const re = /^(\d+(?:\.\d+)?)(px|em|rem|vh|vw|vmin|vmax)?$/;
    const match = re.exec(input);
    if (match !== null) {
      this.isValid = true;
      this.numeral = parseFloat(match[1]);
      this.unit = match[2] || 'px';
    }
```

The regular expression pattern does not include the `%` unit.

Now, the quick fix is to do:

```diff
--- a/includes/embeds/class-amp-facebook-embed.php
+++ b/includes/embeds/class-amp-facebook-embed.php
@@ -191,6 +191,11 @@ class AMP_Facebook_Embed_Handler extends AMP_Base_Embed_Handler {
 			'height' => $node->hasAttribute( 'data-height' ) ? $node->getAttribute( 'data-height' ) : $this->DEFAULT_HEIGHT,
 		);
 
+		if ( '100%' === $attributes['width'] ) {
+			unset( $attributes['width'] );
+			$attributes['layout'] = 'fixed-height';
+		}
+
 		$node->removeAttribute( 'data-width' );
 		$node->removeAttribute( 'data-height' );
```

But this will only fix the symptom and not the underlying problem. The lack of validator constraints for `width` and `height` means that any value can be supplied for these attributes and the sanitizer will not strip them out. For example:

```html
🚫<amp-img src="https://example.com/img.jpeg" width="bogus" height="100" layout="fixed"></amp-img>
```

I think what we need to do is extend `\AMP_Tag_And_Attribute_Sanitizer::delegated_sanitize_disallowed_attribute_values_in_node()` to consider the logic for the supported layouts for a given element, and apply the constraints for the allowed value (and units), and check that the `layout` matches `width`/`height` attributes. For example, if `layout=fixed-height` then `width` can be omitted or be set to `auto`. 

If the `width` or `height` are missing, then the entire element needs to be removed.

**Comment by westonruter** [comment]
This would essentially be revisiting https://github.com/ampproject/amp-wp/pull/1075.

**Comment by pierlon** [comment]
Tests done during code review are deemed as sufficient for QA.
