### ISSUE TITLE
[AMP Stories] Request for AMP stories beta built release to use for testing in Composer-based stack

### ISSUE THREAD

**Issue by davisshaver** [ampproject/amp-wp#2151]
Super excited to test this! A built version would make this a little easier. I wasn't sure if we typically did builds for betas. But it would be nice!

**Comment by westonruter** [comment]
Here you go: https://github.com/ampproject/amp-wp/releases/tag/1.2-alpha1-built

**Comment by davisshaver** [comment]
Thanks @westonruter!
