### ISSUE TITLE
[AMP Stories] Resizing core blocks is not responsive

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2159]
Resizing any block should be responsive and appear in the FE similarly as in the editor. Currently, when resizing an image block or a quote block for example it displays incorrectly in the FE.

In the editor:
![Screen Shot 2019-04-22 at 10 04 22 AM](https://user-images.githubusercontent.com/3294597/56490620-0d4e4600-64e6-11e9-9a7e-ccce7e320dad.png)

In the FE:
![Screen Shot 2019-04-22 at 10 04 03 AM](https://user-images.githubusercontent.com/3294597/56490625-13442700-64e6-11e9-8749-04995e5b6630.png)

**Comment by miina** [comment]
Instructions for testing:
- Create a block, for example an image block.
- Resize the image.
- Verify that in the frontend the image size is accurate, e.g. if the image was resized to cover the full width, then it covers the full width. If it was resized to cover half of the width, it covers half, etc.

**Comment by csossi** [comment]
Verified in QA

Example
Editor:
![image](https://user-images.githubusercontent.com/16945664/57807355-00acbe80-772f-11e9-8009-5fee0a26e4a4.png)

Front-End:
![image](https://user-images.githubusercontent.com/16945664/57807399-17ebac00-772f-11e9-9c42-988649bbbc6d.png)
