### ISSUE TITLE
[AMP Stories] Setting colors for the quote block doesn't work

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2160]
Changing colors of the quote block doesn't work. Consider removing the color settings for now. 

Currently, SVG is used for the icon of the quote block and the color of this wouldn't be changeable without extending the quote block to change the markup, it's not doable just by styling. Since at this moment we have two different quote styles, white and default, then, for now, we could just remove the non-functional color settings.

**Comment by swissspidy** [comment]
@miina Was there work being done here? Which PR is associated with this issue?

**Comment by amedina** [comment]
Reopening to keep in our radar till the PR is linked.

**Comment by swissspidy** [comment]
Ah, looks like it was #2164.

**Comment by swissspidy** [comment]
Related: #2282

**Comment by miina** [comment]
> Ah, looks like it was #2164.

That's correct, at some moment color settings were added to all the blocks, even those where there are no color settings needed, the solution for this issue was to remove the color settings. Note that by default the block does not have color settings, only the pullquote block has.
