### ISSUE TITLE
[AMP Stories] Drag-drop and resizing are not accurate after the editor width/height change

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2161]
The width of the Page was changed, however, dragging-dropping blocks and resizing the blocks is still considering the previous width in calculations.

Todo: Update the calculations to consider the new width and height values.

**Comment by miina** [comment]
Instructions for testing:
- Drag any block, especially more to the right side.
- Verify that the block is moved to the correct position and it doesn's make a jump when finishing dragging.

**Comment by csossi** [comment]
Verified in QA

Am able to drag different block types to new positions

Example:
![image](https://user-images.githubusercontent.com/16945664/57864761-7a45ba80-77ca-11e9-9bcc-1efc850655f4.png)
