### ISSUE TITLE
Text Block with background displays incorrectly when resized very small

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2162]
Text Block's resizing doesn't consider very small Text Blocks, especially with background color set.

In the editor, the fixed padding applied to any Text Block with background color causes the area to display larger than it actually is.

Editor: 
![Screen Shot 2019-04-22 at 10 22 01 AM](https://user-images.githubusercontent.com/3294597/56491419-bd24b300-64e8-11e9-9bc5-49db066bc696.png)

FE:
![Screen Shot 2019-04-22 at 10 22 07 AM](https://user-images.githubusercontent.com/3294597/56491444-d2014680-64e8-11e9-9bd6-c2e57f4a36ee.png)

**Comment by swissspidy** [comment]
Maybe the suggestion in #2224 helps here..?

**Comment by swissspidy** [comment]
As discussed in #2191, this needs more than simply adjusting padding.

I was wondering if perhaps the percentage calculation for frontend display is a bit off. Perhaps `getPercentageFromPixels()` should use `.toFixed()` instead of `Math.round()`, for example, to make this more accurate.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create new story
2. Create text blocks, with and without background colors
3. Resize blocks to make them very small
4. Verify that they look the same on the frontend and in the editor

**Comment by csossi** [comment]
Resized to this:
![image](https://user-images.githubusercontent.com/16945664/58027893-9bb6e700-7ae7-11e9-87ac-671991c476c8.png)

But appearing in preview like this:
![image](https://user-images.githubusercontent.com/16945664/58027941-b1c4a780-7ae7-11e9-8ab8-4d6411a95396.png)

**Comment by miina** [comment]
@swissspidy Could this be related to #2296?

It looks like `amp-fit-text` considers the words not breaking, however, the editor doesn't.

This doesn't seem to be directly related to this specific issue and possibly also not to #2296, so we could potentially create a new bug issue for that. Thoughts?

**Comment by miina** [comment]
@swissspidy I created a separate issue for this, especially since it's not directly related to this specific issue here.

https://github.com/ampproject/amp-wp/issues/2359
