### ISSUE TITLE
Tag amp-img with no image

### ISSUE THREAD

**Issue by vitorh45** [ampproject/amp-wp#2168]
A tag amp-img is created, but no image is shown. The tag has a height with Xpx and looks like a gap on the top of the post.

**Comment by westonruter** [comment]
@vitorh45 Please share the URL for the AMP page that has the problem, and also include a screenshot.

**Comment by vitorh45** [comment]
As you requested, here are the missing details.
The [link](https://www.lendico.com.br/blog/emprestimo-com-celular-como-garantia/amp/).

![Screen Shot 2019-04-23 at 11 15 37](https://user-images.githubusercontent.com/981623/56588181-3e4b7b00-65b9-11e9-90e3-eeef44332fa3.png)

**Comment by westonruter** [comment]
The problem is that you have a lazy-load plugin which is not disabling itself in AMP responses. In AMP, all images are lazy-loading. The lazy-loading plugin you have is rewriting `src` as `data-src` like so:

```html
<amp-img width="847" height="393" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" class="attachment-large size-large csco-lazyload lazyload wp-post-image amp-wp-enforced-sizes" alt="mulher olhando celular preocupada" data-src="https://www.lendico.com.br/blog/wp-content/uploads/2019/04/emprestimo-celular-garantia.jpg" data-sizes="auto" data-srcset="https://www.lendico.com.br/blog/wp-content/uploads/2019/04/emprestimo-celular-garantia.jpg 847w, https://www.lendico.com.br/blog/wp-content/uploads/2019/04/emprestimo-celular-garantia-800x371.jpg 800w, https://www.lendico.com.br/blog/wp-content/uploads/2019/04/emprestimo-celular-garantia-320x148.jpg 320w, https://www.lendico.com.br/blog/wp-content/uploads/2019/04/emprestimo-celular-garantia-560x260.jpg 560w, https://www.lendico.com.br/blog/wp-content/uploads/2019/04/emprestimo-celular-garantia-240x111.jpg 240w, https://www.lendico.com.br/blog/wp-content/uploads/2019/04/emprestimo-celular-garantia-360x167.jpg 360w, https://www.lendico.com.br/blog/wp-content/uploads/2019/04/emprestimo-celular-garantia-380x176.jpg 380w, https://www.lendico.com.br/blog/wp-content/uploads/2019/04/emprestimo-celular-garantia-680x316.jpg 680w, https://www.lendico.com.br/blog/wp-content/uploads/2019/04/emprestimo-celular-garantia-20x9.jpg 20w" layout="intrinsic">...</amp-img>
```

Which image-lazyloading plugin are you using?

**Comment by vitorh45** [comment]
I'm not sure, but I think we are using Azion. I'm gonna check with the other developers and comment here the result. 
Thanks for your help.

**Comment by westonruter** [comment]
What your site should be doing is short-circuiting the lazy images when it is an AMP response, as seen in Jetpack's module:

https://github.com/Automattic/jetpack/blob/217827417bdff01ebb2dc7b2ec575c36fd2555ed/modules/lazy-images/lazy-images.php#L43

You can check if: `function_exists( 'is_amp_endpoint' ) && is_amp_endpoint()`. This should be checked at the `template_redirect` action.

**Comment by vitorh45** [comment]
We removed the lazy loading option in our WP there and it's working fine.
Nobody here is an expert in PHP, so we might let the lazy loading off for now.
Other people are checking if this change is ok.
Thanks for your quick reply.
