### ISSUE TITLE
Suggestion: display CSS sizes in Compatibility Tool (move manifest)

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#2169]
@billerickson had a good suggestion, that it would be useful to display the CSS sizes in the Compatibility Tool. 

It would help developers see how close they are to the limit.

This could include the total CSS size for all files, the size of each file or `<style>` element, and the source of each.

It might be similar to the comment printed above the `<style amp-custom>`. For example, in https://make.xwp.co/?amp:

```html
<!--
The style[amp-custom] element is populated with:
     0 B: style[amp-custom=]
   198 B: link#twentyfifteen-jetpack-css[rel=stylesheet][id=twentyfifteen-jetpack-css][href=https://make.xwp.co/wp-content/plugins/jetpack/modules/theme-tools/compat/twentyfifteen.css?ver=6.5][type=text/css][media=all]
    86 B: link#jetpack_related-posts-css[rel=stylesheet][id=jetpack_related-posts-css][href=https://make.xwp.co/wp-content/plugins/jetpack/modules/related-posts/related-posts.css?ver=20150408][type=text/css][media=all]
     0 B: style#jetpack_related-posts-inline-css[id=jetpack_related-posts-inline-css][type=text/css]
   403 B: link#dashicons-css[rel=stylesheet][id=dashicons-css][href=https://make.xwp.co/wp-includes/css/dashicons.min.css?ver=4.9.8][type=text/css][media=all]
    90 B: link#jetpack_likes-css[rel=stylesheet][id=jetpack_likes-css][href=https://make.xwp.co/wp-content/plugins/jetpack/modules/likes/style.css?ver=6.5][type=text/css][media=all]
   942 B: link#genericons-css[rel=stylesheet][id=genericons-css][href=https://make.xwp.co/wp-content/plugins/jetpack/_inc/genericons/genericons/genericons.css?ver=3.1][type=text/css][media=all]
 26293 B: link#twentyfifteen-style-css[rel=stylesheet][id=twentyfifteen-style-css][href=https://make.xwp.co/wp-content/themes/twentyfifteen/style.css?ver=1.9][type=text/css][media=all]
   109 B: style#twentyfifteen-style-inline-css[id=twentyfifteen-style-inline-css][type=text/css]
   253 B: link#jetpack-widget-social-icons-styles-css[rel=stylesheet][id=jetpack-widget-social-icons-styles-css][href=https://make.xwp.co/wp-content/plugins/jetpack/modules/widgets/social-icons/social-icons.css?ver=20170506][type=text/css][media=all]
     0 B: link#amp-default-css[rel=stylesheet][id=amp-default-css][href=https://make.xwp.co/wp-content/plugins/amp/assets/css/amp-default.css?ver=1.0-beta4-ec11c489-20180924T013410Z][type=text/css][media=all]
   886 B: link#make-xwp-style-css[rel=stylesheet][id=make-xwp-style-css][href=https://make.xwp.co/wp-content/themes/make-xwp/style.css?ver=0.2][type=text/css][media=all]
    29 B: style[type=text/css]
     0 B: style#syntaxhighlighteranchor[type=text/css][id=syntaxhighlighteranchor]
     0 B: style#wp-custom-css[type=text/css][id=wp-custom-css]
     0 B: link#jetpack-responsive-videos-style-css[rel=stylesheet][id=jetpack-responsive-videos-style-css][href=https://make.xwp.co/wp-content/plugins/jetpack/modules/theme-tools/responsive-videos/responsive-videos.css?ver=4.9.8][type=text/css][media=all]
    75 B: div.amp-wp-cb45893[class=amp-wp-cb45893]
Total included size: 29364 bytes
-->
<style amp-custom>
```

Related: #1801 (showing sizing information in the admin bar).

**Comment by westonruter** [comment]
That's a good idea. After #1843 this comment is only displayed when in `WP_DEBUG` or if there is `excessive_css`. However, it would be useful to always have access to that for any validated URL.

**Comment by westonruter** [comment]
I think we should should actually eliminate the HTML comment in favor of showing the data in the validated URL screen entirely.

**Comment by westonruter** [comment]
Related: #2917 (adding support for sourcemaps for amp-custom styles)

**Comment by pierlon** [comment]
I'm unsure what are the implementation details for this. Here's what I have so far:

- If a page is over the maximum stylesheet limit, display a warning/error showing the total stylesheet size (perhaps in the Status postbox container?)

- Each "Excessive CSS" error would include the stylesheet size

**Comment by pierlon** [comment]
Moving this back to the _To Do_ column as I haven't made any progress with this as yet.

**Comment by westonruter** [comment]
This is now ready for testing in #4026.

**Comment by pierlon** [comment]
Testing instructions:

1. Visit the AMP Validated URL page for a post

2. Verify that:
    1. The "Stylesheets" meta box is present. For example:
    
    ![image](https://user-images.githubusercontent.com/16200219/73575684-9a103200-4470-11ea-8e49-f84a089ac065.png)

    2. It shows what CSS was removed during tree-shaking and what CSS remains:

    ![image](https://user-images.githubusercontent.com/16200219/73575814-e5c2db80-4470-11ea-88b7-85bc4e04f21c.png)

    3. It shows where a stylesheet came from:
    
    ![image](https://user-images.githubusercontent.com/16200219/73575881-0723c780-4471-11ea-8e94-06454410eee4.png)

    4. It shows the CSS usage in the admin bar when viewing the AMP post:

    ![image](https://user-images.githubusercontent.com/16200219/73576054-78fc1100-4471-11ea-9c8e-2ce27a190344.png)

**Comment by csossi** [comment]
Verified in QA
