### ISSUE TITLE
Font sizes should be theme-independent

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2178]
One thing we noticed last week is that the list of available font sizes changes depending on which theme you are using, as the theme might be declaring font sizes using `add_theme_support()`.

We should provide our own list of font sizes at all times, so that the list is guaranteed to be safe.

**Comment by swissspidy** [comment]
Note: When we solve this, we should be able to undo de81615e3af6ce79cac8dc09208608d758306d3b and correctly use `getFontSize()` instead of trying to roll our own.

**Comment by swissspidy** [comment]
Here's what Twenty Nineteen does:

```php
// Add custom editor font sizes.
add_theme_support(
	'editor-font-sizes',
	array(
		array(
			'name'      => __( 'Small', 'twentynineteen' ),
			'shortName' => __( 'S', 'twentynineteen' ),
			'size'      => 19.5,
			'slug'      => 'small',
		),
		array(
			'name'      => __( 'Normal', 'twentynineteen' ),
			'shortName' => __( 'M', 'twentynineteen' ),
			'size'      => 22,
			'slug'      => 'normal',
		),
		array(
			'name'      => __( 'Large', 'twentynineteen' ),
			'shortName' => __( 'L', 'twentynineteen' ),
			'size'      => 36.5,
			'slug'      => 'large',
		),
		array(
			'name'      => __( 'Huge', 'twentynineteen' ),
			'shortName' => __( 'XL', 'twentynineteen' ),
			'size'      => 49.5,
			'slug'      => 'huge',
		),
	)
);
```

Here are the default values in Gutenberg:

https://github.com/WordPress/gutenberg/blob/b421fc9574a7f437fb5068f8b6100db8f2926956/packages/block-editor/src/store/defaults.js#L89-L115

We can probably just use the defaults. They're already translated and quite reasonable I think.

**Comment by swissspidy** [comment]
@miina Since you have worked on the font sizes before, would you mind doing a review here?

**Comment by miina** [comment]
@swissspidy Seems to work as expected. Tested it with different themes and the font sizes are consistent.

**Comment by miina** [comment]
Instructions for testing:
- Add a Text block.
- Check the available font sizes in the Block Sidebar on the right.
- Make sure that the font sizes available stay the same when using different WordPress themes.

**Comment by csossi** [comment]
Verified in QA

Font sizes (normal, 13, 20, 36, 48) remain consistent across all Theme selections

![image](https://user-images.githubusercontent.com/16945664/57861578-d1e12780-77c4-11e9-8c13-0e64d81460a9.png)
