### ISSUE TITLE
Force Top Toolbar

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2179]
Having the block toolbar attached to the block makes editing quite cumbersome when they can be resized (very small, overlapping other blocks) and rotated (hard to edit, warrants disabling block rotation) within a page.

It makes more sense to force the Top Toolbar to be active at all times for a better editing experience.

With this plus #1974, we're getting to a point where we don't need to show any block toolbar within a page anymore, but only the block itself.

This will make it easier to have accurate positioning within a page as well. (Think `scale()` in CSS)

Suggestion:

* [x] Filter editor settings to make sure `fixedToolbar` is always enabled.
* [ ] Maybe `subscribe()` to state changes to turn `fixedToolbar` on it somehow gets deactivated through something else.
* [x] Hide Fixed Toolbar option using CSS.

**Comment by swissspidy** [comment]
Created an issue upstream: https://github.com/WordPress/gutenberg/issues/15264

**Comment by swissspidy** [comment]
Related: #2231

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create new story with a few blocks
2. Verify that the block toolbar with block controls lives at the top of the page
3. Click on three dots in the upper right corner
4. Verify that there is no menu item to change the toolbar position

**Comment by csossi** [comment]
Verified in QA

- option to move not appearing in Options
Example - toolbar for Text block at top of page:
![image](https://user-images.githubusercontent.com/16945664/57726384-46995200-765d-11e9-91af-0a62b9bffce6.png)

Example - toolbar for Image block at top of page:
![image](https://user-images.githubusercontent.com/16945664/57726440-6fb9e280-765d-11e9-88ff-b123fbf412dc.png)
