### ISSUE TITLE
Disable/Filter Block Manager

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2180]
Recently, Gutenberg added a block manager that allows you to disable (unregister) certain blocks completely.

While that might make sense for things like the Verse block, we don't want people to be able to unregister the AMP story, ever.

Either by removing these blocks from the block manager if possible, or alternatively by completely hiding the block manager.

**Comment by swissspidy** [comment]
Opened an upstream issue here: #15265

**Comment by swissspidy** [comment]
As decided in the current meeting, we should just disable/hide the block manager as a whole. We already provide a trimmed down list of AMP-compatible blocks, so there's not much value in further disabling them.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Click on the three dots in the top right corner
1. Verify that in the dropdown there is _no_ "Block Manager" option

**Comment by csossi** [comment]
Verified in QA

"Block Manager" not appearing:
![image](https://user-images.githubusercontent.com/16945664/57725932-4fd5ef00-765c-11e9-8464-8f9e3bd6aebd.png)

**Comment by swissspidy** [comment]
This has regressed, see #2904.
