### ISSUE TITLE
Add Move Forward/Backward options to Block Sidebar

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2181]
As discussed in #2057, this is something we might want to consider.

Alternatively, there would be the drag and drop as proposed in #1974, although not sure how obvious that is for people.

**Comment by miina** [comment]
Hey @dawidmlynarz, following up on this comment: https://github.com/ampproject/amp-wp/issues/2057#issuecomment-480209982
Did you have time to look into the icons?

**Comment by miina** [comment]
@swissspidy @westonruter I'm wondering if this would be better in the Toolbar instead? Thoughts?

**Comment by swissspidy** [comment]
There are some proposed icons on that issue if you scroll down: https://github.com/ampproject/amp-wp/issues/2057#issuecomment-484462542

Not sure about the toolbar as it is already a bit crowded with some very different elements.

Or did you mean adding these options under the "More options" menu in the block toolbar (the three dots)? There are currently a few options there:

<img width="293" alt="Screenshot 2019-05-09 at 08 00 08" src="https://user-images.githubusercontent.com/841956/57463888-81038900-7230-11e9-8411-53ddf419da46.png">

That would be like Google Slides:

<img width="594" alt="Screenshot 2019-05-09 at 07 57 47" src="https://user-images.githubusercontent.com/841956/57463959-a98b8300-7230-11e9-998b-d3d882887c19.png">


As for the sidebar, I was thinking of something like Keynote:

<img width="272" alt="Screenshot 2019-05-09 at 07 57 28" src="https://user-images.githubusercontent.com/841956/57463949-a55f6580-7230-11e9-86ab-7e870b8507f4.png">

So there would be four controls in total

**Comment by miina** [comment]
I was thinking of maybe in the "More options" menu, however, we can try it out in the Block Sidebar at first and move it if it feels like it's not accessible enough. Maybe it's completely fine there, I don't have a very strong preference at this moment.

Thank you for pointing out the existing icons, I'll ask @dawidmlynarz for the additional 2 controls, too.

**Comment by swissspidy** [comment]
While waiting for icons I'd use some default up/down arrows in the meantime, just so we have an MVP that we can test already. Maybe we'll even realize that it doesn't quite work before Dawid spends too much time on icons.

**Comment by miina** [comment]
@swissspidy There is already #2279 which has the two icons functional, except for the "Back" and "Front". I was planning to continue with the two remaining today but feel free to test it out already to see if it's OK to have these controls in the sidebar.

**Comment by dawidmlynarz** [comment]
Hello, all icons are ready for different actions. See the image below and leave your feedback.

<img width="719" alt="Icons" src="https://user-images.githubusercontent.com/8026823/57757628-24074780-76f6-11e9-8546-c4fcbebd445d.png">

**Comment by miina** [comment]
Thanks, @dawidmlynarz, unless there are any objections then I think we can use these.

**Comment by miina** [comment]
Instructions for testing:
- Create a few blocks.
- Make sure that the blocks have "Block Position" settings in the sidebar.
- Make sure that there are 4 actions available and each action functions as expected.
- "Forward" should bring the block forward of the first block in front of it.
- "Front" should bring the block forward from all the blocks on that page and make it the top block.
- "Backward" should push the block back by 1.
- "Back" should push the block to the last.
- If the block is already the last, then "Backward" and "Back" should be disabled.
- If the block is already on top, the first, then "Forward" and "Front" should be disabled.

**Comment by csossi** [comment]
I set date block as  "top" on page 2 of a story, but Forward and Front were not disabled:
![image](https://user-images.githubusercontent.com/16945664/58036601-792dc980-7af9-11e9-88c0-b53e3e45b039.png)

**Comment by miina** [comment]
@csossi Could you please send the steps to reproduce the issue, it seems to be working as expected to me in the test environment and locally:
![Screen Shot 2019-05-20 at 6 39 50 PM](https://user-images.githubusercontent.com/3294597/58037862-bd878c80-7b2e-11e9-80d5-92768c4953fa.png)

**Comment by csossi** [comment]
Verified in QA (unable to replicate)
