### ISSUE TITLE
Rotation conflicts with animation

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2186]
I added a Text block and rotated it:

![image](https://user-images.githubusercontent.com/134745/56699630-26ecba80-66ab-11e9-89e5-7bbe2e6044f3.png)

I then added an animation to it:

![image](https://user-images.githubusercontent.com/134745/56699636-31a74f80-66ab-11e9-9419-d3a1474218b0.png)

Even though when I deselect the block I see it rotated in the editor, when I go to the frontend after the animation completes the element is not rotated:

![image](https://user-images.githubusercontent.com/134745/56699662-50a5e180-66ab-11e9-8889-3446f021b81e.png)

**Comment by csossi** [comment]
Verified in QA

Animations working, with text ending up in rotated position
