### ISSUE TITLE
[AMP Stories] Animation delay/duration missing units causing no effect

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2188]
I set the animation delay and duration to a maximum of 5 seconds each:

> ![image](https://user-images.githubusercontent.com/134745/56699981-bd6dab80-66ac-11e9-9394-7c0d73181be1.png)

Nevertheless, the animation starts immediately and finishes.

The HTML generated contains:

`animate-in-delay="5000" animate-in-duration="5000"`

It turns out that this doesn't work. For it to work, there must be units supplied:

`animate-in-delay="5000ms" animate-in-duration="5000ms"`

**Comment by swissspidy** [comment]
Works as expected now.
