### ISSUE TITLE
Integrate with Site Health Check

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2199]
There are some opportunities for the AMP plugin to integrate with the [Site Health Check](https://make.wordpress.org/core/2019/04/25/site-health-check-in-5-2/) in 5.2, including both status and info:

* Detect whether loopback requests are working. (Done ✅)
* Whether persistent object cache is present.
* Warn when suggested extensions are not installed (#2190).
* Warn when `curl_multi_*` functions aren't available (#2423).
* Flag themes and plugins that are not AMP-compatible. (_Future_)
* What mode is enabled (native/transitional/reader).
* What experiences are enabled.
* Which templates are enabled.
* Misc AMP plugin settings.
...

We should include as much information as is helpful to debug issues that are reported on the forums.

**Comment by swissspidy** [comment]
> Detect whether loopback requests are working.

Site Health does that by default because of cron. Perhaps that check is already enough.

**Comment by westonruter** [comment]
See also #2006 (Add warning when a site is not served via HTTPS)

**Comment by westonruter** [comment]
Every warning that we're showing in the plugin admin screen should also be shown in Site Health.

**Comment by kienstra** [comment]
**Request To Work On This**

Hi @westonruter,
Hope your day's off to a great start. 

Could I work on this? Thanks!

**Comment by westonruter** [comment]
Yes, please.

**Comment by westonruter** [comment]
Something that has come up twice recently ([1](https://wordpress.org/support/topic/links-and-buttons-are-disabled/#post-12158823), [2](https://wordpress.org/support/topic/plugin-incompatible-with-php-version-7-2/#post-12126564), [3](https://wordpress.org/support/topic/php-7-2-deprecation-error/)) is a deprecation notice:

> PHP Deprecated: idn_to_utf8(): INTL_IDNA_VARIANT_2003 is deprecated in ...amp/includes/class-amp-http.php on line 233

We may want to consider adding a Site Health check for outdated ICU version. /cc @schlessera 

It was [noted](https://wordpress.org/support/topic/php-7-2-deprecation-error/#post-11526370) by @swissspidy that:

> This typically happens when the version of PHP has been compiled with an older version of ICU.

**Comment by westonruter** [comment]
Something else which may end up needing to be tested for is whether zlib output compression is enabled, as apparently this breaks the output buffer processing. Awaiting to confirm. See https://wordpress.org/support/topic/links-and-buttons-are-disabled/#post-12161184

**Comment by kienstra** [comment]
**Testing Steps**

1. Go to, `/wp-admin/site-health.php`, and ensure the 'Status' tab is showing
2. Expected: there should be 3 AMP pillboxes:

<img width="1043" alt="status-here" src="https://user-images.githubusercontent.com/4063887/73214545-09f08680-4118-11ea-810c-d6420b395722.png">

In the 'Passed tests' section:
<img width="924" alt="passed-tests" src="https://user-images.githubusercontent.com/4063887/73214678-48864100-4118-11ea-9daf-7370c4266342.png">

3. Click the 'Info' tab at the top, or go to `/wp-admin/site-health.php?tab=debug`
4. Expected: Something like this should display:
<img width="919" alt="templates-here" src="https://user-images.githubusercontent.com/4063887/73214821-87b49200-4118-11ea-9e8b-d37edb6b48ff.png">

5. Make some changes to the 'AMP Settings' page. For example, disable Pages:
<img width="925" alt="pages-here" src="https://user-images.githubusercontent.com/4063887/73215062-fbef3580-4118-11ea-85eb-5fbd41046736.png">

6. Go back to the Site Health 'Info' tab in Step 3
7. Expected: the change is reflected there. For example:
<img width="531" alt="page-here" src="https://user-images.githubusercontent.com/4063887/73215245-45d81b80-4119-11ea-9922-3145dc1fcc3f.png">
8. Repeat steps 5-7 for several different settings

**Comment by csossi** [comment]
Verified in QA
