### ISSUE TITLE
AMP Accordion not working in native mode

### ISSUE THREAD

**Issue by vaggelisifantis** [ampproject/amp-wp#2205]
Hey,
I'm using AMP in native mode and amp-accordion is not working properly, `<section>`  is not showing up anywhere in the DOM.

My WP template code is:
```html
<amp-accordion disable-session-states>
    <section>
	<a href="/hello">Hello</a>
        <p>Hello this is an accordion section</p>
    </section>
</amp-accordion>
```
and in the browser the html that's returned is:
```html
<amp-accordion disable-session-states>


</amp-accordion>
```

**Comment by westonruter** [comment]
@vaggelisifantis The AMP plugin's sanitizer is removing elements because it's not valid AMP as can be seen in the AMP validator:

![image](https://user-images.githubusercontent.com/134745/56841114-8af4b780-6840-11e9-9e81-9d47aca15f06.png)

Wrap the `a` in a heading and that should fix the problem:

```html
  <amp-accordion disable-session-states>
    <section>
      <h2><a href="/hello">Hello</a></h2>
      <p>Hello this is an accordion section</p>
    </section>
  </amp-accordion>
```

**Comment by vaggelisifantis** [comment]
Thank's!!! 😀
