### ISSUE TITLE
Block is de-selected after dragging

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2211]
Given a text block which is selected and a grab handle is present:

![image](https://user-images.githubusercontent.com/134745/56928367-6e988b00-6a8b-11e9-8d65-3d64f438e81b.png)

After dragging the block anywhere, the block then becomes de-selected when letting go:

![image](https://user-images.githubusercontent.com/134745/56928394-82dc8800-6a8b-11e9-9ca6-1500e7cb50bc.png)

This is a jarring experience as the sidebar contents unexpectedly changes as well as you have to re-click in the text block to make the grab handle re-appear.

This issue is even worse for a blocks like the story title, which have no editable text. For them you have to re-select the block twice. 

1. Selected: 
![image](https://user-images.githubusercontent.com/134745/56928482-ccc56e00-6a8b-11e9-885d-f49299ab8db1.png)

2. Moved:
![image](https://user-images.githubusercontent.com/134745/56928498-d8189980-6a8b-11e9-8622-fb77ca6e0299.png)

3. Click off the element:
![image](https://user-images.githubusercontent.com/134745/56928512-e1a20180-6a8b-11e9-8c23-60221f8ea002.png)

4. Click the block again:
![image](https://user-images.githubusercontent.com/134745/56928531-ee265a00-6a8b-11e9-9fc1-d3d5b2c85e92.png)

Then the grab handle appears again to be able to move it. But upon moving, these steps have to be repeated.

**Comment by swissspidy** [comment]
> After dragging the block anywhere, the block then becomes de-selected when letting go

IIRC it was added on purpose to force some state changes.

I guess we're gonna change the dragging drastically anyway when we remove the drag handles and arrows and allow dragging the whole block.

**Comment by miina** [comment]
Instructions for testing:
- Add any block
- Drag it around
- Verify that the block remains selected after dragging.

**Comment by csossi** [comment]
Verified in QA

Focus maintained after dragging:
![image](https://user-images.githubusercontent.com/16945664/57802566-457f2800-7724-11e9-8061-4a6a587ab203.png)
