### ISSUE TITLE
Pasting text into empty Text block raises error

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2212]
After inserting a Text block, if the first thing I populate the block with comes from the clipboard, an error is then raised:

> TypeError: Cannot read property 'attributes' of undefined

![image](https://user-images.githubusercontent.com/134745/56929161-c6d08c80-6a8d-11e9-99cf-b5843a1a648a.png)

Fortunately the editor kept working as expected after I unpaused the breakpoint.

**Comment by swissspidy** [comment]
Is there a stack trace?

**Comment by westonruter** [comment]
I encountered it on the test environment so the stack trace is not helpful. I'll have to try locally with a dev build.

**Comment by westonruter** [comment]
Also, when pasting "amp_story" into an empty Text block, I see the following console entries added prior to the error being thrown:

![image](https://user-images.githubusercontent.com/134745/57000026-a294ae80-6b66-11e9-8ad9-03b879b54f43.png)

When running both AMP and Gutenberg in dev, the stack trace still does not seem super helpful:

![image](https://user-images.githubusercontent.com/134745/57000178-3fefe280-6b67-11e9-9c8d-6bbea25cbe79.png)

**Comment by westonruter** [comment]
```
Uncaught TypeError: Cannot read property 'attributes' of undefined
    at Ut (index.js?ver=1555570615:formatted:4287)
    at index.js?ver=1555570615:formatted:4826
    at Array.map (<anonymous>)
    at html (index.js?ver=1555570615:formatted:4820)
    at index.js?ver=1555570615:formatted:4831
    at arrayMap (lodash.js?ver=4.17.11:639)
    at map (lodash.js?ver=4.17.11:9556)
    at flatMap (lodash.js?ver=4.17.11:9259)
    at Rr (index.js?ver=1555570615:formatted:4806)
    at t.value (index.js?ver=1555570615:55)
```

**Comment by swissspidy** [comment]
> Also, when pasting "amp_story" into an empty Text block, I see the following console entries added prior to the error being thrown:

That is just a debug helper from Gutenberg

**Comment by westonruter** [comment]
I think I've found why the error is happening: we have unregistered the Custom HTML block.

The error is coming from `blockType` being undefined:

![image](https://user-images.githubusercontent.com/134745/57107776-c5999c80-6ce5-11e9-85b2-90db35aee72c.png)

What is `blockType`? Stepping up the call stack it is supposed to be the `core/html` block type:

![image](https://user-images.githubusercontent.com/134745/57107816-ea8e0f80-6ce5-11e9-8702-e28562d3e8fc.png)

But we have unregistered it, so it no longer exists. So we can prevent this error from happening via:

```diff
diff --git a/assets/src/constants.js b/assets/src/constants.js
index cbc0418a..ba0dbdf1 100644
--- a/assets/src/constants.js
+++ b/assets/src/constants.js
@@ -51,6 +51,7 @@ export const ALLOWED_MOVABLE_BLOCKS = [
 	'amp/amp-story-post-author',
 	'amp/amp-story-post-date',
 	'amp/amp-story-post-title',
+	'core/html',
 	'core/block', // Reusable blocks.
 	'core/template', // Reusable blocks.
 ];
```

That prevents the error. _But_ the result of pasting results in no content being added to the Text block. So this is something more fundamental going on here. Investigating…

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create text block
2. Paste content (either plain text or some content that contains HTML) into block
3. Check that no errors are added in the console because of that.

**Comment by miina** [comment]
@csossi Sorry for that but could you test this again? Looks like it wasn't deployed to the environment.

**Comment by csossi** [comment]
Thanks, @miina - have verified in QA:

Pasting text:
![image](https://user-images.githubusercontent.com/16945664/57399056-84e6cb00-719e-11e9-8d34-cec1ba2d89e3.png)

Pasting HTML:
![image](https://user-images.githubusercontent.com/16945664/57399431-31c14800-719f-11e9-93c3-91f6a16ca499.png)
