### ISSUE TITLE
Initial focal point of 50%/50% not applied to editor view

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2213]
I inserted an image as background media and even though the focal point said it had a 50%/50% focal point, the image appeared off center:

![image](https://user-images.githubusercontent.com/134745/56929766-575b9c80-6a8f-11e9-9361-f94a9b0aacc9.png)

The frontend looked correct, however:

![image](https://user-images.githubusercontent.com/134745/56929826-84a84a80-6a8f-11e9-94c3-89e8921e5cf6.png)

To get the focal point to look correct in the editor, I had to touch the control to apparently give it a non-default value.

**Comment by swissspidy** [comment]
Possibly related: #2112

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create story
1. Click on "Add Background Media" in the block sidebar
1. Select or upload a large image
1. Verify that the image is positioned in the center, just like the focal point picker indicates

**Comment by csossi** [comment]
Verified in QA

Example 1:
![image](https://user-images.githubusercontent.com/16945664/57784717-616fd300-76fe-11e9-8a88-fb78a6601b3b.png)

Example 2:
![image](https://user-images.githubusercontent.com/16945664/57784836-9aa84300-76fe-11e9-9d43-79b97a74d7eb.png)
