### ISSUE TITLE
Poster image for background video is not centered

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2214]
Upon selecting a background video, it appears correctly as centered in the page:

> ![image](https://user-images.githubusercontent.com/134745/56929934-f54f6700-6a8f-11e9-9a2e-d8e53689dc0b.png)

However, upon selecting a poster image (as required) the image is not centered:

> ![image](https://user-images.githubusercontent.com/134745/56929956-11530880-6a90-11e9-9da0-1cf411371bd1.png)

There is no focal point picker for the poster, so it should be centered like the video is.

Also, should the poster image override the video being played?

**Comment by swissspidy** [comment]
> Also, should the poster image override the video being played?

You mean on the front end? Or in the editor?

**Comment by westonruter** [comment]
In the editor. When setting the poster image, I can no longer see the video playing in the editor. This would probably be a Gutenberg bug, no? Instead of showing. The poster image in the block it would probably be better shown in the sidebar.

**Comment by swissspidy** [comment]
Not a Gutenberg bug, that background media thing is all custom and not a video block or anything.

The poster is added as a background image if set:

https://github.com/ampproject/amp-wp/blob/d48d6265f709c944e201087ca6c6b66c42a09035/assets/src/blocks/amp-story-page/edit.js#L167-L169

And the video is only shown/played if there's no poster, to reduce noise while editing:

https://github.com/ampproject/amp-wp/blob/d48d6265f709c944e201087ca6c6b66c42a09035/assets/src/blocks/amp-story-page/edit.js#L328-L335

(FWIW, that `todo` note is outdated)

Maybe we can just show the video all the time, but just not autplay it?

> The poster image in the block it would probably be better shown in the sidebar.

Interesting suggestion. Might clutter the sidebar a bit though, especially if you'd want to add a focal point picker (which would mean actually cropping the image).

**Comment by westonruter** [comment]
If a focal picker is added for the poster then it would have to be added for the video as well. I don't think it would clutter the sidebar too much. It would be like the featured image.

Plus, the poster image normally is only shown momentarily to the user until the video loads. It's more of a secondary thing, and it doesn't deserve to be featured in the editor IMO.

**Comment by westonruter** [comment]
Otherwise, if the poster image remains in the editor view, perhaps there could be a button to preview how it appears when the video is loading?

**Comment by swissspidy** [comment]
Related: #2223

I am not sure we should add a focal picker here. How would you even position the `<video>` correctly and does AMP support that?

**Comment by westonruter** [comment]
I don't think we should add a focal picker here.

**Comment by westonruter** [comment]
I'll give this a shot.
