### ISSUE TITLE
CTA button should default to center-alignment

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2215]
The CTA block has a button that is by default left-aligned:

![image](https://user-images.githubusercontent.com/134745/56932857-3b112d00-6a9a-11e9-8f94-2cc7aa4e6d6d.png)

This is probably not the best default placement:

![image](https://user-images.githubusercontent.com/134745/56932864-482e1c00-6a9a-11e9-85e9-99396d14aecd.png)

It should by default be center-aligned.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create a few pages
2. On a page (not the first one in the list), add a new call to action button
3. Verify that the CTA button is aligned in the horizontal center of the page 
3. Enter text and URL
4. Save story & preview on frontend
4. Verify that the CTA button is also aligned the same way on the frontend

**Comment by csossi** [comment]
Verified in QA

Editor:
![image](https://user-images.githubusercontent.com/16945664/57784369-cc6cda00-76fd-11e9-9507-7d87ebb7f650.png)


Front-End:
![image](https://user-images.githubusercontent.com/16945664/57784288-ae9f7500-76fd-11e9-937e-0f9f7673f000.png)
