### ISSUE TITLE
Animations don't always work

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2218]
Added different animations to the text in story pages and most of them did not seem to work.

![out](https://user-images.githubusercontent.com/506089/56935419-d065ee80-6aa5-11e9-8b8d-d5953b002fa3.gif)

**Comment by amedina** [comment]
I did hard reload.

**Comment by westonruter** [comment]
@amedina it's hard to tell from the video, but which animations specifically aren't working". It seems the twirling and flying ones are working, but the zooming ones are not? It could be another conflict with transforms, as with #2186.

**Comment by swissspidy** [comment]
See #2186 for more information regarding testing.

**Comment by swissspidy** [comment]
Verified in QA in #2186.
