### ISSUE TITLE
Setting Background Color changes the size of text?

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2219]
![out](https://user-images.githubusercontent.com/506089/56935710-bc22f100-6aa7-11e9-999f-d9d5c0e9d8e2.gif)

**Comment by westonruter** [comment]
This is expected since adding a background color adds a margin to the element. Perhaps the margin should always be present to prevent this?

**Comment by miina** [comment]
Note: this is also related to #2162 and #2230.

**Comment by swissspidy** [comment]
> This is expected since adding a background color adds a margin to the element. Perhaps the margin should always be present to prevent this?

I assume you meant _padding_? AFAIK the padding is added on the container. And yes, a default padding would resolve this. However, it might make it more difficult to position text without a background color precisely at the border of a page for example, because you have to account for the padding. Not sure how common that use case is though.

**Comment by swissspidy** [comment]
> And yes, a default padding would resolve this.

This might clash a bit with #2191 / #2162.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create text block
2. Change background color
3. Verify that changing background color does not affect font size, neither in the editor nor on the frontend

**Comment by csossi** [comment]
Font size seems to be changing on front end when no background colour selected

Editor:
![image](https://user-images.githubusercontent.com/16945664/58029923-9bb8e600-7aeb-11e9-977c-01da4ab63850.png)

Preview:
![image](https://user-images.githubusercontent.com/16945664/58029969-b4c19700-7aeb-11e9-9cd7-6f79c1d3e89f.png)

**Comment by miina** [comment]
@csossi Thank you for testing.

To specify:

In this specific issue what we'd need to test is that the font size remains the same if you switch on and off the background color.

What we'd need to test:
For the editor:
1. Add a text block
2. Look how the font size is.
3. Add background color.
4. Make sure that the font size in the editor did not change after adding the background color.

For the FE:
1. Add a text block.
2. Check how the font size looks like in the frontend.
3. Add background color and save.
4. Make sure the font size in the FE is the same as it was before adding the background color.

Could you please test it again for this specific issue?

I'll create a new issue meanwhile for the text being on one line in the editor and on two lines in the frontend.

**Comment by miina** [comment]
Added a new issue for the one you've found testing: https://github.com/ampproject/amp-wp/issues/2353

**Comment by csossi** [comment]
Thanks, @miina

**Comment by csossi** [comment]
There's a diff in font size when background colour is added when reviewed on the front end

FE without BG colour:
![image](https://user-images.githubusercontent.com/16945664/58047733-d2f0bc80-7b16-11e9-8026-c5bc90beb17b.png)


FE with background colour:
![image](https://user-images.githubusercontent.com/16945664/58047777-f287e500-7b16-11e9-8a3b-eaa458289a4f.png)

**Comment by miina** [comment]
@swissspidy I'm assigning this to you since fixing this was part of #2296.

**Comment by miina** [comment]
Closing this as ready for QA.

**Comment by csossi** [comment]
Verified in QA
