### ISSUE TITLE
Change admin menu icon for AMP stories

### ISSUE THREAD

**Issue by ThierryA** [ampproject/amp-wp#2220]

**Comment by swissspidy** [comment]
I like the Visual Stories icon in Google search results (bottom right corner):

![amp05-visual-story](https://user-images.githubusercontent.com/841956/57817407-0bb61d80-7734-11e9-98c6-e0a19bb891c5.png)

**Comment by amedina** [comment]
+1. We can go with that one.

**Comment by ThierryA** [comment]
cc @dawidmlynarz

**Comment by dawidmlynarz** [comment]
Nice I like it as well! +1
