### ISSUE TITLE
Fullscreen Mode Compatibility

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2221]
Creating a new story when fullscreen mode is active works fine, however there is an error when switching from regular to fullscreen mode when already editing a story:

![Screenshot 2019-04-30 at 12 05 29](https://user-images.githubusercontent.com/841956/56954947-62bad080-6b40-11e9-8e79-029a16b4bc60.png)

This is probably due to the fact that we insert some custom HTML nodes and wrap some existing elements in our new nodes.

If there's not an easy way to solve this in JavaScript, one option would be to completely override the [editor `Layout` component](https://github.com/WordPress/gutenberg/blob/98c97a718799131968e5bfa17a50858e3508c187/packages/edit-post/src/components/layout/index.js) or similar to achieve our custom DOM structure.

**Comment by miina** [comment]
@swissspidy Are you still seeing this issue? Couldn't reproduce it at this moment. Did the following:
- Created a new Story in "normal" mode.
- Added a few pages using the Templates Inserter.
- Saved.
- Switched to Fullscreen Mode.
- Checked console for related errors -- none occurred.

**Comment by swissspidy** [comment]
Indeed seems to work fine now with the latest Gutenberg version. Yay!

Great that it's working. Fullscreen mode makes focusing on story creation so much easier.
