### ISSUE TITLE
AMP Stories not working with Gutenberg Version 5.6.0 

### ISSUE THREAD

**Issue by dchianese** [ampproject/amp-wp#2228]
I have Gutenberg version 5.6.0 installed but I am getting this message "To use AMP stories, you currently must have the latest version of the Gutenberg plugin installed." This is happening with 1.2-alpha1: AMP Stories Editor Preview Release. How can I get this working? Thank you

**Comment by amedina** [comment]
5.6.0 is the latest version; do you have it activated?

Em qua, 1 de mai de 2019 às 13:26, dchianese <notifications@github.com>
escreveu:

**Comment by westonruter** [comment]
I just tested with Gutenberg 5.6.1 and I'm not getting this notice. As Alberto states, the plugin must be activated. I've clarified this in 07eeee2.
