### ISSUE TITLE
Story pages not showing content on reordering screen

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2229]
When reordering the pages in my story, can't see the content of the pages in the reordering screen: 
![Screen Shot 2019-05-01 at 5 06 27 PM](https://user-images.githubusercontent.com/506089/57050878-890d6880-6c33-11e9-8b32-8cac07e9b2c7.png)

**Comment by westonruter** [comment]
I can see the same thing at https://story-test-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=449&action=edit

![image](https://user-images.githubusercontent.com/134745/57086775-9a965500-6cb3-11e9-8f27-95c0dfe1c75c.png)

**Comment by swissspidy** [comment]
To bring back the background images we'd need to add the following CSS:

```css
.amp-story-reorderer .components-disabled div:first-of-type {
  height: 100%;
}
```

I don't know what caused this though. Maybe it was a change in Gutenberg.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create media-rich story with background images, rotated blocks, etc.
2. Start reordering pages
3. Verify that the page previews in the reorder UI match the pages during regular editing, including visible background images, etc.

**Comment by csossi** [comment]
Thanks for the guidance, @swissspidy !

Verified in QA:

Original:
![image](https://user-images.githubusercontent.com/16945664/57588207-dbc20c80-74de-11e9-9278-8cdfc14548f3.png)

Reordered1:
![image](https://user-images.githubusercontent.com/16945664/57588225-10ce5f00-74df-11e9-9170-66b9bab062b1.png)

Reordered 2:
![image](https://user-images.githubusercontent.com/16945664/57588262-5559fa80-74df-11e9-852b-3056e3914d2b.png)
