### ISSUE TITLE
Text Block not Displaying Properly In Preview

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2230]
Added a text block. Within the editor the padding around the text block seems exaggerated. When viewing the story in Preview the background does not actual form a background within the text block.

In editor:
<img width="385" alt="Screen Shot 2019-05-02 at 6 39 58 AM" src="https://user-images.githubusercontent.com/24547817/57070469-85b2c500-6ca5-11e9-8a50-27f5b7dbc4eb.png">

In preview:
<img width="390" alt="Screen Shot 2019-05-02 at 6 39 34 AM" src="https://user-images.githubusercontent.com/24547817/57070468-85b2c500-6ca5-11e9-8661-183faa8a433c.png">

Same issue happening throughout the templates:

<img width="441" alt="Screen Shot 2019-05-02 at 7 54 02 AM" src="https://user-images.githubusercontent.com/24547817/57073644-a849db80-6caf-11e9-95c6-3dd9e1b3f05a.png">

<img width="392" alt="Screen Shot 2019-05-02 at 7 54 15 AM" src="https://user-images.githubusercontent.com/24547817/57073656-af70e980-6caf-11e9-9e55-0cd0bfdb90d4.png">

**Comment by miina** [comment]
This is also related to #2162 and could potentially be resolved within that.

**Comment by swissspidy** [comment]
I cannot seem to reproduce this at the moment.

Let's test this again, ideally after #2296 lands.

**Comment by swissspidy** [comment]
See https://github.com/ampproject/amp-wp/issues/2162#issuecomment-493570554 for testing instructions.

**Comment by csossi** [comment]
Rechecking when #2162 addressed

**Comment by csossi** [comment]
Verified in QA (font sizing addressed in #2359 )
