### ISSUE TITLE
Update content throughout editor, changing "block(s)" to "template(s)"

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2232]
Currently throughout the editor we reference "blocks". Where applicable, change the content from "block(s)" to "template(s)"

**Comment by swissspidy** [comment]
@MackenzieHartung Since you moved this to the "In progress" column: is there a PR where this is being worked on? Or should it be put back to "To do"?

**Comment by swissspidy** [comment]
I don't really see where we currently are referring to blocks when we should actually should refer to templates.

The only thing that comes to mind is the inserter in the top left, but that makes sense as it's about inserting blocks, not complete templates.

Some more information here would be helpful.

**Comment by MackenzieHartung** [comment]
@swissspidy sorry for the delay - I had intended this to be moved to "to do", not "in progress".

As for the terminology update, this was a request of @ThierryA in which I opened a ticket. However, I am not seeing the term "block" in illogical areas anymore. Previously the term "block" was showing in areas where "page" or "template" would have made more sense. @ThierryA can you confirm that you are seeing verbiage as intended.

**Comment by ThierryA** [comment]
I think all instance have now been addressed. In the screenshot below there is "Remove Block" when a page is selected. While this could be "Remove Template", I think this option should potentially not even be there as we shouldn't allow to remove the top level block.
![Screen Shot 2019-05-15 at 11 45 41](https://user-images.githubusercontent.com/3581402/57766216-45bcfa80-7707-11e9-878a-90078c77ffda.png)

**Comment by swissspidy** [comment]
> we shouldn't allow to remove the top level block.

@ThierryA So you're saying we should not allow people to remove pages at all? 🤔

**Comment by ThierryA** [comment]
> @ThierryA So you're saying we should not allow people to remove pages at all? 🤔

Well, if the intent of "Remove Block" when a Page is selected, then I suggest the text should be "Remove Page". The main reason I was saying we may not allow it is because I [am getting an error when trying to do so](https://github.com/ampproject/amp-wp/issues/2321), which let me to think it wasn't intended to actually remove the page.

**Comment by swissspidy** [comment]
No, that error is a bug in Gutenberg that I am actively working on fixing. See #2253.

Unfortunately renaming that label is not really possible in Gutenberg. These actions are basically hardcoded. IIRC we can only add more actions, but not change or remove them.

**Comment by swissspidy** [comment]
I suggest closing this as `no action needed`.
