### ISSUE TITLE
Frontend <-> Editor Disparity

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2236]
Previously: #1967, #2159.
Related: #2234, #2230, #2219, #2162
Somewhat related: #1974

----

This issue is intended as the central place to discuss the current disparities between what you see in the editor and what you get on the front end.

As the list of issues above shows, we have tried to address this in the past, but ended up fixing many issues caused by this (and there are still some open issues). That sounds like treating symptoms instead of the actual root cause.

Currently, it works like this:

* Each page in the editor has an inner width of 328x553 pixels.  
  That's a similar (but not the same) aspect ratio (0.5931283906) of what you get on the front end (which is around 0.5999897907 on desktop, or basically 0.6)
* In the editor, blocks can positioned freely within a page.  
  That position is calculated in pixels, but then (based on the page's dimensions) turned into percentages. So if you position a block 20px from the top in the editor, it will be positioned X% from the top on the front end.  
  This is needed because AMP Stories are responsive, so hardcoded pixel values would not work.
* Like the block's position, its width and height is also turned from pixels into percentage.  
  This is done in `getStylesFromBlockAttributes()`
  Again, AMP Stories are responsive, so hardcoded pixel values would not work.
* The font size of a text block is changed from pixels to using `vw` so that scales correctly.  
  Also happens in `getStylesFromBlockAttributes()`.

These techniques/conversions are a logical consequence, yet they cause these issues.

In some of the meetings and also in-person discussions we briefly discussed how to best handle this, but haven't come to a conclusion yet. Something that was mentioned is how in Chrome developer tools you can basically scale down the viewport without changing the actual viewport (basically `transform: scale()` in CSS) and whether this is something we'd need to do.

However, since Stories are responsive, and fill the full width and height on smartphones, there is not really a base size that you could scale down from.

One thing that was previously raised by Weston is that for the block position, we might want to calculate positions from the center of the page instead of the top left corner. Otherwise it is hard to precisely position a block in the bottom left corner, for example. Not sure how feasible that is though.

**I guess the question now is:** are these just issues that we need just need to fix once for good, or do we need to re-think the whole approach to make it more sound?

Curious to hear everyone's opinions on how to best tackle this.

**Comment by miina** [comment]
Not sure if #2230, #2219, #2162 are related to the calculation with pixels, these seem to be related to two things:
1. The padding assigned to text block if it has background color set, and
2. In the editor view the width and height of the block (and background color) don't accurately reflect the values set for the block via the resizing box, sometimes it seems that it displays larger background when it actually is and sometimes smaller, for example here it displays smaller area:
![Screen Shot 2019-05-02 at 3 37 52 PM](https://user-images.githubusercontent.com/3294597/57079271-4d84a400-6cf0-11e9-8743-33914ace0325.png)

Here, for example, the area shows larger than it actually is:
![Screen Shot 2019-05-02 at 3 44 53 PM](https://user-images.githubusercontent.com/3294597/57079747-4f029c00-6cf1-11e9-9aeb-3f438bc76096.png)

It can be seen that the resize box borders are covering much smaller area than the background color displays. In the frontend the width and height are displayed accurately according to the width and height set via resizing box and this causes disparity between the FE and the editor, however, not related to the conversion from pixels:
![Screen Shot 2019-05-02 at 3 46 50 PM](https://user-images.githubusercontent.com/3294597/57079827-7ce7e080-6cf1-11e9-9f83-07efb658d186.png)

At least that's what seems to be going on when I'm testing it.

**Comment by swissspidy** [comment]
A lot of changes have been made in this area so far, see #2210, #2219, #2230, #2162 for some examples. All these are currently in QA.

If everything works as expected we can review this ticket here as a whole again and see whether something else needs more refinement or if we think the issues have been mostly resolved.
