### ISSUE TITLE
Inserting pages while reordering

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2248]
When you start the reordering, we basically copy the list of all the current pages and perform the reordering on that. Once you are done with the reordering, we update the actual order with the one from the copy. That's what allows you to cancel the reordering again.

Now, when you are reordering, you are still able to insert blocks and pages via the top toolbar. However, you won't see any new pages in the reordering panel because the copy hasn't been updated.

Some possible options here:

* When adding new pages, add these to the end of the block order copy.
* Disable/Hide all the buttons in the top toolbar when reordering.
* Do nothing.

**Comment by westonruter** [comment]
> * Disable/Hide all the buttons in the top toolbar when reordering.

I think this makes the most sense. When reordering, no one page is selected, so it doesn't make sense to have the top toolbar appearing.

**Comment by kienstra** [comment]
**Working On This If That's Alright**

Hi @swissspidy,
If it's alright, I'm going to work on this.

**Comment by swissspidy** [comment]
See gif at #2266 for testing instructions / desired outcome

**Comment by csossi** [comment]
Thanks, @swissspidy 

Verified in QA - Inserter and block options disabled when reordering:
![image](https://user-images.githubusercontent.com/16945664/57697535-7c204a00-7621-11e9-820e-f07a3acef9b8.png)
