### ISSUE TITLE
The caption (hide/show) setting for Image block isn't functional

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2251]
The setting for hiding and showing caption doesn't seem to be working anymore, the caption is visible at all times in the editor even when turned off.

Note: Using the latest Gutenberg from repo.

**Comment by miina** [comment]
Notes for testing:
- Add an image block.
- Choose an image.
- Make sure that image caption is hidden by default in the editor and front-end both.
- In the Image block sidebar, change the "Show Caption" Setting, make sure that the caption displays / hides based on the setting value.

**Comment by csossi** [comment]
Selected image with a caption:
![image](https://user-images.githubusercontent.com/16945664/57783091-81ea5e00-76fb-11e9-83fe-1650d48e05b9.png)

When I returned to Editor, the caption was hidden (fine). But when I toggled to show caption, this appeared - shouldn't the caption noted in the media library  be visible here?:
![image](https://user-images.githubusercontent.com/16945664/57783210-beb65500-76fb-11e9-8f4e-6cf74fdbfe89.png)

**Comment by miina** [comment]
@csossi Thanks for testing that! It's expected that the caption does not appear -- by default the caption is removed for an image block even if the image actually has a caption. At this moment that's the expected behavior.
