### ISSUE TITLE
Rebrand AMP Stories CPT

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2257]
AMP is a developer brand; as a feature in the AMP plugin, `AMP Stories` should be branded as just  `Stories`. Let's include this as part of v1.0.

/cc @pbakaus

**Comment by westonruter** [comment]
Aside: The URLs for stories already just include `/stories/`.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Clear cookies and localstorage
1. Go the AMP settings page
1. Notice that everywhere we refer to just Stories, not AMP Stories, even in admin feature pointers.

Note: If you still see the name AMP Stories _somewhere_, it is a bug. If you see it _everywhere_, then you are not looking at the latest version.

**Comment by csossi** [comment]
Verified in QA

I.E.:
![image](https://user-images.githubusercontent.com/16945664/57697177-a58ca600-7620-11e9-8a51-154119aa47a3.png)
