### ISSUE TITLE
Sanitizer removes CSS that exists

### ISSUE THREAD

**Issue by octoper** [ampproject/amp-wp#2259]
Hello,

I'am using [Tailwind CSS](https://tailwindcss.com/docs/what-is-tailwind/) for my theme.
The AMP CSS Sanitizer dont recognize's CSS classes like this
```html
<div class="bg-black w-16 lg:w-full hover:bg-blue"></div>
```
and removes them from CSS can you change that so it supports them??

**Comment by westonruter** [comment]
Please share the CSS that is getting removed.

I'm surprised to see the colons in the class names.

**Comment by vaggelisifantis** [comment]
This is my CSS class
```css
.lg\:w-full {
    width: 100%;
}
```

**Comment by westonruter** [comment]
Thanks. It could also be a problem with the PHP CSS parser. I'll investigate.

**Comment by westonruter** [comment]
@vaggelisifantis I've found a fix. Please test the build attached to the PR here: #2260.

**Comment by westonruter** [comment]
I found a bug. Don't test yet.

**Comment by westonruter** [comment]
@vaggelisifantis ok, bug fixed. Please test #2260.

**Comment by westonruter** [comment]
@octoper can you test please?

**Comment by octoper** [comment]
@westonruter Yeah I've tested it and it's working. Thanks!!
