### ISSUE TITLE
Console warning when inserting an image with caption

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2263]
Steps to reproduce:
- Create an image block;
- Add an image which previously had a caption set.

**Comment by miina** [comment]
Instructions for testing:
- Choose an Image in Media Library and set a Caption for that image.
- Create an image block in the AMP Stories editor.
- Add the image which has a caption set.
- Make sure that no errors appear in the console.

**Comment by csossi** [comment]
Verified in QA

Image with caption selected:
![image](https://user-images.githubusercontent.com/16945664/57782195-bfe68280-76f9-11e9-9716-38361926ed04.png)

On selection:
![image](https://user-images.githubusercontent.com/16945664/57782277-e4425f00-76f9-11e9-99d1-02355c686fc6.png)
