### ISSUE TITLE
Admin Color Scheme Support

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2265]
**Testing instructions:**

1. Edit user profile
2. Change admin color scheme from default do something like Midnight.
3. Go create a AMP story.
4. Notice the mix of colors

**Screenshot:**

<img width="1678" alt="Screenshot 2019-05-06 at 14 37 06" src="https://user-images.githubusercontent.com/841956/57256890-baf44580-700c-11e9-843a-10f46c0b13ec.png">

**How to solve**

The good thing is that it's very easy to fix since we merged #2000 and #2056.

We basically just need to replace all the hardcoded color values in the CSS files with `theme(primary)` where `primary` is a variable defined in `postcss.config.js`.

Related: https://github.com/WordPress/gutenberg/pull/6739

**Comment by swissspidy** [comment]
**Testing instructions:**

1. Edit user profile
1. Change admin color scheme from default do something like Midnight.
1. Go create a AMP story.
1. Verify that buttons and other UI elements should have consistently changed colors, e.g. from blue to red.

**Comment by csossi** [comment]
Verified in QA

Example: Ectoplasm
![image](https://user-images.githubusercontent.com/16945664/57781343-00dd9780-76f8-11e9-8535-f0cfe0e0998b.png)

Example:
Sunshone:
![image](https://user-images.githubusercontent.com/16945664/57781509-50bc5e80-76f8-11e9-8539-9594fd592d36.png)
