### ISSUE TITLE
AMP Pages created by Plugin show structured data errors 

### ISSUE THREAD

**Issue by p2er** [ampproject/amp-wp#2276]
## What's the issue?

Structured data requires publisher name and logo from now on to avoid errors in google structured data validation. The schema.org definition is created by the amp plugin. The plugin does not provide fields to add this information. 

## How do we reproduce the issue?

1. Open: https://www.cu-camper.com/de/magazin/ratgeber/ratgeber-reiseplanung/campingzubehoer-wohnmobil/#development=1
2. AMP validation succesfull 
3. Test in structured data testing tool: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.cu-camper.com%2Fde%2Fmagazin%2Fratgeber%2Fratgeber-reiseplanung%2Fcampingzubehoer-wohnmobil%2F
4. Validation shows 4 Errors. 

Should not display errors due to generated structured data provided by plugin.

**Comment by swissspidy** [comment]
Hey there

The structured data output on your site comes from the Yoast SEO plugin as you can see from this screenshot of the testing tool:

<img width="1546" alt="Screenshot 2019-05-09 at 17 37 50" src="https://user-images.githubusercontent.com/841956/57495070-35c59680-7281-11e9-9e83-4b2b6db1274e.png">

You should double check your settings there and if in doubt contact their support through the WordPress.org plugin support forums or on GitHub.
