### ISSUE TITLE
Setting background opacity is not showing in the editor

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2277]
Steps to reproduce:
- Add a Text block.
- Add background color.
- Try to set background opacity.

**Comment by miina** [comment]
@swissspidy This is reopened, is this something that needs to be addressed again? Saw that #2320 was merged, did this fix this issue fully and we can close it, or is there still something that needs to be done?

**Comment by miina** [comment]
Instructions for testing:
- Add a Text block.
- Add background color (try both custom color and available colors)
- Set background opacity.
- Make sure the background opacity appears both in the editor and in the frontend.

**Comment by swissspidy** [comment]
Yes, #2330 fully fixed the issue.

**Comment by csossi** [comment]
Verified in QA

Editor:
![image](https://user-images.githubusercontent.com/16945664/57805305-a447a000-772a-11e9-980a-7e440033b447.png)

Front-End:
![image](https://user-images.githubusercontent.com/16945664/57805360-bc1f2400-772a-11e9-91bc-561d29f45cab.png)
