### ISSUE TITLE
Long post title hidden behind block navigation

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2280]
When entering a rather long post title, all the UI controls are pushed down, except for the block navigation. This leads to something like this:

<img width="1199" alt="Screenshot 2019-05-10 at 11 34 01" src="https://user-images.githubusercontent.com/841956/57549177-ae773200-7317-11e9-9b6f-20de27d02c48.png">

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create a new story
2. Write a long title that spans multiple lines
3. Verify that all elements (block navigation and the pages) are pushed down (see https://github.com/ampproject/amp-wp/pull/2383 for screenshots)

**Comment by csossi** [comment]
Verified in QA

Before long title:
![image](https://user-images.githubusercontent.com/16945664/58509742-46bd4580-8165-11e9-9e42-c471786c9a1b.png)



After long title:
![image](https://user-images.githubusercontent.com/16945664/58509699-2bead100-8165-11e9-973c-cdb8158649a6.png)
