### ISSUE TITLE
Background Video: Icon used as poster

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2284]
Introduced by #2240.

Given a video that has no featured image:

![image (1)](https://user-images.githubusercontent.com/841956/57572312-42ef9c00-73cd-11e9-9cf0-b8e69d38524f.png)

Incorrectly the file icon is used as the poster, when it should be left empty.

![image (2)](https://user-images.githubusercontent.com/841956/57572315-4be06d80-73cd-11e9-8690-952dc11bde40.png)

Not to mention that the block navigation looks bad on such a small screen. But that's something for another issue.

**Comment by swissspidy** [comment]
See above for testing instructions.

Might need to deploy this to the test environment first. cc @westonruter

**Comment by csossi** [comment]
@swissspidy - area is now left empty, which is great - but can the button read "Insert Image" as "Replace Image" doesn't quite make sense if there's no image to replace:
![image](https://user-images.githubusercontent.com/16945664/57667591-1a84bf00-75d2-11e9-9406-5c80a29a50a8.png)

**Comment by swissspidy** [comment]
@csossi FWIW, this issue here is about the background media option on the page block, not the poster option of the video block.

In your case, it seems that the video actually has a poster image. That's why you get the "Replace Image" and "Remove Poster Image" links / buttons.

Let me check why this happens...

**Comment by swissspidy** [comment]
@csossi Can you please test this again?

More precise testing instructions to make it more clear what to test:

1. Create a new story
2. Select a page and choose "Add Background Media" to select a video
3. Select a video with a featured image thumbnail\*
4. Verify that this thumbnail is automatically chosen as thumbnail

**Note** This is about the page block's background media setting, not the video block.


\* Videos with a featured image have thumbnails like this:

<img width="441" alt="Screenshot 2019-05-14 at 13 57 38" src="https://user-images.githubusercontent.com/841956/57731758-48104d80-7650-11e9-9fdf-5e697b7799e8.png">

Note the file extension and the image behind it.

**Comment by csossi** [comment]
Verified in QA:

- video background media selected, with poster image appearing:
![image](https://user-images.githubusercontent.com/16945664/57777290-90cb1380-76ef-11e9-832d-56fe8346bdd0.png)

- video background selected without thumbnail - poster image requires setting:

![image](https://user-images.githubusercontent.com/16945664/57777616-4bf3ac80-76f0-11e9-812e-e162d557f289.png)
