### ISSUE TITLE
Escaped Unicode characters appear in comment form

### ISSUE THREAD

**Issue by vralle** [ampproject/amp-wp#2286]
Hi!
Comment form title example (AMP v1.1.1):
![screenshot 10](https://user-images.githubusercontent.com/3823060/57587453-a680e300-750d-11e9-97af-6934f8fecb4d.jpg)

Edit AMP v1.1.1 `includes\class-amp-theme-support.php#1172`:
`wp_json_encode( $args['title_reply'], JSON_UNESCAPED_UNICODE )`

Result:
![screenshot 12](https://user-images.githubusercontent.com/3823060/57587497-3cb50900-750e-11e9-87af-a697366cf831.jpg)

And more fix:
`includes\sanitizers\class-amp-comments-sanitizer.php#138`
`wp_json_encode( $name, JSON_UNESCAPED_UNICODE )` for submit button

`includes\class-amp-theme-support.php#1170`:
`wp_json_encode( $args['title_reply_to'], JSON_UNESCAPED_UNICODE )`

And all bind?
Thanks!

**Comment by westonruter** [comment]
So you're saying that more changes like #1811 and #1997 are needed?

**Comment by westonruter** [comment]
Would you like to open a pull request?

**Comment by vralle** [comment]
These fixes apply to version 1.1.1.
I did not go into the question, limiting myself to obvious problems with the comment form. But the nature of the problems suggests that all bind operations need revision of the encoding.

**Comment by vralle** [comment]
superficial study did not lead to unambiguous conclusions.

amp-bind specification - nothing about Unicode characters.

json.org page:

> A string is a sequence of zero or more Unicode characters, wrapped in double quotes, using backslash escapes. A character is represented as a single character string. A string is very much like a C or Java string.

RFC:

> 
> 2.5. Strings
> 
> The representation of strings is similar to conventions used in the C family of programming languages. A string begins and ends with quotation marks. All Unicode characters may be placed within the quotation marks except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).
> 
> Any character may be escaped.
> 

The problem may be on the side of javascript scripts.
I think you need someone who better understands javascript and unicode character handling features.

**Comment by vralle** [comment]
We have:
1. https://amp.dev/documentation/components/amp-bind?referrer=ampproject.org

> amp-bind supports data bindings on four types of element state:
> Attribute [text] = Type Node.textContent

2. https://www.w3.org/TR/2004/REC-DOM-Level-3-Core-20040407/core.html#Node3-textContent

> **textContent** of type DOMString, introduced in DOM Level 3
> This attribute returns the text content of this node and its descendants. When it is defined to be null, setting it has no effect. On setting, any possible children this node may have are removed and, if it the new string is not empty or null, replaced by a single Text node containing the string this attribute is set to. 
> On getting, no serialization is performed, the returned string does not contain any markup. No whitespace normalization is performed and the returned string does not contain the white spaces in element content (see the attribute Text.isElementContentWhitespace). Similarly, on setting, no parsing is performed either, the input string is taken as pure textual content.

Total:
`wp_json_encode( $text, JSON_UNESCAPED_UNICODE )` is used for attribute [text]

**Comment by westonruter** [comment]
@vralle Please test https://github.com/ampproject/amp-wp/pull/2293. Also reported the AMP bug upstream: https://github.com/ampproject/amphtml/issues/22265.
