### ISSUE TITLE
Analytics JSON configuration

### ISSUE THREAD

**Issue by amanijoseph87** [ampproject/amp-wp#2288]
Hi guys am a beginner and i found it really confusing  when it come to add analytics on AMP using JSON, My website use Transitional Option and all other way of adding analytics is not working the oly way is using JSON. But i try to read this doc for hours [https://amp-wp.org/documentation/playbooks/analytics/](https://amp-wp.org/documentation/playbooks/analytics/) but i didn't understand how to add analytics so my question is how can get simple example with JSON code that i can change to my own data, i need to track pageviews and am using wordpress.

I just need somebody to provide me with a JSON code to track pageview,  so that i can copy and paste on my site and change example data to my own data. Please i need this so much am a beginner but the amp analytics doc its seem for advance user.

**Comment by westonruter** [comment]
You can actually find an example JSON configuration right in the analytics settings screen. Just expand “Learn about analytics for AMP.”

![image](https://user-images.githubusercontent.com/134745/57629428-a2c28000-7550-11e9-8661-29c8afb8f333.png)

![image](https://user-images.githubusercontent.com/134745/57629538-cd143d80-7550-11e9-9caf-efe26ed6443e.png)

I've also copied this into the amp-wp.org docs page.
