### ISSUE TITLE
Remove skeleton templates, insert template pre-populated

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2289]
AC: When a user selects a template from Template Inserter then a pre-populated template is added to the editor with all the data as seen in the template preview.

- [ ] Remove skeleton templates from the AMP Stories creation experience
- [ ] When a user accesses the templates, they will see the thumbnails as they currently do
- [ ] Selecting a template to add to the story will add a pre-populated version of the template (matching what is seen in the thumbnail)
- [ ] As per existing functionality, the content/media within the pre-populated template will be editable by the user.

Note: See the `TemplateInserter` component where skeleton template is created from a pre-populated template using `createSkeletonTemplate` function.

**Comment by swissspidy** [comment]
Moving back to the backlog as per today's meeting.
