### ISSUE TITLE
Call to Action validation message cut off

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2294]
If you happen to have a CTA block on the first page (which is invalid), you'll get a nice little error message in the editor.

However, due to some `overflow:hidden`, this message is currently partially cut off:

<img width="541" alt="Screenshot 2019-05-13 at 09 14 01" src="https://user-images.githubusercontent.com/841956/57657412-23ed3780-7590-11e9-8b48-7763efe91678.png">

**Comment by amedina** [comment]
Reproduced.

**Comment by miina** [comment]
Notes for QA:
- Add a Page
- Add a second Page.
- Add a CTA block to the second Page.
- Remove the first Page -- this changes the second Page with the CTA block to be the first Page instead.
- Verify that there is a warning message that now appears near the CTA block is fully visible.

**Comment by csossi** [comment]
Verified in QA

Message :
![image](https://user-images.githubusercontent.com/16945664/58636209-c78f5500-82bd-11e9-9f17-6a94d8a82c46.png)
