### ISSUE TITLE
Missing tooltips for template inserter / reorder button

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2298]
These two buttons have labels / tooltips defined in the code, but due to some CSS they are not displayed on hover.

<img width="157" alt="Screenshot 2019-05-13 at 16 32 45" src="https://user-images.githubusercontent.com/841956/57660745-de833700-759c-11e9-9c14-572b13308681.png">

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create a story
2. Hover over the two buttons shown here
3. Verify that tooltips are being displayed

**Comment by csossi** [comment]
Verified in QA - "Insert Template" and "Reorder Pages"
