### ISSUE TITLE
Latest Stories Block: Missing CSS

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2300]
When inserting the "Latest Stories" block, the block is completely unstyled:

<img width="972" alt="Screenshot 2019-05-13 at 18 05 07" src="https://user-images.githubusercontent.com/841956/57663959-16917680-75ab-11e9-881b-e23e5ba14829.png">

The CSS is added when saving and reloading the post:

<img width="904" alt="Screenshot 2019-05-13 at 18 05 16" src="https://user-images.githubusercontent.com/841956/57663964-1b562a80-75ab-11e9-9247-c179c6936b51.png">

**Comment by westonruter** [comment]
I suppose the block should be lazy-loading the CSS file upon insertion or not already added to the page? This seems like a general Gutenberg issue.

**Comment by swissspidy** [comment]
Ugh, just realized that this block uses `ServerSideRender`. That causes problems of course. That feature is more of a legacy support thing in Gutenberg and should be avoided if possible as the UX is not great.

In the meantime, as a quick fix, we should just always enqueue the CSS in the post editor. It's only ~100 lines.

**Comment by westonruter** [comment]
It's only ~100 lines but it is a blocking external request. Couldn't we have the `componentWillMount` check to see if the stylesheet has been added to the page, and if it isn't then dynamically add it?

https://github.com/ampproject/amp-wp/blob/605f1c8acd10cc2a6f712ccb771cf7c629bc939a/assets/src/block-editor/blocks/amp-latest-stories/edit.js#L31-L33

**Comment by kienstra** [comment]
**In Progress**

If it's alright, I'm working on this now.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create and publish a story
2. Create a new blog post
3. Embed "Latest Stories" block in that post
4. Verify that the embedded stories are properly styled, see https://github.com/ampproject/amp-wp/issues/2300#issue-443666591 for screenshots

**Comment by kienstra** [comment]
Thanks for adding the testing instructions. Sorry for not adding those.

**Comment by csossi** [comment]
not seeing any embed in Posts for "Latest Stories"

**Comment by kienstra** [comment]
Thanks, I also see that the 'Latest Stories' block isn't present when creating a [new post](https://story-test-wordpress-amp.pantheonsite.io/wp-admin/post-new.php). I'll look at this.

**Comment by westonruter** [comment]
> not seeing any embed in Posts for "Latest Stories"

Fix has been deployed.

**Comment by kienstra** [comment]
Thanks, @westonruter!

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this again? Thanks!

**Comment by csossi** [comment]
Verified in QA:
![image](https://user-images.githubusercontent.com/16945664/58113341-4f40d980-7bc3-11e9-9b81-e05fc44dcb5f.png)
