### ISSUE TITLE
Odd Behavior when typing a numbered list into a text block

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2304]
1. Add new text block to story page
2. Begin typing a numbered list inside text block, "1. " 
3. Upon pressing the space bar after typing "1." the block converts to a numbered list block (correct), but jumps to the top of the page (incorrect)

<img width="713" alt="Screen Shot 2019-05-14 at 10 37 04 AM" src="https://user-images.githubusercontent.com/24547817/57706727-4f296280-7634-11e9-9bcf-605998c26ff1.png">

<img width="699" alt="Screen Shot 2019-05-14 at 10 37 26 AM" src="https://user-images.githubusercontent.com/24547817/57706752-56e90700-7634-11e9-8dd6-aff3b9e8a80f.png">

<img width="692" alt="Screen Shot 2019-05-14 at 10 37 34 AM" src="https://user-images.githubusercontent.com/24547817/57706759-594b6100-7634-11e9-9f5b-4e14194b0b53.png">

**Comment by swissspidy** [comment]
To explain this behavior:

We use some simple automatic text type detection to see whether one is currently writing a heading or a paragraph:

<img width="1077" alt="Screenshot 2019-05-14 at 12 19 23" src="https://user-images.githubusercontent.com/841956/57725707-9caccc00-7642-11e9-83cd-05d0e42f763f.png">

If you type in just one word or something, then it's usually marked as a heading. Now, when entering `1.`, the editor things you want to insert a list (like in Markdown) and turns the text block into a list block.

There we don't have any text type detection at all, so what you see is the same styling as if you would choose the Paragraph text type:

<img width="1081" alt="Screenshot 2019-05-14 at 12 25 18" src="https://user-images.githubusercontent.com/841956/57726007-5ad05580-7643-11e9-92b2-63ee39bd2150.png">

Now, the sudden jump is less then ideal. However, I cannot think of a good solution right now to improve this. Suggestions welcome.

**Comment by amedina** [comment]
Probably nor urgent prior to stable release, but one possibility would be to remove the ability to add lists that way. This would force lists to be inserted via the main inserter. Not ideal experience but may be better than having to drag the created list to the desired position.

**Comment by swissspidy** [comment]
The jumping after the block transformation is a bug and is the most annoying issue here. Let's fix that jumping issue and then test again.

**Comment by swissspidy** [comment]
For completeness, here's the list of registered transforms for the list block: https://github.com/WordPress/gutenberg/blob/b193b09c536485a9d06c98a208b3bf76935c9562/packages/block-library/src/list/transforms.js

Basically starting text with `1.`, `1)`, `*`, or `-` will result in a list block being added.

**Comment by miina** [comment]
Notes for QA:
- Add a Text block.
- Type in `1.` and then space.
- Verify that nothing changes: the font size stays the same, the block doesn't move to a different location, and it doesn't convert to any other block (still a Text block).
- Verify the same with typing in `1` and space, `*` and space, `-` and space.

**Comment by csossi** [comment]
Verified in QA
