### ISSUE TITLE
Dragging not working after resizing/rotating

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2306]
The gif looks bad, but the issue can be observed:

![out](https://user-images.githubusercontent.com/506089/57711883-74ae7000-7624-11e9-8b61-665646325413.gif)

**Comment by miina** [comment]
Note: this is happening for all blocks, not just for the image block.

Steps to reproduce:
- Add a block.
- Rotate or resize it.
- Try to drag right after.

**Comment by miina** [comment]
Instructions for testing:
- Add any block.
- Resize or rotate the block.
- Without clicking anything else, try to drag the block.
- Verify that dragging works.

**Comment by csossi** [comment]
Verified in QA (selection not required for drag)
