### ISSUE TITLE
Improve skeleton template inserter

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2307]
Related: #2289.

`createSkeletonTemplate` should be improved in a way that it resets _all_ block attributes, not just the ones in `emptyTemplateMapping`.

For example, animations, gradients, and opacity are all left untouched when inserting a skeleton template.

I think we might be able to use `getBlockType` in `createSkeletonTemplate` to get all available attributes, then reset them to their default value. Perhaps we could even use `{}` instead of all the `getSkeletonTemplateBlock` logic.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create a new story
1. Insert templates
1. Verify that things like gradients and images are removed, but the position of the blocks is like in the preview

**Comment by swissspidy** [comment]
Related: #2344

**Comment by miina** [comment]
Notes for QA:
- Use template inserter to add templates.
- Verify that the content (texts) is inserted as it is in the template.
- Verify that font sizes match respectively.
- Verify that after inserting a template and selecting a Text block the font stays the same.

**Comment by csossi** [comment]
The template experience is still not very user-friendly - oversized copy, overlapped content, etc.:
![image](https://user-images.githubusercontent.com/16945664/58710090-8bc1c180-8389-11e9-8dde-43e63c22e57f.png)

**Comment by miina** [comment]
@csossi Looks like the templates need resetting in the test environment. Will ask Weston to do that.

**Comment by swissspidy** [comment]
Newest changes should have been deployed now. Please test again @csossi. If something still looks odd, feel free to ask on Slack real quick. Thx.

**Comment by csossi** [comment]
Still some templates not looking right:
![image](https://user-images.githubusercontent.com/16945664/58883949-6dbbd000-86ad-11e9-9bca-76b7e9cb1928.png)
![image](https://user-images.githubusercontent.com/16945664/58883989-81673680-86ad-11e9-97ab-f0a2170eb1fe.png)
![image](https://user-images.githubusercontent.com/16945664/58884027-9217ac80-86ad-11e9-8485-ad3aa43e932b.png)
![image](https://user-images.githubusercontent.com/16945664/58884059-a065c880-86ad-11e9-8aec-d602dff0118b.png)

**Comment by swissspidy** [comment]
Thanks @csossi. Might need to deploy the latest changes again here. I'll let you know when you can revisit this again.

**Comment by swissspidy** [comment]
@csossi Can you test again? These errors shouldn't be there anymore. Make sure to clear your browser cache.

**Comment by csossi** [comment]
Verified in QA
