### ISSUE TITLE
Always allow switching from Transitional to Native

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2312]
If `add_theme_support('amp', [ 'paired' => true ])` is present, then a user should still be able to still switch from Transitional to Native via the AMP admin screen, and back from Native to Transitional. If a site works in Transitional mode then by definition it should work in Native mode. But if `paired => false` (or `paired` is absent), then Native would be the only option, as the reverse is not true: if a theme only works in Native mode then it may be using AMP components in its templates (e.g. `amp-sidebar`) without any non-AMP version also implemented.

This will allow all Paired themes (e.g. Neve) to be also used in Native mode.

**Comment by amedina** [comment]
> If a site works in Transitional mode then by definition it should work in Native mode. 

I think the opposite is true: Native ==> Transitional; but Transitional does not imply Native.

**Comment by westonruter** [comment]
I'm referring to the theme not to the site. If a theme is marked as being `paired` (transitional) then it is able to generate AMP pages as well as non-AMP ones. Therefore it should be able to switch from Transitional mode to Native mode. However, if it is not `paired` then it is not able to generate non-AMP pages, and thus it should not be able to switch from Native to Transitional.

Related to this is #2314 and whether AMP can be disabled for a given page/template. If a theme is not `paired` and yet it still allows AMP to be disabled, then that would imply it can actually still render non-AMP pages. In other words, such a theme is able to be used without the AMP plugin as a dependency. Such a theme could also presumably switch from Native to Transitional.

> I think the opposite is true: Native ==> Transitional; but Transitional does not imply Native.

This is true at a site level when considering plugins.

**Comment by westonruter** [comment]
Here's a plugin which forces Native mode even for themes that declare themselves as Transitional (`paired=true`): https://gist.github.com/westonruter/bf848ed3c8c922f192b6e2e39598e86c

**Comment by westonruter** [comment]
# Testing Instructions

* Install the [Neve](https://wordpress.org/themes/neve/) theme.
* Be able to switch between Standard and Transitional mode, even  though the theme is defined with `paired => true`. The Reader mode should _not_ appear.
* Activate the Twenty Nineteen theme and switching between all three website modes should still be possible (Standard, Transitional, Reader).
