### ISSUE TITLE
Add ability for theme/site to prevent AMP from being disabled

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2314]
On posts there is an “Enable AMP” for users to be able to opt-out of AMP:

> ![image](https://user-images.githubusercontent.com/134745/57723486-910ad680-763d-11e9-9eca-9fabcd690f32.png)

For sites in Native mode, this could actually result in the page being broken if the theme makes use of AMP components like `amp-sidebar` (ref #2312).

The same thing can happen if a user decides to disable AMP for some templates:

![image](https://user-images.githubusercontent.com/134745/57723673-f363d700-763d-11e9-9d3c-2ec3e0c004a3.png)

What there needs to be is a way for a theme to easily indicate that it does not support AMP to be turned off. Such an option should:

* Disable the “Enable AMP” checkbox.
* Hide the “Supported Templates” option (and force all to be enabled).
* Remove ability to “Reject” validation errors (maybe).

This option could be defined in code by the theme (as an `amp` theme support flag) or via a checkbox on the admin screen.

Also, being able to disable AMP for a given post is something that should perhaps be scoped to the Editor role (or Administrator). 

Similarly, rejection of validation errors should be limited to higher-privileged users, with Authors and Contributors shown validation errors warnings that prompt them either to remove the invalid block (#2285) or to escalate the error to an administrator for support. **Update:** For this, see #2673.

**Comment by amedina** [comment]
There seems to be a case for the scenario of having a site on Native AMP while keeping some posts and/or templates excluded: Native AMP for parts of the site, no AMP for other parts. How can we account for that? Would removing the amp attribute from the doc account for cases such as the sidebar one?

**Comment by amedina** [comment]
> Similarly, rejection of validation errors should be limited to higher-privileged users, with Authors and Contributors shown validation errors warnings that prompt them either to remove the invalid block (#2285) or to escalate the error to an administrator for support.

+1

**Comment by amedina** [comment]
> There seems to be a case for the scenario of having a site on Native AMP while keeping some posts and/or templates excluded.

Discussed offline: the above is correct, but the approach here is to provide the option to allow scenarios such as a theme requiring AMP for all content.

**Comment by westonruter** [comment]
I think this is closely related to #1864.

**Comment by westonruter** [comment]
I don't think we should do this. We should actually remove the ability for a theme to prevent AMP from being disabled. The challenge is if a theme depends on AMP components, then disabling AMP will cause problems. But when Bento AMP is a thing and themes can depend on AMP components specifically, then themes can have AMP turned off and reliably use AMP components.
