### ISSUE TITLE
Discourage Analytics Options

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2317]
We should remove the Analytics Options, as they should be within the jurisdiction of the developer or 3P plugins. 

**Update:** See https://github.com/ampproject/amp-wp/issues/2317#issuecomment-740788684

**Comment by westonruter** [comment]
Importantly, we'll need to make sure the Analytics options screen remains for any site that has the option populated.

Once there is a good ecosystem of analytics plugins, we can draw users to use them and start to deprecate the analytics in the plugin.

**Comment by westonruter** [comment]
The first step here would be to list out the AMP-compatible ecosystem plugins (e.g. Site Kit) on the analytics screen to encourage users to install plugins that tailor the analytics product.

**Comment by quicoto** [comment]
Any idea of a plugin to add Matomo self-hosted analytics into AMP?

Thank you in advance

**Comment by amedina** [comment]
This capability shall remain in place for the time being, but its use is not predicated as a substitute to 3P plugins specializing on analytics. Deprecation path being devised.

**Comment by westonruter** [comment]
In v1.6+ I want to see the analytics screen removed entirely and moved into an “Advanced” area of the main settings screen. This Advanced section would be collapsed by default. We'd use the REST API to update the Analytics and get rid of the current codebase entirely. The beginning of this Advanced section for Analytics would encourage the use of AMP-compatible analytics plugins.

**Comment by westonruter** [comment]
Update on this based on our meeting:

1. While we currently show a notice to use Site Kit if the user tries to enter `googleanalytics` or `gtag` as a entry type (https://github.com/ampproject/amp-wp/pull/5200), we should proactively show the notice up front if Site Kit is active as well. This will avoid the need for the user to discover the notice by typing in the vendor.
2. We should start showing a notice listing all known AMP-compatible analytics plugins in addition to Site Kit (see also #2313).
3. The Analytics section on the Settings screen won't be deprecated for removal but rather _discouraged_ in favor of analytics plugins. It seems there will always be a need to manually enter analytics, such as for analytics vendors that don't have AMP-compatible plugins or for in-house analytics.
4. There should be a filter which allows the plugin to block certain vendors from being provided if their corresponding plugin is active. So if Site Kit is active, there could be plugin code which _prevents_ users from supplying a `googleanalytics` type. This could be used as part of a bundle.
