### ISSUE TITLE
[AMP Stories] "Pan" animation looks strange

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#2318]
# Steps to Reproduce
1. Create a new story, like [this](https://story-test-wordpress-amp.pantheonsite.io/stories/a-chicago-getaway/)

2. Enter text in the text block

3. In "Animation Type," select "Pan Left," or any other "Pan" animation:
<img width="1436" alt="pan-animation" src="https://user-images.githubusercontent.com/4063887/57737601-dea13680-7671-11e9-8ae7-450e8ba18a0d.png">

4. Update the post, and go to the front-end, like on the 5th page in [this story](https://story-test-wordpress-amp.pantheonsite.io/stories/a-chicago-getaway/)

5. Expected: The text should pan, and should appear in the same place on the front-end

6. Actual: The text appears in the wrong place:

![with-is-resized](https://user-images.githubusercontent.com/4063887/57737662-17411000-7672-11e9-8fe5-4b2ad8653f6d.gif)

This looks to exist whether this uses `<amp-fit-text>` or not:
<img width="994" alt="issue-with-this" src="https://user-images.githubusercontent.com/4063887/57737814-9f271a00-7672-11e9-817e-7ced23aa9fc1.png">

**Comment by swissspidy** [comment]
Another issue with animations was reported in #2302. I wonder whether this issue is a bug in AMP, caused by our absolute positioning, or a bug in the AMP stories viewer. Perhaps we can try to reproduce in a non-WordPress context.

**Comment by kienstra** [comment]
Hi @swissspidy, sounds good, I'll try to reproduce this in non-WordPress.

**Comment by kienstra** [comment]
**Looks To Not Be Caused By WP Implementation**

Hi @swissspidy,
It looks like something similar appears in the AMP Playground.

For example, if you use this snippet in place of `<amp-story-page id="page-1">` in this [AMP Playground page](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fstyle-layout%2Fdesktop_and_landscape_mode_support&runtime=amp4stories), a similar issue exists:

```
<amp-story-page id="page-1">
        <amp-story-grid-layer template="fill">
                <amp-img src="https://amp.dev/static/samples/img/tree-1920x1277.jpg"
          width="1920"
          height="1277" layout="responsive"></amp-img>
        </amp-story-grid-layer>
        <amp-story-grid-layer template="fill">
                <h1 animate-in="pan-left">
                        Here is some text
                </h1>
       </amp-story-grid-layer>       
</amp-story-page>
```

![pan-left-example](https://user-images.githubusercontent.com/4063887/57739067-bb798580-7677-11e9-8019-3725034e2edc.gif)

Maybe this type of animation isn't intended for text. None of the [examples in this document](https://amp.dev/documentation/components/amp-story#animations) has an animated text element, like an `<h1>`. Many of the examples use `<amp-img>`.

Though that's just a guess.

**Comment by MackenzieHartung** [comment]
Testing note: When QAing this ticket please ensure all animations are reviewed within all specific block types. cc @csossi 

Issue #2302 likely related.

**Comment by miina** [comment]
Notes for QA:
- Make sure that only Image block allows selecting Pan animations (Pan Left, Right, Down, Up).
- Image block should have these 4 animations listed as options, the other blocks not.

**Comment by csossi** [comment]
Created this in editor (with pan animation):
![image](https://user-images.githubusercontent.com/16945664/58905890-cbb1dd00-86d8-11e9-98d3-12fceac33ff2.png)

On Preview, image is much larger:
![image](https://user-images.githubusercontent.com/16945664/58906027-0ddb1e80-86d9-11e9-857c-7e862124050d.png)


Is it the intent that images set to "pan" are automatically enlarged?

**Comment by swissspidy** [comment]
@csossi yes, that‘s what this animation does. It‘s great for going through panorama pictures (hence the name)
