### ISSUE TITLE
AMP plugin validator logs amp-timeago component as an error

### ISSUE THREAD

**Issue by pradeep910** [ampproject/amp-wp#2323]
Just wanted to point out that `amp-timeago` is AMP component and works properly on AMP pages. https://amp.dev/documentation/examples/components/amp-timeago/
However AMP plugin validator is logging it as an error. See the attachment below.
Should this be an error? 

![Screenshot 2019-05-16 at 12 15 05 AM](https://user-images.githubusercontent.com/1139853/57801103-9caaea00-7770-11e9-9ead-b978eb385f28.png)

**Comment by swissspidy** [comment]
Hi there and thanks for your report!

I just quickly tested this on my site and I cannot seem to reproduce this. Perhaps you can give us some more information about this? In particular:

* Which version of the plugin are you using
* Which mode are you using (classic/reader, paired/transitional, or native)
* How did you insert the `amp-timeago` component and what content did you put into it
* What error details are shown when you expand the errors to show details

**Comment by swissspidy** [comment]
I just saw that you reported a similar issue in #2067 before. Mentioning it here for context. Did you make sure to use the component with all the required attributes?

**Comment by westonruter** [comment]
@pradeep910 All of those validation errors have a Found URL count of “0”. All you need to do is click the “Clear Empty” button and they'll go away.

**Comment by westonruter** [comment]
In other words, you fixed the error and so that is why there are no URLs on which the error occurs. So now you can just clean up the old references. Eventually we should use WP Cron to clear out empty validation errors like this. See #1415.

**Comment by swissspidy** [comment]
D'oh, I didn't even look at that column 😅

**Comment by pradeep910** [comment]
@westonruter I still think `amp-timeago` should not be part of error list as its valid AMP component. So if we don't log this error, we don't have to use WP Cron to clear out empty validation errors of this component.

**Comment by swissspidy** [comment]
It is a valid component, but if you use it wrongly it will still be an error.

**Comment by pradeep910** [comment]
Yes, I think we were using wrong date format earlier. But that's fixed later. 

![Screenshot 2019-05-17 at 8 02 25 PM](https://user-images.githubusercontent.com/1139853/57935328-2e386a00-78df-11e9-94f3-99561ff39d88.png)

Corrected format - 

`<amp-timeago width="100" height="22" layout="responsive" class="gk-date-diff" datetime="2019-05-17T16:31:05+05:30" cutoff="2592000">May 17, 2019, 4:31 PM</amp-timeago>
 `

But since it got fixed later it is showing 0 URLs found. 

All good! 👍
