### ISSUE TITLE
Use Moment.js instead of timeago.js in amp-timeago block

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2324]
The `amp-timeago` block uses `timeago.js` to preview the block's output in the editor.

Although it is a relatively small library (2KB), it might be possible to drop it entirely and replace it with something like `moment().fromNow();`

The block editor already uses Moment.js, so this would be no extra script to load.

Chrome and Firefox also support [`Intl.RelativeTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat) for this kind of feature, so Moment.js could even just serve as a fallback for that.

**Comment by westonruter** [comment]
Also: Once Bento AMP is a thing, we should be able to get rid of both and just embed `amp-timeago` directly into the edit function. 🤞
