### ISSUE TITLE
Allow toggling class on submenu elements

### ISSUE THREAD

**Issue by felixarntz** [ampproject/amp-wp#2325]
As part of `AMP_Nav_Menu_Dropdown_Sanitizer`, one can currently dynamically insert dropdown toggle buttons, which toggle a class (such as `toggled-on`) on themselves when clicked (via `amp-state`). This appears to be only part of the solution, as sometimes themes also add a similar toggle class to the actual submenu element (typically the `ul.sub-menu` elements).

It sounds like a quick improvement to make by adding a new (optional) argument `sub_menu_toggle_class` that would add this class to the above elements via AMP bind. However, WordPress unfortunately doesn't offer a filter for that content, so in order to achieve that we would most likely use post-processing. There's only a `nav_menu_submenu_css_class` filter now but that wouldn't be able to accomplish it.

cc @westonruter

**Comment by westonruter** [comment]
> However, WordPress unfortunately doesn't offer a filter for that content, so in order to achieve that we would most likely use post-processing. There's only a `nav_menu_submenu_css_class` filter now but that wouldn't be able to accomplish it.

Seems fine to me since `AMP_Nav_Menu_Dropdown_Sanitizer` can already work in the post-processor phase. We just have to define `\AMP_Nav_Menu_Dropdown_Sanitizer::sanitize()`.

**Comment by westonruter** [comment]
We need to have an example theme that needs this in order to implement.
