### ISSUE TITLE
Block validation error for image blocks.

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2330]
Steps to reproduce:
- Add an image block.
- Add image.
- Save and refresh.

The validation errors can also be seen in the templates:
- Open the template inserter
- See the block validation errors and console log.

![Screen Shot 2019-05-16 at 9 45 32 AM](https://user-images.githubusercontent.com/3294597/57838001-2d5ee580-77c4-11e9-9984-0976896d402a.png)

**Comment by swissspidy** [comment]
LGTM
