### ISSUE TITLE
Guide users to not use heavy assets when creating stories

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2332]
The AMP Stories editor currently relies on users to only use pre-optimized assets (images and videos). This is not user-friendly. We should try to do this for them or else warn when we can't.

# Images

Currently the images that are added to a story can be much larger than necessary. For example, when selecting this image for background media:

![image](https://user-images.githubusercontent.com/134745/57868785-8163cd00-77b8-11e9-9dce-da6e2bd49b0f.png)

This image is used as-is in the editor. This is a violation of the [`oversized-images` Feature Policy](https://www.chromestatus.com/feature/5953669526716416). It's true that the AMP Cache should resize the image down, but this doesn't help when viewing the image on origin. Instead of being 3024x4032 and 2MB, it should rather be 1080x1440 and ~301kB (with WordPress's default 82% JPEG compression quality).

One caveat here is that we need to eventually support landscape stories, so there will always be wasted bytes when selecting a landscape image and the focal point picker is used for selecting the right “crop” in portrait. At the very least, if the image gets a height of 1440 as opposed to 3024 then this will still be an  improvement.

So I suggest we `add_image_size()` for `amp_story_page`, with an unbounded width and a constrained height without cropping:

```php
add_image_size( 'amp_story_page', 99999, 1440, false );
```

Then when an image is picked from the media library, we should use this image size as opposed to the `full` size.

This should also apply when automatically supplying a video's featured image as its `poster`, or when selecting an image as the poster generally.

# Videos

Uploading videos taken from one's phone to the media library is a much bigger challenge, as WordPress has no native transcoding ability for videos. A 2-second video extracted from a Motion Photo taken on a Pixel 3 is 7MB:

![image](https://user-images.githubusercontent.com/134745/57869902-e0c2dc80-77ba-11e9-922d-af74243d3f50.png)

The issue would be much worse if this wasn't just extracted from a Motion Photo. Imagine someone trying to use a 4K video at 60fps.

~The ideal here I think would be to allow users to embed control-less YouTube videos in stories, but this is not yet allowed. See https://github.com/ampproject/amphtml/issues/15847.~ YouTube is not going to be good to rely on, per [amphtml Slack conversation](https://amphtml.slack.com/archives/C9ARUE6Q6/p1558025296088500) with @newmuis:

> ![image](https://user-images.githubusercontent.com/134745/57872726-2da9b180-77c1-11e9-80b3-76093e6e2773.png)

☝️ Edit: YouTube videos are _rarely_ portrait.

So perhaps we should add a warning to users when a video seems to be too large. I'm not sure what “too large” is, but perhaps we should target 1 megabyte per second? So we'd show no warning if there is a 7-second video that is 7MB.

The dog video in the [Hello World](https://amp.dev/documentation/examples/introduction/stories_in_amp/preview/) example is 2MB for 3 seconds:

![image](https://user-images.githubusercontent.com/134745/57870460-fe447600-77bb-11e9-9cdc-04bfc198dd93.png)

**Comment by swissspidy** [comment]
FWIW in 5.3 some effort is being put into [image processing improvements](https://make.wordpress.org/core/2019/05/15/improve-processing-of-uploaded-images/) in WordPress, and which might eventually lead to better responsive image support.

**Comment by westonruter** [comment]
Also, even with responsive image support, we would still at least need the image size to be defined in order to be served.

**Comment by amedina** [comment]
This would be great to have. I would like to see a combination of automatic handling (as the image case here), and information/warnings in cases where manual intervention is needed. Same guidelines as the AMP plugin functional spectrum (manual ~> automatic).

**Comment by kienstra** [comment]
Hi @westonruter,
This looks interesting. Would you mind if I worked on it?

Thanks, see you soon at WCEU.

**Comment by westonruter** [comment]
Go ahead

**Comment by kienstra** [comment]
Thanks!

**Comment by kienstra** [comment]
**Test Steps**
(For when #2509 is merged)

# Image Block
1. Create a new story with an image block

2. Upload an image to the block that's taller than `1440px`, like any of these (not necessarily all of them):

[1000 x 1500](http://lorempixel.com/1000/1500/technics/)
[1200 x 1500](http://lorempixel.com/1200/1500/technics/)
[1500 x 1600](http://lorempixel.com/1500/1600/technics/)
[1800 x 1800](http://lorempixel.com/1800/1800/technics/)

3. Expected: In the Inspector Controls, the 'AMP Story Max Size' is available in the 'Image Size' `<select>` element:

<img width="953" alt="image-block-here" src="https://user-images.githubusercontent.com/4063887/59263694-2ed6ce80-8c07-11e9-8c83-a2f356802dbf.png">

# Background Video
1. Click a page, then click 'Background Media' > 'Select Media':
<img width="966" alt="background-media-here" src="https://user-images.githubusercontent.com/4063887/59264111-013e5500-8c08-11e9-8bd1-62839cee2dd8.png">

2. Click the 'Upload Files' tab, and upload [this video](https://drive.google.com/file/d/1gM3_6iarZcrjeXo2lOePVSPxlUEVKiiU/view?usp=sharing)

3. Click 'Select'

4. Expected: a notice should appear: 'A video size of less than 1 MB per second is recommended.'

<img width="997" alt="notice-here" src="https://user-images.githubusercontent.com/4063887/59264246-511d1c00-8c08-11e9-8303-d907d414a5b7.png">

# Background Image
1. Click 'Background Media' > 'Edit Media'

2. Click the 'Upload Files' tab, and upload an image taller than `1440px`, like [this](http://lorempixel.com/1900/1900/technics)

3. Inspect the source of the page

4. Expected: the `url` of the `background-image` should end in `1440.jpeg`, even though the original image was taller than that:

<img width="879" alt="bg-img-url" src="https://user-images.githubusercontent.com/4063887/59264553-f20bd700-8c08-11e9-86dd-787184e0f673.png">

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Hope you're doing great. Could you please test this?

Thanks, Claudio.

**Comment by kienstra** [comment]
Ah, sorry. I should wait until this is deployed to the test environment to assign this to testing.

**Comment by csossi** [comment]
Selected this image:
![image](https://user-images.githubusercontent.com/16945664/59361970-b8b69280-8d00-11e9-9426-a538ab090eb4.png)

Not seeing the "AMP Story Max Size" option:
![image](https://user-images.githubusercontent.com/16945664/59362165-fe735b00-8d00-11e9-99ee-a3eb6d19bc9e.png)

**Comment by kienstra** [comment]
Hi @csossi,
Thanks for testing this.

1. Was that image newly-uploaded? This won't work with existing images that were already in the Media Library, as it needs to create the image size.

2. Was the image for an Image block or Background Media?

**Comment by swissspidy** [comment]
Maybe we can regenerate thumbnails on the test environment / cc @westonruter

**Comment by csossi** [comment]
Verified in QA

**Comment by kienstra** [comment]
@csossi, thanks a lot for testing this again!

**Comment by csossi** [comment]
you're welcome, @kienstra !!

**Comment by westonruter** [comment]
> Maybe we can regenerate thumbnails on the test environment

Now running: `terminus remote:wp wordpress-amp.story-test -- media regenerate --only-missing --yes --skip-delete`

**Comment by kienstra** [comment]
Nice, thanks!
