### ISSUE TITLE
Review shared amp-editor-blocks script

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2333]
`amp-editor-blocks.js` is currently enqueued for both the regular block editor as well as the stories editor.

That script is rather small, and only applies a few filters to add some extra attributes and controls to existing blocks.

As pointed out in https://github.com/ampproject/amp-wp/pull/2331#discussion_r284780247, most if not all of the controls added by  that script do not make sense in a stories context. For example the AMP layout, noloading, or lightbox controls.

We need to go through them and see whether we need to move them over to `amp-block-editor.js` (which doesn't load for stories). Perhaps we can even get rid of `amp-editor-blocks.js` so that everything is in either `block-editor.js` or `amp-stories.js`.

Tagging @westonruter @kienstra as you probably know these controls better than I.

**Comment by westonruter** [comment]
Actually @miina would be the expert on these controls.

**Comment by swissspidy** [comment]
Thanks Weston, good to know! 🙂

**Comment by miina** [comment]
Sure, I'll look through the controls either tomorrow (Friday) morning or Monday morning.

**Comment by swissspidy** [comment]
Monday should be fine enough :)

**Comment by miina** [comment]
@swissspidy It seems to be that none of this is necessary for AMP Stories:
- Layout
- Lightbox
- ampFitText (it is added in the Stories editor separately already) together with minHeight, et.
- No loading
- ampCarousel - it's not used anyway in Stories.

The other filters which are used for filtering saving etc. are also not necessary for the AMP Stories.

Not sure if there would be any reason for keeping "AMP No Loading" setting?

I think it makes sense to do as you mentioned -- get rid of the file and move everything to either `block-editor.js` or `amp-stories.js`.

**Comment by westonruter** [comment]
> Not sure if there would be any reason for keeping "AMP No Loading" setting?

It doesn't appear that the placeholder “…” even appears for AMP Stories images, so this setting doesn't appear to be relevant for stories. In effect, stories has `noloading` by default. So it can be removed.

It's also of dubious value generally as well). It should probably be a theme configuration instead.
