### ISSUE TITLE
Normalize frameborder=no|yes to frameborder=0|1 in iframe sanitizer

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2335]
When adding an `iframe` such as:

```html
<iframe frameborder="no" height="200" scrolling="no" src="https://player.megaphone.fm/DEM1119155060?" width="100%"></iframe>
```

It gets converted into an `amp-iframe` successfully as:

```html
<amp-iframe frameborder="0" height="200" scrolling="no" src="https://player.megaphone.fm/DEM1119155060?" width="640" sandbox="allow-scripts allow-same-origin" layout="intrinsic" class="amp-wp-enforced-sizes">
    <span placeholder="" class="amp-wp-iframe-placeholder"></span>
    <noscript>
        <iframe height="200" scrolling="no" src="https://player.megaphone.fm/DEM1119155060?" width="100%"></iframe>
    </noscript>
</amp-iframe>
```

Nevertheless, one AMP validation error is raised in the process:

![image](https://user-images.githubusercontent.com/134745/57876945-74040e00-77cb-11e9-8893-e39cedbb3a84.png)

This validation error is pointless, however, because the `iframe` that `amp-iframe` component generates already provides `frameborder=0`:

![image](https://user-images.githubusercontent.com/134745/57876996-90a04600-77cb-11e9-9c37-5bba77ef6954.png)

It seems that while HTML allows `no` as a synonym for `0` (and `yes` for `1`), this is [not supported by AMP](https://github.com/ampproject/amphtml/blob/bf504ab750f64b9343c228a1756d38d95bbba7c8/extensions/amp-iframe/validator-amp-iframe.protoascii#L46-L50):

```
  attrs: {
    name: "frameborder"
    value: "0"
    value: "1"
  }
```

Apparently this is [not even allowed in HTML4](https://www.w3.org/TR/html4/present/frames.html#h-16.5), so it could just be a common author mistake (which browsers gracefully handle, and it has been [deprecated/removed in HTML5](https://www.w3.org/TR/2010/WD-html5-20100304/obsolete.html#non-conforming-features)):

```
  frameborder (1|0)          1         -- request frame borders? --
```

The AMP plugin makes the default `frameborder=0` as seen in the generated example above. What is missing is when the `$value` is `no` it should be normalized to `0`, and when `yes` normalized to `1`:

https://github.com/ampproject/amp-wp/blob/437c335b84106a8099fb3929c8d6faeaa6d7fb7b/includes/sanitizers/class-amp-iframe-sanitizer.php#L153-L158

This will prevent a validation error from being raised, and it will allow `iframe[frameborder=yes]` to actually result in `amp-iframe[frameborder=1]` as the user intends.

**Comment by swissspidy** [comment]
>  so it could just be a common author mistake (which browsers gracefully handle

Perhaps that comes from [the other frame elements](https://html.spec.whatwg.org/#frames-and-framesets):

> A frameset or frame element has a border if the following algorithm returns true:
> 
> If the element has a frameborder attribute whose value is not the empty string and whose first character is either a U+0031 DIGIT ONE (1) character, a U+0079 LATIN SMALL LETTER Y character (y), or a U+0059 LATIN CAPITAL LETTER Y character (Y), then return true.

Interesting read :)

**Comment by westonruter** [comment]
Good find. So it's not just `yes` and `no` but `y` and `n` that we also should handle 😄
