### ISSUE TITLE
Numbered List, images & boxes

### ISSUE THREAD

**Issue by bilaldweik** [ampproject/amp-wp#2341]
My Website is in Arabic language, after using this plugin I have faced the followings:

1- the numbered list are not aligned correctly, it should be aligned one step ahead (compared to the normal paragraph). but actually, it shown as one step BEHIND instead!

2- The images that are aligned left, and are little big, should be shown separately in the line, without any text beside it, but actually, some of texts are show (one letter each line!).

3- I’m using some styled boxes (boxes with certain background colour), and by this plugin, it is shown as normal text in way that appears the same as the article texts, I need to distinguish between them.

Example URL: https://www.kammasheh.com/%D9%83%D9%8A%D9%81%D9%8A%D8%A9-%D8%B6%D8%A8%D8%B7-%D8%AA%D8%A7%D9%8A%D9%85%D8%B1-%D8%A7%D9%84%D8%AB%D9%84%D8%A7%D8%AC%D8%A9-%D9%81%D9%8A-8-%D8%AE%D8%B7%D9%88%D8%A7%D8%AA-%D8%B3%D9%87%D9%84%D8%A9/amp

![Photo from Bilal Dweik (1)](https://user-images.githubusercontent.com/50753001/57952202-1c61c180-78f5-11e9-9010-2c679c5ae92b.jpg)
![Photo from Bilal Dweik](https://user-images.githubusercontent.com/50753001/57952208-1d92ee80-78f5-11e9-910b-badef569c9f8.jpg)

**Comment by westonruter** [comment]
> 1- the numbered list are not aligned correctly, it should be aligned one step ahead (compared to the normal paragraph). but actually, it shown as one step BEHIND instead!

Non-AMP:

![image](https://user-images.githubusercontent.com/134745/57978167-416d3780-79bc-11e9-86c9-fb1effc85fcb.png)

AMP:

![image](https://user-images.githubusercontent.com/134745/57978170-49c57280-79bc-11e9-95d2-c8e20796ff21.png)

Are you referring to the numbers appearing indented under the headings? And you'd expect them to appear directly under “ الأدوات” in both cases?

**Comment by bilaldweik** [comment]
Hi westonruter,

Yes, I'm referring to these numbers, and I'm expecting both AM and non-AMP look like the same. the numbers should appear directly under "الأدوات" but not aligned with it, instead, it should be with one **tab** to the left.

Thanks again

**Comment by westonruter** [comment]
@bilaldweik ok, in looking at your AMP page's CSS, I see:

```css
.amp-wp-article-content ul,
.amp-wp-article-content ol { margin-left: 1em; }
```

This is unexpected. It should say `margin-right` not `margin-left` here, given this code:

https://github.com/ampproject/amp-wp/blob/348411df58fdf66ecffbcf1486b31c8393659a0c/templates/style.php#L251-L254

So for some reason `is_rtl()` is returning false on your site.

This is strange because your `html` element does have the expected direction:

```html
<html amp dir=rtl lang=ar>
```

I'm not sure why that would be.

**Comment by westonruter** [comment]
@bilaldweik Actually, I may know why. The introduction of better RTL support happened in #1674. Did your theme by chance fork the [`templates/style.php`](https://github.com/ampproject/amp-wp/blob/348411df58fdf66ecffbcf1486b31c8393659a0c/templates/style.php) at a point before that change was merged? Perhaps your theme needs to update its `style.php` to include the latest changes?

**Comment by bilaldweik** [comment]
Thank you @westonruter for your reply, I'll check the latest update if it is included in the Style.php or not..

**Comment by swissspidy** [comment]
@bilaldweik Any update on this?

**Comment by bilaldweik** [comment]
@swissspidy Actaully, I'm still waiting a reply from the author of the theme that I'm using, which was not updated since January 2019. Unfortunately, I don't have a technical background, so, I need to wait their reply :(
