### ISSUE TITLE
Setting Text block as bold/italic causes unexpected shift

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2342]
If I add a Text block and increase its height like so:

![image](https://user-images.githubusercontent.com/134745/57952171-396ca500-78a1-11e9-8be2-204223034185.png)

Upon selecting Bold or Italic, the text shifts up unexpectedly:

![image](https://user-images.githubusercontent.com/134745/57952217-50ab9280-78a1-11e9-8a73-6d7a203fc12d.png)

![image](https://user-images.githubusercontent.com/134745/57952237-68831680-78a1-11e9-88ef-92b69f370051.png)

Removing the formatting causes the expected position to be restored.

**Comment by swissspidy** [comment]
Hmm looks like that's because of the `display: flex` used to make the preview look like the `amp-fit-text` on the front end.

The `amp-fit-text` component uses the same technique, but the content is wrapped in another div. I guess we have to do that too, at least in the editor.

**Comment by swissspidy** [comment]
>  I guess we have to do that too (just in the editor)

Turns out AMP uses a few more divs (absolute positioned and also flexbox). I briefly tried this in dev tools, but without any luck.

**Comment by mehigh** [comment]
Wrapping the text in a div element doesn't work, as these are child elements of a paragraph. 
Here's a solution I've toyed with in the console - wrap the text within a <span>
This way we get the benefits of flex on the wrapper without having a negative effect on the direct child elements which aren't text nodes (like em / strong): 
http://cloud.urldocs.com/b11695ac83e2

**Comment by mehigh** [comment]
I toyed with this some more today
https://codepen.io/mehigh/pen/qGQeQP
I've swapped the flex (which doesn't play that well with children of both text node type & elements) by a classic known height vertical centering approach.

**Comment by csossi** [comment]
Verified in QA

**Comment by miina** [comment]
Instructions for testing:
- Add a Text block
- Add some text inside
- Assign italic and/or bold for part of the text (e.g. some letters)
- Verify that the parts of words that have italic/bold assigned are not broken into separate lines
- Verify that if the text block is quite long and there is just one word, the word is centered in the middle vertically (add background color for better visibility for testing that

Note that this is for Automatically assigned font size only.

**Comment by csossi** [comment]
Verified in QA
