### ISSUE TITLE
AMP Stories Template Internationalization

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2344]
Realized while working on #2343 that the templates cannot currently be translated.

Ideally, when I am using WordPress in German, I would want to see templates with content written in my language. Especially since with #2343 that content is going to be kept upon insertion.

We cannot really translate the templates in PHP, as users A and B might have different locales but still be able to see template previews in their language. So I guess the only solution is to have some sort of placeholders in the template, and then replace this placeholders dynamically in the editor when loading the blocks.

**Comment by amedina** [comment]
Placeholders are also good to customize them to reflect the purpose of the specific block on the given template. Instead of having "Write text...", it should say "Write tip here", "Add Image...", etc.
