### ISSUE TITLE
Rotation handles visible in block style preview

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2345]
`.rotatable-box-wrap` is currently visible in block style previews and should be hidden.

Also, ideally the block would be centered in the preview (horizontally and vertically).

Current:

<img width="275" alt="Screenshot 2019-05-17 at 15 51 14" src="https://user-images.githubusercontent.com/841956/57960125-fec43600-78bb-11e9-9292-3710d03a676e.png">

Suggested direction:

<img width="131" alt="Screenshot 2019-05-17 at 15 52 23" src="https://user-images.githubusercontent.com/841956/57960130-02f05380-78bc-11e9-8289-758daa3d717d.png">

**Comment by miina** [comment]
@swissspidy This seems to be fixed, moving it to Ready for Review, could you confirm if you still see the issue?

What I see:
![Screen Shot 2019-05-28 at 2 42 24 PM](https://user-images.githubusercontent.com/3294597/58478691-f7701880-8156-11e9-902f-3c2e52d9addd.png)

**Comment by swissspidy** [comment]
Indeed seems to have been fixed in the meantime 👍
