### ISSUE TITLE
Choosing Media from Media Library causes error

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2350]
Steps to reproduce:
1. Choose an Image block
2. Click on "Media Library" for choosing the image.
3. Choose an Image.
4. See the console log.

![Screen Shot 2019-05-20 at 2 02 45 PM](https://user-images.githubusercontent.com/3294597/58020269-f4967780-7b07-11e9-8fea-15718f1c6030.png)

**Comment by miina** [comment]
Instructions for testing:
- Add an image block.
- Click "Media Library"
- Choose an image.
- Make sure that the editor doesn't freeze, the functionality continues to work as expected and that no errors appear in console for "Maximum call stack size exceeded".

@csossi This ticket is implemented but hasn't been deployed to the test environment yet. Once it gets deployed it'll be ready for QA.

**Comment by miina** [comment]
Should be ready for QA now.

**Comment by csossi** [comment]
verified in QA
