### ISSUE TITLE
Text displays in 1 line in editor, in 2 lines in the FE

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2353]
Steps to reproduce:

1. Create a text block.
2. Resize the text block to cover around 3/4 of the width.
3. Add text into the text block so that it would exactly fill in the full width on one line, so that adding one more character would break it to two lines.
4. Save, see the results in the FE.

Editor:
![Screen Shot 2019-05-20 at 6 51 42 PM](https://user-images.githubusercontent.com/3294597/58038476-5965c800-7b30-11e9-8ba7-b416cd30139e.png)

FE:
![Screen Shot 2019-05-20 at 6 52 26 PM](https://user-images.githubusercontent.com/3294597/58038560-8914d000-7b30-11e9-8993-7289e4455af0.png)

**Comment by westonruter** [comment]
Would this be largely expected due to the responsive nature of stories? That is, unless the frontend preview is exactly the same aspect ratio as the editor.

**Comment by miina** [comment]
Actually, yes, you're right, that's expected for AMP Fit Text. Closing the issue.
