### ISSUE TITLE
Image doesn't resize while resizing

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2357]
When resizing an image in the post editor, it resizes together with the resizing box while resizing.

In the AMP Stories editor, regression was introduced within #2310 and it's now not "live" resizing anymore.

AC: The image should resize while resizing, too.

See also https://github.com/ampproject/amp-wp/pull/2310#issuecomment-494106233.

**Comment by miina** [comment]
Notes for QA:
- Add an Image block
- Verify that it isn't possible to resize a placeholder without selecting an image.
- Select an image (both via Media Library and also URL).
- Verify that while resizing, the image is resizing "live", together with the handle.

**Comment by csossi** [comment]
I'm unable to add an image via URL. Trying to add https://en.wikipedia.org/wiki/White_Zombie_(band)#/media/File:White_zombie.JPG but it appears as a broken image:

![image](https://user-images.githubusercontent.com/16945664/58509360-66a03980-8164-11e9-959d-3663f8e83d37.png)

**Comment by westonruter** [comment]
@csossi That URL is actually not for an image, although it appears so. The filename appears after `#` indicating it is not part of the underlying URL. So it's an HTML page and that is why it is not working. This is the actual image file URL: https://upload.wikimedia.org/wikipedia/en/7/73/White_zombie.JPG

**Comment by csossi** [comment]
Thanks, @westonruter 

Image still not resizing

Image selected from media library:
![image](https://user-images.githubusercontent.com/16945664/58561534-52f0e380-81f5-11e9-831a-7720d3013525.png)

Resized (crops image):
![image](https://user-images.githubusercontent.com/16945664/58561582-68fea400-81f5-11e9-9b91-23d2ddfd141a.png)

**Comment by miina** [comment]
@csossi That's expected behavior since it needs to cover the whole area without changing the ratio.

**Comment by miina** [comment]
Note: the issue that got fixed here and needed QA was for the image to move together with the resizing handle.

Could you please confirm if the Image size is moving together with the resize handle, please see https://github.com/ampproject/amp-wp/pull/2310#issuecomment-494106233 for reference as well.

**Comment by csossi** [comment]
Verified in QA
