### ISSUE TITLE
Text block words break in the editor but not in the FE

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2359]
When amp-fit-text is used, there is a difference between the editor and front-end:
it looks like in the FE words are not broken to multiple lines, however, this does happen in the editor.

Steps to reproduce:
- Create a text block and add some text.
- Make the Text block long and narrow.
- Save, compare the results in the editor and in the FE.

![Screen Shot 2019-05-21 at 11 45 44 AM](https://user-images.githubusercontent.com/3294597/58085940-fd498500-7bbd-11e9-953f-81747d47fb45.png)
![Screen Shot 2019-05-21 at 11 45 36 AM](https://user-images.githubusercontent.com/3294597/58085941-fd498500-7bbd-11e9-81ad-b9f4bea40aab.png)

**Comment by swissspidy** [comment]
Gutenberg uses `.block-editor-block-list__layout .block-editor-block-list__block { overflow-wrap: break-word; }` and that seems to cause this.

Using `overflow-wrap: normal;` stops the word break, but seems to conflict with font size calculation somehow.

**Comment by miina** [comment]
Notes for QA:
- Create a Text block with text inside.
- Verify that if the text block is long and narrow, the font size is reduced so that the words wouldn't break.
- Verify that the results are similar in the editor and in the FE.

**Comment by csossi** [comment]
Verified in QA (words not breaking)
