### ISSUE TITLE
Validation: BlogPosting requires an image

### ISSUE THREAD

**Issue by kraftbj** [ampproject/amp-wp#236]
https://github.com/Automattic/amp-wp/blob/1bb6f5b28a3e0b0949a5998c2f91bd713ae6ffd3/includes/class-amp-post-template.php#L141

In the JSON for denoting the `BlogPosting`, an [image is required](https://developers.google.com/structured-data/rich-snippets/articles?#article_markup_properties), so we are producing invalid AMP pages when a featured image is not set.

Images should be reflective of the article, so I'm not sure if there's any wiggle room for us to use some type of default. Alternatively, we could either use or have a filter to allow Jetpack's Media Summary to provide a result ([checks for a number of possible images](https://github.com/Automattic/jetpack/blob/3.9.1/class.jetpack-post-images.php#L405))

**Comment by mjangda** [comment]
@rudygalfi is this something we can raise with the Webmaster Tools team? An image won't always be available for posts (think text- or video-only posts) and it doesn't feel right to use a fallback or placeholders like the logo or an empty image just for the sake of validation.

**Comment by alkampfergit** [comment]
It could be possible to select an image based on tag or category of the post? It would be nice to being able to setup an image for each category and tag for the blog, and use that image as fallback if an image is not available.

**Comment by westonruter** [comment]
Note that the error is not an AMP validation error but a validation issue with Google search requirements. Nevertheless, the AMP plugin now warns the user when no featured image is selected. See also #1845 which considered grabbing a fallback from the post content similar to how Jetpack is doing.
