### ISSUE TITLE
Pressing Cntrl+Enter in the Text block causes error in the console

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2377]
Steps to reproduce:
1. Add a Text block.
2. Write something.
3. Click Cntrl + Enter.

![Screen Shot 2019-05-22 at 11 45 32 AM](https://user-images.githubusercontent.com/3294597/58165010-2c77f900-7c87-11e9-8341-2f31ffe01152.png)

**Comment by miina** [comment]
Instructions for QA:
- Add a text block.
- Press Cntrl + Enter
- Verify that this doesn't cause any console errors.

**Comment by csossi** [comment]
Verified in QA
