### ISSUE TITLE
The tag 'amp-next-page with inline config' appears more than once in the document

### ISSUE THREAD

**Issue by sudhakarsukumar** [ampproject/amp-wp#2379]
After enabling the Infinite Scroll (Experimental). occurs validation error as per the AMP Validator.

Validation Status: FAIL
  
The tag 'amp-next-page with inline config' appears more than once in the document. MANDATORY_AMP_TAG_MISSING_OR_INCORRECT

here is website.
https://www.nungu.io/gentleman-jack-the-moment-suranne-jones-makes-the-audience-upset/?amp

please review and help us to resolve the error.

**Comment by swissspidy** [comment]
Hi there

You appear to be using a different AMP plugin called [AMP for WP](https://ampforwp.com/). Please report any issues you have with them. This project here is not affiliated with it.
