### ISSUE TITLE
Resizing a Text block doesn't always respect the minimum limits

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2390]
Steps to reproduce:
- Add a text block.
- Add some text with background color (for visibility).
- Resize the text block to be long.
- Try to resize the text block to be as narrow as possible.

![Screen Shot 2019-05-23 at 11 27 40 AM](https://user-images.githubusercontent.com/3294597/58241928-28fb7500-7d4e-11e9-921d-8359c66c25cf.png)
 
![Screen Shot 2019-05-23 at 11 32 17 AM](https://user-images.githubusercontent.com/3294597/58242081-77a90f00-7d4e-11e9-9602-2226fb4d161a.png)

Expected: The width of a Text block should not go lower than it's minimum width assigned (40)

**Comment by swissspidy** [comment]
**Testing instructions**

1. Add a text block.
1. Add some text with background color (for visibility).
1. Resize the text block to be long.
1. Try to resize the text block to be as narrow as possible.
1. Verify that width and height don't go below a certain minimum

**Comment by csossi** [comment]
I can shrink enough so it appears in the editor that there is overlap:
![image](https://user-images.githubusercontent.com/16945664/58508847-0957b880-8163-11e9-8ce4-d86ddfea1e4b.png)


noted that in preview at this size, no text appears:
![image](https://user-images.githubusercontent.com/16945664/58508876-25f3f080-8163-11e9-9dc2-2ae5dd20de45.png)

**Comment by miina** [comment]
I'm not able to reproduce the issue, in my testing, the block respects the minimum limit and does not allow going so narrow. Could you please confirm if you can see the issue, @swissspidy & @kienstra?

On another note:
There seems to be an additional issue, namely, the FE doesn't seem to consider the set width and height.
Editor:
![Screen Shot 2019-05-29 at 1 08 19 PM](https://user-images.githubusercontent.com/3294597/58552512-dec53880-8212-11e9-9ab0-d97a4c4234a4.png)

FE:
![Screen Shot 2019-05-29 at 1 08 23 PM](https://user-images.githubusercontent.com/3294597/58552522-e2f15600-8212-11e9-8ecd-eb4097482dbe.png)

I'll create an issue for that and try to fix it ASAP.

**Comment by miina** [comment]
@csossi Ready for re-testing.

**Comment by csossi** [comment]
Verified in QA

Editor:
![image](https://user-images.githubusercontent.com/16945664/58662776-f545bf80-82f8-11e9-995f-95f3d6f9a866.png)

FE:
![image](https://user-images.githubusercontent.com/16945664/58662794-0393db80-82f9-11e9-9934-0f38f0d2cae3.png)
