### ISSUE TITLE
Resizing Title block below minimum limit causes change in its width and height both

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2391]
Steps to reproduce:

- Add a title block.
- Add a longer title with a background color to see the effect better.
- Remove Automatic font change (amp-fit-text) and assign a larger font size.
- Resize the title block to change width
- Observe the height changing as well.

![May-23-2019 12-07-37](https://user-images.githubusercontent.com/3294597/58244682-6f9f9e00-7d53-11e9-851a-3a659bc84716.gif)

Expected:
- When changing the width, only the width should change.
- The width and height should not go under the limit (the room that the block needs to fit its text)

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create new story
2. Add a longer title
3. Add title block
4. Disable automatic font size
5. Resize block width and verify that height does not change.
6. Verify that height and width cannot be made smaller than what is needed to fit the text.

**Comment by csossi** [comment]
Verified in QA
