### ISSUE TITLE
PHPSESSID Cookie causes validation to time out.

### ISSUE THREAD

**Issue by mattrn** [ampproject/amp-wp#2392]
Hello!

I am not sure if this really falls in this plugin's responsibility or is just symptom of something else.

While using this plugin in paired mode, validation of a post timed out with a white screen and no error msg.

I did some digging and fount that in **AMP_Validation_Manager::validate_url** the **wp_remote_get()** does return empty after timeout.

It seems that one of my sites cookies, "**PHPSESSID**", is causing this problem, when I **unset()** it in the **$_COOKIE** Array everything works.

I know a default php session cookie shouldn't get set in my site (I am suspecting a plugin does this), but maybe there is a way to make this call more robust. Could the number of cookies be reduced to the ones really necessary instead of just passing them all?

**Comment by swissspidy** [comment]
Thanks for your report!

This reminds me of https://core.trac.wordpress.org/ticket/47320 where there's the same issue.

> I know a default php session cookie shouldn't get set in my site

Correct, WordPress does not use PHP sessions.

> Could the number of cookies be reduced to the ones really necessary instead of just passing them all?

That sounds reasonable. Off the top of my head there are the following cookies in WP by default:

* Cookies prefixed with `wp-postpass_`
* Cookies named `AUTH_COOKIE`
* Cookies named `SECURE_AUTH_COOKIE`
* Cookies named `LOGGED_IN_COOKIE`

Limiting to these would make sense.

I could see some issues when some plugins add custom cookies for access control, but in that case they could filter the HTTP calls I guess.
