### ISSUE TITLE
Consider making video caption optional

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2393]
Video caption always displays in the editor, consider making it optional via Toggle as it is for Image block.

**Comment by miina** [comment]
Instructions for testing:
- Create a Video block
- Verify that the caption isn't displayed by default
- Verify that caption can be added via settings in the block sidebar.
- Verify that the editor view reflects the backend view (the caption displays when toggled on and filled in, and doesn't display when toggled off).

**Comment by csossi** [comment]
Verified in QA
