### ISSUE TITLE
Resizing box around video goes smaller than the video itself

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2394]
Steps to reproduce:
- Create a video block.
- Add video, e.g. from URL.
- Try to resize the video block to small.

![Screen Shot 2019-05-23 at 12 30 20 PM](https://user-images.githubusercontent.com/3294597/58246132-93181800-7d56-11e9-9b3c-e2c7a5a7dce0.png)

Expected: resizing should adjust the video's size.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create a video block.
1. Add video, e.g. from URL.
1. Try to resize the video block to make it small.
1. Verify that video height/width are changed accordingly.

**Comment by csossi** [comment]
Nothing seems to happen when I paste a YouTube url and click "Apply" - can't test this one
![image](https://user-images.githubusercontent.com/16945664/58502638-eaeac080-8154-11e9-8f1b-3fae2f1d3bd6.png)

**Comment by westonruter** [comment]
> Nothing seems to happen when I paste a YouTube url and click "Apply" - can't test this one

@csossi You'll have to supply the URL to an actual video file (e.g. `.mp4`). 

You've identified an important issue, however. This field should have validation to handle the case of incorrectly adding a YouTube video, since YouTube is not currently allowed in AMP Stories.

**Comment by swissspidy** [comment]
@csossi Please test with an actual video file URL or a video from the media library for now. We'll handle pasting YouTube URLs separately. Thanks!

**Comment by swissspidy** [comment]
Created a separate issue for it: #2455.

**Comment by csossi** [comment]
Understood - thanks, guys

**Comment by csossi** [comment]
Resizing serves to crop the video as opposed to making it smaller:

Editor - from media library:
![image](https://user-images.githubusercontent.com/16945664/58555950-cdffcd00-81e8-11e9-939d-66e8dc16a393.png)

Resized:
![image](https://user-images.githubusercontent.com/16945664/58555979-e2dc6080-81e8-11e9-9d73-12a5bd07c663.png)


Preview:
![image](https://user-images.githubusercontent.com/16945664/58556021-fbe51180-81e8-11e9-885d-0cdd4b086054.png)

**Comment by miina** [comment]
@csossi Thanks for testing, that's expected behavior. Moving this to Ready for Merging.

**Comment by swissspidy** [comment]
@miina Hmm, in my quick test it doesn't crop the video, but skews it instead 🤔

**Comment by miina** [comment]
@swissspidy I can also see that it's not cropping anymore 😕 I'll reopen this issue and look into this again, not sure what changed meanwhile.

**Comment by miina** [comment]
@csossi Ready for re-testing. Note that it's OK if the video "crops", please refer to the description as the original issue -- the video shouldn't be larger than the resized area.

**Comment by csossi** [comment]
Verified in QA
