### ISSUE TITLE
Adding onclick="" to AMP

### ISSUE THREAD

**Issue by zJar84** [ampproject/amp-wp#2402]
Hello, I have this line of code on my html:

`<p onclick="window.open('https://www.example.com/contact', '_self')">Contact</p>`

Casually, the AMP Plugin cancel it, and I want to know if it has solution.

Thanks.

**Comment by westonruter** [comment]
You mean the AMP plugin strips out the `onclick` attribute? That's right, because AMP doesn't allow custom JavaScript (in the traditional way).

Why is this not rather just a normal link?

```html
<p><a href="https://www.example.com/contact">Contact</a></p>
```

**Comment by zJar84** [comment]
I know that an `a` tag can solve the problema, but I need do the same with the `onclick` attribute.

There isn't a solution?

**Comment by westonruter** [comment]
What is the reason for this code?

**Comment by zJar84** [comment]
I want to use it for some links on the footer (like the Contact link).

**Comment by westonruter** [comment]
But why? Are you trying to prevent crawlers from following those links? Then you should be using `rel=nofollow`.

**Comment by zJar84** [comment]
The `rel=nofollow` attribute consume PageRank, and the `onclick` is a solution for this. Crawlers doesn't follow the links and the web doesn't lose PageRank.

**Comment by westonruter** [comment]
Consumes PageRank? I don't understand. See:

> # How does Google handle nofollowed links?
> In general, we don't follow them. This means that Google does not transfer PageRank or anchor text across these links. Essentially, using `nofollow` causes us to drop the target links from our overall graph of the web. However, the target pages may still appear in our index if other sites link to them without using `nofollow`, or if the URLs are submitted to Google in a Sitemap. Also, it's important to note that other search engines may handle `nofollow` in slightly different ways.

https://support.google.com/webmasters/answer/96569?hl=en

**Comment by zJar84** [comment]
Gary Illyes and Eric Enge think different:

[Gary Illyes and Eric Enge](https://www.stonetemple.com/seo-tags-virtual-keynote-with-gary-illyes-and-eric-enge/)

**Comment by westonruter** [comment]
Well, if you must there is this method:

```html
<p role=button on="tap:AMP.navigateTo(url='https://www.example.com/contact')" tabindex=0>Contact</p>
```

But I consider this to be _highly_ dubious. I do no recommend this.
