### ISSUE TITLE
Page is behind the block navigation

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2403]
![Screen Shot 2019-05-23 at 8 35 30 PM](https://user-images.githubusercontent.com/3294597/58277611-6128a500-7d9a-11e9-8ab3-2066a46e3413.png)

Expected behavior: Page should be fully visible

**Comment by miina** [comment]
@swissspidy Are you also seeing this issue? Not sure which recent change might have influenced it.

**Comment by swissspidy** [comment]
So this looks different than in older versions?

Maybe #2383 changed something here.

**Comment by miina** [comment]
Yes, in older versions the block navigation didn't cover the active page. Right now the initial block's drag handle is covered by the block navigation so I have to rotate the block to see the drag handle and drag it. Is it different on your screen?

**Comment by swissspidy** [comment]
I see the same when I resize the window, but I don't remember exactly what it looked like on smaller screens in earlier version.

What did it look like before, was the box smaller, or just _behind_ the page (z-index regression)?

A quick improvement we could make is to change the `@media (min-width: 961px)` media query for the block navigation to something more like `@media (min-width: 1600px)` and show the block navigation in the toolbar when below that width.

At some point we have to improve the UI for smaller viewports anyway.

**Comment by miina** [comment]
The box definitely was not behind the page, so I guess that either the block navigation was smaller or it was more to the left side.

The page should be centered so I doubt that the page was more to the right.

It was something like this:
![Screen Shot 2019-05-24 at 2 21 38 PM](https://user-images.githubusercontent.com/3294597/58327214-4a805d80-7e2f-11e9-865c-8a95953291d5.png)

Seems to be approximately 70px difference.

It does seem like the text in the block navigation cuts of quite early considering the block navigation's width, so I guess it was smaller before?

**Comment by swissspidy** [comment]
> I guess that either the block navigation was smaller or it was more to the left side.

Ah, yes it was a bit more on the left side. #2383 changed that so it better aligns with the post title at the top.

I suppose we can fix some of the `calc()` in the CSS to account for the changed position.

> It does seem like the text in the block navigation cuts of quite early considering the block navigation's width, so I guess it was smaller before?

I don't think the width changed, it's still 300px max. That cut-off is more arbitrary than anything and not related to the element width.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create new story
2. Resize window
3. Verify that block navigation width decreases so that it never covers the current page (unless the window is super small)

**Comment by csossi** [comment]
drag handle can still be behind block navigation:
![image](https://user-images.githubusercontent.com/16945664/58504111-ea9ff480-8157-11e9-828e-6c7d73065051.png)

**Comment by miina** [comment]
@csossi The text block seems to be to the left from the Page, was it like this when you added it? It shouldn't be over the left edge by default.

Note that this issue covers the default position of the blocks, if the user moves the blocks behind the block navigation then yes, it goes behind.

Previously, by default, when adding a Page, the text block was already behind the block navigation. The goal of this issue was to fix it so that it wouldn't be behind the block navigation by default.

Please confirm if you moved the block behind the block navigation or if it was already over the left edge by default.

**Comment by swissspidy** [comment]
Regarding the drag handle, it's worth pointing out that it is likely going to be removed soon in favor of a better alternative, see #2275 / #2389. That shouldn't block this ticket here.

**Comment by csossi** [comment]
Ah, my mistake - thought a moved blocked would have its drag handle "on top" of the block navigation section - Sorry about that, @miina 

Verified in QA
