### ISSUE TITLE
Make story page bounding box line thinner

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2404]
Currently the line of the bounding box for story pages is a little too thick. Let's experiment making it thinner (i.e. 1 px or so).

<img width="418" alt="Screen Shot 2019-05-23 at 11 17 18 AM" src="https://user-images.githubusercontent.com/506089/58280320-2fd9b600-7d55-11e9-828b-330e66718a33.png">

**Comment by miina** [comment]
Note that this will also most likely influence the calculation of centering the active page.
