### ISSUE TITLE
[Feature Request] Gather insights on user journey: de-activation feedback

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2406]
Currently we have zero insights on the user journey following the download and activation of the plugin. The plugin should have the capability of asking a user for some simple yet effective feedback about why deactivating the plugin: intimidating error messages? too many errors? did not understand what the plugin does?

**Comment by swissspidy** [comment]
I remember MonsterInsights showing such a survey upon plugin deactivation. I always found it quite annoying, but perhaps it's indeed useful 🤷‍♂

**Comment by westonruter** [comment]
I likewise feel annoyed when plugins inject a feedback prompt when trying to deactivate.

**Comment by amedina** [comment]
We may need to devise a mechanism  that provides the insights needed while minimizing the annoyance levels.

**Comment by amedina** [comment]
Closing for now due to potential for annoyance. Will revisit after 2.0.
