### ISSUE TITLE
Consider adding resize handles to left and top edges of the blocks

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2410]
Once the block mover has been completely removed, dragging can be done by dragging the element itself, and there are no other handles, we could add a resize handle to every side.

Right now it's only possible to resize from the bottom and right size which is not the best user experience in case of rotated blocks.

**Comment by swissspidy** [comment]
Corners would be nice too in order to easily change both width and height.

**Comment by swissspidy** [comment]
Duplicate of #2985 which was fixed in 1.3.
