### ISSUE TITLE
Broken Top Toolbar On Small Screens

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2411]
* Content Structure and Block Navigation buttons are visible on smaller screens, but hidden on bigger screens. -> They should always be hidden.
* Shortcuts are stacked on top of each other on smaller screens.

Large Screen:
![Screenshot 2019-05-24 at 14 19 03](https://user-images.githubusercontent.com/841956/58327205-43594f80-7e2f-11e9-9de8-11531f50d544.png)

Small Screen:
![Screenshot 2019-05-24 at 14 19 32](https://user-images.githubusercontent.com/841956/58327178-350b3380-7e2f-11e9-9e25-d0b2325af659.png)

Thought: Maybe we can display our custom block navigation in the top toolbar  when there's not enough space.

Related: #2403, #2401, #2523

**Comment by swissspidy** [comment]
@csossi Could you please verify that the toolbar on a small screen doesn't look like in the screenshot above? Instead it should look like the one in #2654.

**Comment by csossi** [comment]
Verified in QA
