### ISSUE TITLE
Make amp-timeago block dynamic

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2413]
The `amp-timeago` block saves some formatted and localized markup in the database:

https://github.com/ampproject/amp-wp/blob/8f23abc05c5deb65b4944a0fccb3ffa63324d563/assets/src/block-editor/blocks/amp-timeago/index.js#L157-L159

This leads to block validation errors when a user with a different profile language than the original editor tries to edit a post, or when changing the site language at some point.

To prevent this, the attributes could be saved in the block's comment delimiter (instead of being sourced from the HTML attributes) and just use `save() { return null; }`.

Then, a PHP `render_callback` would be responsible for printing the `<amp-timeago>` component.

In theory that callback could also use `human_time_diff()` to make the block available in both versions when using Transitional mode.

**Comment by westonruter** [comment]
In #4556 I suggest deprecating this block, in favor of this timeago functionality being exposed in a plugin dedicated for that purpose.
