### ISSUE TITLE
requirs necessary featured image of 1200 by 1600 pixels

### ISSUE THREAD

**Issue by Amanrazdan** [ampproject/amp-wp#2421]
when creating a new story when we add featured image it says at least 1200 by 1600 pixels of image size is required but that's too much of size. No file I found actually help change 

![image](https://user-images.githubusercontent.com/28403318/58369804-52b6c680-7f1d-11e9-83de-a920e3c5b41f.png)

help fix this

**Comment by westonruter** [comment]
To confirm, you are testing 1.2-beta1?

The image size requirement is intentional. In order for the various image sizes to be generated for the AMP story poster image and Schema.org metadata image, an image with these minimum dimensions. The solution would be for you to upload a larger image.

For a lot more information about this, see: https://github.com/ampproject/amp-wp/pull/2038#issuecomment-482429194

I can't think of a better alternative than to prevent selecting images that are too small.

**Comment by Amanrazdan** [comment]
this increases the image size a lot and the platform takes time to load. Where can I change this to upload a low quality image

**Comment by Amanrazdan** [comment]
also would like to ask if we are allowed to upload modified version of the plugin to the wordpress plugin directory and maintain the updates as they come from your end. 

or
 submit those features here

**Comment by westonruter** [comment]
Google Search requires images to be of this size. If you don't upload large images then you'll get warnings from Google Search Console and your content may not be able to appear in all search contexts (e.g. carousel). See https://github.com/ampproject/amp-wp/issues/1812

I do not recommend forking the plugin. You certainly are allowed under the terms of the GPL, but it would mean a lot of extra work for you and it would dillute the AMP plugin options.

What is better is to identify clear use cases for how the plugin can be configured for your needs. 

Uploading a large image does not mean this large image is served to your site visitors. The large, medium, and thumbnail sizes should be automatically generated for you and used in the content.

**Comment by Amanrazdan** [comment]
thanks

**Comment by Amanrazdan** [comment]
what if we don't want to index it on google search and just want the featured image for the post thumbnail. Is there any way to do that and set the featured image with any size

**Comment by Amanrazdan** [comment]
Are you there

**Comment by westonruter** [comment]
@swissspidy What do you think of removing the disabling of the Media Library Select button:

https://github.com/ampproject/amp-wp/blob/0e922372dd9084a727800401fcaff646963d2d64/assets/src/components/featured-image-select-media-frame.js#L88-L94

The result is the user will allowed to select an image that is too small, but there will still be this warning in the media modal:

> ![image](https://user-images.githubusercontent.com/134745/58581632-e1209600-8204-11e9-95c4-da3d59a67745.png)

And upon selection, there will still be this warning:

> ![image](https://user-images.githubusercontent.com/134745/58581584-b9c9c900-8204-11e9-998e-127c4e7e8072.png)

**Comment by westonruter** [comment]
@Amanrazdan does #2490 satisfy your requirements?
