### ISSUE TITLE
Add additional templates to have 10 in total

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2426]
AC: There are 5 Travel and 5 Fandom templates which can be inserted from the Template Inserter.

Add the following templates:
- Vertical (Travel) template -- this already has a .html file ready but it needs updating and adding to the import list.
- 5 templates for Fandom

See the templates here: https://projects.invisionapp.com/d/main#/projects/prototypes/17106855

**Comment by ThierryA** [comment]
> 5 templates for Fandom

I suggest to implement the following from [this list](https://projects.invisionapp.com/d/main#/projects/prototypes/17106855):
- Fandom-GoT-01
- Fandom-GoT-02
- Fandom-GoT-05
- Fandom-GoT-06
- Fandom-GoT-14

@amedina WDYT?

**Comment by miina** [comment]
Actually, just realized that we might want to wait until #2472 is fixed to update the `fandom-cta` template before merging.

**Comment by swissspidy** [comment]
Move this back to `In progress` because of the images.

@dawidmlynarz As discussed on Slack, can you try to find something on Unsplash for the following templates?

* Fandom-GoT-01
* Fandom-GoT-02
* Fandom-GoT-05
* Fandom-GoT-06
* Fandom-GoT-14

**Comment by miina** [comment]
@swissspidy Could you give it another look? The assets are updated now based on the new ones that Dawid found.

**Comment by swissspidy** [comment]
I think the templates need some updating. Waiting for #2535 and/or #2484 to get merged before assigning for QA.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Hope you had a great week. Could you please test this?

1. Create a new story
2. Click the 'Template inserter' to add a new page:
<img width="1007" alt="click-templates" src="https://user-images.githubusercontent.com/4063887/59133659-547d8280-893e-11e9-8648-45b192118a16.png">

3. Expected: the previous 'Travel' and new 'Fandom' templates shouldn't have obvious display issues, like block validation issues
4. Click a template to create a page with it
5. Expected: the page should have the same text as the template, but not the image(s):
<img width="1085" alt="template-here" src="https://user-images.githubusercontent.com/4063887/59133781-b0480b80-893e-11e9-8615-3a38d2d87fec.png">
6. Repeat steps 4 and 5 for all 10 of the templates

Thanks, Claudio!

**Comment by csossi** [comment]
Verified in QA
