### ISSUE TITLE
Onboarding Wizard to get started with the AMP Stories editor

### ISSUE THREAD

**Issue by cathibosco** [ampproject/amp-wp#2427]
On-boarding/Off-boarding
Some items to include in the Getting Started wizard (or minimal settings page) might be: 

- size of media (background images etc)

- optimization of media

- video integration and optimization recommendations

- text readability recommendations 

- animation options/suggestions 

- desktop view options

- links to documentation

**Comment by cathibosco** [comment]
A checklist or wizard like this on the dashboard might help new AMPStory editors be more successful when they are just getting started and reduce some friction. 

Also, a similar formatted wizard or optional “Provide feedback” interaction could be used when editors remove the plugin or make it inactive. Let me to link that issue...

**Comment by swissspidy** [comment]
Thanks for sharing your thoughts!

Some more documentation definitely cannot hurt. I think for an initial version we should not overthink this, but have some minimal guidance in place instead. For example, I like the [onboarding in Gutenberg with the tips and guides](https://github.com/WordPress/gutenberg/tree/master/packages/nux). Most written documentation should probably live on the website, as it's way easier to update.

----

See also #2332 for media optimization.

**Comment by cathibosco** [comment]
Thinking out loud a bit... 
It is nice to have a minimal few things up front when you are in NUX mode... Gutenberg tool tips and guides are very useful and not too disruptive. 
When creating visual stories one of the first things I want to know is what is the optimal size for my background images for mobile and for desktop enabled use. Editors want their images to look great (and obviously perform well). 

Next thing editors might need are the links to the rest of the documentation. So it is possible a settings page would be enough with an outline a few details and links to the major documentation topics.

Its nice to have it handy in the dashboard - does not have to be a wizard of course. :) 

Thanks for thinking it through with me @swissspidy
