### ISSUE TITLE
How to index AMP pages and get AMP on the homepage

### ISSUE THREAD

**Issue by zJar84** [ampproject/amp-wp#2436]
Hello, I have the AMP on lector mode and I want know how to have an AMP version of my homepage on [https://significadodelosgirasoles.ovh](https://significadodelosgirasoles.ovh). It can be possible? And how?

And, with the Google Search Console, I must put on the inspection tool the AMP's url? Or is better put just the original one?

Thanks.

**Comment by westonruter** [comment]
> Hello, I have the AMP on lector mode and I want know how to have an AMP version of my homepage on https://significadodelosgirasoles.ovh. It can be possible? And how?

In Lector/Reader mode, this is only possible if you have your homepage set as a static page. You can opt-in to AMP for the homepage by editing the page's settings to “Enable AMP”. This won't work for when you have the latest posts shown on the homepage.

> And, with the Google Search Console, I must put on the inspection tool the AMP's url? Or is better put just the original one?

If you are in Reader/Transitional mode, then you'd put the non-AMP URL I believe. If you put the AMP version, then you'd see this message:

![image](https://user-images.githubusercontent.com/134745/58432525-ab927600-8067-11e9-943f-c32a9c7eaf70.png)

On the other hand, if I supply the non-AMP version that links to the AMP version, then I see:

![image](https://user-images.githubusercontent.com/134745/58432550-c533bd80-8067-11e9-9c42-9c4c69b109bd.png)
