### ISSUE TITLE
Tablets are in to the effects of AMP?

### ISSUE THREAD

**Issue by zJar84** [ampproject/amp-wp#2438]
The google results that has AMP, on tablets devices, appears on AMP?

Thanks.

**Comment by westonruter** [comment]
Not currently. See https://support.google.com/webmasters/answer/6340290?hl=en

> **Why aren’t my AMP-specific features appearing on tablet or desktop?**
>
> AMP-specific features on Google, such as the Top Stories carousel, are currently available only on mobile. Although AMP itself works on all device types, including desktop, there are currently no plans to expand AMP-specific features to non-mobile platforms.

**Comment by westonruter** [comment]
My hope is that Native mode sites will be shown as AMP results in tablet and desktop in the future. For paired AMP (Reader and Transitional modes), it would not make sense to show them in desktop/tablet because they are often optimized for mobile screens.
