### ISSUE TITLE
Consider adding taxonomies for hierarchical categorization in AMP Stories

### ISSUE THREAD

**Issue by cathibosco** [ampproject/amp-wp#2439]
It would be very useful to organize and present Stories based on their taxonomy or category. WordPress users are expecting to being able to organize, consume, and present content according to category hierarchies - taxonomies. 

Recipes for example ...organized by Vegetarian, Paleo, Italian, Vegan, Gluten-free...

**Comment by swissspidy** [comment]
Thanks for your input!

Adding a taxonomy sounds like a reasonable enhancement for Stories.

Having both tags and categories for posts has always been confusing for WordPress users, so perhaps we should only add one taxonomy, not two. Plugins could always extend this.

**Comment by cathibosco** [comment]
Yes, adding the categories taxonomy is foundational / fundamentally useful and great to have plugins extend beyond.

**Comment by westonruter** [comment]
Why not just add the Category and Tag taxonomies? Seems like a user should be able to organize stories in the same way as posts.

**Comment by swissspidy** [comment]
I suppose we can do that and see how it goes.

**Comment by Amanrazdan** [comment]
Bravo...I would love seeing this happen

**Comment by westonruter** [comment]
See #2469.

**Comment by amedina** [comment]
Thanks for your input Cathi; keep'em coming! :)

Em ter, 28 de mai de 2019 às 03:14, Cathi Bosco <notifications@github.com>
escreveu:
