### ISSUE TITLE
Reordering styling is broken

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2445]
Reordering styling is displaying texts in incorrect size.

Steps to reproduce:
- Add a few pages with texts.
- Reorder.

![Screen Shot 2019-05-28 at 3 03 26 PM](https://user-images.githubusercontent.com/3294597/58480043-c80edb00-8159-11e9-8a12-193b054d02d9.png)

**Comment by miina** [comment]
Instructions for testing:
- Add a few Pages
- Add Text blocks on the Pages.
- Try to reorder
- Verify that the texts are in appropriate size considering the reduced size of pages in reordering mode. Please see the description of the ticket as a reference to see the screenshot of the original issue.

**Comment by csossi** [comment]
Verified in QA
Example

Before reordering:
![image](https://user-images.githubusercontent.com/16945664/58660429-697d6480-82f3-11e9-9988-edb80cea2205.png)

After reordering:
![image](https://user-images.githubusercontent.com/16945664/58660477-84e86f80-82f3-11e9-95f1-83a7b6777584.png)
