### ISSUE TITLE
Stacking up browsing history when new amp story is opened from bookend!

### ISSUE THREAD

**Issue by dhruva205** [ampproject/amp-wp#2453]
Opening up a **new story** from the **amp-stories bookend** adds up a new  URL in the browsing history (previous story URL and now new story URL in the browsing history) .
User going through multiple stories will lead to a long history generation in the browser , so at this point if user click back button(browser or other physical back button) he/she will go through all those stories again..

The current bookend works this way..
Code Sample
` <amp-story-bookend layout=nodisplay>
        <script type="application/json">
            {
                "bookendVersion": "v1.0",
                "shareProviders": ...
                "components": [
                    {
                        "type": "heading",
                        "text": "More to read"
                    },
                    {
                        "type": "small",
                        "title": "This is India an the best places you should go",
                        "url": "http://localhost/app/posts/p10/",
                        "image": "http://placehold.it/256x128"
                    }
                ]
            }
        </script>
    </amp-story-bookend>`

When clicking the bookend component, it will load the URL specified in it.
If i do not mention the "url" tag , the component don't show up in the bookend.
I need something like to execute location.replace(url) or if we can specify the id tag in components to run a script on event click listener of the "id" along with giving tag of "no url" which will specify that the url is not required for this component..

**Comment by westonruter** [comment]
@dhruva205 Thank you for the report. 

Could you actually please report this upstream to AMP itself? https://github.com/ampproject/amphtml/issues?q=is%3Aopen+is%3Aissue+label%3A%22Category%3A+AMP+Story%22

As I understand, this is out of scope for the AMP plugin. The `amp-story-bookend` component is part of AMP, not the AMP plugin.
