### ISSUE TITLE
Text blocks not considering the set width and height

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2456]
Steps to reproduce:
- Add a Text (or title) block.
- Add background color (for visibility).
- Make the block long and narrow.
- Save, see the FE result.

Note: this is for amp-fit-text only.

Editor:
![Screen Shot 2019-05-29 at 1 08 19 PM](https://user-images.githubusercontent.com/3294597/58552639-319ef000-8213-11e9-8d87-113eff4b010e.png)

FE:
![Screen Shot 2019-05-29 at 1 08 23 PM](https://user-images.githubusercontent.com/3294597/58552644-35327700-8213-11e9-9262-7b448a14df9d.png)

**Comment by miina** [comment]
Instructions for testing:
- Create a text block
- Make it quite narrow.
- Save and see the result in the front-end
- Verify that the width and height are similar in the editor and in the FE

Please refer to the screenshot from the description to see the original issue.

**Comment by csossi** [comment]
Verified in QA

Example
Editor:
![image](https://user-images.githubusercontent.com/16945664/58635143-1be50580-82bb-11e9-9631-4b306c13427a.png)

Preview:
![image](https://user-images.githubusercontent.com/16945664/58635167-2bfce500-82bb-11e9-9f8c-2ccb3ba37b72.png)

**Comment by csossi** [comment]
Slight diff in line breaks here

Editor:
![image](https://user-images.githubusercontent.com/16945664/58635301-8ac25e80-82bb-11e9-986d-799f2b33a413.png)

Preview:
![image](https://user-images.githubusercontent.com/16945664/58635339-a3cb0f80-82bb-11e9-91a1-d874efbbe298.png)

**Comment by miina** [comment]
Thank you, Claudio. This should be expected due to responsiveness. It seems that the font weight differs though. Will test and possibly create a separate issue for this.
