### ISSUE TITLE
Integrate with block-based widgets management UI

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2465]
Gutenberg 5.8 contains an early beta of the new block-base widget management UI.

To test it, install Gutenberg 5.8 and head over to Gutenberg -> Widgets (Beta) in your WordPress admin.

It would be good to include AMP blocks and AMP validation errors there. Depending on the mode of course.

**Comment by westonruter** [comment]
Given that widgets are going away, I don't think this is a priority.
