### ISSUE TITLE
Demo Working Export Feature

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2467]
As a user, through a demo, I want to ensure that the new created export feature works as intended.

**Comment by swissspidy** [comment]
Perhaps we can even add a E2E test that verifies the file download part.

See https://github.com/GoogleChrome/puppeteer/issues/299

**Comment by swissspidy** [comment]
Opened #2898 specifically for adding E2E tests.

**Comment by swissspidy** [comment]
Closing in favor of #2898.

We extensively tested this in QA already, and E2E tests will further help verify functionality of this feature.
