### ISSUE TITLE
Consider keeping rotation for the skeleton template

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2471]
AC: Rotation is kept after inserting a template.
AC: `travel-vertical` template is available under Template Inserter.

If rotation is not kept then there is a significant difference in the looks of the template and the skeleton template.

![Screen Shot 2019-05-30 at 2 49 12 PM](https://user-images.githubusercontent.com/3294597/58633945-44382880-82ea-11e9-92ca-490d8120199e.png)

![Screen Shot 2019-05-30 at 2 49 37 PM](https://user-images.githubusercontent.com/3294597/58633956-47331900-82ea-11e9-842a-fdbbfd5f64b7.png)

**Comment by miina** [comment]
@amedina @swissspidy @ThierryA Let me know your thoughts on this one -- should we keep the rotation in the skeleton templates or not.

**Comment by swissspidy** [comment]
Definitely should be kept IMO

**Comment by amedina** [comment]
Agree. If a rotation is present it would be an essential part of the template. +1 for keeping it.

**Comment by ThierryA** [comment]
Strong :+1: to keep rotation upon templates insertion.

**Comment by miina** [comment]
Sounds good, I've added AC-s for the issue.

**Comment by miina** [comment]
Testing instructions:
- Verify that "vertical" template with rotated text blocks appears in the Template Inserter.
- Verify that the rotation is kept after inserting.

**Comment by csossi** [comment]
Verified in QA
