### ISSUE TITLE
CTA block's button missing color settings

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2472]
To reproduce:
- Add CTA block
- Try to change the background color and text color.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create a new story with at least 2 pages
2. On any page that is not the first one in the story, add a new CTA block.
3. Verify that the CTA block has colors by default.
4. Verify that the color and opacity can be customized freely

**Comment by csossi** [comment]
Verified in QA
