### ISSUE TITLE
Font weight for title is 600 in the editor but 700 in the FE

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2473]
To reproduce:

- Add a title
- Add a title block
- See the font weight in the editor
- See the font weight in the FE.

![Screen Shot 2019-05-30 at 7 25 45 PM](https://user-images.githubusercontent.com/3294597/58651198-ebc85180-8310-11e9-9323-151df34e11c2.png)
![Screen Shot 2019-05-30 at 7 25 05 PM](https://user-images.githubusercontent.com/3294597/58651199-ebc85180-8310-11e9-8337-3207f7411daf.png)

**Comment by miina** [comment]
Testing instructions:
- Add Story Title block
- Verify that the font weight is similar in the editor and in the FE.

**Comment by csossi** [comment]
Verified in QA
