### ISSUE TITLE
Consider Side-by-Side in desktop and Side-over-Side in mobile

### ISSUE THREAD

**Issue by cathibosco** [ampproject/amp-wp#2482]
Review the Washington Post amp-story version. Their template better handles the side-by-side in desktop and side-over-side in mobile. This is an issue we are facing while editing our stories to work on both mobile and desktop. 
Their solution is excellent. 
Here is an example - beautiful and useful! 
https://www.washingtonpost.com/graphics/2018/lifestyle/amp-stories/william-ferris-and-the-voices-of-southern-folklore/

My work around that is failing... https://cathibosco.com/stories/spring-in-kyoto/

Almost all WordPress use cases would really benefit if this worked similarly with the WordPress  plugin. We can create useful templates based on a setup like this possibly.

**Comment by westonruter** [comment]
I believe this will require having totally separate layout for landscape vs portrait.

This is part of #2409.
