### ISSUE TITLE
Provide user opt-in for automatic updates

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2487]
WordPress by default only auto-updates core patch versions. Plugins can also opt-in to automatic updates via:

```php
add_filter(
    'auto_update_plugin',
    function ( $update, $item ) {
        if ( in_array( $item->slug, [ 'amp' ], true ) ) {
            $update = true;
        }
        return $update;
    },
    10,
    2
);
```

However, doing this by default could be a violation of user expectations, since plugins normally only auto-update if the site owner has configured them to do so.

We could however provide a way for the user to opt-in to automatic updates. For example:

![image](https://user-images.githubusercontent.com/134745/58726290-3809a500-8396-11e9-8473-534a65b3f7dd.png)

Upon activation there could be an admin notice encouraging auto-updates to be enabled.
amending the default “Plugin activated.” message:

![image](https://user-images.githubusercontent.com/134745/58726310-43f56700-8396-11e9-983f-6aa3ad9f32eb.png)

Nevertheless, this could be a short-lived feature since auto-updating plugins is one of the 9 projects for 2019: https://make.wordpress.org/core/2018/12/08/9-priorities-for-2019/

**Comment by igrigorik** [comment]
I would like to suggest the opposite: enable automatic updates by default and provide an opt-out. We can provide an explicit notification when this is first enabled, that site owners can dismiss or go to disable this feature if they want to. 

There is no reason why enabling this policy should block on wider WP rollout of automatic updates. To the contrary, that rollout will be gated on informed experience which the community lacks today, and we can start that journey by taking these baby steps. In the spirit of AMP... baking in best practices and guardrails that lead site owners to the right outcomes.

**Comment by westonruter** [comment]
In contrast to core, the biggest problem with plugin auto-updates at the moment is that users are much more likely to have hacked plugin files. There is the "Plugin Editor" in WordPress that allows for this, even though it warns the user against it. (And there is no warning when users have modified and updated files via Git/FTP.) For them, auto-updates can mean losing changes, especially if they are counting updates always being manual.

Given that automatic updates for themes and plugins is already on the radar this year (as part of Matt's [9 Projects for 2019](https://make.wordpress.org/core/2018/12/08/9-priorities-for-2019/)), I think we should support that effort instead. If the whole ecosystem is transitioned to automatic updates for themes/plugins, then there will be a much wider impact, and we won't risk potential blowback for rolling it out for the AMP plugin prematurely.

**Comment by amedina** [comment]
>In contrast to core, the biggest problem with plugin auto-updates at the moment is that users are much more likely to have modified plugin files. 

That is an important point @westonruter. It is likely that such a case would not correspond to the majority. Could a mitigating approach be for the update process to check if files have been modified and warn the user if that's the case? That would be equivalent to the user triggering the update herself. 

>Given that automatic updates for themes and plugins is already on the radar this year (as part of Matt's 9 Projects for 2019), I think we should support that effort instead. 

That is a good possibility. Although, being in Matt's radar means that the issue has been recognized and accepted as of paramount  importance for the ecosystem. It seems taking the lead with our plugin would be both beneficial to users and in line with the direction of the ecosystem.

**Comment by westonruter** [comment]
> It is likely that such a case would not correspond to the majority.

I'm not so sure. It came up again today, as a matter of fact: https://wordpress.org/support/topic/getting-large-no-of-404s-when-amp-is-integrated-on-pages/#post-11601128

> Could a mitigating approach be for the update process to check if files have been modified and warn the user if that's the case?

Potentially. We could generate MD5 checksums of each template file and distribute these with the plugin to check against runtime re-computations of the template files to determine whether or not they were modified. But this is somewhat re-inventing the wheel, as WP-CLI has [`wp plugin verify-checksums`](https://developer.wordpress.org/cli/commands/plugin/verify-checksums/) and I'd assume that this same logic would be essential for incorporating into any auto-update logic that goes into core.

**Comment by amedina** [comment]
A couple of extra points:

- Following an opt-out approach comes with a sound communication strategy: it should be crystal clear to users what is happening, and they will have the option to opt out.
- An opt out approach may initially be misaligned with user expectations, but that is going to happen now or later as the ecosystem moves in the right direction. It is a challenge we face by introducing key changes to the ecosystem. It is a factor that needs to be accounted for, but we need to be prepared in some cases to challenge expectations in areas crucial to the success of the ecosystem.

**Comment by westonruter** [comment]
But if the change is going to happen for the ecosystem as a whole this year anyway, then there is no need to jump the gun.

**Comment by amedina** [comment]
What is the status of that 2019 project? Is there consensus? Is happening? What is the approach proposed?

**Comment by amedina** [comment]
We need to agree (or not) about what is the right thing to do in terms of user benefits and the health of the ecosystem. Waiting for things that are arguably urgent makes no sense, especially when there are no fundamental technical limitations to achieve the best approach.

**Comment by westonruter** [comment]
> What is the status of that 2019 project? Is there consensus? Is happening? What is the approach proposed?

That's what the next step should be. We're debating something we don't have data about yet 😄

**Comment by westonruter** [comment]
See also conversation in the WordPress Slack `#pluginreview` channel that @felixarntz started: https://wordpress.slack.com/archives/C1LBM36LC/p1559287145034000

@Clorith mentioned he thought that @pento was looking at this, but he is at the moment on a much-needed vacation.

**Comment by igrigorik** [comment]
I think we can boil this down to... A safe auto update mechanism requires:

1. Integrity checking to verify that it won't blow out customizations
1. Plugins+theme developers to deliver backwards compatible updates
1. Site owners to have confidence (and per plugin opt-outs) in 1 and 2

It is true that (1) would be, ideally, handled by WP core. However, implementing a simple checksum on a set of known files within a plugin is not rocket science, and something we could easily add today and replace once core capability is available. Besides, can't we just lift some of the code from WP CLI? Blocking on core to solve this is entirely unnecessary and only delays what ought to have been the WP default for another year+, unless we can say with certainty that it's shipping in an upcoming release.

---

> See also conversation in the WordPress Slack `#pluginreview` channel that @felixarntz started: https://wordpress.slack.com/archives/C1LBM36LC/p1559287145034000

Tangent: it's really unfortunate that all of the WP core discussions are behind a login prompt and can't be indexed or searched for on the web; it makes it impossible to meaningfully link to or engage with these discussions.

**Comment by westonruter** [comment]
The theme/plugin auto-updates feature is underway in core: https://make.wordpress.org/core/tag/auto-update/

On GitHub: https://github.com/audrasjb/wp-autoupdates

This being the case, I don't think there's anything special we need to do in the AMP plugin.

**Comment by westonruter** [comment]
Some lessons from enabling auto-updates by default: https://wptavern.com/all-in-one-seo-plugin-turns-on-automatic-updates-without-notifying-users-removes-functionality-in-latest-release

**Comment by westonruter** [comment]
Also: [Reminder: Plugins Must Not Interfere with Updates](https://make.wordpress.org/plugins/2021/01/26/reminder-plugins-must-not-interfere-with-updates/).
