### ISSUE TITLE
Phase out “Native” terminology in favor of “AMP-first”

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2507]
The AMP settings screen describes the three modes: Reader, Transitional, and Native.

![image](https://user-images.githubusercontent.com/134745/58920205-f35b7200-86e5-11e9-993a-6717d4bf3dad.png)

Originally Reader was called “Classic” and Transitional was called “Paired”, but these were renamed in #2034. The “Native” name was not changed, however. While it used to be called “canonical AMP” it is now termed “AMP first” as referenced in [AMP as your web framework](https://blog.amp.dev/2019/05/01/amp-as-your-web-framework/). While the Native mode description does reference AMP-first, the mode itself is not termed that yet.  This should change.

Changing the mode name may need to be done as part of a redesign of the whole screen, as with #1288. This especially true as we hope to be able to default sites to AMP-first in the future (as opposed to Reader mode), per #1384.

**Comment by amedina** [comment]
A proposal for the naming, as discussed with @pbakaus, is the following:

- AMP
- Transitional
- Reader

The idea is that AMP-first is really just AMP, and the AMP-first name is as confusing, or more, than Native AMP.

**Comment by pbakaus** [comment]
My $0.02: Since this is a unique scenario where the ability to run AMP for the whole site appears directly in a list next to two other modes, my vote as per @amedina  would be to call it just "AMP", or otherwise something like:

- Default
- Transitional
- Reader

or

- Complete
- Transitional
- Reader

or

- Full
- Transitional
- Reader

or

- Standard
- Transitional
- Reader

**Comment by westonruter** [comment]
I think simply “AMP” is still insufficient because the other modes are also AMP, and even in “AMP” mode you can opt-out for specific posts/pages or for entire templates (e.g. homepage or shopping cart).

“Full” and “Complete” wouldn't work for the same reason, because you can conditionally opt-out of AMP.

“Default” is better, but it isn't the default now (as Reader is), so that could be confusing, at least until #1384.

“Standard” I think I like the most of all these.

**Comment by amedina** [comment]
I am leaning to just align with the overall trend and switch from "Native" .to "AMP-first".

It seems no matter what choice we make it will have drawbacks. Better err on the side of consistency then.

**Comment by westonruter** [comment]
I like “Standard” though because it implies that the site is using AMP primarily, but there are exceptions, such as when there is opt-out at post or template level.

**Comment by amedina** [comment]
I see the semantic benefit of "Standard"; I hesitate because the meaning of "standard" is overloaded.

To follow up on your point, perhaps "Default AMP" would capture the goal of outputting AMP by default and allowing for exceptions. 

Would you consider a good alternative to "Standard AMP"?

**Comment by westonruter** [comment]
“Default” is ok, but the default mode now is Reader mode. So users would be confused thinking that Default means Reader, at least until #1384. While overloaded, I still like “Standard” more than these other options.

**Comment by amedina** [comment]
Makes sense. In lieu of "Native AMP", I'd vote for "Standard AMP" as well.

**Comment by pbakaus** [comment]
Can we just do:

> Standard (AMP-First)

?

**Comment by westonruter** [comment]
Along with:

> Transitional (Paired AMP)

?

**Comment by pbakaus** [comment]
Works for me!

**Comment by amedina** [comment]
If we are going to include `AMP First` why do we need `Standard`? Similarly, why adding back the `Paired` terminology we decided before to avoid?

It seems to me we are regressing.

**Comment by westonruter** [comment]
> If we are going to include `AMP First` why do we need `Standard`? Similarly, why adding back the `Paired` terminology we decided before to avoid?

I don't think we were trying to avoid the “Paired” terminology. Mentioning “paired” with the mode explains what _kind_ of AMP it is. We do mention “paired” in the description already:

> ![image](https://user-images.githubusercontent.com/134745/59152000-fa89c500-89f0-11e9-830c-2c26d60bca9c.png)

Part of the problem comes down to it being redundant to say “AMP” in the modes, because they are all AMP. It's the AMP settings screen. If one mode has AMP in the name, then shouldn't they all? Does “AMP First” make sense when contrasted alongside “Transitional” and “Reader”?

If we have “AMP First” appearing after “Standard” then this explains what _kind_ of AMP it is. It's not Paired AMP, it's AMP First.

So what about:

* Standard (AMP First)
* Transitional (Paired AMP)
* Reader (Paired AMP)

**Comment by amedina** [comment]
We are moving away from `Paired`.

**Comment by amedina** [comment]
Thinking this more through. I think we can go with either @westonruter suggestion of:
>Standard (AMP First)
Transitional (Paired AMP)
Reader (Paired AMP)

Or with simply with @pbakaus suggestion: 
Standard
Transitional
Reader

@pbakaus WDYT?

**Comment by westonruter** [comment]
The latter is less wordy, and the AMP scheme can be indicated in the description.

**Comment by pbakaus** [comment]
second (less wordy) one works for me! Let's do it.
