### ISSUE TITLE
Story not working on duplicate action

### ISSUE THREAD

**Issue by Amanrazdan** [ampproject/amp-wp#2510]
It has been observed that whenever we use block duplicate action and then publish the story, the story doesn't work and shows something like this
![image](https://user-images.githubusercontent.com/28403318/58931887-0ff7b880-877f-11e9-99f5-e8938cc44742.png)

This problem is still persisting with beta 2. Turns out when pages are duplicated they also **duplicate the story page ID** which turns amp story engine to play weirdly and then we can not move around at all. I don't if the pageID is the actual reason to this but this really doesn't let us use duplicate action at all

**Comment by westonruter** [comment]
I was able to _duplicate_ this issue:

https://story-test-wordpress-amp.pantheonsite.io/stories/try-duplicate/

![image](https://user-images.githubusercontent.com/134745/59010614-b88d3300-87e6-11e9-9752-825b99bd62cd.png)

Steps to duplicate:

1. Start story.
2. Populate text block.
3. Duplicate page.
4. Preview

**Comment by kienstra** [comment]
Thanks, I'll work on this today (Thursday).

**Comment by swissspidy** [comment]
Cool. Should be as simple as going trough all blocks on `subscribe()` and updating the anchor attribute when it doesn't match the client ID / when it exists twice.

**Comment by kienstra** [comment]
**Testing Steps**
*(Refer to Weston's)*

To test this, please refer to @westonruter's [great steps above](https://github.com/ampproject/amp-wp/issues/2510#issuecomment-499361632). The front-end shouldn't look [like this](https://github.com/ampproject/amp-wp/issues/2510#issue-452318481).

**Comment by csossi** [comment]
Verified in QA:
![image](https://user-images.githubusercontent.com/16945664/59129360-9b697900-893a-11e9-9487-b60291b290bc.png)
