### ISSUE TITLE
Form submitting, no notification

### ISSUE THREAD

**Issue by paulkirspuu** [ampproject/amp-wp#2511]
Hello

My Gravity Forms AMP form is submitting fine, but it gives no indication to the user. Had there been a class added to form element, I could add couple of extra fields to form and display these with css rules when success / error classes happen.

Is this a known problem, do you have a fix for it?

**Comment by swissspidy** [comment]
Hi there!

Which version of the AMP plugin are you using? Are you using any compatibility plugin to make Gravity Forms AMP compatible or did you build something yourself?

**Comment by westonruter** [comment]
@paulkirspuu Please test with 1.2-beta2, if you haven't already: https://github.com/ampproject/amp-wp/releases/tag/1.2-beta2

And then refer to this article on how form submissions are handled by the plugin: https://amp-wp.org/documentation/playbooks/handling-form-submissions/

I believe these with answer your questions, but if not, please let us know.

**Comment by westonruter** [comment]
The easiest way to ensure a form is compatible with AMP is to configure it to redirect to a success page. 

But I recall this may not work as expected with Gravity Forms as it may not use the `wp_redirect()` function. 

You may also need some plugin code like this: https://gist.github.com/westonruter/b2554073461707a88057bb86b6b603d6

**Comment by paulkirspuu** [comment]
Sending success / error messages with `wp_send_json()` via Gravity Forms hooks did it. Thanks!
