### ISSUE TITLE
nav menu which overlays toggle so cant close it

### ISSUE THREAD

**Issue by craig-stanfield** [ampproject/amp-wp#2512]
I have a scenario on a website (https://www.retailassociates.co.uk/blog/company-news/retail-associates-announce-the-launch-of-paypod/) where when the user clicks the hamburger menu the menu shows with an x in the corner to close the menu. the usual toggle button (hamburger button) is below the off-canvas menu. The live site is using 0.7.2 but in non amp view you'll be able to see how it functions.

Any idea how to make this x close the menu? i tried adding the toggle class to the X button but didn’t work, clicking outside the menu also wont close it. The code below is my local code using v1.1.3

There is no issue opening the menu and if i hide the menu and click the hamburger it resets as it should. Whats needed is a way I can click the x in the top left of the menu to close the menu

This is in my functions file
```php
/**
 * AMP Theme Support and nav menu
 */
add_theme_support(
    'amp',
    array(
        'nav_menu_toggle'   => array(
            'nav_container_id'           => 'offCanvas',
            'nav_container_toggle_class' => 'is-open',
            'menu_button_id'             => 'menu-toggle',
            'menu_button_toggle_class'   => 'active',
        ),
        'paired'            => true,
    )
);
```
this is in my top-menu file
```php
<div class="mobile-toggle small-2 medium-1 hide-for-large cell">
    <a type="button" id="menu-toggle" class="menu-toggle" data-toggle="offCanvas">
        <img src="<?php echo get_stylesheet_directory_uri() . '/dist/images/menu-hamburger.svg' ?>" alt="<?php _e('Open Menu'); ?>"> <br>Menu
    </a>
</div>
```
my off-canvas section contains
```php
<button class="close-button active" aria-label="Close menu" type="button" data-close>
    <span aria-hidden="true">&times;</span>
</button>
<br>
<div class="is-drilldown" style="min-height: 627px; max-width: 306px;">
<?php wp_nav_menu( array(
  'theme_location'  => 'main_menu',
  'menu'            => '',
  'container'       => '',
  'container_class' => '',
  'container_id'    => '',
  'menu_class'      => 'mobile-menu',
  'menu_id'         => '',
  'echo'            => true,
  'fallback_cb'     => 'wp_page_menu',
  'before'          => '',
  'after'           => '',
  'link_before'     => '',
  'link_after'      => '',
  'items_wrap'      => '<ul id = "%1$s" class = "%2$s vertical menu drilldown" data-drilldown data-parent-link="true">%3$s</ul>',
  'depth'           => 0,
  'walker'          => new gs_walker_drilldown,
) ); ?>
</div>
```

![Screenshot_2019-06-05 Retail Checkout Solutions - Retail Associates(1)](https://user-images.githubusercontent.com/27850046/58942170-2862d580-8775-11e9-8bc9-a5bc28154cd8.png)
![Screenshot_2019-06-05 Retail Checkout Solutions - Retail Associates](https://user-images.githubusercontent.com/27850046/58942171-2862d580-8775-11e9-9abc-5883884498e4.png)

Initially posted on wordpress forums
https://wordpress.org/support/topic/nav-menu-which-overlays-toggle/#post-11605410

**Comment by craig-stanfield** [comment]
Thinking about this, one fix would be to change the hamburger into a cross position it above the off-canvas area moved to where the x is but this seems a lot of extra work, I could also redesign the entire menu inline with other sites developed that work correctly but again if there is a solution that works out the box I'd prefer that as an option

**Comment by westonruter** [comment]
Thanks for opening the issue. This is a good one that exposes something that is missing from the `nav_menu_toggle` feature. In short, in addition to there being a `menu_button_id` there should be an `open_menu_button_id` and a `close_menu_button_id`. You could then have `open_menu_button_id` target the hamburger button and the `close_menu_button_id` target the ✖️ button.

**Comment by westonruter** [comment]
@craig-stanfield Another alternative, en lieu of [`AMP_Nav_Menu_Toggle_Sanitizer`](https://github.com/ampproject/amp-wp/blob/develop/includes/sanitizers/class-amp-nav-menu-toggle-sanitizer.php) directly supporting your use case, would be to just implement the same logic yourself in the theme directly. 

You can  follow the instructions after the horizontal line break in https://amp-wp.org/documentation/playbooks/toggling-hamburger-menus/

You just have to also add a Close button to set the `navMenuExpanded` state to `false`:

```html
<button
        class="close-button active" 
        aria-label="Close menu" 
        type="button" 
        on="tap:AMP.setState( { navMenuExpanded: false } )"
        [class]="'close-button ' + ( navMenuExpanded ? ' active' : '' )"
>
        <span aria-hidden="true">&times;</span>
</button>
```

**Comment by craig-stanfield** [comment]
@westonruter Interesting. I'll take a look into this, not at my desk right now but guessing until this feature supports this case i could extend the class and override the specific function? I'll look into both solutions later today and get back on this. Appreciate the help.

**Comment by westonruter** [comment]
There is no need to extend the class. If you follow the steps.mentioned in the playbook, there is no need for a sanitizer.The sanitizer is activated by that theme support flag, and the sanitizer is just an implementation of the playbook.

**Comment by craig-stanfield** [comment]
@westonruter I'm getting nowhere with this. the amp-state value stays as false. I tried with and without my original theme support snippet in functions.

I'm going to try this moving the toggle with css using the active class and see if I can work it this way

**Comment by craig-stanfield** [comment]
Actually the whole top menu container needs refactoring. We have an animated button on one of our sites which mutates from hamburger to a cross using css animation. I'll try this approach as it looks nicer anyway.

**Comment by craig-stanfield** [comment]
In the end i went with a simple solution and moved the off-canvas down to expose the button.

**Comment by westonruter** [comment]
Probably better anyway since you can just tap to open/close without moving your finger.
