### ISSUE TITLE
Access-Control-Allow-Origin multiple headers

### ISSUE THREAD

**Issue by paulkirspuu** [ampproject/amp-wp#2518]
Hey

Getting an error when using amp-form: `Access to fetch at 'https://example.com' from origin 'https://example-com.cdn.ampproject.org' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'https://example-com.cdn.ampproject.org, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Removing `cdn` header didn't help, then there was a new error: `The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.`.

Any idea how to deal with this?

**Comment by westonruter** [comment]
Are you setting the `Access-Control-Allow-Origin` header yourself? The AMP plugin is currently setting it via:

https://github.com/ampproject/amp-wp/blob/bd6b83a092564fe99023788621ece5e8d933f17a/includes/class-amp-http.php#L295

Note also that the `'replace' => false` param, indicating that it is not overriding any previous `Access-Control-Allow-Origin` headers that have been sent. So if you have previously sent `Access-Control-Allow-Origin: *` and then the AMP plugin sends `Access-Control-Allow-Origin: https://example-com.cdn.ampproject.org`.

So I'm guessing that PHP is sending two headers:

```
Access-Control-Allow-Origin: https://example-com.cdn.ampproject.org
Access-Control-Allow-Origin: *
```
and then it is combining these into one:
```
Access-Control-Allow-Origin: https://example-com.cdn.ampproject.org, *
```

**Comment by paulkirspuu** [comment]
Thanks for the answer!

We need the wildcard there, is the anything we can tweak on client side about this?
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

**Comment by westonruter** [comment]
But how are you adding the wildcard? Are you adding it via PHP or the webserver? 

I'm thinking that we could check to see if `Access-Control-Allow-Origin` has already been sent and is `*`, and if so, skip doing:

https://github.com/ampproject/amp-wp/blob/bd6b83a092564fe99023788621ece5e8d933f17a/includes/class-amp-http.php#L295

But if `*` is being sent by the webserver, then the plugin wouldn't be able to see it.

**Comment by paulkirspuu** [comment]
Worked around the wildcard, works fine now. Thanks!

**Comment by westonruter** [comment]
@paulkirspuu but how was it being added in the first place?

**Comment by paulkirspuu** [comment]
We had it in `.htaccess`, necessary HLS functionality.

**Comment by westonruter** [comment]
OK, so then the plugin wouldn't have been able to detect it. 👍
