### ISSUE TITLE
Automatic text type should not change formatting

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2519]
Text blocks have the text type (i.e. whether it's a heading or a paragraph) set to _automatic_ by default. Among other things, the text type changes depending on text length and position of the block. When the text type changes, so does the formatting, e.g. a heading is more bold than a paragraph.

For users these changes can be very unclear. Ideally the text type change does not affect formatting.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Hope you're having a great Friday. Could you please test this?

1. Create a new story

2. Add some text to the text block

3. In the inspector controls, change the settings for 'Select text type.' Try all 4: 'Automatic,' 'Paragraph,' 'Heading 1,' and 'Heading 2.'
<img width="1185" alt="text-block" src="https://user-images.githubusercontent.com/4063887/59133110-99081e80-893c-11e9-8bcd-4d7361f3e6ca.png">

4. Expected: changing these values shouldn't make the text in the text block look more or less bold (font-weight)

It shouldn't look like this:


![changing-text-type](https://user-images.githubusercontent.com/4063887/59133116-9f969600-893c-11e9-874f-7d02c175f775.gif)

**Comment by csossi** [comment]
Verified in QA
