### ISSUE TITLE
When adding a CTA block, the URL Input receives focus first

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2520]
This is basically the same issue as https://github.com/WordPress/gutenberg/issues/15859, so we need to implement a fix like https://github.com/WordPress/gutenberg/pull/15951.

**Comment by kienstra** [comment]
**Test Steps**

Hi @csossi,
Hope you're doing great. Could you please test this? It's very similar to #2521.

1. Create a new story and add a 'Call to Action' block:
<img width="1103" alt="add-call-block" src="https://user-images.githubusercontent.com/4063887/59097209-924cbd80-88e2-11e9-92f6-8e3d1d12e5e0.png">

2. Expected: after adding the block, the button text should have focus, not the URL input:
<img width="962" alt="focus-in-this" src="https://user-images.githubusercontent.com/4063887/59097784-13f11b00-88e4-11e9-9d43-f53ac4b6ea0a.png">

**Comment by csossi** [comment]
Verified in QA
![image](https://user-images.githubusercontent.com/16945664/59115389-32bcd500-8917-11e9-8d2a-a42773459f47.png)
