### ISSUE TITLE
When adding a CTA block, the placeholder does not disappear

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2521]
When inserting a CTA block and clicking on the button to change its text, the placeholder does not disappear and the user does not know that it is possible to start writing.

**Comment by kienstra** [comment]
**Steps To Test**

Hi @csossi,
Hope you had a great week. Could you please test this?

1. Create a new story and add a 'Call to Action' block:
<img width="1103" alt="add-call-block" src="https://user-images.githubusercontent.com/4063887/59097209-924cbd80-88e2-11e9-92f6-8e3d1d12e5e0.png">

2. Ensure that you can add text, without a placeholder interfering:
<img width="470" alt="ct-block" src="https://user-images.githubusercontent.com/4063887/59097307-d3dd6880-88e2-11e9-936a-fc995f4b0b1d.png">

**Comment by csossi** [comment]
Verified in QA
