### ISSUE TITLE
Change Block Navigation label

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2522]
The use of "Block" is confusing since it is Gutenberg terminology exposed to the user.

One suggestion was to rename it to "Page Components".

Another possibility would be "(Page) Elements" for example. Other suggestions welcome.

**Comment by westonruter** [comment]
Resolved by #2545.

**Comment by csossi** [comment]
Verified in QA - changed to "Elements":
![image](https://user-images.githubusercontent.com/16945664/59129058-be475d80-8939-11e9-9a52-ceb18401c956.png)
