### ISSUE TITLE
Consider making Block Navigation toggleable

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2523]
Sometimes the block navigation can get a bit into the way, and it might be irrelevant when you only have 1 or 2 blocks on a page anyway.

We should consider making it possible to collapse the block navigation, or perhaps even hide it completely (like you can close the sidebar).

That would also be a good thing especially on smaller screens.

**Comment by swissspidy** [comment]
The default block navigation in the post editor is in the top toolbar and looks like this:

![Screenshot 2019-06-12 at 16 29 57](https://user-images.githubusercontent.com/841956/59359845-62147d00-8d2f-11e9-9666-7641e7ae6943.png)

So my suggestion would be to have such a button in the top toolbar as well, but use it to just hide/show our custom block navigation. Still at the same place.

**Comment by amedina** [comment]
That is a good idea. Would it be possible to `undock` the box that pops up? I am thinking about the scenario where the creator clicks on that toolbar button, and the block navigation opens around the place where it is located now; and then the user can click on a `close` section of it and it would disappear.  This would have the advantage of keeping the navigation closer to the pages when open.

**Comment by swissspidy** [comment]
That was my suggestion. Our custom component stays in the same location, but we would add a toggle in the toolbar for it.

**Comment by amedina** [comment]
Got it; that would be a good  UX enhancement.
