### ISSUE TITLE
Enable video previews in editor

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2530]
In AMP story context, videos must autoplay and loop to be valid. That's why we hide these controls already.

Now, it would be even better when the videos would autoplay in the editor already. Just like we already do for the page background video.

For that we probably have to extend the video block's edit component as the video tag is hardcoded (and disabled) there:

https://github.com/WordPress/gutenberg/blob/ff70de60086e8f505de51a9f9883d77bf5eda119/packages/block-library/src/video/edit.js#L280-L291

**Comment by kienstra** [comment]
**Going To Work On This**

Hi @swissspidy,
If it's alright, I'm going to work on this.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this?

1. Create a new AMP Story
2. Add a Video block
3. Select a video for it
4. Expected: the video [plays in the editor](https://github.com/ampproject/amp-wp/pull/2799#issuecomment-510728653) (it didn't before)
<img width="1056" alt="video-block-editor" src="https://user-images.githubusercontent.com/4063887/61257664-9ff23000-a737-11e9-89da-a42216f4f51e.png">


5. Expected: there should be toggles for 'Display Caption' and 'Loop,' and they should work

**Comment by csossi** [comment]
Verified in QA
