### ISSUE TITLE
Add easier way to duplicate a page

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2532]
## Feature description
As a user I want there to be an easier way to duplicate pages from within the editor.

## Acceptance criteria
AC1: Add "Duplicate page" to the right-click context menu, upon selection, page will be duplicated.
AC2: The duplicated page should be inserted right next to the original one (same behavior as when using the block toolbar)

## Implementation brief
For more detail, see https://github.com/ampproject/amp-wp/issues/3279

A mockup of what this will look like. 
![Screenshot from 2019-10-15 15-40-31](https://user-images.githubusercontent.com/237508/66846117-34537500-ef69-11e9-81ed-62aa77137b4a.png)

## QA testing instructions

- Create new story post. 
- Create a second page. 
- Select second page. 
- Right Click page to show context menu
- Click duplicate page. 
- Confirm page is duplicated.  
- Confirm the duplicate page is inserted next to original page

## Demo

* https://youtu.be/fMA5nCsxyKo

## Changelog entry

*

**Comment by westonruter** [comment]
See also a bug with the current duplication: #2510

**Comment by swissspidy** [comment]
What about using the new right click menu for this?

Related: #3279.

**Comment by spacedmonkey** [comment]
In #3537 there is now a option to duplicate a page.

**Comment by jauyong** [comment]
@swissspidy I'd like to add this to 1.4 as Jonny said this is basically done in this PR. Is all that needs to be done to add the milestone and get this on the execution board?


https://github.com/ampproject/amp-wp/pull/3537

**Comment by swissspidy** [comment]
@jauyong Yep, but should also have ACs  and testing instruction for sure. #3279 covers a large part of that already.

**Comment by spacedmonkey** [comment]
@jauyong If you could put in ACs, I can put in IB and testing instructions.

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
Demo (props @spacedmonkey): https://www.youtube.com/watch?v=fMA5nCsxyKo&feature=youtu.be
