### ISSUE TITLE
Use React Hooks where appropriate

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2538]
In the latest version of Gutenberg, a bunch of handy [React hooks](https://reactjs.org/docs/hooks-intro.html) have been added, most notably `useSelect` and `useDispatch`. ([see documentation](https://github.com/WordPress/gutenberg/tree/2564c2122f75541cbdf4fcfdebdfc839dadeeb7a/packages/data)). It also exposes existing hooks like `useState`, for example.

Specifically for AMP Stories we have added many higher-order components that over time can make code quite hard to read. We also heavily leverage the pre-existing `withSelect` and `withDispatch` HOCs.

With React hooks we have the opportunity to greatly simplify many of our custom React components to make them easier to comprehend and maintain in the long term.

Note: `withSelect` internally already uses that new `useSelect` hook, so switching to hooks directly would remove an unnecessary layer in-between.

**Comment by swissspidy** [comment]
* We currently require Gutenberg 5.8 or higher
* React hooks are available since Gutenberg 5.3
* `useSelect` has been introduced in Gutenberg 5.9
* A bug with scalar return types values in `useSelect` has been fixed in Gutenberg 6.3

**Comment by swissspidy** [comment]
Quick update: #3167 bumped the Gutenberg requirement to 5.9, so we can now freely leverage `useSelect and `useDispatch`.

**Comment by spacedmonkey** [comment]
List of remaining components 

- `InserterMenu`
- `EnhancedResizableBox`
- `IgnoreNestedEvents`
- `Draggable`
- `PostSelector`

**Comment by swissspidy** [comment]
#3412 covered the stories editor, but as Jonny notes there are still some remaining class components. For various reasons:

Some components are copied from Gutenberg (e.g. `IgnoreNestedEvents`), and keeping them that way makes it easier to merge any upstream changes. Others are quite large and could benefit from their own PR (e.g. `Draggable`), others have some uncertainty around their future (e.g. `PostSelector`)

As for the non-stories part we have to wait with hook usage due to backward compatibility (see #3359).

**Comment by westonruter** [comment]
@swissspidy Is this still relevant?
