### ISSUE TITLE
Consider making the 'Block Navigation' panel 'toggable' 

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2539]
Right now the Block Navigation panel can get in the way of the editing experience (e.g. if the window is not big enough, or get on top of the 'previous' page. It would be good if users could make the Block Navigation panel disappear if they wish to do so. 

/cc @pbakaus

**Comment by westonruter** [comment]
@amedina Duplicate of #2523?

**Comment by swissspidy** [comment]
There‘s already an issue for this.
