### ISSUE TITLE
Export AMP Story as Images

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2543]
Related: #2466

----

Yesterday I learnt that someone is working on a really interesting tool that takes an existing AMP Story and creates screenshots for each page in the story. These screenshots can then be used to publish a story on Instagram or another platform. -> write once, use anywhere.

See demo: https://twitter.com/WillmannTobias/status/1135128875791527937

I think it would be really cool to have the same feature in the WordPress Stories editor as well, in addition to a ZIP file export (#2466).

**Comment by westonruter** [comment]
This wouldn't work with stories that have video or animations, correct?

**Comment by swissspidy** [comment]
Well you could try doing a screen recording to capture those, but otherwise no

**Comment by swissspidy** [comment]
The tool has now launched and can be accessed here: https://prod-seo-ampstoryscreenshotsfrontend.s3.eu-central-1.amazonaws.com/index.html

No idea why it needs a login though...

Article with details about how it was built: https://medium.com/@WillmannTobias/reuse-amp-stories-on-instagram-23eb169e4ed2

**Comment by amedina** [comment]
This is very interesting as we have been pondering about such capability. Let's analyze the options here. 

/cc @pbakaus

**Comment by ithinkihaveacat** [comment]
Note that if you load an AMP Story with a UA string that includes "bot", the runtime renders the story as one continuous page. This is more intended for search engines rather than for taking high-fidelity screenshots, but it might be useful somehow.

(I also have some screenshot code that uses Puppeteer, if you're interested I can make public.)
