### ISSUE TITLE
WordPress Core Locale Switcher Causes Loop in AMP Validator

### ISSUE THREAD

**Issue by chriscct7** [ampproject/amp-wp#2547]
When attempting to validate an AMP page (native or in transitional mode), the validation fails with `URL validation failed to due to the absence of the expected JSON-containing AMP_VALIDATION comment after the body.`.

Upon inspecting the page in the frontend as a logged in admin via the `?amp_validate` query parameter, a PHP error is displayed (error output to frontend is enabled on local development site):

```
[07-Jun-2019 15:58:48 UTC] PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /app/public/wp-includes/functions.php:5971
Stack trace:
#0 /app/public/wp-includes/functions.php(5971): strpos('/app/public/wp-...', '://')
#1 /app/public/wp-includes/functions.php(1900): wp_is_stream('/app/public/wp-...')
#2 /app/public/wp-content/plugins/amp/includes/validation/class-amp-validation-manager.php(1389): wp_normalize_path('/app/public/wp-...')
#3 /app/public/wp-content/plugins/amp/includes/validation/class-amp-validation-manager.php(1179): AMP_Validation_Manager::get_source('wp_normalize_pa...')
#4 /app/public/wp-includes/class-wp-hook.php(332): AMP_Validation_Manager::wrap_hook_callbacks('theme_root', '/app/public/wp-...')
#5 /app/public/wp-includes/plugin.php(862): WP_Hook->do_all_hook(Array)
#6 /app/public/wp-includes/plugin.php(187): _wp_call_all_hook(Array)
#7 /app/public/wp-includes/theme.php(590): apply_filters('theme_root', '/app/public/wp-...')
#8 /app/public/wp-content/plugins/amp/includes/validation/class-a in /app/public/wp-includes/functions.php on line 5971
```

Upon attempting to debug this, via adding a `var_dump( $file );wp_die();` on line 1388 of `amp/includes/validation/class-amp-validation-manager.php`, it is visibly apparent that the WordPress core file `wp-includes\class-wp-locale-switcher.php` is looping over and over.

Upon opening this file and commenting out the contents of the public function `init` to prevent this class from executing, the AMP validation works immediately, and is able to successfully validate the page.

On this local environment, WordPress core downloads translation files for three languages due to some testing I've been doing (Arabic (RTL testing) and Russian (cyrllic testing)) as part of standard testing of one of my plugins, each set to load for a particular user. This explains WordPress's inclusion of the file.

When I remove the `die`, the error begins happening again.

Then when I use the AMP plugin setting to remove the admin bar (where the WordPress Core locale switcher is located), the validation also succeeds. 

And again as I turn off that setting it fails again.

This issue cannot be replicated on a new WordPress install which does not have more than 1 language locale installed.

I have not traced the issue specifically in the locale class causing it to loop, but if it requires time to fix, a quick solution to at least solve the AMP validation for those in this situation would be to disable the locale switching feature for admin users in the admin bar when trying to validate AMP.

Since the AMP service will never see this service (as the users logged out do not have locale switching), this is a quick tradeoff until it can be properly fixed.

**Comment by chriscct7** [comment]
The WordPress version installed is 5.2.1 but I tested back to 5.0.4, so the bug causes an incompatibility with WordPress versions at least as old as 5.0.4 (possibly older as well).

The AMP version is 1.1.3

**Comment by chriscct7** [comment]
Notably, I did not test with the 1.2 beta. So its possible the beta fixes this already.

**Comment by westonruter** [comment]
@chriscct7 Thanks for reporting this. Actually, I think I encountered this myself. The `theme_root` appearing in the callstack makes me think the issue that I encountered and fixed in 68d61d852dc06694578631641590ed6ae44d3b38. This is actually in [1.2-beta2](https://github.com/ampproject/amp-wp/releases/tag/1.2-beta2). Could you please actually try in 1.2?

**Comment by westonruter** [comment]
Also, to help further guard against the possibility of infinite recursion, this could be further hardened perhaps as follows:

```diff
index d81c3472..91be11d9 100644
--- a/includes/validation/class-amp-validation-manager.php
+++ b/includes/validation/class-amp-validation-manager.php
@@ -1398,13 +1398,10 @@ class AMP_Validation_Manager {
 			if ( preg_match( ':' . preg_quote( trailingslashit( wp_normalize_path( WP_PLUGIN_DIR ) ), ':' ) . $slug_pattern . ':s', $file, $matches ) ) {
 				$source['type'] = 'plugin';
 				$source['name'] = $matches[1];
-			} elseif ( preg_match( ':' . preg_quote( trailingslashit( wp_normalize_path( self::$template_directory ) ), ':' ) . ':s', $file ) ) {
+			} elseif ( preg_match( ':' . preg_quote( trailingslashit( wp_normalize_path( self::$template_directory ) ), ':' ) . $slug_pattern . ':s', $file ) ) {
 				$source['type'] = 'theme';
-				$source['name'] = get_template();
-			} elseif ( preg_match( ':' . preg_quote( trailingslashit( wp_normalize_path( self::$stylesheet_directory ) ), ':' ) . ':s', $file ) ) {
-				$source['type'] = 'theme';
-				$source['name'] = get_stylesheet();
-			} elseif ( preg_match( ':' . preg_quote( trailingslashit( wp_normalize_path( get_theme_root() ) ), ':' ) . $slug_pattern . ':s', $file, $matches ) ) {
+				$source['name'] = $matches[1];
+			} elseif ( preg_match( ':' . preg_quote( trailingslashit( wp_normalize_path( self::$stylesheet_directory ) ), ':' ) . $slug_pattern . ':s', $file ) ) {
 				$source['type'] = 'theme';
 				$source['name'] = $matches[1];
 			} elseif ( preg_match( ':' . preg_quote( trailingslashit( wp_normalize_path( WPMU_PLUGIN_DIR ) ), ':' ) . $slug_pattern . ':s', $file, $matches ) ) {
```

It's unnecessary to include the check for `get_theme_root()` since only the parent theme or child theme are going to be active anyway.

**Comment by chriscct7** [comment]
I spent a bit of time on this today but I'm not able to replicate it on the beta but I'm not sure I'm accurately reproducing my own bug atm. I'll keep working on this tomorrow.

I know you all are planning to ship v1.2 so I'll try to get to it as early as possible again but worst case scenario it can probably wait till another release since it at least is mitigatable via the existing settings in v1.1

**Comment by swissspidy** [comment]
@chriscct7 Have you had a chance to test with the new 1.2 release? We released it last week.

**Comment by chriscct7** [comment]
Yeah I haven't been able to replicate this since. I think we can close this
for now

**Comment by swissspidy** [comment]
Awesome, thanks for confirming!

@westonruter Still wanna do that hardening you mentioned? If not, I'll close this.

**Comment by westonruter** [comment]
Yes, I'll add the hardening for this while addressing #2698.
