### ISSUE TITLE
Update validating sanitizer to be aware of satisfies/requires constraints

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2551]
There are instances of tag specs containing `satisfies` and `requires`:

```
validator/validator-main.protoascii
260:  satisfies: "amp-app-banner data source"
478:  satisfies: "amp-app-banner data source"
539:  satisfies: "meta name=amp-consent-blocking"
569:  satisfies: "amp-experiment-token"
4472:  satisfies: "amp-app-banner button[open-button]"

extensions/amp-consent/validator-amp-consent.protoascii
34:  satisfies: "amp-consent extension .json script"
73:  satisfies: "amp-consent [type]"

extensions/amp-animation/validator-amp-animation.protoascii
37:  satisfies: "amp-animation extension .json script"

extensions/amp-ad-exit/validator-amp-ad-exit.protoascii
48:  satisfies: "amp-ad-exit configuration JSON"

extensions/amp-story/validator-amp-story.protoascii
158:  satisfies: "amp-story-page"
439:  satisfies: "amp-story-consent extension .json script"

extensions/amp-subscriptions/validator-amp-subscriptions.protoascii
35:  satisfies: "amp-subscriptions extension .json script"

extensions/amp-link-rewriter/validator-amp-link-rewriter.protoascii
25:  satisfies: "amp-link-rewriter"

extensions/amp-smartlinks/validator-amp-smartlinks.protoascii
26:  satisfies: "amp-smartlinks"

extensions/amp-skimlinks/validator-amp-skimlinks.protoascii
26:  satisfies: "amp-skimlinks"

extensions/amp-access/validator-amp-access.protoascii
35:  satisfies: "amp-access extension .json script"
```

```
extensions/amp-consent/validator-amp-consent.protoascii
57:  requires: "amp-consent extension .json script"
71:  requires: "meta name=amp-consent-blocking"
72:  requires: "amp-consent extension .json script"

extensions/amp-animation/validator-amp-animation.protoascii
61:  requires: "amp-animation extension .json script"

extensions/amp-ad-exit/validator-amp-ad-exit.protoascii
31:  requires: "amp-ad-exit configuration JSON"

extensions/amp-story/validator-amp-story.protoascii
38:  requires: "amp-story-page"
124:  requires: "amp-story-page"
463:  requires: "amp-story-consent extension .json script"

extensions/amp-app-banner/validator-amp-app-banner.protoascii
32:  requires: "amp-app-banner data source"
36:  requires: "amp-app-banner button[open-button]"

extensions/amp-script/validator-amp-script.protoascii
33:  requires: "amp-experiment-token"
```

For example, `amp-script` is requires an `amp-experiment-token` in #2537.

It is unlikely that these validator constraints will be encountered by users, since none of them relate to regular HTML. In other words, the sanitizers converting theme/plugin HTML into AMP should never encounter a scenario where these constraints are violated. They are primarily of concern for developers who are writing AMP directly. This being the case, the developers will be already much more likely to be using the AMP Validator extension and be aware of what the AMP components need to be _present_ (not what AMP requires to be _absent_, which is what the sanitizers are primarily concerned with).

In other words, if someone adds an `amp-script` to the page with just:

```php
add_action( 'wp_footer', function() {
    ?>
    <amp-script layout="container" src="https://example.com/hello-world.js">
        <button id="hello">Insert Hello World!</button>
    </amp-script>
    <?php
} );
```

The AMP validator will complain:

> The tag 'amp-experiment-token' is missing or incorrect, but required by 'amp-script'. Learn more.

But the AMP plugin won't strip out the `amp-script` in this case. It would be up to the developer to do:

```php
add_action( 'wp_head', function() {
    ?>
    <meta name="amp-experiment-token" content="{copy your token here}">
    <?php
} );
```

So this is something to keep in mind, but it isn't something the AMP plugin is going to do automatically for the foreseeable future (due to the limited benefit, and increased processing time).

Note that the validating sanitizer _is_ aware of the `requires_extension:` constraint, as that is how it determines which AMP scripts to automatically include on the page.

**Comment by amedina** [comment]
> So this is something to keep in mind, but it isn't something the AMP plugin is going to do automatically for the foreseeable future (due to the limited benefit, and increased processing time).

Closing for now. Will revisit in the future.
