### ISSUE TITLE
Embed block: "Convert to link" causes console error

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2552]
Steps to reproduce:
- Add an Embed block.
- Add URL, e.g. `https://amp.wordpress.test`.
- Click "Embed".
- When it says `Sorry, this content could not be embedded.`, click "Convert to link"
- See the error in console.

![Screen Shot 2019-06-10 at 4 00 24 PM](https://user-images.githubusercontent.com/3294597/59200868-7aeb2a00-8b99-11e9-806e-905fe1aabc41.png)

**Comment by swissspidy** [comment]
I assume "Convert to link" tries to create a paragraph block? If so, this is closely related to https://github.com/WordPress/gutenberg/issues/15883 / #2455 and likely needs to be fixed upstream using a similar fix as https://github.com/WordPress/gutenberg/pull/15885.

**Comment by miina** [comment]
@swissspidy That's right, it tries to convert to a paragraph block. Wondering if we should hide the link in AMP Stories. Not sure if there's a good selector though. Thoughts?

**Comment by swissspidy** [comment]
Ideally we'd fix this upstream so the button would not show when the block type has been unregistered :-)

Not sure about a selector to hide the button in the meantime, I'd need to test it.

**Comment by miina** [comment]
> Ideally we'd fix this upstream so the button would not show when the block type has been unregistered :-)

Agreed! 

> Not sure about a selector to hide the button in the meantime, I'd need to test it.

We could target the second button of the error area which suggests converting to a link. However, not sure if that's reliable. I guess that if it's an upstream issue then it'd be OK to leave as it is for now as well.

**Comment by swissspidy** [comment]
Here's the upstream code in question:

https://github.com/WordPress/gutenberg/blob/f46d6f486f954588d6271086bdaec00ea478c127/packages/block-library/src/embed/util.js#L173-L185

https://github.com/WordPress/gutenberg/blob/f46d6f486f954588d6271086bdaec00ea478c127/packages/block-library/src/embed/edit.js#L144-L158

https://github.com/WordPress/gutenberg/blob/f46d6f486f954588d6271086bdaec00ea478c127/packages/block-library/src/embed/embed-placeholder.js#L28
