### ISSUE TITLE
Resizing going smaller than the block for less common blocks

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2553]
This issue seems to happen at least for the table, pullquote, verse, code block.

Steps to reproduce:
1. Add any of the blocks mentioned above.
2. Add some content.
3. Try resizing smaller.

Screenshots based on pullquote.

Editor:
![Screen Shot 2019-06-10 at 4 08 57 PM](https://user-images.githubusercontent.com/3294597/59201202-27c5a700-8b9a-11e9-88b8-648b6ebb7435.png)

FE:
![Screen Shot 2019-06-10 at 4 09 14 PM](https://user-images.githubusercontent.com/3294597/59201210-2c8a5b00-8b9a-11e9-9ec3-19508b1e9ff5.png)

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this, using the [steps above](https://github.com/ampproject/amp-wp/issues/2553#issue-454190371)?

Thanks!

**Comment by Saoming** [comment]
0m; hug tlhoui

**Comment by csossi** [comment]
Verified in QA
