### ISSUE TITLE
Use customized edit-post package

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2554]
The whole awesomeness of the block editor in WordPress begins with the `@wordpress/edit-post` package. It's responsible for [initializing the editor](https://github.com/WordPress/gutenberg/blob/59e56dc607b6796d104f21f03ca90e87d4b4a1e0/packages/edit-post/src/index.js#L52-L96), complete with the NUX tips, [editor settings](components/layout), and the [overall layout](https://github.com/WordPress/gutenberg/blob/59e56dc607b6796d104f21f03ca90e87d4b4a1e0/packages/edit-post/src/components/layout/index.js) with header (toolbar), sidebar, and of course the (visual/code) editor itself.

While this works great for the regular post edit screen, it has caused some pain when working on the AMP Stories editor as some of the features in that package simply do not apply to our use case.

As a consequence, there were multiple instances where we had to insert elements in the middle of the editor using some DOM operations, and hide tons of things using CSS.

Examples of conflicting components include [WritingFlow](https://github.com/WordPress/gutenberg/blob/40797c63bbb5f2c28c0b9af17791d7565d181bc5/packages/block-editor/src/components/writing-flow/index.js) and [BlockList](https://github.com/WordPress/gutenberg/blob/59e56dc607b6796d104f21f03ca90e87d4b4a1e0/packages/block-editor/src/components/block-list/index.js), as well as basically the whole header and sidebar areas and components therein. That all our blocks are draggable and resizable is also something that makes using all these components

In the future, I expect the Stories editor UI to diverge more and more from the default post editor.

For example, we might position the block toolbar in a completely different place (#2309) and add some new UI controls (#2532) or even completely new interfaces (#2529, #2525, #2527, #2409).

All these changes are also likely to cause problems with features like fullscreen or spotlight mode (#2221, #2177).

With that, we will soon reach a point where we need to consider using our own custom `@wordpress/edit-post` implementation or find some other way to gain more control over the UI by overriding some components with our own implementations.

**Comment by swissspidy** [comment]
^ thoughts?

**Comment by swissspidy** [comment]
@miina @westonruter @kienstra ^ thoughts?

**Comment by westonruter** [comment]
In other words, you're thinking that we could fork the Gutenberg repo to start maintaining a modified version of the `edit-post` (i.e. `edit-story`) package that we would bundle with the AMP plugin?

**Comment by swissspidy** [comment]
Forking the repository is not really what I had in mind, but yes some custom package is probably something we could end up with. An example would be the new [`@wordpress/edit-widgets`](https://github.com/WordPress/gutenberg/tree/59e56dc607b6796d104f21f03ca90e87d4b4a1e0/packages/edit-widgets) package and to some degree perhaps https://github.com/woocommerce/woocommerce-admin

**Comment by miina** [comment]
Could be a good idea if we'll continue to need overriding the default package -- to have better control over things potentially breaking with updates and also not having to invent complicated workarounds.

Are you thinking of a completely new package instead of the `edit-post`, or still using the default components as well?

**Comment by swissspidy** [comment]
I haven't looked closely into it yet. Last time I checked, most of the components within that `edit-post` package were not exported, so reusing them is not easily possible.

**Comment by swissspidy** [comment]
As discussed today I'll work on writing a design doc for that.
