### ISSUE TITLE
Resizing text block causes validation error

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#2556]
Steps to reproduce:
1. Checkout the `develop` branch, create a new Text block and add some text
2. Resize it
3. Click 'Save Draft'
4. Reload the page
5. Expected: there's no validation error
6. Actual: there's a validation error:

![text-block-here](https://user-images.githubusercontent.com/4063887/59229802-0ddb9280-8ba1-11e9-85ee-59e6c6f185e8.gif)

The validation error:
<img width="1188" alt="validation-error-here" src="https://user-images.githubusercontent.com/4063887/59229863-44191200-8ba1-11e9-8e30-dd6c495e0a70.png">

**Comment by kienstra** [comment]
Reverting #2389 seemed to fix this. I'll keep looking at it.

**Comment by kienstra** [comment]
It looks like on resizing the Text block to expand the size, it sets the `positionLeft` and `positionTop` to `null`:

![resizing-here](https://user-images.githubusercontent.com/4063887/59233356-b98adf80-8bad-11e9-93a6-9ee416875374.gif)

**Comment by miina** [comment]
Instructions for testing:
- Create a Text block.
- Resize it and rotate it.
- Reload the page.
- Verify that there are no validation errors after reloading the page and the block shows as it was saved.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Hope you're having a great day so far.

Could you please test this, using the [steps to reproduce](https://github.com/ampproject/amp-wp/issues/2556#issue-454392626) at the top? Thanks!

**Comment by csossi** [comment]
Verified in QA

**Comment by kienstra** [comment]
Nice, thanks a lot for testing this.
