### ISSUE TITLE
CTA block not working as expected

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2559]
Steps to reproduce:

1. Open the templates inserter.
2. Observe the CTA blocks in the template preview -- both look without content.
3. See the console error:
![Screen Shot 2019-06-11 at 11 24 13 AM](https://user-images.githubusercontent.com/3294597/59260306-a58dbf00-8c3b-11e9-90a3-a02bc20a6b69.png)

Additionally, it looks like it's not possible to add text to the CTA block and displays some warning messages in the console. To reproduce, add a CTA block, try to add content, save and reload. See the empty content after reloading.

![Screen Shot 2019-06-11 at 11 27 55 AM](https://user-images.githubusercontent.com/3294597/59260560-20ef7080-8c3c-11e9-9768-83c5900cd537.png)

**Comment by swissspidy** [comment]
Looks like this has somehow been fixed by #2561.

@miina If you cannot reproduce this anymore feel free to close this.

**Comment by miina** [comment]
Same here, can't reproduce this. Closing as fixed within #2561.
