### ISSUE TITLE
Display a notice if a video in the video block is over 1 MB per second

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#2560]
* Splitting off a requirement from #2509 into this issue
* There should be a warning when adding a video to the Video block that is over 1 MB per second:
<img width="520" alt="video-block" src="https://user-images.githubusercontent.com/4063887/59262697-588ef600-8c05-11e9-9c45-6184af3821ee.png">

As @swissspidy mentioned:
>A suggestion of mine was to also show the warnings when selecting the video in the media modal, just like we do for the featured image.

<img width="718" alt="featured-im" src="https://user-images.githubusercontent.com/4063887/59262987-dfdc6980-8c05-11e9-979b-2d635210af68.png">

**Comment by westonruter** [comment]
Also, once a video has been selected, both for the video block and for the video background, let's have the warning message indicate what the current MB/second is for the selected video. This will tell them how far from the target they are.

**Comment by kienstra** [comment]
Sure, sounds good 😄

**Comment by westonruter** [comment]
# Testing instructions

Given an uploaded MP4 that is relatively large given its duration, such as:

![image](https://user-images.githubusercontent.com/134745/59387904-39848700-8d1f-11e9-8579-7b21637f650d.png)

Select the video as a page background and you should see the warning amended with text like “The selected video is 10 MB per second”:

![image](https://user-images.githubusercontent.com/134745/59387938-4e611a80-8d1f-11e9-874e-e5cd834bc092.png)

**Comment by westonruter** [comment]
> Also, once a video has been selected, both for the video block and for the video background, let's have the warning message indicate what the current MB/second is for the selected video. This will tell them how far from the target they are.

Fixed in #2607.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please this, using the [steps here](https://github.com/ampproject/amp-wp/pull/2755#issuecomment-509507198)?

**Comment by csossi** [comment]
Verified in QA
