### ISSUE TITLE
Block Navigation label is incorrect when there is only a CTA block

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2564]
**To reproduce:**

1. Create a few pages
2. Add a CTA block on a page
3. Notice that the block navigation says "No elements added to this page yet."

**Screenshot:**

![Screenshot 2019-06-11 at 17 10 41](https://user-images.githubusercontent.com/841956/59284154-0df49480-8c6c-11e9-8424-4168e0e6a307.png)

**Reason**

This happens because we don't show the CTA block in the block navigation as it cannot be moved anyway.

**Possible Solution(s)**

Since #2443 we enforce the CTA block to be last in the list. So perhaps now we could display it in the block navigation again.

However, we would need to make sure that the block is not draggable there and that it doesn't have a drop zone, i.e. no block can be moved past it.

Alternatively, we could try to show a different text in that case. Or perhaps this can be considered as `won't fix` under the stance of the CTA block not being a regular element like the other blocks — a call to action.

**Comment by miina** [comment]
Note: will start looking into this.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this, using the [steps above](https://github.com/ampproject/amp-wp/issues/2564#issue-454752258)?

**Comment by csossi** [comment]
Verified in QA
![image](https://user-images.githubusercontent.com/16945664/60769316-34a3c080-a09c-11e9-82a5-1a0e7655801f.png)
