### ISSUE TITLE
Horizontal scrollbars are appearing in story editor

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2566]
![image](https://user-images.githubusercontent.com/134745/59289841-e5e54100-8c2b-11e9-8871-06d6acba6593.png)

**Comment by westonruter** [comment]
This happens particularly on the first page:

![image](https://user-images.githubusercontent.com/134745/59289872-ff868880-8c2b-11e9-80fb-027d8c248b81.png)

On the second page, the scrollbar goes away:

![image](https://user-images.githubusercontent.com/134745/59289917-1cbb5700-8c2c-11e9-84be-8f55bec7c755.png)

**Comment by swissspidy** [comment]
As an explanation, that the width of `1110` is coming from the width of the wrapping `#amp-story-editor` element. `#amp-story-editor > .editor-block-list__layout` then uses flexbox to lay out the inner blocks horizontally.

**Comment by westonruter** [comment]
Can we just add `overflow:hidden` on the `#amp-story-editor`? That seems to fix the problem for me.

**Comment by swissspidy** [comment]
As mentioned on Slack, a simply `overflow: hidden` there is not going to work. This will cut off elements all over the place. Quick example:

<img width="793" alt="Screenshot 2019-06-11 at 18 55 33" src="https://user-images.githubusercontent.com/841956/59291208-9843f500-8c7a-11e9-8f92-3accec645bd2.png">

**Comment by westonruter** [comment]
This is the only place I see an element being cut off when I add `overflow:hidden` to `#amp-story-editor`:

![image](https://user-images.githubusercontent.com/134745/59292384-d2d56f80-8c31-11e9-92a1-cb96f184ac6c.png)

Which seems just fine.

**Comment by swissspidy** [comment]
Note that `.amp-story-editor-carousel-navigation` needs more top margin there, at least `margin-top: 7em;`. Or ideally the elements above would automatically push it down. 🤷‍♂

**Comment by westonruter** [comment]
@swissspidy in regards to the CTA block on the first page, what if the warning were displayed instead of the block? Or above the block?

![image](https://user-images.githubusercontent.com/134745/59304160-8a777b00-8c4c-11e9-8c53-eaeda6503ee0.png)

**Comment by swissspidy** [comment]
That works too. Still think the margin needs to be increased a bit though.

**Comment by csossi** [comment]
Verified in QA
