### ISSUE TITLE
AMP Page as canonical one

### ISSUE THREAD

**Issue by zJar84** [ampproject/amp-wp#2568]
Hello, I have AMP on Reader mode and I want to see my AMP pages EQUAL as I have on their canonicals.

There are a method that I can use for it?

An example of a web doing this is unareceta.com. Those are some examples:

[https://unareceta.com/tarta-de-queso/](https://unareceta.com/tarta-de-queso/)
[https://unareceta.com/tarta-de-queso/amp/](https://unareceta.com/tarta-de-queso/amp/)

Thanks!

**Comment by westonruter** [comment]
@zJar84 Hi. I'm not sure I understand. Are you desiring to have the AMP version look the same as the non-AMP version? To do that, you'll need to have an AMP-compatible theme and switch to Native (soon “Standard”) or Transitiional mode.

Also, I notice that you are using a very old version of the plugin. Please update from 0.7 to the latest. Note that [1.2-beta2](https://github.com/ampproject/amp-wp/releases/tag/1.2-beta2) is available, with 1.2-rc1 due in the next day. The 1.2 stable release should be out next week.

**Comment by zJar84** [comment]
> @zJar84 Hi. I'm not sure I understand. Are you desiring to have the AMP version look the same as the non-AMP version? To do that, you'll need to have an AMP-compatible theme and switch to Native (soon “Standard”) or Transitiional mode.
> 
> Also, I notice that you are using a very old version of the plugin. Please update from 0.7 to the latest. Note that [1.2-beta2](https://github.com/ampproject/amp-wp/releases/tag/1.2-beta2) is available, with 1.2-rc1 due in the next day. The 1.2 stable release should be out next week.

Yes, I want have the AMP version look the same as the non-AMP version. I have the Orbital theme, and a question.

With the Transitional mode, the amp pages will be apart of the canonicals as occurs with the Reader mode?

I need it, have AMP pages separated from the non-AMP pages.

Thanks!

**Comment by westonruter** [comment]
> With the Transitional mode, the amp pages will be apart of the canonicals as occurs with the Reader mode?

Yes. In Transitional mode, the canonical pages will be left unmodified. Since this is a paired AMP mode, there is separate `?amp` URL for each page with the AMP version.

I have not tested Orbital to see how well it works in Transitional mode, but you'll get best results if you test in 1.2-beta2.
