### ISSUE TITLE
Template thumbnails not appearing as intended in + menu

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2574]
When accessing the + menu to insert a template, the template thumbnails contain unexpected text styles, see image below:

<img width="480" alt="Screen Shot 2019-06-12 at 5 51 27 AM" src="https://user-images.githubusercontent.com/24547817/59341776-71b3a780-8cd6-11e9-83d2-19e9a725eeb1.png">

Expectation is that the text styles would match what is being inserted...use the "tip" template to recreate issue...when inserted, text appears in a different style than it does in the thumbnail.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Click on template inserter
2. Verify that previews don't look as odd as in the screenshot above
3. Verify that call-to-action buttons in the previews are properly centered

**Comment by csossi** [comment]
Verified in QA
