### ISSUE TITLE
Template Inserters menu styling displays incorrectly sometimes

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2576]
Sometimes, depending on the vertical scrolling on the page, the template inserter's styling looks a bit odd:

<img width="374" alt="Screenshot 2019-06-12 at 12 35 00" src="https://user-images.githubusercontent.com/3294597/59344769-01754800-8d0f-11e9-84a5-489730bbd6f0.png">

**Comment by swissspidy** [comment]
I _might_ have seen that in the regular post editor before, but not sure.

**Comment by miina** [comment]
Instructions for testing:
- Open the template Inserter.
- Scroll vertically while the template inserter is open.
- Verify that the template inserter does not have two small triangles showing as seen in the screenshot here: https://github.com/ampproject/amp-wp/issues/2576#issue-455138768

**Comment by csossi** [comment]
Verified in QA
