### ISSUE TITLE
Block navigation goes too narrow when resizing the window small

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2578]
Steps to reproduce:
1. Resize the window to quite narrow.
2. Observe the results:
<img width="1096" alt="Screenshot 2019-06-12 at 16 06 12" src="https://user-images.githubusercontent.com/3294597/59358099-42c82080-8d2c-11e9-8031-efb245dd5a94.png">

Expected:
- The block navigation shouldn't look broken. Not clear what's the best approach here though.

**Comment by swissspidy** [comment]
Sort of related: #2523

**Comment by miina** [comment]
Instructions for testing:
- Verify that in any viewport size the Block Navigation doesn't look broken so that the text inside doesn't fit and goes over (see the [description](https://github.com/ampproject/amp-wp/issues/2578#issue-455236458) of the ticket for reference).

**Comment by csossi** [comment]
Verified in QA
