### ISSUE TITLE
Too many things hidden in image block toolbar

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2580]
Current situation:

![Screenshot 2019-06-12 at 17 04 26](https://user-images.githubusercontent.com/841956/59362720-3d6ed400-8d34-11e9-9316-4789a9b1569b.png)

Desired situation:

![Screenshot 2019-06-12 at 17 04 47](https://user-images.githubusercontent.com/841956/59362733-41025b00-8d34-11e9-9451-3307f0a5e77a.png)

Code in question:

https://github.com/ampproject/amp-wp/blob/5e096963ba6662f59c51246a328d7bbc1627d60c/assets/src/stories-editor/blocks/amp-story-page/edit.css#L153-L162

It looks like changing the selector `.edit-post-layout[data-block-name="core/image"] .edit-post-header-toolbar__block-toolbar .block-editor-block-toolbar > .components-toolbar` to `.edit-post-layout[data-block-name="core/image"] .edit-post-header-toolbar__block-toolbar .block-editor-block-toolbar > .components-toolbar:nth-child(2)` resolves the issue.

**Comment by swissspidy** [comment]
@csossi Since you originally discovered it, I think you know what to look for 🙂 

Note that I made changes not only to the image block, but also to the  pullquote, embed, and video blocks. So make sure to test these as well.

**Comment by csossi** [comment]
Verified in QA
