### ISSUE TITLE
Video caption: editor and FE view don't match

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2583]
The alignment is off:

Editor:
<img width="399" alt="Screenshot 2019-06-12 at 19 08 37" src="https://user-images.githubusercontent.com/3294597/59371524-8713ea80-8d45-11e9-8e44-014ee850054c.png">

FE:
<img width="384" alt="Screenshot 2019-06-12 at 19 07 59" src="https://user-images.githubusercontent.com/3294597/59371479-6a77b280-8d45-11e9-9072-f507fc3adfb3.png">

**Comment by swissspidy** [comment]
@miina The first screenshot seems to be the wrong one

**Comment by miina** [comment]
Switched!

**Comment by miina** [comment]
Instructions for testing:
- Add a Video block.
- Add caption.
- Verify that the caption's color and alignment match with the editor in the front-end.

**Comment by csossi** [comment]
Verified in QA
