### ISSUE TITLE
Poster image sizes aren't right when using Photon

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#2590]
Thanks to @westonruter for testing and finding this. This is a follow-up on #2332.

Steps to reproduce:

1. Activate [Jetpack](https://jetpack.com/) and Photon
2. Pull the `develop` branch of this AMP plugin, and build it
3. Create an AMP Story and **upload** an image for the Background Media of a page with an appropriate size, like [2000 x 2000](https://ipsumimage.appspot.com/2000x2000) (this won't work with existing images uploaded before #2509 was merged)
4. Save, go to the front-end and, and inspect the source
5. This should be automatically be assigned as the featured image, `poster-portrait-src`, `poster-landscape-src`, and `poster-square-src` on the front-end
6. Expected: those are resized to the appropriate sizes

| Type   |   Expected Size  | 
|---|---|
| poster-portrait-src | `696 x 928px` | 
| poster-landscape-src |  `928 x 696` |
| poster-square-src | `928 x 928` |

7. Actual: the images that Photon produces for those aren't the right size:

| Type   |   Actual Size  | 
|---|---|
| poster-portrait-src | `349 x 466px` ([image](https://i2.wp.com/dev-westonruter.pantheonsite.io/wp-content/uploads/2019/06/downasaur.jpg?resize=696%2C928&amp;ssl=1)) |
| poster-landscape-src | `621 x 466` ([image](https://i2.wp.com/dev-westonruter.pantheonsite.io/wp-content/uploads/2019/06/downasaur.jpg?resize=928%2C696&amp;ssl=1) |
| poster-square-src | `466 x 466` ([image](https://i2.wp.com/dev-westonruter.pantheonsite.io/wp-content/uploads/2019/06/downasaur.jpg?resize=928%2C928&amp;ssl=1)) |

Related to #2595

**Comment by westonruter** [comment]
> 3\. Create an AMP Story, and add an image for the Background Media of a page with an appropriate size, like [1400 x 1400](http://lorempixel.com/1400/1400/technics/)

The image size should be at least 2000x2000 to successfully test the image size resizing. The `amp_story_page` image size is defined as having a 1440 height, so a 1400x1400 image is too small to test.

Once you've supplied an image that is 2000 pixels high, and it has been assigned as _both_ the featured image and the story background image, then you should see:

1. Expected image sizes are used for posters, and are pointing to the Photon CDN.  Currently this is _not happening_  as the images are half the expected dimensions.
2. Expected image size is used for the background image `src` and it is pointing to the Photon CDN. Currently this is _not happening_ as the image is the `full` size and loading from origin as opposed to the Photon CDN.

**Comment by kienstra** [comment]
>The image size should be at least 2000x2000 to successfully test the image size resizing. The amp_story_page image size is defined as having a 1440 height, so a 1400x1400 image is too small to test.
Sure, that's [changed now](https://github.com/ampproject/amp-wp/issues/2590#issue-4553603860.

**Comment by westonruter** [comment]
@kienstra Humm, I'm not actually able to reproduce this. Can you? When I upload an 2448⨉3264 image and set it as the featured image, I see when previewing a story:

```html
<amp-story
	standalone
	publisher-logo-src="https://i2.wp.com/weston.ruter.net/wp-content/uploads/2018/12/cropped-00100sPORTRAIT_00100_BURST20171116114919116_COVER-cropped.jpg?fit=32%2C32&amp;ssl=1"
	publisher="Weston Ruter"
	title="Downasaur"
	poster-portrait-src="https://i0.wp.com/weston.ruter.net/wp-content/uploads/2019/06/westonruter-and-downasaur.jpg?resize=696%2C928&amp;ssl=1"
	poster-square-src="https://i0.wp.com/weston.ruter.net/wp-content/uploads/2019/06/westonruter-and-downasaur.jpg?resize=928%2C928&amp;ssl=1"
	poster-landscape-src="https://i0.wp.com/weston.ruter.net/wp-content/uploads/2019/06/westonruter-and-downasaur.jpg?resize=928%2C696&amp;ssl=1"
>
```

Each of the images have the expected pixel dimensions.

Perhaps you were grabbing the dimensions when looking with DevTools open and the image being zoomed out?

**Comment by kienstra** [comment]
**Don't see this anymore either**

Hi @westonruter,
Yeah, I don't see this anymore either.

For example, on this [test story](http://ryankienstra.staging.wpengine.com/stories/423) on a site using Jetpack, the `poster-*` images have the right size:

<img width="1225" alt="resize-attributes" src="https://user-images.githubusercontent.com/4063887/60061211-cd5c3880-96b9-11e9-865f-aa093de8cada.png">


| Type   |   Actual Size  | 
|---|---|
| poster-portrait-src | `696 x 928` ([image](https://i2.wp.com/ryankienstra.staging.wpengine.com/wp-content/uploads/2019/06/story-2000x2000-4.png?resize=696%2C928)) |
| poster-landscape-src | `928 x 696` ([image](https://i2.wp.com/ryankienstra.staging.wpengine.com/wp-content/uploads/2019/06/story-2000x2000-4.png?resize=928%2C696) |
| poster-square-src | `928 x 928` ([image](https://i2.wp.com/ryankienstra.staging.wpengine.com/wp-content/uploads/2019/06/story-2000x2000-4.png?resize=928%2C928)) |

**Comment by kienstra** [comment]
**Closing**

If it's alright, I'm closing this. We can reopen it if someone can reproduce it.
