### ISSUE TITLE
Image as Background Media isn't resized when using Photon

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#2595]
Steps to reproduce:
1. Activate [Jetpack](https://jetpack.com/) and Photon
2. Pull the `develop` branch of this AMP plugin, and build it
3. Create an AMP Story, and **upload** an image for the Background Media of a page with height taller than `1440px`, like [3000 x 4000](https://ipsumimage.appspot.com/3000x4000) (this won't work with existing images uploaded before #2509 was merged)
4. Save, go to the front-end and, and inspect the source
5. Expected: the image as background media should have been resized down to a height of `1440px` via #2509 
6. Expected: the src should be for the Photon CDN
6. Actual: the image isn't resized at all, and its URL is from the origin:

`https://example.com/wp-content/uploads/2019/06/downasaur.jpg`

<img width="1215" alt="image-not-resized-down" src="https://user-images.githubusercontent.com/4063887/59377709-68e3c580-8d18-11e9-965a-d56e6dcce130.png">

Related to #2332 and #2590

**Comment by westonruter** [comment]
Also, the `src` for the image should be pointing to the Photon CDN. Currently it is incorrectly still pointing to the origin.

**Comment by westonruter** [comment]
The underlying issue here is that we're storing `amp-img` in the `post_content`. Because oft his, Photon isn't seeing it when it runs [`\Jetpack_Photon::parse_images_from_html()`](https://github.com/Automattic/jetpack/blob/73fa66fbe91efd07907c8a5c2cb0d5b053689049/class.photon.php#L237-L251).

So the fix here may be to update the regex in Jetpack to be made AMP-compatible.

**Comment by westonruter** [comment]
This patch fixes the problem, at least for the CDN:

```diff
--- a/wp-content/plugins/jetpack/class.photon.php
+++ b/wp-content/plugins/jetpack/class.photon.php
@@ -237,7 +237,7 @@ class Jetpack_Photon {
 	public static function parse_images_from_html( $content ) {
 		$images = array();
 
-		if ( preg_match_all( '#(?:<a[^>]+?href=["|\'](?P<link_url>[^\s]+?)["|\'][^>]*?>\s*)?(?P<img_tag><img[^>]*?\s+?src=["|\'](?P<img_url>[^\s]+?)["|\'].*?>){1}(?:\s*</a>)?#is', $content, $images ) ) {
+		if ( preg_match_all( '#(?:<a[^>]+?href=["|\'](?P<link_url>[^\s]+?)["|\'][^>]*?>\s*)?(?P<img_tag><(?:amp-)?img[^>]*?\s+?src=["|\'](?P<img_url>[^\s]+?)["|\'].*?>){1}(?:\s*</a>)?#is', $content, $images ) ) {
 			foreach ( $images as $key => $unused ) {
 				// Simplify the output as much as possible, mostly for confirming test results.
 				if ( is_numeric( $key ) && $key > 0 )
```

**Comment by westonruter** [comment]
This is resulting in an `amp-img` like:

```html
<amp-img layout="fill" src="https://i2.wp.com/example.com/wp-content/uploads/2019/06/downasaur.jpg?w=1000&amp;ssl=1" data-recalc-dims="1" class="amp-wp-6ed12b8"></amp-img>
```

The `w=1000` is somewhat troubling still. The underlying `full` size image is 3264px tall, but the linked image with `w=1000` is only 1333px tall. It should be 1440px tall, per:

https://github.com/ampproject/amp-wp/blob/f4f364ad4b4eb125e068dd2b006f0a86747ea4a6/includes/class-amp-story-post-type.php#L234-L235

This is due to my theme having a `$content_width` set to 1000. 

If I override the `$content_width` via:

```php
add_action( 'wp', function() {
	if ( is_singular( 'amp_story' ) ) {
		$GLOBALS['content_width'] = 1000 * 10;
	}
} );
```

Then it bumps the param to `w=10000` which has the effect of serving the `full` size.

What is needed is for the image to have `h=1440` added instead of the `w` param, since it is the _height_ that needs to be constrained for this image size.

**Comment by westonruter** [comment]
I've opened a PR to fix this in Jetpack: https://github.com/Automattic/jetpack/pull/12821

It can be tested via that PR, so I'll move this to Ready for QA, but it will need to be tested by a developer (like @kienstra).

**Comment by kienstra** [comment]
Thanks, @westonruter! I'll test that PR.

**Comment by kienstra** [comment]
**Following Up On Background Image Without Photon**
*Saw Original Issue On Test Story, But Couldn't Reproduce*

Hi @westonruter,
Great to see you this past week!

This comment is following up on the issue you mentioned in Slack with the story background image not getting the proper size.

This doesn't relate to this issue directly, as it doesn't involve Photon. The [story-test environment](https://story-test-wordpress-amp.pantheonsite.io) isn't using Jetpack.

If it's alright, I temporarily restored the test story you mentioned from the trash, and saw the same issue you brought up.

The background image wasn't resized:

<img width="1107" alt="doesn't-end-right" src="https://user-images.githubusercontent.com/4063887/60059800-98e57e00-96b3-11e9-875b-d309ba9c0d40.png">

But for some reason I couldn't reproduce that on that same [story-test staging site](https://story-test-wordpress-amp.pantheonsite.io/?post_type=amp_story&p=2299&preview=true&_thumbnail_id=2094). Maybe something changed in the meantime.

Steps I took:
1. Create a new story
2. For the 1st page's 'Background Media,' select the image [PIA19048_realistic_color_Europa_mosaic_alt.jpg](https://story-test-wordpress-amp.pantheonsite.io/wp-content/uploads/2019/06/PIA19048_realistic_color_Europa_mosaic_alt.jpg):

<img width="1066" alt="this-image" src="https://user-images.githubusercontent.com/4063887/60059486-625b3380-96b2-11e9-95b5-30c59217fd88.png">

3. Save the post and view it [on the front-end](https://story-test-wordpress-amp.pantheonsite.io/?post_type=amp_story&p=2299&preview=true&_thumbnail_id=2094)

4. As expected, the image ends in `1440.jpeg`, as it was resized down:

<img width="1205" alt="image-resized" src="https://user-images.githubusercontent.com/4063887/60059651-f7f6c300-96b2-11e9-9e1c-e4b54870c20d.png">

Also, I tried to reproduce this using the same test story you mentioned (temporarily restored from the trash). 

The first page that you mentioned still had the issue, though I didn't edit that.

But when I added the same background image on the second page, it was resized as expected:

<img width="1348" alt="resized-here" src="https://user-images.githubusercontent.com/4063887/60060057-8cadf080-96b4-11e9-8981-b9c1760716c8.png">

Thanks, Weston!

**Comment by kienstra** [comment]
**Jetpack PR Works As Expected**

>I've opened a PR to fix this in Jetpack: Automattic/jetpack#12821

>It can be tested via that PR, so I'll move this to Ready for QA, but it will need to be tested by a developer (like @kienstra).

Hi @westonruter,
Sorry for the delay. Your [Jetpack PR](https://github.com/Automattic/jetpack/pull/12821) deployed to a [test site](http://dev-kienstra.pantheonsite.io/stories/heres-a-story/) with Photon looks to fix this issue.

With [that PR](https://github.com/Automattic/jetpack/pull/12821), the images appear with `?h=1440`, as expected:

<img width="1197" alt="proper-size-here" src="https://user-images.githubusercontent.com/4063887/60231130-dc7beb80-985d-11e9-9141-75d0ffa9a4ec.png">

Here's the test story: https://dev-kienstra.pantheonsite.io/stories/heres-a-story/

**Comment by westonruter** [comment]
> But for some reason I couldn't reproduce that on that same [story-test staging site](https://story-test-wordpress-amp.pantheonsite.io/?post_type=amp_story&p=2299&preview=true&_thumbnail_id=2094). Maybe something changed in the meantime.

@kienstra Please try uploading a new photo. I just did so with an image that is 4567x3421. I uploaded the image to the media library and then set it as the background image. The result is  https://story-test-wordpress-amp.pantheonsite.io/stories/4567x3421/ with an unexpected `src` that does not constrain the height  to 1440px:

```html
<amp-img layout="fill" src="https://story-test-wordpress-amp.pantheonsite.io/wp-content/uploads/2019/06/4567x3421.png" class="amp-wp-fe26396"></amp-img>
```

_But_ if I then reload the editor and add a new story page and then select that same uploaded image as the background, the new image gets added as:

```html
<amp-img layout="fill" src="https://story-test-wordpress-amp.pantheonsite.io/wp-content/uploads/2019/06/4567x3421-1922x1440.png" class="amp-wp-549f0cb"></amp-img>
```

I believe the problem is that the `upload-attachment` Ajax action is not being included in the logic here:

https://github.com/ampproject/amp-wp/blob/3e89b9cfe36e9c952bbc7b7fd2ec56da4a9c165c/includes/class-amp-story-post-type.php#L1547

**Comment by kienstra** [comment]
Hi @westonruter, sure I'll try that today with a new photo.

**Comment by kienstra** [comment]
**Reproduced the issue with newly-uploaded image**

Hi @westonruter,
Thanks, like you mentioned, I also saw this issue with a newly-uploaded image:

<img width="1436" alt="background-image-here" src="https://user-images.githubusercontent.com/4063887/60389143-702e0180-9a82-11e9-9dc6-a7a795d22f9a.png">

I followed the [steps here](https://github.com/ampproject/amp-wp/issues/2595#issuecomment-505228965), but in step 2, I uploaded [an image](https://via.placeholder.com/2000), instead of selecting one from the Media Library.

I'll work on this, but tomorrow might be the earliest I could start if that's alright.

**Comment by swissspidy** [comment]
@kienstra @westonruter What's the current status of this? Can this be closed? Or is it still a todo?

Asking because the issue is open but in the QA column on the board.

**Comment by kienstra** [comment]
Hi @swissspidy, sorry, I should have moved this into QA.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this, using the [steps to reproduce here](https://github.com/ampproject/amp-wp/pull/2723#issue-293581445)?

Thanks, hope you had a great Canada Day.

**Comment by csossi** [comment]
Verified in QA
