### ISSUE TITLE
Text block with background opacity is doubled

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2606]
When adding a Text block with a background of say 50%, the result is an opacity of ~75% because they are getting doubled up:

<img width="775" alt="Screenshot 2019-06-12 at 20 27 33" src="https://user-images.githubusercontent.com/841956/59376536-96e4fc00-8d50-11e9-976e-78328bec9670.png">

It should rather look like this:

<img width="771" alt="Screenshot 2019-06-12 at 20 27 37" src="https://user-images.githubusercontent.com/841956/59376541-99dfec80-8d50-11e9-92e1-79b25bcae8df.png">

See #2591 for what was thought to be a fix, but it had to be reverted (#2601) because it caused problem with `amp-fit-text`.

**Comment by miina** [comment]
Instructions for testing:
1. Add a Text block.
2. Increase the height quite a bit.
3. Assign background and background opacity.
4. Verify that the background color (and opacity) is even across the whole block.

**Comment by csossi** [comment]
Verified in QA
