### ISSUE TITLE
Unable to type in text blocks in Safari

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2612]
When in Safari - all text blocks do not display text when typing, and do not update from the helper text.

This is not impacting the "code" block, however.

**Comment by miina** [comment]
Instructions for testing:
1. Use Safari.
2. Add Text block.
3. Verify that you can type inside the Text block.
4. Verify that you can drag the Text block.
5. Repeat the same with a few other blocks which allow typing, such as quote block, code block.
6. Verify that you can drag other types of blocks, such as Image block, Video block, Title, Date, Author blocks.

**Comment by csossi** [comment]
Verified in QA
