### ISSUE TITLE
Video Selection - Incorrect Video in Editor as Background Media

### ISSUE THREAD

**Issue by csossi** [ampproject/amp-wp#2616]
Steps to reproduce

- selected the small story_video_dog.mp4 as Background Media.
- appeared fine in editor (look at that dog go!):
![image](https://user-images.githubusercontent.com/16945664/59396468-e4fcfe00-8d56-11e9-9e01-748c18828401.png)
- decided to Change Media
- selected video IMG_20190429_130647_exported_stabilized_1524510947523174136.mp4 (fountain) from Media Library
- appeared in editor with warning/recommendation:
![image](https://user-images.githubusercontent.com/16945664/59396547-4de47600-8d57-11e9-9b82-ecc96be3802f.png)
- so then decided to Change Media BACK to the originally selected "dog" video
- change didn't take effect in editor:
![image](https://user-images.githubusercontent.com/16945664/59396602-8e43f400-8d57-11e9-9879-26a0fa7c1af0.png)

NOTE: Preview DOES show the correct "doggy" video - it's just not right in the editor

**Comment by westonruter** [comment]
This is expected actually. The doggy video has a featured image set, and it populated the poster image automatically upon selection. Once a poster is set, it would not get automatically overridden when selecting another video, especially in this case where there is no featured image set on the video.

**Comment by swissspidy** [comment]
I don't think this is about the poster.

If I understood correctly, the goal was to replace the actual background video again, but nothing happened.

**Comment by swissspidy** [comment]
Was able to reproduce this.

**Comment by csossi** [comment]
fyi, the poster image "rule" makes sense - but this is about a background video not being replaced in the Editor (use case being a user simply changes their mind about a video they selected)

**Comment by swissspidy** [comment]
@csossi The issue should be fixed now. Since you originally reported it, I assume you know what to look for 🙂

**Comment by csossi** [comment]
Verified in QA
