### ISSUE TITLE
Lack of bottom padding on text block

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2620]
Adding a Text block with a background color shows that there is an apparent lack of bottom padding:

![image](https://user-images.githubusercontent.com/134745/59451833-3f32a900-8dc1-11e9-9ac2-b102b2986258.png)

Selecting text shows it going outside of its container:

![image](https://user-images.githubusercontent.com/134745/59451916-74d79200-8dc1-11e9-8855-fa80b99b412e.png)

This is not exhibited on the frontend:

![image](https://user-images.githubusercontent.com/134745/59451887-5ffafe80-8dc1-11e9-8581-7e7d354e19a3.png)

This is the same whether fit-text is enabled or not.

**Comment by miina** [comment]
Note:
Related to this is also an issue with resizing a rotated block when amp-fit-text is not on. Will aim to fix this issue within it as well.

<img width="463" alt="Screenshot 2019-06-14 at 02 11 30" src="https://user-images.githubusercontent.com/3294597/59475911-5ec3e300-8e4e-11e9-9dbc-10ccbfe4b583.png">

**Comment by csossi** [comment]
Verified in QA
