### ISSUE TITLE
Text block with fit text can wrap on load and overflow container until interacted with

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2621]
I created a Text block like so:

![image](https://user-images.githubusercontent.com/134745/59455711-9fc5e400-8dc9-11e9-8c3d-e6dadf93f8cc.png)

Upon reloading the editor, it appears as:

![image](https://user-images.githubusercontent.com/134745/59455750-ac4a3c80-8dc9-11e9-8cea-63af06074729.png)

But when I click to edit the text, then it reflows as expected:

![image](https://user-images.githubusercontent.com/134745/59455795-c552ed80-8dc9-11e9-854c-01bd1a0b17ca.png)

Reloading the page brings back the original overflow appearance.

The underlying block markup is:

```html
<!-- wp:amp/amp-story-text {"placeholder":"Write text…","tagName":"h1","align":"center","textColor":"very-dark-gray","backgroundColor":"vivid-cyan-blue","opacity":70,"autoFontSize":37,"positionTop":12.66,"positionLeft":11.59} -->
<amp-story-grid-layer template="vertical" data-block-name="amp/amp-story-text"><div class="amp-story-block-wrapper" style="position:absolute;top:12.66%;left:11.59%;width:76.22%;height:10.85%" animate-in="rotate-in-left" animate-in-delay="1801ms" animate-in-duration="700ms"><h1 style="background-color:rgba(6, 147, 227, 0.7);text-align:center;display:flex" class="wp-block-amp-amp-story-text has-text-color has-background has-very-dark-gray-color" id="aeecffc1-2be7-469b-ba5c-a64a71d03298"><amp-fit-text layout="flex-item" class="amp-text-content">Union Station!</amp-fit-text></h1></div></amp-story-grid-layer>
<!-- /wp:amp/amp-story-text -->
```

**Comment by westonruter** [comment]
When removing `vertical-align:middle` from:

https://github.com/ampproject/amp-wp/blob/0172fbaabea895ce58b1b75bb41ed1e3310994c3/assets/src/stories-editor/blocks/amp-story-text/edit.css#L56-L60

This improves things _marginally_ going from:

![image](https://user-images.githubusercontent.com/134745/59456662-b3724a00-8dcb-11e9-84d7-295c913822a2.png)

To:

![image](https://user-images.githubusercontent.com/134745/59456719-d0a71880-8dcb-11e9-85d1-2b339122f516.png)

But notice contained `p.wp-block-amp-amp-story-text` is still higher than the containing `.wp-block-amp-story-text-wrapper`. Here it is set to `50px` but it should be `56px` to account fo rthe height of the contained `p`, since `42 + 7 + 7`:

![image](https://user-images.githubusercontent.com/134745/59457276-fbde3780-8dcc-11e9-8a61-dd7a7cc3c183.png)

**Comment by westonruter** [comment]
A further problem caused by this is the text overflows the bottom of the element, making the bottom edge not accessible for dragging.

**Comment by kienstra** [comment]
Thanks for all of the details here. I'm looking at this now.

**Comment by kienstra** [comment]
It looks like on clicking the Text block, its `autoFontSize` attribute changes from `39` to `37`. Though I'm not sure yet if this is the cause of the problem:

![auto-font-size](https://user-images.githubusercontent.com/4063887/59471020-5bedd180-8dff-11e9-85ad-9f57ab283e19.gif)

**Comment by kienstra** [comment]
Opening a WIP PR for this now.

**Comment by csossi** [comment]
Verified in QA
