### ISSUE TITLE
Alignment not working for meta blocks when amp-fit-text Off

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2629]
The alignment doesn't seem to be working for the following blocks:
- Author
- Title
- Date

Note that this happens only when amp-fit-text is turned off.

To reproduce:
- Create any of the blocks mentioned above.
- Turn "Automatically fit text to container" setting off.
- Try to align.

<img width="452" alt="Screenshot 2019-06-14 at 12 40 57" src="https://user-images.githubusercontent.com/3294597/59503822-b0498d80-8ea1-11e9-9623-4d31c8cb2228.png">

**Comment by csossi** [comment]
Switched off auto-fit and Title block appeared as:
![image](https://user-images.githubusercontent.com/16945664/59519224-5fcc3300-8e95-11e9-9349-6253d814aa16.png)

**Comment by westonruter** [comment]
> Switched off auto-fit and Title block appeared as:

I think this is expected, because the text no longer auto-fits. So it would be up to you to make the height taller to fit the text yourself.

**Comment by csossi** [comment]
ok, thanks @westonruter 

Verified in QA
