### ISSUE TITLE
Investigate Text block regressions

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2630]
Looks like multiple regressions were caused for Text block by:
1. Vertical centering.
2. Dragging the whole block.

Would be good to investigate if there are simpler ways to achieve the same goals to make all the padding and border considerations more manageable.

Currently, we have to add and subtract the draggable area borders and the paddings in various places and all this makes the logic quite confusing. Perhaps this needs another look.

**Comment by swissspidy** [comment]
Agreed that there's quite some complexity around this block now. This makes it harder to maintain the code there. Would be good to look into is for 1.2.1 or 1.3.

**Comment by miina** [comment]
Note that #2863 reduces the complexity quite a bit by reverting the extra border calculations.
