### ISSUE TITLE
Block IDs sometimes start with a number

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2631]
I just ran into an issue where a block's ID on the frontend was starting with a number. This is not allowed in HTML and specifically in AMP Stories breaks things like animations.

We use [`uuid()`](https://www.npmjs.com/package/uuid) to automatically generate these IDs.

Possible fix:

Create new `getUniqueId()` helper function. This function calls `uuid()` in a loop until it does not start with a number.

Then, we'd use that helper function everywhere we currently import `uuid/v4` directly (3 instances at the moment).

**Comment by westonruter** [comment]
> Create new `getUniqueId()` helper function. This function calls `uuid()` in a loop until it does not start with a number.

Alternatively, we could just always replace the first character with a letter if it is a number.

> I just ran into an issue where a block's ID on the frontend was starting with a number. This is not allowed in HTML and specifically in AMP Stories breaks things like animations.

It should actually be allowed now, per the [HTML 5 spec](https://www.w3.org/TR/html5/dom.html#element-attrdef-global-id):

> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

Apparently AMP Stories doesn't like it though.

**Comment by swissspidy** [comment]
Not really much that can be QA'd here, as this is is quite an edge case. Moving to "Ready for Merging"
