### ISSUE TITLE
Block error when using "/" shortcut

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2632]
This might be an issue in Gutenberg 5.9.

1. Create a new page
2. Type `/title` or any other block name in the already added text block
3. See the broken page.

The error happens within `insideSelectWithDataAlign` in Gutenberg. That HOC filters the `BlockListBlock`. For some reason, it gets a weird set of props:

![Screenshot 2019-06-14 at 16 25 46](https://user-images.githubusercontent.com/841956/59518177-6d99ac80-8ec5-11e9-9537-6410ce0ca2dd.png)

The `clientId` in that screenshot seems to be the one from the existing text block.

Interestingly, this crash only seems to happen with the pre-existing text block on the page. Once you delete that text block and add a new one, `/` works fine.

**Comment by swissspidy** [comment]
While #2633 addresses this for the most use cases, the underlying issue needs to be fixed in Gutenberg.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this?

1. Create a new story
2. Don't use the default Text block
3. Add a new Text block:

<img width="1021" alt="text-block" src="https://user-images.githubusercontent.com/4063887/59525791-e0daf880-8e9c-11e9-95dd-e2fed5a59912.png">

4. Enter `/title`
5. Click the 'Story Title' block
6. Expected: this adds a 'Story Title' block
7. Repeat steps 3-4 for a few different block types

**Comment by csossi** [comment]
Verified in QA
