### ISSUE TITLE
AMP Story Latest Stories and WP Embed blocks display differently in non-AMP posts

### ISSUE THREAD

**Issue by ernee** [ampproject/amp-wp#2636]
Congrats on 1.2 RC1! 

Giving stories a try and I experienced display disparities with the non-AMP version of posts when using the _Latest Stories_ and _WordPress Embed_ blocks. The issue looks to occur in both _Transitional_ and the new _Stories_ only mode (no _Website_). I'm using an AMP compatible default theme (Twenty Nineteen).

**AMP Latest Stories and WP Embed in AMP post**

![AMP Latest Stories and WP Embed in AMP post](https://user-images.githubusercontent.com/8108643/59541937-dc95f600-8f03-11e9-933e-501941794dd1.png)

**AMP Latest Stories and WP Embed in non-AMP post**

![AMP Latest Stories and WP Embed in non-AMP post](https://user-images.githubusercontent.com/8108643/59541988-1830c000-8f04-11e9-96ec-215f14e3b406.png)

The blocks in the post editor also show some display variations: 

![AMP Latest Stories and WP Embed Block in Editor](https://user-images.githubusercontent.com/8108643/59542221-04398e00-8f05-11e9-973f-d3a50df43729.png)

**Comment by westonruter** [comment]
Are these images that you uploaded after trying 1.2-RC1 or before? It could be because the image sizes weren't generated.

**Comment by westonruter** [comment]
I bet if you regenerate the image sizes then the two would look the same.

**Comment by ernee** [comment]
Hi @westonruter, 

I uploaded the images before 1.2-RC1, but noticed the display difference in 1.2-beta2. With that said, regenerating the images worked for both the post front end and editor blocks. Thanks!

**Comment by swissspidy** [comment]
Closing this now as it has been resolved.

Thanks for testing!
