### ISSUE TITLE
AMP Story link sharing issues in particular browsers

### ISSUE THREAD

**Issue by ernee** [ampproject/amp-wp#2637]
When using the link sharing functionality for an AMP story, I experienced the following in different browsers:

1) In Chrome and Opera, the story link is copied successfully
2) In Firefox, the story link isn't copied successfully
3) In Safari, the story sharing icon opens the following menu:
![Safari AMP story link sharing ](https://user-images.githubusercontent.com/8108643/59542969-d22a2b00-8f08-11e9-8611-babfc74447ea.png)

**Comment by westonruter** [comment]
This seems like it would be an issue in AMP itself, not the plugin. Please check in another AMP Story, like this one from the Washington Post: https://www.washingtonpost.com/graphics/2019/world/amp-stories/hong-kong-protests/

**Comment by ernee** [comment]
Yes, I also experience the same with the Washington Post AMP story.

**Comment by westonruter** [comment]
It appears you are testing these browsers on MacOS as opposed to a mobile device, correct?

It looks like the Firefox issue is captured in https://github.com/ampproject/amphtml/issues/17023

Please report the Safari issue on the amphtml repo if not there already. Thanks!

**Comment by ernee** [comment]
Yes, I was using MacOS primarily for testing the browsers. I don't have an Apple device, but it appears like the same might be happening in iOS per simulator testing. Made an issue here: https://github.com/ampproject/amphtml/issues/22851
