### ISSUE TITLE
Navigating back to post (and post editor) from AMP Story

### ISSUE THREAD

**Issue by ernee** [ampproject/amp-wp#2638]
After navigating to a story from a  _Latest Stories_ or  _WordPress Embed_ block in a post or "View Story" links from the editor, to return back to the original post or editor one needs to use the browser's back button. 

**Proposal:** it may be helpful to automatically open separate tabs for these cases or include a way to navigate back to the origin from the story.

**Comment by westonruter** [comment]
Relates to the ability to add a sidebar to stories, as perhaps there could be a link back to the previous URL: https://github.com/ampproject/amp-wp/issues/2639

Also relates to the bookend: https://github.com/ampproject/amp-wp/issues/2442
