### ISSUE TITLE
Add sidebar to AMP Story pages

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2639]
- [ ] Register a new nav menu location for AMP Stories
- [ ] Add `amp-sidebar` with the `wp_nav_menu()` call to the PHP template

Needs more discussion.

**Comment by swissspidy** [comment]
https://github.com/ampproject/amphtml/issues/16532 has some examples of this. From what I can see, it seems that some customization might be wanted there, e.g. with colors and showing the site logo.

**Comment by swissspidy** [comment]
Another use case for the sidebar: a table of contents. See #2645.

**Comment by swissspidy** [comment]
Docs: https://amp.dev/documentation/components/amp-sidebar/?format=stories#sidebar-for-stories

Request for it on Slack: https://amphtml.slack.com/archives/C9ARUE6Q6/p1565619709085400

**Comment by cathibosco** [comment]
It would be useful for navigating back to a publisher's site, or to an archive stories page, or to next story, or to related stories....

**Comment by westonruter** [comment]
> It would be useful for navigating back to a publisher's site, or to an archive stories page, or to next story, or to related stories....

Some of these would be better suited for [the bookend](https://amp.dev/documentation/components/amp-story/#bookend:-amp-story-bookend) (#2442)
