### ISSUE TITLE
A value for the logo field is required.

### ISSUE THREAD

**Issue by LanaPummill** [ampproject/amp-wp#2643]
I have changed my image to make sure it is the right size. I have looked over settings. The error isn't for my entire site. It is only showing up on 3 pages. 

A value for the logo field is required.

What do I do??? I'm frustrated beyond belief.

**Comment by westonruter** [comment]
Please share the URLs for the three AMP pages that have the problem.

**Comment by LanaPummill** [comment]
https://findinginspirationinthechaos.blog/2018/08/19/im-not-handling-this-well/amp/
https://findinginspirationinthechaos.blog/2018/10/01/words-cut-like-a-knife/amp/
https://findinginspirationinthechaos.blog/2018/09/01/every-day-life-struggling-to-find-inspiration/amp/

**Comment by westonruter** [comment]
I can see this is coming from the Schema.org markup added by the Yoast plugin.

I suggest contacting Yoast for support about this: https://wordpress.org/support/plugin/wordpress-seo/

The underlying cause seems to be that you haven't selected a featured image for the post.

**Comment by westonruter** [comment]
You may need to supply a logo and/or site icon for your site in the Customizer. You say the the error is regarding the logo, but I don't see that specifically in the testing tool: https://search.google.com/structured-data/testing-tool/

Anyway, as you make changes you can use that tool to check to see if the issue is fixed.

**Comment by LanaPummill** [comment]
I already have a logo and site icon in my Customizer

**Comment by westonruter** [comment]
Ok, please contact Yoast about what their plugin is generating.

**Comment by westonruter** [comment]
@LanaPummill I'm happy to reopen this issue is it turns out to be a problem with the AMP plugin. Feel free to add additional comments with more information even though the issue is closed. Please don't open a new issue (e.g. #2644).
