### ISSUE TITLE
My Issue Isn't Fixed

### ISSUE THREAD

**Issue by LanaPummill** [ampproject/amp-wp#2644]
Seriously, I didn't fix the problem and I was still asking for help and they closed my thread?

I changed my site icon/logo and it still shows 3 errors on these pages:

https://findinginspirationinthechaos.blog/2018/08/19/im-not-handling-this-well/amp/
https://findinginspirationinthechaos.blog/2018/10/01/words-cut-like-a-knife/amp/
https://findinginspirationinthechaos.blog/2018/09/01/every-day-life-struggling-to-find-inspiration/amp/

I am using the google structured data tool and I am getting this error:

A value for the image field is required.
The image field is recommended. Please provide a value if available.

**Comment by LanaPummill** [comment]
![ERROR](https://user-images.githubusercontent.com/51884728/59567199-398eca80-9030-11e9-8f5f-151a9c0f156b.jpeg)
![ERROR 2](https://user-images.githubusercontent.com/51884728/59567201-3e537e80-9030-11e9-8836-ecb6b7296550.jpeg)

**Comment by westonruter** [comment]
I told you in your previousnhttps://github.com/ampproject/amp-wp/issues/2643 that the issue is not coming from the AMP plugin. It appears to be coming from Yoast (WordPress SEO).

**Comment by westonruter** [comment]
I closed the thread because there isn't much we can do. It's something you'd need Yoast to help with.

Otherwise, as also noted on the other issue, make sure you have provided a featured image for each post to avoid the warning about image being recommended.
