### ISSUE TITLE
Move inline scripts and styles into separate files

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2647]
There are a few instances on the AMP plugin's admin pages where some necessary JS and CSS for these screens is printed inline.

In order to make these easier to maintain together with the rest of our JS and CSS, I'd suggest extracting these into their own separate files.

This is a bit of a lower priority thing, because in the future there might be some bigger UI changes anyway. Wanted to track this nonetheless :-)

**Comment by westonruter** [comment]
Yes, we'll need to do this as part of the redesign of the screens in #2316.

**Comment by westonruter** [comment]
Closing as this will be a given with #2316.
