### ISSUE TITLE
Allow plugins to allow their blocks in the Story editor

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2650]
In lieu of being able to automatically determine whether a given block will be allowed in AMP Stories, there should be a filter for plugins to explicitly indicate that certain blocks are compatible with AMP Stories.

Given this list of `ALLOWED_BLOCKS`:

https://github.com/ampproject/amp-wp/blob/9342ddab702c06ad496cd36ff1f21f30ffc12014/assets/src/stories-editor/constants.js#L102-L105

The logic here needs a filter to allow additional blocks to be allowed:

https://github.com/ampproject/amp-wp/blob/1c52a0f0a5b36acb42a7f1b0d8925193c7c07595/assets/src/stories-editor/index.js#L99-L104

This will allow other plugins to extend the Story editor with their own blocks.

**Comment by swissspidy** [comment]
At first glance this might even be doable without a filter.
