### ISSUE TITLE
Image block placeholder not draggable

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2655]
1. Create a new story.
2. Add a new image block. It should show a placeholder to upload a new image.
3. Notice that the image block is not draggable.

Compare this to the video block:

1. Add new video block. It should show a placeholder as well.
2. Notice that you can drag it everywhere on the page.

**Comment by swissspidy** [comment]
Introduced on purpose in #2385. However, only resizing should be disabled, not the dragging.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this?

Steps:
1. Create a new story

2. Add an image block, but don't add an image to it

3. Expected: you should be able to drag it:
<img width="723" alt="story-draggable" src="https://user-images.githubusercontent.com/4063887/60686736-3426e200-9e70-11e9-85ba-f519567b5150.png">

4. Select an image for the block
5. Resize and rotate it
6. Click it so the 'placeholder' view appears, not the view that show the whole image:
<img width="833" alt="placeholder-view" src="https://user-images.githubusercontent.com/4063887/60686808-8a942080-9e70-11e9-9827-b2476d53a1a5.png">

7. Expected: you should be able to drag from anywhere in the 'placeholder' view, other than the buttons

**Comment by csossi** [comment]
Verified in QA:
![image](https://user-images.githubusercontent.com/16945664/61078760-5def8400-a3ef-11e9-82be-949d88728a2d.png)
