### ISSUE TITLE
Editor halfway hidden when using browser zoom

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2662]
As reported by Alberto, the editor area is somehow halfway hidden on his site.

Video: https://cloudup.com/c6ZtNTi-6zL

The site uses a standard set of plugins like Jetpack, Atomic Blocks, Site Kit, Gutenberg, and the Hemingway.

We had a similar issue once, see #2119. This one seems to be different.

Edit:  Looks like this is related to zooming controls in the browser (Cmd+Plus, Cmd+Minus)

**Comment by miina** [comment]
Testing locally then zooming in and out sometimes hides more than just half of the page as well:
<img width="1280" alt="Screenshot 2019-06-19 at 15 57 49" src="https://user-images.githubusercontent.com/3294597/59771965-289dbd80-92ab-11e9-8dc5-0cb22789f181.png">

**Comment by miina** [comment]
Note: will start looking into this, also as a continuation of #2477.

**Comment by swissspidy** [comment]
See https://github.com/ampproject/amp-wp/pull/2680#issuecomment-505603816 for testing instructions.

The editor should break when using browser zoom controls.

**Comment by csossi** [comment]
This is fixed, but want to note that I can browser-zoom to the point where I "lose" the ability to scroll down far enough to see the page selector below the story page:
![image](https://user-images.githubusercontent.com/16945664/60665460-80ebc800-9e32-11e9-9143-9183242f2215.png)

**Comment by westonruter** [comment]
Build from today for testing: [amp.zip](https://github.com/ampproject/amp-wp/files/3379156/amp.zip) (1.2.1-alpha-20190710T045237Z-0bf1d5a7)

**Comment by westonruter** [comment]
Issue confirmed to be fixed in another support forum topic: https://wordpress.org/support/topic/amp-stories-chrome-incompatibility/#post-11721562
