### ISSUE TITLE
Incorrect URLs in story templates after renaming plugin directory

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2663]
Example:

1. Upload AMP plugin to a folder like `wp-content/plugins/amp-foo`.
2. Activate plugin and enable stories experience
3. <--- At this point, story templates will be imported.
4. Rename plugin folder to `amp` because there is a big warning in the plugin about it.
5. Notice that all URLs in the imported stories are incorrect.

---

Not sure what we can really do here. This is kinda expected behavior. It's like when you move your site to another domain and the URLs don't match anymore.

Some thoughts:

1. Import templates as late as possible, e.g. only when actually clicking on the template inserter for the first time.
2. Add button to reset templates.

In the future we'd want to unbundle templates from the plugin anyway, so not sure what's the best interim solution here.

**Comment by miina** [comment]
One option could also be importing the stories only if the plugin folder is named correctly.

**Comment by swissspidy** [comment]
That could work. The inserter would then only show the blank page option.

Given that there is already a big notice in the admin about the wrong folder name, I guess that would suffice as an indication that not everything works as expected.
