### ISSUE TITLE
Remove unnecessary file_exists() checks from plugin builds

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2670]
In order to help guide users to properly install the plugin when it has been cloned from GitHub, the plugin includes this code:

https://github.com/ampproject/amp-wp/blob/cb0c7e324f92ce5523378fee923fb7677f9acd1b/amp.php#L148-L157

As [potentially discovered](https://wordpress.org/support/topic/error-on-updating-to-the-latest-version-of-plugin/page/2/#post-11658421) on the support forum, the `file_exists()` check may return stale results that necessitate calling `clearstatcache()`. 

Nevertheless, this entire `if` statement is irrelevant from being included in plugin builds distributed from WordPress.org because we already _know_ that those files exist at build time. So we can potentially prevent a bug from happening and improve performance a _tiiiiiiny_ bit by just removing it entirely from `amp.php` during a build.

**Comment by swissspidy** [comment]
Related core ticket: https://core.trac.wordpress.org/ticket/36455

**Comment by westonruter** [comment]
It can be bumped.

**Comment by westonruter** [comment]
I prototyped this yesterday in another plugin:

https://github.com/westonruter/syntax-highlighting-code-block/blob/47d78a41084f5625f349b3de785caef8941d997d/syntax-highlighting-code-block.php#L21

https://github.com/westonruter/syntax-highlighting-code-block/blob/47d78a41084f5625f349b3de785caef8941d997d/Gruntfile.js#L85
