### ISSUE TITLE
Invalid URL like `foo@` passed through without sanitization causing AMP validation error

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2671]
When a commenter adds "foo@" as their URL, the result is an AMP validation error on the frontend:

![image](https://user-images.githubusercontent.com/134745/59897249-18d9c280-93ec-11e9-881e-254e1f0bbca1.png) ![image](https://user-images.githubusercontent.com/134745/59897280-3eff6280-93ec-11e9-8d33-21d4944b8fe2.png)

![image](https://user-images.githubusercontent.com/134745/59897319-7110c480-93ec-11e9-9b21-4c750538480a.png)

It's strange that WordPress accepts this as a “URL” in the first place, but that's beside the point.

----

Additionally, an AMP validation error occurs when a link's `href` is just `http://`. See https://wordpress.org/support/topic/malformed-url-found-for-attribute-href-in-tag-a-3/

The `href` attribute should be removed by the sanitizer.

**Comment by westonruter** [comment]
Some check is needed around:

https://github.com/ampproject/amp-wp/blob/cb0c7e324f92ce5523378fee923fb7677f9acd1b/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L845-L856

Perhaps:

```php
if ( isset( $attr_spec_rule[ AMP_Rule_Spec::VALUE_URL ] ) && false === wp_parse_url( $node->getAttribute( $attr_name ) ) ) {
    return 0;
}
```

**Comment by schlessera** [comment]
Related core ticket: https://core.trac.wordpress.org/ticket/25385

**Comment by schlessera** [comment]
It is nearly impossible to get a `false` from `wp_parse_url()` if you don't include a mis-built protocol... It happily accepts `foo@` and tells you it is a `'path'`...

![Image 2019-08-27 at 4 49 11 PM](https://user-images.githubusercontent.com/83631/63781799-9ccb9180-c8ea-11e9-9a32-3594f12ab1c8.png)

From what I can see, the AMP validation actually fails on `http://foo@`, not `foo@`. WordPress appends the protocol after the point at which we validate this value. If we would check the value with the protocol included, it would properly fail to validate already with the current code in place (as it would detect `foo@` to be the host name and then see the `@` as an invalid char).

As we can't just append a protocol to all `value_url` attributes, I think this needs an edge case solution specifically for the comment website URL, where we check this with protocol attached through hooks and sanitize accordingly.

**Comment by schlessera** [comment]
Here's a few screen caps to show what I mean regarding the protocol:
![Image 2019-08-27 at 4 53 51 PM](https://user-images.githubusercontent.com/83631/63782552-d650cc80-c8eb-11e9-8750-310f705ba198.png)
![Image 2019-08-27 at 4 54 02 PM](https://user-images.githubusercontent.com/83631/63782561-d8b32680-c8eb-11e9-8e83-f6ecb45b47f8.png)

**Comment by schlessera** [comment]
> In the latter case, wp_parse_url() does return false. So is that not suitable here?
Yes, it is. But it is not catchable within the tag&attribute sanitizer as initially proposed.

I've finished a new fix now that goes over the final comment output to sanitize the URLs there.

**Comment by schlessera** [comment]
> I think we need something general rather than something specific for comments in #3103 because it's entirely possible for someone to put a malformed URL in content:

This is already being caught, if the `http://` is part of the attribute already.

Are you talking about scrubbing the entire document for invalid `href` attributes?

**Comment by schlessera** [comment]
So, the comment-specific fix is ready here: https://github.com/ampproject/amp-wp/pull/3103

But I'm fine with working on a more general fix for all `href` attributes if you think that's more sensible.

**Comment by schlessera** [comment]
> I think we need something general rather than something specific for comments 
I'll have a look at this tomorrow then.
