### ISSUE TITLE
Picture getting cropped in landscape mode

### ISSUE THREAD

**Issue by Amanrazdan** [ampproject/amp-wp#2678]
this is while using official amp stories plugin that comes with amp

When using landscape mode for amp stories, we set the image with the default Gutenberg editor and setting the image width to 100% 

![1](https://user-images.githubusercontent.com/28403318/60020285-5de04c00-96ad-11e9-9cf1-a2371a69f7d4.JPG)

but when viewing in landscape mode image is getting automatically height cropped 

![2](https://user-images.githubusercontent.com/28403318/60020359-823c2880-96ad-11e9-8bbe-571a0b594de3.JPG)

**Comment by westonruter** [comment]
Please share the dimensions of the original image you added as a background. Actually, please share the URL for that image to test with.

Please also go to "view page source" in the browser and copy all the underlying HTML to share here (e.g. in a Gist).

**Comment by cathibosco** [comment]
Same issue is visible here too: https://cathibosco.com/stories/nikko/

Both image and text layers are not displaying as expected on desktop view.

**Comment by Amanrazdan** [comment]
Here is the link to the story that has example problem 
https://twimbit.atlancey.com/stories/test/
This is the link to image 
https://twimbit.atlancey.com/wp-content/uploads/2019/06/Picture4.png

Also while setting image width the 100% it streches out of boundry 
![image](https://user-images.githubusercontent.com/28403318/60182656-569e7700-9842-11e9-836b-7d4732b1df3c.png)
```<amp-story standalone="" supports-landscape="" publisher-logo-src="https://twimbit.atlancey.com/wp-content/uploads/2019/06/cropped-twimbit-logo-transparent-1.jpg" publisher="Twimbit" poster-portrait-src="https://twimbit.atlancey.com/wp-content/plugins/Amp-plugin/assets/images/story-fallback-poster.jpg" class="i-amphtml-element i-amphtml-layout-container i-amphtml-layout i-amphtml-story-loaded" i-amphtml-layout="container" orientation="landscape">
   <amp-story-page id="1afb2243-22db-49d8-b3aa-7d3b561614f3" class="wp-block-amp-amp-story-page amp-wp-74885c3 i-amphtml-element i-amphtml-layout-container i-amphtml-layout i-amphtml-story-page-loaded" i-amphtml-layout="container" active="" distance="0">
      <amp-story-grid-layer template="fill" class="amp-wp-47788c3 i-amphtml-element i-amphtml-layout-container i-amphtml-story-layer i-amphtml-story-grid-template-fill i-amphtml-layout" i-amphtml-layout="container"></amp-story-grid-layer>
      <amp-story-grid-layer template="vertical" data-block-name="core/image" class="i-amphtml-element i-amphtml-layout-container i-amphtml-story-layer i-amphtml-story-grid-template-vertical i-amphtml-layout" i-amphtml-layout="container">
         <div class="amp-story-block-wrapper amp-wp-5308ec9">
            <figure class="wp-block-image is-resized" id="a2788e4e-0f16-4b24-b0cc-76fedaed7274">
               <amp-img src="https://twimbit.atlancey.com/wp-content/uploads/2019/06/Picture4-1024x660.png" alt="" class="wp-image-8946 amp-wp-enforced-sizes i-amphtml-element i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-layout" width="325" height="215" layout="intrinsic" i-amphtml-layout="intrinsic">
                  <i-amphtml-sizer class="i-amphtml-sizer">
                     <img alt="" role="presentation" aria-hidden="true" class="i-amphtml-intrinsic-sizer" src="data:image/svg+xml;charset=utf-8,<svg height=&quot;215px&quot; width=&quot;325px&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; version=&quot;1.1&quot;/>">
                  </i-amphtml-sizer>
                  <img decoding="async" alt="" src="https://twimbit.atlancey.com/wp-content/uploads/2019/06/Picture4-1024x660.png" class="i-amphtml-fill-content i-amphtml-replaced-content">
               </amp-img>
            </figure>
         </div>
      </amp-story-grid-layer>
      <div class="i-amphtml-story-spinner" aria-hidden="true" aria-label="Loading video">
         <div class="i-amphtml-story-spinner-container">
            <div class="i-amphtml-story-spinner-layer">
               <div class="i-amphtml-story-spinner-circle-clipper left"></div>
               <div class="i-amphtml-story-spinner-circle-clipper right"></div>
            </div>
         </div>
      </div>
   </amp-story-page>
   <amp-story-bookend layout="nodisplay" class="i-amphtml-element i-amphtml-layout-nodisplay" i-amphtml-layout="nodisplay">
      <script type="application/json">
         {
             "bookendVersion": "v1.0",
             "shareProviders": [
                 "linkedin",
                 "whatsapp",
                 "Twitter"
             ],
             "components": [
                 {
                     "type": "heading",
                     "text": "Up Next"
                 }
         ,{ "type": "landscape", "title": "Trumps ban Huawei","url": "https://twimbit.atlancey.com/stories/trumps-ban-huawei/","image": "https://twimbit.atlancey.com/wp-content/uploads/2019/06/Slide4.jpg"}  ]
         }
      </script>
   </amp-story-bookend>
   <div class="i-amphtml-story-button-container i-amphtml-story-fwd-next next-container">
      <button class="i-amphtml-story-button-move"></button>
      <div class="i-amphtml-story-page-sentinel"></div>
   </div>
   <div class="i-amphtml-story-button-container i-amphtml-story-button-hidden prev-container">
      <button class="i-amphtml-story-button-move"></button>
      <div class="i-amphtml-story-page-sentinel"></div>
   </div>
   <div></div>
   <div></div>
</amp-story>```

**Comment by kienstra** [comment]
**Overflowing Images**


Hi @Amanrazdan,
Thanks a lot for bringing this up, and for your detailed response with the markup. 

1. In the [screenshot above](https://github.com/ampproject/amp-wp/issues/2678#issuecomment-505870680), the image overflows the AMP story page in the editor, as it's `1024x660`:

`https://twimbit.atlancey.com/wp-content/uploads/2019/06/Picture4-1024x660.png`

Maybe the plugin could better handle overflowing the page, or have some kind of notice about that. But I think we'd expect the front-end display to also be wrong, even in landscape. The image didn't fit on the AMP story page even in the editor:

<img width="1194" alt="image-overflows-story" src="https://user-images.githubusercontent.com/4063887/60930779-9d499380-a27c-11e9-9577-9d661eef7e2d.png">


2. I tried to reproduce [the first comment in this issue](https://github.com/ampproject/amp-wp/issues/2678#issue-459875793), using a [300 x 193 image](https://ipsumimage.appspot.com/300x193). 

That looked fine on the front-end in landscape, though it was stretched, as the `300px` width probably isn't meant for that width.

The only case where it got cropped was if I moved the browser up. Maybe if my display was wider, this 'cropping' would appear normally:

![moving-browser-up](https://user-images.githubusercontent.com/4063887/60930284-886c0080-a27a-11e9-9ad2-ee05fbd94de4.gif)

**Comment by swissspidy** [comment]
Closing in favor of #3498
