### ISSUE TITLE
FR: Add REST API endpoints for content and styles

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2681]
In order to enable the use of the AMP plugin in the context of WordPress being used in headless mode, we need to add endpoints in the REST API to expose the rendered AMP content and the processed styles. This way frameworks such as [Frontity](https://frontity.org/) or any other solution using WordPress as a Headless CMS can take advantage of the AMP plugin.

/cc @luisherranz, @westonruter

**Comment by westonruter** [comment]
I believe we have this is something we have an issue for already: https://github.com/ampproject/amp-wp/issues/1014

This is something that @ataylorme has also requested recently.

**Comment by luisherranz** [comment]
Awesome. Thanks guys.

An array of scripts would be useful as well:

```js
{
  ...
  content: {
    rendered: "....<iframe src="https://youtube....></iframe>",
    amp: "...<amp-youtube ...>..."
  },
  amp: {
    styles: "....",
    scripts: [
      {
        "custom-element": "amp-youtube",
        src: "https://cdn.ampproject.org/v0/amp-youtube-0.1.js"
      }
    ]
  }
}
```

**Comment by luisherranz** [comment]
@westonruter feel free to close this one in favor of #1014.

**Comment by westonruter** [comment]
Great. Please provide the above context on #1014.

**Comment by luisherranz** [comment]
Done 👍
