### ISSUE TITLE
Breaking editing experience for user role 'Author' 

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2685]
Users with role of 'Author' seem unable to preview or publish stories. See snapshots for observed results. 
<img width="1176" alt="Screen Shot 2019-06-26 at 11 59 44 AM" src="https://user-images.githubusercontent.com/506089/60150188-2dfa8b00-980a-11e9-90e6-8d8360718503.png">
<img width="1100" alt="Screen Shot 2019-06-26 at 11 59 52 AM" src="https://user-images.githubusercontent.com/506089/60150190-3357d580-980a-11e9-836b-1c615e4014c8.png">

**Comment by westonruter** [comment]
If you reload the editor after saving, do you see block validation errors? And what does the post content look like if you switch to the code view?

I suspect there is an `unfiltered_html` problem here, with the AMP markup being stripped out.

**Comment by amedina** [comment]
Yes, I do see some errors...
<img width="1526" alt="Screen Shot 2019-06-26 at 12 50 19 PM" src="https://user-images.githubusercontent.com/506089/60151878-fd6a1f80-9810-11e9-937c-9a835f1272c6.png">

And the code view:
<img width="742" alt="Screen Shot 2019-06-26 at 12 50 58 PM" src="https://user-images.githubusercontent.com/506089/60151923-238fbf80-9811-11e9-9cc7-e41a1ed9c006.png">

**Comment by westonruter** [comment]
@miina I think more AMP elements and attributes need to be Kses-whitelisted perhaps.

**Comment by miina** [comment]
Instructions for testing:
- Log in as an Author
- Verify that the functionality of creating and editing stories works as usual.

**Comment by csossi** [comment]
Currently with "Author" profile

Adding diff blocks as "author". Added a video block and selected video from media library. 
![image](https://user-images.githubusercontent.com/16945664/61176803-5538b280-a595-11e9-93fc-77feaa0876df.png)

Checked Preview. Blocks appearing as they should except for video (appearing as a blank page):
![image](https://user-images.githubusercontent.com/16945664/61176791-34705d00-a595-11e9-95c3-cfdf46a97096.png)

**Comment by miina** [comment]
@csossi Seems to work fine when I'm testing.

Could you confirm that when adding a video block you also added the poster Image for the video? Note that without adding the poster image, the video is not valid AMP and won't render.

**Comment by csossi** [comment]
Right you are, @miina - didn't see the poster message as I didn't scroll down further. "Verified in QA", but opening another related ticket re: videos
