### ISSUE TITLE
schema.org data doesn't get overriden completely

### ISSUE THREAD

**Issue by Mike-Antipov** [ampproject/amp-wp#2700]
I've added amp_post_template_metadata filter to implement my own schema, but still I see this additional bit of code:
```html
<script type="application/ld+json">{"publisher":{"logo":{"@type":"ImageObject","url":"https:\/\/smratanstage.wpengine.com\/wp-content\/themes\/presso\/images\/my-amp-metadata-logo.png","height":39,"width":229}}}</script>
```

How do I get rid of it?

**Comment by westonruter** [comment]
Please share the filter code you are using.

**Comment by Mike-Antipov** [comment]
add_filter('amp_post_template_metadata', 'schema_org_injection', 1);
	function schema_org_injection(){
		$szs = wp_get_attachment_image_src(get_post_thumbnail_id(), 'full');
		echo('<script type="application/ld+json">');
		$data = array(
			"@context" => "http://schema.org",
			"@type" => "NewsArticle",
			"mainEntityOfPage" => array (
				"@type" => "WebPage",
				"@id" => "https://www.smarteranalyst.com"
			),
			"headline" => get_the_title(),
			"datePublished" => get_the_date().'T'.get_the_time('H:i:s'),
			"dateModified" =>  get_the_modified_date().'T'.get_the_modified_time('H:i:s'),
			"author" => array (
				"@type" => "Person",
				"name" => get_the_author_meta('display_name')		
			),
			"about" => array (
					"@type" => "Corporation",
					"tickerSymbol" => $ftag
			),
			"publisher" => array (  
				"@type" => "Organization",
				"name" => "Smarter Analyst",
				"logo" => array (
				   "@type" => "ImageObject",
				   "url" => "https://www.smarteranalyst.com/wp-content/uploads/2019/02/SA-Logo-new-size-1.png",
				   "width" => 229,
				   "height" => 39
				)
			),
			 "description" => get_the_excerpt(),
			 "image" => array (
				"@type" => "ImageObject",
				"url" => get_the_post_thumbnail_url(),
				"width" => $szs[1],
				"height" => $szs[2]
			)
		);  
		echo json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
		echo('</script>');
	};

**Comment by westonruter** [comment]
I see. You should not be doing `echo` in this function. Rather, you just need to `return $data`.
