### ISSUE TITLE
Block style "broken" with the latest Gutenberg updates

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2703]
To reproduce:
- Update to the latest Gutenberg (e.g. from repo)
- Open the template Inserter
- Add the Tip template

This can be seen especially well when using narrow blocks.

Result:
<img width="355" alt="Screenshot 2019-06-28 at 12 23 21" src="https://user-images.githubusercontent.com/3294597/60336046-929b1e80-999f-11e9-8e56-817a42fea5ab.png">
<img width="1127" alt="Screenshot 2019-06-28 at 12 23 36" src="https://user-images.githubusercontent.com/3294597/60336051-95960f00-999f-11e9-91ae-1865e456acac.png">
<img width="180" alt="Screenshot 2019-06-28 at 12 25 04" src="https://user-images.githubusercontent.com/3294597/60336132-c7a77100-999f-11e9-8052-7a420dceee0b.png">

EDIT: Also the templates seem to be broken, potentially related to style changes upstream.

**Comment by miina** [comment]
Looks like the template previews look broken due to this styling here which removes our `transform`:
<img width="951" alt="Screenshot 2019-07-10 at 13 53 57" src="https://user-images.githubusercontent.com/3294597/60967162-45fa0080-a31a-11e9-946e-bc53a9a41d72.png">

**Comment by miina** [comment]
Note that this effects reordering as well.

**Comment by miina** [comment]
Instructions for testing:
- Verify that the template preview doesn't look broken.
- Verify that a text block doesn't have noticeable extra padding between the content and its borders (the padding should be around 7px and not 28px).
- Set rotation to a block, save and refresh. Verify that the block displays rotated in the editor.

**Comment by csossi** [comment]
Verified in QA
