### ISSUE TITLE
Latest Stories block Edit and ServerSideRender requests are inconsistent

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2704]
Tested with the latest Gutenberg from the repo as of today.

When trying to use the Latest Stories the following happens:
<img width="1160" alt="Screenshot 2019-06-28 at 12 14 55" src="https://user-images.githubusercontent.com/3294597/60335736-e35e4780-999e-11e9-88be-a2b8bfc0ed99.png">
<img width="1101" alt="Screenshot 2019-06-28 at 12 14 48" src="https://user-images.githubusercontent.com/3294597/60335738-e3f6de00-999e-11e9-9b7d-782b5c9eb3b0.png">

To reproduce:
- Create AMP Stories without featured image (make sure there are no other Stories or the others are drafts)
- Open any post.
- Add Latest Stories Post.

**Comment by swissspidy** [comment]
You mean latest Gutenberg as in version 6.0, or latest as in _from the GitHub repository_?

For me, the block displays fine in the editor and on the frontend. The prop type warning is also there, but that does not break anything (still should be fixed though).

**Comment by miina** [comment]
I mean the latest from the GitHub repository.

I'll debug a bit more, perhaps there are some other things that need to be in place for this to happen. Or perhaps it's just local.

**Comment by miina** [comment]
OK, finally found the reason. Basically, it displayed empty since none of the AMP Stories had a featured image. It's a requirement within `render_block_latest_stories`, however, the `getEntityRecords( 'postType', 'amp_story', latestStoriesQuery )` within the `edit.js` of the  Latest Stories block doesn't require that.

So the result in the console showed the Stories as response but the `ServerSideRender` didn't actually fetch any due to the featured image requirement, seemed like a bug.

This is a bit inconsistent behavior, also, there is really no need for fetching the stories twice, the `ServerSideRender` does that already, I guess it's being used so that we could display "No Stories found" if relevant?

Perhaps we could instead do the following:
- Remove fetching the latest stories from the `edit.js`
- Update the `render_block_latest_stories` logic so that if no stories are found it would display a message about it (and perhaps also mention that featured images are relevant, too).

This would need detecting if we're displaying in the editor or in the FE though, probably wouldn't want to display "No Stories found" in the FE. If that's not possible, we could alternatively display the default `ServerSideRender` message, or update the `ServerSideRender` in Gutenberg to allow passing messages as attributes instead of enforcing the default ones.

Alternatively, we should make the two queries consistent, although, it would make more sense to me to make fewer requests instead.

Thoughts, @swissspidy?

**Comment by swissspidy** [comment]
> Alternatively, we should make the two queries consistent, although, it would make more sense to me to make fewer requests instead.

It would be a quick fix to filter `latestStories` in `edit.js` based on whether there are featured images.

I am not really a fan of `ServerSideRender` because of the degraded UX that comes with it. I'd much rather get rid of that.

Also, `render_block_latest_stories` should not be concerned about its location.

**Comment by miina** [comment]
> I am not really a fan of ServerSideRender because of the degraded UX that comes with it. I'd much rather get rid of that.

Well, getting rid of that would probably require duplicating the FE and BE display since in the FE the data still needs to come dynamically.

> It would be a quick fix to filter latestStories in edit.js based on whether there are featured images.

👍

**Comment by westonruter** [comment]
> I am not really a fan of ServerSideRender because of the degraded UX that comes with it. I'd much rather get rid of that.

How is the UX degraded? There has to be an HTTP request either way in order to obtain the latest stories. Are you referring specifically to re-rendering from the server after changing the story count?

**Comment by swissspidy** [comment]
IMO the [`ServerSideRender` readme](https://github.com/WordPress/gutenberg/blob/01db6008fdf7b4c4e77647bb31dac8ca94a12704/packages/server-side-render/README.md) says it best:

> ServerSideRender is a component used for server-side rendering a preview of dynamic blocks to display in the editor. Server-side rendering in a block's `edit` function should be limited to blocks that are heavily dependent on existing PHP rendering logic that is heavily intertwined with data, particularly when there are no endpoints available.
> 
> ServerSideRender may also be used when a legacy block is provided as a backward compatibility measure, rather than needing to re-write the deprecated code that the block may depend on.
> 
> ServerSideRender should be regarded as a fallback or legacy mechanism, it is not appropriate for developing new features against.
> 
> New blocks should be built in conjunction with any necessary REST API endpoints, so that JavaScript can be used for rendering client-side in the `edit` function. This gives the best user experience, instead of relying on using the PHP `render_callback`. The logic necessary for rendering should be included in the endpoint, so that both the client-side JavaScript and server-side PHP logic should require a minimal amount of differences.
