### ISSUE TITLE
Intermittent build failures due to HTTP requests

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2705]
The `\AMP_Image_Dimension_Extractor_Extract_Test::test__multiple_valid_image_files()` test currently often fails because the HTTP requests don't seem to go through for the two files hosted on GitHub.

Perhaps there are some timeouts or rate limits. We should consider hosting the images elsewhere or consider increasing the default timeout in `\AMP_Image_Dimension_Extractor::fetch_images()` from the default (10 seconds) to something more like 30 seconds.

**Comment by westonruter** [comment]
It would also be nice if tests with external requests could be skipped by default to speed things up, especially on local. All the jobs could by default not do the external requests, except for one that opts-in. I recall core has a similar flag.

Additionally, it would be nice if FasterImage were able to be smarter about URLs pointing to the local filesystem to avoid the HTTP request in the first place.

**Comment by westonruter** [comment]
We should store the test image files on amp-wp.org rather than fetch them from Gists.

**Comment by swissspidy** [comment]
Skipping external HTTP tests by default is fairly easy with PHPUnit, but not really with wp-dev-lib, as it doesn't really allow for customization of the PHPUnit command.

**Comment by westonruter** [comment]
It's easy to do via an environment variable. But if needing to vary the args for `phpunit` then this should be something that support is added for.

**Comment by swissspidy** [comment]
@westonruter Here's what it looks like when it's done the same way as in core: #2716.
