### ISSUE TITLE
Consider removing inline image feature from CTA block (or improve styling)

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2706]
Apparently, the CTA block allows adding an inline image, this feature might be unnecessary for AMP Stories, we might want to consider removing it. Currently, this looks more like a bug and not a feature. We should either remove it or fix the styling to make BE and FE match and align the text better.

To reproduce:
- Add CTA block
- Add an inline image from the Toolbar's "More RichText Controls" menu.
- Add some Text, too
- Check how it looks like in the FE.
- Compare the FE and BE, it's quite different.

<img width="445" alt="Screenshot 2019-06-28 at 12 55 31" src="https://user-images.githubusercontent.com/3294597/60337686-093a1b00-99a4-11e9-93bf-db61a074c1dc.png">
<img width="543" alt="Screenshot 2019-06-28 at 12 55 19" src="https://user-images.githubusercontent.com/3294597/60337687-093a1b00-99a4-11e9-8106-bc83de4ac7d0.png">

**Comment by swissspidy** [comment]
Apparently formats like this are available for _any_ `RichText` component, including within the text block.

I think they could only be disabled globally, e.g. using code like this: 

```js
wp.richText.unregisterFormatType( 'core/image' )
```

**Comment by swissspidy** [comment]
Just added an inline image for testing and set its width to 50px.

Apparently that only changes the CSS, nothing else.

In `post_content` it looks like this (excerpt):

```
<amp-story-cta-layer class="wp-block-amp-amp-story-cta aligncenter" id="aeb5d510-efc1-43d6-ba4c-e2937a2b4c75"><a class="amp-block-story-cta__link amp-text-content has-text-color has-background" style="background-color:rgba(50, 55, 60, 1);color:#ffffff;text-align:center">Hello <img class="wp-image-55" style="width: 50px;" src="https://amp.local/wp-content/uploads/2019/04/stefan-rodriguez-1435708-unsplash-e1555077414512.jpg" alt="Alt Alt"> World</a></amp-story-cta-layer>
```

The plugin turns this into this:

```
<amp-img class="wp-image-55 amp-wp-unknown-size amp-wp-unknown-width amp-wp-unknown-height amp-wp-enforced-sizes amp-wp-ae1f13b" src="https://amp.local/wp-content/uploads/2019/04/stefan-rodriguez-1435708-unsplash-e1555077414512.jpg" alt="Alt Alt" srcset="https://amp.local/wp-content/uploads/2019/04/stefan-rodriguez-1435708-unsplash-e1555077414512.jpg 4000w, https://amp.local/wp-content/uploads/2019/04/stefan-rodriguez-1435708-unsplash-e1555077414512-273x300.jpg 273w, https://amp.local/wp-content/uploads/2019/04/stefan-rodriguez-1435708-unsplash-e1555077414512-768x844.jpg 768w, https://amp.local/wp-content/uploads/2019/04/stefan-rodriguez-1435708-unsplash-e1555077414512-932x1024.jpg 932w" width="640" height="400" layout="intrinsic"></amp-img>
```

Which seems reasonable, given that the change is made using CSS only.

The image is stretched because of some `object-fit` rule coming from somewhere. It seems that using `object-fit: contain;` would fix that.

**Comment by miina** [comment]
Instructions for testing:

- Add a CTA block
- Add an inline image from the Toolbar's "More RichText Controls" menu.
- Add some Text, too
- Verify that the image is not going over the Page's borders.
- Verify that FE and BE look similar.

**Comment by csossi** [comment]
Looks fine in BE/Editor, but doesn't match in Preview/FE

BE:
![image](https://user-images.githubusercontent.com/16945664/61239130-2ee95300-a70c-11e9-9591-462a63b5d40a.png)

FE:
![image](https://user-images.githubusercontent.com/16945664/61239151-3dd00580-a70c-11e9-91d0-1913971cb67a.png)

**Comment by miina** [comment]
Hmm, weird, the same image and the same text displays as expected locally.

Will have to debug this more to understand why it's different in the test environment.

**Comment by miina** [comment]
Note:
Couldn't find a difference locally vs in the test environment, asked @mehigh to chime in and take a look.

**Comment by miina** [comment]
Update: @mehigh will take a look tomorrow (Thursday).

**Comment by mehigh** [comment]
For me, it looks wrong in both BE & FE
BE: 
http://cloud.urldocs.com/22d57a8c04da
FE: 
http://cloud.urldocs.com/385a76deda15

The thing I've noticed causing iffiness is the top/bottom padding on the CTA layer:
http://cloud.urldocs.com/c05b493599b0
.amp-block-story-cta__link { padding: 12px 24px ...

Turning it down to `padding: 0 24px` makes it behave: http://cloud.urldocs.com/03d6a650726b
Just like 

But that's not sufficient for the FE which expands well beyond the limits:
http://cloud.urldocs.com/ad4a9bbe96f5
There's again amp-img iffiness 

I'll get back at this tomorrow with a clear head.

**Comment by mehigh** [comment]
I hope the above PR puts this to bed. Thanks for your patience!

**Comment by mehigh** [comment]
I've swapped the height by max-height and also tested this out with a tiny image and without one in both the editor and outside:
http://cloud.urldocs.com/a7b9a593566f
http://cloud.urldocs.com/e6046b23aba9

Should be good to go now.

**Comment by miina** [comment]
Closed within #2857

**Comment by miina** [comment]
Should be ready for testing again (once deployed).

Instructions for testing: https://github.com/ampproject/amp-wp/issues/2706#issuecomment-510870701

**Comment by csossi** [comment]
Verified in QA
