### ISSUE TITLE
Settings: Welcome notice should not use h1

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2707]
When visiting the settings screen for the first time, a "Welcome to AMP for WordPress" notice is displayed. That message uses an `h1`, even though there is already an `h1` on the page for the actual page title.

Suggested fix: use an `h2` for the welcome notice.

**Comment by pierlon** [comment]
Would the style of the `h1` element still apply? Here's the difference:

h1 | ![image](https://user-images.githubusercontent.com/16200219/67612848-67b5b100-f76c-11e9-9625-8b1c4963c998.png)
---|--
h2 | ![image](https://user-images.githubusercontent.com/16200219/67612854-78662700-f76c-11e9-85d2-dbe9bbf3d444.png)

**Comment by westonruter** [comment]
The smaller heading style looks fine to me.
