### ISSUE TITLE
Background color does not extend with the text when resized

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2719]
When autosizing text is toggled off, if a user changes the font larger than the block size the font extends past the block, but the background color does not extend with the text.

Similar to: https://github.com/ampproject/amp-wp/issues/2210

**Comment by MackenzieHartung** [comment]
<img width="349" alt="Screen Shot 2019-07-01 at 12 47 23 PM" src="https://user-images.githubusercontent.com/24547817/60455095-8d3e0e00-9c03-11e9-80f1-1785cfe77477.png">

**Comment by swissspidy** [comment]
I just noticed that while working on #2720.

Might be able to fix it by updating the block's `componentDidUpdate` method to also account for more attributes than just height, width, and the actual content.

**Comment by swissspidy** [comment]
**Testing Instructions**

1. Create new text block with some content
2. Change dimensions to make it rather small
3. Turn off amp-fit-text option
4. Change font size to a larger option
5. Verify that block size changes accordingl
6. Test the same behavior with "meta" blocks (story title, author, date)

**Comment by csossi** [comment]
Entered content, resized to smaller, and then switched auto-fit toggle to "off". The display defaulted to NORMAL font size, but extends beyond block border:
![image](https://user-images.githubusercontent.com/16945664/61176538-78149800-a590-11e9-8f0a-9e65860baba5.png)

It's only when I change font size that the content seems to reset to fit in block (here changed to medium):
![image](https://user-images.githubusercontent.com/16945664/61176553-a6927300-a590-11e9-8c6d-c7fea3ce578f.png)

**Comment by swissspidy** [comment]
Thanks for testing @csossi!

I've just merged a change now that should address this. Can you revisit this (after Weston has done a deployment)?

**Comment by csossi** [comment]
Verified in QA
