### ISSUE TITLE
Normal font is larger than Medium font

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2720]
When looking at the list of font sizes, it appears that Normal font size should be smaller than Medium font, but when selected Normal font size is larger than Medium.

**Comment by swissspidy** [comment]
Here's the default list of font sizes that we use:

https://github.com/WordPress/gutenberg/blob/636b7bf072a4365d5c41fec07872a81fe0247516/packages/block-editor/src/store/defaults.js#L90-L116

As for the difference int font size, it looks like we currently override it depending on whether the text is determined to be a h1, h2, or paragraph. I thought we had removed that already 🤔

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create new text block
2. Try out all the available font sizes
3. Verify that the font sizes change in according to their name, e.g. Medium should be bigger than Normal, Large bigger than Medium, etc.

**Comment by csossi** [comment]
Verified in QA
![image](https://user-images.githubusercontent.com/16945664/61176410-73e77b00-a58e-11e9-9d98-9a0dd65e8c58.png)
