### ISSUE TITLE
Text does not display in Preview/Publish the same way it does in the editor

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2721]
Text in preview is a different size than text in editor

Editor:
<img width="216" alt="Screen Shot 2019-07-01 at 4 42 23 PM" src="https://user-images.githubusercontent.com/24547817/60466196-06982980-9c21-11e9-9f29-bafb00e3b579.png">

Preview:
<img width="213" alt="Screen Shot 2019-07-01 at 4 40 50 PM" src="https://user-images.githubusercontent.com/24547817/60466175-f7b17700-9c20-11e9-94ff-4ad0e0d838cd.png">

Text wrapped in editor is not wrapped in preview

Editor: 
<img width="222" alt="Screen Shot 2019-07-01 at 4 43 49 PM" src="https://user-images.githubusercontent.com/24547817/60466218-144daf00-9c21-11e9-9a22-7d6ed9b2ca0c.png">

Preview:
<img width="253" alt="Screen Shot 2019-07-01 at 4 44 17 PM" src="https://user-images.githubusercontent.com/24547817/60466233-1adc2680-9c21-11e9-9fce-4ee58a572959.png">

**Comment by miina** [comment]
That might be expected considering the varying aspect ratio of the Stories -- unless the ratio is exactly the same there can be some differences.

However, just tested the issue with exactly the same aspect ratio in the FE as it is in the editor and looks like there are still some differences.

**Comment by miina** [comment]
Instructions for testing:

- Create a Text block
- Add some text in it (e.g. based on the original ticket example or some sentences consisting of small words or just characters).
- See the preview / FE view and set the width and height to 328x553 (the same as the editor Page's measures)
- Compare the FE and editor view and verify that the texts don't have any size differences: the width and height (the room that the content has available for amp-fit-text) and font size are the same in both editor and FE.

**Comment by csossi** [comment]
Verified in QA
