### ISSUE TITLE
Video upload does not work

### ISSUE THREAD

**Issue by vinaymahag** [ampproject/amp-wp#2727]
Repro steps:

1. Upload a video, the video thumbnail does not appear in the media library, but if you upload a single video, it is selected in the pane on the right. 
1. Tapping "Select" takes you to the "Crop image" screen; however the image is broken, so you cannot hit "Select" and you are stuck on this screen.

![image](https://user-images.githubusercontent.com/38660603/60516967-d1d1b400-9cac-11e9-8c25-8f64b3cf97b6.png)
![image](https://user-images.githubusercontent.com/38660603/60516986-dbf3b280-9cac-11e9-8249-427b6f7a371a.png)

**Comment by swissspidy** [comment]
Hi there

Thanks a lot for your report! This screen should definitely not appear when not uploading an actual image.

Is this happening using version 1.2 of the plugin, or with the current `master` build?

**Comment by vinaymahag** [comment]
I was using this link: https://story-test-wordpress-amp.pantheonsite.io/wp-admin/

**Comment by westonruter** [comment]
@vinaymahag Did you access the media uploader via the Featured Image panel:

![image](https://user-images.githubusercontent.com/134745/60518747-fcb10d80-9c96-11e9-97f5-2476f01d371f.png)

Two problems here:

1. The mov file format is not supported. You have to upload an MP4. 
2. WordPress core is failing to constrain the media type when uploading a file. Even though only images are shown in the grid, you can bypass the image type by uploading a file.

**Comment by westonruter** [comment]
Aside: Just realized that the Video block is not constraining the type fo MP4, whereas the page background media _is_ constraining to MP4 video.

**Comment by vinaymahag** [comment]
I used the background media. I am uploading a *.mov. We should tell users
that only *.mp4 is supported. Alternatively, is it possible to support
*.mov?

**Comment by swissspidy** [comment]
`.mov` is not a supported media type on the web, see https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats. One would need to transcode the video. Ideally locally on their computer, because not many webservers would have `ffmpeg` installed to do so.

And yes, we should add a warning for that.

**Comment by westonruter** [comment]
Thanks. I was also able to reproduce this issue by uploading a Text file from the media modal opened for background media:

![image](https://user-images.githubusercontent.com/134745/60520112-aee9d480-9c99-11e9-92f7-e6e163d7e4b2.png)

This is in spite of the Text file not being shown in the previously-uploaded media grid. So yeah, WordPress core is failing to constrain the file type of uploaded files. So we at least need to add an error notice upon selection if we can't prevent the selection in the first place.

**Comment by westonruter** [comment]
> `.mov` is not a supported media type on the web, see https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats. One would need to transcode the video. Ideally locally on their computer, because not many webservers would have `ffmpeg` installed to do so.

I think transcoding in the browser is going to be not practical, especially on CPU-constrained devices (as support for mobile editing is improved).

I think the best bet here is to integrate with services like Jetpack's VideoPress which not only would provide transcoding from MOV to MP4, but also (I believe) reduction in bitrate as well as extracting a  poster image. Another option is Cloudinary.

**Comment by swissspidy** [comment]
> I think transcoding in the browser is going to be not practical

I meant locally on the computer, not in the browser.

> WordPress core is failing to constrain the file type of uploaded files.

Is there a core ticket for that already?

**Comment by westonruter** [comment]
> Is there a core ticket for that already?

Yes. I've also provided more details just now: https://core.trac.wordpress.org/ticket/39625#comment:10

**Comment by westonruter** [comment]
We could preempt core fixing this by trying to force disable the button and show an error message as was originally done in #2038 to prevent selecting a image that has insufficient dimensions:

https://github.com/ampproject/amp-wp/blob/323eadb8ca3f6da3174d236f3e827a9391addd3e/assets/src/components/featured-image-select-media-frame.js#L73-L93

**Comment by kienstra** [comment]
Hi @westonruter,
If it's alright, I'm working on applying your [suggestion](https://github.com/ampproject/amp-wp/issues/2727#issuecomment-507726715) to:

>...preempt core fixing this by trying to force disable the button and show an error message as was originally done in #2038 to prevent selecting a image that has insufficient dimensions:

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Hope you're doing great.

Could you please test this, using the [5 scenarios here](https://github.com/ampproject/amp-wp/pull/2737#issuecomment-508886732)?

**Comment by csossi** [comment]
Verified in QA
