### ISSUE TITLE
STAMP preview does not work

### ISSUE THREAD

**Issue by vinaymahag** [ampproject/amp-wp#2728]
Repro steps:

1. Create a story
1. Preview the story
1. The entire page is blank; however, it might be shifted up by a page, and may be a dupe of https://github.com/ampproject/amp-wp/issues/2685 
![image](https://user-images.githubusercontent.com/38660603/60517187-3ab92c00-9cad-11e9-9a2c-2585bba14d76.png)

**Comment by westonruter** [comment]
@vinaymahag I just changed your role from author to editor, so if you re-test you should be able to determine if it is a duplicate of #2685.

**Comment by vinaymahag** [comment]
Duplicate of #2685
