### ISSUE TITLE
Ensure default text is visible on different backgrounds when adding a new text element

### ISSUE THREAD

**Issue by vinaymahag** [ampproject/amp-wp#2729]
When adding a new text element on a page with a background color/image/video, sometimes the default text isn’t visible, so it looks like nothing happened. Perhaps use the background to draw either a dark or light box around the text? In the screenshot below, the new text element is above the boat where the rocks meet the trees. It’s almost impossible to see.

![image](https://user-images.githubusercontent.com/38660603/60517849-5ffa6a00-9cae-11e9-9c47-c26749071831.png)

**Comment by swissspidy** [comment]
Related issue/card for automatically choosing colors with good contrast based on the background: https://github.com/ampproject/amp-wp/projects/10#card-17824942
