### ISSUE TITLE
Some text editing options are in the toolbar at the top, and others are in the side pane on the right

### ISSUE THREAD

**Issue by vinaymahag** [ampproject/amp-wp#2730]
When editing text, it’s confusing that some text editing options are in the toolbar at the top, and some are in the sidebar at the right. Ideally, they should be in one place. 

You can close this bug if this is the WordPress default.

![image](https://user-images.githubusercontent.com/38660603/60518020-b1a2f480-9cae-11e9-800c-b65633050dd0.png)

**Comment by swissspidy** [comment]
It's true that stock WordPress is a bit inconsistent with these options, but there's not much space in either area to fit _all_ controls.

The top toolbar is very limited in space and only fits the most common options. Everything else is supposed to live in the sidebar.
