### ISSUE TITLE
When editing a text element, there are 2 paragraph icons

### ISSUE THREAD

**Issue by vinaymahag** [ampproject/amp-wp#2731]
We should use a different icon to differentiate the two.

You can close this if this is a WordPress default.

![image](https://user-images.githubusercontent.com/38660603/60518080-cd0dff80-9cae-11e9-948b-406b0f0eb464.png)

**Comment by westonruter** [comment]
@vinaymahag Are you referring to these two:

![image](https://user-images.githubusercontent.com/134745/60518226-eeaebd00-9c95-11e9-8c25-e9f1cd0d987a.png)

If so, then yes, this is default WordPress. The second icon is to switch the style.

**Comment by swissspidy** [comment]
The paragraph and image icons on the left are shortcuts for easily inserting the most needed blocks. The right one is for transforming the current block into another one, as Weston said.

Not sure what we could do to make that less confusing.

**Comment by vinaymahag** [comment]
If it's default WP, then let's leave it as is.
