### ISSUE TITLE
More functionality in a text box / text element

### ISSUE THREAD

**Issue by vinaymahag** [ampproject/amp-wp#2732]
It would be nice if you could hit enter and start a new line in a text box, and if you could have different fonts (sizes, colors) on the new line.

**Comment by swissspidy** [comment]
#2979 addresses the `Enter` part. For the other part (different font sizes and colors) we could draw some inspiration from https://wordpress.org/plugins/advanced-rich-text-tools/, but it might not be quite straightforward and needs some UX considerations.

**Comment by swissspidy** [comment]
Related: #2982 will add support for changing background color for different texts using the `data-text-background-color` attribute.
