### ISSUE TITLE
Add helpers to align objects on the screen and with other objects

### ISSUE THREAD

**Issue by vinaymahag** [ampproject/amp-wp#2733]
It would be nice to have helpers that show you how to center align an object with the page or align an object with another object, similar to what Google Slides does. In the screenshot below, it’s hard for me to create a date byline in a smaller font that’s aligned with the title.

![image](https://user-images.githubusercontent.com/38660603/60518392-72c16e80-9caf-11e9-8dfe-71e4309b9d26.png)

**Comment by swissspidy** [comment]
There's a card in the backlog for snapping: https://github.com/ampproject/amp-wp/projects/10#card-20983897

I am going to create an issue for it and mark this one as a duplicate 👍

**Comment by swissspidy** [comment]
Handled by #2992, #2993, #2994, #2995
