### ISSUE TITLE
Cache query result in add_admin_menu_new_invalid_url_count

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2736]
Query Monitor just warned me about a slow query in WordPress admin coming from `AMP_Validated_URL_Post_Type::add_admin_menu_new_invalid_url_count()`:

https://github.com/ampproject/amp-wp/blob/13114be415be0a7096e97b577482cf3ea4602ae7/includes/validation/class-amp-validated-url-post-type.php#L370-L380

I think that post count result can easily be cached in a transient and updated/flushed whenever validation happens.

**Comment by westonruter** [comment]
@swissspidy Would you do a dev QA to confirm that this eliminates the warning  on your side?

**Comment by swissspidy** [comment]
Sure, I'll have a look 👍

**Comment by swissspidy** [comment]
It was a warning specifically about a slow query, not about duplicate ones. But the change looks good, so I think it will resolve the issue 👍
