### ISSUE TITLE
Support custom fonts in AMP Stories

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-wp#2758]
Many publishers have custom fonts, which they should be able to specify either by uploading a file, or providing a URL (or maybe the appropriate CSS).

**Comment by swissspidy** [comment]
Interesting suggestions for implementation.

Right now adding custom CSS is only possible via code. I am not sure if adding a UI option for this would be very useful, as it's usually something you configure once.

In any case, this would also need to allow extending the font family dropdown so authors can actually select the custom font.

**Comment by swissspidy** [comment]
Closing in favor of #3315
