### ISSUE TITLE
Not clear how to change document title

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-wp#2759]
In the AMP Stories editor, it's not clear how to change the story title:

<img width="1050" alt="Screenshot 2019-07-05 at 16 04 14" src="https://user-images.githubusercontent.com/51244/60809940-cb977800-a183-11e9-845b-76d9a0e179b4.png">

**Comment by swissspidy** [comment]
Right now the title cannot be edited inline, but we're tracking this enhancement in #2572.

**Comment by ithinkihaveacat** [comment]
Thanks!
