### ISSUE TITLE
Add method to provide schema.org metadata

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-wp#2761]
There doesn't seem to be any way for a user to provide schema.org metadata? i.e. https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/discovery#use-schema.org-for-most-search-engines

The metadata itself seem so to be supported via https://github.com/ampproject/amp-wp/issues/873 but perhaps this is not exposed in the UI?

**Comment by swissspidy** [comment]
While the AMP plugin displays some limited schema.org metadata when this data is otherwise missing, this is usually something that's handled by SEO plugins.

**Comment by westonruter** [comment]
Plugins like Yoast can extend/override the baseline Schema.org metadata via the `amp_schemaorg_metadata` filter.
