### ISSUE TITLE
No way for users to add templates (?)

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-wp#2762]
Is there a way for users to add templates? Or do they need to modify the theme?

i.e. how to add to this list (triggered by tapping on blue plus sign):

<img width="768" alt="Screenshot 2019-07-05 at 16 18 29" src="https://user-images.githubusercontent.com/51244/60810957-25993d00-a186-11e9-9bb0-c5f08a225e9c.png">

**Comment by swissspidy** [comment]
This is something we haven't implemented yet / disabled for the moment, as there were some unsolved questions still. See #2011.
