### ISSUE TITLE
Missing or invalid structured data element

### ISSUE THREAD

**Issue by newsautoit** [ampproject/amp-wp#2765]
By 18th June 2019 get this advice in AMP pages.: Missing or invalid structured data element.
It s related with missing element in article type, publisher schema, involving name and logo missing and defined as required. atm it s in a warning advice. started with the last update.

**Comment by westonruter** [comment]
Please share the URL for an example AMP page that has the problem.

**Comment by newsautoit** [comment]
have 6000 errors...
example
https://www.newsauto.it/renault/megane/renault-megane-rs-trophy-2019-foto-prezzi-caratteristiche-2018-177281/amp/

**Comment by westonruter** [comment]
OK, I can see that here: https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.newsauto.it%2Frenault%2Fmegane%2Frenault-megane-rs-trophy-2019-foto-prezzi-caratteristiche-2018-177281%2Famp%2F

Note that the structured data is coming from the Yoast plugin:

```html
<script type='application/ld+json' class='yoast-schema-graph yoast-schema-graph--main'>
```

So this is something you should inquire of Yoast support: https://kb.yoast.com/kb/support/
