### ISSUE TITLE
I created a wordpress shortcode on AMP [value] bind removed

### ISSUE THREAD

**Issue by webmaster444** [ampproject/amp-wp#2771]
I created an WP shortcode and when I created a post template for AMP not works very well.

All other attributes like [hidden], [text] works, but no [value] for input tags.

https://www.screencast.com/t/Rdl2oYZ8
https://www.screencast.com/t/gLU6T6Tn
https://www.screencast.com/t/af6sRe0OEC

**Comment by webmaster444** [comment]
When I use _the_content()_ inside template file it works, but when I use this function _echo $this->get( 'post_amp_content' );_ It not works, even showing [value] amp-bind.

**Comment by westonruter** [comment]
Please share the actual source code for your shortcode, not a screenshot of the code.

**Comment by webmaster444** [comment]
single.php file for AMP post template.
	<div class="amp-wp-article-content">		
		<?php echo $this->get( 'post_amp_content' );>
		<?php # the_content(); ?>
	</div>

**Comment by westonruter** [comment]
Also the code for the adding the shortcode.

**Comment by webmaster444** [comment]
This class AMP_Post_Template is from wordpress amp plugin I think.

**Comment by westonruter** [comment]
I don't understand why you are sharing that class.

Please just share the code you are using to add the shortcode.

**Comment by webmaster444** [comment]
I added shortcode snippet at the very bottom.

**Comment by jamesozzie** [comment]
@webmaster444 I will try recreate the issue from my side. Do you mind sharing your function in code format.
Also just looking at the code you provided in single.php, I see a missing closing php tag:
	`<?php echo $this->get( 'post_amp_content' ); >`
This row should be
	`<?php echo $this->get( 'post_amp_content' ); ?>`

**Comment by webmaster444** [comment]
Sorry that was typo, properly coded in my end.
`<?php echo $this->get( 'post_amp_content' ); ?>`

**Comment by webmaster444** [comment]
Which function do you want?

**Comment by webmaster444** [comment]
functions.php in theme? or single.php for AMP post template?

**Comment by webmaster444** [comment]
That code can be checked here.[https://github.com/webmaster444/ampplugin/blob/master/template/single.php](url)

**Comment by jamesozzie** [comment]
@webmaster444 Are you using the jNews theme? If so can you you disable the AMP plugin that comes with that theme and install the official AMP plugin, before trying to insert the
`$this->get( 'post_amp_content' );` into the single page template file. 

If you want to share you URL also I can check if I can see anything.

**Comment by webmaster444** [comment]
Yes I'm using jNews theme and that single.php file is in that jNews-AMP folder. 
Where could I edit it if I disable that jNewsAmp plugin?

**Comment by jamesozzie** [comment]
@webmaster444 You can create an `amp` folder inside your themes root directory. Then copy the single.php file from with the AMP plugin folder (wp-content/plugins/amp/templates/single.php) to the newly created amp folder in your theme. From there you can modify that single.php file, which will overwrite the plugins default single.php. You'll find more on that [here](https://amp-wp.org/documentation/how-the-plugin-works/classic-templates/). 

You can also deactivate the JNews AMP plugin from with your JNews theme dashboard, if not already done so.

**Comment by webmaster444** [comment]
I tried to deactivate that jNews Amp plugin and I followed your instruction.  I created a subfolder named "amp" and copied "single.php" file and same with above. 
Not showing _[value]="testing"_ as jnews plugin template is added.

**Comment by jamesozzie** [comment]
@webmaster444 Can you share the full code for your [shortcode function](https://www.screencast.com/t/gLU6T6Tn), so I can paste that into a test site myself.

**Comment by webmaster444** [comment]
I created a post and added element using default post editor and having same issue. not a shortcode issue.

**Comment by jamesozzie** [comment]
@webmaster444 Sharing the function whereby you created that shortcode would be helpful, allowing me to copy and paste it. 

Can you also show with me the single.php file again, the link won't open. 
> That code can be checked here.https://github.com/webmaster444/ampplugin/blob/master/template/single.php

**Comment by webmaster444** [comment]
I created a post and added element using default post editor and having same issue. not a shortcode issue.

**Comment by webmaster444** [comment]
I disabled Jnews amp plugin and removed shortcode too. 
I just added input box with [value]="testing" attribute to trigger amp-bind.
I can see <p [text]="textState"> but not [value] attribute. 
So this problem is not related with jnews amp plugin and shortcode.

**Comment by westonruter** [comment]
@webmaster444 I think this was fixed by https://github.com/ampproject/amp-wp/pull/2854. Please test the `amp.zip` build attached there to confirm.
