### ISSUE TITLE
Custom Embed

### ISSUE THREAD

**Issue by CHEWX** [ampproject/amp-wp#2777]
Hi,

I have a video that is from another provider; vinyard.com

I assume I'm going to need to create a custom amp component for this? If so, can I hook this into the plugin anywhere as I cannot see anywhere that allows this.

For reference it's a JavaScript injected video in a custom theme, it doesn't utilise `the_content()`

Thanks,
Tom

**Comment by westonruter** [comment]
There are two options for custom videos. On one hand, you can just use an [`amp-iframe`](https://amp.dev/documentation/components/amp-iframe?format=websites). Otherwise, you could consider [`amp-video-iframe`](https://amp.dev/documentation/components/amp-video-iframe?format=websites).

You'll need to override the JS logic with logic that adds the element via PHP, such as adding the `amp-iframe` or `amp-video-iframe` in `the_content`.

If you show your site and the JS logic that is being used to inject the video, than we can better advise.

**Comment by CHEWX** [comment]
I'm not sure either of those will work. This is a JavaScript injected video player, quite a few services use this. 

Example embed:

```
<!-- The script tag should live in the head of your page if at all possible -->
<script type="text/javascript" async src="https://play.vidyard.com/embed/v4.js"></script>

<!-- Put this wherever you would like your player to appear -->
<img
  style="width: 100%; margin: auto; display: block;"
  class="vidyard-player-embed"
  src="https://play.vidyard.com/LtJJqfyHztRQP2PRYoQ4gf.jpg"
  data-uuid="LtJJqfyHztRQP2PRYoQ4gf"
  data-v="4"
  data-type="inline"
/>
```

**Comment by westonruter** [comment]
The key thing is to look at what the JavaScript constructs in the DOM. I can see it is ultimately generating an `iframe`:

```html
<iframe allow="autoplay *; fullscreen *; picture-in-picture *" allowfullscreen="" allowtransparency="true" aria-label="Video" class="vidyard-iframe-LtJJqfyHztRQP2PRYoQ4gf" frameborder="0" height="100%" width="100%" scrolling="no" src="https://play.vidyard.com/LtJJqfyHztRQP2PRYoQ4gf?v=4.2.13&amp;type=inline&amp;disable_popouts=1" title="Video" style="opacity: 1; background-color: transparent; position: absolute; top: 0px; left: 0px;"></iframe>
```

So what you then need do is take that UUID (`LtJJqfyHztRQP2PRYoQ4gf`) and use it to construct an `amp-iframe` when `is_amp_endpoint()` is true. For example, with a placeholder image as poster:

```html
<amp-iframe allowfullscreen sandbox="allow-scripts" layout="responsive" width="814" height="459" class="vidyard-iframe-LtJJqfyHztRQP2PRYoQ4gf" src="https://play.vidyard.com/LtJJqfyHztRQP2PRYoQ4gf?v=4.2.13&amp;type=inline&amp;disable_popouts=1">
    <amp-img placeholder layout="fill" src="https://play.vidyard.com/LtJJqfyHztRQP2PRYoQ4gf.jpg"></amp-img>
</amp-iframe>
```

Works great for me:

![image](https://user-images.githubusercontent.com/134745/61079776-6ab4ad80-a3d8-11e9-9a08-3af00fe5b925.png)

It would be great if you could contribute this `amp-iframe` solution upstream Vidyard.

**Comment by westonruter** [comment]
@CHEWX Here is an updated version of the [Vidyard WordPress plugin](https://knowledge.vidyard.com/hc/en-us/articles/360009993593-Using-the-Vidyard-for-WordPress-oEmbed-plugin) which adds support for AMP: https://gist.github.com/westonruter/db093fd74797a965fbb4f3af232db47c

I've contacted their support to ask them to update their plugin with my changes, and also for them to add direct support for `amp-video-iframe`.

**Comment by CHEWX** [comment]
Perfect! Thanks very much.
