### ISSUE TITLE
Add Jest unit tests for remaining helper functions

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#2779]
Most of the functions in `/helpers/index.js` have unit tests. But it'd be nice to add test to the remaining ones, like the ones that have:

```js
it.todo( 'add tests' );
```

**Comment by kienstra** [comment]
If you'd like, I could develop for this.

**Comment by swissspidy** [comment]
I think we should focus on adding E2E tests for crucial parts of the UI and newly introduced stuff first. There is lots of other stuff on our plates already :-)

**Comment by kienstra** [comment]
Sounds good.
