### ISSUE TITLE
Allow dragging of CTA button in the bottom specified area within the page

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2781]
As a user I want to be able to move, and place, the CTA block freely within the bottom area of the page. 

AC1: Enable a user to drag, and place, CTA block freely within the page
AC2: Ensure limitations of designated area on the page for CTA blocks (e.g. bottom 20%) persist.

**Comment by miina** [comment]
Instructions for testing:
- Create a CTA block
- Verify that the button can be dragged but not over the blocks upper border (can go over from other borders)
- Verify that clicking twice on the CTA block will allow editing the Text and the URL.

**Comment by csossi** [comment]
Verified in QA

**Comment by cathibosco** [comment]
https://youtu.be/2LQZzCLcgmM
