### ISSUE TITLE
Enable users to click and drag anywhere within a block, if block contains text require a double click to edit text.

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2783]
As a user I want to be able to click anywhere on a block, and drag/place it elsewhere on a page.

AC1: Single clicking anywhere on a block, and dragging will drag a block.
AC2: Upon release block will remain in new place.
AC3: Double clicking within a text block will enable edit-mode.

**Comment by swissspidy** [comment]
For reference, here's how they implemented the clickthrough feature for inner blocks in Gutenberg: https://github.com/WordPress/gutenberg/pull/15537

**Comment by swissspidy** [comment]
Do we have an item somewhere for an Instagram-like focus when editing a text block? I wonder whether that might be useful here too.

**Comment by miina** [comment]
By instragram-like focus do you mean that the rest of the screen is faded out and the text appears in the center instead of its actual position?

**Comment by swissspidy** [comment]
Yes. Perhaps just with the fading out, without the position change.

**Comment by miina** [comment]
I don't think we have an issue for that, the only related issue was displaying the selected block on top of the other blocks (couldn't find the issue right now).

We could create a consideration issue for that, it could be useful in some cases. Might also be useful when rotating elements which are close to each other.

I guess this would need testing to see if it makes sense for desktop editing.

**Comment by miina** [comment]
Instructions for testing:
- Create a Text block
- Verify that the block can be dragged from anywhere.
- Verify that clicking twice on the block will allow editing the Text and disable dragging.
- Verify that deselecting the block will disable the edit mode and allow dragging again.

**Comment by csossi** [comment]
Verified in QA

**Comment by cathibosco** [comment]
https://youtu.be/XU9UkrxTtZk
