### ISSUE TITLE
Improve drag & drop reordering of elements in layer panel

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2784]
As a user I want the drag/drop reordering of elements in the layer panel to be easier, and more intuitive, to use

**Comment by swissspidy** [comment]
To give some context, our implementation is based on Gutenberg's drag & drop component, which was mainly implemented for dragging blocks in the editor. There, the draggable items are quite big and it's easy to drag a block before/after another block.

In our use case, the elements and dropzones are way smaller, and it's tricky to find the right spot.

Note that any learnings we get from improving the layer panel can be adapted for the reorder view as well.

**Comment by kienstra** [comment]
**Question About Sorting**

Hi @MackenzieHartung and @swissspidy,
Would you like the sorting of the layer panel to be like sorting in [jQuery UI](https://jqueryui.com/sortable/)? Of course, this wouldn't actually use [jQuery UI](https://github.com/jquery/jquery-ui/blob/master/ui/widgets/sortable.js):

![jquery-ui-demo](https://user-images.githubusercontent.com/4063887/61656801-27372a80-ac87-11e9-803d-fcd6db1a0e02.gif)

...as opposed to the current state, where there's only a blue 'bar' on dragging over:

![current-dragging](https://user-images.githubusercontent.com/4063887/61657091-c3613180-ac87-11e9-92d0-52c79256b1e9.gif)

**Comment by swissspidy** [comment]
It seems more natural at first glance 👍

**Comment by kienstra** [comment]
**Steps To Test**

1. Create a new story
2. Add at least 4 blocks to the first page
3. In the 'Elements' section, change the order of the elements (layers) by dragging them 
4. Expected: dragging should work well
5. Expected: on dropping an element, it should stay in place, unless it is dragged outside of the 'Elements' area:

![dragging-example](https://user-images.githubusercontent.com/4063887/62181209-24d47080-b318-11e9-8eba-64e62419d751.gif)

6. Expected: after clicking 'Save Draft' and  reloading the page, the elements should be in the same order

**Comment by swissspidy** [comment]
(Please hold off with testing until this has been deployed)

**Comment by swissspidy** [comment]
This has now been deployed to the test env 🎉

**Comment by csossi** [comment]
Verified in QA

**Comment by kienstra** [comment]
Thanks, @csossi!

**Comment by cathibosco** [comment]
https://youtu.be/ea2mVn9zoy0
