### ISSUE TITLE
Explore Gutenberg Core updates associated with copy/paste discoverability

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2786]

**Comment by miina** [comment]
Note: Will start looking into this.

**Comment by miina** [comment]
Currently copying and pasting is handled only via [`RichText`](https://github.com/WordPress/gutenberg/blob/0214d79f059f75f49e9d7014243b78eb839a3a25/packages/block-editor/src/components/rich-text/index.js#L104), see also the [RichText package](https://github.com/WordPress/gutenberg/blob/0214d79f059f75f49e9d7014243b78eb839a3a25/packages/rich-text/src/component/index.js#L196). For example it's not possible to copy a block, then select a Column block and then Paste. First, the user would need to add a block using `RichText` to the Column (e.g. Paragraph / Heading ) and then paste the content inside there.

Doesn't look like there are any issues / PR-s attempting to change that logic.

Assuming that what we would need would be:
- Copying a block (or some blocks)
- Choosing a Page and Pasting
- This would need to result in copying the blocks to the selected Page.

We could achieve this for example by adding `onPaste` handler to the selected Page block which would then process the `clipboardData` (perhaps in a similar way as is done within `RichText`) and create new blocks accordingly.

Thoughts? 

cc @swissspidy

**Comment by swissspidy** [comment]
Made similar observations about pasting in https://github.com/ampproject/amp-wp/issues/2785#issuecomment-513811297, where we need this.

> We could achieve this for example by adding onPaste handler to the selected Page block which would then process the clipboardData (perhaps in a similar way as is done within RichText) and create new blocks accordingly.

+1

**Comment by miina** [comment]
Will create a separate ticket for that for keyboard copy-paste but looks like the pasting/cutting logic will be the same as in Right-Click tickets.

**Comment by miina** [comment]
Added #2996.
