### ISSUE TITLE
Allow select-mode to select one or more elements

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2788]
As a user I want to be able to engage "select" mode to select one or more elements at a time.

AC1: A CTA will be added to the editor that when selected will put the user in select mode.
AC2: When in select mode a user can click to select a block.
AC3: When in select mode a user can drag from an empty area on the page and select one or multiple elements by dragging the selection area over the element.
AC4: A user will remain in select mode until they double-click within a text block (related to issue #2783  )

**Comment by swissspidy** [comment]
This depends on #2787, as otherwise it would not be possible to select a random list of blocks in this way.

**Comment by swissspidy** [comment]
Gutenberg issue to follow: https://github.com/WordPress/gutenberg/issues/17088

**Comment by swissspidy** [comment]
I don't think this 100% depends on #2787, as we can first start with single selection only, and then when #2787 is resolved we support selecting multiple elements.
