### ISSUE TITLE
Allow multi-selected elements to be copied as a group, and pasted as a group

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2790]
As a user, once I have selected multiple elements on a page, I want to be able to copy the group of them, and paste the group of them.

AC1: Once multiple items are selected on a page, selecting copy will copy all items collectively
AC2: Selecting paste will paste the copied items, as a group, based on their placement in relation to one another when copied

Dependent on #2785 and #2786

**Comment by swissspidy** [comment]
When trying to copy via the right click, this upstream issue is relevant: https://github.com/WordPress/gutenberg/issues/16376
