### ISSUE TITLE
Choosing pre-defined font size causing error

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2794]
Steps to reproduce:
- Create a text block.
- Add some text.
- Turn off the setting for amp-fit-text ("Automatically fit text to container").
- Switch the font size to one of the pre-defined sizes, e.g. to “Large” 

<img width="1374" alt="Screenshot 2019-07-11 at 13 26 47" src="https://user-images.githubusercontent.com/3294597/61049084-df411980-a3e3-11e9-8f53-b4d2e0c46989.png">

AC: User should be able to set a custom font size and choose between different font sizes.

**Comment by miina** [comment]
Instructions for testing:

- Create a text block.
- Add some text.
- Turn off the setting for amp-fit-text ("Automatically fit text to container").
- Switch the font size to one of the pre-defined sizes, e.g. to “Large”
- Verify that the Text block works properly.
- Verify the same for Meta blocks as well (Title, Author, Date).

**Comment by csossi** [comment]
Verified in QA

(Creating new issue re: font sizes for Page Title block)
