### ISSUE TITLE
Live Stories

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2796]
Live Stories are now a thing in AMP. Users will be able view stories that are updated in real-time as the publisher adds new pages to it - without the need of having the user refresh the page

See https://github.com/ampproject/amphtml/issues/21714
See https://github.com/ampproject/amphtml/pull/23041/files for the docs.

Technical implementation is rather trivial, just requires a few attributes here and there. In the UI we could simply add a checkbox for that.

Not a priority now but a nice thing to keep in mind.

**Comment by westonruter** [comment]
Very nice. To support this I suppose we'd need to populate the `data-sort-time` prop on the `amp-story-page` block with a timestamp whenever a page is inserted or modified?

**Comment by swissspidy** [comment]
In a nutshell, yes.
