### ISSUE TITLE
Page Title - Auto-Fit "OFF" Font sizes

### ISSUE THREAD

**Issue by csossi** [ampproject/amp-wp#2801]
Added Page Title block. Here's the size when set to "Normal":
![image](https://user-images.githubusercontent.com/16945664/61177013-1c9ad800-a599-11e9-9406-26d2a15387f5.png)

Which is actually larger than "Medium":
![image](https://user-images.githubusercontent.com/16945664/61177018-350af280-a599-11e9-96cd-f4e1348ada7c.png)

note: sizing logic looks fine for author, text, and date blocks, fyi

**Comment by miina** [comment]
Note:
Looks like when turning off amp-fit-text for the first time then the font size is not set at all (the custom font size input showing the font size is empty) although "Normal" label is shown as the selected font.
<img width="278" alt="Screenshot 2019-07-15 at 13 23 05" src="https://user-images.githubusercontent.com/3294597/61210116-2d1b9180-a704-11e9-8b9b-be0e188b4fc4.png">


When clicking "Medium" and then "Normal" again then the correct font sizes are used (and shown).
<img width="287" alt="Screenshot 2019-07-15 at 13 27 17" src="https://user-images.githubusercontent.com/3294597/61210158-4a506000-a704-11e9-804f-b27b35a98530.png">

**Comment by swissspidy** [comment]
@miina I think that's normal Gutenberg behavior. Same happens in the regular post editor.

**Comment by swissspidy** [comment]
To solve this issue we would to override the default `h1` style in the CSS.

**Comment by miina** [comment]
Alternatively, maybe we could set a specific value when amp-fit-text is turned off and there's no previous value saved yet?

**Comment by swissspidy** [comment]
@miina One can still manually clear the number input field, and Gutenberg then goes back to using/assuming the `default` value. So it needs a default value no matter what.

**Comment by swissspidy** [comment]
@csossi since you originally reported this, would you mind verifying the fix that I just added? Need to wait for a deployment first though.

**Comment by csossi** [comment]
Verified in QA:
![image](https://user-images.githubusercontent.com/16945664/61231877-03aa3800-a6fb-11e9-940e-317800e5285b.png)
