### ISSUE TITLE
Video poster image warning shown in placeholder

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2808]
**Steps to reproduce**

1. Add new video block
2. Select video without a poster image
3. Verify that the missing poster image warning appears in the block sidebar.
4. Click on pencil icon in the block toolbar to replace the video
5. See the poster image warning in the placeholder

**Screenshot**

![Screenshot 2019-07-15 at 14 22 09](https://user-images.githubusercontent.com/841956/61215800-1e38dd00-a70c-11e9-97b3-5d234d62748f.png)

**Comment by swissspidy** [comment]
Doesn't look like there's a way for us to know whether the video block is currently in edit mode:

https://github.com/WordPress/gutenberg/blob/ff70de60086e8f505de51a9f9883d77bf5eda119/packages/block-library/src/video/edit.js#L171-L185

However, in #2799 we are overriding the video block's edit component anyway, so I think we should just integrate `withVideoPosterImageNotice` there.

**Comment by swissspidy** [comment]
Added this to #2799.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Add video block
2. Add video that does not have a poster.
3. Verify that a warning about missing poster image is shown in the sidebar.
4. Click on pencil icon in block toolbar
4. Verify that **no** poster warning is shown there

**Comment by csossi** [comment]
Verified in QA
