### ISSUE TITLE
Reorder buttons not aligned properly

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2836]
No idea what changed, but this is definitely incorrect:

![Screenshot 2019-07-18 at 10 56 14](https://user-images.githubusercontent.com/841956/61443949-bf14db80-a94a-11e9-9efe-a45f7bbf79bc.png)

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create a new story
2. Click on reorder button
3. Verify that the cancel and save buttons are vertically aligned

**Comment by csossi** [comment]
Verified in QA
![image](https://user-images.githubusercontent.com/16945664/61464563-7b1ed800-a944-11e9-9f35-6b899be980ec.png)
