### ISSUE TITLE
Turning amp-fit-text on doesn't always adjust the font size

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2839]
Turning on the amp-fit-text setting seems to (at least sometimes) take the previously saved font size and not trigger calculating new font size.

Steps to reproduce:
- Add a Text block.
- Write something and resize the Text block to larger.
- Turn off amp-fit-text setting.
- Resize the Text block to smaller.
- Turn amp-fit-text setting back.

<img width="378" alt="Screenshot 2019-07-18 at 12 55 50" src="https://user-images.githubusercontent.com/3294597/61448921-8251e000-a95c-11e9-9e56-ed19a5fce500.png">

**Comment by swissspidy** [comment]
I think 973576121b0345b4ab3fede402ca75994677a0b9 in #2831 fixes this.

**Comment by swissspidy** [comment]
Fixed by #2831.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Add a Text block.
1. Write something and resize the Text block to larger.
1. Turn off amp-fit-text setting.
1. Resize the Text block to smaller.
1. Turn amp-fit-text setting back.
1. Verify that the font size adjusts accordingly so it doesn't overflow the block's container.

**Comment by csossi** [comment]
Verified in QA
