### ISSUE TITLE
maybeSetTagName not robust enough

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2843]
## Bug Description

Text block's have this feature of determining the semantic tag name (`<p>`, `<h1>`, `<h2>`) on the frontend based on a few characteristics.

The underlying `maybeSetTagName()` function responsible for that tries to ensure there's only one text block with `h1` on a given page. It does so by checking whether any sibling block explicitly uses `h1` text type.

However, it does not check whether any sibling block uses `auto` text type. Also, it does not take into account story title blocks, which are `h1`.

At the same time, a story could be considered to be a single document which should only have one `h1` tag. That means the whole `maybeSetTagName()` logic doesn't make too much sense at the moment. Plus it seems to be broken anyway because it checks the wrong set of blocks.

See discussion below for more details.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Turns out this was indeed broken because it actually fetched the list of children instead of siblings.

Even then, comparing to siblings does not really work. For example, if you have 3 blocks with text type `auto`, how do we decide which block gets "promoted" to h1?

I see two options:

1. Using the data store as the source of truth for this.
2. Instead of performing the check from the child block's point of view, we do it from the parent's point of view, going through all children and then simply "promoting" the first eligible block as h1.

**Comment by swissspidy** [comment]
Also, what if there are multiple story title blocks on a page?

**Comment by miina** [comment]
> For example, if you have 3 blocks with text type auto, how do we decide which block gets "promoted" to h1?

We could, in theory, choose the block with the largest font size. E.g. if there's a sibling with manually selected `h1` then just use that one, if not, then choose the block based on font size.

> Also, what if there are multiple story title blocks on a page?

Maybe this shouldn't be allowed? :)

**Comment by swissspidy** [comment]
> We could, in theory, choose the block with the largest font size.

`getTagName` already includes such logic (and more)

There can also be cases where there are 2 text blocks with long text, where neither really makes sense as an `h1`, resulting in no heading on that page.

> Maybe this shouldn't be allowed? :)

Creating an issue for consideration 👍 

--- 

On a related note, I was just browsing through some example stories on the web and there quite a few differences in semantics.

Some stories did not use any headings whatsoever, others used an `h1` only on the first page followed by `h2`, `h3`, and of course `p` on the following pages. One had `h1` on multiple pages.

The current logic in our editor assumes that there should ideally be one `h1` on a page, but it feels like that assumption is not really true.

Also, we don't currently support `h3` at all.

**Comment by miina** [comment]
> getTagName already includes such logic (and more)

Hmm, I didn't see `getTagName` comparing the font size between siblings. Anyway, I guess it doesn't really matter if the assumption of having one `h1` per Page is not really true.

> The current logic in our editor assumes that there should ideally be one h1 on a page, but it feels like that assumption is not really true.

There aren't any guidelines for this either, right? Couldn't find any at least.

In this case, we could go for something not too complex, e.g. we could have `h1` only for the Story Title and leave the `getTagName` logic for `h2` and `h3`, not caring about the siblings. And of course, the user could still choose manually if preferred. Thoughts?

**Comment by swissspidy** [comment]
I couldn't find any guidelines either, but I'll try to ask around.

Reducing the current complexity and not making it more complex would indeed be nice.

**Comment by swissspidy** [comment]
Just realized that it currently doesn't seem to work at all anyway, as it operates with a wrong list of sibling blocks. Will have to test it properly as a whole.

**Comment by jauyong** [comment]
Hey @jasti I reviewed this and wasn't able to add any AC. Would you like to meet or take a look so that we can get this ticket moved on to the IB column?

**Comment by miina** [comment]
Perhaps we should remove the logic for now since it's not working anyway at this moment. Doing that should also fix #3646. And then we can rediscuss the necessity of this feature. Thoughts?
