### ISSUE TITLE
Website renders wrong after the plugin uninstall

### ISSUE THREAD

**Issue by dafdriver** [ampproject/amp-wp#2846]
After the plugin uninstall, there is still a mobile version left, can be see from any mobile device or emulated mobile user agent in the console http://prntscr.com/ogz068
Also, UX blocks are encapsulated in quotes. 
Caching is disabled. The database cleaned from any leftovers. I did rewrite permalinks too, no effect.
Can you have a look please.

https://belitavitex.co.uk

**Comment by swissspidy** [comment]
Hi there

These shortcodes that you see there are coming from some other plugin that you‘ve installed. The AMP plugin does not use such shortcodes and leaves no traces anyway when being uninstalled.

**Comment by dafdriver** [comment]
Hi, I know the shortcodes are not from your plugin. This is the problem - after the plugin was installed, the shortcodes are encapsulated in quotation marks and fail to render. The desktop version is OK. Even when I uninstall the plugin, nothing has changed, the UX block shortcodes are still echoed as a quoted text.

**Comment by westonruter** [comment]
This would be a general WordPress problem not something with the AMP plugin.

**Comment by dafdriver** [comment]
Gentlemen, I appreciate your efforts to brush me off, but it seems you are ignoring a simple fact here. My website main colour is green. The AMP version main colour is navy. I uninstalled your plugin and the website is still navy in colour, totally different set of css styles, etc. . Please help me uninstall your plugin properly, something is definitely went wrong here.  
http://prntscr.com/oi4v05 - desktop version
http://prntscr.com/oi4v87 - emulated mobile version 
http://prntscr.com/oi4vik - actual mobile version (open from mobile or open in emulated console and do hard refresh)
You can see that the plugin somehow is still operational.

**Comment by swissspidy** [comment]
@dafdriver We certainly did not intend to brush you off. What you're seeing on http://prntscr.com/oi4vik is the mobile theme from the Jetpack plugin you are using, see https://jetpack.com/support/mobile-theme/. It is not related to AMP or the AMP plugin.

**Comment by dafdriver** [comment]
Now this is a sensible answer! Thank you, guys.
