### ISSUE TITLE
Lightbox attribute in carousel

### ISSUE THREAD

**Issue by rsmith4321** [ampproject/amp-wp#2849]
In the code for the amp carousel you seem to add the "lightbox" attribute to each individual amp-image. The better way appears to be to add the "lightbox" attribute to the entire amp-carousel. Then once the lightbox opens the entire carousel of images can be browsed in the lightbox. Unless I'm misunderstanding something. The details can be found here https://amp.dev/documentation/examples/components/amp-lightbox-gallery/?format=websites

**Comment by kienstra** [comment]
**Question about shortcode or block**

Hi @rsmith4321,
Hope you've been doing great.

Was this for a `[gallery]` shortcode, or a Gallery block? I think there were `[gallery]` shortcodes on your site when we worked on other issues together.

Your suggestion [is applied](https://github.com/ampproject/amp-wp/pull/3659/files#r340341137) for the `[gallery]` shortcode, but not for the Gallery block.

The `[gallery]` shortcode doesn't add the `lightbox` attribute to the `<amp-carousel>`, but the effect is similar to what's [described above](https://github.com/ampproject/amp-wp/issues/2849#issue-470100238):

![shortcode-gall](https://user-images.githubusercontent.com/4063887/69663908-e1cba500-104c-11ea-98b3-61d03384524a.gif)

It wouldn't be very hard to [apply a similar change](https://github.com/ampproject/amp-wp/pull/3659/files#r340341137) to the [Gallery block](https://github.com/ampproject/amp-wp/blob/9c853ca3f599d03bf8b59abe0385005fa244c7ce/includes/sanitizers/class-amp-gallery-block-sanitizer.php#L148)

Thanks, Ryan!

**Comment by kienstra** [comment]
**Testing Steps**
*For when #3823 is ready for QA*

1. Create a new post
2. Add a gallery block
3. Select 'Add lightbox effect'
4. Go to the front-end of the AMP URL
5. Click the gallery
6. Expected: a lightbox opens, and you can click to go to other images, like in the [.gif above](https://github.com/ampproject/amp-wp/issues/2849#issuecomment-558773677).

**Comment by rsmith4321** [comment]
This was an old post, I believe this was already solved on the last update all the images in a gallery now open correctly in a lightbox.  Thanks for the help.

**Comment by kienstra** [comment]
OK, thanks!

**Comment by csossi** [comment]
Verified in QA
