### ISSUE TITLE
Add lightbox effect doesn't work with gallery shortcode

### ISSUE THREAD

**Issue by rsmith4321** [ampproject/amp-wp#2850]
I have a gallery shortcode inserted with the shortcode block like [gallery ..... link="file"] so each image should be linked to its source image. And without any amp settings selected it works correctly. However, if in the AMP settings in the shortcode block editor sidebar I have selected to "Add lightbox effect", then the the links to the source images disappear and the lightbox doesn’t work. It’s is the same as if link=”file” is not in the shortcode. 

Originally https://wordpress.org/support/topic/amp-carousel-doesnt-have-alt-tags/

**Comment by rsmith4321** [comment]
This isn't a "Help Request" I'm reporting a bug.  Has anyone tested a standard wordpress gallery shortcode with the "add lightbox effect" option selected but the "display as carousel" option not selected.  The lightbox doesn't work and the image links are removed. Can someone please test this?  Thanks.

**Comment by westonruter** [comment]
I can confirm this is a bug. If carousel is not enabled, then no lightbox is applied.

**Comment by westonruter** [comment]
I believe the problem is rooted in this code:

https://github.com/ampproject/amp-wp/blob/1b8afd930a6c3512846ecae0ef767e78275d7a57/includes/embeds/class-amp-gallery-embed.php#L165-L176

**Comment by rsmith4321** [comment]
Thanks, I was actually looking though that code as well but I don't know enough to fix it myself. It's adding a class="amp-lightbox" to the ul which I don't think does anything. It needs to just add lightbox attribute to the end of each <amp-img> tag, then even better it could use figcaption or alt for description as described here https://amp.dev/documentation/components/amp-lightbox-gallery/?format=websites

**Comment by rsmith4321** [comment]
Has anyone had a chance to look at this bug?

**Comment by westonruter** [comment]
I don't believe so, but we have it prioritized in the project board we are currently working through: https://github.com/ampproject/amp-wp/projects/13

**Comment by kienstra** [comment]
**Steps To Test**

1. Create a new post
2. Add a Shortcode block
3. Paste this in the block:
```
[gallery ids="3079, 2376, 1714"]
```
4. Select 'Add lightbox effect'
5. Save the page, and go to the AMP URL on the front-end
6. Expected: on clicking an image, the lightbox appears
7. Go back to the block editor, and paste this in the same Shortcode block:
```
[gallery ids="3079, 2376, 1714" link="file"]
```
8. Save the page, and go to the AMP URL on the front-end
9. Expected: just like in step 6, clicking on an image causes the lightbox to appear

**Comment by rsmith4321** [comment]
I just tested the latest version of the amp plugin. I have the lightbox option set on the gallery shortcode but the images still do not open in the lightbox.  You can check out an example here https://www.ryansmithphotography.com/blog/2019/09/30/bridal-portraits-on-the-conway-river-and-new-garden-walks-with-the-nikon-d850/

**Comment by westonruter** [comment]
@kienstra Would you please double-check this?

**Comment by kienstra** [comment]
Sure, Weston!

**Comment by kienstra** [comment]
**Question About Caching**

Hi @rsmith4321,
Thanks for letting us know. I also see the issue on the [link you shared](https://www.ryansmithphotography.com/blog/2019/09/30/bridal-portraits-on-the-conway-river-and-new-garden-walks-with-the-nikon-d850/), where the gallery shortcode with 'Add lightbox effect' checked doesn't actually open a lightbox on clicking it:

```html
[gallery ids="3762, 3470, 3327, 2877" link="file"]  // Only example IDs, of course.
```

*Is there anything you could do to clear the cache on [that URL](https://www.ryansmithphotography.com/blog/2019/09/30/bridal-portraits-on-the-conway-river-and-new-garden-walks-with-the-nikon-d850/), if that applies?*

It looks like it's using WP Rocket:
```html
<!-- This website is like a Rocket, isn't it? Performance optimized by WP Rocket. Learn more: https://wp-rocket.me - Debug: cached@1570044620 -->
```

Though not to cast blame. It's showing the latest version of the AMP plugin, so it could still be a bug with the plugin:

```html
<meta name="generator" content="AMP Plugin v1.3.0; mode=standard; experiences=website">
````

Locally, I couldn't reproduce the issue. 

The [expected behavior](https://github.com/ampproject/amp-wp/pull/3097/files#diff-a0af6b56b4ac0b105c0004e60d2ded4cR73) with the latest (v1.3.0) is that when `link="file"` and 'Lightbox', the `<amp-img>` tags aren't wrapped in `<a>` tags:

The fact that it's wrapped in `<a>` suggests that something is wrong. Maybe with caching, maybe with the plugin:

<img width="1218" alt="amp-img-wrapped" src="https://user-images.githubusercontent.com/4063887/66090935-163e4b80-e54b-11e9-9452-9cd66368579d.png">

**Comment by rsmith4321** [comment]
The issue seems to be in my custom filter in functions.php.  Instead of using attributes in the shortcode itself I had the following filter.  However if I remove this and add link="file" directly in the shortcode it works.  Do you know how I could correct this filter so it would work?

`add_filter(
	'shortcode_atts_gallery',
	function( $atts ) {
		$atts['size']    = 'large';
		$atts['columns'] = 1;
		$atts['link'] = 'file';
		return $atts;
	}
);
add_filter( 'use_default_gallery_style', '__return_false' );`

**Comment by kienstra** [comment]
Ah, thanks for sharing that filter. I can reproduce the issue with that. I'll look at this and get back to you.

**Comment by rsmith4321** [comment]
Great I appreciate it, using a filter is much better for me than editing each gallery shortcode.

**Comment by kienstra** [comment]
**Question About Workaround**

Hi @rsmith4321,
Sure, it sounds like using the filter is easier for your workflow than editing the individual shortcodes.

But as a workaround, would it be possible to remove `$atts['link'] = 'file';` from the filter?

For AMP, it shouldn't be necessary to add `link="file"` to the shortcode string, as [the plugin overwrites it](https://github.com/ampproject/amp-wp/pull/3097/files#diff-089afc93c28d84ef35d208849c52193cR177).

```html
[gallery ids="3762, 3470, 3327, 2877" size="large"]
```

It looks like [your site](https://www.ryansmithphotography.com) is using Standard mode, which is great! If there happen to be non-AMP URLs with the gallery shortcode, the `link="file"` string would be needed.

Thanks, Ryan!

**Comment by rsmith4321** [comment]
Your right, without that link="file" it seems to work correctly and the lightbox is great with the slideshow function and captions! One other question, instead of going to each gallery shortcode in the editor and clicking the add lightbox effect checkbox.  Would there be any kind of filter I could add to my functions.php that would default to on the add lightbox effect on all gallery shortcodes?

**Comment by rsmith4321** [comment]
One other thing I've noticed, with add lightbox effect disabled the original image size will be linked too which is what I want.  However with the lightbox effect on it seems to just load the large thumbnail size in the lightbox.  Is it possible for the lightbox to display the original image file?

**Comment by kienstra** [comment]
>One other question, instead of going to each gallery shortcode in the editor and clicking the add lightbox effect checkbox. Would there be any kind of filter I could add to my functions.php that would default to on the add lightbox effect on all gallery shortcodes?

That'd be useful 😄 But unfortunately, I couldn't find a way to do that. 

[The method](https://github.com/ampproject/amp-wp/blob/f3550c39b6b9ffa39ca07a22c1df7fe0b0d9be73/includes/embeds/class-amp-gallery-embed.php#L165) that adds the lightbox runs as a filter of [post_gallery](https://github.com/ampproject/amp-wp/blob/f3550c39b6b9ffa39ca07a22c1df7fe0b0d9be73/includes/embeds/class-amp-gallery-embed.php#L19), and there unfortunately isn't a way that I can find to add the lightbox before it runs.

**Comment by kienstra** [comment]
Hi Ryan,
>One other thing I've noticed, with add lightbox effect disabled the original image size will be linked too which is what I want. However with the lightbox effect on it seems to just load the large thumbnail size in the lightbox. Is it possible for the lightbox to display the original image file?

Hm, interesting.

Could you please share a link with that issue, and an image where it exists (if it's a different link from the one you shared)?

In the [link you shared above](https://www.ryansmithphotography.com/blog/2019/09/30/bridal-portraits-on-the-conway-river-and-new-garden-walks-with-the-nikon-d850/), it looks like the images in the lightbox are generally `1500 x 1000`.

For example, here's the 2nd image in the gallery:
<img width="1434" alt="image-size-now" src="https://user-images.githubusercontent.com/4063887/66163958-2c094a80-e5f7-11e9-8f19-9626337ef1af.png">

**Comment by kienstra** [comment]
Hi Ryan,
Sorry, I forgot to mention that `$atts['link'] = 'file';` would be necessary in that filter if there are galleries that that you **don't** want to be lightboxes, but you still want to link to the files.

**Comment by rsmith4321** [comment]
Yes the 1500x1000px image is the large thumbnail size. The original image size would be a 2048px image. Here is a link to the full size original file, this is what a typical lightbox would link to.  This would also be what would be linked to with just link="file" setting with no lightbox.  https://www.ryansmithphotography.com/wp-content/uploads/2019/09/bride-standing-on-train-tracks-conway-river-walk-2019.jpg.  The large size thumbnail is probably fine anyway but this isn't typical lightbox behavior. Thanks for the help with this.

**Comment by westonruter** [comment]
@rsmith4321 Would you please test #3439?

**Comment by kienstra** [comment]
>Yes the 1500x1000px image is the large thumbnail size. The original image size would be a 2048px image.

Good point, it would make sense to have a bigger image in a lightbox. I'll look at this more. It might be more of an issue with AMP in general.

**Comment by kienstra** [comment]
With #3439, this will allow the [previous filter](https://github.com/ampproject/amp-wp/issues/2850#issuecomment-537790526), even setting `$attr['link'] = 'file';`

**Comment by kienstra** [comment]
**Better Lightbox Images**

Hi @rsmith4321,
>Here is a link to the full size original file, this is what a typical lightbox would link to. 

Yeah, that makes sense to want a bigger image size for the lightbox.

I think this might have to come from the AMP project, though. Here are some slightly related issues:
https://github.com/ampproject/amphtml/issues/21736
https://github.com/ampproject/amphtml/issues/14900

Though unfortunately, I haven't noticed any issue that looks like it's close to being fixed.

I'll let you know if anything else comes to mind.

**Comment by rsmith4321** [comment]
Thanks, I'll keep an eye on this to see if it's ever resolved but it's not a huge deal.  There is something strange going on because sometimes it does put the original size in the lightbox and sometimes the thumbnail.  It's strange I would assume that the html would be generated by php in wordpress selecting the full size image and not something in amp.

I also tested the latest update and it seems to fix the issue with $attr['link'] = 'file';.  I've added that back into my functions.php and the lightbox is working, thanks.

**Comment by kienstra** [comment]
Hi @rsmith4321,
>There is something strange going on because sometimes it does put the original size in the lightbox and sometimes the thumbnail. It's strange I would assume that the html would be generated by php in wordpress selecting the full size image and not something in amp.

Ah, interesting.

Is there an example image you can point to that does that? 

It looks like at least some portrait images are `1365 x 2048`:

<img width="1195" alt="portrait-intrinsic-size" src="https://user-images.githubusercontent.com/4063887/66178214-2842eb80-e62a-11e9-996a-04f510091736.png">

...but maybe that's not the 'full size image' that you referred to.

**Comment by rsmith4321** [comment]
Yes that is the original full size.  Basically if the file name has image dimensions at the end of the file name such as 1500x1000.jpg, that is a wordpress generated thumbnail.  If it doesn't have this it'a an original upload size image. In the wordpress php that would be like full, large, medium, and thumbnail. Why some images in the lightbox show the full size and some the large size I have no idea, they should all be the same.
