### ISSUE TITLE
AMP plugin causes JS errors with Yoast SEO in WP < 5.0

### ISSUE THREAD

**Issue by ethanclevenger91** [ampproject/amp-wp#2862]
To replicate, set up a test environment with:

- WP 4.9.10
- AMP v1.2
- Yoast v11.6

Go to the "Edit Post" screen. Yoast meta box fails to load completely. Console shows JS errors: 

```
TypeError: m is undefined wp-components-1160.min.js:19:199958
TypeError: r is undefined wp-seo-post-scraper-1160.min.js:1:30350
```

Issue does not appear on WP 5.0+ using Classic Editor (or w/o Classic Editor, for that matter). Also not present w/ AMP 1.1.

I'll open this on the Yoast plugin as well.

**Comment by ethanclevenger91** [comment]
Someone [already reported it](https://wordpress.org/support/topic/yoast-seo-conflict-with-amp/) but never followed up. I've directed Yoast support here.

**Comment by westonruter** [comment]
I believe this is a duplicate of #2679. Please check that issue and the merged fix which you can test in the the latest beta pre-release: https://github.com/ampproject/amp-wp/releases/tag/1.2.1-beta1

**Comment by ethanclevenger91** [comment]
I believe you're correct - sorry, didn't see Yoast in the title of the issue when I searched.

That beta resolves the issue, btw. Closing as duplicate.
