### ISSUE TITLE
Notice error for featured image in Reader Mode template when using Multisite-Global-Media plugin

### ISSUE THREAD

**Issue by spacedmonkey** [ampproject/amp-wp#2869]
I am getting the following notice error 
```
Notice: Trying to get property 'post_excerpt' of non-object in /var/www/html/wordpress/wp-content/plugins/amp/includes/templates/class-amp-post-template.php on line 378
```

**Comment by westonruter** [comment]
What is the context for getting the error? What request/query are you making to WordPress?

**Comment by spacedmonkey** [comment]
This is just an a single post page. I am running PHP 7.3 if that is helpful.

**Comment by westonruter** [comment]
And you're requesting the AMP version, of course, so like /2019/07/23/Foo/amp/ ?

**Comment by spacedmonkey** [comment]
![Screenshot 2019-07-23 at 15 40 43](https://user-images.githubusercontent.com/237508/61721964-5326de80-ad61-11e9-95b7-a28309e7c77c.png)

I believe it related to the fact we using [Multisite-Global-Media](https://github.com/humanmade/Multisite-Global-Media) plugin. 

A simple fix would be change this [line](https://github.com/ampproject/amp-wp/blob/develop/includes/templates/class-amp-post-template.php#L378).
```
'caption'  => $featured_image->post_excerpt,
```
to  
```
'caption'  => get_the_excerpt( $featured_image ),
```

**Comment by westonruter** [comment]
In the case here:

https://github.com/ampproject/amp-wp/blob/518cfcb94d781a6ebf8e5fc9ea2507978eecff0a/includes/templates/class-amp-post-template.php#L361

What is `$featured_id` when using that plugin? And what is `$featured_image`?

**Comment by spacedmonkey** [comment]
The id is set, but set but the post doesn't exist. `$featured_image` is null.

**Comment by westonruter** [comment]
So why would `get_the_excerpt()` work? It would not obtain the featured image excerpt.

**Comment by spacedmonkey** [comment]
`get_the_excerpt` check if the post exists, and if it doesn't returns an empty things. 

`get_the_excerpt` also runs through filter, which this code should also be doing.

**Comment by westonruter** [comment]
Ok, sounds good. However the code that tries to do things with the `$thumbnail_id` should also be wrapped in a conditional to only do so if it is not `null`.

Want to open a PR?

**Comment by spacedmonkey** [comment]
Sorry for the relay here. I have created a PR https://github.com/ampproject/amp-wp/pull/3360 for review.

**Comment by westonruter** [comment]
I don't think this is worth putting through more QA, other than what @spacedmonkey has already done.

**Comment by spacedmonkey** [comment]
LTGM. No need for QA.
