### ISSUE TITLE
Conflict With Gutenberg Columns Block

### ISSUE THREAD

**Issue by jeffersonrabb** [ampproject/amp-wp#2870]
### Description Of Problem

With Gutenberg plugin (6.1.1) installed and AMP in **Transitional** or **Standard** mode, the Gutenberg columns block is unusable — when a column's block picker is invoked, it appears and then closes immediately.

Problem has been observed in:
- Chrome (Version 75.0.3770.100 (Official Build) (64-bit))
- Firefox (68.0.1)
- Safari (Version 12.1.1 (14607.2.6.1.1)).

### Video

https://cloudup.com/cjq9BdDF5TN

### Steps to Reproduce

1) Spin up a clean WordPress instance (e.g. using https://jurassic.ninja/)
2) Install Gutenberg plugin (6.1.1)
3) Create a post, add columns block, select "Two Columns, Equally Split" layout. 
4) Verify blocks clicking the + icons in either column correctly displays the block picker, and blocks can be selected normally.
5) Install AMP plugin and set it to "Reader Mode" (it will default to this)
6) Return to post and verify that column block continues to work normally. 
7) Switch AMP to "Transitional Mode" or "Standard Mode."
8) Return to post and attempt to add a block to the Columns block. Observe that the block picker appears and disappears immediately, which makes it unusable.

**Comment by westonruter** [comment]
Thank you for the thorough report.

I'm thinking this may be a problem with how the AMP validation logic is interacting with the Gallery block. Perhaps the AMP plugin is dispatching some state change which is causing the Gallery block popover to collapse? @swissspidy thoughts?

**Comment by jeffersonrabb** [comment]
> AMP validation logic is interacting with the Gallery 

Note that this is Columns block, not Gallery.

**Comment by swissspidy** [comment]
I was able to reproduce this. And yes, might be a state thing. Will try to look into it soon-ish.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create new regular post
2. Add columns block
3. Click on inserter/appender to add a new paragraph to the column
4. See that it works as expected, and the appender is not suddenly closing or anything

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
Was also reported here: https://github.com/WordPress/gutenberg/issues/16914
