### ISSUE TITLE
Story templates queried on regular post

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2873]
Steps to reproduce:
- Create a new post (doesn't happen with existing post).
- Start typing `/template` into the existing paragraph block.
- See the console.

AC: The story templates should be queried only in the context of an AMP Story post.

**Comment by miina** [comment]
The only differentiator for the two requests of reusable blocks (amp_story post vs any other post) seems to be the referer, basically, we could use `wp_get_referer()` and get the relevant data from there, ensuring displaying the templates only for AMP Story post type.

@swissspidy Do you have any concerns with that? If I remember correctly then you mentioned something.

**Comment by swissspidy** [comment]
I think that was for the KSES issue, not for reusable block part.

If that's the only difference between the two requests then I guess that's the only option. Not the nicest one I guess 🤷‍♂

**Comment by swissspidy** [comment]
## Testing instructions

### Stories experience disabled

1. Edit an _existing_ post
2. Search for "Template" in the block inserter
3. No templates should appear (i.e. "No blocks found")

---

1. Create a _new_ post
2. Search for "Template" in the block inserter
3. No templates should appear (i.e. "No blocks found")

---

1. Visit the [block management screen](https://story-test-wordpress-amp.pantheonsite.io/wp-admin/edit.php?post_type=wp_block)
2. No templates should appear

### Stories experience enabled

1. Edit an _existing_ post
2. Search for "Template" in the block inserter
3. No templates should appear (i.e. "No blocks found")

---

1. Create a _new_ post
2. Search for "Template" in the block inserter
3. No templates should appear (i.e. "No blocks found")

---

1. Visit the [block management screen](https://story-test-wordpress-amp.pantheonsite.io/wp-admin/edit.php?post_type=wp_block)
2. No templates should appear

---

1. Edit an _exiting_ story
2. Open template inserter
3. Templates should appear

---

1. Create a _new_ story
2. Open template inserter
3. Templates should appear

**Comment by kienstra** [comment]
@swissspidy, thanks for adding the test steps.

**Comment by csossi** [comment]
Fine until the last two scenarios - templates not appearing:
![image](https://user-images.githubusercontent.com/16945664/62554742-ab6cde80-b83f-11e9-8063-c958f35e15cd.png)

**Comment by swissspidy** [comment]
@csossi Can you please test the last two scenarios again? We deployed a new version briefly after your comment, and both @miina and I cannot reproduce the issue you're seeing here.

**Comment by csossi** [comment]
Verified in QA
