### ISSUE TITLE
Extracted video poster image doesn't use correct image size

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2881]
When adding a video block, it always uses the full size image URL instead of a more suitable one.

Same for the page background video, where we already have a suitable image size.

Originally added in: #903.

**Comment by swissspidy** [comment]
> When adding a video block, it always uses the full size image URL instead of a more suitable one.

Not sure what a "more" suitable image size would be though... Thoughts?

**Comment by swissspidy** [comment]
See #2835 for official recommendations / best practices.

**Comment by swissspidy** [comment]
To test:

1. Get a demo video for testing, e.g. https://www.pexels.com/video/blue-sky-with-white-clouds-above-a-body-of-water-1860684/
2. Create a new page
3. Add background media
4. Upload video
5. Notice that poster image is extracted and saved
6. Save and preview story.
7. Poster file name should have suffix `-2560x1440.png`

**Comment by csossi** [comment]
- selected Background Media and Upload from Media Library
- uploaded locally saved video
- on upload completion, selected and it appeared in Story, but poster area was blank:
![image](https://user-images.githubusercontent.com/16945664/62891040-bc6f9100-bd12-11e9-9fd0-05393c9acb88.png)

(plus, on saving and previewing, not seeing the png suffix

**Comment by westonruter** [comment]
Humm. Also, it shouldn't be a PNG but a JPEG.

**Comment by swissspidy** [comment]
Indeed JPEG makes more sense. Off the top of my head no idea why the image is just plain black.

**Comment by swissspidy** [comment]
Hmm maybe the video hasn‘t properly loaded by the time the image is extracted.

**Comment by westonruter** [comment]
@csossi what is the first frame of the video you tried? Does it fade in from black?

**Comment by swissspidy** [comment]
Created PR #3021 to address this.

**Comment by swissspidy** [comment]
@csossi Mind testing this again?

**Comment by csossi** [comment]
Poster image is fine - now only not seeing the -2560x1440.jpog suffix

**Comment by swissspidy** [comment]
@csossi The poster image is as big as the video originally is. The poster's maximum dimensions are `2560x1440`. Since the video you uploaded is only `960×540` that is totally correct. We don't upscale it to `2560x1440`.

**Comment by csossi** [comment]
Verified in QA
