### ISSUE TITLE
Fix style sanitizer test against login.css in WordPress trunk

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2891]
There was a [change in WordPress trunk today](https://core.trac.wordpress.org/changeset/45673) that changed the login.css stylesheet.

This breaks `\AMP_Style_Sanitizer_Test::test_css_import()` with the `local_css_files` data set which attempts to make some assertions against that stylesheet.

**Comment by swissspidy** [comment]
@westonruter Do you have bandwidth to look into this at some point? Maybe we can skip the test for now on trunk, or make the assertion less strict. Or ideally use some other, never-changing stylesheet.

**Comment by westonruter** [comment]
I'm on it.
