### ISSUE TITLE
E2E Tests: Block Position Controls

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2896]
* [ ] Verify functionality of the block positon controls.
  * [ ] Send to front
  * [ ] Send forward
  * [ ] Send backward
  * [ ] Send to back
* [ ] Verify that buttons do not appear when there is only one block on the page.
* [ ] Verify that forward/front buttons are disabled when the current element is the already the first one on the page.
* [ ] Verify that back/backward buttons are disabled when the current element is the already the last one on the page.

**Comment by swissspidy** [comment]
Looks like we can even verify that the assertive messages for screen readers are added properly: https://github.com/WordPress/gutenberg/blob/2f757fa8012edb5cd684a26adef9cb4e8c2158db/packages/e2e-tests/specs/links.test.js#L436-L446

**Comment by kienstra** [comment]
**Question About Screen Reader Messages**

Hi @swissspidy,
Hope you had a great end of the week.

>Looks like we can even verify that the assertive messages for screen readers are added properly: https://github.com/WordPress/gutenberg/blob/2f757fa8012edb5cd684a26adef9cb4e8c2158db/packages/e2e-tests/specs/links.test.js#L436-L446

It looks like the [Block Position controls](https://github.com/ampproject/amp-wp/blob/186c83ee4d8b0fc7d383ae27fd2891c9bb094ec7/assets/src/stories-editor/components/higher-order/with-amp-story-settings.js#L332) don't have assertive screen reader messages, like:

```js
speak( 'Example message', 'assertive' );
```

...though maybe I missed something.

Should I add an assertive message on clicking any of the 4 'Block Position' buttons, and test it in this e2e test?

<img width="508" alt="assertive-message" src="https://user-images.githubusercontent.com/4063887/62799830-6c40c680-baa7-11e9-9ba1-a9a57741031b.png">

**Comment by swissspidy** [comment]
Ah, my bad! I thought those were screen reader messages. Instead, the position controls use `aria-describedby` and `getBlockOrderDescription()`.

That function already has unit tests, so the e2e test doesn't have to cover all scenarios really.

**Comment by kienstra** [comment]
All good, thanks for looking at it.
