### ISSUE TITLE
E2E Tests: Featured Image

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2897]
* [ ] Verify that a featured image is set automatically when uploading a large enough image in an image block.
* [ ] Verify that a featured image is set automatically when uploading a large enough image as the page background.

**Comment by kienstra** [comment]
Hi @swissspidy,
Hope you're doing great. Would it help if I worked on this? 

Thanks, Pascal.

**Comment by swissspidy** [comment]
Sure thing!

**Comment by kienstra** [comment]
If it's alright, I added the WIP work for this to PR #2927, which was originally for the media file size warnings. It uses the helper function `uploadMedia()` in that PR.
