### ISSUE TITLE
Conflict With Yoast Plugin

### ISSUE THREAD

**Issue by spencerbeggs** [ampproject/amp-wp#2916]
This is a [cross-post from and issue I opened in the Yoast project](https://github.com/Yoast/wordpress-seo/issues/13314) as it is an issue between these two pluing. Not sure which end the issue could be resolved in.

* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

When the site has the official [AMP plugin v1.2](https://github.com/ampproject/amp-wp) for WordPress active in any mode the Yoast metabox appears truncated any you cannot use the metabox. There are two JS errors in the console:

`wp-components-1170.min.js?ver=11.7:19 Uncaught TypeError: Cannot read property '__' of undefined at Object.<anonymous> (wp-components-1170.min.js?ver=11.7:19)`

`wp-seo-post-scraper-1170.min.js?ver=11.7:5 Uncaught TypeError: Cannot read property 'analysis' of undefined at Object.<anonymous> (wp-seo-post-scraper-1170.min.js?ver=11.7:5)`

### Please describe what you expected to happen and why.

The Yoast metabox should be available in the backend.

### How can we reproduce this behavior?
1. Clean install of WP 4.9.10, use Twenty Nineteen Theme
2. Install AMP v1.2
3. Install Yoast 11.7
4. Vist Add new post page

### Technical info

* If relevant, which editor is affected (or editors): 
- [X] Classic Editor
- [ ] Gutenberg
- [ ] Classic Editor plugin

* Which browser is affected (or browsers): 
- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Other 

#### Used versions
* WordPress version: 4.9.10
* Yoast SEO version: 11.7
* AMP version: 1.2
* Gutenberg plugin version: 
* Classic Editor plugin version: 
* Relevant plugins in case of a bug: 

* Tested with theme: Twenty Nineteen

**Comment by westonruter** [comment]
@spencerbeggs I believe this is a duplicate of #2679 and #2862, being fixed in #2688. Please test the most recent beta: https://github.com/ampproject/amp-wp/releases/tag/1.2.1-beta1

**Comment by spencerbeggs** [comment]
Hi, @westonruter, thanks for the quick reply. I can confirm that the beta fixes this issue.
