### ISSUE TITLE
Investigate feasibility of generating source maps for amp-custom CSS

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2917]
It can be difficult to debug CSS on an AMP page since the `amp-custom` style consists of the enqueued stylesheets and inline styles all minified, tree-shaken, and concatenated together. During the processing of the stylesheets by the sanitizer, it would be interesting if it could possibly generate a source map for the resulting CSS.

The generation of sourcemaps would likely be expensive and it would likely have to be performed at runtime, so if it is possible it should only be enabled in a development mode (e.g. `WP_DEBUG`).

**Comment by swissspidy** [comment]
That would be really slick!

Looks like sourcemaps can be referenced by URL only, so it'd probably need to be saved as an actual file somewhere.

----

A quick search revealed this library as potentially useful for creating a sourcemap with the correct format: https://github.com/axypro/sourcemap

**Comment by westonruter** [comment]
Yeah, referencing the sourcemap by a URL will complicate things, since it will mean the external URL will need to be able to re-evaluate the CSS from the style sanitizer to compute the sourcemap, taking into account all of the tree shaking and enqueued stylesheets. But this avoids another complication, as if the whole sourcemap data were included as a CSS comment then it would run against the 50KB limit for the element.

So since the sourcemap must be external, the feasible way to achieve this seems to be to introduce a new query parameter added to any AMP page which would cause the sourcemap JSON to be served. For example, given an AMP page at https://example.com/about/?amp the `style[amp-custom]` element could end with:

```css
/*# sourceURL=amp-custom.css */
/*# sourceMappingURL=https://example.com/about/?amp_custom_css_sourcemap */
```

When a request is made with the `amp_custom_css_sourcemap` query parameter, then this would be a signal to the `\AMP_Theme_Support::prepare_response()` method to obtain the sourcemap data to return in an `application/json` response, rather than returning the post-processed HTML as normal.

I think this will actually work.
