### ISSUE TITLE
Custom HTML block causing validation error

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2923]
To reproduce:
- Add Custom HTML block
- Add any content, e.g. "Hello World"
- Save
- Refresh

AC: Custom HTML block should either work as expected or not be visible in the Inserter.

**Comment by westonruter** [comment]
Note the Custom HTML block needs to be present to ensure that block validation errors can be resolved. See #2256/#2254.

**Comment by miina** [comment]
Should get fixed within #2906.

**Comment by miina** [comment]
Instructions for testing:
- Add a Custom HTML block.
- Add some content.
- Save and refresh.
- Verify that the block still shows without errors.
- Verify that the content is displayed as expected in the front-end.

**Comment by csossi** [comment]
Verified in QA

saved and refreshed:
![image](https://user-images.githubusercontent.com/16945664/62891867-dad68c00-bd14-11e9-873c-2d53f336469a.png)

front-end
![image](https://user-images.githubusercontent.com/16945664/62891891-e9bd3e80-bd14-11e9-90a2-f5d7f4b5f243.png)
