### ISSUE TITLE
Indicate when active theme is designed for Reader mode

### ISSUE THREAD

**Issue by ktmn** [ampproject/amp-wp#2931]
Hello,

is there a way to disable Standard and Transitional mode for a theme? 

When you add support for Standard it shows a message "Your active theme is known to work well in standard or transitional mode.". I'd like to show a message ~"Your active theme only works in Reader mode." and have the Standard and Transitional mode radio inputs disabled or hidden. I've had multiple users switch to these modes and then get confused why everything is broken.

Thanks!

**Comment by westonruter** [comment]
That is not currently supported. The ideal is that themes add support for AMP in Standard/Transitional modes, and not to add support via custom Reader mode templates. Is that what your theme currently has?

**Comment by ktmn** [comment]
Yes, it was implemented before there were any other modes and I'm not looking to implement Standard/Transitional support for this theme any time soon or probably ever.

**Comment by westonruter** [comment]
@ktmn Do you have an `amp` directory in your theme which has AMP Reader mode templates?

I'm thinking such a message could be displayed when a theme does not have `add_theme_support( 'amp' )` but at the same time it _does_ have an `amp/` directory.

In that case, there could be something like this:

![image](https://user-images.githubusercontent.com/134745/62405500-c0e9bc00-b552-11e9-93dc-43d7f22bffde.png)

Something similar should be displayed when a theme _does_ indicate it has support for Standard/Transitional modes.

**Comment by ktmn** [comment]
Yes, it's got an `/amp` directory and does not define support for amp, so that would work.

**Comment by westonruter** [comment]
@ktmn Please test #3188.

**Comment by westonruter** [comment]
We'll close once the PR is merged.

**Comment by kienstra** [comment]
**Steps To Test**

1. Activate a theme that doesn't call `add_theme_support( 'amp' )`, and isn't a core theme, like Twenty Nineteen
2. Add an `amp/` directory to the theme 
3. In AMP Settings, select 'Standard' or 'Transitional' mode
4. Expected: There is a notice 'Your theme indicates it works best in Reader mode'. This should only appear after carrying out steps 1-3.

<img width="732" alt="new-notice-reader-here" src="https://user-images.githubusercontent.com/4063887/64321675-a312db00-cf86-11e9-9d1a-bd6fdd3d164b.png">

5. Expected: There should not be a link to the Ecosystem page:

<img width="985" alt="another-lnink" src="https://user-images.githubusercontent.com/4063887/64323099-6a283580-cf89-11e9-8d83-bb06b9c12411.png">
