### ISSUE TITLE
How can I preview AMP pages in Gutenberg?

### ISSUE THREAD

**Issue by TwisterMc** [ampproject/amp-wp#2934]
In the classic editor, next to the preview button was an AMP icon which allowed a user to preview the AMP page. In Gutenberg this button doesn't show and there doesn't seem to be a way to preview AMP pages in Gutenberg.

Is there a button someplace that I just don't see? Or is it not available in Gutenberg?

I do know I can just add `&amp=1` to the preview URL, but that's not client friendly. They like buttons. :)

**Comment by swissspidy** [comment]
I don't think we currently add an AMP Preview button in Gutenberg. But I suppose we should :-)

**Comment by westonruter** [comment]
Yeah, the classic editor has a preview button for AMP in Transitional and Reader modes (IIRC). We didn't add it to Gutenberg because... we probably didn't know how.

**Comment by TwisterMc** [comment]
Love the honesty. What about adding a text link below the _Enable AMP_ toggle that says _Preview AMP Post_? It doesn't have to be next to the preview button.

**Comment by swissspidy** [comment]
For comparison, here's the preview button in the classic editor:

![Screenshot 2019-08-05 at 13 00 06](https://user-images.githubusercontent.com/841956/62467881-131a1f80-b795-11e9-9e1f-206b4c63603c.png)

And here is the same section in the block editor:

![Screenshot 2019-08-05 at 13 02 20](https://user-images.githubusercontent.com/841956/62467896-19a89700-b795-11e9-9e54-751ab2c85057.png)

Since the preview button in the block editor could only be modified using direct DOM manipulation or perhaps by overriding `wp.editor.PostPreviewButton`. Both options would be prone to breakage when new versions.

So using the same `PluginPostStatusInfo` slot as we already do for the AMP toggle makes most sense to me.

I think that is a reasonably small enhancement to include in the next release. It might mean duplicating larges parts of the [`PostPreviewButton`](https://github.com/WordPress/gutenberg/blob/1df83a3998d1acbf224f96bbe4320b607747cb45/packages/editor/src/components/post-preview-button/index.js) component though.

**Comment by swissspidy** [comment]
Right, that's my suggested location as well. Needs lots of the logic from `PostPreviewButton` either way though in order to get the correct preview link, saveable status, to open the preview window etc. Otherwise the preview might not be accurate.

This is currently in the backlog, so we will get to it at some point.

**Comment by westonruter** [comment]
If possible to integrate with the existing Preview button, that'd be great, otherwise having a separate AMP preview button makes sense.

**Comment by cathibosco** [comment]
For consideration - Options 2 & 3 are improved UX/UI due to label "preview" being duplicated in option 1 - check it out for feasibility.
![2934--AMP-Preview](https://user-images.githubusercontent.com/4819761/64456837-22a3c580-d0bf-11e9-8051-945dcbe5f8d5.png)

**Comment by schlessera** [comment]
I think Option 2 is the nicest. The question is whether we can reliably decorate the existing Preview button here.

**Comment by cathibosco** [comment]
Agreed - yes that would be optimal.

**Comment by TwisterMc** [comment]
I concur; as long as the effort is not a lot more.

**Comment by kienstra** [comment]
Hi @schlessera,
Hope you had a great Friday.

Would you mind if I worked on this?

**Comment by schlessera** [comment]
@kienstra No, not at all. I saw you were already looking into it, so I skipped it and went to the first item in the back log already.

**Comment by kienstra** [comment]
OK, thanks! Have a great weekend!

**Comment by kienstra** [comment]
**Testing Steps**
*For when #3323 passes review*

1. Select 'Transitional Mode'
2. Create a new post
3. Enter any title
4. Expected: as long as AMP is enabled, there should be a button to preview AMP:

<img width="859" alt="amp-enabled-preview-button" src="https://user-images.githubusercontent.com/4063887/65406333-d2a64d80-dda4-11e9-9a0f-ea54d1283b60.png">

5. Toggle off 'Enable AMP' 
6. Expected: the preview button shouldn't appear anymore
7. Toggle the 'Enable AMP' button back on
8. Change the mode to 'Reader Mode'
9. Reload the post editor
10. Expected: the 'AMP Preview' button should still appear
11. Change the AMP mode to 'Standard' 
12. Reload the post editor
13. Expected: the 'AMP Preview' button should not appear anymore
14. Change the mode to 'Transitional'
15. Reload the editor
16. Click the 'AMP Preview button
17: Expected: it should open a new tab for an AMP URL:

 ![amp-preview-g](https://user-images.githubusercontent.com/4063887/65400301-04a8b700-dd87-11e9-8463-75d7f185ec26.gif)

**Comment by kienstra** [comment]
I'll make a screencast for this when #3323 is approved, as there might be changes to the button or the preview `<svg>`.

**Comment by swissspidy** [comment]
Can this new preview button be used to enhance the existing one as in option 2 mentioned above? I thought that was the consensus.

**Comment by kienstra** [comment]
**Option 2**

Hi @swissspidy,
Yeah, [Option 2](https://github.com/ampproject/amp-wp/issues/2934#issuecomment-528993707) would be really nice.

But I couldn't find a way to do that, other than maybe manipulating the DOM.

<img width="743" alt="dom-here" src="https://user-images.githubusercontent.com/4063887/65458684-c4dbe100-de13-11e9-8749-bace473c6b8a.png">

That [PostPreviewButton](https://github.com/WordPress/gutenberg/blob/0b4abfb5fad18b47d460678bab11669df273d5b1/packages/editor/src/components/post-preview-button/index.js) doesn't look to be filterable, nor does the [Header](https://github.com/WordPress/gutenberg/blob/0b4abfb5fad18b47d460678bab11669df273d5b1/packages/edit-post/src/components/header/index.js#L58) that uses it.

**Comment by swissspidy** [comment]
Yes, DOM manipulation was mentioned earlier in this thread as the potentially only possible way to do this.

@kienstra For the sake of testing, could you perhaps create a PR against your `add/block-editor-amp-preview` branch to explore this option?

**Comment by kienstra** [comment]
Sure, I'll create a PR to the `add/block-editor-amp-preview` branch to try DOM manipulation.

**Comment by kienstra** [comment]
**Steps To Test**

1. Enable 'Paired' mode
2. Create a new post 
3. Add any content to it
4. Click the AMP preview button:

<img width="1053" alt="amp-preview-here" src="https://user-images.githubusercontent.com/4063887/68605747-8e652e80-0472-11ea-9029-d92368fda75f.png">

5. Expected: A new tab opens with 'Generating AMP preview...', and it is a preview of the edited post:
<img width="1432" alt="generating-pr" src="https://user-images.githubusercontent.com/4063887/68606073-3a0e7e80-0473-11ea-969e-2faba50cce75.png">

6. Click the non-AMP 'Preview' button:

<img width="1053" alt="non-amp-preview-here" src="https://user-images.githubusercontent.com/4063887/68605909-e69c3080-0472-11ea-8d29-1d20d62c4af4.png">

7. Expected: This should still work as expected, showing a preview of the non-AMP post
8. Change the mode to 'Standard'
9. Go back to the same post
10. Expected: the AMP 'Preview' button should no longer appear, as there isn't a separate AMP URL

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Sorry for the lack of testing instructions earlier. Here are some instructions above, and it looks like this is now deployed to the testing environment.

**Comment by csossi** [comment]
Verified in QA
