### ISSUE TITLE
Lightbox effect: Fails if image is aligned

### ISSUE THREAD

**Issue by jamesozzie** [ampproject/amp-wp#2936]
When using the `Add lightbox effect` option on a Gutenburg image block the lightbox effect fails if the image is aligned.  

Video of the issue [here](https://i.imgur.com/5zptllj.gif). 

Image block without alignment - lightbox works fine:
![imageblock](https://user-images.githubusercontent.com/41326532/62426586-83199e80-b6de-11e9-804a-54d25b246823.jpg)

Image block with alignment - lightbox fails:
![imageblock_aligned](https://user-images.githubusercontent.com/41326532/62426589-8e6cca00-b6de-11e9-93c2-53e8d6d3e08b.jpg)

WordPress [support question](https://wordpress.org/support/topic/lightbox-120/#post-11798665) on this issue.

Temporary workaround, adding the following to the aligned image:
`on="tap:amp-image-lightbox" role="button" tabindex="0"`

**Comment by swissspidy** [comment]
Looks like `\AMP_Img_Sanitizer::maybe_add_lightbox_attributes()` currently assumes that the `data-amp-lightbox` attribute is set on the parent element of `amp-img`. While that is true for an image without alignment, there's an extra `div` when it is aligned, as can be seen on that second screenshot.

https://github.com/ampproject/amp-wp/blob/3a7e0645c1ae99d837eb578fdb1112657465f084/includes/sanitizers/class-amp-img-sanitizer.php#L371-L396

**Comment by westonruter** [comment]
Build for testing: [amp.zip](https://github.com/ampproject/amp-wp/files/3553169/amp.zip) - 1.2.3-alpha-20190828T225520Z-7515ad11

**Comment by schlessera** [comment]
Testing instructions:
1. Add image block
2. Switch "Add lightbox effect" option to ON
3. Publish page
4. Verify on the frontend that a click on the image opens a lightbox
5. In the editor, change alignment on the image to center or align left or align right
6. Republish the page
7. Verify on the frontend that a click on the image still opens a lightbox

**Comment by csossi** [comment]
Verified in QA
