### ISSUE TITLE
Featured image notice shown even when AMP is disabled

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2954]
Currently we show the following notice in the post publish panel when the featured image is too small:

![Screenshot 2019-08-05 at 13 15 04](https://user-images.githubusercontent.com/841956/62469409-7e192580-b798-11e9-9aca-c4a0dd969cb0.png)

This is because of a Search Console recommendation that says images on AMP pages should be at least 1200 pixels wide.

I think we should not display that warning when AMP is disabled for the current post (by checking `isAMPEnabled()`).

**Comment by westonruter** [comment]
Please re-open if you disagree.
