### ISSUE TITLE
Consider adding a toggle to story editor to allow landscape view off or on - per story.

### ISSUE THREAD

**Issue by cathibosco** [ampproject/amp-wp#2969]
It would be useful to allow full landscape mode for any stories we need to on a "per story basis" with a toggle. Toggle landscape mode on or off as we choose. 

Having the ability to control the output on a per story basis would be very useful for editors because assets vary and user experience may not always require full landscape. It is wonderful to have full landscape, it just may not always be necessary. 😍

**Comment by westonruter** [comment]
This can be done now with the plugin I made which enables landscape support for a story if it has the `landscape` post tag: https://gist.github.com/westonruter/4e4ee2b5790c6218fab40a7b3f90331f

So the tag is essentially serving the purpose of the toggle.

**Comment by westonruter** [comment]
See #2409 for overall landscape support.

**Comment by cathibosco** [comment]
Terrific! Thank you Weston ⚡️

**Comment by jdelia** [comment]
Are you still planning to add a landscape toggle to the story document settings? I think that is the best option. For those that want that to be the default, they can set the filter to do so. 

I'm not a fan of using the 'landscape' tag, as it is usually included in search results and I'm wondering what value that would have for visitors. Would one want to view all of the stories using that tag? Would they think that is referring to viewing scenic landscapes?

**Comment by westonruter** [comment]
The landscape tag is just a temporary measure until #2409 is fully addressed. A tag was easy because no UI was needed for my little plugin. It could have added a toggle instead, but that would have taken longer. Just wanted to put together something quick and easy.

**Comment by jdelia** [comment]
Perfect. Thank you. Yes, I agree it is fine for a temporary measure. I am working on testing various archive pages for stories including categories and tags, hence my question. I'm going to leave the temporary landscape tag out of my next post - just focus on the story archive page for now.
