### ISSUE TITLE
Investigate drag & drop support in E2E tests

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2975]
I am extracting this from #2863, where we were having troubles testing the drag & drop functionality. See discussion at https://github.com/ampproject/amp-wp/pull/2863#pullrequestreview-269806036 for details.

My current guess for why it's not working is a conflict with Puppeteer and browser events related to mouse movements / dragging:

We currently use the `dragAndResize` utility, which is used in Gutenberg for testing the resizing of the spacer block. That block uses `ResizableBox`, which in turn uses `re-resizable`. That component listens to the `mousedown` / `mouseleave` / `mouseup` events.

We, on the other hand, use the block mover component to drag blocks, which listens to the `dragend` event. Which Puppeteer does not seem to send when interacting with the mouse...

I found these related issues:

https://github.com/GoogleChrome/puppeteer/issues/1265
https://github.com/GoogleChrome/puppeteer/issues/343
https://github.com/GoogleChrome/puppeteer/issues/423

The latter one contains an interesting approach with using multiple steps for the mouse move part, but that didn't seem to work in my quick testing.

**Comment by kienstra** [comment]
Hi @swissspidy,
That's great that you looked at this, great links to issues above.

Like you mentioned, I also saw that passing the `steps` option to `mouse.move` didn't enable dragging, [like here](https://github.com/GoogleChrome/puppeteer/issues/423).

```js
await mouse.move(innerWidth/2+200, innerHeight/2, {steps: 100})
```
