### ISSUE TITLE
Create RTL versions for all stylesheets

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#2976]
Extracting this from #2972.

Right now we only have RTL versions for the stylesheets created by webpack, which is just a small part of all the CSS.

We can also look into using PostCSS for all these stylesheets, which allows us to use things like `postcss-themes`

**Comment by swissspidy** [comment]
PostCSS would also allow us to have a minified version of the admin bar stylesheet, so we don't have to do things like `wp_styles()->registered['admin-bar']->extra['suffix'] = '';`  (see https://github.com/ampproject/amp-wp/pull/2972/files#diff-2585472f207548f626a43a7ff3cab922)

**Comment by westonruter** [comment]
@swissspidy This is resolved now, right?

**Comment by swissspidy** [comment]
Yes indeed.

PostCSS can be considered at some later point.
