### ISSUE TITLE
Implement flat text background scrim (support “data-text-background-color” attribute)

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2982]
_Edit by @swissspidy:_

Documentation: https://amp.dev/documentation/components/amp-story/#data-text-background-color

> The `data-text-background-color` attribute highlights the text of the element with a specified color. To highlight the entire block, add this attribute directly to the text element. To only highlight the text, add the attribute and text to an inner . Note that works anywhere inside an `<amp-story-page>`, not just in `<amp-story-grid-layer>`.

[Example 1](https://github.com/ampproject/amphtml/blob/ddd07fdbba8985d968b1c2d495500a8c1d4607a9/extensions/amp-story/img/text-background-color-ex-1.png):

![text-background-color-ex-1](https://user-images.githubusercontent.com/841956/62689244-b9029f80-b9ca-11e9-96c4-50ef637f8632.png)

[Example 2](https://github.com/ampproject/amphtml/blob/ddd07fdbba8985d968b1c2d495500a8c1d4607a9/extensions/amp-story/img/text-background-color-ex-2.png):

![text-background-color-ex-2](https://user-images.githubusercontent.com/841956/62689262-c15ada80-b9ca-11e9-8d6f-57a771766c3b.png)

I think example 2 is already possible with our existing text background color support.

Example 1 can be achieved by using Gutenberg's [Format API](https://developer.wordpress.org/block-editor/tutorials/format-api/), which makes it possible for developers to add custom buttons to the formatting toolbar and have them apply a _format_ to a text selection (e.g. bold, italic, or in this case background color).

https://wordpress.org/plugins/advanced-rich-text-tools/ is an example plugin that already allows adding an inline background color. We could do the same, just with different markup that uses the `data-text-background-color` attribute.

That attribute can have any color that `background-color` in CSS supports ([source](https://github.com/ampproject/amphtml/blob/2a2055e2857cf5eec7b9e53bdf44004adfdfb4c7/extensions/amp-story/1.0/utils.js#L289-L316)).

**Comment by swissspidy** [comment]
**Testing instructions**

1. Create new text block with some content
2. Select some text in it using the mouse and use the text & highlight color buttons in the block toolbar to change the text's (background) color.  
  See https://github.com/ampproject/amp-wp/pull/3033#issuecomment-521828971 for an example.
3. Verify that text and background color for the selected text have changed
4. Verify that text and background color as displayed in the editor matches the display on the frontend

**Comment by westonruter** [comment]
So ultimately `data-text-background-color` was not used here, correct?

**Comment by swissspidy** [comment]
@westonruter Correct. I couldn't find a way to use `data-text-background-color` on the frontend and an inline style in the editor. Unless we'd basically mimic `data-text-background-color`'s behavior by messing with the DOM, which I deemed unreliable

**Comment by csossi** [comment]
Verified in QA

**Comment by cathibosco** [comment]
https://youtu.be/89wRTn36Tvw
