### ISSUE TITLE
Texts display empty in Templates

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2997]
Steps to reproduce:
- Open Template Inserter
- Observe the Text blocks in template previews -- placeholders display instead of the texts, and the blocks are also inserted empty.

Also, any previously (e.g. from 2 days ago) saved Text blocks seems to display empty.

<img width="196" alt="Screenshot 2019-08-08 at 18 36 57" src="https://user-images.githubusercontent.com/3294597/62716893-904eca00-ba0b-11e9-9f31-71c6e966c3ba.png">

**Comment by schlessera** [comment]
I have only placeholders for most templates. But 2 of them seem to display actual text. Here's an example of one with text and one with placeholders right next to each other:
![Image 2019-08-08 at 5 46 02 PM](https://user-images.githubusercontent.com/83631/62717617-7c539a00-ba04-11e9-924d-c57080b270d8.png)

The other one with real text is the Game Of Thrones one.

**Comment by schlessera** [comment]
Also note: When you insert one of these templates, you also get the same issue (placeholder, instead of actual text) except for the ones that work.
So at first glance, I'd say it is a problem of populating the templates properly, not of display.

**Comment by miina** [comment]
Looks like the ones that show the actual text are Quote, Title, and Author blocks, etc. So basically the issue is with the Text block only.

Thanks for testing!
