### ISSUE TITLE
Regression Testing - Post-Deployment (Block Elements)

### ISSUE THREAD

**Issue by csossi** [ampproject/amp-wp#3000]
Testing for the following blocks:

**Verify all for Front-End integrity (preview)**

**Text/Page Title**
- editing
- moving
- font family change
- resizing 
- rotating
- colour 
- opacity
- animation types

Where applicable, repeat with autofit=OFF and its associated font size settings

**Author/Date**
- editing
- moving
- font family change
- resizing 
- rotating
- colour 
- opacity
- animation types

Where applicable, repeat with autofit=OFF and its associated font size settings

**Video**
- selection
- moving
- resizing
- rotating
- caption on/off
- loop on/off
- animation types
- poster image

**Image**
- selection
- moving
- resizing (by handles)
- resizing (by sidebar - dimensions, %, etc.)
- rotating
- alt-text
- caption on/off
- animation types

**Quote**
- editing
- moving
- resizing
- rotation

**CTA**
- editing
- colour
- verify page 2+ only (CTA option shouldn't be available for page 1)

**List**
- editing
- moving
- resizing
- rotating
- animation types

**Custom HTML**
- editing
- moving
- rotating
- animation types

**Comment by swissspidy** [comment]
@csossi What's with this issue? Can it be closed?
