### ISSUE TITLE
Regression Testing - Post-Deployment (Global/Document Elements)

### ISSUE THREAD

**Issue by csossi** [ampproject/amp-wp#3001]
Global or "Document" features

**Test the following:**

Sidebar:
- set background video
- set background colour
- set background colour opacity
- page advance options (manual, etc.)

- template loading/selection
- elements reordering (left side)
- reordering pages button
- top toolbar shortcuts

**Comment by swissspidy** [comment]
@csossi What's with this issue? Can it be closed?
