### ISSUE TITLE
Always replace `no-svg` class with `svg` if exists

### ISSUE THREAD

**Issue by felixarntz** [ampproject/amp-wp#3009]
The `AMP_Core_Theme_Sanitizer` includes a [method](https://github.com/ampproject/amp-wp/blob/develop/includes/sanitizers/class-amp-core-theme-sanitizer.php#L564-L581) to replace the `no-svg` class with a `svg` class on the document element. While this is used in the Twenty Seventeen theme, I think it would be useful to generically run this for every theme.

* Many themes take a core theme for inspiration when building certain features, and this is one of them (Twenty Seventeen is a good example for how to use SVG icons instead of the "old" way with an icon font).
* A theme adding the `no-svg` class would have its SVGs broken today without applying this same fix manually.

I think we can run this sanitizer snippet unconditionally because probably anyone that had a `no-svg` would want to have it replaced with `svg` if SVGs work (which we force in Twenty Seventeen already). Alternatively, if there's reason to suspect this as too "aggressive", we could also hide it behind an opt-in via theme support.

**Comment by swissspidy** [comment]
For reference, here's the method in question:

https://github.com/ampproject/amp-wp/blob/develop/includes/sanitizers/class-amp-core-theme-sanitizer.php#L564-L581

And here's a list of themes on WordPress.org that use `no-svg` in some way:

https://wpdirectory.net/search/01DJ2K30R1YGK5KSQVB9224S36

Not too many.

**Comment by felixarntz** [comment]
Thanks for that @swissspidy!

I still think the number is "many" enough for us to make this easier for them. :)

**Comment by westonruter** [comment]
Yeah, this probably makes sense to do generally. All browsers support SVG now, from IE9 and above. So I don't see any reason why `no-svg` should persist.
