### ISSUE TITLE
Template Inserter broken

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3016]
Steps to reproduce:
- Make sure Gutenberg is up to date.
- Open the Template Inserter

<img width="594" alt="Screenshot 2019-08-12 at 21 59 56" src="https://user-images.githubusercontent.com/3294597/62895003-9cfa5780-bd56-11e9-8958-148d65ec3128.png">

Todo:

- [x] Fix Template Inserter
- [x] E2E tests (#2887)

**Comment by miina** [comment]
Instructions for testing:
- Open the Template Inserter
- Verify that the Templates look OK and aren't all on top of each other.

**Comment by csossi** [comment]
Looks like it's loading with broken images:
![image](https://user-images.githubusercontent.com/16945664/63101909-1016f000-bf48-11e9-9bac-81c067eb5204.png)

![image](https://user-images.githubusercontent.com/16945664/63101935-215ffc80-bf48-11e9-81a3-cdd4bcd55a68.png)

**Comment by miina** [comment]
I'm not able to replicate this issue, the images display as expected.

@kienstra / @swissspidy Could you test if you can see the issue that Claudio pointed out?

**Comment by kienstra** [comment]
Sure, I'll test this in a bit if that's alright 😄

**Comment by kienstra** [comment]
**Works As Expected In My Browser**

Hi @miina and @csossi,
Having created a test story at:
https://story-test-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=2910&action=edit

...it looks like the template images appear. There's a slight delay, but I think that was there before:

![images-loading](https://user-images.githubusercontent.com/4063887/63188690-abcb5d80-c027-11e9-8bf2-5bd4e391aca0.gif)

**Comment by miina** [comment]
Thank you for testing, @kienstra.

Moving this back to QA to test again.

**Comment by csossi** [comment]
Verified in QA
