### ISSUE TITLE
Font Picker: Bundle list of Google Fonts

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3026]
As outlined in #2877, we need to download a JSON file of Google Fonts that we can then display in the font family picker.

* [ ] Download list of fonts to bundle in the plugin.
* [ ] Document process of how the JSON file can be downloaded and kept up-to-date.
* [ ] E2E (#2900 )

**Comment by westonruter** [comment]
> Download list of plugins to bundle in the plugin.

Plugins or fonts?

**Comment by swissspidy** [comment]
Fonts 😄

**Comment by spacedmonkey** [comment]
I have a WIP PR at #3110 that I wouldn't mind someone looking at before I continue. 

I think that we should refactor the fonts to lazy load, as I am worried about the performance of loading in 512kb into every admin request. 

This existing PR, also contains the API, something that should be remove from final release. The API key used should be linked to a Google account for security reasons.

**Comment by spacedmonkey** [comment]
In #3110, I have mark this PR as ready to review. However, before it merged, we need to generate a google font api key, and setup .env / travis environment varibles. Documentations will also need to be updated.

**Comment by spacedmonkey** [comment]
Screencast can be seen here. https://youtu.be/D8Yg7Yv4Los
