### ISSUE TITLE
wordpress gif image overstretched

### ISSUE THREAD

**Issue by bloodchow** [ampproject/amp-wp#3042]
this is my page https://zentobyte.com/my/malaysia-construction-industry/7-construction-technology-to-follow-in-2019/552/

the gif image overstretched till it touched both sides, how to rescale it to 400px width instead?

![gg](https://user-images.githubusercontent.com/48185838/63228978-ab9caf00-c22d-11e9-93e5-e6b5ddd89a44.JPG)

**Comment by westonruter** [comment]
@bloodchow Thanks for reporting this. Can you please test with [1.2.1-beta2](https://github.com/ampproject/amp-wp/releases/tag/1.2.1-beta2)? This was recently fixed: #2793 for #2792.

**Comment by bloodchow** [comment]
> @bloodchow Thanks for reporting this. Can you please test with [1.2.1-beta2](https://github.com/ampproject/amp-wp/releases/tag/1.2.1-beta2)? This was recently fixed: #2793 for #2792.

You appear to have installed the AMP plugin incorrectly. It is currently installed in the amp-1 directory, but it needs to be placed in a directory named amp. Please rename the directory. This is important for WordPress plugin auto-updates.

**Comment by swissspidy** [comment]
@bloodchow Delete the old `amp` folder and rename `amp-1` to `amp`, as the message indicates. Alternatively, delete the old plugin in the WordPress admin, download the ZIP file from GitHub, and then upload it to your site.
