### ISSUE TITLE
Font size changing after refresh

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3047]
Steps to reproduce:
- Add an author block.
- Resize the block to be quite long and quite narrow.
- Save
- Refresh

The result before refresh:
<img width="229" alt="Screenshot 2019-08-19 at 21 31 33" src="https://user-images.githubusercontent.com/3294597/63289848-c4a66e00-c2c8-11e9-8138-d3821626c882.png">

The result after refresh:
<img width="185" alt="Screenshot 2019-08-19 at 21 31 44" src="https://user-images.githubusercontent.com/3294597/63289858-c96b2200-c2c8-11e9-90f7-2e92160012ab.png">

**Comment by swissspidy** [comment]
**Testing instructions**

Steps to reproduce:
- Add an author block.
- Resize the block to be quite long and quite narrow.
- Save
- Memorize font size
- Refresh
- Verify that font size is the same as before

**Comment by csossi** [comment]
verified
