### ISSUE TITLE
amp-twitter sanitiser doesn't respect data-lang or data-conversation attributes

### ISSUE THREAD

**Issue by benbowler** [ampproject/amp-wp#3050]
Afternoon, I've been looking into the amp sanitiser for a project. I've noticed the `AMP_Twitter_Embed_Handler` class doesn't support the full range of attributes supported by the component: https://amp.dev/documentation/components/amp-twitter/

Would you accept this as a PR?

**Comment by benbowler** [comment]
If so what tag would you like me to build against?

**Comment by westonruter** [comment]
Yes of course! Please open the PR against the `develop` branch, which is the default branch.

However, are you looking at the `tweet` shortcode specifically? If so, then this should be actually get migrated to the Jetpack plugin which is what defines this shortcode normally.

**Comment by benbowler** [comment]
Good question, I'll test the `tweet` shortcode to make sure it supports those first.

**Comment by westonruter** [comment]
Related: #1753.
