### ISSUE TITLE
Unable to create AMP story with a video element

### ISSUE THREAD

**Issue by dublinranch** [ampproject/amp-wp#3058]
I installed the latest AMP plug-in and tried to create a story that has a mix of video (MP4) and images. The media was uploaded to WP. I used the video block in the editor. The video appears in the WP editor, but with an invalid element error ("Invalid element: amp-video") which means the story won't pass AMP validation. Is video supported in the beta of AMP stories? Screenshot attached.

<img width="951" alt="Screen Shot 2019-08-20 at 2 57 51 PM" src="https://user-images.githubusercontent.com/14243203/63387715-097ae500-c35b-11e9-9078-93e941558f73.png">

**Comment by swissspidy** [comment]
Thanks for your report!

Could you please try installing the 1.2.1-RC1 version we published today to see if that still happens? Download: https://github.com/ampproject/amp-wp/releases/tag/1.2.1-RC1

**Comment by dublinranch** [comment]
Will do. I kept trying things and noticed that a "poster image" was required. I uploaded an image (not sure what it's for) and then the error went away.

**Comment by swissspidy** [comment]
Then I can happily tell you that with this new version the poster image will be automatically set for you :-)

To give some background: a poster image is used to show a preview of the video in case it hasn‘t loaded yet (for example on a slow connection). Usually the first frame of the video is used for that poster image.

**Comment by dublinranch** [comment]
Got it - figured that was the purpose and glad it will be set automatically now!
