### ISSUE TITLE
Global Inserter looks broken on upstream develop branch

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3062]
Looks like some changes to the inserter style were implemented which look broken on AMP Stories:

<img width="384" alt="Screenshot 2019-08-21 at 18 03 09" src="https://user-images.githubusercontent.com/3294597/63443798-1c1a1a80-c43e-11e9-9f12-47fe26e4c5dd.png">

This change hasn't been released yet but we'll likely need to address this thinking of the release.

**Comment by miina** [comment]
Instructions for testing:
- Open global block inserter
- Verify that it doesn't look broken (see the [description](https://github.com/ampproject/amp-wp/issues/3062#issue-483479449) to see how it's not supposed to look like)

**Comment by csossi** [comment]
Verified in QA:
![image](https://user-images.githubusercontent.com/16945664/63520159-3eee1280-c4c2-11e9-95a3-55c3eb905615.png)
