### ISSUE TITLE
Discovery surrounding UI for color palettes

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#3067]
We need to look into how best to display the option of selecting a color palette within the editor. Please consider, the need for customized colors to be utilized alongside a selected palette.

**Comment by cathibosco** [comment]
@dero and I reviewed some concepts noted above and recommend breaking this work into 3 technical stages:
1. **Palette Selector** Make it possible for editors to choose from a dropdown selection of palettes 
2. Make it possible to preview the colors for each palette with a  **Palette Preview** by adding the colors to the dropdown menu item as a preview.
3. Make it possible to add custom colors to the **Custom Palette**

**Comment by cathibosco** [comment]
![1-AMP Beta - Background Media and Color Layers@2x](https://user-images.githubusercontent.com/4819761/63953269-08c70a80-ca4f-11e9-9481-2722039f05a8.png)
![3-AMP Beta - Background Media and Color Layers@2x](https://user-images.githubusercontent.com/4819761/63953340-28f6c980-ca4f-11e9-8680-46734374542b.png)
![4-AMP Beta - Background Media and Color Layers@add to defaults](https://user-images.githubusercontent.com/4819761/63953403-475cc500-ca4f-11e9-98ed-e3a910024288.jpg)

**Comment by dero** [comment]
@cathibosco How do you think the users should _remove_ the custom colors?

**Comment by cathibosco** [comment]
@dero 
Currently the rectangular box (visual indicator shows the "active" color. 

Currently we have a second level of visual indicator(s) showing the "active color" when the color is "in the palette" with circle and checkmark.

The active color is **changed** by adding a new custom or clicking on different color in the palette.  
The active color is **removed** when an editor uses the "clear" button all background color is removed.

It would be intuitive to have a + (plus- see mock ups) as the next possible color at the end of a palette
It would be intuitive to have the first color in all palette be "null" for NO background color

That might leave room for a remove color from palette in place of the clear button

or

The ability to drag a color off a palette to remove it would be useful.

or with right click remove color from palette... although I do not think we have that baked in yet?

Check this out:
![5-AMP-Beta---Background-Media-and-Color-Layers-add-to-defaults](https://user-images.githubusercontent.com/4819761/64129160-6ed1cb80-cd88-11e9-98c3-2d5fa87b1981.png)
![5-clean-AMP Beta - Background Media and Color Layers-add to defaults](https://user-images.githubusercontent.com/4819761/64129161-6ed1cb80-cd88-11e9-9ff6-488c778a722f.jpg)

**Comment by cathibosco** [comment]
Also - The checkmark is not necessary if we have a WordPress blue outline on the "active" color. It will make it more useful and intuitive for the editor to manage their work to be able to visually see the color better too. : 
![7-AMP-Beta---Background-Media-and-Color-Layers-add-to-defaults](https://user-images.githubusercontent.com/4819761/64129612-22d45600-cd8b-11e9-81fd-b1214c01b0ae.png)

**Comment by cathibosco** [comment]
See how https://miro.com has a nice simple color tool. You can drag colors off the palette and the additional custom colors pile up at the end of the default palette. They do not have multiple palettes to chose from however. 
![Screen Shot on 2019-09-04 at 12-59-47](https://user-images.githubusercontent.com/4819761/64275932-b2f1d700-cf14-11e9-90aa-78e71dcd173b.png)

**Comment by cathibosco** [comment]
Here is a collection of palettes we can consider.... I can begin to formally create each color collection that we want to include. 
![AMP-Beta---Background-Media-and-Color-Layers-the-palettes-of-choice-2@2x](https://user-images.githubusercontent.com/4819761/64283117-cdcc4780-cf24-11e9-9f4b-ef35d53e77ac.png)

**Comment by dero** [comment]
@MackenzieHartung We propose to break the technical implementation into two stages per https://github.com/ampproject/amp-wp/issues/3067#issuecomment-526227863. In this stage we would extend the color picker to include a [palette select box](https://user-images.githubusercontent.com/4819761/63953269-08c70a80-ca4f-11e9-9481-2722039f05a8.png).

I propose we create a new ticket to handle the [palette preview](https://user-images.githubusercontent.com/4819761/63953340-28f6c980-ca4f-11e9-8680-46734374542b.png) in the dropdown as well as all functionality related to [custom colors](https://user-images.githubusercontent.com/4819761/64129160-6ed1cb80-cd88-11e9-98c3-2d5fa87b1981.png) handling.

**Comment by swissspidy** [comment]
@dero Can you create these two new issues you proposed? Then I think we can close this one.

**Comment by dero** [comment]
@MackenzieHartung @swissspidy Updated the [existing ticket](https://github.com/ampproject/amp-wp/issues/3068) for palettes implementation to cover for the first stage of implementation and created a [new issue](https://github.com/ampproject/amp-wp/issues/3213) for the second stage.

I believe we can close this issue now.
