### ISSUE TITLE
Implementation color palettes in editor

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#3068]
## Feature description

As a user, when creating/editing a story, I want to be able to select form ~5 color palettes to assist in making my story visually cohesive. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Dependent on Issue #3067.

* AC1: In all default color selection contexts, users can select a predefined color palette and populate the colors area with colors from that palette.
* AC2: Users can see a preview of colors within a palette when the selector is expanded

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by cathibosco** [comment]
Example:
![AMP Beta - Background Media and Color palettes](https://user-images.githubusercontent.com/4819761/64428980-ff5b2500-d082-11e9-9478-f2ff7548dd96.png)

**Comment by dero** [comment]
Let's also preview the colors defined by the palette in the dropdown as part of this ticket.

![image](https://user-images.githubusercontent.com/433570/64549874-f0e66500-d331-11e9-9145-19feb15e4728.png)

**Comment by cathibosco** [comment]
I am currently mocking up color palettes for us to implement... do we want hex codes (for example, #AFD645) and/or RGB values - I think we will need both so I am building the collections with both. Any other details I should gather for us? @dero

**Comment by pbakaus** [comment]
both, I'd say. Looping in @spacedmonkey. Jonny, should this work continue per your comment at https://github.com/ampproject/amp-wp/issues/3181#issuecomment-533568363, or should we pause this?

**Comment by spacedmonkey** [comment]
> both, I'd say. Looping in @spacedmonkey. Jonny, should this work continue per your comment at [#3181 (comment)](https://github.com/ampproject/amp-wp/issues/3181#issuecomment-533568363), or should we pause this?

I think we need to work out how we manage color and gradient in error. Color palettes are heavily linked to color selection in my mind. This issue maybe blocked until we can get #3182 #3181 worked out.
