### ISSUE TITLE
Add new story embed block, containing full iframe with full story

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#3072]
## Feature description

As a user, I want to be able to embed a story into an iframe.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

AC1 - Add a new story embed block that contains the full story within a full iframe.
AC2 - Need a way for users to chose which type of embed they want to use.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

* Added support for embedding stories inline in post content

**Comment by swissspidy** [comment]
Previously/related: #2301

**Comment by miina** [comment]
@jauyong @kmyram This issue doesn't have a related PR and the work hasn't started yet. It has AC-s defined but no Implementation Brief, probably would be good to send it to the IB column in the Definition board so that someone could start looking into it.

Thoughts?

**Comment by jauyong** [comment]
Hey @miina I noticed several like that as well in the AC column. I wasn't sure if there was a process needed to move things out of the AC column on the definition board. CC: @kmyram @ThierryA 


I see this is now in To Do on the Execution board. Let me know if you need anything else.

**Comment by swissspidy** [comment]
Moving this back to the definition board as this could really benefit from an IB first, as per our new process.
