### ISSUE TITLE
AMP Stories Frontend styles overwriting theme styles on archive page

### ISSUE THREAD

**Issue by jdelia** [ampproject/amp-wp#3085]
After creating an archive page for AMP Stories (we are using the Essence Pro theme), when viewing the archive page on the frontend, the AMP frontend styles for the `body, p { }` are overriding theme styles on the rest of the page. 

(https://github.com/ampproject/amp-wp/blob/c0486f39b316092ab102424a001c3ceb21bd0bc0/includes/class-amp-story-post-type.php#L956)
Here is a [screenshot](https://cl.ly/993a0e9467d3) from [https://cathibosco.com/stories/](https://cathibosco.com/stories/) - you can see that the post meta info `font-family` from the AMP body tag is replacing the` font-family` from the theme's body tag.

**Comment by westonruter** [comment]
Seems like a simple fix:

```diff
diff --git a/includes/class-amp-story-post-type.php b/includes/class-amp-story-post-type.php
index 381b9bcb..d0c26702 100644
--- a/includes/class-amp-story-post-type.php
+++ b/includes/class-amp-story-post-type.php
@@ -954,8 +954,7 @@ class AMP_Story_Post_Type {
 	 * @see /assets/css/amp-stories.css
 	 */
 	public static function add_custom_stories_styles() {
-		$post = get_post();
-		if ( ! $post || self::POST_TYPE_SLUG !== $post->post_type ) {
+		if ( ! is_singular( self::POST_TYPE_SLUG ) ) {
 			return;
 		}
```

Can you try that patch?

Also, how are you forcing the `amp_story` post type to have a post type archive? Are you modifying the post type object to include `has_archive`?

**Comment by jdelia** [comment]
Thanks Weston. I’ll try the patch tomorrow when I’m back at my computer. Yes I am modifying the post type object with `has_archive`.

**Comment by jdelia** [comment]
Following up... That patch worked. I've pushed that up to cathibosco.com - all looks good.
