### ISSUE TITLE
Resizing causes multiselection

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3092]
To reproduce:
- Create at least two blocks.
- Ensure that either Page block is selected or none of the blocks is selected.
- Resize on of the blocks, e.g. over the other block.
- Observer the results: both blocks get selected while resizing.

**Comment by miina** [comment]
It looks like this might be an upstream issue instead. The `toggleSelection` should in theory disable being able to select blocks, however, tested it on a post and this is what happened when resizing an image so that the cursor overlapped with another block:
<img width="1099" alt="Screenshot 2019-09-03 at 14 39 02" src="https://user-images.githubusercontent.com/3294597/64173950-b031ac00-ce58-11e9-9622-35b65ec558cb.png">

Looks like `onSelectionChange` does not have the `this.props.isSelectionEnabled` correctly set -- it shows `true` for `isSelectionEnabled`, here:
https://github.com/WordPress/gutenberg/blob/85eaee36845864ff97fd98f71589863533c59386/packages/block-editor/src/components/block-list/index.js#L150-L157

@swissspidy You are just working on multiselection for being able to select non-consecutive blocks, any thoughts on this? Otherwise, I'll create an upstream issue.

**Comment by swissspidy** [comment]
Probably best to report this upstream separately, as apparently in my PR there I won't touch that code at all.

**Comment by miina** [comment]
OK, will report.

**Comment by miina** [comment]
Reported: https://github.com/WordPress/gutenberg/issues/17313

**Comment by swissspidy** [comment]
Did a first pass at an upstream PR: https://github.com/WordPress/gutenberg/pull/17359

**Comment by swissspidy** [comment]
https://github.com/WordPress/gutenberg/pull/17359 has been merged and will be in Gutenberg 6.5 🎉

**Comment by swissspidy** [comment]
**Testing Instructions**

1. Create at least two blocks.
1. Ensure that either Page block is selected or none of the blocks is selected.
1. Resize one of the blocks so the mouse cursor goes over the other block.
1. Verify that the two blocks get selected while resizing.

**Comment by csossi** [comment]
Verified in QA
