### ISSUE TITLE
Reusable blocks shouldn't show up in the Global Inserter

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3105]
Reusable blocks might contain blocks that are not allowed within AMP Story Pages and should not be allowed.

We could filter the post query so that on AMP Story post type it would only include reusable blocks which have `TEMPLATES_TERM` and `TEMPLATES_TAXONOMY` assigned (the opposite of what we're doing right now for non-Story post types).

**Comment by miina** [comment]
Testing instructions:
- Add a Reusable Block while being on a regular Post edit page.
- Go to AMP Stories
- Verify that the created reusable block does not show up in the global block Inserter and does not come up with searching by its name.

**Comment by csossi** [comment]
The reusable block I created doesn't come up when using the block inserter for Stories nor does it appear when I search by name (fine).

However, it also doesn't appear in the "Reusable Blocks" section for new Posts 

(created reusable block named "REUSE" - I can see it if I choose to manage reusable blocks)

**Comment by csossi** [comment]
Now it's appearing after I logged out of WP and then logged back in

**Comment by swissspidy** [comment]
@csossi I cannot reproduce this behavior. Sounds like a caching thing. Did you make sure the post and the reusable block were saved before going on to create a new post?
