### ISSUE TITLE
Text is not centered when not in edit mode

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3113]
Steps to reproduce:
- Add a text block (leave Auto fit text setting on.)
- Write "Hello" (or something else) in it.
- Resize the block to be quite long.

Results:
<img width="261" alt="Screenshot 2019-08-28 at 21 04 39" src="https://user-images.githubusercontent.com/3294597/63884941-82bbad00-c9d7-11e9-9bae-bdf15281b103.png">

Expected results:
The text should be vertically aligned in the middle.

**Comment by swissspidy** [comment]
**Testing instructions**

1. Add a text block
2. Make sure "Automatically fit text to container" is **on**
3. Write some text.
5. Verify that text is vertically centered
4. Resize block to make it quite tall
5. Verify that text is still vertically centered

**Comment by csossi** [comment]
Verified in QA:
![image](https://user-images.githubusercontent.com/16945664/64650081-4da65600-d3ec-11e9-977b-1cbf7a2cf2d3.png)
