### ISSUE TITLE
Error in required structured data element

### ISSUE THREAD

**Issue by hollisterca** [ampproject/amp-wp#3120]
Using AMP Version 1.2.2, WP 5.2.2
On Google Search Console under AMP I get the following warning. "Error in required structured data element".
I then check with AMP Test from Google
https://search.google.com/test/amp?utm_source=support.google.com%2Fwebmasters%2F&utm_medium=referral&utm_campaign=%207320015&id=ineGapRAijlrSXQYNIlkwQ
and I get the follwing for this sample URL: https://www.teawea.com/obwalden-anise-birds/amp/

Missing or invalid structured data item
A required property in your structured data is missing, misspelled, or has an invalid value.

Details:
![Screenshot from 2019-08-29 12-58-32](https://user-images.githubusercontent.com/23412806/63934956-c4db0200-ca5c-11e9-8a9e-58062f3a0241.png)

**Comment by swissspidy** [comment]
Hi @hollisterca

These are not errors, but instead warnings about missing data on your site.

If you check the structured data for the non-AMP version at https://www.teawea.com/obwalden-anise-birds/ you'll notice that the same warnings are being reported:

https://search.google.com/structured-data/testing-tool/u/0/?utm_source=search_console&utm_campaign=sc-amp-test#url=https%3A%2F%2Fwww.teawea.com%2Fobwalden-anise-birds%2F

So this is not an issue with AMP, but with the structured data your recipe that is added by Yoast SEO. So ideally you'd just add that missing information for your post.

If you have questions about Yoast SEO's handling of structured data, I recommend asking in the respective [support forums](https://wordpress.org/support/plugin/wordpress-seo/).
