### ISSUE TITLE
AMP images on local dev not displaying as on live site

### ISSUE THREAD

**Issue by jdelia** [ampproject/amp-wp#3143]
I’m running into an issue when testing locally - using LocalbyFlywheel. I've got a copy of my live site installed. 

On the local dev - the Images on AMP pages are not sizing properly. The AMP HTML outputs includes classes `amp-wp-unknown-size amp-wp-unknown-width amp-wp-unknown-height` - and the images displayed on the front-end **are smaller**.  The live site does not have those classes and images are sized as intended.

This only happens locally.  I've tested this on three separate local installs with different data - same result.

Any idea what might be causing this? Does it have something to do with getting `$dimensions_by_url` in the image sanitizer? 

If I disable the AMP plugin (1.2.2 or even 1.2.0) the images display as intended locally. If I disable all other plugins locally except AMP and still have the same issue.

Example - Live Site: 
<img width="1296" alt="Image 2019-08-29 at 3 53 31 PM" src="https://user-images.githubusercontent.com/3217274/63971734-345ceb80-ca75-11e9-8e36-7b0eafbe3be7.png">

Local Dev Site (exact copy):
<img width="1318" alt="Image 2019-08-29 at 3 55 15 PM" src="https://user-images.githubusercontent.com/3217274/63971822-71c17900-ca75-11e9-99f6-7875d23b7ee1.png">

**Comment by westonruter** [comment]
The issue is likely that the AMP plugin is not able to do the necessary loopback request to obtain the dimensions from the image. So yes, it probably has something to do with `AMP_Image_Dimension_Extractor`. Please do a check in Site Health specifically for the results of this test:

![image](https://user-images.githubusercontent.com/134745/63973276-47fd5780-ca5f-11e9-9e86-4f95f8a01236.png)

Aside: if this is not working then it is likely that you'll not be able to schedule any posts to publish in your Local environment either.

**Comment by jdelia** [comment]
Weston, confirmed. 
<img width="980" alt="Image 2019-08-29 at 4 38 07 PM" src="https://user-images.githubusercontent.com/3217274/63974862-b223f580-ca7b-11e9-8624-8a54ce794be1.png">

**Comment by jdelia** [comment]
I removed the SSL and ran the Site Check again. 

<img width="937" alt="Image 2019-08-29 at 4 44 30 PM" src="https://user-images.githubusercontent.com/3217274/63975161-573ece00-ca7c-11e9-932e-e1cfada27d6f.png">


The report looks good - but the image issue remains. 

<img width="646" alt="Image 2019-08-29 at 4 46 13 PM" src="https://user-images.githubusercontent.com/3217274/63975229-881f0300-ca7c-11e9-8bbb-dac52ba0b45d.png">

**Comment by westonruter** [comment]
This is probably a bug in Local. Apparently they need to install the SSL certificate inside the container.

**Comment by jdelia** [comment]
Thanks, Weston.

**Comment by jdelia** [comment]
Note: After adding the image back again using non-ssl - it works as expected. Site Health reports no loopback issue.
