### ISSUE TITLE
Update configuration to enable using class properties.

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3152]
Currently, it's not possible to use class properties, would be good to add this option for not having to bind all the functions.

Right now we have to do this:
```class Foo {
  constructor() {
    this.method = this.method.bind(this);
  }
  method() {
    ...
  }

  // method can now be invoked correctly bound to class regardless of scope
```
But could do this instead:
```class Foo {
  method = () => {
    ...
  }

  // method can now be invoked correctly bound to class regardless of scope
```

Thanks to @barklund for bringing this up and for the example.

**Comment by swissspidy** [comment]
Babel plugin that could enable this: [`@babel/plugin-proposal-class-properties`](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties)

Looks pretty straightforward.

**Comment by swissspidy** [comment]
Just gave it a quick try and while the code works well, there seem to be some inconsistencies with ESLint.
