### ISSUE TITLE
[AMP Stories] Add filter for allowing more video extensions

### ISSUE THREAD

**Issue by pradeep910** [ampproject/amp-wp#3168]
AMP story background media select option only allows mp4 videos for selection. 

We'd need to add a filter to allow more extensions like `.mov`, `.mkv`, `.flv`, `.avi` etc. to make it ready for Video Transcoding.

**Comment by thrijith** [comment]
I am currently editing these files and building the zip for temporarily adding other extensions.

https://github.com/ampproject/amp-wp/blob/f5cbc6f6a40d79edf4f245c0c6b031d273263c80/assets/src/stories-editor/constants.js#L110
https://github.com/ampproject/amp-wp/blob/8ff2ce74650322a0d2b1f6de60f92db9ad123ced/assets/src/common/helpers/index.js#L252-L254

I am working on adding a filter for the same, will update here once I am ready with the changes.
