### ISSUE TITLE
[amp-script] Are the amp scripts supported?

### ISSUE THREAD

**Issue by maciejmackowiak** [ampproject/amp-wp#3178]
Hi,
I was trying to use the [amp-script]
https://amp.dev/documentation/examples/components/amp-script/?format=websites
but it looks like they are cutted out.
Are the [amp-script] supported and maybe I'm doing something wrong or they are not supported yet?

Thanks
Maciej

**Comment by westonruter** [comment]
Yes, it is supported. What is the specific example code you are using?

**Comment by maciejmackowiak** [comment]
I was trying to use something like this:
https://amp.dev/documentation/examples/components/amp-script/?format=websites#basic-usage
and this:
https://amp.dev/documentation/examples/components/amp-script/?format=websites#inline-scripts

but in both cases the meta CSP header tag:
`meta name="amp-script-src" content="sha....">`

Is getting cut out and I get this in console(I belice it is related to this meta tag):

> [%s] %s has Content-Type: "%s". Only "application/javascript" is allowed. amp-script amp-script

And when I'm trying to use the inline script
`<script id="amp-inline-script" type="text/plain" target="amp-script">script conntent</script>';`
It's also getting cut out.

So maybe I'm doing something wrong?
Maybe you have a working example?

Thanks 
Maciej

**Comment by westonruter** [comment]
Yes, adding the script inline is not fully supported yet, in spite of the documentation explaining it. 

You can see the logic is commented-out in the validator spec: https://github.com/ampproject/amphtml/blob/1ca2c96570fdd48c469672d0d44327d95b7eb319/extensions/amp-script/validator-amp-script.protoascii#L27-L56

See https://github.com/ampproject/amphtml/issues/24309 and https://github.com/ampproject/amp.dev/issues/2807.

So at the moment, you should reference an external script and that script should be on the same domain as the page you are serving. Local scripts and cross-domain scripts require that additional CSP verification.
