### ISSUE TITLE
Enhance Gradient Functionality within Stories Editor

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#3181]
## Feature Description

As a user I would like to have enhanced gradient features to increase the visual impact of my stories.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AC1: Enable users to see a group of templated gradients (visually ideal)
* AC2: Templated gradients should allow for the following: linear gradients, radial gradients, multiple colors.
* AC3: Enable all templated gradients to be customizable
* AC4: Enable user to change the direction/angle of a templated linear gradient
* AC5: Enable a user to change the radial location for a radial gradient
* AC6: Enable user to add more than two colors for a gradient
* AC7: Enable user to specify breakpoint of a gradient when 2 or more colors exist
* AC8: Review Gutenbergs Gradient related plans, and look to see what can be extended to fit the criteria above. [PR 17603](https://github.com/WordPress/gutenberg/pull/17603)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by spacedmonkey** [comment]
Related: https://github.com/WordPress/gutenberg/pull/17154

**Comment by spacedmonkey** [comment]
Related: https://github.com/WordPress/gutenberg/pull/17169

**Comment by spacedmonkey** [comment]
Related https://github.com/WordPress/gutenberg/issues/16662#issuecomment-519243504

**Comment by spacedmonkey** [comment]
To summarize my research. 

The gutenberg team is working on some new options for how colours and gradients to blocks. 
- The colour and gradients are being broken into two components.
- New options are being added to have present gradients. I assume that either presents will work similar to the developer definable colours at theme setup. 
- Mentioned [here](https://github.com/WordPress/gutenberg/issues/16662#issuecomment-519243504), the gutenberg team are working on more complex user configurable gradients. Possibly allowing for 3 colour gradients and changing of the angel of gradients. 

The work on the new gradients work is not yet complete. However implementing should not be two hard, as it should be a matter updating / importing these new packages. To speed up these PRs being merged into gutenberg, we could help with the code review / contribute code to existing PRs. 

As these changes are handing upstream, it is unwise to go our own way with custom gradient options for the amp plugin.

**Comment by spacedmonkey** [comment]
Related: https://github.com/WordPress/gutenberg/pull/17603

**Comment by spacedmonkey** [comment]
I spent sometime code reviewing the gradient PR https://github.com/WordPress/gutenberg/pull/17603#issuecomment-538122253 . I am getting involved with this PR and people working on it. 

I will feedback when I have idea of how much work is required to get this PR merged.

**Comment by cathibosco** [comment]
Thanks for the links to current work being done. Let me also show these from our collective work. 
<img width="955" alt="Screen Shot 2019-10-08 at 1 44 12 PM 1" src="https://user-images.githubusercontent.com/4819761/66419575-56318280-e9d2-11e9-8296-a794e02016f9.png">

**Comment by cathibosco** [comment]
Here with the angle added: 
<img width="1440" alt="Screen Shot 2019-10-08 at 3 00 54 PM" src="https://user-images.githubusercontent.com/4819761/66424907-7e25e380-e9dc-11e9-8d29-5b2c021691da.png">

**Comment by cathibosco** [comment]
With angle settings:
<img width="956" alt="Screen Shot 2019-10-08 at 3 00 57 PM" src="https://user-images.githubusercontent.com/4819761/66424941-93027700-e9dc-11e9-890c-57e23e162586.png">
