### ISSUE TITLE
Update Color Picker, with Opacity, to Present a Better UX

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#3182]
## Feature description

As a user I want to see a more intuitive/visual dynamic color picker (including opacity) when selecting colors, with opacity option, currently in the editor.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AC1: A new display of the color picker will be implemented within the editor.
* AC2: The color picker will include opacity option
* AC3: The new color picker will display in all areas where color picker, and opacity, currently exist (e.g. page and blocks)

This is closely related to #3068 and #3213 

 
## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by spacedmonkey** [comment]
This ticket needs more details. Currently the background options for a page, already has opacity options. 

![Screenshot from 2019-09-23 12-06-52](https://user-images.githubusercontent.com/237508/65421104-d1a00b00-ddfa-11e9-96b1-dc2d0a678f76.png)

What sort of shade options would be required?

**Comment by pbakaus** [comment]
Jonny, should this work continue per your comment at https://github.com/ampproject/amp-wp/issues/3181#issuecomment-533568363, or should we pause this as well?

Re: shades: This refers to shades of primary colors, see Chrome DevTools Colorpicker, where you can long press to bring them up (I worked on this one ;-) ):

![image](https://user-images.githubusercontent.com/43004/65429607-bf33ca80-de16-11e9-82e1-522adff97ae3.png)

**Comment by cathibosco** [comment]
Regarding opacity in editors - this simple editor is a very useful example as well and may be worth looking at closer. We have used it as a model in other issues like the color palettes mock ups...

You see the results in the page and it has some simple break points that I am not sure about the usability on. 
Here is a look: 
![Screen Capture on 2019-09-23 at 12-44-52](https://user-images.githubusercontent.com/4819761/65445393-1c705180-de00-11e9-8cb1-92d734626c04.gif)




You can open a free account at https://miro.com and experience this.

**Comment by cathibosco** [comment]
Here is a low fi sketch of an option of moving the opacity selector up top in the panel so that it is not covered by added palette options...  (brain storming here) 

It might be useful to see the changes as they happen on the page and not just when you are using the color picker... 

Editors have a palette they are working with, select a color and can set the opacity. Preview is live on the page.

![AMP Beta - Background Media and Color Layers-palettes-panel-opacity](https://user-images.githubusercontent.com/4819761/65446094-9ead4580-de01-11e9-84be-d02224164dbf.jpg)

**Comment by cathibosco** [comment]
The shade picker above from Chrome dev Tools is nice... I''' keep an eye out for more options on that.

**Comment by cathibosco** [comment]
More resources:

https://github.com/edelstone/tints-and-shades

https://maketintsandshades.com/#9165e0

**Comment by spacedmonkey** [comment]
Some examples of open source color pickers. 

https://github.com/loicmahieu/material-ui-color-picker
https://github.com/casesandberg/react-color
https://github.com/react-component/color-picker

The material UI color picker looks the best of the lot.

**Comment by spacedmonkey** [comment]
React-color seems like the most usable of the packages I tested. `material-ui-color-picker` seems to based on React Color anyway. 

Here is an screenshot of the new colour picker while I was testing. It even includes colors defined in the theme. 

![Screenshot from 2019-09-24 17-07-17](https://user-images.githubusercontent.com/237508/65529803-b8788680-deee-11e9-8337-f2b47ea73ccf.png)

**Comment by spacedmonkey** [comment]
![Screenshot from 2019-09-24 17-19-07](https://user-images.githubusercontent.com/237508/65530233-70a62f00-deef-11e9-88dc-aff3dd43a9a6.png)
This slide is also available in react-color

**Comment by spacedmonkey** [comment]
![Screenshot from 2019-09-24 17-26-34](https://user-images.githubusercontent.com/237508/65530782-7bad8f00-def0-11e9-9389-84acbf23e921.png)
Chrome based color picker also available.

**Comment by cathibosco** [comment]
`"React-color seems like the most usable of the packages I tested. material-ui-color-picker seems to based on React Color anyway."`

This looks very useful @spacedmonkey  Nice discovery.

**Comment by spacedmonkey** [comment]
Interesting fact, gutenberg's color pickers, is [based on](https://github.com/WordPress/gutenberg/blob/f91e66ca2bcd9e1e7b97aa39c01f2888fc751712/packages/components/src/color-picker/index.js#L2-L7) React color.

**Comment by MackenzieHartung** [comment]
Shade Support was moved to a separate ticket: #3423
