### ISSUE TITLE
Consider using [amp-img] instead of [amp-anim] for gif's to support [amp-lightbox-gallery]

### ISSUE THREAD

**Issue by maciejmackowiak** [ampproject/amp-wp#3184]
There is no possibility to use [amp-lightbox-gallery] for gifs because AMP WP automatically uses amp-anim for gifs and [amp-anim] doesn't support lightbox

And as suggested here 
https://github.com/ampproject/amphtml/issues/24306#issuecomment-527688934
We could simply use amp-img instead of amp-anim

So perhaps simply remove this line of code
https://github.com/ampproject/amp-wp/blob/develop/includes/sanitizers/class-amp-img-sanitizer.php#L311

ampproject/amphtml#24306

**Comment by westonruter** [comment]
Here's a quick workaround plugin that forcibly converts all `amp-anim` to `amp-img` after the image sanitizer has done its conversions: https://gist.github.com/westonruter/1eeb2224004c0e904fa2a35fc92899c0

**Comment by westonruter** [comment]
In the AMP plugin it appears that it needs to be smarter than just checking if the `img` is a GIF. It should also be checking for the context, such as whether it is in an `amp-lightbox-gallery`. In such cases, it should go ahead and be an `amp-img` instead of an `amp-anim`.

**Comment by maciejmackowiak** [comment]
Thanks for so fast response,
I will test Your plugin but a bit later, and let you know if it's solving our problem.

**Comment by maciejmackowiak** [comment]
@westonruter 
Your plugin works.
Thanks a lot for help.

**Comment by archon810** [comment]
Fantastic - the workaround works https://www.androidpolice.com/2019/08/28/gmail-finally-adds-that-smooth-account-switching-gesture-apk-download/?amp.

We'll revert it when this ticket is eventually properly resolved.

Thanks @westonruter!

**Comment by westonruter** [comment]
I highly doubt that support for `amp-anim` will be added to `amp-lightbox-gallery`. Instead, I expect that it will be updated to just use `img` since `amp-img` is intended to be deprecated: https://github.com/ampproject/amphtml/issues/30442. When that happens we'll just pass through `img` elements, and make sure they have the required dimensions and attributes (e.g. `loading`).
