### ISSUE TITLE
Hook for remove AMP Stories feed from Header

### ISSUE THREAD

**Issue by luizeof** [ampproject/amp-wp#3190]
When you add a Google Podcast feed to the head of your site, no other feeds can be added to the header. Google says:

> The homepage cannot have another `<link type="application/rss+xml" rel="alternate">` element on it. The homepage must be available to Googlebot at the exact URL specified in the RSS feed. The homepage must have the following HTML element somewhere in the page code:

See the Google documentation: https://developers.google.com/search/reference/podcast/homepage-requirements

**AmpStories** feed was added on #2641.

There are some hook to remove the feed from header?

**Comment by westonruter** [comment]
Humm. This seems like a bug on the Google Podcast side of things. It is very common for a site to have multiple `rel=alternate` side of things. For example, on https://blog.amp.dev/ there is:

```html
<link rel="alternate" type="application/rss+xml" title="The AMP Blog » Feed" href="https://blog.amp.dev/feed/">
<link rel="alternate" type="application/rss+xml" title="The AMP Blog » Comments Feed" href="https://blog.amp.dev/comments/feed/">
```

Almost every WordPress site is like this.

I'll see if I can find out who to reach out to on the Google Podcasts team to address this.

**Comment by luizeof** [comment]
something like:
`remove_action( 'wp_head', 'print_feed_link', 3 );`

since the [feed is added here](https://github.com/ampproject/amp-wp/blob/85414053676e01b953820a11521436611b2ff973/includes/class-amp-story-post-type.php#L339).

**Comment by westonruter** [comment]
Sure, this will do that:

```php
add_action( 'init', function() {
	remove_action( 'wp_head', [ 'AMP_Story_Post_Type', 'print_feed_link' ] );
} );
```

However, this should only be needed temporarily to fix the symptom. I believe the underlying problem should be fixed on the Google Podcasts side of things and then this workaround can be removed.

**Comment by luizeof** [comment]
thanks @westonruter ... tested and works!
