### ISSUE TITLE
Non-fitted text blocks cannot be resized smaller

### ISSUE THREAD

**Issue by barklund** [ampproject/amp-wp#3199]
A non-fitted text block (a block with the default-enabled "Adjust font size automatically" turned off) cannot be resized to a smaller size.

**Steps to recreate:**

- Create a text block.
- Type some text.
- Switch off "automatically fit text".
- Resize the block.

**Expected result:**
- You can make the box any size you want (down to the configured minimum size).

**Actual result:**
- You can only ever make the box bigger than it was when you started resizing or keep it the same size.
- If you make the box bigger, this new size will be the new "minimum size" for future resizing.

**Comment by swissspidy** [comment]
That is indeed a bug. It should be possible to make the box just small enough so that the text is not cropped.

**Comment by barklund** [comment]
QA instructions:

- Create text box
- Disable "fit text to box"
- Add text
- Resize box and verify that it can be made smaller (down to the size of the text) as well as larger.

Outside the scope of this test:

- The box does not automatically scale up to fit content when pasting (or switching from fit to non-fit), if content is larger than box size (see bug #3291).
- The box acts weirdly when resized below minimum size when rotated (see bug #3290).

**Comment by csossi** [comment]
Verified in QA
