### ISSUE TITLE
iframe-format Hulu embeds are converted to amp-youtube elements

### ISSUE THREAD

**Issue by ethanclevenger91** [ampproject/amp-wp#3202]
Probably somehow related to whatever fixed #266. The following:

`<iframe width="512" height="288"src="http://www.hulu.com/embed.html?eid=JwB8oTlBc_BndPOX5NpuHw" frameborder="0"scrolling="no" webkitAllowFullScreen mozallowfullscreen allowfullscreen></iframe>`

Turns into:

`<amp-youtube layout="responsive" height="270" width="450"></amp-youtube>`

Which is invalid.

**Comment by westonruter** [comment]
I'm not seeing that… 

If I add it to a Custom HTML block like so:

![image](https://user-images.githubusercontent.com/134745/64447353-09cfeb80-d090-11e9-88dc-e58139af9dc8.png)

The generated AMP markup is:

```html
<amp-iframe width="512" height="288" src="https://www.hulu.com/embed.html?eid=JwB8oTlBc_BndPOX5NpuHw" frameborder="0" scrolling="no" allowfullscreen="" sandbox="allow-scripts allow-same-origin" layout="intrinsic" class="amp-wp-enforced-sizes">
	<span placeholder="" class="amp-wp-iframe-placeholder"></span>
	<noscript>
		<iframe width="512" height="288" src="https://www.hulu.com/embed.html?eid=JwB8oTlBc_BndPOX5NpuHw" frameborder="0" scrolling="no"></iframe>
	</noscript>
</amp-iframe>
```

**Comment by ethanclevenger91** [comment]
Hm, let me get more details and get back to you. May be an edge case, because this isn't dropped into a Custom HTML block.

**Comment by ethanclevenger91** [comment]
Oh someone hard-coded turning the embed code into an `amp-youtube` element at some point, hadn't seen that. Invalid. Thanks!
