### ISSUE TITLE
URL validation failed to due to the absence of the expected JSON-containing AMP_VALIDATION comment after the body.

### ISSUE THREAD

**Issue by jaiminrlogical** [ampproject/amp-wp#3207]
Hi 

I am facing this issues on my wordpress site : https://prnt.sc/p312ql
My site url is : https://www.rlogical.com/

As I want to increase the speed of the site on google page speed so as per recommendation I have installed this plugin but I am getting the above error.

**Comment by westonruter** [comment]
Please check your PHP error log for any fatal errors.

Also, while logged in to WordPress, try visiting a post with `?amp&amp_validate` in the URL. See if there is an error showing anywhere at the bottom of the page.

**Comment by jaiminrlogical** [comment]
@westonruter I have checked this way and still it is giving same error.

**Comment by westonruter** [comment]
But did you check the PHP error log for fatal errors?

**Comment by jaiminrlogical** [comment]
@westonruter 

I am getting this errors in error log:

PHP Warning:  Module 'dom' already loaded in Unknown on line 0
[Mon Sep 09 06:37:01.952253 2019] [mpm_prefork:notice] [pid 3306] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Mon Sep 09 06:37:01.952351 2019] [core:notice] [pid 3306] AH00094: Command line: '/usr/sbin/apache2'
[Mon Sep 09 06:39:49.678263 2019] [php7:error] [pid 3323] [client 165.227.73.133:38466] PHP Fatal error:  Uncaught Error: Call to a member function hasAttribute() on null in /var/www/html/wp-content/plugins/amp/includes/class-amp-theme-support.php:2089\nStack trace:\n#0 /var/www/html/wp-content/plugins/amp/includes/class-amp-theme-support.php(1768): AMP_Theme_Support::prepare_response('<!DOCTYPE html>...')\n#1 [internal function]: AMP_Theme_Support::finish_output_buffering('<!DOCTYPE html>...', 9)\n#2 /var/www/html/wp-includes/functions.php(4339): ob_end_flush()\n#3 /var/www/html/wp-includes/class-wp-hook.php(286): wp_ob_end_flush_all('')\n#4 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)\n#5 /var/www/html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)\n#6 /var/www/html/wp-includes/load.php(954): do_action('shutdown')\n#7 [internal function]: shutdown_action_hook()\n#8 {main}\n  thrown in /var/www/html/wp-content/plugins/amp/includes/class-amp-theme-support.php on line 2089, referer: https://www.rlogical.com/?amp&amp_validate=7c4ba2fa5c&amp_cache_bust=2288926177

**Comment by westonruter** [comment]
Interesting:

> PHP Warning: Module 'dom' already loaded in Unknown on line 0

This warning seems to indicate there is a problem with your PHP configuration.

The fatal error here:

> Fatal error: Uncaught Error: Call to a member function hasAttribute() 

Is coming from these lines:

https://github.com/ampproject/amp-wp/blob/1b38600c48fe4a929b4e243cb43af26839a309be/includes/class-amp-theme-support.php#L2088-L2091

The `$dom->documentElement` property here should never be `null`.  Can you log out what the `$response` that is being passed into `AMP_DOM_Utils::get_dom()` here:

https://github.com/ampproject/amp-wp/blob/1b38600c48fe4a929b4e243cb43af26839a309be/includes/class-amp-theme-support.php#L2046

**Comment by jaiminrlogical** [comment]
@westonruter 
Can you please let me know how can I solve this issue. 

Also let me know which PHP configuration I have to add?

**Comment by westonruter** [comment]
You didn't provide enough information.  As requested, please log out the `$response` that is being passed into `AMP_DOM_Utils::get_dom()`.

**Comment by jaiminrlogical** [comment]
@westonruter Ok, I will provide you details by tomorrow

**Comment by jaiminrlogical** [comment]
@westonruter 

Below is the log:

<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n   <meta charset="utf-8">\r\n   <meta name="viewport" content="width=device-width, initial-scale=1">\r\n   <title></title> \r\n   <meta name="revisit-after" content="3 days" />\r\n   <meta name="distribution" content="Global" />\r\n   <meta name="copyright" content="Copyright Rlogical Techsoft Pvt Ltd" />\r\n   <meta name="Owner" content="Rlogical.com" />\r\n   <link rel="icon" href="https://www.rlogical.com/wp-content/themes/logical/images/favicon.ico" type="image/x-icon"/>\r\n   \r\n   <link rel="stylesheet" href="https://www.rlogical.com/wp-content/themes/logical/css/master.css?ver="1568207938">\r\n\r\n      \n<link rel="manifest" href="/superpwa-manifest.json">\n<meta name="theme-color" content="#e8e8e8">\n<link rel="apple-touch-icon" sizes="192x192" href="https://www.rlogical.com/wp-content/uploads/2019/02/logo192.png">\n<link rel="apple-touch-icon" sizes="512x512" href="https://www.rlogical.com/wp-content/uploads/2019/02/final_rlogical_logo_black.png">\n\n<style amp-custom></style>\n\n<meta name="description"  content="Rlogical - A Leading Web and Mobile Application Development Company providing PHP, ASP.NET, Magento, WordPress, iOS and Android App Development Services." />\n\n<meta name="keywords"  content="Web Development, Mobile App Development, IT Outsourcing" />\n\n<link rel="canonical" href="https://www.rlogical.com/" />\n<meta property="og:type" content="website" />\n<meta property="og:title" content="Web and Mobile Application Development Company India" />\n<meta property="og:description" content="Rlogical - A Leading Web and Mobile Application Development Company providing PHP, ASP.NET, Magento, WordPress, iOS and Android App Development Services." />\n<meta property="og:url" content="https://www.rlogical.com/" />\n<meta property="og:site_name" content="Rlogical" />\n<meta property="og:image" content="https://www.rlogical.com/wp-content/uploads/2019/02/final_rlogical_logo_black.png" />\n<meta property="og:image:secure_url" content="https://www.rlogical.com/wp-content/uploads/2019/02/final_rlogical_logo_black.png" />\n<meta name="twitter:card" content="summary" />\n<meta name="twitter:title" content="Web and Mobile Application Development Company India" />\n<meta name="twitter:description" content="Rlogical - A Leading Web and Mobile Application Development Company providing PHP, ASP.NET, Magento, WordPress, iOS and Android App Development Services." />\n<meta name="twitter:image" content="https://www.rlogical.com/wp-content/uploads/2019/02/final_rlogical_logo_black.png" />\n\n<link rel='dns-prefetch' href='//cdn.ampproject.org' />\n<link rel='dns-prefetch' href='//www.google.com' />\n\t\t<style>\n\t\t\t.wp-block-gallery.is-cropped .blocks-gallery-item amp-img > img {\n\t\t\t\tobject-fit: cover;\n\t\t\t}\n\t\t</style>\n\t\t<link rel='stylesheet' id='amp-default-css'  href='https://www.rlogical.com/wp-content/plugins/amp/assets/css/amp-default.css?ver=1.2.2' type='text/css' media='all' />\n<script type='text/javascript' src='https://www.rlogical.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp'></script>\n<script type='text/javascript' defer src='https://www.rlogical.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>\n<script type='text/javascript' defer src='https://cdn.ampproject.org/v0.js' async></script>\n<script type='text/javascript'>\n/* <![CDATA[ */\nvar cnArgs = {"ajaxurl":"https:\\/\\/www.rlogical.com\\/wp-ajax\\/","hideEffect":"fade","onScroll":"no","onScrollOffset":"100","cookieName":"cookie_notice_accepted","cookieValue":"true","cookieTime":"2592000","cookiePath":"\\/","cookieDomain":"","redirection":"","cache":"","refuse":"no","revoke_cookies":"0","revoke_cookies_opt":"automatic","secure":"1"};\n/* ]]> */\n</script>\n<script type='text/javascript' defer src='https://www.rlogical.com/wp-content/plugins/cookie-notice/js/front.min.js?ver=1.2.46'></script>\n<link rel='https://api.w.org/' href='https://www.rlogical.com/wp-json/' />\n<link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://www.rlogical.com/xmlrpc.php?rsd" />\n<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="https://www.rlogical.com/wp-includes/wlwmanifest.xml" /> \n<meta name="generator" content="WordPress 5.2.3" />\n<link rel='shortlink' href='https://www.rlogical.com/' />\n<link rel="alternate" type="application/json+oembed" href="https://www.rlogical.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.rlogical.com%2F" />\n<link rel="alternate" type="text/xml+oembed" href="https://www.rlogical.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.rlogical.com%2F&#038;format=xml" />\n

**Comment by westonruter** [comment]
This is the value of `$response` here?

https://github.com/ampproject/amp-wp/blob/1b38600c48fe4a929b4e243cb43af26839a309be/includes/class-amp-theme-support.php#L2046

If so, why does the page not have the `<html>` element? It seems you may have some optimization plugin that is conflicting with the AMP plugin, such as one that adds `defer` to all scripts. What plugins do you have active?

**Comment by jaiminrlogical** [comment]
@westonruter 

We have autooptimize plugin installed. So is there any issue due to that?

**Comment by westonruter** [comment]
Try deactivating that plugin to see if that fixes the problem.

**Comment by jaiminrlogical** [comment]
@westonruter Ok, let me de activate it and check again

**Comment by jaiminrlogical** [comment]
@westonruter 
I have logged the $response after removing Autooptimise plugin and response here :

<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n   <meta charset="utf-8">\r\n   <meta name="viewport" content="width=device-width, initial-scale=1">\r\n   <title></title> \r\n   <meta name="revisit-after" content="3 days" />\r\n   <meta name="distribution" content="Global" />\r\n   <meta name="copyright" content="Copyright Rlogical Techsoft Pvt Ltd" />\r\n   <meta name="Owner" content="Rlogical.com" />\r\n   <link rel="icon" href="https://www.rlogical.com/wp-content/themes/logical/images/favicon.ico" type="image/x-icon"/>\r\n   \r\n   <link rel="stylesheet" href="https://www.rlogical.com/wp-content/themes/logical/css/master.css?ver="1568269898">\r\n\r\n      \n<link rel="manifest" href="/superpwa-manifest.json">\n<meta name="theme-color" content="#e8e8e8">\n<link rel="apple-touch-icon" sizes="192x192" href="https://www.rlogical.com/wp-content/uploads/2019/02/logo192.png">\n<link rel="apple-touch-icon" sizes="512x512" href="https://www.rlogical.com/wp-content/uploads/2019/02/final_rlogical_logo_black.png">\n\n<style amp-custom></style>\n\n<meta name="description"  content="Rlogical - A Leading Web and Mobile Application Development Company providing PHP, ASP.NET, Magento, WordPress, iOS and Android App Development Services." />\n\n<meta name="keywords"  content="Web Development, Mobile App Development, IT Outsourcing" />\n\n<link rel="canonical" href="https://www.rlogical.com/" />\n<meta property="og:type" content="website" />\n<meta property="og:title" content="Web and Mobile Application Development Company India" />\n<meta property="og:description" content="Rlogical - A Leading Web and Mobile Application Development Company providing PHP, ASP.NET, Magento, WordPress, iOS and Android App Development Services." />\n<meta property="og:url" content="https://www.rlogical.com/" />\n<meta property="og:site_name" content="Rlogical" />\n<meta property="og:image" content="https://www.rlogical.com/wp-content/uploads/2019/02/final_rlogical_logo_black.png" />\n<meta property="og:image:secure_url" content="https://www.rlogical.com/wp-content/uploads/2019/02/final_rlogical_logo_black.png" />\n<meta name="twitter:card" content="summary" />\n<meta name="twitter:title" content="Web and Mobile Application Development Company India" />\n<meta name="twitter:description" content="Rlogical - A Leading Web and Mobile Application Development Company providing PHP, ASP.NET, Magento, WordPress, iOS and Android App Development Services." />\n<meta name="twitter:image" content="https://www.rlogical.com/wp-content/uploads/2019/02/final_rlogical_logo_black.png" />\n\n<link rel='dns-prefetch' href='//cdn.ampproject.org' />\n<link rel='dns-prefetch' href='//www.google.com' />\n<link rel='dns-prefetch' href='//s.w.org' />\n\t\t<style type="text/css">\n\t\t\timg.wp-smiley,\n\t\t\timg.emoji {\n\t\t\t\tdisplay: inline-block !important; /* Patched from core, which had display:inline */\n\t\t\t\tborder: none !important;\n\t\t\t\tbox-shadow: none !important;\n\t\t\t\theight: 1em !important;\n\t\t\t\twidth: 1em !important;\n\t\t\t\tmargin: 0 .07em !important;\n\t\t\t\tvertical-align: -0.1em !important;\n\t\t\t\tbackground: none !important;\n\t\t\t\tpadding: 0 !important;\n\t\t\t}\n\t\t</style>\n\t\t\t\t<style>\n\t\t\t.wp-block-gallery.is-cropped .blocks-gallery-item amp-img > img {\n\t\t\t\tobject-fit: cover;\n\t\t\t}\n\t\t</style>\n\t\t<link rel='stylesheet' id='amp-default-css'  href='https://www.rlogical.com/wp-content/plugins/amp/assets/css/amp-default.css?ver=1.2.2' type='text/css' media='all' />\n<script type='text/javascript' src='https://www.rlogical.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp'></script>\n<script type='text/javascript' defer src='https://www.rlogical.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>\n<script type='text/javascript' defer src='https://cdn.ampproject.org/v0.js' async></script>\n<script type='text/javascript'>\n/* <![CDATA[ */\nvar cnArgs = {"ajaxurl":"https:\\/\\/www.rlogical.com\\/wp-ajax\\/","hideEffect":"fade","onScroll":"no","onScrollOffset":"100","cookieName":"cookie_notice_accepted","cookieValue":"true","cookieTime":"2592000","cookiePath":"\\/","cookieDomain":"","redirection":"","cache":"","refuse":"no","revoke_cookies":"0","revoke_cookies_opt":"automatic","secure":"1"};\n/* ]]> */\n</script>\n<script type='text/javascript' defer src='https://www.rlogical.com/wp-content/plugins/cookie-notice/js/front.min.js?ver=1.2.46'></script>\n<link rel='https://api.w.org/' href='https://www.rlogical.com/wp-json/' />\n<link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://www.rlogical.com/xmlrpc.php?rsd" />\n<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="https://www.rlogical.com/wp-includes/wlwmanifest.xml" /> \n<meta name="generator" content="WordPress 5.2.3" />\n

**Comment by westonruter** [comment]
I cannot. I do not know what is wrong. You'll have to share more information. Perhaps the Site Health info, including your active themes  and plugins.
