### ISSUE TITLE
Temporarily remove AMP Stories templates insertion 

### ISSUE THREAD

**Issue by ThierryA** [ampproject/amp-wp#3211]
Given that AMP Stories templates are going back to the drawing board in the upcoming month for various reasons, I suggest to remove the current template capabilities in the UI by keeping the "+" upper right button which would simply insert a blank page instead of triggering the templates dropdown.

**Comment by swissspidy** [comment]
**Testing Instructions**

1. Click on what was previously the story template inserter button:   
  ![Screenshot 2019-09-11 at 10 36 05](https://user-images.githubusercontent.com/841956/64681450-05d10e80-d480-11e9-9424-98a96a7a50fb.png)
2. Verify that it inserts a new blank page and focuses it

**Comment by csossi** [comment]
Verified in QA
