### ISSUE TITLE
Allow for custom palettes to be defined

### ISSUE THREAD

**Issue by dero** [ampproject/amp-wp#3213]
## Feature description

As a user, I want to be able to add certain colors to a "Custom" color palette and select this palette when creating/editing a story alongside the predefined palettes.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Dependent on #3067 #3068 

* AC1: Users are able to add and remove custom colors to a custom color palette.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by MackenzieHartung** [comment]
@dero all immediate labels are there. The two we will need to add are ticket size and sprint. Is this intended for Sprint 15? If so, I can add that label. Additionally, if you will be working on this just please add an estimation size when you begin work.

**Comment by dero** [comment]
@MackenzieHartung Thank you. And yes, unless we de-prioritize the feature, this is intended for Sprint 15.
