### ISSUE TITLE
Add remove button to block navigation

### ISSUE THREAD

**Issue by spacedmonkey** [ampproject/amp-wp#3221]
In the list of sidebar elements in the AMP stories, it allows you be reorder the elements. However, it doesn't allow you to remove these elements. This is a little confusing. I have mocked up a remove element button might look like. 

![Screenshot from 2019-09-10 13-14-44](https://user-images.githubusercontent.com/237508/64613141-5471a080-d3cd-11e9-9dea-4e48ab3930ea.png)

**Comment by cathibosco** [comment]
This looks good to me @spacedmonkey however we will want to look closer at the accessibility implications. Mouse, keyboard...
