### ISSUE TITLE
Style sanitizer contains a piece of logic that doesn't seem to have any effect

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3232]
The style sanitizer contains piece of logic that stores "$indices_by_stylesheet_element_id". However, the entire array is only assembled, but never used.

https://github.com/ampproject/amp-wp/blob/7ba9f26f72aed7560545fc0aa9f844eb20ad9598/includes/sanitizers/class-amp-style-sanitizer.php#L2907-L2910

This entire snippet could just be removed, to save processing time and memory.

**Comment by westonruter** [comment]
Curious: How did you find this logic was not being used?

**Comment by schlessera** [comment]
@westonruter PHPStorm actually shows this (at least with my current settings):

![Image 2019-09-17 at 6 49 24 PM](https://user-images.githubusercontent.com/83631/65062222-e3f1f300-d97b-11e9-9df6-a4f428fb1999.png)

You can see that the code is grayed out, which means it is not being used. When you hover over it with the mouse, you'll get additional information.

**Comment by schlessera** [comment]
Oh, I just noticed that this actually comes from a paid addon to PHPStorm: https://kalessil.github.io/php-inspections-ultimate.html

![Image 2019-09-17 at 7 02 54 PM](https://user-images.githubusercontent.com/83631/65063161-fa00b300-d97d-11e9-9e31-0def25657b59.png)

I can heartily recommend this plugin, and @kalessil is extremely responsive if you hit issues or have ideas for addiotional checks.
