### ISSUE TITLE
Redirect test with Google Optimize

### ISSUE THREAD

**Issue by jonathan-dejong** [ampproject/amp-wp#3244]
Hi!

I'm racking my brain trying to figure out if I can setup a google optimize redirect test with regex/wildcards which will split users between the amp version and the regular version of a page that fits my rules. 

Example:
`website.com/product/my-product`
`website.com/product/my-product?amp`

where `my-product` would be a wildcard/dynamic value in order to match *all* products. 
So a target like:
`website.com/product/*`
would split visitors to
`website.com/product/*`
and
`website.com/product/*?amp`

Anyone with experience of this? 
Any help would be very appreciated!

**Comment by jonathan-dejong** [comment]
To sort of answer myself in case someone else finds their way here in search of answers.
I *think* this can be done by using a regular product URL (in my example it's products) in the "original" URL field. And then setting just the `?amp` as a variation which will append to the "Original" URL.

Then setup the page targeting with regex. For me that means:
`When URL matches regex https://website.com/product/*`
`and URL does not end with ?amp`

I've yet to test this tho.

**Comment by swissspidy** [comment]
This sounds more like a general Google Optimize question rather than one specific to this plugin or even AMP in general. I recommend using the [Optimize Resource Hub](https://support.google.com/optimize) if there are still some unanswered questions. There you'll find a help center as well as community forums.

**Comment by jonathan-dejong** [comment]
You're right @swissspidy ! 

I think in my delirium I thought that this was the official AMP repo. 
In any case it's solved. 

Thank you, sorry for taking up your time!
