### ISSUE TITLE
Issue with keyboard cut to clipboard

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#3250]
This bug has been partially addressed in the development of keyboard copy/paste (#2996 ). However, this ticket has been created to individually track the specific bug that @spacedmonkey is working on.

**Comment by spacedmonkey** [comment]
Testing details. 
1. Create two text blocks with different text.
1. Cut block A (Using keyboard ctrl /control + x )
1. Change page a new page. 
1. Paste block onto new page using keyboard.
1. Cut block B (Using keyboard ctrl /control + x )
1. Change page a new page. 
1. Paste block onto new page using right click context menu.
1. Cut text or other information into clipboard (Using keyboard ctrl /control + x )
1. Paste into page (Using keyboard ctrl /control + p )
1. Cut block A (Using keyboard ctrl /control + x )
1. Create new story.
1. Paste block onto new page using keyboard.

**Comment by csossi** [comment]
Verified in QA
