### ISSUE TITLE
Discovery: Look in to keyboard cut/paste

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#3251]
There have been a few issues surrounding the ease/logic around cutting, and pasting, using keyboard commands. This Discovery is to take a holistic look at the solution, and potential gaps, causing issues.

**Comment by spacedmonkey** [comment]
Work continues at #3246

**Comment by spacedmonkey** [comment]
Closed via #3246

**Comment by swissspidy** [comment]
Didn't #3246 close #3250 specifically? And this here is just kind of a follow-up?
