### ISSUE TITLE
<iframe> height="100%" stripped to empty value throwing validation error

### ISSUE THREAD

**Issue by claudiopome** [ampproject/amp-wp#3277]
`<iframe src="https://landbot.io/u/H-22078-X2B4IWABAFJE2ROQ/index.html" width="100%" height="100%" frameborder="0">`

This code throws an error on the AMP Validator saying 

> The attribute 'height' in tag 'amp-iframe' is set to the invalid value ''. 

I checked #402 and it seems that % values on height attributes get stripped to empty by default? Am I missing something here?

**Comment by westonruter** [comment]
Percentage dimensions are not valid in AMP. The AMP plugin is currently passing through invalid units: https://github.com/ampproject/amp-wp/issues/2146.

Nevertheless, there is currently auto-conversion of `with=100%` to a `layout=fixed-height`:

https://github.com/ampproject/amp-wp/blob/93276f713e78abf546c1277ee34564a9c4bdd123/includes/sanitizers/class-amp-base-sanitizer.php#L318-L321

The question remains as to whether we can add some similar conversion for `height=100%`. This actually was done in #3209. Is this a similar scenario? Is your `iframe` absolutely positioned to stretch to its container's dimensions? If so, then that PR could be followed up with doing the same logic if an element has `width=100%` and `height=100%`.

**Comment by claudiopome** [comment]
Hi @westonruter. 

>Nevertheless, there is currently auto-conversion of `width=100%` to a `layout=fixed-height:`

Indeed. That's what happens, `layout` gets converted into `fixed-height` but the `height` value is empty

>Is your `iframe` absolutely positioned to stretch to its container's dimensions?

Yes, There's a container `div` with a `width="100%"` and `height="500px"` Here's is the actual code: 

`<div style="width: 100%; height: 500px; position: relative; overflow: hidden;"><iframe style="position: absolute; left: 0; right: 0; bottom: 0; top: 0; border: 0;" src="https://landbot.io/u/H-22078-X2B4IWABAFJE2ROQ/index.html" width="100%" height="100%" frameborder="0"></iframe></div>`

**Comment by westonruter** [comment]
Please test fix in #3295.
