### ISSUE TITLE
Discovery: Enable generation of Transformed AMP pages

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#3282]
This ticket is to determine logical next steps pertaining to enabling generation of transformed AMP pages.

Related to issue #958 .

Development related to this is currently blocked (https://github.com/ampproject/amp-wp/issues/958#issuecomment-531896531)

[AMP SSR Toolkit Implementation Guide
](https://docs.google.com/document/d/1lZl7UJ5eUrhwTmfbOZ7g-HFIgMnTeqGwfUxE98kALzU/edit#heading=h.fzwfkw32haw7)

**Comment by jauyong** [comment]
Notes from grooming:

- This is related to the prepared response @schlessera was working on. Need to take that and augment with new sanitizers and logic, then implement the optimized amp format which is a server side rendering
- PRs are still currently op on #958 (dependency on that)
- Refer to this doc: https://docs.google.com/document/d/1lZl7UJ5eUrhwTmfbOZ7g-HFIgMnTeqGwfUxE98kALzU/edit#heading=h.fzwfkw32haw7
- Discussed adapting our naming to match the naming of transformers in the doc.
