### ISSUE TITLE
Use aliases to import modules more easily

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3288]
In the JavaScript modules we import lots of things from locations like  `../../../common/constants` or `../../../../images/stories-editor/call-to-action.svg`. Those long relative paths are hard to grasp.

Using aliases we would be able to import such modules way easier.

Instead of typing `import {} from '../../../common/constants'` we could then just write `import {} from 'common/constants'`, or `import {} from 'stories/components';` instead of `import {} from '../../components'`

Aliases would need to be defined in a few places:

* webpack configuration, as [`resolve.alias`](https://webpack.js.org/configuration/resolve/#resolvealias).
* Jest configuration, as [`moduleNameMapper`](https://jestjs.io/docs/en/configuration#modulenamemapper-object-string-string) with some regex.
* ESLint configuration, as a custom [resolver](https://www.npmjs.com/package/eslint-plugin-import#resolvers) for [`eslint-plugin-import`](https://www.npmjs.com/package/eslint-plugin-import). Perhaps [`eslint-import-resolver-alias`](https://www.npmjs.com/package/eslint-import-resolver-alias).

Benefits:

* Less headaches when writing `import` statements
* Increased readability

Drawbacks:

* Added complexity to build setup

**Comment by swissspidy** [comment]
Related: https://github.com/WordPress/gutenberg/issues/16789

**Comment by westonruter** [comment]
Is this still relevant?

**Comment by swissspidy** [comment]
Let‘s close
