### ISSUE TITLE
Text block does not update height after pasting

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3291]
## Bug Description

As reported in #3259:

See https://github.com/ampproject/amp-wp/pull/3259#issuecomment-532610932 for where this might be happening.

## Expected Behaviour

Pasting arbitrary text should create a new text block with correct height

## Steps to reproduce

1. Copy text from somewhere
1. Click on story page
1. Paste via keyboard
1. Notice how newly added text block does not update its height

## Screenshots

![Screenshot from 2019-09-18 10-07-54](https://user-images.githubusercontent.com/237508/65135242-7d151e00-d9fd-11e9-97bf-406bad8a2cee.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Pasting arbitrary text should create a new text block with correct height

## Implementation brief

* Update `maybeUpdateBlockDimensions` so it correctly handles pasted blocks

## QA testing instructions

1. Copy text from somewhere
1. Click on story page
1. Paste via keyboard ( CTRL + V)
1. Verify height of text block is the height of the text.

## Demo

* https://youtu.be/X8i0Tb71QLc

## Changelog entry

* Improve calculating block dimensions when pasting text

**Comment by barklund** [comment]
A similar issue occurs when a fitted text box is switched to non-fit. The text can then outgrow the box and the box does not increase height automatically to fit the content.

**Comment by spacedmonkey** [comment]
Testing instructions 

1. Copy a chunk of text from another source, such [lorem-ipsum](http://generator.lorem-ipsum.info/_latin). 
2. Paste into text from clipboard using control + V 
3. When text is pasted appears in editor, the text should be set to auto fit unchecked and the text box should be the size of the text. 

See screenshot. 
![Screenshot from 2019-09-30 16-16-04](https://user-images.githubusercontent.com/237508/65892132-ab9bdd00-e39d-11e9-9130-398136c0555c.png)

**Comment by spacedmonkey** [comment]
Does this issue need a screencast?

**Comment by swissspidy** [comment]
> Does this issue need a screencast?

I don't think so. It's a bugfix, not a new feature.

**Comment by csossi** [comment]
Not seeing the resizing to content size here:
![image](https://user-images.githubusercontent.com/16945664/65990063-e1ea6280-e458-11e9-8184-361a2da40d5f.png)

**Comment by spacedmonkey** [comment]
@csossi Not seeing this locally. https://www.youtube.com/watch?v=UpK99SpqRsM&feature=youtu.be 

Are you sure you are testing again version will this fix in it?

**Comment by swissspidy** [comment]
Perhaps the change wasn't deployed yet, so yeah please try again :-)

**Comment by csossi** [comment]
Verified in QA

![image](https://user-images.githubusercontent.com/16945664/66324650-d59c5480-e8f3-11e9-8521-19554e948102.png)

**Comment by swissspidy** [comment]
I was unable to reproduce this, moving back to "To do" to check this again.

**Comment by spacedmonkey** [comment]
It seems like this broke in https://github.com/ampproject/amp-wp/pull/3529 as the `maybeUpdateBlockDimensions` function was changed by @miina . 

How the block height is only changed when the rotation is also changed. In #3644 I have also check to see if a block is `isPasted`.

**Comment by spacedmonkey** [comment]
Another demo - https://youtu.be/X8i0Tb71QLc

**Comment by csossi** [comment]
Rechecked after staging update - still seems to be a prob:
![image](https://user-images.githubusercontent.com/16945664/67808690-84ecc700-fa6d-11e9-8f1a-cd76eee4e2e0.png)

**Comment by spacedmonkey** [comment]
@csossi Can I have a video showing the error?

Here is a video of it working for me - https://youtu.be/X8i0Tb71QLc

**Comment by miina** [comment]
@csossi Could you also confirm if you're pasting the text into an existing Text block or into an empty Page. Note that this issue addresses pasting into an empty Page only.

**Comment by miina** [comment]
@csossi Moving this to QA for re-testing. Note that this issue addresses pasting into an empty Page only.

**Comment by csossi** [comment]
https://drive.google.com/file/d/1D5R0iVNgI6J5cgmcrf3fATR1jYSV2pyj/view

video added

**Comment by spacedmonkey** [comment]
@csossi That video shows passing into an existing text block. Not into a new empty page with no blocks. The issue you are seeing is documented #3650 .

**Comment by csossi** [comment]
Verified in QA
