### ISSUE TITLE
Investigate switching to Masterminds HTML5-PHP parser as opposed to built-in PHP DOM extension

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3293]
The AMP plugin uses PHP's built-in [DOM](https://www.php.net/manual/en/book.dom.php) extension which are powered by libxml. There are various idiosyncrasies with libxml which force us to do various workarounds in [`AMP_DOM_Utils`](https://github.com/ampproject/amp-wp/blob/06ff84fec4357359ce556c889aacecfb06db66cb/includes/utils/class-amp-dom-utils.php), namely:

1. Convert AMP-bind bracketed attribute syntax to `data-amp-bind-*` syntax using regular expression replacements, since PHP DOM doesn't understand the brackets. (The replacements should still be done, but preferably not via regex!)
2. Force all self-closing tags to have closing tags since DOMDocument isn't fully aware of them.
3. Replace noscript elements with placeholders since libxml<2.8 can parse them incorrectly.
4. Add a pre-HTML5-style declaration of the encoding since libxml doesn't always recognize HTML5's meta charset.

We may be able to remove these workarounds and improve our parsing routines by switching to the Masterminds [HTML5-PHP](https://github.com/Masterminds/html5-php) parser. This was actually chosen for the Drupal AMP module's underlying [AMP PHP Library](https://github.com/Lullabot/amp-library) (which is no longer maintained, cf. https://github.com/ampproject/amp-wp/issues/2315). This HTML5 parser did not exist at the time the AMP plugin was first created, do it made sense to use PHP's DOM extension. But now a better choice may be the Masterminds library. This would also reduce a dependency.

Something that makes me wary, however, is whether the Masterminds library would be slower than the PHP extension. This is something to be investigated.

**Comment by swissspidy** [comment]
> Something that makes me wary, however, is whether the Masterminds library would be slower than the PHP extension. This is something to be investigated.

A bit surprised that this seemingly popular library doesn't address this by having a small comparison table somewhere or at least a paragraph about it.
