### ISSUE TITLE
Decouple build process from packaging process

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3302]
When you run `npm run build`, it goes through all `build:*` tasks and processes them. This does not only trigger a fresh build (converting source files to build artifacts), but also triggers the packaging process (remove development dependencies and generate a ZIP archive).

As a follow-up to #3183, I'd like to decouple "building" from "packaging", so that `npm run build` only does the required steps to make the current source folder run as a valid plugin, and provide a separate `npm run package` (name up for debate) to optimize for a production environment and to generate a ZIP.

This seems to make sense, as an `npm run build` is something you need a lot during development, whereas you seldom need a ZIP file.

Related #3183, #1840

**Comment by thelovekesh** [comment]
QA Passed ✅ 

**Before:**
On executing `npm run build:(dev|prod)` following `build:*` scripts were get executed and results in:
- Plugin zip as `amp.zip` 
- Plugin build as `./build` dir
- JS build files

https://github.com/ampproject/amp-wp/blob/4e54b03dce6f360845bfde5dbd19f85cccab7287/package.json#L106-L109

**After:**
Now on executing the `npm run build:(dev|prod)` following `build:*` scripts get executed and generate JS build files.
https://github.com/ampproject/amp-wp/blob/68d9bb3f977967fa05fb09f5f52da561dc85bd72/package.json#L107-L108

To generate a zip or plugin build following npm scripts are being used now.
https://github.com/ampproject/amp-wp/blob/68d9bb3f977967fa05fb09f5f52da561dc85bd72/package.json#L130-L133
