### ISSUE TITLE
Text Too Small Warning

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3304]
## Feature Description

As a user I want to be warned when my text is too small so that my stories look good and are engaging

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AC1: When text is smaller than (?), a warning should be displayed to the user

Notes: This is dependent on the outcome of #3298
 
## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

* 

.

**Comment by samitron7** [comment]
A user can set font type to Automatic, Paragraph, Heading 1, Heading 2 (what are the sizes for these now?). Is there a reason we're allowing a user to scale to a size that would throw this error message? It's more ideal to set limits and avoid throwing an error which would require a user to go back and fix things.

Also, Stories can be viewed on both mobile and web. Font guidelines are different for web and mobile, I like to address both but not sure how we are handling this now. ie Do we adjust font size when I view a story from a shared link on web vs on a mobile device?

**Comment by ThierryA** [comment]
Blocked by #3298
