### ISSUE TITLE
Line Height and Spacing Warning 

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3306]
## Feature Description

As a user I want to be warned when I have poor line height and spacing so that my stories look good and are engaging.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AC1: When line height and spacing is determined to be (bad?), a warning should be displayed to the user

Notes: This is dependent on the outcome of #3298
 
## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
This is dependent on the available functionality. There is currently nothing for line height, kerning or block spacing.

**Comment by ThierryA** [comment]
Blocked by #3298
