### ISSUE TITLE
Inserting background video from toolbar doesn't have validation

### ISSUE THREAD

**Issue by thrijith** [ampproject/amp-wp#3308]
Inserting video from toolbar allows selection of unsupported video types.

![background-media-selection](https://user-images.githubusercontent.com/13589980/65258101-f0af4c00-db1f-11e9-91c0-32a21c5cc682.png)

Please refer this.

![instert_background_video_toolbar](https://user-images.githubusercontent.com/13589980/65258475-8fd44380-db20-11e9-94d0-2f0dddec5900.gif)

**Comment by spacedmonkey** [comment]
Good spot @thrijith  and thanks for the bug report. I have already got a fix this merged, in https://github.com/ampproject/amp-wp/pull/3314 . It should be in the final 1.3 release, but at least will be in 1.3.1.

**Comment by swissspidy** [comment]
@spacedmonkey Heya, could you add some testing instructions here and assign to Claudio? Thanks in advance!

**Comment by spacedmonkey** [comment]
Testing. 

1. In the media library, upload an mp4 and ogv files. 
2. Create a new story. 
3. Click insert media from top toolbar
4. Click insert background video. 
5. Only the uploaded mp4 file should be visible. 
6. Select mp4 file to make background.

**Comment by csossi** [comment]
Verified in QA

upload to media library:
![image](https://user-images.githubusercontent.com/16945664/66657293-9466b600-ec0d-11e9-853d-38ccc48e40d8.png)

Selection on adding bg video:
![image](https://user-images.githubusercontent.com/16945664/66657400-c2e49100-ec0d-11e9-9a9b-bf254f86ed3c.png)

**Comment by spacedmonkey** [comment]
@csossi Can you provide more details on what happens when you select ogv file. I think the validation will still allow you upload whatever you want, I believe the issue comes when selecting the video.

**Comment by swissspidy** [comment]
The screenshots look correct to me. OGV files are not visible in the list when selecting videos, so they cannot be selected in the first place.

**Comment by spacedmonkey** [comment]
I believe what we are seeing here is the expected behavior. I am awaiting feedback, but unless I hear back, I will move this back to demo.

**Comment by spacedmonkey** [comment]
Demo https://youtu.be/tDwPu7j9C18
