### ISSUE TITLE
Migrate Jetpack shortcode handling out of AMP plugin and into Jetpack

### ISSUE THREAD

**Issue by chvillanuevap** [ampproject/amp-wp#3309]
The AMP plugin includes shortcodes for several various embed handlers, including:

* `tweet`
* `vimeo`
* `soundcloud`
* `youtube`
* `dailymotion`
* `instagram`
 
For example, the AMP plugin includes a `vimeo` shortcode as part of its `AMP_Vimeo_Embed_Handler` for historical reasons, but over time more and more Jetpack code has been moved from the AMP plugin to… Jetpack. See #1021. This code needs to be extracted from the AMP plugin to move over to Jetpack. All such shortcode handling needs to be moved to Jetpack since the shortcodes are only being registered for AMP responses, leaving non-AMP pages without any shortcode defined.

----
Hi there!

I am trying to convert my website's theme to be fully AMP compatible. 

In the blog posts from my website, we use the Jetpack Vimeo shortcode. As the [documentation](https://en.support.wordpress.com/videos/vimeo/) states, we can use the shortcode by providing the URL or the video ID. We have used the shortcode exclusively using the [vimeo 123456] format, and it has worked as intended so far.

While testing the AMP version of my site, I noticed that the Vimeo videos were not showing. Further debugging took me to the AMP plugin, to the file `includes/embeds/class-amp-vimeo-embed.php`, to the function `shortcode` in line 71.

```php
public function shortcode( $attr ) {
	$video_id = false;

	if ( isset( $attr['id'] ) ) {
		$video_id = $attr['id'];
	} elseif ( isset( $attr['url'] ) ) {
		$video_id = $this->get_video_id_from_url( $attr['url'] );
	} elseif ( isset( $attr[0] ) ) {
		$video_id = $this->get_video_id_from_url( $attr[0] );
	} elseif ( function_exists( 'shortcode_new_to_old_params' ) ) {
		$video_id = shortcode_new_to_old_params( $attr );
	}

	if ( empty( $video_id ) ) {
		return '';
	}

	return $this->render(
		[
			'video_id' => $video_id,
		]
	);
}
```
The issue here is that the way the Jetpack documentation says it's possible to use the shortcode there is no need to use an `id` or `url` attribute, so the first two if statements do not apply to my case. Now, the third statement applies because I have submitted the Vimeo ID to the shortcode, and therefore `$attr[0]` is set. However, the statement assumes that I have passed a URL, as it calls `get_video_id_from_url`, where as I have passed an ID. 

I think this shortcode function needs to parse the `$attr` variable first, similar to how Jetpack does it:

```php
$attr = array_map(
	'intval',
	shortcode_atts(
		array(
			'id'       => 0,
			'width'    => 0,
			'height'   => 0,
			'autoplay' => 0,
			'loop'     => 0,
		),
		$atts
	)
);

if ( isset( $atts[0] ) ) {
	$attr['id'] = jetpack_shortcode_get_vimeo_id( $atts );
}

if ( ! $attr['id'] ) {
	return '<!-- vimeo error: not a vimeo video -->';
}
```

My other option is to do a search and replace on all my posts, but I think making the function be compatible with Jetpack's documentation would be easier.

Thanks!

**Comment by westonruter** [comment]
It turns out that the `vimeo` shortcode is something that is provided by Jetpack. The AMP plugin includes a `vimeo` shortcode as part of its `AMP_Vimeo_Embed_Handler` for historical reasons, but over time more and more Jetpack code has been moved from the AMP plugin to… Jetpack. See #1021. So this looks like another case where this code needs to be extracted from the AMP plugin to move over to Jetpack. This is similarly captured in:

https://github.com/ampproject/amp-wp/blob/eca9ec2f4ba65cfd0f661428fc98befa697cabf1/includes/embeds/class-amp-soundcloud-embed.php#L26-L29

All such shortcode handling needs to be moved to Jetpack since the shortcodes are only being registered for AMP responses, leaving non-AMP pages without any shortcode defined.

So rather than fixing `\AMP_Vimeo_Embed_Handler::shortcode()` I believe this issue should be fixed by patching Jetpack to add AMP compatibility, and then remove the code from the AMP plugin.

**Comment by westonruter** [comment]
Feel free to open a PR to fix the shortcode implementation in the short term. But perhaps better for you to do a search-replace using a early-running filter like this:

```
add_filter( 'the_content', function( $content ) {
    return preg_replace( '/\[vimeo (?=\d+)/', '[vimeo id=', $content );
}, 0 );
```

**Comment by chvillanuevap** [comment]
Thank you for that filter! I think I'll use that for now, and wait until Jetpack has modified the shortcodes.

**Comment by kienstra** [comment]
https://github.com/Automattic/jetpack/pull/13921 is ready for review, but from Jetpack 😄

**Comment by kienstra** [comment]
The AMP handling of the `[vimeo]` shortcode is now migrated to Jetpack, though 5 shortcodes remain. Work for 3 of those is in a branch on my fork of Jetpack, as I was waiting for the first PR to be merged before submitting others.

**Comment by kienstra** [comment]
**Status Of Migration**

|Shortcode   | Status  |
|---|---|
| vimeo  |  [Jetpack PR](https://github.com/Automattic/jetpack/pull/13921) merged  |
|  youtube | [Jetpack PR](https://github.com/Automattic/jetpack/pull/14010) close to being merged  |  soundcloud |  [Jetpack PR](https://github.com/Automattic/jetpack/pull/14028) just opened | 
| tweet  |  Work begun, but no PR yet  | 
| tweet  |  Work begun, but no PR yet  | 
| dailymotion  |  No work begun |
| instagram  |  No work begun |

**Comment by kienstra** [comment]
The [Jetpack PRs](https://github.com/ampproject/amp-wp/issues/3309#issuecomment-553989965) above should be released in [8.0.0](https://github.com/Automattic/jetpack/milestone/138). So this PR probably shouldn't be released until that is. 

Most of this PR is simply deleting `add_shortcode()` calls, as there's usually no new function to check `if ( function_exists() )` . So if a user doesn't have the new Jetpack, the shortcode won't work in AMP.

**Comment by kienstra** [comment]
**Steps To Test**

1. Create a new post
2. Add a Shortcode block
3. Add a shortcode with a YouTube URL, like `[video src="https://www.youtube.com/watch?v=gS6_xOABTWo"]`
4. Preview the AMP URL
5. Expected: the video should display on the front-end
6. Repeat steps 2-5, but for a Vimeo shortcode, like `[video src="https://vimeo.com/64086087"]`

**Comment by kienstra** [comment]
Hi @csossi,
Sorry for the delay in adding the steps to test here.

**Comment by csossicql** [comment]
Verified in QA

**Comment by csossi** [comment]
verified in QA
