### ISSUE TITLE
Optimize AMP_Style_Sanitizer::has_used_class_name()

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3310]
I did a quick profile run to test the impact of the AMP plugin on frontend rendering. I tested against an empty 
front page (with 1 block with custom HTML that contained an invalid style).

Here's the comparison: https://blackfire.io/profiles/compare/f1c2bcf1-e0c0-4d14-a9b2-85e719895e3f/graph

|Walltime   |128 ms ⇾ 325 ms  |
|-----------|-----------------|
|I/O Wait   |1.43 ms ⇾ 3.95 ms|
|CPU        |127 ms ⇾ 321 ms  |
|Peak Memory|3.37 MB ⇾ 9.25 MB|
|SQL Queries|19 req ⇾ 45 req  |
|SQL Time   |1.55 ms ⇾ 4.44 ms|

Based on this, I suggest starting with optimizing the [`AMP_Style_Sanitizer::has_used_class_name()`](https://github.com/ampproject/amp-wp/blob/eca9ec2f4ba65cfd0f661428fc98befa697cabf1/includes/sanitizers/class-amp-style-sanitizer.php#L490-L621) as the current worst offender, which should yield tangible improvements.

**Comment by schlessera** [comment]
This is hard for QA to test without an actual profiler.

Basically:
1. Verify that operations on the frontend are quicker to display results.
2. Verify that the CSS is not broken.

I'm afraid I can't give anything more precise here.

**Comment by westonruter** [comment]
Smoke testing for no styling regressions seems like the best task this.
