### ISSUE TITLE
Allow drag element to different story page

### ISSUE THREAD

**Issue by barklund** [ampproject/amp-wp#3311]
_Result of #3180._

As a story editor, I want to be able to drag an element from one story page to another.

This should work for all elements.

This should allow me to drag either to a direct neighbor or (if my viewport shows it) to an even further neighbor in either direction.

Auto-scrolling is outside the scope of this ticket. If you want to drag to a page much further "down the line" (e.g. from page 1 to page 10), you have to drop on intermediate pages that you can "reach" and then continue drag from there.

**Comment by barklund** [comment]
### Testing instructions

#### Test drag of regular block
1. Create new empty story.
2. Add a new page 2.
3. Add a text block 2 page 2.
4. Drag new text block on page 2 to page 1, and see that it drops there and the editor switches to have page 1 in focus.

#### Test drag of CTA block
1. Create new empty story.
2. Add a new page 2.
3. Add a new page 3.
4. Add a CTA block to page 3.
5. Add a new page 4.
6. Switch to page 2.
7. Add a CTA block to page 2.
8. Attempt to drag CTA block from page 2 to page 1, and see that **it's not allowed** *(because it's the first page in the story)*.
9. Attempt to drag CTA block from page 2 to page 3, and see that **it's not allowed** *(because it already has a CTA block)*.
10 Attempt to drag CTA block from page 2 to page 4, and see that **it is allowed**.

Note: to see all the way from page 2 to page 4, you might need to reduce content size several times and/or use a very wide browser.

**Comment by csossi** [comment]
Verified in QA

**Comment by barklund** [comment]
Demo created here: https://youtu.be/xUzGdwFeP-w
