### ISSUE TITLE
Font Management CTA in Editor

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3316]
## Feature description

As a user in the editor page, I am easily able to access the font management page 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

*AC1: There should be a way to access the font management from the editor page (https://github.com/ampproject/amp-wp/issues/3315). This should include a CTA somewhere within the editor that brings the user to the font management experience. 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by spacedmonkey** [comment]
Related: https://github.com/ampproject/amp-wp/issues/3224
