### ISSUE TITLE
How to create an additional php file for attachment (Media) pages ??

### ISSUE THREAD

**Issue by Stafik120** [ampproject/amp-wp#3324]
Now working only Single.php

Full path - amp/templates/single.php

Now working:

site.com/post.html/amp - ( working from amp/templates/single.php)

site.com/post.html/post-media?amp - ( working from amp/templates/single.php) too), 
need additional attachment php file, for example - amp/templates/attachment.php - How to create it? 

HELP pls

**Comment by westonruter** [comment]
I assume you are using Reader mode. You must not edit the files in the `amp/templates` directory, as the changes will be lost when the plugin updates. You must instead create an `amp` directory in your custom theme and then put the customized `single.php` there instead.

Also, the attachment template is not supported in Reader mode, as can be seen here:

https://github.com/ampproject/amp-wp/blob/b44ac6ac687008e4d1c5dd2ef78b2a5d3d9ecd23/includes/templates/class-amp-post-template.php#L198

Adding support for attachment templates in Reader mode would be something to request as part of #2044.

Attachment templates are supported in Transitional and Standard modes, but your theme may not be compatible.
