### ISSUE TITLE
Unskip resizing test after bugfix

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3326]
Since #3199 got resolved with #3259, we need to unskip the relevant e2e test for it:

https://github.com/ampproject/amp-wp/blob/b44ac6ac687008e4d1c5dd2ef78b2a5d3d9ecd23/tests/e2e/specs/stories-editor/resizing.js#L275-L299

In my quick test it actually didn't quite work out of the box, so perhaps the issue is not yet fully resolved.

**Comment by spacedmonkey** [comment]
After unskipping this test, I am still getting this error in the e2e tests. 
```
  ● Resizing › Non-Fitted Text block › should not resize smaller than the set minimum width and height

    expect(received).toStrictEqual(expected) // deep equality

    Expected: 40
    Received: 250

      288 | 			await dragAndResize( resizableHandleLeft, { x: 300, y: 0 } );
      289 | 			dimensions = await getSelectedBlockDimensions();
    > 290 | 			expect( dimensions.width ).toStrictEqual( textBlockMinWidth );
          | 			                           ^
      291 | 
      292 | 			const resizableHandleRight = await page.$( '.wp-block.is-selected .components-resizable-box__handle-right' );
      293 | 			await dragAndResize( resizableHandleRight, { x: -300, y: 0 } );

      at Object.toStrictEqual (specs/stories-editor/resizing.js:290:31)

```

@barklund Should this tests now work?

**Comment by swissspidy** [comment]
The test was probably flawed before, so it needs some investigation into what is actually expected. The text block in that test doesn't have any content in it either, just the placeholder, which might make a different as well. Would be good to test both cases.

**Comment by spacedmonkey** [comment]
I believe this video displays what the issue is 

https://www.youtube.com/watch?v=9nWmkmaUv5Q&feature=youtu.be

In short, the block isn't resized but instead the block is being dragging around. I am unable to workout why this happening.

**Comment by spacedmonkey** [comment]
I believe the issue is somewhere in the test suite itself. It took me a long time to track this down. Not sure it is the best use of time right now to focus on this.

**Comment by swissspidy** [comment]
Let's focus on other items first that aren't in the backlog. We can get to this later.

**Comment by miina** [comment]
@spacedmonkey If you're OK with me taking this issue over then I'm thinking of looking into this within #3397 since it's needed there.

**Comment by spacedmonkey** [comment]
> @spacedmonkey If you're OK with me taking this issue over then I'm thinking of looking into this within #3397 since it's needed there.

Go for it. I couldn't work it out.
