### ISSUE TITLE
Investigate broken test against WordPress trunk

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3327]
There is currently one test failure on PHP 7.3 / WordPress trunk:

```
1) Test_AMP_Validated_URL_Post_Type::test_render_post_filters
json_encode() expects parameter 2 to be int, array given

/tmp/wordpress/src/wp-includes/functions.php:3733
/tmp/wordpress/src/wp-content/plugins/amp/tests/php/validation/test-class-amp-validated-url-post-type.php:1361
```

Looks like the `wp_json_encode` call there is actually wrong as it passes an arbitrary `int` as the `$options` argument.

https://github.com/ampproject/amp-wp/blob/b44ac6ac687008e4d1c5dd2ef78b2a5d3d9ecd23/tests/php/validation/test-class-amp-validated-url-post-type.php#L1358-L1363

**Comment by westonruter** [comment]
I just noticed this as well and ended up fixing as part of #3328. There was a missing `array_merge()` there.

**Comment by swissspidy** [comment]
Moving this out of QA as it was just a broken test that is now fixed.
