### ISSUE TITLE
Add option to move to previous/next page from context menu

### ISSUE THREAD

**Issue by barklund** [ampproject/amp-wp#3330]
## Feature description

As a user I want to be able to move elements to next or previous page via the context menu for said element from the right-click menu and from the existing context menu.

Related to #3311.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- This will move the element to the same relative position on the page, just on the desired page.
- This will be the only way to move Page Attachments to a different page, as they aren't draggable by themselves.
- Moving to previous page should only be possible for elements on page 2 and further along in the story (except for CTA elements - they can only be moved to previous if they're at least on page 3).
- Moving to next page should only be possible for elements on the penultimate page or earlier in the story.
- Some elements can only exist at most once on a page (Page Attachments and CTA's) - they shouldn't be allowed to be moved to pages that already have a similar item.
- Unavailable options (as per the above restrictions) should be hidden from the menu (or dimmed? but normally we hide in the UI as per current UX).

## Implementation brief

* 

### Test 1
1. Create 2 pages (They should be 3 pages in total)
1. Navigate to Page 1
1. Create text element (or reuse existing one)
1. Select text element
1. Right click on text element. 
1. Select 'Send to next page' (note the send to previous page should not be present). 
1. After element has moved, if not selected, select text element. 
1. Right click on text element. 
1. Select 'Send to previous page' (note the send to previous page and next page should be present). 

### Test 2
1. Create 3 pages (They should be 4 pages in total)
1. Navigate to Page 2
1. Create CTA element
1. Select CTA element
1. Right click on text element. 
1. Select 'Send to next page' (note the send to previous page should not be present). 
1. After element has moved, if not selected, select CTA element. 
1. Right click on CTA element. 
1. Select 'Send to previous page' (note the send to previous page and next page should be present).

## Demo

* https://youtu.be/JTEvudZHBsM

## Changelog entry

* Added support for moving elements across pages via keyboard

**Comment by spacedmonkey** [comment]
As discussed in https://github.com/ampproject/amp-wp/pull/3312 

It is extremely hard to make drag and drop functionality accessible. To surface the functionality to as many users as possible, another option should be added to the context (right click) menu. This will allow many more users to use this functionality. 

I recommend the following. 
New option is added to right click menu. This new option will be named 'Send block to page' and will have a right arrow icon. When this option is hover over, a list of available page to send block will be displayed. This list will consider the following 
- If there is only one page, do not display menu item. 
- Page that already have attachment / CTA blocks, will not be displayed in list if moving on of these blocks. 
- Current page will not be displayed in list. 

This recommendation is slightly different from the tile of this issue. Sending backward and forwards is a little limiting.

**Comment by spacedmonkey** [comment]
Doing a little research into this ticket. 

While doing some research into the solution I mentioned above. I looked into the [popover](https://github.com/WordPress/gutenberg/tree/5920ab8620e0a5ea6ed810e399dc42fd94d99abd/packages/components/src/popover), doesn't supported nested popovers. So we have two options. 

1. Just go back to two buttons, one to send back and one to send forward. 
![Screenshot from 2019-09-30 18-10-18](https://user-images.githubusercontent.com/237508/65901198-9c258f80-e3af-11e9-8bc1-ac8813df0718.png)

2. Instead of having the option in the right click menu, the option could be in the right hard sidebar next to the block position. 
![Screenshot from 2019-09-30 18-11-38](https://user-images.githubusercontent.com/237508/65901235-ae9fc900-e3af-11e9-87ee-c9604aecb810.png)

Would like some UX feedback on this one.

**Comment by cathibosco** [comment]
Are you suggesting that in the right sidebar we consider adding a section like **Block Position** 
called for example **Page Position** so you could move an element to the next page or the previous page? 
For accessibility this is a proposed solution that would replace the need for this in right click menu... do I understand correctly? @spacedmonkey

**Comment by spacedmonkey** [comment]
> Are you suggesting that in the right sidebar we consider adding a section like **Block Position**
> called for example **Page Position** so you could move an element to the next page or the previous page?
> For accessibility this is a proposed solution that would replace the need for this in right click menu... do I understand correctly? @spacedmonkey

Yeah, that is correct, either the options goes in the right click menu or the sidebar. My feeling is the sidebar is a much more accessible place to put it. My only worry is that functionality will be lost, as people like not see it. An argument could be made about the block position as well.

**Comment by spacedmonkey** [comment]
As a talking point, I have mocked up the two options. 

**Option 1**
![Screenshot from 2019-10-01 10-53-35](https://user-images.githubusercontent.com/237508/65953246-75149f80-e43b-11e9-901d-c6be03eae4c9.png)

**Option 2**

![Screenshot from 2019-10-01 11-00-16](https://user-images.githubusercontent.com/237508/65953238-7219af00-e43b-11e9-913a-a69dfc12cdee.png)

**Comment by cathibosco** [comment]
Very helpful - in terms of accessibility, I am honestly uncertain which would be the most user friendly. I can ask some colleagues.

**Comment by cathibosco** [comment]
My colleague shared this: **tab through, select with spacebar**
https://dev.opera.com/articles/accessible-drag-and-drop/example.html

I comes from W3.org

**Comment by spacedmonkey** [comment]
There is already a PR (https://github.com/ampproject/amp-wp/pull/3408) in place to make the context menu available for the keyboard. 

I do like the dropdown functionality in option 2, I do worry that it is a little disconnected to the other block implementations like duplicate and remove block. Lets go ahead with option 1.

**Comment by swissspidy** [comment]
Needs testing instructions added above for QA

**Comment by spacedmonkey** [comment]
Testing instructions 
------------------------
### Test 1
1. Create 2 pages (They should be 3 pages in total)
1. Navigate to Page 1
1. Create text element (or reuse existing one)
1. Select text element
1. Right click on text element. 
1. Select 'Send to next page' (note the send to previous page should not be present). 
1. After element has moved, if not selected, select text element. 
1. Right click on text element. 
1. Select 'Send to previous page' (note the send to previous page and next page should be present). 


### Test 2
1. Create 3 pages (They should be 4 pages in total)
1. Navigate to Page 2
1. Create CTA element
1. Select CTA element
1. Right click on text element. 
1. Select 'Send to next page' (note the send to previous page should not be present). 
1. After element has moved, if not selected, select CTA element. 
1. Right click on CTA element. 
1. Select 'Send to previous page' (note the send to previous page and next page should be present).

**Comment by csossi** [comment]
Verified in QA

Included verification that CTA block can't be moved to a page that already has a CTA (option doesn't appear in context menu):
![image](https://user-images.githubusercontent.com/16945664/66773482-144e8380-ee8d-11e9-97e6-eeb1e16779bd.png)
