### ISSUE TITLE
Remove validation handling options with the checkbox to disable auto-accepting sanitization

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3350]
For the vast majority of users the option to auto-accept validation errors should be enabled:

![image](https://user-images.githubusercontent.com/134745/66362535-29895680-e951-11e9-8c32-55948403910c.png)

This option is in fact enabled by default. Based on usage over the past year it seems this option is rarely unchecked, and in fact it is not even able to be unchecked when in Standard mode:

![image](https://user-images.githubusercontent.com/134745/66362588-5ccbe580-e951-11e9-92a0-fb1d6f903503.png)

Therefore the checkbox option should be removed entirely.

As part of this, the notices that appear in the validated URLs screen should be removed:

![image](https://user-images.githubusercontent.com/134745/66362604-71a87900-e951-11e9-80f5-ff58b512e876.png)

![image](https://user-images.githubusercontent.com/134745/66362617-7f5dfe80-e951-11e9-9673-bcda92a8b7e2.png)

Note that in #3346 (fixing #2326) the `excessive_css` validation error actually defaults to _auto-rejected_ when the site is in Standard mode. To extend this now to give control over a site's developers to have control over the default behavior, the `AMP_Validation_Manager::is_sanitization_auto_accepted()` method should be made filterable. This will then allow for the removal of the checkbox and removal of the `'auto_accept_sanitization'` option.

Context: For almost all users, accepting sanitization by default just makes sense, so going by the "decisions, not options" mantra of WordPress and removing the option seems sensible. See https://github.com/ampproject/amp-wp/pull/3346#issuecomment-535117041

This is related to #2346 which removed the checkbox for showing the admin bar in AMP pages. It reverts the admin notices added in #1376.

**Comment by westonruter** [comment]
I've updated the title and description to combine the removal of the auto-accept checkbox with the addition of the filter for whether a validation error's sanitization is auto-accepted.
