### ISSUE TITLE
Feature Request: Toggle on/off classes for nav_menu_toggle theme support

### ISSUE THREAD

**Issue by craig-stanfield** [ampproject/amp-wp#3363]
Hi,

I'd like to see a method to add a toggled on and toggled off class for the nav_container_toggle_class and menu_button_toggle_class (or perhaps easier to add nav_container_toggle_on_class / nav_container_toggle_off_class and menu_button_toggle_on_class / menu_button_toggle_off_class)

I've come across a few sites that switch a class like toggle-on / toggle-off to implement the nav menu which currently means usage of amp_endpoint to implement.

thanks

Craig

**Comment by westonruter** [comment]
Have you considered implementing support for toggling without using the theme support flag? 

The theme support flag is essentially just implementing the guidance outlined in this playbook: https://amp-wp.org/documentation/playbooks/toggling-hamburger-menus/

**Comment by craig-stanfield** [comment]
In the end we are using the test for amp from the same Doc, however in our example we toggle between on and off classes so having ability to add 2 classes as say an array would be very helpful for the few sites we maintain that use this method. Of course we could refactor the method used.

**Comment by amedina** [comment]
Closing for now. Will reopen if revisiting is needed.
