### ISSUE TITLE
Images and data-pin-media

### ISSUE THREAD

**Issue by chvillanuevap** [ampproject/amp-wp#3369]
Hi there!

I currently display a hidden image at the bottom of my website for users to pin by using this code:

```html
<div class="hidden-pin-image">
    <img src="image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-pin-media="https://thepostmansknock.com/wp-content/uploads/2019/09/1Remy_Hawaii.jpg">
</div>
```
The `src` attribute is a 1x1 blank image, and the `data-pin-media` attribute is the one that holds the actual pinnable image.

I have the Pinterest extension installed on Google Chrome. When I click on the Pinterest logo next to the URL bar in Chrome, Pinterest pulls the 1Remy_Hawaii.jpg image correctly. However, when AMP is activated, the `img` tag gets converted to an `amp-img`, which causes the Pinterest extension to no longer be able to pull the image correctly. I noticed this behavior when I went to check our Pinterest stats, and noticed that our number of pins had decreased.

However, I see that inside `amp-img`, there is a `<i-amphtml-sizer class="i-amphtml-sizer">` piece that contains an `img` tag. But this `img` tag did not carry over the data-pin-media attribute. If I open the developer console, copy and paste the `data-pin-media` information into the HTML, and try to use the Pinterest extension again, then Pinterest does pull the correct image.

Is there a way to let the AMP plugin know that this attribute needs to be carried over to the `img` tag inside `i-amphtml-sizer`?

**Comment by westonruter** [comment]
That's an interesting use case. So there needs to be a way for `amp-img` to copy certain attributes to the `img`. This is essentially already being done for `alt` and `src` but not for other attributes, specifically the `data-*` attributes. This isn't something that the AMP plugin can implement so you should actually post it to the amphtml repo. Please [open a feature request](https://github.com/ampproject/amphtml/issues/new?assignees=&labels=Type%3A+Feature+Request&template=feature_request.md&title=Copy+data-*+attributes+from+amp-img+onto+img).
