### ISSUE TITLE
amp-ad using Doubleclick network

### ISSUE THREAD

**Issue by firmanpolyrific** [ampproject/amp-wp#3371]
I'm wondering if this plugin supports ads via Doubleclick?

on the documentation, it says:

> Automatically enqueue the AMP component scripts required in a given page. For example, if an <amp-ad> tag is included in the markup of a given template, the plugin will automatically add the required  wp_enqueue_script( ‘amp-ad’ ) without user intervention

But when I got Double ad implementation docs, which is here:
https://github.com/ampproject/amphtml/blob/master/ads/google/doubleclick.md

it says deprecated and must use this one instead:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md

which is need to implements Fast Fetch network (don't have any idea about this yet)

I don't know I get lost here, how to implement Doubleclick ads in the right way using this plugin?
anyone can help me?

**Comment by westonruter** [comment]
If you put markup like this into your content:

```html
<amp-ad width=320 height=50
    data-override-width=111
    data-override-height=222
    type="doubleclick"
    data-slot="/4119129/mobile_ad_banner">
</amp-ad>
```

Then yes, it should result in the `amp-ad` script automatically being added to the page.

As for how to configure Doubleclick ads, this is out of scope for this plugin. I suggest inquiring of general AMP support: https://amp.dev/support/
