### ISSUE TITLE
Resizing smaller not possible than initial size for a rotated block (without amp-fit-text)

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3396]
Steps to reproduce:
- Create a text block and turn amp-fit-text off.
- Rotate the block a little bit.
- Add some text inside it so that it would be on two lines at least.
- Resize the text from the bottom so that there would be enough room to resize it smaller from the side.
- Try resizing smaller from the side (e.g. right side).

![resizing](https://user-images.githubusercontent.com/3294597/65957184-8023fb80-e44c-11e9-942a-abc4aa72758e.gif)

Expected: As long as there is room for the text, it should be possible to resize it smaller from any side.

**Comment by spacedmonkey** [comment]
Might be related to https://github.com/ampproject/amp-wp/issues/3291

**Comment by swissspidy** [comment]
Interesting that this only applies to rotated blocks and when resizing from the side 🤔

**Comment by miina** [comment]
Yep. Will debug this in more detail to see what's happening.

**Comment by miina** [comment]
Instructions for testing:
- Create a text block and turn amp-fit-text off.
- Rotate the block a little bit.
- Add some text inside it so that it would be on two lines at least.
- Resize the text from the bottom so that there would be enough room to resize it smaller from the side.
- Try resizing smaller from the side (e.g. right side).
- Verify that it's possible to reduce the width.

(See the gif in [issue description](https://github.com/ampproject/amp-wp/issues/3396#issue-500825126) for seeing how it should not be)

**Comment by csossi** [comment]
Verified in QA

Before:
![image](https://user-images.githubusercontent.com/16945664/66658430-7306c980-ec0f-11e9-8715-d006405842fb.png)

After:
![image](https://user-images.githubusercontent.com/16945664/66658470-8ca81100-ec0f-11e9-9be2-7e6060f7b41a.png)

**Comment by miina** [comment]
Demo of working as expected: https://www.dropbox.com/s/fuw2b3x1vytnbkk/demo-resizing.mp4?dl=0
