### ISSUE TITLE
Resizing Text block: Trying to resize smaller than possible moves the position

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3397]
Steps to reproduce:
- Create a Text block.
- Turn off amp-fit-text.
- Resize it from the left handle to as narrow as possible.
- See the results.
![resizing-2](https://user-images.githubusercontent.com/3294597/65973325-6cd45880-e46b-11e9-9bef-b169fd7ac0eb.gif)

Expected: The block should stay in place when resizing and reaching limits.

Note: Same issue for non-rotated Text block, too.

Todo:
- [x] Fix the issue
- [x] Add tests for resizing for when amp fit text is turned off.

**Comment by miina** [comment]
Note that this happens in case of other resizing handles, too. Not all but most.

**Comment by swissspidy** [comment]
I think that's the same as #3290.

**Comment by miina** [comment]
Ah, looks like it! Thanks for noting that.

**Comment by swissspidy** [comment]
@miina Could you add testing instructions here for Claudio? Thanks in advance!

**Comment by csossi** [comment]
Verified in QA
