### ISSUE TITLE
Text size not adjusting correctly when resizing a rotated block

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3398]
Steps to reproduce:
- Add a Text block
- Write some text in it.
- Rotate the block.
- Resize it larger step by step, e.g. from the right top corner.

![resizing-3](https://user-images.githubusercontent.com/3294597/65974507-57602e00-e46d-11e9-8ef2-c4926eb3fc0d.gif)

Expected:
- The font size should always adjust according to the room it has.

**Comment by miina** [comment]
Note: Seems to happen for a rotated block only when testing.

**Comment by jauyong** [comment]
Hey @miina after I resize my rotated text block, it looks like the text is adjusting appropriately. I never got the small text in your gif after my resizes. 

![3398](https://user-images.githubusercontent.com/5874851/67884892-f8014680-fb1c-11e9-8169-ec63daf37980.gif)

**Comment by miina** [comment]
Hey @jauyong, it still happens but it's not something that happens all the time, I had to resize quite a few times for this to happen. Tested on staging:
![font-size](https://user-images.githubusercontent.com/3294597/67904250-c8ae0200-fb3b-11e9-961d-05fb661dde35.gif)
