### ISSUE TITLE
Erroneous XML processing instructions (e.g. <?php ?>) are not sanitized

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3409]
As reported on the [support forums](https://wordpress.org/support/topic/amp-1-3-0-validation-errors/), upon upgrading to AMP 1.3 they they started getting the AMP validator complaining about validation errors for this markup:

```html
<?php
$schema = get_post_meta(get_the_ID(), 'schema', true);
if(!empty($schema)) {
echo $schema;
}
?>
```

Naturally this is a bug since the PHP code is getting incorrectly included on the page. But still this `<?php ... ?>` processing instruction and others like it should be getting sanitized. It was actually getting removed in the previous version of the plugin, with an error code of `unknown`:

![image](https://user-images.githubusercontent.com/134745/66010417-a4df9980-e473-11e9-9adb-b8b2a912c992.png)

We should restore this behavior, or rather add a more specific error code like `invalid_processing_instruction`. The validator doesn't apparently allow _any_ processing instructions, including:

* 🚫 `<?xml version="1.0" encoding="UTF-8" ?>`
* 🚫 `<?xml-stylesheet type="text/xsl" href="style.xsl"?>`
* 🚫 `<?php /*...*/ ?>`

This would be a regression likely introduced by #3243.

**Comment by westonruter** [comment]
Here is a workaround plugin to restore the sanitization of processing instructions: https://gist.github.com/westonruter/96ae3cb713051aae867b874196eef910

**Comment by westonruter** [comment]
Proposed patch to fix this in the plugin:

```php
diff --git a/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php b/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
index 7d8df775..0d2f3ab2 100644
--- a/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
+++ b/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
@@ -291,6 +291,8 @@ class AMP_Tag_And_Attribute_Sanitizer extends AMP_Base_Sanitizer {
 						$result
 					);
 				}
+			} elseif ( $this_child instanceof DOMProcessingInstruction ) {
+				$this->remove_invalid_child( $this_child, [ 'code' => 'invalid_processing_instruction' ] );
 			}
 			$this_child = $next_child;
 		}
diff --git a/tests/php/test-tag-and-attribute-sanitizer.php b/tests/php/test-tag-and-attribute-sanitizer.php
index bd59920e..2724dac6 100644
--- a/tests/php/test-tag-and-attribute-sanitizer.php
+++ b/tests/php/test-tag-and-attribute-sanitizer.php
@@ -1670,6 +1670,13 @@ class AMP_Tag_And_Attribute_Sanitizer_Test extends WP_UnitTestCase {
 				[],
 				[ 'invalid_element' ],
 			],
+
+			'invalid_php_pi'                               => [
+				'<?php $schema = get_post_meta(get_the_ID(), \'schema\', true); if(!empty($schema)) { echo $schema; } ?>',
+				'',
+				[],
+				[ 'invalid_processing_instruction' ],
+			],
 		];
 	}
 ```

Perhaps we should audit other DOM node types to make sure that nothing else is added which is illegal.

**Comment by csossi** [comment]
Verified in QA
![image](https://user-images.githubusercontent.com/16945664/67729578-012ccf00-f9c8-11e9-8d3a-093c068441cc.png)
![image](https://user-images.githubusercontent.com/16945664/67729601-199ce980-f9c8-11e9-9304-3af9a2dd0dca.png)

**Comment by westonruter** [comment]
> Verified in QA

Actually, this highlights some deficiencies. Opened https://github.com/ampproject/amp-wp/pull/3660 to fix.
