### ISSUE TITLE
Scribd embeds are not fully supported

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3424]
## Bug Description

Scribd is a core-supported oEmbed provider. However, when adding a Scribd embed with an AMP validation error is sanitized due to a `script` being included in the oEmbed response:

```html
<iframe class="scribd_iframe_embed" src="https://www.scribd.com/embeds/110799637/content" scrolling="no" id="110799637" width="100%" height="500" frameborder="0"></iframe>
<script type="text/javascript">
          (function() { var scribd = document.createElement("script"); scribd.type = "text/javascript"; scribd.async = true; scribd.src = "https://www.scribd.com/javascripts/embed_code/inject.js"; var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(scribd, s); })()
 </script>
```

In spite of this, the block renders fine on the frontend, _except_ the full screen button does not work. An error appears in the console:

> Blocked opening 'https://www.scribd.com/document/110799637/Synthesis-of-Knowledge-Effects-of-Fire-and-Thinning-Treatments-on-Understory-Vegetation-in-Dry-U-S-Forests#fullscreen&from_embed' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.

## Expected Behaviour

The block renders on the frontend without any validation errors. Full screen functionality should be available.

## Steps to reproduce

1. Add a Scribd embed, for example https://www.scribd.com/document/110799637/Synthesis-of-Knowledge-Effects-of-Fire-and-Thinning-Treatments-on-Understory-Vegetation-in-Dry-U-S-Forests
2. View the frontend.
3. Notice AMP validation errors appearing in the admin bar.
4. Clicking the Full screen button has no effect.
5. The height of the iframe is not the same as the non-AMP version.

## Screenshots

<img width="1030" alt="Screen Shot 2019-10-02 at 14 20 35" src="https://user-images.githubusercontent.com/134745/66082898-00fff780-e520-11e9-97ec-661cb5eff655.png">

![image](https://user-images.githubusercontent.com/134745/66083074-6c49c980-e520-11e9-9ccf-4e6669515198.png)

## Additional context

 - WordPress version: 5.3-beta
 - Plugin version: 1.3.0
 - Gutenberg plugin version (if applicable): 6.6.0
 - AMP plugin template mode: Transitional
 - PHP version: 7.3
 - OS: Mac
 - Browser: Chrome
 - Device: Mac

---------------

## Acceptance criteria

* Embedding Scribd results in no AMP validation errors.
* An embedded Scribd can be opened in full screen from an AMP page.
* [Optional] An embedded Scribd can resize itself.

## Implementation brief

* Following the model in the `AMP_SoundCloud_Embed_Handler`, add a `embed_oembed_html` filter which looks for embeds for Scribd.
* Use filter to strip out the `script`.
* Use filter to inject `sandbox="allow-scripts allow-popups"` attribute into the `<iframe>`
* Try to also add the `resizable` attribute, to [allow the iframe to resize](https://amp.dev/documentation/components/amp-iframe/?format=websites#iframe-resizing). This may not have any effect if Scribd does not send the required messages.

## QA testing instructions

1. Set template mode to Transitional.
1. Create a new Embed block or Scribd block provide the  URL: https://www.scribd.com/document/110799637/Synthesis-of-Knowledge-Effects-of-Fire-and-Thinning-Treatments-on-Understory-Vegetation-in-Dry-U-S-Forests
1. Click save draft and preview.
1. The AMP version should not show any validation errors in the Admin Bar and the embed should be fully functional.

## Demo

* 

## Changelog entry

* Add direct support for Scribd embeds.

**Comment by kienstra** [comment]
In case these help, here are a few more Scribd embed URLs for testing:

https://www.scribd.com/doc/315548946/William-Shakespeare
https://www.scribd.com/document/96882378/Trademark-License-Agreement
https://www.scribd.com/document/352090945/The-time-to-start-is-now-How-implementing-natural-infrastructure-solutions-can-improve-and-protect-our-coasts
