### ISSUE TITLE
When Pasting an Item it does not Always Paste on the Top Layer

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#3430]
## Bug Description

When a user goes to paste an item, upon the paste action the item does not always paste on the top layer.

## Expected Behaviour

Pasted item would always be the top layer when pasted.

## Steps to reproduce

1. Copy a block
2. Paste a block

## Screenshots

<img width="697" alt="Screen Shot 2019-10-03 at 6 32 16 AM" src="https://user-images.githubusercontent.com/24547817/66119898-a1e5c580-e5a7-11e9-97ae-c5cdbecd2975.png">

<img width="623" alt="Screen Shot 2019-10-03 at 6 32 29 AM" src="https://user-images.githubusercontent.com/24547817/66119906-a7431000-e5a7-11e9-8a66-dff714b68f10.png">

<img width="650" alt="Screen Shot 2019-10-03 at 6 32 34 AM" src="https://user-images.githubusercontent.com/24547817/66119911-aad69700-e5a7-11e9-9c03-f99a8641f2fd.png">

## Additional context

 - WordPress version:
 - Plugin version: 1.3-rc
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Pasted blocks should be on the top most layer of the page, i.e. in the block navigation it would appear at the top, not the bottom.

## Implementation brief

Blocks are inserted when pasting in two places:
https://github.com/ampproject/amp-wp/blob/e8b003750940062329ae0d2bddffa1c3cc38a504/assets/src/stories-editor/components/context-menu/index.js#L113

and
https://github.com/ampproject/amp-wp/blob/e8b003750940062329ae0d2bddffa1c3cc38a504/assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js#L79

In both cases, the index where to set the block is currently set to `null`. We should replace that with an appropriate index to ensure that the block is pasted to the last position.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Recorded a quick demo as I just ran into this again: https://cloudup.com/ckuVo60lvMB

**Comment by miina** [comment]
Looking into this to add IB.

**Comment by miina** [comment]
IB ready for review.

**Comment by swissspidy** [comment]
Neat!

**Comment by csossi** [comment]
Verified in QA

With right click:
![image](https://user-images.githubusercontent.com/16945664/67423078-9e8b9b80-f5a1-11e9-8d0d-8889bd7989a3.png)

With keyboard:
![image](https://user-images.githubusercontent.com/16945664/67423252-e7dbeb00-f5a1-11e9-819d-d64f89d6afb5.png)
