### ISSUE TITLE
`tap:scrollTo()` markup broken in Transitional mode

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3435]
## Bug Description

The `tap:scrollTo()` action allows for implementing smooth scrolling to links that navigate within the current page to a given anchor element.

In Transitional mode, the `tap:scrollTo()` action markup is broken, as it still receives the `href="?amp"` markup. The smooth scrolling does work, but is then followed by a full page reload to satisfy the `href` markup.

## Expected Behaviour

Smooth-scrolling links within the current page should not receive the `href="?amp"` attribute.

## Screenshots

Below is the result of using `AMP_Core_Theme_Sanitizer::add_smooth_scrolling()` on TwentyTwenty in Transitional Mode:

![Image 2019-10-03 at 4 29 20 PM](https://user-images.githubusercontent.com/83631/66136345-9ae8a280-e5fb-11e9-967c-ed8cd6f8e004.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I think this is just a bug in the AMP-to-AMP linking plugin. I pushed up a fix for it yesterday. Can you try the latest? https://gist.github.com/westonruter/f9ee9ea717d52471bae092879e3d52b0

**Comment by westonruter** [comment]
This change specifically:

![image](https://user-images.githubusercontent.com/134745/66144297-7077f480-e5bd-11e9-8795-11d2aeec5c8c.png)

**Comment by schlessera** [comment]
It was indeed a problem with this plugin, but a different change is needed:

![Image 2019-10-04 at 8 07 24 AM](https://user-images.githubusercontent.com/83631/66185388-85b55780-e67f-11e9-92c9-74ce6a1ab335.png)

Closing the issue here.

**Comment by westonruter** [comment]
Fixed in https://gist.github.com/westonruter/f9ee9ea717d52471bae092879e3d52b0
