### ISSUE TITLE
Integrate `@ampproject/toolbox-linter` into AMP Plugin Validation workflows

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3441]
## Feature description

The AMP Toolbox project includes a JS-based linter that includes higher level rules to check against than we currently use within our sanitizer/validation setup: https://github.com/ampproject/amp-toolbox/tree/master/packages/linter

Some of the rules might make sense to check against, and they are easily extensible: https://github.com/ampproject/amp-toolbox/tree/master/packages/linter/src/rules

We should look into adding this linter to the plugin to run it from within the admin bar, to provide additional help in setting up a clean and performant AMP implementation.

This check would be completely async and optional and not block the loading time.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Oh, that would be really neat. I see a few AMP Stories related rules as well. If we could enable the admin bar for stories (with AMP dev mode) and lint stories, that would be awesome.

**Comment by westonruter** [comment]
I tried a quick patch to see if the admin bar could be added to stories, and it seems promising:

<img width="1150" alt="Screen Shot 2019-10-04 at 10 12 40" src="https://user-images.githubusercontent.com/134745/66226408-953c9c80-e68f-11e9-9cf9-188f1d8f67d2.png">

```diff
diff --git a/includes/class-amp-story-post-type.php b/includes/class-amp-story-post-type.php
index f02e241c..867b4868 100644
--- a/includes/class-amp-story-post-type.php
+++ b/includes/class-amp-story-post-type.php
@@ -224,6 +224,8 @@ class AMP_Story_Post_Type {
 				 * Same as wp_print_styles() but importantly omitting the wp_print_styles action, which themes/plugins
 				 * can use to output arbitrary styling. Styling is constrained in story template via the
 				 * \AMP_Story_Post_Type::filter_frontend_print_styles_array() method.
+				 *
+				 * @todo We need to be able to allow admin-bar scripts to also be printed.
 				 */
 				wp_styles()->do_items();
 			},
@@ -244,17 +246,6 @@ class AMP_Story_Post_Type {
 		add_action( 'amp_story_head', 'wp_site_icon', 99 );
 		add_action( 'amp_story_head', 'wp_oembed_add_discovery_links' );
 
-		// Disable admin bar from even trying to be output, since wp_head and wp_footer hooks are not on the template.
-		add_filter(
-			'show_admin_bar',
-			static function( $show ) {
-				if ( is_singular( self::POST_TYPE_SLUG ) ) {
-					$show = false;
-				}
-				return $show;
-			}
-		);
-
 		// Remove unnecessary settings.
 		add_filter( 'block_editor_settings', [ __CLASS__, 'filter_block_editor_settings' ], 10, 2 );
 
@@ -774,6 +765,11 @@ class AMP_Story_Post_Type {
 		return array_filter(
 			$handles,
 			static function( $handle ) {
+				// @todo Also need to allow any style that depends on admin-bar.
+				if ( 'admin-bar' === $handle || 'dashicons' === $handle ) {
+					return true;
+				}
+
 				if ( ! isset( wp_styles()->registered[ $handle ] ) ) {
 					return false;
 				}
diff --git a/includes/templates/single-amp_story.php b/includes/templates/single-amp_story.php
index 6b3353da..087cabb5 100644
--- a/includes/templates/single-amp_story.php
+++ b/includes/templates/single-amp_story.php
@@ -70,7 +70,9 @@ the_post();
 
 		<?php
 		// Note that \AMP_Story_Post_Type::filter_frontend_print_styles_array() will limit which styles are printed.
+		wp_admin_bar_render();
 		print_late_styles();
+
 		?>
 	</body>
 </html>
```

**Comment by westonruter** [comment]
I think that straight integrating the Linter into the plugin may not be as helpful as possible. Namely, the Linter will tell you are problems but it won't have any guidance about how the issue can be fixed. It would be better if the rules were internalized into the AMP plugin as part of the editorial workflows. This would provide the user with the information contextually.
