### ISSUE TITLE
Support for radio inputs in comment form

### ISSUE THREAD

**Issue by billerickson** [ampproject/amp-wp#3443]
## Feature description

Food blogs will commonly have a "Rate this Recipe" input field in the comment form. I followed the AMP documentation for a [star rating field](https://amp.dev/documentation/examples/interactivity-dynamic-content/star_rating/?format=websites), but when I include it in the WordPress comment form the data is not saved.

I believe the issue is [this line](https://github.com/ampproject/amp-wp/blob/4b597d8d33001601203d548cfb9c8fea0a2cbcd5/includes/sanitizers/class-amp-comments-sanitizer.php#L117-L120):

https://github.com/ampproject/amp-wp/blob/4b597d8d33001601203d548cfb9c8fea0a2cbcd5/includes/sanitizers/class-amp-comments-sanitizer.php#L117-L120

I'm using WP Recipe Maker which normally includes a JS star rating field, but is disabled on AMP pages.  I used [this code](https://gist.github.com/billerickson/110f98aedb6211697eddf780780a6c31) to add my star rating field to the comment form. 

WP Recipe Maker uses the `comment_post` hook to save the rating ([code here](https://gist.github.com/billerickson/873e6b5eb43e56229c7e5f2021bc844c#file-class-wprm-comment-rating-php-L282-L291)). I think that hook still fires when AMP comment form submissions are processed, but the issue referenced above strips out the radio field from the posted data.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
The to-do comment there is specifically to support resetting the comment form to initial state after submission, and disabling the input during submission. It's not intended to impact whether the data is saved. Something else seems to be going on here.

**Comment by billerickson** [comment]
I believe I figured out the issue, and it wasn't AMP related. 

When the rating field is disabled in WP Recipe Maker, it still loads the comment form field but adds `display: none` to it. This was overriding the value set in my custom field.

If anyone needs an AMP-compatible star rating field in WordPress, you can use my [BE Comment Rating](https://github.com/billerickson/BE-Comment-Rating) plugin. It works as a standalone star rating field, as well as an AMP replacement for the WPRM star rating component.

**Comment by westonruter** [comment]
Thanks very much for following up on this.
