### ISSUE TITLE
Add lightbox effect doesn't work for image blocks

### ISSUE THREAD

**Issue by rsmith4321** [ampproject/amp-wp#3450]
## Bug Description

If an image is inserted using the block editor image block, and under AMP Settings the Add lightbox effect is selected as on.  The image is not loaded in a lightbox when clicked. 

## Expected Behaviour

The image should be loaded in an amp lightbox when clicked. 

## Steps to reproduce

The first 3 images on this page have Add lightbox effect on with no effect. https://www.ryansmithphotography.com/myrtle-beach-wedding-photography-prices/

## Screenshots

<img width="2108" alt="Screen Shot 2019-10-04 at 11 14 46 PM" src="https://user-images.githubusercontent.com/7704223/66249116-f2bb0280-e6fc-11e9-8f9e-8347f4a39e50.png">

## Additional context

 - WordPress version: 5.2.3
 - Plugin version: 1.3.0
 - Gutenberg plugin version (if applicable): 
 - AMP plugin template mode: standard
 - PHP version: 7.3
 - OS:
 - Browser: chrome
 - Device: MacOS Desktop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@rsmith4321 Do you have any filters on images like you had for galleries in that other issue?

**Comment by rsmith4321** [comment]
As far as I know there are no filters or special settings on my site for images. Does this work on other sites?  I just assumed it was something that hasn't been looked at yet similar to the gallery lightbox issue.

**Comment by westonruter** [comment]
@kienstra Would you please investigate?

**Comment by kienstra** [comment]
Sure, @westonruter!

**Comment by kienstra** [comment]
**Thanks, I also saw this**

Hi @rsmith4321,
Thanks for bringing this up. It looks like this is a valid bug.

As a quick workaround, does removing the link in the Image blocks help?

<img width="1435" alt="image-block-link" src="https://user-images.githubusercontent.com/4063887/66275556-4473a200-e84f-11e9-8139-17e23e826f49.png">

I could reproduce this issue when the Image block has a link, but the lightbox looks good when it doesn't.

I'll look at a code fix in the plugin, but maybe that workaround will help in the meantime.

**Comment by rsmith4321** [comment]
Yes this works. Is there an seo disadvantage to no longer linking to the original image?  Also, on a desktop I want to target these type of images with cursor:pointer css since the cursor no longer changes on hover. How can I target only lightbox supported images with css?  Or perhaps this is something you can add.

**Comment by kienstra** [comment]
Hi @rsmith4321,
Thanks, that sounds good. Of course, I'll also work on a fix in the plugin for that.

>Is there an seo disadvantage to no longer linking to the original image? 

Hm, I'm not sure.

>Also, on a desktop I want to target these type of images with cursor:pointer css since the cursor no longer changes on hover. How can I target only lightbox supported images with css? Or perhaps this is something you can add.

I'll look at this also.

**Comment by kienstra** [comment]
Hi @rsmith4321,

>Also, on a desktop I want to target these type of images with cursor:pointer css since the cursor no longer changes on hover. How can I target only lightbox supported images with css? Or perhaps this is something you can add.

This worked locally, though maybe you'd want to add selectors so it doesn't apply to all `<amp-img>` in the document:

```css
amp-img[data-amp-lightbox] {
	cursor: pointer;
}
```

Images that have that `'Add lightbox effect'` toggle on will have a `data-amp-lightbox` attribute:

<img width="1133" alt="data-amp-lightbox" src="https://user-images.githubusercontent.com/4063887/66363810-1c6a6880-e94d-11e9-90fa-f69cbfa8d44c.png">

**Comment by kienstra** [comment]
Hi @rsmith4321,
Thanks for your help with testing these PRs.

Could you please test #3460, which should fix this issue? It should be possible select links, while still getting the lightbox (though the links won't appear on the front-end):

<img width="978" alt="image-add-link" src="https://user-images.githubusercontent.com/4063887/66364353-f5ad3180-e94e-11e9-838e-90cf2a34fce9.png">

**Comment by kienstra** [comment]
There's probably no need to test this now until there's a response on https://github.com/ampproject/amphtml/issues/25021

**Comment by westonruter** [comment]
It looks like the direction is to stop using `amp-img-lightbox` in favor of using `amp-lightbox-gallery`. See https://github.com/ampproject/amphtml/issues/25021#issuecomment-541846264

**Comment by kienstra** [comment]
Sounds good, thanks for 'bumping' that issue. I'll look at using the `amp-lightbox-gallery` for this.

**Comment by rsmith4321** [comment]
Sorry I haven't had time to test but it sounds like you are going a different way anyway. The amp-lightbox-gallery lightbox seems a lot more full featured for example the amp-img-lightbox doesn't even have a close icon to indicate how to exit the lightbox.  Thanks!

**Comment by kienstra** [comment]
Sure, no problem in testing, this was dependent on the `ampthml` issue anyway. I'm going to work on converting this to an `amp-lightbox-gallery`.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
When you can, could you please test this, using the [steps to reproduce here](https://github.com/ampproject/amp-wp/pull/3460#issue-325574237)?

Thanks, Claudio!

**Comment by csossi** [comment]
Verified in QA
