### ISSUE TITLE
Dragging only possible after selecting page first

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3455]
## Bug Description

When dragging one block then after that it's not possible to drag the other block. It displays the clone but dropping doesn't have any result. For being able to drag again, I first have to click the Page, and then drag the block.

## Expected Behaviour

After dragging one block, dragging another block should still be possible.

## Steps to reproduce

1. Add a block.
2. Add another block
3. Drag the first block.
4. Now try dragging the second block.
5. See the block not being dragged. It's possible to drag again after clicking on Page first.

## Screenshots

![dragging](https://user-images.githubusercontent.com/3294597/66333358-1e293180-e937-11e9-9753-2052ff8ceac4.gif)

## Additional context

 N/A

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A user should be able to select a block within a page, independent of the page being manually selected, and move/drag the block.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
I can confirm that this happens. Just created a new story and added 2 blocks, so there are now three in total:

1. The pre-existing text block
2. First new block
3. Second new block

I can drag around the first new block, but not the others.

There are no JS errors in the console.

**Comment by spacedmonkey** [comment]
Moved to QA already passed close review. @miina As you have owned this, can you put testing instructions in?

**Comment by csossi** [comment]
Verified in QA
