### ISSUE TITLE
Text block jumps when changing normal to huge font

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3461]
## Bug Description

Text block jumps when changing normal to huge font size.

## Expected Behaviour

Text block should not change its position 

## Steps to reproduce

1. Add a Text block and turn off Automatically fitting the text (amp-fit-text)
2. Add some text inside.
3. Rotate the block.
4. Change the font to "huge", without resizing the block larger before.
5. Observe results.

## Screenshots

![jumpinh](https://user-images.githubusercontent.com/3294597/66390719-87f31b00-e9cb-11e9-90ba-025a48dd3315.gif)

## Additional context

 N/A

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AC1: When a block is placed on a page, regardless of size or rotational orientation, it should have a centered focal point, so when the block is rotated, or resized, it does not "jump" visually on the page.

Related to #3444 

### Cause of the bug and possible fix
The issue here is that when the text size is changed to "huge" then the block is resized, it's resized not considering the rotation.

We should adjust the logic so that if block size is increased, the rotation angle should be considered as well and the `positionTop` and `positionLeft` values adjusted accordingly.

The logic needs updating within the `maybeUpdateBlockDimensions` function.

The `resizable-box` component is already doing similar calculations, the relevant helpers are in the `helpers.js` file of that component. We can reuse the helpers and move the shared ones to the helper's folder instead, where applicable.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by miina** [comment]
Implementation Brief added, ready for review.

**Comment by barklund** [comment]
Looks fine to me.

> We should adjust the logic so that if block size is increased, the rotation angle should be considered as well and the positionTop and positionLeft values adjusted accordingly.

Can we make sure to use the same logic already present in `resizable` to avoid duplicating? Is it helper-material?

**Comment by miina** [comment]
> Can we make sure to use the same logic already present in resizable to avoid duplicating? Is it helper-material?

Should be. Looks like `resizable` has its own helpers file where a helper could be pulled out to general helpers if it can be shared.

Will update the brief, thanks!

**Comment by csossi** [comment]
Verified in QA
