### ISSUE TITLE
Reordering Pages from carousel indicators not working

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3464]
## Bug Description

Carousel indicators below the Pages used to be draggable and it used to be possible to reorder the pages using just that. It's not possible anymore.

## Expected Behaviour

It should be possible to reorder Pages from carousel indicators.

## Steps to reproduce

1. Add some Pages
2. Try dragging the carousel indicators
3. See nothing happening, dropzone not showing up either.

## Screenshots

![reordering](https://user-images.githubusercontent.com/3294597/66406838-93a30980-e9ec-11e9-8a76-8fcc2c5d9e5e.gif)

## Additional context

See the original issue: #2525 

N/A

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Since #2525 is still on the board, let's fix it there.
