### ISSUE TITLE
Remove references to blocks in Stories editor

### ISSUE THREAD

**Issue by spacedmonkey** [ampproject/amp-wp#3466]
## Bug Description

There are a number places in the story editor, that still reference block. This is confusing as the story editor references to blocks as either pages and entries. 

Originally flagged in https://github.com/ampproject/amp-wp/pull/3417

## Expected Behaviour

Naming should be consistent throughout all of the editor.  

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Thanks for opening!

I don't think we've looked at this as a whole before, there were only a few smaller fixes like #2545 for example.

The problem with the wording is that we cannot (easily) change the wording in components provided by Gutenberg directly. That might change when we introduce something like #2554.
