### ISSUE TITLE
Validated URLS notification displays zero in counter

### ISSUE THREAD

**Issue by jdelia** [ampproject/amp-wp#3468]
## Bug Description

The Validated URLs notification displays a zero when all URLs are validated after moving to another menu link. 

## Expected Behaviour

Only show a notification counter when the value is greater than 0. 
## Steps to reproduce
Created a new local install of WordPress 5.2.3 with latest Gutenberg plugin 6.6.0 
Create an amp story.  (maybe optional)
Check the AMP Validated URL notifications. 
Even after rechecking URLS, the notification disappears, but when you click on another menu link, the zero notification appears again.

## Screenshots
Screen recording of issue https://cl.ly/a945e05a0117

 - WordPress version: 5.2.3
 - Plugin version: 1.3.0
 - Gutenberg plugin version (if applicable): 6.6.0

**Comment by westonruter** [comment]
Regression introduced by #3222.
