### ISSUE TITLE
The HTML4 meta[http-equiv=Content-Type] causes validation error to leak and should convert automatically to HTML5 meta[charset]

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3469]
## Bug Description

As reported in a [support forum topic](https://wordpress.org/support/topic/http-equivcontent-type-attribute-in-meta-tag/), if a theme like [Koji](https://wordpress.org/themes/koji/) declares the `Content-Type` using the HTML4 method like this:

```php
<meta http-equiv="content-type" content="<?php bloginfo( 'html_type' ); ?>" charset="<?php bloginfo( 'charset' ); ?>" />
```

Then the result the AMP plugin generating:

```html
<meta content="text/html; charset=UTF-8" charset="UTF-8" http-equiv="Content-Type">
```

Somehow the validating sanitizer is leaking the `http-equiv` and `content` attributes here, and this causes an error in the validator:

> ![image](https://user-images.githubusercontent.com/134745/66424817-5b93ca80-e9dc-11e9-8883-fd68c6ccc1c6.png)

This is even though the sanitizer is reporting the former as being invalid:

> ![image](https://user-images.githubusercontent.com/134745/66424272-52eec480-e9db-11e9-8c49-0a703ce117f1.png)

Even though it is accepted, it is not getting sanitized. So that's confusing.

The AMP plugin should transparently convert any such `meta` Content-Type tag into the HTML meta charset that AMP requires:

```html
<meta charset=utf-8>
```

See also #2970. This would have avoided an error in adding support for Twenty Twenty (https://github.com/ampproject/amp-wp/issues/3342#issuecomment-536197548) which was fixed in Twenty Twenty via https://github.com/WordPress/twentytwenty/pull/640.

Here is a workaround plugin for the issue: https://gist.github.com/westonruter/d18fd37fb9a58a26ae375a0cb9570831

There should not be any need to show a validation error as this should automatically get converted. If the site is using an encoding other than UTF-8, then technically the encoding should be getting converted to UTF-8 before being parsed. See:

https://github.com/ampproject/amp-wp/blob/603328895e81305718bbe2afd1b913b7f31ac9be/includes/class-amp-theme-support.php#L2290-L2294

This would fix #855.

## Expected Behaviour

An AMP-valid HTML5 meta charset should only be output.

## Steps to reproduce

1. Install and activate Koji theme.
2. Activate Standard or Transitional mode.
3. See the the AMP Validator report a validation error for `http-equiv` attribute.
4. See the admin bar report a validation error for the same.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `http-equiv` attribute should not be leaked to the frontend.
* Convert HTML4 `meta[http-equiv]` to HTML5 `meta[charset]`.
* (Nice to have) Convert encoding of input documents to UTF-8.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Another support topic that may be resolved by this issue: https://wordpress.org/support/topic/amp-errors-on-search-console-after-updating-to-v1-2-0/

**Comment by schlessera** [comment]
This should be fixed via #3758.

**Comment by westonruter** [comment]
Confirmed that the above build prevents there being a validation error for an `http-equiv` attribute, in the Koji theme.

## Before

![image](https://user-images.githubusercontent.com/134745/71131999-2dd0bc00-21ab-11ea-8c85-e99a98a57475.png)

The page's meta charset is an unexpected:

```html
<meta content="text/html" charset="UTF-8">
```

## After

No such validation error present and the meta charset is as expected:

```html
<meta charset="utf-8">
```

**Comment by csossi** [comment]
Verified in QA
