### ISSUE TITLE
AMP mode and plugin/theme versions need to be included in validated environment setting to determine whether stale

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3474]
## Bug Description

If you switch AMP mode, the validation cache is not invalidated. However, some validation results depend on whether the AMP page is the canonical URL, and therefore change between modes.

An example of this would be the change introduced in #3346, where a change from `Transitional` to `Standard` should change the excessive CSS validation errors from `New - Accepted` to `New - Rejected`.

## Expected Behaviour

When I switch the AMP mode, I expect the changes in validation to be immediately reflected.

## Steps to reproduce

1. Set mode to `Transitional`.
2. Add enough CSS to the page to hit the excessive CSS validation error on the AMP url of a page.
3. The validation screen will show that the excessive CSS validation error is marked as `New - Accepted`.
4. Change mode to `Standard`.
5. The validation screen for that same page will still show the excessive CSS validation error marked as `New - Accepted` - it should be `New - Rejected` instead.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
It would still be more correct to include the AMP mode in the validated environment setting, wouldn't it? Or do you see a major drawback in doing so? Is invalidating everything on mode switch too big of a deal?

**Comment by westonruter** [comment]
Making results stale more often I suppose is not bad. In fact, stale results will encourage re-checking. Since all validated URLs are cached, re-checking them periodically would be good, and if they show as stale more often then this should be the result.

**Comment by westonruter** [comment]
Let's also include the plugin/theme version when indicating staleness. This will be important when there are validation errors being caused by a theme resulting in someone turning off the plugin for AMP responses (a new capability to be built), but then once a plugin is updated they should re-check for stale results to see if the plugin update fixed the issue.

**Comment by westonruter** [comment]
QA Passed for plugins.

Before bumping Akismet version:

![image](https://user-images.githubusercontent.com/134745/87255085-94b20d00-c43c-11ea-9f7d-e48b64286773.png)

After:

![image](https://user-images.githubusercontent.com/134745/87255089-a1cefc00-c43c-11ea-81b8-d780cc228afb.png)

But _not_ for the theme. Changing the ~plugin~ **theme** version does not have the same effect.
