### ISSUE TITLE
Update blue to use WordPress's new blue

### ISSUE THREAD

**Issue by spacedmonkey** [ampproject/amp-wp#3475]
## Bug Description

Update buttons and highlights to use updated WordPress colours. 

## Expected Behaviour

All buttons and icons should use WordPress blue. 

## Screenshots
WordPress's new blue
![Screenshot from 2019-10-09 15-18-56](https://user-images.githubusercontent.com/237508/66489977-59973d80-eaa8-11e9-9022-022d328f06e0.png)

Current blue
![Screenshot from 2019-10-09 15-14-31](https://user-images.githubusercontent.com/237508/66490026-6d42a400-eaa8-11e9-8089-8f631af55f71.png)
![Screenshot from 2019-10-09 15-15-08](https://user-images.githubusercontent.com/237508/66490066-7fbcdd80-eaa8-11e9-9ae1-2f21847aebb0.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Looks like it changed from `#0085ba` to `#007cba`.

Need to change thee PostCSS config like Gutenberg did in https://github.com/WordPress/gutenberg/pull/17645

**Comment by spacedmonkey** [comment]
I just checked and other themes do not seem to be effected. 

@swissspidy should be wait WP 5.3. Otherwise the buttons will look out of place.

**Comment by swissspidy** [comment]
Let's include this 👍 

I'll create a new issue for WordPress 5.3 support in general.

**Comment by spacedmonkey** [comment]
Now that this PR is play, we should also now revisit AXE tests and colour contrasts.
