### ISSUE TITLE
Reordering displays the blocks incorrectly

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3481]
## Bug Description

The block preview in the Reordering interface is off.

## Expected Behaviour

The block preview when reordering should reflect the actual page layout quite accurately.

## Steps to reproduce

1. Add some blocks.
2. Start Reordering
3. Observe the difference

## Screenshots

Editor:
<img width="366" alt="Screenshot 2019-10-10 at 19 29 50" src="https://user-images.githubusercontent.com/3294597/66592299-1070e780-eb95-11e9-9164-cd122220905b.png">

Reordering:
<img width="902" alt="Screenshot 2019-10-10 at 19 29 40" src="https://user-images.githubusercontent.com/3294597/66592301-1070e780-eb95-11e9-8067-4b8b61de79c6.png">

## Additional context

 - Gutenberg plugin version (if applicable): latest `develop` as of 10th of October. Also tested with the latest stable release.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The block preview when reordering should reflect the actual page layout in terms of layout and proportions

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

* Improved Gutenberg compatibility on the reorder screen

**Comment by swissspidy** [comment]
Ah, was just about to file this as well.

There were some significant changes to the BlockPreview component in Gutenberg. We now don‘t have to scale down and position elements ourselves anymore I think.

**Comment by spacedmonkey** [comment]
![Screenshot from 2019-10-28 13-18-08](https://user-images.githubusercontent.com/237508/67681561-79be6c00-f985-11e9-8042-a9f505f4f5f1.png)
![Screenshot from 2019-10-28 13-17-25](https://user-images.githubusercontent.com/237508/67681565-7c20c600-f985-11e9-9090-e38ff3e4b91c.png)

I played around with the css property `transform: scale(0.5);` to scale the original pages. This results in a perfect preview. However, it would mean we would have to reimplement the reordering.

**Comment by swissspidy** [comment]
We probably need to adjust the `BlockPreview`'s `viewportWidth` prop, as Gutenberg uses that for its internal `scale()`. Right now we do our own, which is now obsolete though. In other words:

* Remove our custom `scale()`
* Adjust `viewportWidth` so the preview is correct again
