### ISSUE TITLE
Remove duplicate and unused AMP component scripts from the response

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3489]
## Feature description

If you include more than one copy of an AMP component script on a page, e.g. `amp-form`, then the validator gives a warning:

![image](https://user-images.githubusercontent.com/134745/66708268-b5f59980-ed02-11e9-8edb-31a2eaee0334.png)

In the same way, if there are scripts on the page which are not used, a validation error is also raised:

![image](https://user-images.githubusercontent.com/134745/68098188-eef7d880-fe80-11e9-9f59-d21b38bcced5.png)

These issues come up often in the Reader mode templates which don't send the entire templates through the post-processor (which will be fixed in #2202), but it can also happen in Standard/Transitional mode when duplicate scripts are manually output in `wp_head` or `wp_footer` actions (which normally should not be done since the plugin adds them already).

Cf. https://github.com/ampproject/amp-wp/pull/3253#discussion_r326385709

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

The [`AMP_Theme_Support::ensure_required_markup()`](https://github.com/ampproject/amp-wp/blob/394b2023aaf7bb83146c3968d5b43e8be194cac7/includes/class-amp-theme-support.php#L1526-L1894) method is passed a list of `$script_handles` for the AMP scripts that are required to be in the page. If those scripts are not already present in the DOM, then they are added:

https://github.com/ampproject/amp-wp/blob/394b2023aaf7bb83146c3968d5b43e8be194cac7/includes/class-amp-theme-support.php#L1730-L1746

There are two things missing here:

1. If there is more than one copy of a given script on the page, the duplicates need to be removed.
2. If there are AMP scripts present on the page which are _not_ present in `$script_handles` then they should be removed, as otherwise there can be an AMP validation error (as they are unused).

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kienstra** [comment]
Hi @westonruter,
Hope you had a great day.

Would the duplicate component scripts, like in the [screenshot above](https://github.com/ampproject/amp-wp/issues/3489#issue-506244052), be output with an [amp_post_template_head](https://github.com/ampproject/amp-wp/blob/1a08b1cf837ba70d564260411b2c85501e2f05c7/templates/html-start.php#L29) hook, like this?

```php
add_action( 
        'amp_post_template_head', 
        function() {
                // Echo component scripts here.
        }
);
```

It looks like the [recommended way](https://github.com/ampproject/amp-wp/issues/1095#issuecomment-384027194) of adding component scripts won't normally have duplicates.

**Comment by westonruter** [comment]
@kienstra Sorry for the delay. They could be added in that way, yes, but this won't be the concern in this issue at the moment. Handling scripts added in Reader mode would be fixed as part of #2202, as the entire document would be then sent through the post-processor.

So for this issue, focus on scripts that are added in Standard/Transitional mode. That means scripts that are added at the `wp_head` or `wp_footer` actions.  I've updated the summary of the issue and provided an implementation brief. The scope is also expanded to include not just duplicate script but also unused scripts.

**Comment by kienstra** [comment]
Thanks, @westonruter! No problem, I didn't expect or need a quick response, with the stable release and WCUS this past week.

**Comment by schlessera** [comment]
I'm currently working on this and I'll do two separate PRs, as both the implementation as well as the ramifications are different for the two cases enumerated above.

**Comment by westonruter** [comment]
> I'm currently working on this and I'll do two separate PRs, as both the implementation as well as the ramifications are different for the two cases enumerated above.

The other PR would be about removing the duplicates? It seems to me that the existing PR could include the de-duplication as well.

**Comment by schlessera** [comment]
> The other PR would be about removing the duplicates? It seems to me that the existing PR could include the de-duplication as well.

The thinking was that removing duplicates is a no-brainer, always fixing and never breaking. However, removing unused AMP scripts is more complicated and could potentially lead to use automatically breaking an otherwise working page, because we're missing something.

**Comment by csossi** [comment]
Verified in QA
