### ISSUE TITLE
Disable Code Editor

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3496]
## Feature description

The AMP Stories editor is built on top of the Gutenberg block editor, which has a feature to switch between visual editing and the underlying code representing the blocks.

Other than in the regular post editor, this code view is not something that is of use in the stories editor.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Access to the code editor via the "More tools & options" in top right corner should be prevented, i.e. it should not be visible
* The keyboard shortcut should not work either
* Access to the code editor for an individual block via the  block toolbar should be prevented as well

## Implementation brief

* `\AMP_Story_Post_Type::filter_block_editor_settings` should be amended to disable `codeEditingEnabled`. `richEditingEnabled` should be always `true` in that case.  
  ([Documentation](https://developer.wordpress.org/block-editor/developers/filters/editor-filters/))
* All parts of code related to the code editor should be removed as they are no longer needed.

## QA testing instructions

1. Create a new story
1. Edit text block
1. **Verify:** In the "More tools" (three dots) menu in the block toolbar, there should be no "Edit as HTML" option visible
1. Click on "More tools & options" in top right corner
1. **Verify:** there should be no "Code editor" menu item in the list

## Demo

* https://cloudup.com/czrUvAm_UGi

## Changelog entry

* Disabled access to code editor

**Comment by spacedmonkey** [comment]
![Screenshot from 2019-10-18 15-52-48](https://user-images.githubusercontent.com/237508/67104737-652ce780-f1bf-11e9-9d1a-361930aa7bc0.png)
Will this also remove the 'Edit as html' button in the context menu?

**Comment by swissspidy** [comment]
Yes it should

**Comment by spacedmonkey** [comment]
> Yes it should

It seems like it does 
https://github.com/WordPress/gutenberg/blob/f3e8ac15a9294bc1ca3998dbcd7c9c599249ecdb/packages/block-editor/src/components/block-settings-menu/block-mode-toggle.js#L16-L18

**Comment by spacedmonkey** [comment]
Seems simple enough to me. Approved IB.

**Comment by csossi** [comment]
Verified in QA
