### ISSUE TITLE
Improve Xdebug warning

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3499]
## Feature description

As mentioned on #3198 and #1915, there are some issues with the current admin notice that is shown when Xdebug is active. Screenshot:

<img width="799" alt="Screenshot 2019-10-14 at 16 07 09" src="https://user-images.githubusercontent.com/841956/66757563-ba55ba00-ee9c-11e9-90d3-6e8f6cbb549d.png">

Mainly, the notice is shown even when it is not actually relevant to the site (i.e. Reader mode is used) or when the user cannot do something about it (i.e. they are not an admin).

I'm seeing that myself as well as I've become numb to that warning and don't even notice it anymore really.

A  few thoughts:

1. Don't display notice when using Reader mode (at least until #2202 is done)
1. Only display notice when user can `manage_options`
1. Only display the notice on the AMP plugin settings screen
1. Make notice dismissible with persistence in user settings (bonus: still always show it on the settings screen)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Remove notice in favor or Site Health, or at least limit notice to just AMP settings screen.
* Limit to administrators and/or when `WP_DEBUG` is enabled?

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I think we should move this to Site Health. Potentially we can also put the warning in the admin bar.

**Comment by westonruter** [comment]
We should also consider only showing the warning if `WP_DEBUG` is enabled.

**Comment by westonruter** [comment]
Here's how Site Health is shown on the admin dashboard in a widget:

![image](https://user-images.githubusercontent.com/134745/75820342-08d2fa80-5d51-11ea-8db4-14d1d91f4dac.png)

**Comment by kienstra** [comment]
Hi @westonruter,
Good to see you.

Like you mentioned, what do you think about:

1. Removing the warning entirely as it exists now
2. Display the warning in Site Health if Xdebug is enabled and `WP_DEBUG` is `true`

![xdebug-here](https://user-images.githubusercontent.com/4063887/77097471-7714ef80-69d6-11ea-85b6-6076b56f7074.png)

**Comment by westonruter** [comment]
> 2\. Display the warning in Site Health if Xdebug is enabled and `WP_DEBUG` is `true`

If it is `true` or if it is `false`?  I should think that the warning is most relevant when `WP_DEBUG` is `false` as this can indicate the site is running in production where Xdebug certainly should not be active.

**Comment by kienstra** [comment]
Ah, good point. If Xdebug enabled and `WP_DEBUG` is `false`.

**Comment by kienstra** [comment]
**Testing Steps**

1. Go to [Site Health](https://am.test/wp-admin/site-health.php)
2. Click 'Passed Tests'
3. Expected: this appears:

![expected-site-health](https://user-images.githubusercontent.com/4063887/77467515-c2157500-6dd1-11ea-92ad-bcc06c5e94d8.png)
