### ISSUE TITLE
Giphy embed code fails to create amp-iframe[layout=fill], erroneously outputs height=""

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3501]
## Bug Description

There is [another case](https://wordpress.org/support/topic/amp-html-tag-has-an-invalid-layout-specified-by-its-attributes-6/) for fill iframes not accounted for by #3142 and #3209/#3295.

Consider this source Giphy embed markup:

```html
<div style="width: 100%; height: 0; padding-bottom: 100%; position: relative;"><iframe class="giphy-embed" style="position: absolute;" src="https://giphy.com/embed/OooCfM8WuHPc4" width="100%" height="100%" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>
<p><a href="https://giphy.com/gifs/sharpie-art-motion-OooCfM8WuHPc4">via GIPHY</a></p>
```

It is getting converted to AMP as:

```html
<div class="amp-wp-659d28d"><amp-iframe class="giphy-embed amp-wp-b38de02" src="https://giphy.com/embed/OooCfM8WuHPc4" width="auto" height="" frameborder="0" allowfullscreen="" layout="fixed-height" sandbox="allow-scripts allow-same-origin"><span placeholder="" class="amp-wp-iframe-placeholder"></span><noscript><iframe class="giphy-embed amp-wp-b38de02" src="https://giphy.com/embed/OooCfM8WuHPc4" width="100%" height="100%" frameborder="0"></iframe></noscript></amp-iframe></div>
<p><a href="https://giphy.com/gifs/sharpie-art-motion-OooCfM8WuHPc4">via GIPHY</a></p>
```

Notice `height=0`. The logic needs to apply not only when top/right/bottom/left are 0 but also when just width/height are 100% generally.

## Expected Behaviour

The `amp-iframe` should have `layout=fill`.

## Steps to reproduce

1. Add a Custom HTML block with the above Giphy code.
2. View the post in AMP.
3. The `amp-iframe` erroneously has `height=0` and the `amp-iframe` is not visible on the page at all.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* Copy the source Giphy markup into a Custom HTML block.
* View the AMP version of the post.
* Verify that the Giphy embeds responsively.

## Demo

![image](https://user-images.githubusercontent.com/16200219/66958018-f61f8980-f02c-11e9-9f82-f1a1fd39e770.png)

## Changelog entry

* Apply `layout=fill` to the `amp-iframe` when both the width and height are 100%.

**Comment by westonruter** [comment]
@pierlon Please add before/after screenshots under the Demo section.

**Comment by csossi** [comment]
Verified in QA
![image](https://user-images.githubusercontent.com/16945664/67728863-3daafb80-f9c5-11e9-9630-88282868f36f.png)
![image](https://user-images.githubusercontent.com/16945664/67728893-587d7000-f9c5-11e9-9723-5f0f9fe053f2.png)
