### ISSUE TITLE
Image alignment not functional

### ISSUE THREAD

**Issue by barklund** [ampproject/amp-wp#3504]
## Bug Description

Image alignment is once again possible in Story editor (probably due to changes upstream) and is once again broken.

If you try to align the image using any of the options, nothing useful happens.

This has been fixed before in #2115.

## Expected Behaviour

No image alignment option should be displayed.

## Steps to reproduce

1. Create a new story
2. Add and select an image.
3. Click the image alignment dropdown in top bar.
4. See useless options.

## Screenshots

<img width="528" alt="Screenshot 2019-10-14 at 18 03 56" src="https://user-images.githubusercontent.com/637548/66786520-a0bd6e00-eeae-11e9-8178-f948cb66bab7.png">

## Additional context

 - WordPress version:
 - Plugin version: **develop**
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No alignment controls should be visible for image block
* No alignment controls should be visible for video block
* No alignment controls should be visible for pullquote block
* No alignment controls should be visible for embed block

## Implementation brief

* Update the CSS selectors/add new selectors to ensure that the alignment toolbar is hidden.
* The current selectors are here:
https://github.com/ampproject/amp-wp/blob/468b3492fe8611a13fcbebee8cbd62966ac71376/assets/src/stories-editor/blocks/amp-story-page/edit.css#L217-L226

## QA testing instructions

* Create a new story
* Create a new page
* Create Image / table / pullquote / embed / video block. 
* Verify block options do not show. 

## Demo

![Screenshot from 2019-10-29 13-02-54](https://user-images.githubusercontent.com/237508/67769681-d2a50780-fa4c-11e9-8c37-c5ab158d401e.png)
![Screenshot from 2019-10-29 13-02-27](https://user-images.githubusercontent.com/237508/67769682-d2a50780-fa4c-11e9-8a9b-e9ed767ae350.png)

## Changelog entry

* Fixed an issue with disabled block alignment support

**Comment by swissspidy** [comment]
Ugh 😞 

Good catch! Looks like the DOM structure changed there again. The culprit might be https://github.com/WordPress/gutenberg/pull/16421

Of course it doesn't help that the image block uses a hardcoded alignment toolbar still: https://github.com/WordPress/gutenberg/issues/13780

Some options:

* Fix this upstream in Gutenberg (will take too long, but this makes it more future-proof
* Update CSS selectors once again
* Completely override the image block's (and potentially others) `edit` component and remove irrelevant stuff (gives us more control, but adds maintainability burden)
* Override `wp.blockEditor.BlockAlignmentToolbar` component with one that just returns `null`

**Comment by swissspidy** [comment]
> Update CSS selectors once again

Is easier when we are guaranteed to be on the latest Gutenberg version, see #3546

**Comment by miina** [comment]
> Override `wp.blockEditor.BlockAlignmentToolbar` component with one that just returns `null`

This sounds like be a good option if we can do that per block since some blocks still need the alignment (e.g. Text, post meta). I suppose it should be possible to check which block is selected and depending on that either override it or not?

**Comment by swissspidy** [comment]
Those use `wp.blockEditor.AlignmentToolbar` it seems, so there would be no conflict.

In my quick testing I was not able to modify any ``wp.blockEditor.*` component though, they seem to be non-configurable:

```js
Object.getOwnPropertyDescriptor( window.wp.blockEditor, 'BlockAlignmentToolbar' ).configurable
// false
```

Only `window.wp.blockEditor` as a whole could be rewritten, which is currently not an option (related: #2554).

SO it sounds like this route is not possible at the moment.

**Comment by miina** [comment]
In this case, updating the CSS selector seems to be the only viable option for the bug fix right now.

Perhaps we should create a follow-up issue to discuss a more permanent fix and just do the CSS fix for now. Thoughts?

**Comment by swissspidy** [comment]
This probably ties well enough into #2554 and the design doc I'm planning on writing about that. I will mention this scenario there, but a follow-up issue makes sense nevertheless 👍

**Comment by miina** [comment]
Follow-up issue: https://github.com/ampproject/amp-wp/issues/3580

**Comment by miina** [comment]
Moving to IBR per previous conversation.

**Comment by spacedmonkey** [comment]
After looking into this, I found that change the [block supports](https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#supports-optional) to `align: false`, is a much more effect way of resolving this issue. 

Thoughts @miina

**Comment by miina** [comment]
Good point, If that works then definitely 👍

**Comment by csossi** [comment]
Verified in QA

**Comment by spacedmonkey** [comment]
Added https://github.com/WordPress/gutenberg/issues/13780 which will help resolve the issue going forward.
