### ISSUE TITLE
Full width iframes have `layout=intrinsic` by default

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3506]
## Bug Description

When an iframe is set to be "full width" in the block editor, it is currently broken because its `layout` attribute defaults to `'intrinsic'`.

## Expected Behaviour

An iframe that is set to be "full width" in the block editor should have `'responsive'` as its `layout` attribute.

## Steps to reproduce

1. In the block editor, add an embed block and copy in the URL `https://wordpress.tv/2019/10/08/the-history-of-wordpress-in-four-minutes/`.
2. Set the alignment to "Full width".
3. Publish the post and visit it on its AMP URL.
4. The embedded video will not be full-width, but rather aligned to the left. Its markup shows that the it is set to `layout=intrinsic`.

## Screenshots

Choosing the "Full width" alignment:
![Image 2019-10-15 at 12 03 45 PM](https://user-images.githubusercontent.com/83631/66822736-23910800-ef45-11e9-948c-227ddee31a80.png)

Comparison:
![Image 2019-10-15 at 12 05 14 PM](https://user-images.githubusercontent.com/83631/66822746-268bf880-ef45-11e9-8e2c-547a732fe252.png)

AMP markup:
![Image 2019-10-15 at 12 05 42 PM](https://user-images.githubusercontent.com/83631/66822751-2986e900-ef45-11e9-8ccd-e7af095f2e6d.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
**Testing instructions:**
1. In the block editor, add an embed block and copy in the URL https://wordpress.tv/2019/10/08/the-history-of-wordpress-in-four-minutes/.
2. Set the alignment to "Full width".
3. Publish the post and visit it on its AMP URL.
4. Verify that the embedded video is full-width.
5. Verify that its markup shows that it is set to `layout=responsive`.

**Comment by csossi** [comment]
Verified in QA
