### ISSUE TITLE
maybeSetInitialPositioning not ignoring non-movable blocks

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3541]
## Bug Description

`maybeSetInitialPositioning` tries to position newly inserted blocks nicely on the page so that they do not overlap.

However, when there is a CTA block on a page, that doesn't work because it takes that block's position also into account.

It should only care about movable blocks.

## Expected Behaviour

When there is a CTA or page attachment block on a page, newly inserted blocks should still be inserted underneath each other.

## Steps to reproduce

1. On the first page, add a few text blocks
2. Notice how they're nicely arranged underneath each other.
3. On the second page, add a CTA block.
4. Add a few text blocks
5. Notice how they are all positioned on top of each other

## Screenshots

![Screenshot 2019-10-16 at 16 45 10](https://user-images.githubusercontent.com/841956/66930060-56fe9000-f034-11e9-9105-07aba78bcdda.png)

## Additional context

 - WordPress version: 5.3 Beta
 - Plugin version: current `develop`
 - Gutenberg plugin version (if applicable): 6.6

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When inserting multiple elements on a page, they should not be stacked on top of each other.

## Implementation brief

`maybeSetInitialPositioning` determines the `positionTop` of its siblings in the following lines:
https://github.com/ampproject/amp-wp/blob/e8b003750940062329ae0d2bddffa1c3cc38a504/assets/src/stories-editor/helpers/maybeSetInitialPositioning.js#L47-L49

This should also consider the CTA block and Page Attachment block (non-movable blocks), we can achieve that by adding additional `filter` to `parentBlock.innerBlocks` to ensure that only movable blocks are considered, e.g.
```
const highestPositionTop = parentBlock.innerBlocks
        .filter( ( childBlock ) => [LOGIC TO TEST IF MOVABLE] )
	.map( ( childBlock ) => childBlock.attributes.positionTop )
        ...
```

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by miina** [comment]
Looking into this to write IB.

**Comment by miina** [comment]
Ready for IBR.

**Comment by swissspidy** [comment]
LGTM 👍

**Comment by csossi** [comment]
Verified in QA
