### ISSUE TITLE
Bump WordPress / Gutenberg requirement

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3546]
## Feature description

The AMP Stories editor currently requires at least Gutenberg 5.9 due to some of the JS dependencies in the editor. Also, we require at least WordPress 5.0, even when the Gutenberg plugin is installed.

Now that WordPress 5.3 is around the corner which includes Gutenberg 6.6, we should adjust the requirements in `\AMP_Story_Post_Type::has_required_block_capabilities()` accordingly:

https://github.com/ampproject/amp-wp/blob/5799032d4cc9882ceac94966f67c318ebb60eb68/includes/class-amp-story-post-type.php#L102-L111

To make maintenance and support easier, I suggest the following:

* WordPress 5.3+ _or_
* Gutenberg 6.6+

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The editor should be accessible on WordPress 5.3 RC 1 or higher, without requiring the Gutenberg plugin
* If the WordPress version is older than WordPress 5.3, it should require the latest version of Gutenberg to be installed (6.6 as of this writing).

## Implementation brief

* Bump `REQUIRED_GUTENBERG_VERSION`
* Make the requirements check pass for WordPress 5.3 RC and higher
* Adjust inline documentation where necessary

## QA testing instructions

1. Check that you're using WordPress 5.3 RC
1. Disable Gutenberg plugin
1. Verify that the story editor is still functioning.

## Demo

* https://cloudup.com/cn-sy1Jn7zO

## Changelog entry

* Do not require Gutenberg to be active when running WordPress 5.3 or higher

**Comment by spacedmonkey** [comment]
Have all the existing gutenberg packages been updated to ones that are shipped in GB 6.6

**Comment by swissspidy** [comment]
Yes, but for us they‘re only really relevant for development anyway. The editor uses whatever is provided by WP / Gutenberg, we don‘t bundle them ourselves.

**Comment by spacedmonkey** [comment]
> Yes, but for us they‘re only really relevant for development anyway. The editor uses whatever is provided by WP / Gutenberg, we don‘t bundle them ourselves.

We don't use libraries that are loaded on the page like this 

```
const { registerBlockType } = wp.blocks;
```
We do it like this. 
```
import { registerBlockType } from '@wordpress/blocks';
```

So don't the packages have be up to date in our package file? 
Doesn't doing it this bundle another version of the function into our js?

**Comment by swissspidy** [comment]
> We do it like this.

Yes, we do. But webpack automatically turns this into `const { registerBlockType } = wp.blocks;` for us when building.

**Comment by swissspidy** [comment]
That's why these packages are all just `devDependencies` — they are not in the final bundle. They should still be up to date for development purposes.

**Comment by csossi** [comment]
Verified in QA
