### ISSUE TITLE
Set up code owners

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3548]
## Feature description

[Code owners](https://help.github.com/en/articles/about-code-owners) are automatically requested for review when someone opens a pull request that modifies code that they own. Code owners are not automatically requested to review draft pull requests.

This might be useful for us, especially since the code base contains both the AMP plugin itself as well as the AMP Stories editor.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Closing since Stories has been extracted.
