### ISSUE TITLE
Resizing a block very large makes the block slide

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3549]
## Bug Description

Resizing a block very large makes the block slide

## Expected Behaviour

Blocks should not start sliding when resizing very large.

## Steps to reproduce

1. Add a Text block
2. Resize it to be very large
3. See the sliding

## Screenshots

![sliding](https://user-images.githubusercontent.com/3294597/67006851-5e7e7180-f0e6-11e9-915d-c6a809bb1072.gif)

## Additional context

 N/A

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* After grabbing a corner of the text block and resizing the block, the opposite corner should be anchored and not move as I resize the block 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
Hey @jasti after testing this, it seems the sliding is specific to resizing via the corners. It also appears that the opposite corner is anchored up to a certain size, then it begins to slide the position of the block. As such, I've added AC to hold that anchor when resizing. 

Moving to the IB column.

**Comment by miina** [comment]
@jauyong Note that it's not happening from the corners only, it's happening from some sides as well, e.g. when resizing from the left side. Perhaps a general AC for ensuring that the block doesn't slide when resizing from any of the handles would be good, even if some of the non-corner handles work correctly?
