### ISSUE TITLE
Meta blocks sometimes "jump" when resizing with amp-fit-text off

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3550]
## Bug Description

When amp-fit-text is turned off and resizing a meta blocks quite close to its content minimum limits then it sometimes jumps.

Potentially related: #3461 

## Expected Behaviour

Meta blocks should not jump when resizing.

## Steps to reproduce

1. Add Title block
2. Turn off amp-fit-text
3. Turn on "huge" for font size (easier to reproduce with that)
4. Resize the block so that the edges would go quite close to the Text limits from one side. E.g. make it quite narrow vertically but horizontally leave space.

## Screenshots

![meta-blocks](https://user-images.githubusercontent.com/3294597/67007249-40654100-f0e7-11e9-8219-5a3af8c15f60.gif)

## Additional context

N/A

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
Hey @miina I'm not able to replicate this. I only get the sliding from #3549

**Comment by miina** [comment]
Yep, still happening, just tested on staging:
![meta-jumping](https://user-images.githubusercontent.com/3294597/67904370-27737b80-fb3c-11e9-8c21-88721af39018.gif)
