### ISSUE TITLE
TwentyTwenty modal admin bar offset is targeting wrong class

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3569]
## Bug Description

The TwentyTwenty theme compat code needs to add a CSS offset to a modals when the admin bar is shown, so that they are not partially obscured by the admin bar.

The current code targets a specific modal, though (`.menu-modal`), instead of _all_  modals (`.cover-modal`).

This causes the search modal to be stuck behind the admin bar still.

## Expected Behaviour

All modals should be offset to account for the admin bar.

## Steps to reproduce

1. Open a twentytwenty-themed site at any AMP URL.
2. Click on the magnifying glass in the header bar to open the search modal.

## Screenshots

![Image 2019-10-21 at 12 55 16 PM](https://user-images.githubusercontent.com/83631/67199642-0acf9900-f402-11e9-8b39-48919e77abed.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA:
![image](https://user-images.githubusercontent.com/16945664/67731721-7c45b380-f9cf-11e9-920b-1f75857c97cd.png)
