### ISSUE TITLE
Clicking outside of a TwentyTwenty modal does not close the modal

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3570]
## Bug Description

Clicking outside of a modal in a TwentyTwenty-themed site does not close the modal.

## Expected Behaviour

When clicking outside of an open modal, the modal should close again.

## Steps to reproduce

1. On a twentytwenty-themed site, open any AMP URL.
2. Open the search modal by clicking the magnifying glass in the header bar.
3. Try to close the search modal by clicking outside of it.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
