### ISSUE TITLE
Page Attachment can be copied to a Page where CTA already exists

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3575]
## Bug Description

Page Attachment can be copied to a Page where CTA already exists.

## Expected Behaviour

Each Page can only have exactly 0 or 1 unmovable block. If either a CTA block or a Page Attachment block already exists on a Page then it should not be possible to Paste another unmovable block to that Page.

- The Paste option should not appear in the context menu if Pasting the block is forbidden.
- PasteHandler should consider Page Attachment block as well and prevent Pasting, currently, it does have a `case` but it does not handle it properly:
https://github.com/ampproject/amp-wp/blob/a3c6ba303e16ac6bac988618bbd12cd682c4ff93/assets/src/stories-editor/helpers/ensureAllowedBlocksOnPaste.js#L22-L29

## Steps to reproduce

1. Add 2 Pages
2. Add Page Attachment to the first Page
3. Add CTA block to the second Page
4. Right-click on the Page Attachment and choose "Copy" from the context menu
5. Right-click on the second Page and choose "Paste" from the context menu.
6. See both CTA block and Page Attachment block on the second Page.

## Screenshots

<img width="406" alt="Screenshot 2019-10-21 at 14 47 42" src="https://user-images.githubusercontent.com/3294597/67206357-c5b36300-f411-11e9-8ac8-f4d55d01083f.png">

## Additional context

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. When pasting, page attachment blocks should not be inserted when there already is another page attachment block on the page.
1. When pasting, page attachment blocks should not be inserted when there already is a CTA block on the page.
1. When pasting, CTA blocks should not be inserted when there already is another CTA block on the page.
1. When pasting, CTA blocks should not be inserted when there already is a page attachment block on the page.

## Implementation brief

- Replace usage of `ensureAllowedBlocksOnPaste` with `isBlockAllowedOnPage` hook, as this check is more robust. 

- Remove all references to `ensureAllowedBlocksOnPaste`.
- Check a block can not be pasted, display a 'snap' message to inform user the block could not be pasted.  

## QA testing instructions

1. Add 2 Pages
2. Add Page Attachment to the first Page
3. Add CTA block to the second Page
4. Right-click on the Page Attachment and choose "Copy" from the context menu
5. Right-click on the second Page and choose "Paste" from the context menu.
6. Verify that Page Attachment is not allowed on the second page and a snackbar with a notice appears.

Repeat with CTA block copied to page with Page Attachment and vice-versa.
Repeat with pasting via keyboard.

## Demo

* https://youtu.be/tDrUMX-ztKI

## Changelog entry

* Prevent pasting CTA or Page Attachment blocks when one already exists.

**Comment by swissspidy** [comment]
> The Paste option should not appear in the context menu if Pasting the block is forbidden.

Not sure how feasible that is. It basically means requesting access to the clipboard and running (parts of) `processTextToPaste` before even pasting. Seems a bit odd from a UX perspective.

**Comment by swissspidy** [comment]
Added ACs for the other part so far.

**Comment by miina** [comment]
> Not sure how feasible that is. It basically means requesting access to the clipboard and running (parts of) processTextToPaste before even pasting. Seems a bit odd from a UX perspective.

Hmm, maybe. We could use the locally saved "clipboard" data for that, if it exists, however, this would make the behaviour quite inconsistent.

Perhaps notifying the user via a snackbar message that Pasting was not allowed could make sense then?

**Comment by spacedmonkey** [comment]
There are now two very similar functions in [ensureAllowedBlocksOnPaste](https://github.com/ampproject/amp-wp/blob/910eb1021e8b00c1c14de6413b12b523fd2bf649/assets/src/stories-editor/helpers/ensureAllowedBlocksOnPaste.js) and the hook [useIsBlockAllowedOnPage](https://github.com/ampproject/amp-wp/blob/b7b55391b7da4d65483fdf816c820d484d66ae34/assets/src/stories-editor/helpers/useIsBlockAllowedOnPage.js). I believe we should go ahead and use `useIsBlockAllowedOnPage`, as it seems more solid. 

> Perhaps notifying the user via a snackbar message that Pasting was not allowed could make sense then?

:arrow_up:  :+1:

**Comment by spacedmonkey** [comment]
Replacing
```
const isFirstPage = getBlockOrder().indexOf( pageClientId ) === 0;
insertBlocks( ensureAllowedBlocksOnPaste( content, pageClientId, isFirstPage ), null, pageClientId ).then( ( { blocks } ) => {
```
With
```
const blockContent = content.filter( ( { name } ) => isBlockAllowedOnPage( name, pageClientId ) );
insertBlocks( blockContent, null, pageClientId ).then( ( { blocks } ) => {
```

Worked in my tests. 

Other references to `ensureAllowedBlocksOnPaste` can be removed to make the code clearer.

**Comment by csossi** [comment]
Verified in QA
