### ISSUE TITLE
Dragging not working as expected when CTA block present

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3577]
## Bug Description

If there's a CTA block present then adding a Text block and trying to drag it results in the Text block being positioned incorrectly.

This happens only if the block is in the initial position (`positionTop=0` due to the CTA block), the blocks that have been positioned before already, don't have this issue.

The reason might be more related to the `positionTop` value `0` and not specifically with the CTA block.

## Expected Behaviour

Dragging should work as expected.

## Steps to reproduce

1. Add two Pages
2. Add CTA block
3. Add a Text block
4. Try dragging the Text block
5. See the dragging not working as expected.

## Screenshots

![dragging](https://user-images.githubusercontent.com/3294597/67218774-3f098080-f427-11e9-9dce-adeeb581e50d.gif)

## Additional context

 - WordPress version:
 - Plugin version: develop
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
I can confirm seeing the same, but only once. When dropping the text block and dragging it again, it works as expected. Very odd.

**Comment by miina** [comment]
I can also see it only once. It might have something to do with `positionTop` being `0`.

**Comment by barklund** [comment]
If you cut it and paste it in the same place on the same page (or another page), there's no issue. So it's probably not the position. It's somehow not initialised correctly.

But I guess this needs priority and AC before we investigate further.

**Comment by spacedmonkey** [comment]
I am not seeing the same Ubuntu in Chrome and Firefox.

**Comment by jauyong** [comment]
I can't replicate this

**Comment by miina** [comment]
Looks like something fixed it meanwhile, perhaps #3584.

Also can't replicate this anymore.

**Comment by swissspidy** [comment]
Closing this for now in that case :-)
