### ISSUE TITLE
Disable lightbox toggle for image linking to attachment pages

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3579]
## Feature description

This is a follow-up to #3450. As proposed in https://github.com/ampproject/amp-wp/pull/3460#pullrequestreview-304677157, _"the lightbox toggle should probably be prevented from even being made available when the image block has a link to the attachment page. Otherwise, the lightbox toggle has no effect when an attachment page is linked."_

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@jamesozzie pointed out that images in AMP pages now automatically get lightboxing. See https://github.com/ampproject/amphtml/blob/master/spec/auto-lightbox.md

Do we even need the lightbox toggle anymore?

**Comment by amedina** [comment]
> Do we even need the lightbox toggle anymore?

Closing (as per comment above) and will reopen if needed.

**Comment by westonruter** [comment]
Let's leave open because we should remove the toggle if indeed it is unnecessary.

**Comment by westonruter** [comment]
Closely related issue: #4591

**Comment by westonruter** [comment]
Attachment pages are disabled in 6.4. Also, in 6.4 lightbox images are now supported in core. So in https://github.com/ampproject/amp-wp/issues/7676 we're going to eliminate the AMP toggle when on 6.4. Otherwise, it doesn't seem necessary to anything further with this issue.
