### ISSUE TITLE
Twenty Twenty: Desktop Expanded Menu is not right-aligned or full-height

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3604]
## Bug Description

Menus assigned to the “Desktop Expanded Menu” location do not open right-aligned or full-height in AMP.

## Expected Behaviour

The desktop expanded menu should open being positioned to the right (when `dir=ltr`) and take up the full viewport height.

## Steps to reproduce

0. Activate Twenty Twenty
1. Assign a menu to the “Desktop Expanded Menu” location.
2. View the AMP page.
3. Click the menu button.
4. See incorrect position compared to non-AMP page

## Screenshots

![image](https://user-images.githubusercontent.com/134745/67341801-63c42d80-f4e5-11e9-99d4-5b0c9723e6f3.png)

<img width="2020" alt="Screen Shot 2019-10-22 at 16 01 34" src="https://user-images.githubusercontent.com/134745/67341738-41321480-f4e5-11e9-86eb-a58b9b5c4567.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
