### ISSUE TITLE
Menu immediately closes on open after it was closed via ESC

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3616]
## Bug Description

From https://github.com/ampproject/amp-wp/pull/3606#issuecomment-545395077 :

In the "Desktop Expanded Menu", when you open the menu and close it via the Escape key, then when you try to subsequently open it again, it immediately closes right away.

## Expected Behaviour

The menu should stay open every time you open it after it was closed.

## Steps to reproduce

1. Have a menu set to the location "Desktop Expanded Menu".
2. Open the menu in the AMP page.
3. Close the menu by pressing the Escape key.
4. Try opening the menu again.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Maybe the fix here is to not use `toggleClass` to change the CSS class, and instead to rely on amp-bind to manage the `class`. 

For example, there are `lightboxOpen` and `lightboxClose` events: https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/#amp-lightbox

These events could be made to change some state, and then the `class` could be toggled based on the state.

**Comment by schlessera** [comment]
I already fixed this, but I'm unable to push to GitHub right now because
I'm sitting in a plane and GH is not res9lv8ng on their WiFi. I'll push the
current fix once I'm at the hotel...

**Comment by csossi** [comment]
Verified in QA
