### ISSUE TITLE
AMP lightbox missing 'role' and 'tabindex' attributes

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3617]
## Bug Description

From https://github.com/ampproject/amp-wp/pull/3606#issuecomment-545398633:

The AMP lightbox is required to have `role` and `tabindex` attributes when it has an `on` attribute.

As these are missing, it throws AMP validation errors.

## Expected Behaviour

The AMP lightbox should not produce validation errors.

## Steps to reproduce

1. Install and activate the TwentyTwenty theme.
2. Go to an AMP URL.
3. The AMP lightboxes that are used to simulate the TwentyTwenty modals throw validation errors.

## Screenshots

![image](https://user-images.githubusercontent.com/134745/67388236-22ffff00-f54d-11e9-85da-d7f52fda353a.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
