### ISSUE TITLE
Quick UX wins for the next release

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3623]
## Feature description

This is about some low hanging fruits that came up during UX reviews of the Stories editor. I figured it would be nice to address this for this release as it would result in some nice little improvements.

See #3611 for details and screenshots

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Do not display a featured image notice in the document sidebar  
  -> It should still be displayed in the pre-publish panel
* Opacity controls should be hidden when no color has been selected yet  
  -> changing the opacity has no effect otherwise
* When setting the background color for a page with a background media item, it should do so with reduced opacity. 
* Labelling of color panels should be more aligned between pages and text elements
* When editing a text element, the color panel should initially be open

## Implementation brief

* In `BackgroundColorSettings`, when adding a color for the first time and there is a media item, set `overlayOpacity` to `50`
* Change labels of color settings panels to make them more aligned
* Remove `initialOpen` prop of text element color panel
* Only display opacity controls when there are colors set
* Remove `withStoryFeaturedImageNotice` HOC and its usage

## QA testing instructions

1. Create a new story
1. **Verify:** No featured image warning should be shown on the right
1. Set a background image on the page
1. **Verify:** There should be no opacity control on the right side
1. Set a background color on the page
1. **Verify:** The background color should have opacity so that the image is still visible
1. **Verify:** There should now be a opacity control on the right side, and opacity can be changed at will
1. Add a text element
1. **Verify:** The color panel on the right should be open
1. **Verify:** There should be no opacity control on the right side
1. Set a background color on the text element
1. **Verify:** There should now be a opacity control on the right side, and opacity can be changed at will

## Demo

Remove annoying featured image notice in the document sidebar

![Screenshot 2019-10-24 at 23 08 53](https://user-images.githubusercontent.com/841956/67525564-480e8200-f6b3-11e9-91c7-55e2f4f874b3.png)

Hide opacity controls when no colors have been added yet

No color:

<img width="277" alt="Screenshot 2019-10-24 at 23 09 44" src="https://user-images.githubusercontent.com/841956/67525644-6e342200-f6b3-11e9-88ac-812990cd1c15.png">

Color:

<img width="278" alt="Screenshot 2019-10-24 at 23 09 53" src="https://user-images.githubusercontent.com/841956/67525650-712f1280-f6b3-11e9-8fde-bb6203f5abe9.png">

Page: when adding the first color, reduce opacity in order to not cover the background media

The image is still visible after adding a color:

<img width="1108" alt="Screenshot 2019-10-24 at 23 08 29" src="https://user-images.githubusercontent.com/841956/67525695-83a94c00-f6b3-11e9-8a00-f5067cbe59f3.png">

Initially open the color settings panel (currently it's collapsed by default)

<img width="1463" alt="Screenshot 2019-10-24 at 23 11 10" src="https://user-images.githubusercontent.com/841956/67525738-9885df80-f6b3-11e9-9726-1d7e02de9986.png">

Make color panels more aligned between pages and text elements

Page:

<img width="274" alt="Screenshot 2019-10-24 at 23 07 53" src="https://user-images.githubusercontent.com/841956/67525789-b2bfbd80-f6b3-11e9-92ae-ef6c1e581690.png">

Text block:

<img width="271" alt="Screenshot 2019-10-24 at 23 07 43" src="https://user-images.githubusercontent.com/841956/67525790-b2bfbd80-f6b3-11e9-9eac-712c48cd3750.png">

## Changelog entry

* Fixed a few UX inconsistencies in the editor

**Comment by spacedmonkey** [comment]
Does this even need a demo?

**Comment by swissspidy** [comment]
@spacedmonkey Good call - I think the screenshots from #3611 suffice.
