### ISSUE TITLE
Dragging block before pages doesn't work on RTL

### ISSUE THREAD

**Issue by spacedmonkey** [ampproject/amp-wp#3634]
## Bug Description

Dragging block before pages doesn't work for RTL users. 
See video to show issue.

https://youtu.be/gDw9DUKgswQ

## Expected Behaviour

When a user drags a block over another page, it should move to this page. 

## Additional context

 - WordPress version: 5.4
 - Plugin version: 1.4
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS: Ubuntu
 - Browser: Chrome
 - Device: PC

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Closing in favor of #3012 as it already contains this AC and testing instructions for it.
