### ISSUE TITLE
Brid player support like Youtube possible?

### ISSUE THREAD

**Issue by majestica** [ampproject/amp-wp#3638]
Hi, I apologize if I ask this question in the wrong place, but I hope for possible help.
Please tell me, is it possible to add support for the player brid tv?

inside the posts, journalists add a code in this format, but the video does not work on amp pages (

`<div id="Brid_72263785" class="brid" style="width:700; height:393;" > </div> <script type="text/javascript"> var _bp = _bp||[]; _bp.push({ "div": "Brid_72263785", "obj": {"id":"19331","width":"700","autoplay":false,"height":"393","video":"483405"} }); </script> <script type="text/javascript" async src="//services.brid.tv/player/build/brid.min.js"></script>`

as far as I can see, the code from the article for validity in amp and display should be in the format
In header add this code 
`<script type="text/javascript" src="https://cdn.ampproject.org/v0/amp-brid-player-0.1.js" async="async" custom-element="amp-brid-player"></script>`
and in content like this format
`<amp-brid-player data-partner="14896" autoplay data-player="19331" data-video="483405" layout="responsive" width="600" height="320"> </amp-brid-player>`

If you can tell me how can I filter the output in a valid format? Thanks

**Comment by majestica** [comment]
Weston, thank you, when i try use i got some 500 error, in my log 

```
2019/10/29 12:22:29 [error] 1111#1111: *96694 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function AMP_Brid_Player\wp_unique_id() in /var/www/wp-content/plugins/amp-brid-player/amp-brid-player.php:72
Stack trace:
#0 /var/www/wp-includes/shortcodes.php(319): AMP_Brid_Player\render_shortcode(Array, '', 'brid')
#1 [internal function]: do_shortcode_tag(Array)
#2 /var/www/wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(brid)(...', 'do_shortcode_ta...', '<p><strong>\xD0\x92 \xD0...')
#3 /var/www/wp-includes/class-wp-hook.php(286): do_shortcode('<p><strong>\xD0\x92 \xD0...')
#4 /var/www/wp-includes/plugin.php(203): WP_Hook->apply_filters('<p><strong>\xD0\x92 \xD0...', Array)
#5 /var/www/wp-includes/post-template.php(240): apply_filters('the_content', '<strong>\xD0\x92 \xD0\x9A\xD1\x80...')
```

**Comment by westonruter** [comment]
You should update. Otherwise, you can replace that function with something that does the same thing.
