### ISSUE TITLE
Context menu opening when right-clicking on Toolbar buttons

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3647]
## Bug Description

When doing right-click on the Toolbar (e.g. alignment button), the custom Context menu opens

## Expected Behaviour

Context menu should only open when right-clicking on the block.

## Steps to reproduce

1. Add a block (e.g. Text)
2. Right-click on any of the Toolbar buttons (e.g. alignment menu)
3. See the custom context menu opening.

## Screenshots
<img width="689" alt="Screenshot 2019-10-28 at 18 10 04" src="https://user-images.githubusercontent.com/3294597/67700432-388e8200-f9ae-11e9-961d-0ad1c62384ca.png">

## Additional context

 - WordPress version:
 - Plugin version: `develop`
 - Gutenberg plugin version (if applicable): `develop`
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* After right-clicking on a block, the context menu should open 
* After right-clicking on something other than a block, the context menu should not open
   * e.g. Toolbar

## Implementation brief

* Use [compareDocumentPosition](https://developer.mozilla.org/en-US/docs/Web/API/Node/compareDocumentPosition) to check if element is user right clicks on top toolbar. See the change [here](https://github.com/ampproject/amp-wp/compare/fix/right-click-toolbar?expand=1).

## QA testing instructions

1. Add a block (e.g. Text)
2. Right-click on any of the Toolbar buttons (e.g. alignment menu)
3. Confirm, browser context menu shows and not story editor context menu.

## Demo

![Screenshot from 2019-10-29 18-24-55](https://user-images.githubusercontent.com/237508/67797408-98059400-fa79-11e9-9f56-47f7b36f1f6e.png)

## Changelog entry

*

**Comment by spacedmonkey** [comment]
I was about to open this. Thanks @miina

**Comment by barklund** [comment]
The approach seems solid. Let's get this to implementation.

[The bit mask](https://github.com/ampproject/amp-wp/compare/fix/right-click-toolbar?expand=1#diff-5268aab3d96ebcdb97eecc63d2bcca96R51) should probably be tweaked a bit (pun intended) – for example:

```js
if ( toolBar.compareDocumentPosition( event.target ) & Node.DOCUMENT_POSITION_CONTAINED_BY ) {
```

**Comment by csossi** [comment]
Still getting the story menu when I right-click on these sub menus:
![image](https://user-images.githubusercontent.com/16945664/68600505-a3d95900-0470-11ea-958b-4ef9d394c588.png)
![image](https://user-images.githubusercontent.com/16945664/68600543-b358a200-0470-11ea-9e15-5b9ba7f14600.png)

**Comment by spacedmonkey** [comment]
@csossi These screenshots do no show the context menu for the block. They show the menu that is meant to appear when you click on the menu item in the top bar. What is the issue here?

**Comment by miina** [comment]
@csossi For clarity:
That's the context menu that should _NOT_ appear when doing right click on the toolbar:
<img width="268" alt="Screenshot 2019-11-12 at 19 58 06" src="https://user-images.githubusercontent.com/3294597/68701320-d2e1ee80-0586-11ea-8ff6-3b0d6b5e40d7.png">

The menus appearing on the screenshots you shared are the correct menus. Let me know if there's more information missing from being able to test properly, it wasn't explained in detail what is meant by the "context menu".

**Comment by csossi** [comment]
Verified in QA

**Comment by westonruter** [comment]
Closing because part of impending 1.4.1 release.
