### ISSUE TITLE
Language of AMP different than canonical

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amp-wp#365]
Here's an example:
- canonical (in filipino): http://www.datemypet.com/tl/how-to-attract-woman-of-your-dreams
- Points to this AMP (in english): http://www.datemypet.com/how-to-attract-woman-of-your-dreams/amp

If you remove the /tl/ from the canonical you get an english version that also points to the english AMP. If you add in the /tl/ to the AMP link, you do get the AMP in Filipino, and it points it's rel=canonical to the Filipino canonical so the only problem is that the filipino canonical points to the english AMP.

**Comment by westonruter** [comment]
Looks like this is no longer an issue. The AMP version is now pointing to https://www.datemypet.com/tl/how-to-attract-woman-of-your-dreams/amp/
