### ISSUE TITLE
Ambiguous validation error notice in the editor

### ISSUE THREAD

**Issue by pierlon** [ampproject/amp-wp#3673]
## Bug Description

While reviewing #3670, I realized a potential issue and I would like to bring it up for discussion.

The current validation error notice in the editor may be a bit ambiguous as to what the current validation states are for that page. Let's say there are 4 validation errors for a page:

![image](https://user-images.githubusercontent.com/134745/67903251-4e27b700-fb28-11e9-81ba-c284161789d4.png)

Upon editing that page you would receive the following error notice:

![image](https://user-images.githubusercontent.com/134745/67903285-6566a480-fb28-11e9-8c9d-447b79c421a8.png)

This can be interpreted as there being 3 validation issues which need to be attended to, but in actuality, if at least 1 is kept, then they have to be reviewed in order for it to be served as AMP.

A suggestion by @westonruter to resolve this ambiguity would be to have a error message such as:

> There are 2 new issues which need review. 2 of them involve markup not removed, which cause AMP to be disabled.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
**QA Passed**

The warning notice has been replaced with one that shows up in the AMP Validation sidebar. When there is any invalid markup being kept, the notice exclusively mentions that since it blocks AMP from being served:

> ![image](https://user-images.githubusercontent.com/134745/116010581-b26bef80-a5d4-11eb-8ab7-80c716fe07e5.png)

When there is no invalid markup being kept, but some removed markup that is removed, then it shows:

> ![image](https://user-images.githubusercontent.com/134745/116010836-5904c000-a5d6-11eb-9691-e1d52629ccde.png)
