### ISSUE TITLE
Flying Carpet misaligns on large screens until explicit width is added by amp runtime

### ISSUE THREAD

**Issue by paraleadogg** [ampproject/amp-wp#3680]
Hi Guys,

Spotted an issue with the Flying Carpet component that is actually visible on your own demo page here:

https://amp.dev/documentation/examples/components/amp-fx-flying-carpet/#flying-carpet-for-ads

If the viewport is over 1440px wide the ad in the flying carpet is aligned over to the right as there is no width set on the `.i-amphtml-fx-flying-carpet-container` fixed element 

The width is only set when you resize the screen

## Expected Behaviour

The width on the fixed container should be set on load so the ad within the flying carpet is center aligned in all viewports

## Steps to reproduce

1. Go to https://amp.dev/documentation/examples/components/amp-fx-flying-carpet/#flying-carpet-for-ads on a screen wider than 1440px wide
2. Observe the ad inside the flying carpet is aligned to the right-hand side (possibly off-screen)
3. Slowly resize your screen
4. Once your screen size drops below 1440px width the width attribute is added to the `<div class="i-amphtml-fx-flying-carpet-container"` by the amp runtime and the ad correctly jumps to the correct centered position

## Screenshots

![before](https://user-images.githubusercontent.com/10920375/68039290-bbbc1a80-fcc3-11e9-978d-c97938252fc1.JPG)

![after](https://user-images.githubusercontent.com/10920375/68039322-cd9dbd80-fcc3-11e9-8fb8-9a0dd4a5d233.JPG)

## Additional context

 - WordPress version: 5.2.4
 - Plugin version: 1.4.0
 - Browser: Firefox and Chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by chrissjhitc** [comment]
It looks to me like the component was designed with full width display in mind only. The fixed container (i-amphtml-fx-flying-carpet-container) inside the component has 100% width and no explicit left position, so having a column to the left will push it off the right of the screen. 

It seems when the AMP runtime considers it safe it will add an explicit width to the fixed container inside the component - this width is updated on window resize and always keeps the amp-ad in the correct position.

As the element having the width added to has fixed positioning it could arguably be considered safe to add that inline width at all times regardless of viewport position? It's not going to change the flow of the document.

![image](https://user-images.githubusercontent.com/17746536/68040500-5b7aa800-fcc6-11e9-8ac7-0a96c3ff6f16.png)

**Comment by westonruter** [comment]
@paraleadogg This issue doesn't seem to be specific to the AMP plugin. I think you should be opening this at https://github.com/ampproject/amphtml/
