### ISSUE TITLE
Problem with AMP to AMP navigation 

### ISSUE THREAD

**Issue by maciejmackowiak** [ampproject/amp-wp#3689]
Hello,

AMP to AMP is what we were waiting for, but there is a bug in it.
We are using Transitional mode for single posts only.

## Bug Description

1. On AMP site version we have this link to go to non-AMP version of the post and we would like to keep it:
```<a href="' . get_permalink() . '">View non-AMP version</a>```
2. As mentioned before we only support single posts but AMP 1.4 is also changing all the tags/categories/search etc links to AMP version and it will create a lot of unnecessary redirects.

## Expected Behaviour

1. Somehow force keeping non-AMP link maybe by adding some attribute like `data-force-non-amp` or `data-keep-non-amp` or something like that.

Simple solution would be to change this:
https://github.com/ampproject/amp-wp/blob/develop/includes/sanitizers/class-amp-link-sanitizer.php#L130
```
if ( ! $element->hasAttribute( 'href' ) ) {
```
into:
```
if ( ! $element->hasAttribute( 'href' ) || $element->hasAttribute('data-force-non-amp')) {
```
And then we could just use something like this:
```<a href="' . get_permalink() . '" data-force-non-amp>View non-AMP version</a>```

2. Account for AMP settings:
![obraz](https://user-images.githubusercontent.com/24996403/68210780-86bb0b00-ffd6-11e9-9b18-9dcc2f86ff6c.png)

`Homepage` and `Search` should be simple just matching home_url() and get_search_link() should be easy.
`Not Found (404)` I believe can be skipped.

I'm afraid it can be a little trickier for Archives, but in our case it can be solved by `data-force-non-amp` attribute, so when we are showing tags/categories/etc we could just simply add this attribute and problem solved.

## Additional context

 - WordPress version: 5.2.4
 - Plugin version: 1.4
 - AMP plugin template mode: Transitional
 - PHP version: 7.3
 - Browser: all
 - Device: all

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
> 1. Somehow force keeping non-AMP link maybe by adding some attribute like `data-force-non-amp` or `data-keep-non-amp` or something like that.

Something like that seems like a workable solution. The reason why the plugin is indiscriminately adding `?amp` to all URLs on the site is that it seems difficult or expensive to try to parse every URL encountered using the rewrite rules to determine kind of template it it will render.

Alternatively, AMP-to-AMP linking should perhaps be disabled by default on Transitional mode sites if the “serve all templates” as AMP checkbox is not checked.

**Comment by maciejmackowiak** [comment]
> Something like that seems like a workable solution. The reason why the plugin is indiscriminately adding ?amp to all URLs on the site is that it seems difficult or expensive to try to parse every URL encountered using the rewrite rules to determine kind of template it it will render.

I know that it would be expensive to parse every URL, that's why I've suggested the `attribute` approach as a workaround.

> Alternatively, AMP-to-AMP linking should perhaps be disabled by default on Transitional mode sites if the “serve all templates” as AMP checkbox is not checked.

This is also good idea but with implemented something simillar to my sugestion(also for forms).
So if theme author decide to turn on A2A without support of all templates it will be his job to account for all the cases where `?amp` should not be added.

**Comment by archon810** [comment]
Perhaps A2A should also be a user-facing setting?

**Comment by westonruter** [comment]
> I know that it would be expensive to parse every URL, that's why I've suggested the `attribute` approach as a workaround.

Yes, so I like your suggestion.

> Perhaps A2A should also be a user-facing setting?

I'd like to avoid this if possible. I'm trying to follow the WordPress philosophy of “[decisions, not options](https://wordpress.org/about/philosophy/#decisions)”. As much as possible we should make the best choice for the user, but still provide an extension mechanism for them to override. This is what the `amp_to_amp_linking_enabled` filter allows for. Then again, maybe the A2A checkbox could be conditionally shown only if the “serve all templates” checkbox is unchecked. But there still needs to be a way to selectively opt-out.

**Comment by westonruter** [comment]
What if we provide a single filter for an array of URLs which should be skipped for transformation? This filter would apply after the template is rendered, allowing for a site to gather up a list of opt-out URLs while the page is being generated and then supply that list in the applied filter callback at the point of post-processing.

**Comment by schlessera** [comment]
An array of URLs might not be feasible or hugely expensive depending on the site. How about an array of URL regexes instead? Alternatively, a filter that receives the current URL to be filtered and returns a boolean would be possible as well.

**Comment by schlessera** [comment]
If we use an attribute, I'd suggest using something that is more generic in nature, as it could be needed and/or used for other use cases than just the non-AMP link. Maybe some parts of the domain are hosted on a different platform without AMP? Maybe some custom logic is used within AMP scripts themselves to modify the URL?

So, something like `data-external-link` that defines the nature of the link without making an assumption about what the transformation is meant to do might be preferable?

**Comment by westonruter** [comment]
> An array of URLs might not be feasible or hugely expensive depending on the site. How about an array of URL regexes instead? Alternatively, a filter that receives the current URL to be filtered and returns a boolean would be possible as well.

I don't think it would be so bad. Here's what I had in mind, which doesn't involve regular expression matching…

Let's say AMP is disabled for a `foo` post type. If you wanted to prevent links to such posts from being linked to, then that could be done like so:

```php
$urls_to_exclude = [];

add_filter( 'post_link', static function ( $url, $post ) use ( &$urls_to_exclude ) {
    if ( 'foo' === get_post_type( $post ) ) {
        $urls_to_exclude[] = $url;
    }
    return $url;
}, 10, 2 );

add_filter( 'amp_to_amp_excluded_urls', static function ( $urls ) use ( $urls_to_exclude ) {
    return array_merge( $urls, $urls_to_exclude );
} );
```

Granted this would not work for links inside `post_content`, but it should account for other WP-generated links. In this way you can keep a tally the URLs that are appearing on the page, and then passing them to the post-processor.

> So, something like `data-external-link` that defines the nature of the link without making an assumption about what the transformation is meant to do might be preferable?

Note that external links (to other domains) already are excluded from getting `?amp` added to the URLs via the [`AMP_Link_Sanitizer::is_frontend_url ()`](https://github.com/ampproject/amp-wp/blob/c8704764afa82052f2ca30199a3c0fb882bfd833/includes/sanitizers/class-amp-link-sanitizer.php#L166-L201) method. So I don't know if something more generic would make sense. As an alternative to a data attribute would be a custom link relation. So something like this:

```diff
--- a/includes/sanitizers/class-amp-link-sanitizer.php
+++ b/includes/sanitizers/class-amp-link-sanitizer.php
@@ -132,10 +132,10 @@ class AMP_Link_Sanitizer extends AMP_Base_Sanitizer {
 			}
 
 			$href = $element->getAttribute( 'href' );
+			$rel  = $element->hasAttribute( 'rel' ) ? $element->getAttribute( 'rel' ) . ' ' : '';
 
-			if ( $this->is_frontend_url( $href ) && '#' !== substr( $href, 0, 1 ) ) {
+			if ( $this->is_frontend_url( $href ) && '#' !== substr( $href, 0, 1 ) && false === strpos( $rel, 'not-amphtml' ) ) {
 				// Always add the amphtml link relation when linking enabled.
-				$rel  = $element->hasAttribute( 'rel' ) ? $element->getAttribute( 'rel' ) . ' ' : '';
 				$rel .= 'amphtml';
 				$element->setAttribute( 'rel', $rel );
```

That `not-amphtml` relation could also be stripped from the `rel` attribute that gets serialized back in the response, since it doesn't have any meaning (the `amphtml` link relation isn't really used now either, as far as I know, but at least it has been described in https://github.com/ampproject/amphtml/issues/12496).

**Comment by westonruter** [comment]
Another use case that came to mind for selectively disabling AMP-to-AMP linking is being able to link to the non-AMP version of the page: https://wordpress.org/support/topic/i-want-to-create-a-switch-between-amp-and-no-amp-in-the-article/

This revealed a bug with how AMP-to-AMP linking works (or does not work) with the Exit Reader Mode link added in https://github.com/ampproject/amp-wp/pull/2034

If you have a plugin which is doing:

```php
add_filter( 'amp_to_amp_linking_enabled', '__return_true' );
```

Then the Edit Reader Mode link erroneously links back the AMP page! 😊 

![image](https://user-images.githubusercontent.com/134745/70936144-9591d600-1ff6-11ea-98ee-db052b393afe.png)

**Comment by archon810** [comment]
@westonruter Confused by your last comment. Isn't it exactly what this ticket is for already? From the original description and our previous discussion with @maciejmackowiak:

> On AMP site version we have this link to go to non-AMP version of the post and we would like to keep it:
> <a href="' . get_permalink() . '">View non-AMP version</a>

**Comment by westonruter** [comment]
Not exactly. You reported the issue for Transitional mode where we don't provide an “Exit” link. The issue is more problematic than you reported because when AMP-to-AMP linking is enabled in Reader mode, the plugin-supported “Exit Reader Mode” link does not work at all.

**Comment by kienstra** [comment]
## Discussing Implementation Brief

### 1. Disabled post types

This could address the problem of AMP-to-AMP navigation in paired mode to a post type that has AMP disabled, like if pages are disabled. It doesn't address the problem of the Reader mode 'exit link,' or allowing users to add an HTML attribute to a link to opt-out of AMP-to-AMP links.

<img width="700" alt="r-pages-disabled" src="https://user-images.githubusercontent.com/4063887/72553427-6d4c0000-385e-11ea-879e-45cbf62b5d78.png">

Here's an approach to implementing https://github.com/ampproject/amp-wp/issues/3689#issuecomment-561950404:

```diff
diff --git a/includes/class-amp-theme-support.php b/includes/class-amp-theme-support.php
index b9fe763e3..914438d93 100644
--- a/includes/class-amp-theme-support.php
+++ b/includes/class-amp-theme-support.php
@@ -113,6 +113,15 @@ class AMP_Theme_Support {
         */
        protected static $embed_handlers = [];
+       protected static $urls_to_exclude_from_amp_to_amp = [];
+
        /**
         * Template types.
         *
@@ -190,6 +199,8 @@ class AMP_Theme_Support {
                        }
 
                        add_action( 'widgets_init', [ __CLASS__, 'register_widgets' ] );
+                       add_filter( 'post_link', [ __CLASS__, 'maybe_add_excluded_url' ], 10, 2 );
+                       add_filter( 'amp_to_amp_excluded_urls', [ __CLASS__, 'get_excluded_urls' ] );
 
                        /*
                         * Note that wp action is use instead of template_redirect because some themes/plugins output
@@ -456,6 +467,38 @@ class AMP_Theme_Support {
                }
        }
 
+       public static function maybe_add_excluded_url( $url, $post ) {
+               if ( ! post_supports_amp( $post ) ) {
+                       self::$urls_to_exclude_from_amp_to_amp[] = $url;
+               }
+
+               return $url;
+       }
+
+       public static function get_excluded_urls( $urls ) {
+               return array_merge( $urls, self::$urls_to_exclude_from_amp_to_amp );
+       }
+
        /**
         * Ensure that the current AMP location is correct
```

Then, the excluded URLs could be passed to [AMP_Link_Sanitizer](https://github.com/ampproject/amp-wp/blob/b765c92de2f06288e0857e0d98f39ced27faf3d3/includes/sanitizers/class-amp-link-sanitizer.php) with `apply_filters( 'amp_to_amp_excluded_urls' )`, or maybe something like `AMP_Theme_Support::get_excluded_amp_to_amp_urls()`. 

Those URLs would then link to non-AMP URLs.

**Comment by kienstra** [comment]
## Discussing Implementation Brief

### 2. An HTML attribute to add to an `<a>` to opt-out of AMP-to-AMP links.

Weston's [proposed](https://github.com/ampproject/amp-wp/issues/3689#issuecomment-561950404) `<a rel="not-amphtml">` looks good, along with the snippet for snippet for removing it in the AMP document.

**Comment by kienstra** [comment]
## Discussing Implementation Brief

### 3. Reader mode 'exit' link
As [Weston mentioned](https://github.com/ampproject/amp-wp/issues/3689#issuecomment-566205205), `add_filter( 'amp_to_amp_linking_enabled', '__return_true' );` causes the 'Exit Reader Mode' link to go back to the AMP URL.

The 'Exit Reader Mode' link in the Reader Mode template could add the `[rel="not-amphtml"]` attribute [mentioned above](https://github.com/ampproject/amp-wp/issues/3689#issuecomment-575294836).
https://github.com/ampproject/amp-wp/blob/b765c92de2f06288e0857e0d98f39ced27faf3d3/templates/header-bar.php#L37

Other themes that have a Reader mode template can also include that attribute in 'exit' links.

In the [AMP_Link_Sanitizer](https://github.com/ampproject/amp-wp/blob/b765c92de2f06288e0857e0d98f39ced27faf3d3/includes/sanitizers/class-amp-link-sanitizer.php), that attribute could override the value of `apply_filters( 'amp_to_amp_linking_enabled' )` that was passed to it. 

So any link with `[rel="not-amphtml"]` would go to a non-AMP URL, no matter the value of `apply_filters( 'amp_to_amp_linking_enabled' )`.

**Comment by kienstra** [comment]
Hi @westonruter,
Good to see you earlier. What do you think about the 3 points above?

Thanks!

/cc @amedina

**Comment by westonruter** [comment]
@kienstra I like your use of `post_supports_amp()` as opposed to just checking the post type.

It would be possible to also extend the URL collection to non-post URLs as well. For example, if the sidebar has a Categories widget, each category link URL will be obtained via `get_category_link()` which in turn calls `get_term_link()` which in turn returns a URL with `term_link` filters applied. So the `term_link` filter could also be used to collect URLs. In that case, `post_supports_amp()` would not apply naturally, and there would need to be a check if the given taxonomy term is among `AMP_Theme_Support::get_supportable_templates()`. This method isn't currently optimized for this use case, however. The way it is currently used involves passing a `WP_Query` to `AMP_Theme_Support::get_template_availability()`. We would _not_ want to construct a `WP_Query` for every entity on the page! Perhaps it would be possible to pass a queried object, like a `WP_Term` or `WP_User` into that method which would end up checking the entries for supportable templates. Since we can't call the `callback` in that context, perhaps the object should be supplied as well:

```diff
diff --git a/includes/class-amp-theme-support.php b/includes/class-amp-theme-support.php
index b9fe763e3..5e1a12a38 100644
--- a/includes/class-amp-theme-support.php
+++ b/includes/class-amp-theme-support.php
@@ -963,12 +963,14 @@ class AMP_Theme_Support {
 			$templates['is_category'] = [
 				'label'  => get_taxonomy( 'category' )->labels->name,
 				'parent' => 'is_archive',
+				'object' => get_taxonomy( 'category' ),
 			];
 		}
 		if ( taxonomy_exists( 'post_tag' ) ) {
 			$templates['is_tag'] = [
 				'label'  => get_taxonomy( 'post_tag' )->labels->name,
 				'parent' => 'is_archive',
+				'object' => get_taxonomy( 'post_tag' ),
 			];
 		}
 
@@ -983,6 +985,7 @@ class AMP_Theme_Support {
 				'callback' => static function ( WP_Query $query ) use ( $taxonomy ) {
 					return $query->is_tax( $taxonomy->name );
 				},
+				'object'   => $taxonomy,
 			];
 		}
 
@@ -997,6 +1000,7 @@ class AMP_Theme_Support {
 				'callback' => static function ( WP_Query $query ) use ( $post_type ) {
 					return $query->is_post_type_archive( $post_type->name );
 				},
+				'object'   => $post_type,
 			];
 		}
```

That could then allow for `\AMP_Theme_Support::get_template_availability()` to check against the queried object rather than the query for matches:

```diff
--- a/includes/class-amp-theme-support.php
+++ b/includes/class-amp-theme-support.php
@@ -696,6 +696,14 @@ class AMP_Theme_Support {
 		$matching_templates    = [];
 		$supportable_templates = self::get_supportable_templates();
 		foreach ( $supportable_templates as $id => $supportable_template ) {
+			$is_match = false;
+			if ( ! ( $query instanceof WP_Query ) && isset( $supportable_template['object'] ) ) {
+				if ( $query instanceof WP_Term && $supportable_template['object'] instanceof WP_Taxonomy ) {
+					$is_match = ( $supportable_template['object']->name === $query->taxonomy );
+				} elseif ( $query instanceof WP_Post_Type && $supportable_template['object'] instanceof WP_Post_Type ) {
+					$is_match = ( $query->name === $supportable_template['object']->name );
+				}
+			} elseif ( $query instanceof WP_Query) {
 				if ( empty( $supportable_template['callback'] ) ) {
 					$callback = $id;
 				} else {
@@ -710,7 +718,7 @@ class AMP_Theme_Support {
 				} else {
 					/* translators: %s: the supportable template ID. */
 					_doing_it_wrong( __FUNCTION__, esc_html( sprintf( __( 'Supportable template "%s" does not have a callable callback.', 'amp' ), $id ) ), '1.0' );
-				$is_match = false;
+				}
 			}
 
 			if ( $is_match ) {
```

_However_, this is quickly getting complicated. Also, this will not account for every link type. Also, this will not handle links that are inside post content.

----

So I think that we should start with a limited scope, and that is to only implement support for preventing AMP-to-AMP linking for links that have the designated link relation or data attribute. So let's only focus on https://github.com/ampproject/amp-wp/issues/3689#issuecomment-575294836 and https://github.com/ampproject/amp-wp/issues/3689#issuecomment-575302794. We could still allow for the `AMP_Link_Sanitizer` to take an array of URLs to omit from being AMPified, however the actual list of URLs should not be populated by default. That would be left up to developers to implement.

@archon810 @maciejmackowiak How does this sound? Would you want to have the ability to filter the URLs that should not be AMPified? Or is ability to flag such non-AMP links with a link relation or data attribute sufficient?

**Comment by kienstra** [comment]
Hi @westonruter,
Thanks, good ideas.

>So let's only focus on #3689 (comment) and #3689 (comment). We could still allow for the AMP_Link_Sanitizer to take an array of URLs to omit from being AMPified, however the actual list of URLs should not be populated by default. That would be left up to developers to implement.

That sounds good, it'll still let people opt-out of AMP-to-AMP links.

**Comment by kienstra** [comment]
**Steps To Test**

1. Ensure Paired mode is selected
2. Create a new post
3. Add a Custom HTML block
4. Add this to it: `<a href="https://story-test-wordpress-amp.pantheonsite.io/2019/05/02/post-with-story/" rel="noamphtml">To non-AMP</a>`
5. Save, and go to the front-end of the AMP URL
6. Expected: the markup of the URL is: `<a href="https://story-test-wordpress-amp.pantheonsite.io/2019/05/02/post-with-story/">To non-AMP</a>`, it doesn't have `?amp` or `rel="noamphtml"`

**Comment by csossi** [comment]
Verified in QA

**Comment by kienstra** [comment]
Nice! Thanks, Claudio!

**Comment by westonruter** [comment]
See #4913 for a proposal to add a filter for fine-grained AMP-to-AMP linking exclusions.
