### ISSUE TITLE
Include AMP Carousel v2

### ISSUE THREAD

**Issue by oftara** [ampproject/amp-wp#3700]
## Feature description

AMP Carousel v2 is available for several months, but the plugin loads v1.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Please see https://github.com/ampproject/amp-wp/pull/3115

If you'd like to use v0.2 today, you can do so via:

```php
add_action(
	'wp_default_scripts',
	function( \WP_Scripts $scripts ) {
		if ( isset( $scripts->registered['amp-carousel'] ) ) {
			$scripts->registered['amp-carousel']->src = 'https://cdn.ampproject.org/v0/amp-carousel-0.2.js';
		}
	},
	11
);
```
