### ISSUE TITLE
images are too wide for screen - I have to re-fix after every update

### ISSUE THREAD

**Issue by mark34** [ampproject/amp-wp#3724]
## Bug Description

Using Newsmag theme the in-post images are too wide for mobile phones & cause scrolling left & right to accommodate them.
Looking at the html source the amp-img width style is 'width' and should be 'max-width'.

## Expected Behaviour

Images should be neatly fitting into the same width as the text, and not force the browser to  scroll left & right to see the full, too-large image. 

## Steps to reproduce

See a page containing the problem code - this uses the amp plugin as-is, without my fix in place : 
http://dev.proboxing-fans.com/dubois-on-lewis-and-joshuas-heavyweight-spat_082719/amp/

See the same page on the production server which contains my fix : 
https://www.proboxing-fans.com/dubois-on-lewis-and-joshuas-heavyweight-spat_082719/amp/

## Screenshots

See video showing exactly what's happening & how I fix it for now.

Also - just navigate to the 2 urls using a mobile phone, or emulate a mobile phone in a browser using the dev tools.

## Additional context

 - WordPress version: 5.2.4
 - Plugin version: 1.4.0
 - Gutenberg plugin version (if applicable):n/a
 - AMP plugin template mode: Reader
 - PHP version:7.0

For some reason, before plugin v0.6 max-width would appear in the source, but from v0.6 is seems to be width, which is causing the problem.

Here's a link to the fix I put in place, but of course there are different ways to do this:

[https://www.dropbox.com/s/uy1xomncq6y58h7/screen%20recording%202019-11-13%20at%2011.50.20.mov?dl=0](url)

*** FIX ***
UPDATE FILE:  [plugins]/amp/includes/amp-post-template-functions.php: 
```php
// ...
function amp_post_template_add_styles( $amp_template ) {
	$stylesheets = $amp_template->get( 'post_amp_stylesheets' );
	if ( ! empty( $stylesheets ) ) {
		echo '/* Inline stylesheets */' . PHP_EOL; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped

// update next line
		echo fix_style_width_error(implode( '', $stylesheets )); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	}

	$styles = $amp_template->get( 'post_amp_styles' );
	if ( ! empty( $styles ) ) {
		echo '/* Inline styles */' . PHP_EOL; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		foreach ( $styles as $selector => $declarations ) {
			$declarations = implode( ';', $declarations ) . ';';
// update next line
			print fix_style_width_error( sprintf( '%1$s{%2$s}', $selector, $declarations ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		}
	}
	print "\nh1.title { font-family: 'Open Sans', arial, sans-serif; font-weight:400; color:#222; word-wrap: break-word; }\n";
}

// add this function

/**
 * in v0.6 they used max-width which worked great. After that it was width, which is breaking our amp pages
 * @param $str
 */
function fix_style_width_error($str) {

    return preg_replace('/(^|[^-])(width)/', '$1max-width', $str);
}

/// ...
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
Hi @mark34,

The main problem here comes from WordPress itself, not from the conversion to AMP.

If you look at your non-AMP page, you'll see that the `<figure>` surronuding the image has an inline attribute `width`. This is what the AMP plugin transforms into the CSS style that seems broken.

![Image 2019-11-13 at 6 05 00 PM](https://user-images.githubusercontent.com/83631/68786549-3ed45d80-0640-11ea-85f0-99b90b6ed7a0.png)

WordPress tried to change this `width` into `max-width` with 4.9, but it was reverted as it broke many existing theme, unfortunately: https://make.wordpress.org/core/2018/03/19/max-width-captions-reverted-in-4-9-5/

There are filters you can use to adapt the output from WordPress to make this work as expected. One of them is to filter the shortcode output, as shown in the above post. Another one can be found here: https://stackoverflow.com/a/47662620

So this is not an actual bug with the AMP plugin, it does what it is supposed to. However, we should consider whether we might want to automatically correct this, given its widespread use. @westonruter Thoughts?

**Comment by westonruter** [comment]
@mark34 Have you overridden the `style.php` template for the Reader mode template in your theme? We fixed this issue in https://github.com/ampproject/amp-wp/pull/1728 but on your dev AMP page, I do not find:

https://github.com/ampproject/amp-wp/blob/90c21b1dd531e9db13090aa046cfe13ef536322d/templates/style.php#L263-L265

I tried copying your content onto my test site with Reader mode enabled, and it rendered properly but because of this style:

![image](https://user-images.githubusercontent.com/134745/68794746-74f3ec00-0604-11ea-814d-9a80eeb813ed.png)

So I believe the fix is just to make sure your forked `style.php` incorporates any changes from https://github.com/ampproject/amp-wp/blob/develop/templates/style.php which were 

You should never have to patch the plugin. 

Also, as opposed to overriding the `style.php` entirely, you can eliminate having to maintain your fork by adding custom styles at the `amp_post_template_css` action:

https://github.com/ampproject/amp-wp/blob/90c21b1dd531e9db13090aa046cfe13ef536322d/templates/html-start.php#L27-L30
