### ISSUE TITLE
Uncaught DOMException adjusting attributes

### ISSUE THREAD

**Issue by tomjn** [ampproject/amp-wp#3753]
## Bug Description

```
PHP Fatal error:  Uncaught DOMException: Not Found Error in /srv/www/..../plugins/amp/includes/sanitizers/class-amp-base-sanitizer.php:477
```

Specifically this in `remove_invalid_attribute`

```
		if ( $should_remove ) {
			$element->removeAttributeNode( $node );
```

```
[11-Nov-2019 20:12:05 UTC] PHP Fatal error:  Uncaught DOMException: Not Found Error in /srv/www/.../plugins/amp/includes/sanitizers/class-amp-base-sanitizer.php:477
Stack trace:
#0 /srv/www/.../plugins/amp/includes/sanitizers/class-amp-base-sanitizer.php(477): DOMElement->removeAttributeNode(Object(DOMAttr))
#1 /srv/www/.../plugins/amp/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php(585): AMP_Base_Sanitizer->remove_invalid_attribute(Object(DOMElement), Object(DOMAttr), Array)
#2 /srv/www/.../plugins/amp/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php(302): AMP_Tag_And_Attribute_Sanitizer->process_node(Object(DOMElement))
#3 /srv/www/.../plugins/amp/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php(287): AMP_Tag_And_Attribute_Sanitizer->san in /srv/www/.../plugins/amp/includes/sanitizers/class-amp-base-sanitizer.php on line 477
```

## Steps to reproduce

We're unsure of the content/URL that's generating this at the moment

## Additional context

 - WordPress version: 5.2.3
 - Plugin version: 1.3.0
 - Gutenberg plugin version (if applicable): n/a
 - AMP plugin template mode:
 - PHP version: 7.2.24-1+ubuntu16.04.1+deb.sury.org+1
 - OS: Ubuntu
 - Browser: unknown
 - Device: unknown

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@tomjn This should have been fixed in 1.4.1 via https://github.com/ampproject/amp-wp/pull/3682

Please update and confirm.
