### ISSUE TITLE
Refactor AMP_Theme_Support::ensure_required_markup() into sanitizers

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3763]
## Feature description

The code found in `AMP_Theme_Support::ensure_required_markup()` does a lot, and does it after the sanitizers have run:

https://github.com/ampproject/amp-wp/blob/3b70f6d8e20593920b7b711455e491960b1d0418/includes/class-amp-theme-support.php#L1526-L1542

This code should be refactored into separated sanitizers so that all of that work is part of what the sanitizers do.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `AMP_Theme_Support::ensure_required_markup()` can be removed as it is not needed anymore.

## Implementation brief

- [ ] Create new `AMP_Meta_Sanitizer` to deal with meta tags => WIP PR: https://github.com/ampproject/amp-wp/pull/3758
- [ ] Move script handling into `AMP_Script_Sanitizer`
- [ ] Move rel links and preconnect/preload/prefetch handling to `AMP_Link_Sanitizer`
- [ ] Create `AMP_Title_Sanitizer` to deal with title tags (or include in `AMP_Meta_Sanitizer`?)
- [ ] Move script re-ordering/deduplication and render-delaying logic to `AMP_Script_Sanitizer`
- [ ] Move AMP runtime logic to `AMP_Script_Sanitizer`
- [ ] Move custom style reordering logic in `AMP_Style_Sanitizer`
- [ ] Move the AMP boilerplate logic into `AMP_Style_Sanitizer`

For the above, we might face an issue where we cannot do the ordering at the point in time where the particular sanitizer is run. In case we hit such an issue, we should still put the _generation_ of said elements into the corresponding sanitizers, and then add a final `AMP_Head_Sanitizer` to go over the order of things in one go.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
These sanitizers should be forcibly included among the list of sanitizers, in the same way that we currently force `AMP_Style_Sanitizer` and `AMP_Tag_And_Attribute_Sanitizer` to always be included and always run at the end.

**Comment by westonruter** [comment]
As we discussed previously, the sanitizers that come out of this should align with the Transformers as outlined in the [AMP SSR Toolkit Implementation Guide](https://docs.google.com/document/d/1lZl7UJ5eUrhwTmfbOZ7g-HFIgMnTeqGwfUxE98kALzU/edit).

**Comment by westonruter** [comment]
Much of this work has been accomplished in the Optimizer and will be part of upcoming modularization work.

**Comment by westonruter** [comment]
A good bit of the code was moved in the amp-toolbox-php. More could be refactored, but it's not a priority.
