### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3764]
## Feature description

This ticket was taken from a row in this [spreadsheet](https://docs.google.com/spreadsheets/d/1nqJ-iOypTziWFjWBIBoJUc0LHW3gTeUnLkbjVH_eW4g/edit#gid=0). This ticket can be used to track research and work related to porting this existing feature from the "old" editor to the "new" editor. 

Animations:
- Setting in the right sidebar responsible for assigning animations to a block and previewing animations.

UX Required: Yes
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing animations are ported to the new stories editor
* Need to adjust the preview etc. with the new block structure in the editor.
* The animations are integrated into the new [design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Experimental?node-id=0%3A1)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by dvoytenko** [comment]
Dedupping to ampproject/web-stories-wp#80.
