### ISSUE TITLE
Block Inserter

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3766]
## Feature description

This ticket was taken from a row in this [spreadsheet](https://docs.google.com/spreadsheets/d/1nqJ-iOypTziWFjWBIBoJUc0LHW3gTeUnLkbjVH_eW4g/edit#gid=0). This ticket can be used to track research and work related to porting this existing feature from the "old" editor to the "new" editor. 

Block Inserter:
- The "+" icon in the left Toolbar which allows searching and inserting blocks.

UX Required: Yes
- Team is still investigating whether any of the Gutenberg blocks are useful for visual stories

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing block inserter is ported to the new stories editor
* The block inserter is integrated into the new [design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Experimental?node-id=0%3A1)
## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by miina** [comment]
@pbakaus This issue was created based on the assumption that we'd be building the tool reusing Gutenberg blocks. Since we're not doing that anymore and have our own custom elements implementation in the plan and partially done, then probably this issue could be closed?

**Comment by pbakaus** [comment]
yep, let's close for now. We can revisit in the future whether Gutenblock import makes sense.
