### ISSUE TITLE
Block Component

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3767]
## Feature description

This ticket was taken from a row in this [spreadsheet](https://docs.google.com/spreadsheets/d/1nqJ-iOypTziWFjWBIBoJUc0LHW3gTeUnLkbjVH_eW4g/edit#gid=0). This ticket can be used to track research and work related to porting this existing feature from the "old" editor to the "new" editor. 

Font Picker:
- Block is not really a component per se, registering a block is really creating a set of directives based on what a component is put together.
- The block “module” includes everything related to editing and rendering a block, including settings in the sidebar, block drag handle, settings, alignment options, etc.

UX Required: ?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing block component is ported to the new stories editor
* The block component is integrated into the new [design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Experimental?node-id=0%3A1)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by miina** [comment]
It seems that this ticket could be closed: we won't be porting over blocks from Gutenberg, and the features for elements are tracked in separate issues per feature (e.g. alignment, sidebar, etc.)

cc @pbakaus
