### ISSUE TITLE
Page Inserter 

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3768]
## Feature description

This ticket was taken from a row in this [spreadsheet](https://docs.google.com/spreadsheets/d/1nqJ-iOypTziWFjWBIBoJUc0LHW3gTeUnLkbjVH_eW4g/edit#gid=0). This ticket can be used to track research and work related to porting this existing feature from the "old" editor to the "new" editor. 

Page Inserter:
- Inserts a new page when clicked on, without having to search for a block.

UX Required: Yes

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing page inserter is ported to the new stories editor
* The page inserter is integrated into the new [design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Experimental?node-id=0%3A1)
## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by miina** [comment]
Looks like this issue can be closed, we're not bringing the old inserter over. It should already be covered by ampproject/web-stories-wp#60 

cc @pbakaus

**Comment by pbakaus** [comment]
thanks, makes sense!
