### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3770]
## Feature description

This ticket was taken from a row in this [spreadsheet](https://docs.google.com/spreadsheets/d/1nqJ-iOypTziWFjWBIBoJUc0LHW3gTeUnLkbjVH_eW4g/edit#gid=0). This ticket can be used to track research and work related to porting this existing feature from the "old" editor to the "new" editor. 

Buttons:
- Various buttons / links used for user interactions.

UX Required: Yes

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing Buttons are ported to the new stories editor
* The Buttons are integrated into the new [design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Experimental?node-id=0%3A1)

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by spacedmonkey** [comment]
Does the new editor have buttons? cc @jauyong

**Comment by jauyong** [comment]
@spacedmonkey unless I'm misunderstanding the original intent of the buttons feature from that old spreadsheet, I think any buttons will just be built in as part of the other tickets and this may not be necessary? Does that sound reasonable to you? If so, I can close this ticket and reopen if we ever need it...

**Comment by miina** [comment]
Doesn't look like we will need this as a separate issue, buttons will probably be implemented as part of another issue.

> If so, I can close this ticket and reopen if we ever need it...

Makes sense, closing.
