### ISSUE TITLE
Moveable Library for Resizing Rotating and Dragging

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3783]
## Feature description

This ticket was taken from rows in this [spreadsheet](https://docs.google.com/spreadsheets/d/1nqJ-iOypTziWFjWBIBoJUc0LHW3gTeUnLkbjVH_eW4g/edit#gid=0). This ticket can be used to track research and work related to using the Moveable library. 

Resizing:
Handles resizing a block from each side and corner.

Rotation:
Handles rotating a block

Block Mover/Dragging:
Handles dragging a block

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Research https://daybrush.com/moveable/ to see if it can handle the resizing of blocks.
* Research https://daybrush.com/moveable/ to see if it can handle the rotation of blocks.
* Research https://daybrush.com/moveable/ to see if it can handle the moving of blocks.

AC: There are documented findings with a recommendation if to use Moveable library or something else.
AC: The chosen library has been implemented to provide basic resizing, rotation and dragging.

## Implementation brief

The conclusion from looking into [Moveable](https://www.npmjs.com/package/react-moveable) is that it can be used for Resizing, Dragging, and Rotation.

* See [this commit](https://github.com/ampproject/amp-wp/pull/3798/commits/ae18f64999f5fbdce670d49d87c67011ab6e8488) for a partially working demo of Moveable within our code and attaching it to an element. Note that this code does not update the properties of the moved/resized/rotated block yet, however, it shows that we can use Moveable.

**Overview**
We will use Moveable and implement basic dragging/rotating/resizing. For the initial version, we will follow a similar logic as Google Slides has: an outline of the element is being dragged/resized/rotated instead of the element directly. Once the action has stopped, the properties of the element are updated, too. Using just the outline has the benefit of simplicity -- we won't have to worry about updating the element while it's being resized (e.g. font sizes, image ratio, etc.) which was causing a lot of issues in the previous iteration of the Story editor. This can be improved in a future iteration.
## QA testing instructions

* 

## Demo

* 
![demo-moveable](https://user-images.githubusercontent.com/3294597/69666806-2840f400-108d-11ea-8084-0c7a04f6afd1.gif)

## Changelog entry

*

**Comment by miina** [comment]
@pbakaus Tagging you here for visibility since you asked about it yesterday. In the description, there's a short (very broad) overview of the approach and also there's a partly working PR which basically mainly just proves that we can use Moveable within the app.

I moved it to Execution to now actually start implementing the first working solution. Let me know if you have any concerns.

**Comment by dvoytenko** [comment]
I think we can try to manipulate the DOM nodes directly. But outline is ok as well. The only question I have is w.r.t. whether we will use the Moveable library for media/focal point alignment as well. To align focal point we really have to be able to see the image as it's being moved per https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Experimental?node-id=6%3A421. But we could instead use a different method for that - the needs are much simpler there. There's otherwise some overlap there with grid lines/crosshairs and such.

**Comment by miina** [comment]
There's also the focal point picker in Gutenberg: https://developer.wordpress.org/block-editor/components/focal-point-picker/

If not Moveable then perhaps that could be partly usable or good for inspiration at least. Note: I haven't looked into `FocalPointPicker` in detail at all, however, we did use it previously for the background image. That has a bit different UI though:
<img width="291" alt="Screenshot 2019-11-22 at 20 49 28" src="https://user-images.githubusercontent.com/3294597/69455870-a178d800-0d69-11ea-86f7-3dd7e1e9717e.png">

**Comment by dvoytenko** [comment]
@miina This part looks to have changed quite a bit in the new design.

**Comment by miina** [comment]
Closing this as it got merged as a very basic implementation. Two follow-up issues have been created for improvements: ampproject/web-stories-wp#69 and ampproject/web-stories-wp#70 .

Added a demo under the "Demo" section of the description and moving this to Approval. cc @pbakaus

**Comment by pbakaus** [comment]
this is awesome, great work! WIll talk to Sam, but if resizing the actual element during drag is an option, I would greatly prefer that. Is that a possibility as follow up?

**Comment by miina** [comment]
> but if resizing the actual element during drag is an option, I would greatly prefer that. Is that a possibility as follow up?

Yes, definitely at some point! Resizing the actual element is certainly my preference as well from the UX point of view. It just involves adjusting the content while resizing as well (text flow, size changes, etc.) and as a starting point using an outline is a simpler solution.

**Comment by dvoytenko** [comment]
> > but if resizing the actual element during drag is an option, I would greatly prefer that. Is that a possibility as follow up?
> 
> Yes, definitely at some point! Resizing the actual element is certainly my preference as well from the UX point of view. It just involves adjusting the content while resizing as well (text flow, size changes, etc.) and as a starting point using an outline is a simpler solution.

One point to bring up from UX point of view if we support "Esc" key during moving manipulation to reset back to before moving has started, then the outlines work arguably a little bit better.
