### ISSUE TITLE
Cannot validate. Getting timeout.

### ISSUE THREAD

**Issue by cvaclav** [ampproject/amp-wp#3795]
Hi,

I'm getting in trouble with validating AMP page.

It always ends up with this error message: `Failed to fetch URL(s) to validate. This may be due to a request timeout. Please check your server's PHP error logs; to do this you may need to enable WP_DEBUG_LOG.`

There are no errors in log and access logs says it's been `302` redirected.

I tried to increase timeout for AMP via `http_request_args` filter in `functions.php` but it didn't help. If I set it to `60` then the timeout is returned after minute. If I set it to `120` then I also don't help and returs timeout after 2 minutes and etc.

PHP `max_execution_time` is `60`.

Any ideas?

Thanks for help.

**Comment by westonruter** [comment]
@cvaclav Hi. Please check Site Health in the WordPress admin under Tools to confirm that your site is able to perform loopback requests.

**Comment by cvaclav** [comment]
@westonruter Thanks. Loopback requests test failed. Do you have any tips what are the most common causes?

<img width="620" alt="wp-error" src="https://user-images.githubusercontent.com/5932928/69278349-6bf5b280-0be2-11ea-8838-056da45f4eef.PNG">

**Comment by westonruter** [comment]
Note that we'll be proactively warning about this in the error message soon: #3793.

Someone reported recently that Limit Login Attempts breaks loopback requests. What plugins do you have active? Anything special about your hosting stack? 

I suggest deactivating plugins one-by-one and re-checking Site Health to narrow it down.

**Comment by cvaclav** [comment]
Nice, these error messages will definitely help.

Deactivating plugins was first thing I tried. I deactivated them all and no changes, test still fails.

I don't think it's related to hosting, because loopback requests test fails on Netio VPS and Siteground hosting same way.

**Comment by westonruter** [comment]
But the loopback requests fail even when the AMP plugin is deactivated, right?

**Comment by cvaclav** [comment]
@westonruter Yes exactly.

**Comment by westonruter** [comment]
Ok, so I suggest contacting your host for support because this isn't an issue with the AMP plugin.

**Comment by cvaclav** [comment]
@westonruter Thanks for helping me find where the issue probably is. I found out, that loopback requests test fails only with our custom template. It passes with default one. Do you still think there might be a problem with host or do you have any other suggestions? Thanks.

**Comment by westonruter** [comment]
By custom template do you mean your theme? If so, then you should contact the theme author to fix the issue.
