### ISSUE TITLE
[Research] In-place editing

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3800]
## Feature description

A conflict of needs occur, when you both want the ability to drag a text element as well as select text for editing. The two interactions are indistinguishable on the surface.

The previous editor used double click to enable object editing, and then you had to click either the border or deselect/reselect to be able to drag the element around on the canvas.

Another approach could be the one used by Google Slides and similar tools. In order to drag an object, you have to click in certain places - if you just click/drag in the center of a text element, you select the text / try to insert text. We can also even have a physical anchor-icon placed next to the element that you need to use to drag the element around on the page.

In the most recent version of the Figma design document, a similar double-click-to-edit approach is suggested for editing images - in this case editing is changing the focal point and maybe even the zoom inside the available viewbox. The Figma sketch suggests a view change when double clicking (graying out the background), so it's clear that you're in “edit mode”. This same visual style can be used for other elements, text elements in particular.

For either case it’s necessary to define some sort of link from an element to the element’s editable version. Who handles this switching? Who checks if edit mode is even supported by the given element (as not all elements will have that)?

These ideas must be explored and in particular merged with whatever transformation library we go with in the above. This is however also a UX discussion.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A suggestion is made based on the findings

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by dvoytenko** [comment]
I believe @pbakaus's (please confirm) latest idea is to go to edit mode on the single click on a previously selected element. E.g. the edit mode is activated by:

1. Single-click on the selected element. It has to be a single-element selection, not multi-element.
2. Double-click on the element. It's actually in line with (1) if we assume the first click in series would have selected the element and the second click would have activated edit mode.
3. Enter key on the selected element.

**Comment by pbakaus** [comment]
> I believe @pbakaus's (please confirm) latest idea is to go to edit mode on the single click on a previously selected element. E.g. the edit mode is activated by:
> 
> 1. Single-click on the selected element. It has to be a single-element selection, not multi-element.
> 2. Double-click on the element. It's actually in line with (1) if we assume the first click in series would have selected the element and the second click would have activated edit mode.
> 3. Enter key on the selected element.

that is correct.

**Comment by pbakaus** [comment]
what needs to be done here @barklund?

**Comment by barklund** [comment]
> what needs to be done here @barklund?

@pbakaus the related PR has been merged and the in-place editing concept has been fine-tuned in further PR's, so nothing more to do here.
