### ISSUE TITLE
AMP+Adsense does not work

### ISSUE THREAD

**Issue by markbiernat** [ampproject/amp-wp#3812]
I use AMP.
I use AMP Auto Ads Google Adsense tested with both the old code and the newest code.
I use Wordpress Twenty-Twenty.
Adsense stopped showing Ads last week.
If I deactivate AMP, Ads show.

**Comment by westonruter** [comment]
You'll need to share the AMP page with the ads included in order to get any help.

However, we're not ads experts here. I suggest getting help from the [Google AdSense Help Community](https://support.google.com/adsense/community?hl=en) or to get [general AMP Support](https://amp.dev/support/).

**Comment by markbiernat** [comment]
Weston, thank you and sorry for the sparse information.
Here is the website:

(https://political-economy.com/)


I think it might stem from similar issues with the mobile menu and search, that is,  when AMP is used the mobile menu, search and Adsense does not work.

I used the old Adsense code:  amp-auto-ads-0.1.js and now the new code.

The new instruction says to place one line of code in the <head>, without need for code in the <body>.  Regardless, none works unless AMP is disabled.

Here are some screenshots.

![New Adsense Code](https://user-images.githubusercontent.com/30418497/69468119-f3653200-0d58-11ea-907c-5a1ef656cd72.png)

Regardless it says AMP is ON.
![AMP is on](https://user-images.githubusercontent.com/30418497/69468400-f0b70c80-0d59-11ea-8b81-709a00b6f7c6.png)

I use limited plugins, such as Jetpack and Akismet.

![plugins](https://user-images.githubusercontent.com/30418497/69468120-f6602280-0d58-11ea-8a82-1aa7b4afed4f.png)


Thank you again,

Mark

**Comment by westonruter** [comment]
I'm not sure, but if you're looking for the proper way to add `amp-auto-ads` to your site, you can find a plugin to do this here: https://gist.github.com/westonruter/a41573b932e24810b09949136b9a8445

**Comment by markbiernat** [comment]
Thank you for the link (I tried the plugin). I think the implementation of the code is not the issue. The site was running amp auto ads for a year, then the ads stopped. Only when I disable AMP do ads appear again. Since I have the plainest vanilla WP install I can not imagine someone else is not having the same issue.

 I wrote Adsense support last week and no answer other than asking for more information. Perhaps in the meantime, I can take it to AMP General Support.

**Comment by markbiernat** [comment]
My mistake I changed the code when you looked at the site, I was tinkering. 
Even with the code implemented correctly the issue still exists. 
I think it is an Adsense code issues as people are having this issue on the Adsense community forum also to no avail. 
https://support.google.com/adsense/thread/10337359?hl=en

**Comment by westonruter** [comment]
Ok, good luck with finding a resolution.

**Comment by markbiernat** [comment]
@westonruter Thank you very much. You have always been very responsive and helpful to resolve AMP issues.

**Comment by netnaps** [comment]
the Google AdSense publisher id starts with pub-, not ca-pub- as per google screenshot attached.
![Screenshot 2020-07-21 at 4 16 38 PM](https://user-images.githubusercontent.com/67054369/88046395-9b8ffc80-cb6d-11ea-9322-cc6bcf34e8ef.png)
