### ISSUE TITLE
Measurement units in the editor and in the FE (`px` vs `%`)

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3816]
## Feature description

Previously, for the purposes of responsiveness, the width, height, and positioning of the element were all measured in percentage. This ensured that if an element took half of the width of a Page in the editor that it would do the same in the FE independent of the viewport measures.

There have been suggestions for an alternative approach using pixels instead.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AC: Create test cases in which using % works
* AC: Create test cases in which using % does not work

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Use of percentages also resulted in a baseline support for landscape without having to make a separate layout.

**Comment by dvoytenko** [comment]
I agree: `%` are the best for an average case. But we are trying to figure out if there's more to it based on the complete feature set.

But to clarify things a bit - there are several nuances involved:
 * To stress: we are talking about direction-sensitive `%`. The best proxy for those are `vh` and `vw`.
 * Internally, for the purposed of the editor, we should probably always use the absolute px system normalized on the editor page's width and height. E.g. if the data model specifies width as `15%` we do `15% * editorWidth`.
 * `100%` is not a very good resolution, so we are likely to have to support floats, which we then have to round to some reasonable decimal, e.g. not `33.3333...3%`.
 * If a designer wants to have a fixed aspect ratio (e.g. a square shape) - direction-sensitive `%` cannot give us that by itself. We could try to use `auto`. On the web today we can only do `auto` for height. The only exception to this is when we can use `vw`/`vh` directly. The good news `vh`/`vw` currently work for us. But this could be fragile if we start doing things like grouping or insets viewport.
 * Another issue: `vw`/`vh` are harder for responsiveness with fixed aspect ratio. E.g. trying to have a square that will always be square and always fit on the screen. It'd be good to have `vmin` for that. Offering `vmin` and `vmax` during editing might complicate the editor a lot.
 * There might be some particular shapes or screen elements that require one or both dimensions to be fixed to CSS pixels. E.g. a header that has to have `50px` height or a CTA button that has to be `50px : 120px`. E.g. sometimes scaling elements proportionally is not the right way to go.
 * Offering a limited set of units (such as `%`, `px`, `vmin`) for each of x/y/w/h could be useful, but could also complicate the editor's UI significantly.
 * Event with units, things would get very confusing if a user wanted to place a simple branding-style `50px:50px` (strictly square) image in the vertical and horizontal center of the screen. In CSS we'd do something like `height: calc(50% - 50px/2)`, which is definitely too much for the editor. We could consider "position origin" for something like this where we ask an element to be positioned in alignment with its center, not left/top corner - this is similar to `object-position` or `transform-origin`. 

From the product point of view, we need to decide on non-% units as soon as possible for the product MVP. But technically, I believe, it'd help a lot if we simply switched to editor px values for all internal needs. That will ensure that we can handle most of things that would come up in the product design in the future. We could provide a context-based service for this. E.g.:

```
const units = useContext(Units);
x.style.width = units.toEditorHorizPx(attributes.width);
x.style.height = units.toEditorVertPx(attributes.height);
x.style.left = units.toEditorHorizPx(attributes.width);
x.style.top = units.toEditorVertPx(attributes.height);
```

**Comment by pbakaus** [comment]
Relevant to this discussion is my write up around anchoring in the feature brief / epic: https://docs.google.com/document/d/1_3-_v4zH6bW9hOplOO8wYxj8l4C0soMgEbD7XLiXrrg/edit#

**Comment by jauyong** [comment]
Per our grooming meeting, this will act as a discovery ticket where the AC is to create test cases

**Comment by miina** [comment]
For fixed aspect ratio:
In case of shapes that need to keep the ratio (including squares), could we perhaps use `%` for width and pseudo selector with padding for height? For example, a squared shape which would always have 50% width (assuming there's no room-taking content inside it!):
```
.square {
  width: 50%;
}
.square:before {
  background: url( 'path/to/svg' );
  content: "";
  display: block;
  padding-top: 100%;
}
```
Or a header that needs to always be 50px (again assuming no room-taking content inside):
```
.header {
  width: 100%;
}
.header:before {
  background: yellow;
  content: "";
  display: block;
  padding-top: 50px;
}
```

This, however, would not resolve the issue of "always fitting on the screen" since although the width would always stay in the limits of the screen, the height wouldn't necessarily. Unless we would here change the anchor, e.g. to bottom instead of top if the square is placed near the bottom.

In case of buttons, maybe a button should always be in `px`, possibly with pre-defined (e.g. small/medium/large and full-width for `%` for width) styles + allowing assigning pixels directly. Will the CTA button be be positioned with `absolute`, or will it have left/center/right alignment?

**Comment by dvoytenko** [comment]
@miina 

> In case of shapes that need to keep the ratio (including squares), could we perhaps use % for width and pseudo selector with padding for height?

Yeah, this is exactly what we'd do, but two nuances:
 1. `padding-top` only works on for width-based aspect-ratio. There's not a lot tools yet in CSS land to do height-based one, afaik.
 2. The issue you describe with keeping content on the screen. Width-based aspect ratio could push things off the screen. We could consider using `vmin` CSS units to prevent that. E.g. `50vmin:50vmin` will always be a square and will always fit on the screen.

I think overall we could come up with approaches like this for most of use cases: proportional layout, fixed button sizes, preserved aspect ratios, etc. But we have two issues to solve:
 1. How to make this behavior expected in the editor's context and not overwhelm the designer with many switches, units, etc.
 2. How to interpret the designed model in the editor and generate the "good quality" AMP document.

**Comment by pbakaus** [comment]
The decision has been made to stick to a “TV-safe”content area with a fixed aspect ratio of 9:16, and optionally allow the background layer to fill beyond the safe area.

We need to ensure that the safe area and background are always anchored to each other (such that they never change their position relative to each other), and should make the "unsafe fill" of the background optional.

Helpful drawing visualizing this:
<img width="699" alt="Screen Shot 2019-12-18 at 6 58 58" src="https://user-images.githubusercontent.com/43004/71175184-32f34100-2267-11ea-9664-dc8f5be1a14d.png">

This means we should be able to completely stay with percentage based positioning for now (or alternatively, virtual px).

/cc @dvoytenko @swissspidy

**Comment by miina** [comment]
Thanks for the update, @pbakaus 

Looks like we'll need a new issue for discussing and implementing the fixed aspect ratio. The editor is currently already using percentage for positioning and width/height (in the FE), is there anything remaining to confirm on the `%` vs `px` topic, or could this issue be closed and followed up by a new 9:16 aspect ratio issue?

**Comment by dvoytenko** [comment]
@miina 

> The editor is currently already using percentage for positioning and width/height (in the FE), is 

To confirm: the editor is currently using `px` in FE and model. Or am I misunderstanding this?

**Comment by miina** [comment]
@dvoytenko The editor itself is using pixels, however, `%` is saved to AMP HTML and thus used in the FE when rendering.

**Comment by dvoytenko** [comment]
@miina Got it. I thought it was editor's FE :)

**Comment by dvoytenko** [comment]
But I agree. This issue is set. I'll close it.

**Comment by dvoytenko** [comment]
I filed https://github.com/ampproject/amp-wp/issues/3996 to follow up on the safe/unsafe areas in the editor.
