### ISSUE TITLE
Copy Change for "Remove Element" Button

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3822]
## Feature description

The “Remove Element” button is also now inconsistent with the “Remove” language for invalid markup on the validated URL screen. The text should perhaps be changed to “Delete Element” to make it more clear. Or it could be “Remove Block” to be consistent with Gutenberg:

![image](https://user-images.githubusercontent.com/5874851/69674336-4812f080-106a-11ea-9a14-574133198f60.png)

But at the same time, this removal is redundant because you can already remove blocks in the Gutenberg UI. It would be better to have some explanation for why it should be removed.

This was taken out of #3664 
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kienstra** [comment]
If it's alright, I'm going to open a PR for this to change the text to 'Remove Block.'

**Comment by kienstra** [comment]
**Testing Steps**

1. Create a new post
2. Add a Custom HTML block
3. Add this to it:
```html
<script>foo();</script>
```
4. Update the post
5. Expected: there's a button with the label 'Remove Block':

![remove-block](https://user-images.githubusercontent.com/4063887/76816042-cf74a300-67c4-11ea-83c4-121244fe2929.png)
