### ISSUE TITLE
Add page navigation

### ISSUE THREAD

**Issue by barklund** [ampproject/amp-wp#3830]
## Feature description

Add buttons to go to next and previous page.

<img width="492" alt="Screen Shot 2019-11-27 at 11 02 39 AM" src="https://user-images.githubusercontent.com/637548/69739284-742f7f80-1105-11ea-8d07-5e3d64c96142.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Next and previous buttons added.
2. Clicking Next, takes you to the next page
3. Clicking Previous, takes you to the previous page
4. The buttons should be inactive when you are unable to go next or previous

## Implementation brief

* Add two arrows which will have `onClick` handling.
* The `onClick` handler will set the current Page either previous or next.
* The `onClick` handler is not added to "Prev" icon on the first page and "Next" icon on the last Page, and the arrows are hidden.
* The arrows should be focusable via keyboard (arrows / Tab) and also move to the next/prev page via clicking "Enter".

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
@barklund are you including page navigation via thumbnails in this issue or should I create a separate issue for that?

**Comment by barklund** [comment]
@jauyong, I actually only intended this issue to be about the two navigation buttons to go to next or previous - there are issues for the other things separately.

**Comment by miina** [comment]
Moving this to IBR, unless any objections to the approach, will move this to the Execution board for implementing.

cc @barklund @dvoytenko @spacedmonkey @swissspidy

**Comment by barklund** [comment]
Looks good to me. Remember to set `aria-hidden` when buttons are disabled. I don't think there's any other a11y properties to set here.

**Comment by barklund** [comment]
> Looks good to me. Remember to set `aria-hidden` when buttons are disabled. I don't think there's any other a11y properties to set here.

`aria-disabled` that is - and only if regular `disabled` property isn't used of course.

**Comment by spacedmonkey** [comment]
This seems good to me. We can test accessories when we have a PR for this and add any missing attributes then. I would also add some screen reader text for next and back.

**Comment by dvoytenko** [comment]
LGTM

**Comment by miina** [comment]
Closed with ampproject/amp-wp#4049
