### ISSUE TITLE
Remove "old" add page button

### ISSUE THREAD

**Issue by barklund** [ampproject/amp-wp#3832]
## Feature description

The button to add a new page has been removed from its current location next to the page.

It will be added to the carousel in a separate issue.

This is pending UX review.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Remove add page button.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
Removing the UX label as the Page Navigation with the new add page location is now "UX Locked" in figma.

**Comment by jauyong** [comment]
This is dependent on https://github.com/ampproject/amp-wp/issues/3834. 
Before we remove the add page button we need to make sure we have a button to add pages to.

**Comment by miina** [comment]
@swissspidy Assigning this to you since this should probably be implemented together with ampproject/web-stories-wp#60

**Comment by swissspidy** [comment]
Now this is more tied to ampproject/amp-wp#3829

**Comment by swissspidy** [comment]
Fixed by ampproject/amp-wp#4005
