### ISSUE TITLE
Make all text translatable 

### ISSUE THREAD

**Issue by spacedmonkey** [ampproject/amp-wp#3842]
## Feature description

Make all displayed text to displayed to users translatable.

---------------

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Also assigning myself to look into the linting part

**Comment by spacedmonkey** [comment]
@swissspidy Can you also do you magic around generate json files and loading them into the editor?

**Comment by swissspidy** [comment]
JSON files would be provided by WordPress.org eventually, but we can temporarily generate them ourselves in the meantime if needed
