### ISSUE TITLE
Text Presets

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3858]
## Feature description

Text presets from templates and user generated are added to the Text Block library

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pbakaus** [comment]
Duplicate of ampproject/web-stories-wp#29
