### ISSUE TITLE
Story-only plugin build

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3862]
## Feature description

Dedicated plugin page on wp.org to get just "Stories" portion of plugin

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
This is basically done with the new repository.

What would be needed is updating the AMP plugin accordingly if needed, so that the two plugins work well together without conflict.
