### ISSUE TITLE
Twitter embed in Classic Block is duplicated

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3865]
## Bug Description

Given `post_content` (from theme unit test data) that consists of:

```
https://twitter.com/nacin/status/319508408669708289

This post tests WordPress' <a title="Twitter Embeds" href="https://en.support.wordpress.com/twitter/twitter-embeds/" target="_blank" rel="noopener noreferrer">Twitter Embeds</a> feature.
```

This is incorrectly resulting in the Tweet being duplicated:

![image](https://user-images.githubusercontent.com/134745/69929008-18dc0380-14f0-11ea-9fac-f4fee042fac7.png)

The generated HTML even includes the duplication:

```html
<p><amp-twitter width="600" height="480" layout="responsive" data-tweetid="319508408669708289"></amp-twitter></p>
<amp-twitter width="600" height="480" layout="responsive" data-tweetid="319508408669708289" class="twitter-tweet" data-width="550" data-dnt="true" placeholder=""><blockquote class="twitter-tweet" data-width="550" data-dnt="true" placeholder="">
<p lang="en" dir="ltr">Really cool to read through and find so much awesomeness added to WordPress 3.6 while I was gone. I should take three weeks off more often.</p>
<p>— Andrew Nacin (@nacin) <a href="https://twitter.com/nacin/status/319508408669708289?ref_src=twsrc%5Etfw">April 3, 2013</a></p></blockquote></amp-twitter>
<p></p>
<p>This post tests WordPress’ <a title="Twitter Embeds" href="https://en.support.wordpress.com/twitter/twitter-embeds/" target="_blank" rel="noopener noreferrer">Twitter Embeds</a> feature.</p>
```

## Expected Behaviour

The non-AMP version does not have a duplicated embed, and this is what it should look like in AMP:

![image](https://user-images.githubusercontent.com/134745/69929035-2f825a80-14f0-11ea-99be-45e322c04130.png)

## Steps to reproduce

1. Create a post and enter code editor mode, pasting the above `post_content` into it.
2. Publish and view the AMP version/
3. See duplicated tweet.

## Additional context

The issue doesn't seem to occur in 1.4.1, so it seems to be some regression introduced in `develop` since the 1.4 branch.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Now not seeing any duplication,:

![image](https://user-images.githubusercontent.com/16945664/70380531-d7da5980-190a-11ea-9e51-f23e4447dd3f.png)
