### ISSUE TITLE
Advanced AMP Ads Don't Utilize AMP Iframe

### ISSUE THREAD

**Issue by djixas** [ampproject/amp-wp#3867]
## Bug Description

Can't use iframe for amp advanced ads as it does not auto insert AMP IFRAME javascript, if I add it manually, script removes such content from the ad code.

Custom header code does same.

`<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
`

## Expected Behaviour

Should auto include amp iframe just like for posts

## Additional context

 - Plugin version: AMP Ads 1.17

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I'm not familiar with the AMP Add plugin. Please share the URL to the plugin site.

**Comment by djixas** [comment]
> I'm not familiar with the AMP Add plugin. Please share the URL to the plugin site.

https://ampforwp.com/advanced-amp-ads/

**Comment by westonruter** [comment]
Ok, you are reporting an issue for a different AMP plugin. Please report your issue here: https://github.com/ahmedkaludi/accelerated-mobile-pages
