### ISSUE TITLE
Use objects for validation errors

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#3875]
## Feature description

_(Copied from https://github.com/ampproject/amp-wp/pull/3780#discussion_r350821157)_

We should use objects for the different validation errors (like you would use separate objects for exceptions as well).

**Benefits:**

1. Instead of passing arrays around with multiple types of information, we can pass a single object of type `AMP_Validation_Error` around.
2. The objects can have proper constructors that know which type of data to collect for each error, allowing us to add type checking and other safeguards:
	```php
	return new DisallowedFirstChildError( $child_elements[0]->nodeName, $child_tags['first_child_tag_name_oneof'] );`
	```
3. If we have variations for a given error, we can have named constructors instead of the built-in one. (Don't think that is needed, though) 
4. All the display message generation can be encapsulated:
	```php
	foreach ( $validation_errors as $error ) {
		$title = $error->get_title();
		// [...]
	}
	```
5. Faster, as it replaces string comparisons with type checks:
	```php
	// if ( $validation_error['code'] === AMP_Tag_And_Attribute_Sanitizer::DISALLOWED_ATTR ) {}
	if ( $validation_error instanceof DisallowedAttributeError ) {}
	```
6. Uses less memory, because most arrays with strings will be turned into internal properties instead.
7. Removes big `switch()` statements like the one below. Whatever needs to be checked across all validation errors will be encapsulated as a method on them.
8. I personally think it is much easier to read (see 5. as an example).
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Will be important as part of #3730.
