### ISSUE TITLE
The attribute 'frameborder' in tag 'amp-iframe' is set to the invalid value ''. 

### ISSUE THREAD

**Issue by Mte90** [ampproject/amp-wp#3882]
## Bug Description

Input:
```
<iframe style="border: none; overflow: hidden;" src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2FTheRadfordFamily%2Fphotos%2Fa.506512802742080.1073741827.464409336952427%2F1686097548116927%2F%3Ftype%3D3&amp;width=500" width="500" height="479" frameborder="0" scrolling="no"></iframe>
```

Output:
```
<amp-iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2FTheRadfordFamily%2Fphotos%2Fa.506512802742080.1073741827.464409336952427%2F1686097548116927%2F%3Ftype%3D3&amp;width=500" width=500 height=479 frameborder scrolling=no sandbox="allow-scripts allow-same-origin" layout=intrinsic class="amp-wp-enforced-sizes amp-wp-35a9dde">
```

I get this in the Google Search console: `The attribute 'frameborder' in tag 'amp-iframe' is set to the invalid value ''.`

## Expected Behaviour

No error in search console

## Additional context

 - WordPress version: 5.3
 - Plugin version: Latest

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@Mte90 Are you using “W3 Total Cache” by any chance? I believe the issue is the “HTML minify” feature. Please try turning off that feature and confirm. 

See previously-reported issue at https://wordpress.org/support/topic/amp-validation-issues/

**Comment by Mte90** [comment]
Yes that was the problem. Dammit how many plugins doesn't integrate well with AMP...

**Comment by westonruter** [comment]
I don't think this is an AMP-compatibility problem. It's just a plain bug in W3 Total Cache where `0` is being erroneously equated with an empty attribute value.

**Comment by westonruter** [comment]
I've also submitted https://github.com/W3EDGE/w3-total-cache/issues/90 😄

**Comment by Mte90** [comment]
closed my ticket 😅
