### ISSUE TITLE
Image: Cropped/masked editing

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amp-wp#3895]
## Feature description

* How does the image editing work?
* How does it interop with the selection transformers?
* How are the editing tools overlayed?
* How do we show the background for image cropping?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A suggestion is made based on the findings

## Implementation brief

* A very preliminary implementation demo is [here](https://gist.github.com/dvoytenko/5b75b685595a1e4da0a89f6e61fbba4e). Here's a short [video](https://drive.google.com/file/d/1sh31zM7o5rw0uIYtu0QBkK56ioC2TUqr/view?usp=sharing).
* There are two transformable elements involved: the image's shell (the element itself) and the image panning within the cropped shell. Ideally we will use the Moveable library for them as well.
* These transformables are mostly independent from each other: the elements are not grouped and not operating as a group. But they define boundaries and guidelines for each other. Thus this will require two `Moveable` components.
* I can reuse the existing "selection" `Moveable` implemented in #3798 for the element's shell or we can add a new one. The differences: we have to restyle the resizing grips to crop style and we need to disable dragging and rotation. The demo borrows the `Moveable` from #3798 but changes it quite a bit. But, as in #3798 resizing is done by outline and the actual element is resized once it's released. I think it's better since it shows a clear indication of before/after state. The resize operation itself is expensive: it updates pan position, scale factor, etc.
* The second `Moveable` only enables dragging. It's for panning of the full image in the cropped shell. Unlike resize - the demo implements panning immediately to show exactly how focal point changes. Note that panning is very cheap comparing to resize.
* It's very important that panning `Moveable` is on top of the resizing one. This appears a limitation of the library.
* The demo uses state for element properties. This will, of course, change.
* The panning/cropping implemented using two images on top of each other that are 100% synchronized. The bottom image has opacity of 0.5 and is used to show the "ghost" image behind the actual image. The top image has opacity of 1 and is clipped to the element's outline.
* Demo adds scaler per design mocks. However, this scaler "feels" more like an edit panel, with the only exception that it's not docked in the side-panel on the right. It looks like design mocks add more such "floating" panels for other elements. Perhaps we can implement them the same way as side-panels, except that they will be floating. E.g. `IMAGE_SCALE_PANEL: {float: true, anchor: 'bottom'}` or such.
* Big annoyance: if the element properties are updated some other way, there's no clear way to "refresh" `Moveable` component to remeasure and redraw selection/anchor lines. For now I'm resetting these components using key-increment. Very ugly. So, lmk if you have an advice for this.
* It looks like `Moveable` doesn't support bounds for resizing - that's very annoying. LMK if you found a way.
* Idle observation: we need some form of an ESC stack where different transient operations could push themselves to. When ESC is clicked, we would only need to cancel the top-most operation and pop it from the stack. E.g. while resizing ESC should cancel resizing and go back to the previous size. The subsequent ESC should just exist the edit mode. Etc.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by miina** [comment]
> Big annoyance: if the element properties are updated some other way, there's no clear way to "refresh" Moveable component to remeasure and redraw selection/anchor lines. For now I'm resetting these components using key-increment. Very ugly. So, lmk if you have an advice for this.

Do you mean sth like this?
https://github.com/ampproject/amp-wp/pull/3804/files#diff-3688303d740704ce521b8f44dbb09923R79-R84

> It looks like Moveable doesn't support bounds for resizing - that's very annoying. LMK if you found a way.

Do you mean for setting min-max size? Or do you mean for not allowing resizing more than X pixels from the handles (to avoid going "over the edge" of something)?

**Comment by dvoytenko** [comment]
> Do you mean sth like this?
> https://github.com/ampproject/amp-wp/pull/3804/files#diff-3688303d740704ce521b8f44dbb09923R79-R84

Thanks! This works perfectly well. I've updated my example to use this instead of keys.

> > It looks like Moveable doesn't support bounds for resizing - that's very annoying. LMK if you found a way.
> 
> Do you mean for setting min-max size? Or do you mean for not allowing resizing more than X pixels from the handles (to avoid going "over the edge" of something)?

I think the "over the edge" issue that you're describing. I.e. if you're pulling the handle and it goes out of canvas or such. Not 100% certain we need to be too protective over this. But another thing I've been noticing: I'm not sure guideliness/snapping works on resize either.

**Comment by dvoytenko** [comment]
I updated the [demo](https://gist.github.com/dvoytenko/5b75b685595a1e4da0a89f6e61fbba4e) with a few suggestions and also changed Moveable handles to crop-style. [New demo video](https://drive.google.com/file/d/1sh31zM7o5rw0uIYtu0QBkK56ioC2TUqr/view?usp=sharing).
