### ISSUE TITLE
Eliminate add_smooth_scrolling from Twenty Twenty core theme sanitization

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3900]
In WordPress 5.3.1, Twenty Twenty will remove its JS-based smooth scrolling in favor of `scroll-behavior` CSS. See [Make/Core post](https://make.wordpress.org/core/2019/12/08/twenty-twenty-animated-scroll-changes-in-wordpress-5-3-1/). This being the case, we should be able to eliminate this code from the core theme sanitizer:

https://github.com/ampproject/amp-wp/blob/bf8a1740e3561a6852b36155f6b3c9998deeaa7e/includes/sanitizers/class-amp-core-theme-sanitizer.php#L67-L70

Trac ticket: https://core.trac.wordpress.org/ticket/48763

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I just found that this introduced a regression with paired browsing. Because of the `scroll-behavior:smooth` the scrolling is no longer synchronized.

Perhaps paired browsing needs to add some highly-specific style rule like:

```
html {
    scroll-behavior: auto !important;
}
```

**Comment by csossi** [comment]
Verified in QA - 1.1
