### ISSUE TITLE
Lasso selection

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amp-wp#3906]
## Feature description

This is a classical laso selection mechanism where a user can start dragging with the pointer down and on pointer-up select 1-N elements that overlap with the laso's area. This issue assumes the multi-selection is already (at least) in the execution phase.

Some nuances:

1. Any part of unobscured canvas area can be used to start laso.
2. We may or may not want to allow Laso to be cancelable with ESC.
3. (Controversial part) The "background" elements do not participate in laso, but can be used to start it.
4. We may or may not be able (or want) to use `Moveable` for this. I'm not sure `Moveable` by default provides drag-to-resize ability.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The laso implementation architecture is proposed.

## Implementation brief

* See #4018
* Pointer events are handled on the canvas' background
* The special overlay layer is used to draw the laso rectangle
* The laso rectange coordinates are recalculated to the page's coordinates
* A simple element lookup finds all intersecting elements and selects them

TODO:

- [ ] Background elements cannot participate in the laso selection, otherwise nothing can ever be selected this way.
- [ ] Possibly similar behavior should apply to fullscreen elements

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pbakaus** [comment]
Outline here confirmed to be consistent with [epic brief](https://docs.google.com/document/d/1_3-_v4zH6bW9hOplOO8wYxj8l4C0soMgEbD7XLiXrrg/edit#heading=h.tpoomr3k647b).

**Comment by miina** [comment]
@dvoytenko Could you write a short implementation brief as well generally describing the approach in ampproject/amp-wp#4018, the idea of overlays and the change from using the wrapper for the attributes instead of the elements directly, etc.

**Comment by dvoytenko** [comment]
> @dvoytenko Could you write a short implementation brief as well generally describing the approach in ampproject/amp-wp#4018, the idea of overlays and the change from using the wrapper for the attributes instead of the elements directly, etc.

Done. PTAL. I also left outstanding TODO items once we have background elements.

**Comment by miina** [comment]
LGTM, will move this to In Progress.
