### ISSUE TITLE
Add support for Katex

### ISSUE THREAD

**Issue by yogeshbeniwal** [ampproject/amp-wp#3914]
## Feature description

Add Katex Support for AMP pages as supported by https://wordpress.org/plugins/katex/ plugin for non-AMP pages

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Support for AMP should go into the Katex plugin instead. Otherwise, it should go into a separate adapter plugin.

**Comment by westonruter** [comment]
I could encourage you to reach out to the developer to suggest adding support for [`amp-mathml`](https://amp.dev/documentation/components/amp-mathml/).
