### ISSUE TITLE
Font Picker 

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3916]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
@jauyong Duplicate of #3759?

**Comment by jauyong** [comment]
@swissspidy I'll delete this. I think was supposed to be for #3917
