### ISSUE TITLE
Background 

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3919]
## Feature description

This ticket covers background images / videos. 
Note that this is related to but different than full bleed components #3802. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by dvoytenko** [comment]
Duplicate of https://github.com/ampproject/amp-wp/issues/3936
