### ISSUE TITLE
Notices php 7.4.0

### ISSUE THREAD

**Issue by Camilo517** [ampproject/amp-wp#3925]
Notice: is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /var/www/vhosts/domain.com/httpdocs/wp-includes/functions.php on line 4903

Notice: is_feed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /var/www/vhosts/domain.com/httpdocs/wp-includes/functions.php on line 4903

Notice: is_amp_endpoint was called incorrectly. is_amp_endpoint() fue llamado antes de llamar al gancho parse_query. Please see Debugging in WordPress for more information. (This message was added in version 0.4.2.) in /var/www/vhosts/domain.com/httpdocs/wp-includes/functions.php on line 4903

Notice: is_amp_endpoint was called incorrectly. is_amp_endpoint() fue llamado antes de generar la instancia para WP_Query. Please see Debugging in WordPress for more information. (This message was added in version 1.1.) in /var/www/vhosts/domain.com/httpdocs/wp-includes/functions.php on line 4903

**Comment by westonruter** [comment]
As the notices say, it appears a theme or plugin is calling `is_amp_endpoint()` too early.

**Comment by Camilo517** [comment]
It happens when using your plugin and php 7.4 @westonruter

**Comment by westonruter** [comment]
Yes, but the cause is most likely because of the theme or plugin your are using. Please share the list of themes and plugins, and search for instances of `is_amp_endpoint()` being called in them.

**Comment by Camilo517** [comment]
I'm sorry, right. The cause is this plugin. I have already reported it
https://wordpress.org/plugins/visual-portfolio/
When I saw amp I thought that the cause was the plugin amp: S

**Comment by westonruter** [comment]
Topic: https://wordpress.org/support/topic/notices-php-7-4/

Tip: When submitting bug reports or support topics, it is helpful if you share more details about the error, rather than just a dump of the error messages. For example, the active plugins and theme. WordPress now has the Site Health Info which is allows you to easily share important information.
