### ISSUE TITLE
Validation error for hoverintent-js appearing in WP 5.3.1 

### ISSUE THREAD

**Issue by Lofesa** [ampproject/amp-wp#3927]
Hi
I have upgraded WP to version 5.3.1 and now in validation have a new issue with a js file loaded in the admin side,
`wp-includes/js/hoverintent-js.min.js`
Is loaded by the WP core file 
script-loader.php:2647 
cript-loader.php:2637

**Comment by westonruter** [comment]
Thanks for reporting this. I can see the same. We'll fix in 1.4.2. In the meantime, you can just leave the invalid markup as “Removed”.

**Comment by westonruter** [comment]
Another problem with WordPress 5.3.1 with hoverintent being removed is the admin bar dropdowns don't appear. This is also fixed in #3928 by including hoverintent in dev mode.

**Comment by Lofesa** [comment]
Hi
If I put these changed file to the 1.5.0-alpha-20191207T181223Z-c3e9208b version I have it must work?

**Comment by westonruter** [comment]
@Lofesa I've made a build with the PR applied to the 1.4 branch. Please test v1.4.2-alpha-20191215T003107Z-8e22e4f0: [amp.zip](https://github.com/ampproject/amp-wp/files/3964507/amp.zip)

**Comment by Lofesa** [comment]
But this build contain the changes made in PR #3898 ?
If not then I will make some trick to get back the JSON

**Comment by westonruter** [comment]
@Lofesa Here's a build which includes the changes from both PRs #3898 and #3928: https://github.com/ampproject/amp-wp/pull/3928#issuecomment-565861292

**Comment by Lofesa** [comment]
@westonruter  It work.

**Comment by rsmith4321** [comment]
Great I was having the same issue, thanks.
