### ISSUE TITLE
Paired browsing JS fails to load in WordPress 4.9

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3932]
## Bug Description

Originally reported in https://github.com/ampproject/amp-wp/pull/3928#issuecomment-565828463.

There is a conflict in WordPress 4.9 due to the amp-paired-browsing-client not being printed: https://travis-ci.org/ampproject/amp-wp/jobs/625330248#L1062-L1068

I believe this is due to the fact that `amp-paired-browsing-client` depends on both `wp-dom-ready` and `wp-polyfill` but only the former is being polyfilled for WordPress 4.9:

https://github.com/ampproject/amp-wp/blob/80e70e3a48a55e80597c698d748180e94716c471/webpack.config.js#L261-L263

In other words, there is no polyfill for the polyfills.

Three options I see here:

1. Increase minimum WP version to 5.0 and eliminate these pre-Gutenberg polyfills altogether.
2. Polyfill the polyfills.
3. Prevent paired browsing from being available in WordPress 4.9.

I've gone ahead and removed the test case in 64a80518461c1191aef540fc8b922823376514ca, but this will need to be fixed for v1.5 in a separate PR. That PR can revert this commit to re-add those tests.

## Expected Behaviour

Paired browsing should either be not available or the minimum version of WordPress should be bumped.

## Steps to reproduce

Try to access paired browsing in WordPress 4.9.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
I believe adding a polyfill for the polyfills would be the safest option here, but increasing the minimum WP version to 5.0 is also an interesting option to investigate. If information is available to analyze the current installs of the plugin by WP version that would make the decision of increasing said version much easier.

**Comment by csossi** [comment]
any QA instructions for me here, @pierlon ?

**Comment by pierlon** [comment]
Developer QA done by @swissspidy so this can be moved to Done.
