### ISSUE TITLE
AMP Plugin removes 'application/ld+json' script created by custom Yoast filters only in posts.

### ISSUE THREAD

**Issue by oftara** [ampproject/amp-wp#3935]
## Bug Description

The AMP Plugin removes the ' application/ld+json' data generated by Yoast only from posts, when extended with filters.

I've debugged until the output function of yoast and everything is correct. After that the whole script tag gets replaced with the one generated by the AMP plugin. I guess, that this happens on line 1566 in includes\class-amp-theme-support.php

## Steps to reproduce
Here is the code that I am using:

in functions.php of my theme:

```php
add_filter( 'wpseo_schema_graph_pieces', function ( $pieces, $context ) {

require_once __DIR__ . '/inc/class-wpseo-schema-classes.php';
   $pieces[] = new WPSEO_Schema_Medical_Page( $context );

   return $pieces;
}, 11, 2 );
```

the class file:

```php
class WPSEO_Schema_Medical_Page implements WPSEO_Graph_Piece {

	private $context;

	protected $type = array( 'MedicalWebPage' );

	public function __construct( WPSEO_Schema_Context $context ) {
		$this->context = $context;
	}

	public function is_needed() {
		return ! empty( get_post_meta( $this->context->id, 'custom_schema_medical_webpage', true ) );
	}

	public function generate() {

		$data = get_post_meta( $this->context->id, 'custom_schema_medical_webpage', true );

		if ( ! empty( $data ) ) {
			$data          = json_decode( $data , true );
			$data['@type'] = 'MedicalWebPage';
			$data['text']  = get_the_content( $this->context->id );

		}

		return $data;
	}

}
```

I'm saving the data as JSON objects in the custom fields of Wordpress:

```json
custom_schema_medical_webpage: { "about": {"@type": "MedicalCondition", "name": "Schnarchen"}, "audience": {"@type": "Audience", "url": "http://schema.org/Patient"}, "author": [{"@type": "Person", "honorificPrefix": "", "jobTitle": "Arzt", "name": "Arzt"}], "dateModified": "28.11.2019", "headline": "Was tun gegen Schnarchen – unsere 5 Tipps", "inLanguage": "de-DE", "name": "Was tun gegen Schnarchen – unsere 5 Tipps", "}
```

## Additional context

 - WordPress version: 5.3.1
 - Plugin version: 1.4.1
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: Standard
 - PHP version: 7.3
 - OS: CentOS 7
 - Yoast SEO Premium: 12.7.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by oftara** [comment]
I've found the cause of this behavior. The 'text' data in this case is too long.

**Comment by westonruter** [comment]
Too long for Yoast?

**Comment by oftara** [comment]
No, it works  when AMP is disabled on that page.

**Comment by westonruter** [comment]
How long was the text data? Please share the `<script>` as it appears on the non-AMP page.

**Comment by oftara** [comment]
The text data is 11339 chars long. In this case the HTML and Gutenberg code
is not stripped from it. It should be a lot less when done.

I'm also attaching the Json object inside the script tag.

**Comment by westonruter** [comment]
@oftara It looks like the actual cause is the JSON data contains HTML comments inside of some of the strings:

> ![image](https://user-images.githubusercontent.com/134745/71115302-7a55d080-2186-11ea-9a5a-1f076e64cd8b.png)

This something we could fix in the AMP plugin by replacing `<!--` with Unicode escape sequences upon serialization.

**Comment by westonruter** [comment]
The quick fix is for you to figure out a way to strip the Gutenberg block comments from the `text` appearing in the JSON.

**Comment by westonruter** [comment]
@oftara actually, that's something you should report as a bug to Yoast. The `text` content should not be containing markup, I believe.

**Comment by oftara** [comment]
I'm extending the YOAST plugin and this is my mistake. I'll clear it from all markups and HTML.
Is there an issue with longer text, or is it caused just by the Gutenberg comments?

**Comment by westonruter** [comment]
The only issue is that the text contains HTML comments. The AMP validator spec does not allow it:

https://github.com/ampproject/amphtml/blob/aba0528f13a46920c40eb6eb8a55f1163b3c6b83/validator/validator-main.protoascii#L4990-L4995

If you remove the `<!--` then the issue will go away. All you need to do is:

```diff
- $data['text']  = get_the_content( $this->context->id );
+ $data['text']  = strip_tags( get_the_content( $this->context->id ) );
```

**Comment by oftara** [comment]
Thanks a lot! :)
