### ISSUE TITLE
Prevent decoding=async from being copied from img to amp-img since invalid (and built-in); raise validation error for loading!=lazy

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3938]
## Bug Description

When adding an `<img>` with `decoding=async` attribute, a validation error is raised because of this `decoding` attribute. The `AMP_Img_Sanitizer` should be just omitting the `decoding` attribute entirely when it has a value of `async` since `amp-img` does asynchronous decoding by default and so it is redundant.

Additionally, when a `loading` attribute is supplied, it should not silently pass through if it has a value other than `lazy`; it is important to raise a validation error in such case to capture cases where the user tried to load an image non-lazily. This is a follow-up on #3084. In patch form:

```diff
--- a/includes/sanitizers/class-amp-img-sanitizer.php
+++ b/includes/sanitizers/class-amp-img-sanitizer.php
@@ -197,10 +197,15 @@ class AMP_Img_Sanitizer extends AMP_Base_Sanitizer {
 
 				// Skip directly copying new web platform attributes from img to amp-img which are largely handled by AMP already.
 				case 'importance': // Not supported by AMP.
-				case 'loading': // Lazy-loading handled by amp-img natively.
 				case 'intrinsicsize': // Responsive images handled by amp-img directly.
 					break;
 
+				case 'loading': // Lazy-loading handled by amp-img natively.
+					if ( 'lazy' !== strtolower( $value ) ) {
+						$out[ $name ] = $value;
+					}
+					break;
+
 				default:
 					$out[ $name ] = $value;
 					break;
```

## Expected Behaviour

The `decoding=async` and `loading=lazy` attributes should be omitted; no validation error should occur. If `decoding` or `loading` attributes are supplied with any other value than `async` and `lazy`, respectively, then validation errors should be raised.

## Steps to reproduce

1. Create a Custom HTML block containing: `<img decoding="async" loading="eager" src="https://blog.amp.dev/wp-content/uploads/2019/12/AdobeStock_163856462-e1574813805126-1024x448.jpeg" alt="" class="wp-image-3003" width="1024" height="448">`
2. Save the post.
3. See a validation error for `decoding` attribute but not one for the `loading` attribute (which there should be).

## Screenshots

![image](https://user-images.githubusercontent.com/134745/70940711-c296b680-1fff-11ea-9b32-7a48af8d1195.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA:
![image](https://user-images.githubusercontent.com/16945664/74475143-db431180-4e74-11ea-9231-2a488649b4f6.png)
