### ISSUE TITLE
Prevent loading=lazy from being copied from iframe to amp-iframe since invalid (and built-in)

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3939]
## Bug Description

When adding an `<iframe>` with `loading=lazy` attribute, a validation error is raised because of this `loading` attribute. The `AMP_Iframe_Sanitizer` should be just omitting the `loading` attribute entirely when it has a value of `lazy` since `amp-iframe` does lazy-loading by default and so it is redundant.

If the value is anything other than `lazy` (e.g. `eager` or `auto`) then a validation error should still be raised so the user is informed of the failed attempt to lazy-load.

Relates to #3938.

## Expected Behaviour

No validation error should be raised when `loading=lazy` is added to an `<iframe>`.

## Steps to reproduce

1. Create a Custom HTML block with `<iframe loading="lazy" src="https://example.com" width="320" height="640"></iframe> `
2. Save the post.
3. See the validation error.

## Screenshots

![image](https://user-images.githubusercontent.com/134745/70941535-8a907300-2001-11ea-9515-2926ccf06707.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by claudiosossi** [comment]
Verified in QA
