### ISSUE TITLE
Omit security=restricted and handle marginheight/marginwidth attributes in iframe sanitizer

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3950]
## Bug Description

When adding an `<iframe>` with `security=restricted` attribute, a validation error is raised. This `security` attribute is obsolete (only ever supported in IE, AFAIK) in favor of the `sandbox` which `amp-iframe` supports and the iframe sanitizer provides by default. So I believe the `security=restricted` attribute should be omitted entirely, as was done with `loading=lazy` in #3939.

Similarly, iframes have legacy attributes [`marginwidth`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-marginwidth) and [`marginheight`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-marginheight) which were made obsolete in HTML5. When these attributes have a value of `0` they should also be omitted from copying to the `amp-iframe`.

These three attributes—`security`, `marginwidth`, and `marginheight`—are all added by WordPress's post embeds. By preventing these from being copied, post embeds will at least not cause validation errors when used in WordPress but they still won't be fully supported. For that, see #3426.

## Expected Behaviour

No validation errors should be raised.

## Steps to reproduce

1. Create a post and insert a WordPress embed block with the URL https://blog.amp.dev/2019/10/18/the-amp-contributor-summit-hits-new-york/
2. Save the post
3. See validation error warning.

## Screenshots

![image](https://user-images.githubusercontent.com/134745/71026029-2af79d80-20bd-11ea-821f-4245ad884456.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
No validation errors raised:
![image](https://user-images.githubusercontent.com/16945664/71559019-3a64d800-2a27-11ea-8f05-fea04081ea0a.png)
