### ISSUE TITLE
Google does not index the amp links in reader mode

### ISSUE THREAD

**Issue by tommydv** [ampproject/amp-wp#3955]
For general, technical and product help requests, please post it on the [AMP Plugin support forum](https://wordpress.org/support/plugin/amp/). Support will not be provided on GitHub.

Thank you!

Please help.

I have a website using CMS wordpress that has installed the amp plugin and customized it in Reader mode. As I later found in google search console the amp paths in reader mode are not indexed.

Please help me on how to get google to index all amp paths in reader mode. Thank you.

**Comment by westonruter** [comment]
> For general, technical and product help requests, please post it on the [AMP Plugin support forum](https://wordpress.org/support/plugin/amp/). Support will not be provided on GitHub.

I'm confused. Please submit this as a topic on the [support forum](https://wordpress.org/support/plugin/amp/) then.
