### ISSUE TITLE
Default WordPress Fallback images appearing in Google Search on mobile

### ISSUE THREAD

**Issue by athalos** [ampproject/amp-wp#3961]
## Bug Description

Hello. On mobile devices, some of the URLs for our news site, in the News results of Google Search, shows the site name/branding as WordPress instead of our company name.

## Expected Behaviour

When someone searches for our site and clicks News, the expected behavior should be for our company name to appear, but it doesn't. Instead it shows the WordPress Logo.

## Steps to reproduce

To duplicate the error, on a mobile device browser, (chrome, Edge or Safari - the error was reported on all of them), do a Goog for search for mgretailer or mgretailer.com, then tap News.

Below is a screenshot of the results taken from Edge browser.

All of the links are caches of our AMP pages.

## Screenshots

![thread-23197876-6905137328893967831](https://user-images.githubusercontent.com/32401128/71112966-a5e2b600-219a-11ea-942b-b3329f2c1483.jpg)

## Additional context

 - WordPress version: 5.3.1
 - Plugin version:
 - Gutenberg plugin version (if applicable): Yes
 - AMP plugin template mode: version 1.4.1, Reader/classic mode.
 - PHP version: 7.3
 - OS: Unix
 - Browser: Edge, Chrome and Safari
 - Device: Problems were initially reported on iPhone and was duplicated on Android (galaxy s9)

The default fallback images are:
.../wp-content/plugins/amp/assets/images/amp-page-fallback-wordpress-publisher-logo.png
.../wp-content/plugins/amp/assets/images/stories-editor/amp-story-fallback-wordpress-publisher-logo.png

For a quick fix, I'm hoping works, what I did was replace the two of them with our site logos.

I would love to see an option where we can upload our own images, or copy/paste a URL to our logos, at the very least so we can use SEO friendly names.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I took a look at this AMP page: https://mgretailer.com/business/legal-politics/congressional-update-senate-nixes-house-plan-georgia-seeks-legalization/amp/

It has Schema.org metadata defined as follows:

```json
{
    "@graph": [
        {
            "@context": "https://schema.org/",
            "@type": "BreadcrumbList",
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "item": {
                        "@id": "https://mgretailer.com",
                        "name": "Cannabis News Magazine and Digital Platform"
                    },
                    "position": "1"
                },
                {
                    "@type": "ListItem",
                    "item": {
                        "@id": "https://mgretailer.com/business/",
                        "name": "Business"
                    },
                    "position": "2"
                },
                {
                    "@type": "ListItem",
                    "item": {
                        "@id": "https://mgretailer.com/business/legal-politics/",
                        "name": "Legal &amp; Politics"
                    },
                    "position": "3"
                },
                {
                    "@type": "ListItem",
                    "item": {
                        "@id": "https://mgretailer.com/business/legal-politics/congressional-update-senate-nixes-house-plan-georgia-seeks-legalization/",
                        "name": "Congressional Update: Senate Nixes House Plan; Georgia Seeks Legalization"
                    },
                    "position": "4"
                }
            ]
        },
        {
            "@context": "https://schema.org/",
            "@id": "https://mgretailer.com/business/legal-politics/congressional-update-senate-nixes-house-plan-georgia-seeks-legalization/",
            "@type": "Article",
            "author": {
                "@type": "Person",
                "name": "Danny Reed",
                "url": "https://mgretailer.com/author/daniel/"
            },
            "dateModified": "2019-12-17T15:27:08+00:00",
            "datePublished": "2019-12-17T15:27:00+00:00",
            "headline": "Momentum for several changes to federal cannabis law has stalled in the U.S. Senate. In June, the House",
            "image": {
                "@type": "ImageObject",
                "height": "900",
                "url": "https://mgretailer.com/wp-content/uploads/2019/12/Congress_Marijuana_Updates_mgretailer.jpg",
                "width": "1200"
            },
            "keywords": "Legalization",
            "mainEntityOfPage": {
                "@type": "WebPage",
                "url": "https://mgretailer.com/business/legal-politics/congressional-update-senate-nixes-house-plan-georgia-seeks-legalization/"
            },
            "name": "Congressional Update: Senate Nixes House Plan; Georgia Seeks Legalization",
            "publisher": {
                "@type": "Organization",
                "description": "mg Magazine - Cannabis News, information, and exclusive content for Cannabis Professionals. A trusted source for news about marijuana legalization.",
                "logo": {
                    "@type": "ImageObject",
                    "url": "https://mgretailer.com/wp-content/uploads/2019/06/mg-Magazine-Cannabis-News-for-Professionals-logo.png"
                },
                "name": "mg Magazine",
                "url": "https://mgretailer.com/business/legal-politics/congressional-update-senate-nixes-house-plan-georgia-seeks-legalization/"
            },
            "url": "https://mgretailer.com/business/legal-politics/congressional-update-senate-nixes-house-plan-georgia-seeks-legalization/"
        }
    ]
}
```

This doesn't look as expected. I haven't seen the `@graph` before. So while I see you have `publisher.logo` specified, it is nested inside of that Graph object which I don't know if Google understands. 

You can see the requirements for Google Search here: https://developers.google.com/search/docs/data-types/article

Namely, it should look like this:

```json
{
  "@context": "https://schema.org",
  "@type": "NewsArticle",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://google.com/article"
  },
  "headline": "Article headline",
  "image": [
    "https://example.com/photos/1x1/photo.jpg",
    "https://example.com/photos/4x3/photo.jpg",
    "https://example.com/photos/16x9/photo.jpg"
   ],
  "datePublished": "2015-02-05T08:00:00+08:00",
  "dateModified": "2015-02-05T09:20:00+08:00",
  "author": {
    "@type": "Person",
    "name": "John Doe"
  },
   "publisher": {
    "@type": "Organization",
    "name": "Google",
    "logo": {
      "@type": "ImageObject",
      "url": "https://google.com/logo.jpg"
    }
  },
  "description": "A most wonderful article"
}
```

I see a comment after the Schema.org JSON script:

```html
<!-- /Squirrly SEO Plugin -->
```

My guess is that this is a bug with [Squirrly SEO](https://wordpress.org/plugins/squirrly-seo/) and you should submit a bug report to [their forum](https://wordpress.org/support/plugin/squirrly-seo/).

**Comment by westonruter** [comment]
Otherwise, you should open a forum topic on Google's [Webmasters Help Community](https://support.google.com/webmasters/community), as this would be a problem regarding Google Search not the AMP plugin.

**Comment by athalos** [comment]
I guess I'm fully in the batting field now, where everyone thinks it's someone else's problems. Google says it's AMP-WP, AMP-WP says it's Google. Squirrly said it was either Google or AMP-WP. I have put in tickets on all three. Joy
