### ISSUE TITLE
Document sidebar

### ISSUE THREAD

**Issue by spacedmonkey** [ampproject/amp-wp#3974]
## Feature description
 
In the current stories editor, the gutenberg document sidebar is used. See [screenshot](https://user-images.githubusercontent.com/237508/71176605-1dc7e380-2262-11ea-8912-1a3305c1dc6a.png). 

The current sidebar for a story allows user to complete the following functions. 

- Change post status. Status include, draft, published, scheduled and password protected. 
- Publish date, change publish date and set publish date to future (scheduled post). 
- Change author by selecting from dropdown. 
- Move post to trash ( set post status to trash). 
- Edit and preview front end URL / Slug. 
- Add / edit / remove post categories 
- Add / edit / remove post tags
- Set / Remove feature image. 

[**Epic: Document Workflow**](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit#heading=h.epbi26vaa94r) 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by adamsilverstein** [comment]
One feature that would be great to add in a (v2?) sidebar (and I didn't see mentioned elsewhere) would be a _thumbnail map of the story pages._ 

Similar to the way presentation editors show a list of slide thumbnails, the sidebar could display a list of story pages in miniature preview. These thumbnail-pages could be used for navigation or page ordering as well. Related prior art: https://github.com/adamsilverstein/block-minimap

**Comment by swissspidy** [comment]
There are designs for a grid view of pages that can be used for reordering, if that's what you have in mind. Screenshot:

![Screenshot 2020-01-08 at 17 00 23](https://user-images.githubusercontent.com/841956/71994106-7b839600-3238-11ea-87b6-8180eaba633c.png)

**Comment by adamsilverstein** [comment]
Ah, nice - thanks for the link - this is close to what I was thinking of and fulfills the same purpose.

**Comment by miina** [comment]
@spacedmonkey Is this a duplicate of ampproject/amp-wp#3784 and can be closed?

**Comment by spacedmonkey** [comment]
Duplicate of ampproject/amp-wp#3784
