### ISSUE TITLE
Vimeo Block: Output differs depending on URL format used

### ISSUE THREAD

**Issue by laurelfulford** [ampproject/amp-wp#4046]
## Bug Description

Depending on the URL format you use for a video in Core's Vimeo block, the AMP output is different; if you use something like `https://vimeo.com/####`, `amp-video` will be used, but if you use `https://player.vimeo.com/video/####` (the format you get when picking 'Share' on a Vimeo video), `amp-iframe` is used.

## Expected Behaviour

That both URLs formats would use `amp-video`, especially since the URL that's actually output with the tag on the front end does use the `https://player.vimeo.com/video/####` format. 

## Steps to reproduce

1. Add two Vimeo blocks to the Gutenberg editor.
2. In the first one, use the URL format `https://vimeo.com/####` (eg. https://vimeo.com/997312)
3. In the second one, use the URL format `https://player.vimeo.com/video/#####` (eg. https://player.vimeo.com/video/997312)
4. View the source on the front-end; the first video will look like:

```
<figure class="wp-block-embed-vimeo wp-block-embed is-type-video is-provider-vimeo  wp-has-aspect-ratio">
     <div class="wp-block-embed__wrapper">
          <amp-vimeo data-videoid="997312" layout="responsive" width="16" height="9" class="i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-layout i-amphtml-video-component i-amphtml-video-interface" i-amphtml-layout="responsive" style="--loader-delay-offset:600ms !important;">
               <i-amphtml-sizer style="padding-top: 56.25%;"></i-amphtml-sizer>
               <iframe allowfullscreen="" src="https://player.vimeo.com/video/997312" class="i-amphtml-fill-content" frameborder="0"></iframe>
          </amp-vimeo>
     </div>
</figure>
```

And the second video:

```
<figure class="wp-block-embed-vimeo wp-block-embed is-type-video is-provider-vimeo  wp-has-aspect-ratio">
     <div class="wp-block-embed__wrapper">
          <amp-iframe title="Kittens - filmed with the world's first ever Glidetrack!" src="https://player.vimeo.com/video/997312?dnt=1&amp;app_id=122963" width="960" height="540" frameborder="0" allow="autoplay; fullscreen" allowfullscreen="" sandbox="allow-scripts allow-same-origin" layout="intrinsic" class="amp-wp-enforced-sizes i-amphtml-element i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-layout" i-amphtml-layout="intrinsic" style="--loader-delay-offset:19ms !important;">
               <i-amphtml-sizer class="i-amphtml-sizer">
                    <img alt="" role="presentation" aria-hidden="true" class="i-amphtml-intrinsic-sizer" src="data:image/svg+xml;charset=utf-8,<svg height=&quot;540px&quot; width=&quot;960px&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; version=&quot;1.1&quot;/>">
               </i-amphtml-sizer>
               <span placeholder="" class="amp-wp-iframe-placeholder amp-hidden"></span>     
               <noscript>
                    <iframe title="Kittens - filmed with the world's first ever Glidetrack!" src="https://player.vimeo.com/video/997312?dnt=1&amp;app_id=122963" width="960" height="540" frameborder="0"></iframe>
               </noscript>
               <i-amphtml-scroll-container class="amp-active">
                    <iframe class="i-amphtml-fill-content" name="amp_iframe0" style="z-index: 0;" allowfullscreen="" allow="autoplay-disabled; fullscreen" sandbox="allow-scripts allow-same-origin" src="https://player.vimeo.com/video/997312?dnt=1&amp;app_id=122963#amp=1" frameborder="0"></iframe>
               </i-amphtml-scroll-container>
          </amp-iframe>
     </div>
</figure>
```

The issue I'm seeing because of this is that if you accidentally use the second URL format, the video won't fill large spaces, regardless of the block's AMP settings (screenshot below). 

I _think_ this has to do with this regex matching the first URL but not the second: https://github.com/ampproject/amp-wp/blob/6de46e01cbe467e55bcf0ed201c3598dfdc560d2/includes/embeds/class-amp-vimeo-embed.php#L20

## Screenshots

Video using the `https://vimeo.com/####` URL format:

![image](https://user-images.githubusercontent.com/177561/72029341-7fb0b300-323a-11ea-81b2-3d1d900f71a0.png)

Video using the `https://player.vimeo.com/video/####` URL format:

![image](https://user-images.githubusercontent.com/177561/72029353-863f2a80-323a-11ea-90cb-284ee078d71f.png)

## Additional context

 - WordPress version: 5.3.2
 - Plugin version: 1.4.2
 - Gutenberg plugin version (if applicable): 7.2
 - AMP plugin template mode: Standard
 - PHP version: 7.3.13
 - OS: OSX 10.14.6
 - Browser: Firefox 71.0, Chrome 79.0.3945.88
 - Device: Mac laptop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
For reference, here is the regex used by core for vimeo embeds:

https://github.com/WordPress/wordpress-develop/blob/29e97b7b0c0cfc705b00e1c7a4754da939d9cd9b/src/wp-includes/class-wp-oembed.php#L56

**Comment by csossi** [comment]
Verified in QA
