### ISSUE TITLE
Investigate validation errors that are not sanitized in WordPress.org themes

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4060]
## Bug Description

I'm [doing an analysis](https://github.com/westonruter/amp-wp-theme-compat-analysis) of how the entire directory of themes on WordPress.org fair in terms of AMP-compatibility. For each theme (which doesn't go over the 50KB limit), I've obtained the validation results for the initial Hello World post, using the current 1.5-alpha state of the plugin.

The themes which the AMP plugin thinks is serving as valid AMP but actually is not, are:

Theme | Validation Error
------|-----------------
brovy | The mandatory tag 'meta name=viewport' is missing or incorrect. (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#required-markup)
catch-wedding | CSS syntax error in tag 'style amp-custom' - invalid declaration.
catch-wheels | CSS syntax error in tag 'style amp-custom' - invalid declaration.
curiosity-lite | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
curiosity-lite | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
curiosity-lite | CSS syntax error in tag 'style amp-custom' - invalid declaration.
foodoholic | CSS syntax error in tag 'style amp-custom' - invalid declaration.
hamza-lite | The mandatory tag 'meta name=viewport' is missing or incorrect. (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#required-markup)
intuitive | CSS syntax error in tag 'style amp-custom' - invalid declaration.
keep-calm-and-e-comm | The mandatory tag 'meta name=viewport' is missing or incorrect. (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#required-markup)
lakshmi-lite | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
lakshmi-lite | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
lakshmi-lite | CSS syntax error in tag 'style amp-custom' - invalid declaration.
namaste-lite | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
namaste-lite | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
namaste-lite | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
namaste-lite | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
namaste-lite | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
nullpoint | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
nullpoint | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
organic-lite | CSS syntax error in tag 'style amp-custom' - invalid declaration.
organic-lite | CSS syntax error in tag 'style amp-custom' - invalid declaration.
palette | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
palette | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
personal-trainer | CSS syntax error in tag 'style amp-custom' - invalid declaration.
postmag | The property 'width' in attribute 'content' in tag 'meta name=viewport' is set to ' device-width', which is invalid. (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#required-markup)
robot | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
robot | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
ultimate-showcase | The mandatory tag 'meta name=viewport' is missing or incorrect. (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#required-markup)
zincy-lite | The mandatory tag 'meta name=viewport' is missing or incorrect. (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#required-markup)

The frequency is as follows:

Count | Error
-----: | ------
  15 | CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule.
   9 | CSS syntax error in tag 'style amp-custom' - invalid declaration.
   5 | The mandatory tag 'meta name=viewport' is missing or incorrect. (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#required-markup)
   1 | The property 'width' in attribute 'content' in tag 'meta name=viewport' is set to ' device-width', which is invalid. (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#required-markup)

The themes are:

1. [brovy](https://wordpress.org/themes/brovy)
1. [catch-wedding](https://wordpress.org/themes/catch-wedding)
1. [catch-wheels](https://wordpress.org/themes/catch-wheels)
1. [curiosity-lite](https://wordpress.org/themes/curiosity-lite)
1. [foodoholic](https://wordpress.org/themes/foodoholic)
1. [hamza-lite](https://wordpress.org/themes/hamza-lite)
1. [intuitive](https://wordpress.org/themes/intuitive)
1. [keep-calm-and-e-comm](https://wordpress.org/themes/keep-calm-and-e-comm)
1. [lakshmi-lite](https://wordpress.org/themes/lakshmi-lite)
1. [namaste-lite](https://wordpress.org/themes/namaste-lite)
1. [nullpoint](https://wordpress.org/themes/nullpoint)
1. [organic-lite](https://wordpress.org/themes/organic-lite)
1. [palette](https://wordpress.org/themes/palette)
1. [personal-trainer](https://wordpress.org/themes/personal-trainer)
1. [postmag](https://wordpress.org/themes/postmag)
1. [robot](https://wordpress.org/themes/robot)
1. [ultimate-showcase](https://wordpress.org/themes/ultimate-showcase)
1. [zincy-lite](https://wordpress.org/themes/zincy-lite)

## Expected Behaviour

When the AMP plugin intends to serve a valid AMP page, no validation errors should be encountered by the AMP validator.

## Steps to reproduce

0. Enable AMP Standard template mode.
1. Activate one of the above themes.
2. Navigate to the Hello World post.
3. Look for validation errors reported by the AMP validator.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Issues #4070, #4113, #4179 and #4197 were created to resolve the errors above and they should be resolved before this issue can be closed.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
For the themes that have excessive CSS, there is just one that has unexpected validation errors: [corpoz](https://wordpress.org/themes/corpoz/). There appears to be a problem with the output buffering because the first content is `<title>` followed later by `<!DOCTYPE html>`.

**Comment by westonruter** [comment]
> CSS syntax error in tag 'style amp-custom' - invalid declaration.

These seem to all be instances of #4113, except for `curiosity-lite` and `lakshmi-lite`.

In `organic-lite` it is due to properties like `4z-index:1;`.

**Comment by westonruter** [comment]
> brovy	The mandatory tag 'meta name=viewport' is missing or incorrect. (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#required-markup)

I suspect this one will be resolved by #4070. The meta viewport added by the theme is:

```html
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalabe=no">
 ```

So the invalid properties are causing the `meta` tag to be removed.

**Comment by pierlon** [comment]
An overview of the work being done to resolve the validation errors reported above:

Theme | Solution
---|---
[brovy](https://wordpress.org/themes/brovy) | Will be fixed by #4070
[catch-wedding](https://wordpress.org/themes/catch-wedding) | Will be fixed by #4113
[catch-wheels](https://wordpress.org/themes/catch-wheels) | Will be fixed by #4113
[curiosity-lite](https://wordpress.org/themes/curiosity-lite) | Will be fixed by #4197
[foodoholic](https://wordpress.org/themes/foodoholic) | Will be fixed by #4113
[hamza-lite](https://wordpress.org/themes/hamza-lite) | Will be fixed by #4070
[intuitive](https://wordpress.org/themes/intuitive) | Will be fixed by #4113
[keep-calm-and-e-comm](https://wordpress.org/themes/keep-calm-and-e-comm) | Will be fixed by #4070
[lakshmi-lite](https://wordpress.org/themes/lakshmi-lite) | Will be fixed by #4197
[namaste-lite](https://wordpress.org/themes/namaste-lite) | Will be fixed by #4197
[nullpoint](https://wordpress.org/themes/nullpoint) | Will be fixed by #4197
[organic-lite](https://wordpress.org/themes/organic-lite) | Will be fixed by #4113
[palette](https://wordpress.org/themes/palette) | Will be fixed by #4197
[personal-trainer](https://wordpress.org/themes/personal-trainer) | Will be fixed by #4113
[postmag](https://wordpress.org/themes/postmag) | Will be fixed by #4170 and #4197
[robot](https://wordpress.org/themes/robot) | Will be fixed by #4197
[ultimate-showcase](https://wordpress.org/themes/ultimate-showcase) | Will be fixed by #4070
[zincy-lite](https://wordpress.org/themes/zincy-lite) | Will be fixed by #4070

**Comment by pierlon** [comment]
Now that the sub-issues (#4070, #4113, #4179, #4197) created from this discovery are resolved, I'll review the themes in question once more to ensure the reported validation errors for each no longer occurs.

**Comment by pierlon** [comment]
All reported validation errors for each theme are fixed :tada:.

> For the themes that have excessive CSS, there is just one that has unexpected validation errors: [corpoz](https://wordpress.org/themes/corpoz/). There appears to be a problem with the output buffering because the first content is <title> followed later by <!DOCTYPE html>.

Ah I missed that one. I'll open a separate issue for that, but this issue can be closed since the validation errors in the description are resolved.

**Comment by westonruter** [comment]
> Ah I missed that one. I'll open a separate issue for that, but this issue can be closed since the validation errors in the description are resolved.

Sounds good.

**Comment by SpawnTerror** [comment]
Hello all. Has it ever been fixed? My site throws the same error and I'm using AMP Project plugin.

**Comment by westonruter** [comment]
@SpawnTerror Please [open a new support topic](https://wordpress.org/support/plugin/amp/#new-topic-0) with details about what you're seeing.
