### ISSUE TITLE
Add validation of individual properties in meta content attributes

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4070]
## Feature description

Split out from #3758 via the conversation with @schlessera in https://github.com/ampproject/amp-wp/pull/3758#discussion_r348074703:

> More generally, would it be possible to refactor the tag & meta sanitizer to strip the offending properties only, and then check if the entire thing is still valid or not? This way, we wouldn't have to duplicate this logic all over the place...

This is in relation to this code:

https://github.com/ampproject/amp-wp/blob/a7e0497b72b624f6e3032f857f6dcbbf85039f6f/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L1155-L1159

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Adding invalid properties to a `meta[viewport]` should not result in the entire attribute being removed, if there are other valid properties.
* A separate validation error should be raised for each invalid property in a `meta[content]` attribute.

## Implementation brief

Instead of raising one single `DISALLOWED_PROPERTY_IN_ATTR_VALUE` for the entire `meta[content]` attribute and then causing the entire `content` attribute to be removed, we instead need to:

1. Raise a `DISALLOWED_PROPERTY_IN_ATTR_VALUE` validation error for each individual property in the `content` attribute.
2. Remove the invalid property from the `content` attribute if the validation error if `\AMP_Base_Sanitizer::should_sanitize_validation_error()` returns `true`.

What this means is that the `\AMP_Tag_And_Attribute_Sanitizer::sanitize_disallowed_attribute_values_in_node()` method will need to be augmented to not simply return a list of `[ $attr_node, $error_code ]` tuples. I the case of invalid properties, it will also need to return `[ $attr_node, self::DISALLOWED_PROPERTY_IN_ATTR_VALUE, $property_name, $property_value ]`. 

This resulting list of ` $disallowed_attributes` will then need to be iterated over in the `foreach ( $disallowed_attributes as $disallowed_attribute ) {…}` here:

https://github.com/ampproject/amp-wp/blob/a7e0497b72b624f6e3032f857f6dcbbf85039f6f/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L667-L695

Where instead of calling the `\AMP_Base_Sanitizer::remove_invalid_attribute()`, there would need to be a direct call to `AMP_Base_Sanitizer::should_sanitize_validation_error()` and if it returns true, update the value of the attribute to omit that invalid property.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
This would be one more case where the move to error objects instead of error strings&arrays would make sense. Error objects could have an arbitrary number of additional properties and associated logic.

**Comment by westonruter** [comment]
> This would be one more case where the move to error objects instead of error strings&arrays would make sense. Error objects could have an arbitrary number of additional properties and associated logic.

Agreed. However, We can implement this using primitives in the immediate term, and then we can let the requirements help inform the refactor for the next version.

**Comment by westonruter** [comment]
A good theme to test with this is [brovy](https://wordpress.org/themes/brovy). The meta viewport added by the theme is:

```html
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalabe=no">
```

So the invalid properties are causing the `meta` tag to be removed. This is wrong. Only the invalid properties should be removed.

**Comment by csossi** [comment]
Verified in QA
![image](https://user-images.githubusercontent.com/16945664/75361824-e55a0c80-5885-11ea-97f3-f0e18ba12514.png)
