### ISSUE TITLE
Validation broken in Genesis themes by Document::normalize_document_structure()

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4104]
## Bug Description

I was testing out a Genesis theme and I saw in the admin bar that it was ✅ valid AMP. When I clicked to validate the page, however, I unexpectedly saw two validation errors:

![image](https://user-images.githubusercontent.com/134745/72310385-7c506980-3636-11ea-9295-1336563678ff.png)

This made no sense to me and I was racking my brain trying to figure it out. It turns out to be that the `link[rel=canonical]` element was located in the `body` during validation, when for non-validation requests it is in the `head` as expected. 

The issue turns out to be `\Amp\AmpWP\Dom\Document::normalize_document_structure()` introduced in #3758, namely that it is not currently written to account for HTML comments occuring before the doctype.

Normally, WordPress themes hard-code the `<!DOCTYPE html>`, `<html>`, and `<head>` tags. Genesis, however, uses `genesis_doctype()` to generate them. When a validation request is being performed, source stack comments are added before and after `genesis_doctype()` like so:

```html
<!--amp-source-stack {"type":"theme","name":"genesis","file":"lib\/structure\/header.php","line":28,"function":"genesis_do_doctype","hook":"genesis_doctype","priority":10}--><!DOCTYPE html>
<html lang="en-US">
<head >
<meta charset="UTF-8" />
<!--/amp-source-stack {"type":"theme","name":"genesis","file":"lib\/structure\/header.php","line":28,"function":"genesis_do_doctype","hook":"genesis_doctype","priority":10}-->
```

This has the effect of `Document::normalize_document_structure()` normalizing the document to start as:

```html
<!DOCTYPE html><html><head></head><body><!--amp-source-stack {"type":"theme","name":"genesis","file":"lib\/structure\/header.php","line":28,"function":"genesis_do_doctype","hook":"genesis_doctype","priority":10}--><!DOCTYPE html>
<html lang="en-US">
<head >
```

## Expected Behaviour

The DOM used for validation should be normalized to be the same as the DOM used for rendering.

## Steps to reproduce

1. Activate Genesis.
2. Enable Transitional or Standard mode in the AMP plugin.
3. Validate a URL.
4. Notice unexpected validation errors for `link[rel=canonical]` or other tags. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Validating a page generated by Genesis should not result in validation errors when there are none on the frontend.
* HTML comments that occur before and around the `<!DOCTYPE>`, `<html>`, and `<head>` tags must be preserved so that validation errors can be properly sourced.

## Implementation brief

* Perhaps capture the whitespace before/after the `<!DOCTYPE>`, `<html>`, and `<head>` and ensure that they are retained after normalization.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
Good news!

It looks like the comments are not actually stripped:
![Image 2020-01-14 at 2 21 25 PM](https://user-images.githubusercontent.com/83631/72347831-49ab7d00-36d9-11ea-871c-c529d1144fc0.png)

😄

**Comment by schlessera** [comment]
So as it turns out, the main obstacle here is (again) PHP's `DOM_Document`, because when the first tag is _not_ a `<!doctype>`, it prepends a new one, and then strips the duplicate one later in the document. So the comment ends up after the `<!doctype>` instead of in front of it.

I'll need to add additional logic to allow for this, it seems.

**Comment by westonruter** [comment]
Isn't it the normalize method here that is prepending the doctype by prepending `<!DOCTYPE html><html><head></head><body>` when it doesn't find the document to start with a doctype in the first place?

**Comment by schlessera** [comment]
I changed the regexes now to take leading comments into account. But as soon as I do that and keep the first comment, `DOM_Document` strips mine and prepends a default one.

I'm experimenting with the best way of getting around this, which seems to be a combination of changing the doctype into a comment and using the `LIBXML_HTML_NODEFDTD` flag. Weirdly enough, `LIBXML_HTML_NODEFDTD` makes it so that `DOM_Document` doesn't add a default one if it is missing, but still strips mine and adds a default one if it is not the first element.

**Comment by csossi** [comment]
verified in qa
