### ISSUE TITLE
Initial whitespace in href causes validation error

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4117]
## Bug Description

Given HTML like this:

```html
<p>Powered by <a href=" https://wordpress.org/">WordPress</a></p>
```

A `INVALID_URL_PROTOCOL` validation error is raised:

![image](https://user-images.githubusercontent.com/134745/72481584-d6286f00-37af-11ea-9570-8a20271f25f1.png)

Notice the initial whitespace before the URL in the `href` attribute. The link works properly in the non-AMP version, and the above markup causes no validation error in the AMP validator.

So it seems the URL needs to be trimmed before checking whether it is valid.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kienstra** [comment]
**Implementation Brief**

It looks like `trim( $url )` will fix this, but adding test cases for this will also be important.

**Comment by kienstra** [comment]
**Testing Steps**

1. Create a new post
2. Add a Custom HTML block with:
```html
<p><a href=" https://foo.com">Leading Space In href</a></p>
<p><a href="https://foo.com ">Trailing Space In href</a></p>
```
3. Save, and go to the front-end of the AMP URL
4. Expected: there's no validation error

**Comment by csossi** [comment]
Verified in QA

**Comment by kienstra** [comment]
Thanks, Claudio!
