### ISSUE TITLE
Automatically extract @viewport CSS at-rules to meta viewport tag

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4118]
## Feature description

A very common validation error encountered when checking themes is:

> Illegal CSS at-rule: @-ms-viewport

We even suppress them in core themes. For example:

https://github.com/ampproject/amp-wp/blob/1da327d32753d811af023416b75c67f1d0b1dbb1/includes/sanitizers/class-amp-core-theme-sanitizer.php#L251-L265

(There are other vendor prefixes which are possible which we are not accounting for in the core themes.)

We should consider extracting the properties from the the `@viewport` at-rules to populate the `meta[name=viewport]` element, and then just remove the rules from the CSS and skip reporting any validation error.

Something needing to be checked whether the `meta` tag or the at-rule has precedence, and then prepend or append the properties accordingly. Validation would also need to be performed to only copy valid properties.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kienstra** [comment]
I'm working on this if that's alright.

**Comment by kienstra** [comment]
**Implementation**

Hi @westonruter,
Hope you had a great day.

What do you think about:

1. In `AMP_Style_Sanitizer`, find the `@viewport`, `@-ms-viewport`, `@-o-viewport` style rules. Maybe I'm missing some vendor prefixes.

2. Store them in a private property

```diff
diff --git a/includes/sanitizers/class-amp-style-sanitizer.php b/includes/sanitizers/class-amp-style-sanitizer.php
index a58ca41e8..e2e0bb1d8 100644
--- a/includes/sanitizers/class-amp-style-sanitizer.php
+++ b/includes/sanitizers/class-amp-style-sanitizer.php
@@ -1987,7 +1987,12 @@ class AMP_Style_Sanitizer extends AMP_Base_Sanitizer {
                                        $this->splice_imported_stylesheet( $css_item, $css_list, $options )
                                );
                        } elseif ( $css_item instanceof AtRuleSet ) {
-                               if ( ! in_array( $css_item->atRuleName(), $options['allowed_at_rules'], true ) ) {
+                               if ( in_array( $css_item->atRuleName(), ['viewport', '-ms-viewport', '-o-viewport'], true ) ) {
+                                       foreach ( $css_item->getRules() as $rule ) {
+                                       
        // Add rules to self::$extracted_viewport_rules.
+                                       }
+                                       $css_list->remove( $css_item );
+                               } elseif ( ! in_array( $css_item->atRuleName(), $options['allowed_at_rules'], true ) ) {
                                        $error     = [
                                        
        'code'      => self::CSS_SYNTAX_INVALID_AT_RULE,
                                        
        'at_rule'   => $css_item->atRuleName(),
```

3. In `AMP_Meta_Sanitizer::ensure_viewport_is_present()`, get those stored `@viewport` rules
4. Add them to the `meta[name="viewport"]`:

```diff
diff --git a/includes/sanitizers/class-amp-meta-sanitizer.php b/includes/sanitizers/class-amp-meta-sanitizer.php
index 4436605fc..623044af6 100644
--- a/includes/sanitizers/class-amp-meta-sanitizer.php
+++ b/includes/sanitizers/class-amp-meta-sanitizer.php
@@ -135,8 +135,14 @@ class AMP_Meta_Sanitizer extends AMP_Base_Sanitizer {
         * The viewport defaults to 'width=device-width', which is the bare minimum that AMP requires.
         */
        protected function ensure_viewport_is_present() {
+               // Get the valid meta[name="viewport"] rules in AMP_Style_Sanitizer::$extracted_viewport_rules per https://github.com/ampproject/amphtml/blob/5f75efe35b734a4fcf0884d373315d
+               $viewport_rules = $this->get_valid_viewport_rules( AMP_Style_Sanitizer::get_extracted_viewport_rules() );
+
                if ( empty( $this->meta_tags[ self::TAG_VIEWPORT ] ) ) {
-                       $this->meta_tags[ self::TAG_VIEWPORT ][] = $this->create_viewport_element( static::AMP_VIEWPORT );
+                       // Merge the viewport rules from @viewport with the existing ones in meta[content], prioritizing the existing ones.
+                       $this->meta_tags[ self::TAG_VIEWPORT ][] = $this->create_viewport_element( $viewport_rules );
+               } else {
+                       // Add $viewport rules to the existing meta[name="viewport"], prioritizing the existing ones.
                }
        }
```

Thanks, Weston!

**Comment by kienstra** [comment]
**Testing Instructions**

1. Create a new post
2. Add a Custom HTML block with:

```html
<style>
@viewport { viewport-fit: auto }
@-ms-viewport { height: 90% }
</style>
```

3. Go to the front-end of the AMP URL, and inspect the source
4. Expected: There's a `<meta name="viewport" ...>` with a content value that includes `viewport-fit=auto,height=90%,width=device-width`. For example:

![vi-meta](https://user-images.githubusercontent.com/4063887/76518479-c54d5000-6424-11ea-8729-a23eb5742d7d.png)

It's fine if it also has another value, like `initial-scale=1.0`, if that is present on a non-AMP URL.
