### ISSUE TITLE
Paired browsing sporadically fails to detect loaded AMP page

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4127]
## Bug Description

When I have DevTools open and I have “Disable Cache” checked, about 10% of the time that I load paired browsing the AMP version shows the modal:

> The navigated URL is not available for paired browsing.

![image](https://user-images.githubusercontent.com/134745/72574010-70ee7f80-387c-11ea-8ec1-e45bb48d7053.png)

If I reload to try again, then the issue normally goes away, but this is because the issue happens sporadically. 

I can reproduce it both with DevTools open and with doing a hard-reload (Cmd+Shift+R).

There appears to be a race condition that is causing the detection in the AMP window to fail or vice-versa, or rather, detection that the page was able to load properly.

In the console I see an error that may be a clue for what is going on:

![image](https://user-images.githubusercontent.com/134745/72574271-46e98d00-387d-11ea-9fc1-7a81f272e094.png)

This appears to be due to the fact that the paired browsing scripts are being added with `async` attributes:

![image](https://user-images.githubusercontent.com/134745/72574360-9c259e80-387d-11ea-98c6-dfebb4c91ec3.png)

This is resulting in inconsistent loading order, and thus sporadic failures.

So we need to prevent adding the `async` attribute on these scripts, which probably just means removing it from this line:

https://github.com/ampproject/amp-wp/blob/0b91f99566b7254cc5688523291864d3ff49488e/includes/class-amp-theme-support.php#L2485

## Steps to reproduce

1. Enable Transitional mode
2. Open DevTools and Disable Cache
3. Open paired browsing
4. Try reloading 20 times and notice that a couple times the above error is shown.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kienstra** [comment]
This [already has](https://github.com/ampproject/amp-wp/issues/4127#issue-551133043) a good implementation brief:
>So we need to prevent adding the async attribute on these scripts, which probably just means removing it from this line:

...so I'll proceed with a PR if that's alright.

**Comment by kienstra** [comment]
**Testing**

For testing steps, please use Weston's [steps to reproduce](https://github.com/ampproject/amp-wp/issues/4127#issue-551133043), and verify that the issue doesn't occur.

**Comment by csossi** [comment]
Verified in QA
