### ISSUE TITLE
WordPress TV embeds in Classic Editor result in validation error

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4130]
## Bug Description

Adding a WordPress.tv video embed via Classic Editor block results in a validation error:

![image](https://user-images.githubusercontent.com/134745/72656675-d7919d00-3951-11ea-9d1d-98cfcc0f055d.png)

Post content is as follows:

```
Video:

https://wordpress.tv/2009/03/16/anatomy-of-a-wordpress-theme-exploring-the-files-behind-your-theme/

Was it good?
```

Interestingly, if the video is added an Embed block, then no validation error results.

This appears to be a bug with `AMP_WordPress_TV_Embed_Handler`. As opposed to using the `render_block` filter it should instead using the `embed_oembed_html` filter.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kienstra** [comment]
**Confirming Implementation Brief**

Hi @westonruter,
Good to see you earlier.

Your suggestion above of using the `embed_oembed_html` filter looks good, and works locally so far.

If it's alright, here's the rough implementation I'm planning on:

```diff
diff --git a/includes/embeds/class-amp-wordpress-tv-embed-handler.php b/includes/embeds/class-amp-wordpress-tv-embed-handler.php
index 18343a269..512d38c7e 100644
--- a/includes/embeds/class-amp-wordpress-tv-embed-handler.php
+++ b/includes/embeds/class-amp-wordpress-tv-embed-handler.php
@@ -13,34 +13,40 @@
  */
 class AMP_WordPress_TV_Embed_Handler extends AMP_Base_Embed_Handler {
 
+       const URL_PATTERN = '#https?://wordpress\.tv/.*#i';
+
        /**
         * Register embed.
         */
        public function register_embed() {
-               add_filter( 'render_block', [ $this, 'filter_rendered_block' ], 10, 2 );
+               add_filter( 'embed_oembed_html', [ $this, 'filter_oembed_html' ], 10, 2 );
        }
 
        /**
         * Unregister embed.
         */
        public function unregister_embed() {
-               remove_filter( 'render_block', [ $this, 'filter_rendered_block' ], 10 );
+               remove_filter( 'embed_oembed_html', [ $this, 'filter_oembed_html' ], 10 );
        }
 
-       public function filter_rendered_block( $block_content, $block ) {
-               if ( ! isset( $block['blockName'] ) || 'core-embed/wordpress-tv' !== $block['blockName'] ) {
-                       return $block_content;
+       public function filter_oembed_html( $cache, $url ) {
+               if ( ! preg_match( self::URL_PATTERN, $url ) ) {
+                       return $cache;
                }
 
-               $modified_block_content = preg_replace( '#<script(?:\s.*?)?>.*?</script>#s', '', $block_content );
-
-               return null !== $modified_block_content ? $modified_block_content : $block_content;
+               $modified_block_content = preg_replace( '#<script(?:\s.*?)?>.*?</script>#s', '', $cache );
+               return null !== $modified_block_content ? $modified_block_content : $cache;
        }

```

Thanks, Weston!

**Comment by westonruter** [comment]
Looks good. Just make sure the regex matches what is in core and that it works with both blocks and classic embeds.

**Comment by kienstra** [comment]
Thanks, that sounds good!

**Comment by kienstra** [comment]
**Testing Steps**

1. Ensure Standard or Paired mode is selected
2. Create a new post
3. Add a Custom HTML block, add enter https://wordpress.tv/2009/03/16/anatomy-of-a-wordpress-theme-exploring-the-files-behind-your-theme/
4. Add a WordPress.tv block, and enter the URL from step 3
5. Add an Embed block, and enter the URL from step 3
6. Click 'Update,' and go to the front-end of the AMP URL
7. Expected: the videos should display and work, and there should be no validation error:
![custom-html](https://user-images.githubusercontent.com/4063887/72873186-c24fa200-3cb4-11ea-8c76-35a6b44706c0.png)

**Comment by csossi** [comment]
Verified in QA

**Comment by kienstra** [comment]
Thanks, Claudio!
