### ISSUE TITLE
Automatically convert head[profile] to head > link[rel=profile]

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4131]
## Feature description

When doing an analysis of themes on WordPress, I got a `DISALLOWED_ATTR` validation error for the `profile` attribute on the `head` element, such as code in :

```html
<head profile="http://gmpg.org/xfn/11">
```

The `profile` attribute on the `head` element is part of HTML4 but not HTML5. 

The W3 validator provides this advice:

![image](https://user-images.githubusercontent.com/134745/72658213-a53c6b80-3962-11ea-8d33-d08c0dce799b.png)

According to [this SO answer](https://stackoverflow.com/a/14002644), the right way to represent this in HTML5 is:

```html
<head>
    <!-- … -->
    <link rel="profile" href="http://gmpg.org/xfn/11">
```

This should perhaps be done as part of the normalization done in the `Document` class (appending the `link` element to the end of the `head`). It could also be done in a separate sanitizer, though that may be overkill. Since the `Document` class is normalizing to HTML5, I think it makes sense to let the class handle the `profile` transformation.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kienstra** [comment]
**Discussing Implementation Brief**

Hi @westonruter,
Hope you're having a great week.

Assuming it's alright for me to work on this, what do you think about this plan:

1. Add a new method like `Document::convert_head_profile_to_link()`
```diff
diff --git a/src/Dom/Document.php b/src/Dom/Document.php
index 5bad55ddd..5979e983d 100644
--- a/src/Dom/Document.php
+++ b/src/Dom/Document.php
@@ -350,6 +350,8 @@ final class Document extends DOMDocument {
                                $this->head->removeChild( $meta );
                        }
 
+                       $this->convert_head_profile_to_link();
+
                        // Add the required utf-8 meta charset tag.
                        $charset = $this->createElement( 'meta' );
                        $charset->setAttribute( 'charset', self::AMP_ENCODING );
```

Placing it in that location will mean that the new `<link>` will be in the `<head>` after the `<meta charset="utf-8">`

2. As you suggested, create a new `<link rel="profile" href="https://foo.com">`, and insert it in the `<head>`
3. Strip the `head[profile]` attribute

Thanks, Weston!

**Comment by westonruter** [comment]
> 1. Add a new method like `Document::convert_head_profile_to_link()`

Yes, and make it `private`.



> Placing it in that location will mean that the new `<link>` will be in the `<head>` after the `<meta charset="utf-8">`

It can be appended to the `head`. It doesn't need to be right after the `meta` tag.

> * As you suggested, create a new `<link rel="profile" href="https://foo.com">`, and insert it in the `<head>`

The value of the `href` will naturally be the value of the `profile` attribute.

**Comment by kienstra** [comment]
Thanks, Weston! That sounds good.

**Comment by kienstra** [comment]
Hi @westonruter,
Thanks a lot for reviewing and merging #4193. What do you think about moving this to 'Done,' without QA? 

I'm not sure what functional testing is possible, other than review from another developer.

Thanks, Weston!

**Comment by westonruter** [comment]
Yeah. Moved to done.

**Comment by kienstra** [comment]
Thanks, Weston!
