### ISSUE TITLE
Scripts and styles enqueued before wp_enqueue_scripts fail to get sources identified

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4133]
## Bug Description

Scripts and stylesheets enqueued at `init` do not get sourcing information. The same goes for assets registered at `wp_default_styles` and `wp_scripts`.

See [demo plugin](https://gist.github.com/westonruter/7ce1e6270aa5b1bd9e66a3f0adf93b07) which demonstrates the issue.

(Additionally, inline styles added via `wp_add_inline_style()` do not get their source attributed.)

The `wp-includes` source is erroneous for 2 scripts and 3 stylesheets shown on the page.

Related: #4134

## Expected Behaviour

The source column should indicate the theme/plugin that is actually responsible for the style or script being added to the page.

The case of the inline stylesheet is a tricky one, since it is one stylesheet with multiple sources. At the very least it should have the same source information as the stylesheet it is being added inline for. Best case is for it to include all themes/plugins that added inline styles to it.

## Steps to reproduce

0. Enable Standard or Transitional mode in the AMP plugin.
1. Activate the [above plugin](https://gist.github.com/westonruter/7ce1e6270aa5b1bd9e66a3f0adf93b07)
2. Validate a page.
3. Notice the `wp-includes` mentioned unexpectedly.

## Screenshots

When active (and #4026 checked out) the validated URL screen looks like the following, with the red entries erroneously saying they are from `wp-includes` when they should actually be from “Add Assets before wp_enqueue_scripts”.

![72671921-d66e7780-3a06-11ea-8135-d2f12e3dc6b5](https://user-images.githubusercontent.com/134745/72671995-09fdd180-3a08-11ea-8939-07eefbddf6c7.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

* This may be resolved simply by adding the validation hooks earlier. Origination is also a solution, perhaps long-term.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
@kienstra , can you do a dev QA check on this one (or shoot instructions my way?)

**Comment by kienstra** [comment]
**Works as expected**

Now, scripts enqueued on the `init` action get their source.

Similar to the test in https://github.com/ampproject/amp-wp/issues/4134#issuecomment-589893312:

```php
// Enqueues a script and stylesheet.
add_action(
	'init',
	function() {
		$script_slug = 'amp-scratchpad-script';
		wp_enqueue_script(
			$script_slug,
			plugins_url( 'script.js', __FILE__ ),
			[ 'jquery' ],
			'0.1',
			true
		);

		wp_localize_script(
			$script_slug,
			'ampScratchpad',
			wp_json_encode( [ 'foo' => 'baz' ] )
		);

		wp_add_inline_script(
			$script_slug,
			'doSomethingHere()'
		);

		$style_slug = 'amp-scratchpad-style';
		wp_enqueue_style(
			$style_slug,
			plugins_url( 'style.css', __FILE__ ),
			[ 'wp-color-picker', 'site-icon' ],
			'0.1'
		);

		wp_add_inline_style(
			$style_slug,
			'body { background-color: #ffffff; }'
		);
	}
);
```

...the source now appears:

![sources-there](https://user-images.githubusercontent.com/4063887/75717807-7ae70900-5c97-11ea-8b01-274b9c93f6e0.png)

Before, it was `wp-includes`, as Weston mentioned.
