### ISSUE TITLE
Inline scripts/styles should have sources identified and core script/style dependencies should get enqueueing theme/plugin as source

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4134]
## Feature description

Related: #4133

If a theme enqueues a `navigation.js` that has jQuery as a dependency, currently this appears in the validated URL screen as “wp-includes” as the source. This is not very helpful. It would be helpful that if a theme or plugin enqueues a script or a style, that the original theme/plugin that enqueued it would be attributed as a source in some way. As an example, consider this [demo plugin](https://gist.github.com/westonruter/b8f559338bc9ecf1c9f9967c48676219).

All of the scripts here should get “Enqueue assets with core dependencies” as the source, at least indirectly:

![image](https://user-images.githubusercontent.com/134745/72672177-5565af00-3a0b-11ea-9923-a7948ef14025.png)

And for the stylesheets, the same goes for the circled stylesheets:

![image](https://user-images.githubusercontent.com/134745/72676209-7a761400-3a43-11ea-9f4d-877d09f0353c.png)

I believe that [Origination](https://github.com/GoogleChromeLabs/wp-origination) already provides support here for this, so this should perhaps be deferred to the incorporation of that library.

Also: For each script/stylesheet, the asset which caused the dependency to be printed should be listed.

Additionally, inline styles added via `wp_add_inline_style()` do not get their source attributed.

### Inline Scripts

Scripts added via `wp_localize_script()` and `wp_add_inline_script()` should all get properly identified. For this, see [another example plugin](https://gist.github.com/westonruter/2b1b64249befa3b39adccc9f139f9aba).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kienstra** [comment]
I'll do 'dev QA' for this.

**Comment by kienstra** [comment]
**Looks Good!**

Hi @westonruter,
It's really nice to have the sources of dependencies.

As you mentioned in the [testing instructions](https://github.com/ampproject/amp-wp/pull/4135#issue-364504310), this shows the correct plugin sources for:

## Scripts

![plugin-here](https://user-images.githubusercontent.com/4063887/75082204-204fef00-54d8-11ea-9a30-be022ad9f753.png)

## Styles

 
![style-identified](https://user-images.githubusercontent.com/4063887/75082221-29d95700-54d8-11ea-81fd-d5c6d38d6285.png)

Similar to the plugins you shared, here's what I used to test this:

```php
// Enqueues a script and stylesheet.
add_action(
	'wp_enqueue_scripts',
	function() {
		$script_slug = 'amp-scratchpad-script';
		wp_enqueue_script(
			$script_slug,
			plugins_url( 'script.js', __FILE__ ),
			[ 'jquery' ],
			'0.1',
			true
		);

		wp_localize_script(
			$script_slug,
			'ampScratchpad',
			wp_json_encode( [ 'foo' => 'baz' ] )
		);

		wp_add_inline_script(
			$script_slug,
			'doSomethingHere()'
		);

		$style_slug = 'amp-scratchpad-style';
		wp_enqueue_style(
			$style_slug,
			plugins_url( 'style.css', __FILE__ ),
			[ 'wp-color-picker', 'site-icon' ],
			'0.1'
		);

		wp_add_inline_style(
			$style_slug,
			'body { background-color: #ffffff; }'
		);
	}
);

```
