### ISSUE TITLE
PHP Warning due to passing null as haystack value for in_array()

### ISSUE THREAD

**Issue by northernbeacheswebsites** [ampproject/amp-wp#4145]
## Bug Description

Getting the following PHP Error: Warning: in_array() expects parameter 2 to be array, null given in .../plugins/amp/includes/class-amp-theme-support.php on line 1533 this can be seen here: https://www.dropbox.com/s/n25ufth7yzt5n86/amp-error.jpg?dl=0

## Expected Behaviour

There should be no PHP error

## Steps to reproduce

Plugin is activated and I have standard settings activated as shown here:  https://www.dropbox.com/s/8cetg3lu39vluc5/amp-settings.jpg?dl=0

## Screenshots

As shown above

## Additional context

 - WordPress version: 5.3.2
 - Plugin version: 1.4.2
 - PHP version: 7.1.33
- Server: Apache

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Humm. This is the code in question, assuming you are using v1.4.2:

https://github.com/ampproject/amp-wp/blob/2504794703c9e18ba868a573dd06041a15261028/includes/class-amp-theme-support.php#L1533

I wonder why it is `null` for you. Normally it would be equal to `[ 'dashicons' ]`. Do you have some other plugin which is modifying the `admin-bar` stylesheet?

This patch should fix the problem for you regardless:

```diff
--- a/includes/class-amp-theme-support.php
+++ b/includes/class-amp-theme-support.php
@@ -1561,7 +1561,7 @@ class AMP_Theme_Support {
 	 */
 	public static function filter_admin_bar_style_loader_tag( $tag, $handle ) {
 		if (
-			in_array( $handle, wp_styles()->registered['admin-bar']->deps, true ) ?
+			is_array( wp_styles()->registered['admin-bar']->deps ) && in_array( $handle, wp_styles()->registered['admin-bar']->deps, true ) ?
 				self::is_exclusively_dependent( wp_styles(), $handle, 'admin-bar' ) :
 				self::has_dependency( wp_styles(), $handle, 'admin-bar' )
 		) {
@@ -1581,7 +1581,7 @@ class AMP_Theme_Support {
 	 */
 	public static function filter_admin_bar_script_loader_tag( $tag, $handle ) {
 		if (
-			in_array( $handle, wp_scripts()->registered['admin-bar']->deps, true ) ?
+			is_array( wp_scripts()->registered['admin-bar']->deps ) && in_array( $handle, wp_scripts()->registered['admin-bar']->deps, true ) ?
 				self::is_exclusively_dependent( wp_scripts(), $handle, 'admin-bar' ) :
 				self::has_dependency( wp_scripts(), $handle, 'admin-bar' )
 		) {
```

**Comment by northernbeacheswebsites** [comment]
Hi @westonruter Wow, thank you so much for coming up with a solution for this so quickly, I really appreciate it :) I can confirm this works great, will this be released in a future version?

Thank you,

**Comment by westonruter** [comment]
@northernbeacheswebsites Can you please investigate how a theme or plugin is modifying the registered `admin-bar` style to have a `null` value for its `deps`?

**Comment by northernbeacheswebsites** [comment]
I will look into this and see if I can find something, the client has a lot of plugins so it may take some time. Thanks,

**Comment by westonruter** [comment]
We can still harden the plugin to prevent this from happening to others.

**Comment by kienstra** [comment]
**Implementaion**

Hi @westonruter,
Good to see you earlier.

You've essentially fixed this in https://github.com/ampproject/amp-wp/issues/4145#issuecomment-576535058

What do you think about me committing that, and adding unit test cases to cover those not being arrays?

Thanks, Weston!

**Comment by westonruter** [comment]
Please do.

**Comment by kienstra** [comment]
Thanks!
