### ISSUE TITLE
Discovery: Ensure compatibility with new Web Stories plugin

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#4172]
## Feature description

With [the new repo](https://github.com/google/web-stories-wp) for the stories editor soon taking off, we need to ensure the two plugins work flawlessly together.

While the Web Stories plugin already works well standalone, there still seems to be some interference. For example with hooks/filters and rewrites.

The same issue is also being tracked from the other repo's perspective: https://github.com/google/web-stories-wp/issues/3

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Is there an issue when the Stories experience is turned off in the AMP plugin?

One suggestion is activating the Web Stories plugins should force the Stories experience to be disabled in the AMP plugin.

Once the Web Stories plugin is available on WordPress.org, we should remove the experiences options and add a CTA to try out Web Stories.

**Comment by amedina** [comment]
We had a discussion with Paul and Sam yesterday on the best way to proceed
regarding the removal of the editor from the AMP plugin. We'll discuss it
today and update this thread.

Em sex., 24 de jan. de 2020 às 11:14, Weston Ruter <notifications@github.com>
escreveu:

**Comment by westonruter** [comment]
As noted in https://github.com/ampproject/amp-wp/pull/4074#issuecomment-580104897:

We need to disable the AMP Stories experience if either the user is on WordPress version under 5.3 or they have a Gutenberg version that is too new.

Additionally, we need to hide the Stories experience entirely (the experience checkboxes) if the user has no `amp_story` posts created. The thinking being that we can continue to allow access to Stories for users who are using them, but we discontinue offering the Stories feature for new installs or people who don't have stories created. In the place of the experience checkboxes, there can be a notice that says a new Stories plugin is coming and link to it when it is available for testing.

**Comment by westonruter** [comment]
> We need to disable the AMP Stories experience if either the user is on WordPress version under 5.3 or they have a Gutenberg version that is too new.

See #4200.

> Additionally, we need to hide the Stories experience entirely (the experience checkboxes) if the user has no `amp_story` posts created. The thinking being that we can continue to allow access to Stories for users who are using them, but we discontinue offering the Stories feature for new installs or people who don't have stories created. In the place of the experience checkboxes, there can be a notice that says a new Stories plugin is coming and link to it when it is available for testing.

See #4201.

**Comment by westonruter** [comment]
And #4202 for adding a notice to the impending minor release to alert users that the Stories experience bundled with the AMP plugin is deprecated and they need to export them, and then to look out for the Web Stories plugin.

**Comment by westonruter** [comment]
And see #4203 which removes the AMP Stories experience from the AMP plugin.

**Comment by westonruter** [comment]
I believe this discovery has been completed.
