### ISSUE TITLE
E2E tests broken in 1.4 branch

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4174]
## Bug Description

As [reported](https://github.com/ampproject/amp-wp/pull/4043#issuecomment-573132725) in #4043, the E2E test job is failing in the `1.4` branch.

@pierlon [writes](https://github.com/ampproject/amp-wp/pull/4043#issuecomment-573279276):

> The Gutenberg plugin [failed to activate](https://travis-ci.org/ampproject/amp-wp/jobs/635359942#L870), which led to tests failing due to them being unable to find the case-sensitive words "Featured image" (see [1f842d3#diff-792685570ec094fec9f40f84e3af8d3bR25](https://github.com/ampproject/amp-wp/commit/1f842d3deff649af9494772cbb29d5db34f226fa#diff-792685570ec094fec9f40f84e3af8d3bR25)). Apparently WP CLI failed to install and activate Gutenberg due to clash in a function declaration (`WP_CLI\UpgraderSkin::feedback($string)` vs `WP_Upgrader_Skin::feedback($string, ...$args)`.
> 
> On the `1.4` branch, WP CLI v2.3.0 is installed via Composer while within the Docker container v2.4.0 is used. Further investigation shows v2.3.0 uses `WP_CLI\UpgraderSkin::feedback($string)` while v2.4.0 on PHP > 5.6 (which is the case here) uses `WP_Upgrader_Skin::feedback($string, ...$args)`, which leads me to speculate whether both versions are being loaded at the same time. Thoughts @schlessera?
> 
> The `develop` branch uses WP CLI v2.4.0 in both instances, however, which I think is why the error does not occur there.

And @schlessera [replied](https://github.com/ampproject/amp-wp/pull/4043#issuecomment-575497335):

> This is due to a breaking change in WordPress Core 5.3. While making the move to PHP 5.6 code, the signature for the upgrader base class `feedback()` method changed from `WP_Upgrader_Skin::feedback($string)` to `WP_Upgrader_Skin::feedback($string, ...$args)`.
> 
> WP-CLI 2.3.0 is compatible with older versions of WP (< 5.3) only, while WordPress Core 5.3+ requires WP-CLI 2.4.0+.
> 
> This is unfortunate, but that's WordPress' way of backward compatibility I'm afraid...
>
> In case that wasn't clear, the solution is to use WP-CLI v2.4.0+ in the Docker container as well, as it seems to be using WP Core 5.3+.
>
> No, the other way around, install WP-CLI 2.4.0+ on the v1.4 branch if you're using WP Core 5.3+ there. 🤪

## Expected Behaviour

Just as the E2E test on `develop` is not failing, so too should the E2E job not fail in the `1.4` branch.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
> The Gutenberg plugin [failed to activate](https://travis-ci.org/ampproject/amp-wp/jobs/635359942#L870)

@pierlon Are you sure this is the cause of the problem? The PHP warning doesn't seem to indicate a failure to activate the plugin.

I'll be honest that I'm somewhat lost on what to do here.

**Comment by pierlon** [comment]
I'm fairly certain. The error occurs right after the plugin is [installed and activated](https://github.com/ampproject/amp-wp/blob/6cd2c47320f575b1b37bc5f9e98e85635cde3cb2/bin/local-env/install-wordpress.sh#L100).
