### ISSUE TITLE
Restore PHPUnit code coverage to 60%+

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4175]
## Bug Description

After merging #4026 I noticed an ❌ status with the commit:

![image](https://user-images.githubusercontent.com/134745/73117644-e18d4000-3efd-11ea-8b9e-b6955346fa81.png)

Alas, I should have written more tests and Codecov is now [complaining](https://codecov.io/gh/ampproject/amp-wp/commit/50d76db15b8fc9baad3182f82f2e35a58dc9104d).

This is because 0.69% is greater than the configured threshold of 0.1%:

https://github.com/ampproject/amp-wp/blob/50d76db15b8fc9baad3182f82f2e35a58dc9104d/codecov.yml#L8

Coverage should be brought back up to at least 60%.

## Expected Behaviour

Codecov should be happy; test coverage should be complete.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This can be closed once the Codecov has reported the coverage for `develop`, assuming it will be much improved.

**Comment by pierlon** [comment]
[Mission accomplished](https://codecov.io/gh/ampproject/amp-wp/commit/d0b3e7a409814d239eb5b70608cb03c53eacf30e):

![image](https://user-images.githubusercontent.com/16200219/74634479-d5427e80-515b-11ea-8e81-ba55d2fa251d.png)
