### ISSUE TITLE
Eliminate post-processor cache in favor of detecting

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4178]
## Feature description

It has become clear that the post-processor caching is not working. It is currently only offered when the user has an external object cache, and when it is available then very frequently users will see this notice appear on the AMP settings screen:

![The post-processor cache was disabled due to detecting randomly generated content found on on this web page. Randomly generated content was detected on this web page. To avoid filling up the cache with unusable content, the AMP plugin's post-processor cache was automatically disabled.	Read more. This will enable post-processor caching to speed up processing an AMP response after WordPress renders a template.](https://user-images.githubusercontent.com/134745/73126696-b2f97e80-3f6a-11ea-93a6-6a77cf42184f.png)

The reality is that pages with highly-variable content are extremely common, whether that be random numbers, timestamps, or nonces. Therefore I believe this is a feature that should be removed since it is not effective.

We may also want to eliminate support for sending 304 Not Modified responses (#1481). Even though this doesn't directly cause data to be put in to a cache, it can be wasted processing time to compute the `ETag` if it changes with each request.

PRs related to post-processor response caching:

* #1156 for #959 
* #1325 for #1239

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
@westonruter Would you consider removing post-processor related cache as well, or let them expire?

**Comment by westonruter** [comment]
Removing the cache _entries_? There wouldn't be a way to iterate over all of them, so no, there's nothing we can do to delete them. They'll be deleted when they expire.

**Comment by pierlon** [comment]
Yep that's true... I see no problem with them expiring anyways.

**Comment by pierlon** [comment]
The [wiki page on post-processor cache](https://github.com/ampproject/amp-wp/wiki/Post-Processor-Cache) may need to be updated to indicate it has been removed.
