### ISSUE TITLE
Disable AMP Stories experience when recent Gutenberg is active

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4200]
## Feature description

As discussed in #4074 and [reported](https://wordpress.org/support/topic/new-version-of-gutenberg-breaks-stories-layout/) in the support forum, recent versions of Gutenberg break the AMP Stories editor. 

We need to disable the AMP Stories experience if either the user is on WordPress version under 5.3 and/or they have a Gutenberg version that is too new.

Note that if the user does _not_ have any stories created, then the experience would be hidden entirely. See #4201. So this only is needed for users who have existing `amp_story` posts.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by csossi** [comment]
Verified in QA
