### ISSUE TITLE
Hide experience options if no Stories are created, to replace with notice about upcoming Stories plugin

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4201]
## Feature description

The AMP Stories editor is no longer compatible with the latest Gutenberg version (see #4200). For this reason and because work is underway on a new effort to create a standalone Stories plugin (see #4172), we need to sunset the AMP Stories editor in the AMP plugin.

The first part of this, as noted in #4074, we need to hide the Stories experience entirely (the experience checkboxes) if the user has no `amp_story` posts created. The thinking being that we can continue to allow access to Stories for users who are using them, but we discontinue offering the Stories feature for new installs or people who don't have stories created. In the place of the experience checkboxes, there can be a notice that says a new Stories plugin is coming and link to it when it is available for testing.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
As part of this, let's go ahead and make this change:

```diff
diff --git a/includes/admin/class-amp-story-templates.php b/includes/admin/class-amp-story-templates.php
index 6ffcec3af..de6908eb6 100644
--- a/includes/admin/class-amp-story-templates.php
+++ b/includes/admin/class-amp-story-templates.php
@@ -32,6 +32,10 @@ class AMP_Story_Templates {
 	 * Init.
 	 */
 	public function init() {
+		if ( ! AMP_Options_Manager::is_stories_experience_enabled() ) {
+			return;
+		}
+
 		// Always hide the story templates.
 		add_filter( 'pre_get_posts', [ $this, 'filter_pre_get_posts' ] );
 
@@ -41,10 +45,6 @@ class AMP_Story_Templates {
 		// We need to register the taxonomy even if AMP Stories is disabled for tax_query.
 		$this->register_taxonomy();
 
-		if ( ! AMP_Options_Manager::is_stories_experience_enabled() ) {
-			return;
-		}
-
 		add_action( 'save_post_wp_block', [ $this, 'flag_template_as_modified' ] );
 
 		$this->maybe_import_story_templates();
```

I got feedback that the `filter_user_has_cap` here was causing big database load. If the stories experience is not enabled, we can assume that no story templates have been imported.

**Comment by csossi** [comment]
Verified in QA
