### ISSUE TITLE
Remove AMP Stories and eliminate the obsolete experiences UI

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4203]
## Feature description

The Stories experience is being moved to a separate standalone plugin, per #4172. As such, all of the AMP Stories codebase can be removed from the AMP plugin. This includes the experience checkboxes because the AMP plugin would again only be for the website:

![image](https://user-images.githubusercontent.com/134745/73485173-7a391b00-4357-11ea-8fb0-b54e75f47252.png)

Note that this should be done after these issues are resolved: #4200, #4201, #4202. Otherwise, merge conflicts would ensue (though not the end of the world since the merge conflicts would be easy to resolve)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Happy to help with the code removal here and cleaning up all the story-related parts

**Comment by swissspidy** [comment]
An important thing to remember here is that the next plugin update needs to remove any story templates that were stored in the database (as `wp_block` posts). Related: #3210.

**Comment by westonruter** [comment]
I'd say this doesn't have to be done not at the next plugin update but an update in the future. If someone upgrades to 1.5 but then they had stories they wanted to export still and they try downgrading to 1.4.x, the data should still be there for them to export. 

I suppose this isn't exactly relevant for these `wp_block` story templates since they aren't user-generated in the first place. 

But eventually we'd want to remove the `amp_story` posts as well?

**Comment by swissspidy** [comment]
Yes, those as well. Makes sense to me. As long as we don't forget about that data.

**Comment by swissspidy** [comment]
One thought about the templates: if we remove stories entirely, they would suddenly pop up in the reusable blocks management screen. So I think we should really remove those. `amp_story` we can keep in the database.

**Comment by westonruter** [comment]
Great point. Yeah, the AMP Story template `wp_block` posts should be deleted. If someone rolls back to 1.4.x, they'd get re-inserted anyway, as long as the `story_templates_version` setting gets removed as well. This will allow `AMP_Story_Templates::maybe_import_story_templates()` to do its thing.

**Comment by pierlon** [comment]
> Yeah, the AMP Story template wp_block posts should be deleted.

Added to the todo list on #4315.

**Comment by csossi** [comment]
Any QA instructions to add here, @pierlon ?

**Comment by pierlon** [comment]
*Testing instructions:*

1. Verify that the "Experiences" section on the AMP settings page
2. Verify that the "Stories" menu option in the Admin main menu is not available
3. On the "Site Health Info" page, verify that the "Enabled Experiences" debug information is not shown. For example:
    
    ![image](https://user-images.githubusercontent.com/16200219/76335174-09890500-62ec-11ea-866d-0b1049d3a0f2.png)

**Comment by csossi** [comment]
Verified in QA
