### ISSUE TITLE
Implementing and testing for non-standard transformers

### ISSUE THREAD

**Issue by kmyram** [ampproject/amp-wp#4214]
## Feature description

Implementing non-standard/optional/experimental transformers as based in the discovery of #4213. This provides the actual transformers based on the findings in the discovery. For now, the scope is not determined and subsequently neither is AC.

Relates to #4213, #4215, #4216 
Related to #958 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
This is superseded by these issues:
1. **ServerSideRendering** transformer with the following functionality:
	- [Rewrite media, sizes, and heights attributes for SSR](https://github.com/ampproject/amp-wp/issues/4439)
2. **Minify** transformer with the following functionality:
	- [Minify HTML](https://github.com/ampproject/amp-wp/issues/4454)
	- [Strip comments](https://github.com/ampproject/amp-wp/issues/4455)
	- [Trim whitespace in body text nodes](https://github.com/ampproject/amp-wp/issues/4456)
3. **BrowserHints** transformer with the following functionality:
	- [Preload images](https://github.com/ampproject/amp-wp/issues/4457)
4. **BlurredPlaceholders** transformer
	- [Add blurred placeholders for images and video posters](https://github.com/ampproject/amp-wp/issues/4458)
