### ISSUE TITLE
Extract amp/common & amp/optimizer libraries into separate composer packages

### ISSUE THREAD

**Issue by kmyram** [ampproject/amp-wp#4215]
## Feature description

Packaging transformer libraries with Composer for simpler management. Describe and document the individual composer packages and perform the extraction and implementation.

Relates to #4213, #4214, #4216
Related to #958

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ability to install/remove libraries as composer packages, manually and through script

## Implementation brief

* Simply outline steps to take to package each library in composer
* Provide overview of affected libraries

## QA testing instructions

* Test the ability to manually and automatically install and remove libraries with Composer

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
This was fixed via https://github.com/ampproject/amp-wp/issues/4215. The two libraries were merged into one separate package at https://github.com/ampproject/amp-toolbox-php.
