### ISSUE TITLE
Documentation for optimizer libs

### ISSUE THREAD

**Issue by kmyram** [ampproject/amp-wp#4216]
## Feature description

Provide written documentation for optimizer libraries. 

Relates to #4213, #4214, #4215
Related to #958 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* N/A

## Implementation brief

* N/A

## QA testing instructions

* N/A

## Demo

* N/A

## Changelog entry

*

**Comment by amedina** [comment]
@schlessera @kmyram We should prioritize this now that the optimizer functionality is out.

**Comment by amedina** [comment]
This documentation covers aspects of the optimizer as a library, but it does not address the documentation needs for the optimizer being used inside the AMP plugin. We should address the former first, and the former should be ready once the optimizer library is actually ready for release independently of the AMP plugin. Let's create a separate issue to address this.
