### ISSUE TITLE
Templates script[type=text/plain] are removed if "id" attribute is added

### ISSUE THREAD

**Issue by spasibych** [ampproject/amp-wp#4277]
## Bug Description

If add "id" attribute to template like `<script id="my-template" type="text/plain" template="amp-mustache">...</template>` to refer to it, for example from `<amp-list>`, the plugin will completely remove this template from the resulting code.

## Expected Behaviour

Provide "id" attribute support for templates like `<script id="my-template" type="text/plain" template="amp-mustache">...</template>`.

## Steps to reproduce

1. Add code to AMP page:
```html
<script type="text/plain" template="amp-mustache">
    <h2>Plain template</h2>
</script>
<script id="my-template" type="text/plain" template="amp-mustache">
    <h2>Referenced template</h2>
</script>
```
2. View the resulting source code for an AMP page.
3. Make sure the `<script id="my-template" type="text/plain" template="amp-mustache">...</template>` is missing.

Please also see issue [#26676](https://github.com/ampproject/amphtml/issues/26676).

## Additional context

 - WordPress version: 5.3.2
 - Plugin version: 1.4.2
 - AMP plugin template mode: Website; Standard; Serve all templates as AMP regardless of what is being queried.
 - PHP version: 7.3.11

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@spasibych Your markup seems malformed:

```html
<script type="text/plain" template="amp-mustache">
    <h2>Plain template</h2>
</template>
<script id="my-template" type="text/plain" template="amp-mustache">
    <h2>Referenced template</h2>
</template>
```

Should it not rather be:

```html
<script type="text/plain" template="amp-mustache">
    <h2>Plain template</h2>
</script>
<script id="my-template" type="text/plain" template="amp-mustache">
    <h2>Referenced template</h2>
</script>
```

Note `</script>` rather than `</template>` should be used.

**Comment by spasibych** [comment]
@westonruter sorry, wrong, fixed in start post.

But the problem is urgent. Corrections for AMP Cache are already in effect [#26676](https://github.com/ampproject/amphtml/issues/26676#issuecomment-584906020).

Additionally, I add that support for the "id" attribute is not specified in the plugin version 1.4.2 code for "script" templates.

In plugin file class-amp-allowed-tags-generated.php line 13704 are present only for attributes "nonce", "type" and "template":

```php
'attr_spec_list' => array(
	'nonce' => array(),
	'template' => array(
		'dispatch_key' => 2,
		'mandatory' => true,
		'value' => array(
			'amp-mustache',
		),
	),
	'type' => array(
		'mandatory' => true,
		'value_casei' => array(
			'text/plain',
		),
	),
)
```

**Comment by spasibych** [comment]
@westonruter is my mistake, i'm sorry.

Now I tried it and it works. Maybe something from "blacklisted_value_regex" got in the way earlier.
