### ISSUE TITLE
Verify compatibility with Gutenberg 7.5.0

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4286]
## Feature description

Gutenberg [v7.5.0](https://github.com/WordPress/gutenberg/releases/tag/v7.5.0) has some new features which need to be checked for AMP-compatibility:

> ![image](https://user-images.githubusercontent.com/134745/74362382-75c02980-4d7d-11ea-8444-c39fba037cf7.png)

Each should work the same in AMP as non-AMP.

See also release post: https://make.wordpress.org/core/2020/02/12/whats-new-in-gutenberg-12-february/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
All features are working except for Tiktok embeds, which is being tracked in #4326.
