### ISSUE TITLE
Add syntax highlighting for CSS in Stylesheets metabox

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#4295]
## Feature description

We're showing more and more code snippets to end users, with the latest additions being the HTML and the CSS in the stylesheet recap.

As a developer, I would love to have syntax highlighting for all of the code snippets that is being displayed in the compatibility tool.

Right now, this only uses the default `<code>` styling from the WordPress admin, resulting in a hard-to-read, gray mess:

![Image 2020-02-15 at 9 03 29 AM](https://user-images.githubusercontent.com/83631/74584482-0c395880-4fd3-11ea-9d01-9c707ef6cca7.png)

We could either look into resuing CodeMirror's highlighting, as that is shipped with Core (which would then be done client-side), or add a PHP library to do it in PHP on the server-side right away when rendering the markup.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
> We could either look into resuing CodeMirror's highlighting, as that is shipped with Core (which would then be done client-side), or add a PHP library to do it in PHP on the server-side right away when rendering the markup.

It's actually simpler than this. We can do basic syntax highlighting now by color-coding the selectors, braces, property names, and property values… all of which are already tokenized. When concatenating the tokens together we could add some syntax highlighting. This may be sufficient.

**Comment by schlessera** [comment]
> We can do basic syntax highlighting now by color-coding the selectors, braces, property names, and property values… all of which are already tokenized.

That's true for the CSS snippets, but not for the HTML snippets.

Something like the "Original markup" at the top of the screenshot I posted should also be syntax highlighted.

**Comment by westonruter** [comment]
> Something like the "Original markup" at the top of the screenshot I posted should also be syntax highlighted.

Ah, that HTML markup is also being generated based on the data in the validation error. So we can syntax-highlight that as well.

**Comment by schlessera** [comment]
It's pretty easy to add syntax highlighting to an existing DOM graph, yes. We can of course just hand-code everything we require on an as-needed basis.
