### ISSUE TITLE
Add sanitization of JSON to prevent AMP validation errors

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4320]
## Bug Description

I found out that the AMP validator validates JSON for parse errors, but we are not.

Given this markup:

```html
<script type="application/ld+json">
	{BAD  🚫 🚫 🚫
</script>
<amp-analytics type="nielsen">
	<script type="application/json">
		{
			"vars": {
				"apid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
				"apv": "1.0",
				"ap BAD  🚫 🚫 🚫
	</script>
</amp-analytics>
```

No validation errors are reported by the AMP plugin, and yet the AMP validator does report them:

![image](https://user-images.githubusercontent.com/134745/74971027-41c7b280-53d4-11ea-9927-326717396fc7.png)

Such invalid JSON should be sanitized while also reporting a validation error to the user to prevent GSC from alerting users to an error when it crawls next that we can proactively alert them of immediately.

Note that the AMP validator does not yet validate `application/ld+json` data, but it should after https://github.com/ampproject/amphtml/issues/25610.

One way that this JSON parse error can occur is if JSON contains emoji. See https://github.com/ampproject/amp-wp/issues/4318.

The code needing to be patched here is [`AMP_Tag_And_Attribute_Sanitizer::validate_cdata_for_node()`](https://github.com/ampproject/amp-wp/blob/b059e63c1de983a94d598142fded3c6758b0d0b9/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L881-L926). Note this code will also need to be modified to fix a separate bug with how `blacklisted_cdata_regex` is handled, so beware of merge conflicts; see https://github.com/ampproject/amp-wp/issues/4319.

The logic can be adopted from the `amphtml-validator` here: https://github.com/ampproject/amphtml/blob/e1fd0e15b85e6f80f5d6382600b0765875d37b23/validator/engine/validator.js#L6226-L6237

Note the `INVALID_JSON_CDATA` error code. The error message should be: “The script tag contains invalid JSON that cannot be parsed.”

Related support topics:

* https://wordpress.org/support/topic/the-script-tag-contains-invalid-json-that-cannot-be-parsed-4/
* https://wordpress.org/support/topic/the-script-tag-contains-invalid-json-that-cannot-be-parsed-3/
* https://wordpress.org/support/topic/the-script-tag-contains-invalid-json-that-cannot-be-parsed-2/

## Expected Behaviour

* 

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kienstra** [comment]
This is probably a small size.

**Comment by csossi** [comment]
Any QA instructions to add here, @kienstra ?

**Comment by kienstra** [comment]
Hi @csossi,
Could you please use the testing instructions in https://github.com/ampproject/amp-wp/pull/4340#issue-381623731, but ignore step 1 (copying code into a plugin)?

In Step 4, there should be 1 expected validation error.

Thanks, Claudio!

**Comment by csossi** [comment]
Seeing this now, @kienstra - this the description expected here?:
![image](https://user-images.githubusercontent.com/16945664/76713763-67a55600-66f9-11ea-8aa1-dececf712a1c.png)

**Comment by kienstra** [comment]
Hi @csossi,
Thanks, that looks [as expected](https://github.com/ampproject/amp-wp/pull/4340/files#diff-ff6d70c0505290e11be8ca83967c2af0R1851). Sorry, I should have updated the testing instructions for the new message.
