### ISSUE TITLE
HTML outputted before the <!DOCTYPE> declaration produces invalid AMP page

### ISSUE THREAD

**Issue by pierlon** [ampproject/amp-wp#4321]
## Bug Description

An invalid AMP page is served although HTML is outputted before the `<!DOCTYPE>` declaration. An example of this can be seen by installing the [corpoz](https://wordpress.org/themes/corpoz/) theme and viewing an AMP page.

## Expected Behaviour

HTML before the `<!DOCTYPE>` declaration should be sanitized so that a valid AMP page can be produced.

## Steps to reproduce

1. Install the [corpoz](https://wordpress.org/themes/corpoz/) theme
2. The AMP version of any page should be viewable although it is invalid
3. View the page source and observe there are several HTML elements before the `<!DOCTYPE>` declaration

## Screenshots

- Invalid AMP page produced although invalid:

    ![image](https://user-images.githubusercontent.com/16200219/74985292-11613200-542f-11ea-9923-eb164aa2e960.png)

- HTML outputted before `<!DOCTYPE>` declaration:

    ![image](https://user-images.githubusercontent.com/16200219/74985375-3c4b8600-542f-11ea-852c-8250327ca4a9.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Wow. The [`header.php`](https://themes.trac.wordpress.org/browser/corpoz/1.0.6/header.php#L1) in that theme does not… have proper usage of `wp_head()`:

```php
<?php wp_head(); ?> 
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<?php if ( is_singular() && pings_open( get_queried_object() ) ) : ?>
<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
<?php endif; ?>
<?php wp_head(); ?>

</head>
...
```

Notice there are duplicated `wp_head()` calls.

I wonder if we aren't actually doing the wrong thing here. That is so blatantly wrong that it's hard to recover from it.

**Comment by westonruter** [comment]
Perhaps the best course of action for this would be to open a support forum topic for the theme to alert them of the bug.

**Comment by schlessera** [comment]
Yes, I would recommend against taking on arbitrary tech debt on our end because people do the weirdest stuff in themes.

We should build in support for:
- everything that is correct HTML syntax
- everything that is the "lived version" of HTML, where common usage predates and bypasses correct syntax

Everything else should just be flagged as an upstream bug and ignored.

**Comment by pierlon** [comment]
Agreed. I'll file an issue upstream. This is also related to #4297, which _may_ preserve [comments before the `<!DOCTYPE>` declaration](https://github.com/ampproject/amp-wp/pull/4297#issuecomment-589574575).

**Comment by pierlon** [comment]
Upstream issue for reference: https://wordpress.org/support/topic/duplicate-call-of-wp_head-in-header-php/.
