### ISSUE TITLE
PM: Updating Project Management guidelines for AMP Plugin

### ISSUE THREAD

**Issue by kmyram** [ampproject/amp-wp#4322]
## Feature description

Update and adapt the PM guidelines to match the current process for AMP Plugin.
The specifications are documented in `<root>/contributing/project-management.md` and don't apply for this project after the codebase was split.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- [ ] It is easy for anyone in the team or outside to understand the PM guidelines for the AMP Plugin effort 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
Related: #4315

**Comment by westonruter** [comment]
This will be facilitated by #4473.
