### ISSUE TITLE
Trailing right brace in tree-shaken CSS when using featured image in Twenty Twenty theme

### ISSUE THREAD

**Issue by pierlon** [ampproject/amp-wp#4335]
## Bug Description

When a featured image is set on a post with the Twenty Twenty theme activated, the required styles for featured image (added by `AMP_Core_Theme_Sanitizer::add_twentytwenty_masthead_styles`) are not successfully being applied, although the styles can be seen in the page source.

The reason for the CSS not being applied to the rendered page lies within a trailing right brace (`}`) being put immediately before the inline CSS added via `AMP_Core_Theme_Sanitizer::add_twentytwenty_masthead_styles`, causing the rule after to be ignored and thus not being applied to the page. This can be verified by validating the tree-shaken CSS:

![image](https://user-images.githubusercontent.com/16200219/75318794-27be2200-5863-11ea-980e-157915c9b04f.png)

## Expected Behaviour

Required inline style for the featured image in the Twenty Twenty theme should be applied to the page.

## Steps to reproduce

1. Activate Twenty Twenty theme
1. Create a post with a featured image
2. View the AMP page source and verify that there is a trailing right brace in the tree-shaken CSS

## Screenshots

Trailing right brace in tree-shaken CSS:
![image](https://user-images.githubusercontent.com/16200219/75318565-a1094500-5862-11ea-96e9-d6124dbfb6aa.png)

Missing property that should be applied to featured image:
![image](https://user-images.githubusercontent.com/16200219/75319181-11fd2c80-5864-11ea-9fbd-41a4cc8061bf.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@pierlon Is the issue not `\AMP_Core_Theme_Sanitizer::add_nav_menu_styles()`? Namely, I think it is is this brace:

https://github.com/ampproject/amp-wp/blob/28a05d38a19d07eefcfeb86ecdb30156e9752b6b/includes/sanitizers/class-amp-core-theme-sanitizer.php#L1079

Please see if #4370 fixes the problem (and perhaps #4336?).

**Comment by pierlon** [comment]
Yep that's the offender. That fixes bith #4370 and #4336 :tada: .
