### ISSUE TITLE
Consider removing remaining e2e tests

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#4341]
## Feature description

Most of the e2e tests are for Stories, so they might be removed as part of #4315.

This might be a good opportunity to remove the rest of the e2e tests.

They served the plugin well, but at a different time.

There will [only be 2 left](https://github.com/ampproject/amp-wp/tree/a478d12829b345e1716530d67880cfe00cc835e5/tests/e2e/specs/block-editor), one for the AMP toggle, and one for the featured image notice. I wrote those, but they might have outlived their usefulness 😄 

Those might not justify the [intermittent Travis failures](https://github.com/ampproject/amp-wp/pull/4340#commits-pushed-1421fd5).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Travis build [doesn't run e2e tests](https://github.com/ampproject/amp-wp/blob/a478d12829b345e1716530d67880cfe00cc835e5/.travis.yml#L95-L107)
* There is no more [tests/e2e/](https://github.com/ampproject/amp-wp/tree/a478d12829b345e1716530d67880cfe00cc835e5/tests/e2e) directory, and any other dependencies are removed

## Implementation brief

* Remove [the E2E Travis job](https://github.com/ampproject/amp-wp/blob/a478d12829b345e1716530d67880cfe00cc835e5/.travis.yml#L95-L107)
* Remove everything in the [tests/e2e/](https://github.com/ampproject/amp-wp/tree/a478d12829b345e1716530d67880cfe00cc835e5/tests/e2e) directory 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Definitely worth looking into this IMO, but I'd also consider whether the setup could be improved and whether actually _more_ tests would be beneficial.

Alternatively, there would need to be some kind of integration tests that serve as a replacement.

**Comment by kienstra** [comment]
Good points!
