### ISSUE TITLE
amp-facebook is wrapped in a <p> tag when it should be in post root like amp-twitter

### ISSUE THREAD

**Issue by jerclarke** [ampproject/amp-wp#4358]
## Bug Description
<img width="597" alt="Screen Shot 2020-03-02 at 6 49 51 PM" src="https://user-images.githubusercontent.com/139995/75731936-b0e7b580-5cb6-11ea-90d4-a72dc674af27.png">

As you can see, the `amp-facebook` element is inside a `<p>`. To me this is not very elegant and it's also different from the `amp-twitter` output, which is in the post root:

<img width="619" alt="Screen Shot 2020-03-02 at 6 51 43 PM" src="https://user-images.githubusercontent.com/139995/75732019-e8eef880-5cb6-11ea-8c0c-eafd5044fc66.png">

The specific thing I want to do is style the `blockquote.translation` that comes after the embed, which should be possible with `amp-facebook+blockquote.translation`, but becomes essentially impossible due to the wrapping `<p>`. 

## Expected Behaviour

Seems to me that both `amp-facebook` and `amp-twitter` should render without the containing `<p>`. 

Maybe I'm wrong? Is it maybe something wrong with my setup?

#### Example embed code for twitter:

```
<blockquote class="twitter-tweet" data-lang="en">
<p dir="ltr" lang="en">Facebook Instant Articles doesn't allow horizontal rules because lines are dangerous and need to be kept under control.</p>
— jeremyclarke (@jeremyclarke) <a href="https://twitter.com/jeremyclarke/status/826895852350345217">February 1, 2017</a></blockquote>
<blockquote class="translation">Les Articles Instants de Facebook ne permet pas de règles horizontales car les lignes sont dangereuses et doivent être gardées sous contrôle.</blockquote>
```

#### Example embed code for Facebook

```
[embed]https://www.facebook.com/globalvoicesonline/videos/10154528534218876/[/embed]
<blockquote class="translation">This is a translation of the facebook thing above.</blockquote>
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
The difference appears to be that for Twitter, you're using the `blockquote` embed code which doesn't have an implied paragraph whereas for Twitter, you are. I thought this would automatically be fixed if you used the `embed` shortcode for Twitter as well? In other words:

```html
[embed]https://twitter.com/jeremyclarke/status/826895852350345217[/embed]
<blockquote class="translation">Les Articles Instants de Facebook ne permet pas de règles horizontales car les lignes sont dangereuses et doivent être gardées sous contrôle.</blockquote>

[embed]https://www.facebook.com/globalvoicesonline/videos/10154528534218876/[/embed]
<blockquote class="translation">This is a translation of the facebook thing above.</blockquote>
```

However, this doesn't seem to be the case:

![image](https://user-images.githubusercontent.com/134745/75824549-8cdcb080-5d58-11ea-8dfd-f7770ce4ca5e.png)

So there is indeed an inconsistency here.

**Comment by jerclarke** [comment]
A great, sorry I didn't think of that! Glad in the end it still applies, since I really prefer the Twitter embed via. blockquote compared to a straight `[embed]` of the URL (whereas with FB the URL `[embed]` is the obvious winner. 

Thanks for looking into it so quickly.

**Comment by pierlon** [comment]
WordPress wraps these embeds in `<p>` tags so we should be replicating the same behavior here.

**Comment by westonruter** [comment]
We just need to be careful that the embed is the only content in the paragraph.

**Comment by westonruter** [comment]
@jerclarke Would you please test the merged fix in this build: [amp.zip](https://github.com/ampproject/amp-wp/files/4345378/amp.zip) (v1.5.0-alpha-20200317T192008Z-ff8e61ce2)? Thank you.

**Comment by jerclarke** [comment]
@westonruter sorry for the delay, just checked and it works great. Thanks so much!

**Comment by jerclarke** [comment]
At the risk of seeming ungrateful, this same issue affects `amp-instagram`:

<img width="670" alt="Screen Shot 2020-03-25 at 7 19 09 PM" src="https://user-images.githubusercontent.com/139995/77600459-a2637700-6ecd-11ea-905f-71b1552aefb5.png">

Maybe it's easy to fix this too?

**Comment by jerclarke** [comment]
And YouTube

<img width="672" alt="Screen Shot 2020-03-25 at 7 21 08 PM" src="https://user-images.githubusercontent.com/139995/77600513-cc1c9e00-6ecd-11ea-847e-9afd0a89b7eb.png">

Would you like me to make a new ticket to collect these?

**Comment by westonruter** [comment]
> Would you like me to make a new ticket to collect these?

Yes. Please do.

**Comment by jerclarke** [comment]
@westonruter Just a quick note that the .zip version of the plugin broke my Soundcloud embeds. Just noticed after a lot of debugging that Soundcloud works fine with the released plugin (i.e. on all my other sites I tried) but not on the .zip version (the site I had been working on). 

Good idea to double-check that before release 🙏🏻

**Comment by westonruter** [comment]
@jerclarke broke in what way?

**Comment by pierlon** [comment]
@jerclarke could you give an example of the Soundcloud embed you're referring to, along with the plugin version you're using?

**Comment by westonruter** [comment]
Testing a SoundCloud block and an Embed block:

> ![image](https://user-images.githubusercontent.com/134745/77706295-36d9e200-6f7f-11ea-8658-c5e4c7afcc02.png)

Post content:

```html
<!-- wp:paragraph -->
<p>SoundCloud block:</p>
<!-- /wp:paragraph -->

<!-- wp:core-embed/soundcloud {"url":"https://soundcloud.com/jack-villano-villano/mozart-requiem-in-d-minor","type":"rich","providerNameSlug":"soundcloud","className":"wp-embed-aspect-4-3 wp-has-aspect-ratio"} -->
<figure class="wp-block-embed-soundcloud wp-block-embed is-type-rich is-provider-soundcloud wp-embed-aspect-4-3 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://soundcloud.com/jack-villano-villano/mozart-requiem-in-d-minor
</div></figure>
<!-- /wp:core-embed/soundcloud -->

<!-- wp:paragraph -->
<p>Embed shortcode:</p>
<!-- /wp:paragraph -->

<!-- wp:shortcode -->
[embed]https://soundcloud.com/jack-villano-villano/mozart-requiem-in-d-minor[/embed]
<!-- /wp:shortcode -->
```

These are rendering identically:

> ![image](https://user-images.githubusercontent.com/134745/77706355-65f05380-6f7f-11ea-99d6-d562b6ec9a32.png)

**Comment by westonruter** [comment]
Well, we're going live with 1.5 today.
