### ISSUE TITLE
Optimizer strips admin bar style[data-ampdevmode]

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4369]
## Bug Description

When the admin bar is shown and dev mode is enabled, when the Optimizer is turned off an AMP page will include:

```html
<style id="admin-bar-inline-css" data-ampdevmode="">
html { margin-top: 32px !important; }
	@media screen and ( max-width: 782px ) {
		html { margin-top: 46px !important; }
	}html:not(#_) > body { position:unset !important; }
</style>
```

However, when the Optimizer is enabled, this `style` element is getting removed. The effect is the admin bar is not properly positioned:

![image](https://user-images.githubusercontent.com/134745/76170925-c2601000-6143-11ea-921d-a3376ffad947.png)

## Expected Behaviour

Elements with `data-ampdevmode` should be exempted from the Optimizer.

## Steps to reproduce

1. Make sure the Optimizer is enabled, e.g. via `add_filter( 'amp_enable_optimizer', '__return_true' ); add_filter( 'amp_enable_ssr', '__return_true' );`
2. Log-in to the WordPress admin so the admin bar us displayed.
3. View the frontend with Twenty Twenty active.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
cc @schlessera

**Comment by westonruter** [comment]
Most likely culprit: 

https://github.com/ampproject/amp-wp/blob/28a05d38a19d07eefcfeb86ecdb30156e9752b6b/lib/optimizer/src/Transformer/AmpBoilerplate.php#L69-L94

**Comment by westonruter** [comment]
I see two options for addressing this:

1. Prevent running optimizer when dev mode is enabled.
2. Fix `removeStyleAndNoscriptTags` to only remove the boilerplate styles exclusively.

In reality, I think both should be done. It would be good to default to not running Optimizer when dev mode is enabled (as opposed to `WP_DEBUG`, which is the current condition). It would also be good to harden the Optimizer so it doesn't fail when in dev mode: this should include upstream fixes to the Node version as well.

**Comment by csossi** [comment]
Any QA instructions to add here, @schlessera ?

**Comment by schlessera** [comment]
@csossi Added testing instructions to the description above.

**Comment by csossi** [comment]
Verified in QA
