### ISSUE TITLE
Query string params are discarded from url

### ISSUE THREAD

**Issue by hellotoby** [ampproject/amp-wp#4376]
## Bug Description

Query string parameters should be kept in the URL regardless of whether the page is amp or not.

A common use case for this is Google analytics campaign tracking which requires urls be appended with a ?utm_source=campaign query string parameter.

e.g 
https://test.com/?utm_source=campaign => will always resolve to https://test.com/
https://test.com/?amp&utm_source=campaign => will always resolve to https://test.com/?amp

I have only been able to test this in amp transitional mode.

## Expected Behaviour

The query string params should be kept in the url for non-amp pages. For amp pages using the ?amp param, they should be appended.

## Steps to reproduce

1. Enter the URL for an amp or non-amp wp page.
2. Append a query string param eg. ?utm_source=123
3. Load the page

## Additional context

 - WordPress version: 5.3.2
 - Plugin version: 1.5.0-alpha
 - AMP plugin template mode: transitional
 - PHP version: 7.3

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@hellotoby Hello. Kept in the URL in what way? 

I'm testing in the latest build of 1.5-alpha: [amp.zip](https://github.com/ampproject/amp-wp/files/4327834/amp.zip) (1.5.0-alpha-20200312T162035Z-d077842e1), and in Transitional mode if I go to:

https://example.com/?utm_source=campaign

Then in the source of the page I can see:

```html
<link rel="amphtml" href="https://wordpressdev.lndo.site/?utm_source=campaign&#038;amp">
```

So this is ensuring the AMP URL includes the query param: https://example.com/?utm_source=campaign&amp

How are you seeing the query param being removed?

**Comment by westonruter** [comment]
Also, if I disable AMP for a given post and I try accessing the AMP version at:

https://example.com/2020/03/12/amp-disabled/?amp&utm_campaign=true

Then I am redirected to the non-AMP version:

https://example.com/2020/03/12/amp-disabled/?utm_campaign=true

The query parameters are preserved.

**Comment by hellotoby** [comment]
Hmm perhaps this is an issue with PWA. 

We are using PWA with amp in transitional mode, with the amp content being loaded in the inner shell.

I'm not seeing the same behaviour as you with this configuration. In fact the only query string param that I can get to stick in this config is the ?amp parameter.

**Comment by westonruter** [comment]
How are you implementing app shell? Are you using the experimental PR: https://github.com/ampproject/amp-wp/pull/1519?

**Comment by hellotoby** [comment]
@westonruter - Yes that's the pr that we're using.

**Comment by westonruter** [comment]
It may have to do this with this code in that PR:

https://github.com/ampproject/amp-wp/blob/87afea2d8f731d0911726077593965fc066dc37b/assets/js/amp-wp-app-shell.js#L183-L190

I suggest trying commenting out that first condition when `currentShadowDoc.canonicalUrl` is truthy to see if that fixes the problem. I don't recall actually why the PR is using `canonicalUrl` here. Perhaps it is to facilitate removing the `componentQueryVar`.

**Comment by arundhati1213** [comment]
how to get url parameter in localstorage in AMP pages
