### ISSUE TITLE
Raise PHPStan level for the `amp/common` package to 4

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#4379]
## Feature description

The Common package (`ampproject/common`) is currently sitting at and enforcing level 3 of PHPStan static analysis.

There are 5 errors that need to be fixed so that we can raise the level to 4 and enforce this new quality level in Travis CI.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PHPStan does not show any detected errors when run on level 4.

## Implementation brief

* Change the level to `4` in the file `phpstan.neon.dist`.
* Run `composer analyze`.
* Fix detected errors until no more are found.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
### Dom/Document.php                                                                        
|Line|Error|
|---:|---|
|  811|    Negated boolean expression is always true.|                                              
|  815|    Unreachable statement - code above always terminates.|                                   
|  1167|   Negated boolean expression is always false.|                                             
|  1390|   Strict comparison using === between null and DOMElement will always evaluate to false.|  

### RuntimeVersion.php                                                        
|Line|Error|
|---:|---|
|  81|     Comparison operation ">=" between int<min, 200> and 300 is always false.|

**Comment by amedina** [comment]
@schlessera Please include QA/Testing criteria.
