### ISSUE TITLE
Use amp-script instead of amp-bind to implement comment form interactivity with 100% feature parity

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4389]
## Feature description

When support for WordPress comments was introduced, amp-bind was used to implement support for inline replies. Using amp-bind got us most of the way there, but there are some pieces that don't work.

Clicking the Reply link brings the user down to the comment form instead of bringing the comment form _up_ to appear right after the comment they are replying to.:

![image](https://user-images.githubusercontent.com/134745/76694456-475d9480-6630-11ea-88f0-d5fa3bf2df6e.png)

Instead of bringing the form up inline the comment being replied to, the AMP implementation changes the reply-title heading to indicate the name of the commenter being replied to. This is not ideal. Additionally, when `comment_form()` is called with arguments to override the reply-title, we cannot use amp-bind to override heading in the first place (see #2489).

The reason why amp-bind was originally used to implement interactivity for WordPress comments is that it is what we had available at the time. Now, however, we have amp-script. We should be able to achieve 100% AMP parity in functionality by replacing amp-bind with amp-script. We may even be able to core's [`comment-reply.js`](https://github.com/WordPress/wordpress-develop/blob/5.3.2/src/js/_enqueues/lib/comment-reply.js) as is (or rather `comment-reply.min.js`)! The main thing we'd need to do is use a sanitizer to rewrite the use of `onclick` attributes as used by `get_post_reply_link()`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This issue is also important as we will soon support comments in Reader mode via alternate themes.

**Comment by schlessera** [comment]
The straight-forward approach of just pulling in Core's version of `comment-reply.min.js` does not seem to cut it with `<amp-script>`.

The component is not getting hydrated, and the console shows this:

![Image 2020-04-25 at 6.29.27 AM.png](https://images.zenhubusercontent.com/57bd4612e40e5714b16dc08b/28b27428-d816-40ef-85ba-f2bf71f39194)

There's not much documentation around for dealing with `<amp-script>`, but from what I can gather I assume for now that this means the script does stuff that is blacklisted, so the sandbox complains about code elements that would need to be removed but aren't.

I'll try a different approach now where we control the actual JS that gets used and adapt as needed to see whether we can strip it down to work while keeping the wanted functionality.

**Comment by westonruter** [comment]
@schlessera Can you open a PR with you've tried here? I can help explain usage if I can see what you were trying.

**Comment by schlessera** [comment]
@westonruter Nothing fancy yet, just trying to load the JS directly to see what happens. Result is that it doesn't hydrate, so I don't think that's worth pursuing further.

![Image 2020-04-25 at 6 45 30 AM](https://user-images.githubusercontent.com/83631/80271442-73a11200-86c0-11ea-810e-be25136ed990.png)

**Comment by westonruter** [comment]
If you load the page with `#development=1` in the URL then you can get more debugging information.

**Comment by schlessera** [comment]
That only adds the validation errors to the console, which only contain the `amp-devmode` attribute validation error.

**Comment by schlessera** [comment]
I'm not running out of surprises with `<amp-script>`...

The compatibility tables shows the following:
![Image 2020-05-04 at 5 37 50 PM](https://user-images.githubusercontent.com/83631/80984505-3c540300-8e2e-11ea-94b7-6160b7531c54.png)

So, according to this, using `event.preventDefault()` within an event handler is supported. And indeed, it doesn't produce an error when you put it in your `<amp-script>` code. However, it does not do anything, as the event is handled in the worker, which is a different thread than the main one from the document, see https://github.com/ampproject/amphtml/issues/22253 .

This means that we can't use actual links to add `<amp-script>` logic to, as they will just navigate to whatever URL the anchor has.

The alternative would be to use something like a `<button>` without a URL. However, that probably has all sorts of usability and accessibility implications, so I'm not entirely that is a good idea.

@westonruter What do you think, should I continue hacking my way to a working solution, even if it entails workarounds like this?

I feel like I'm wasting a lot of time with `<amp-script>` right now for a very dubious end-result...

**Comment by westonruter** [comment]
@schlessera Are you referring to the **Reply** and **Cancel Reply** links?

> ![image](https://user-images.githubusercontent.com/134745/80985248-cf1b8000-8de3-11ea-9c78-019bcb432315.png)

I think a `button` actually makes more sense and would be just as good (if not better) for accessibility. But switching to use a `button` would be problematic mostly for styling reasons. 

If you want to push up a draft PR with the current state of what you have and then move this to the Icebox for revisiting later, I'm fine with that. While this is nice to have, it's not critical.

**Comment by westonruter** [comment]
Also, links could still be used but they could have the `href` attribute replaced with `tabindex=0` and `role=button`. That may still have some styling issues, however, as we'd need to re-add the `cursor:pointer`. Other style changes may not show up as expected, e.g. ones attached with the `:link` pseudo-class selector.

**Comment by schlessera** [comment]
Yes, I'm talking about these (cancel) reply links.

Hmm, I assumed that AMP would throw a validation error for a link without an `href` attribute, but I just tried in the validator right now and it is perfectly happy with it.

I can try going down that route.

That being said, I already expect by now to just hit the next road block a few lines of code later...

**Comment by westonruter** [comment]
> Hmm, I assumed that AMP would throw a validation error for a link without an `href` attribute, but I just tried in the validator right now and it is perfectly happy with it.

Yeah, it's valid because of things like `<a name="anchor"></a>` from the olden days. More: https://stackoverflow.com/a/10510353/93579
