### ISSUE TITLE
Use amp-nested-menu to implement mobile menu in Twenty Nineteen

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4400]
## Feature description

When AMP compatibility was added for the Twenty Nineteen theme, we tried our best to implement support for the mobile menu (or rather, to use CSS only to implement the feature: https://github.com/WordPress/twentynineteen/pull/337):

![Comps for submenu](https://user-images.githubusercontent.com/1202812/47451566-2031c900-d796-11e8-90a2-53e29194d67d.png)

However, we weren't able to implement this without JS (see [`touch-keyboard-navigation.js`](https://github.com/WordPress/wordpress-develop/blob/f5c050791047e61ac5fdc6c1344c50afdbd3a577/src/wp-content/themes/twentynineteen/js/touch-keyboard-navigation.js)), so we had to ship the no-JS fallback experience for AMP (https://github.com/ampproject/amp-wp/pull/1587).

However, there is now an AMP component dedicated for this purpose: [`amp-nested-menu`](https://amp.dev/documentation/components/amp-nested-menu/). We should now leverage it in the core theme sanitizer.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Marking this as P1 since we'll be using Twenty Nineteen potentially as one of the templates we make available in Reader mode.

**Comment by westonruter** [comment]
The Bento version of `amp-sidebar` is incompatible with non-Bento `amp-nested-menu`. Since there is no Bento version of `amp-nested-menu` yet, this issue is blocked.

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Cross-checked the issue, Fix is working as expected. 

Non AMP



https://user-images.githubusercontent.com/44057535/216939312-a44495ce-6f82-4e56-8dc8-d2c59f32b6ac.mp4




**AMP**


https://user-images.githubusercontent.com/44057535/216939336-19d2a502-fb2b-4109-b72c-dff603915a97.mp4
