### ISSUE TITLE
Limit linting and fixing to files changed with develop

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4402]
## Feature description

Currently running linting commands like `npm run lint:php` is slow because it checks every file. We should limit to just checking the files that have changed in comparison with `develop`. In other words, 

```bash
vendor/bin/phpcs $(git diff develop --name-only | grep php)
```

If no PHP files are changed, then it should also just short-circuit.

This should be done for PHP, JS, and CSS.

This will then allow for the `lint` commands to be added to a `pre-commit` hook.

The `lint:fix` commands could also benefit from this.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kienstra** [comment]
If it's alright, I'll work on this. Though no urgency in reviewing it, as it's not in 1.5.

**Comment by schlessera** [comment]
**QA passed**

Tested 5 scenarios:
- Change in PHP file
- Change in JS file
- Change in CSS file
- Change in `package.json`
- Change in `amp.php` (added PHP 5.3+ syntax)

All scenarios were properly skipped when not staged and showed an error when staged. All lint passes were fast except for the very first PHPStan analysis, which is to be expected.
