### ISSUE TITLE
Content of noscript element is displayed in post

### ISSUE THREAD

**Issue by pierlon** [ampproject/amp-wp#4415]
## Bug Description

If a post has the following markup in the content:

```html
<noscript>hello</noscript>
```

On the AMP page, the `noscript` element is commented out and the word `hello` can be seen. 

## Expected Behaviour

The contents of the `noscript` element should not be visible.

## Steps to reproduce

1. Create a post with the following content:

```html
<noscript>hello</noscript>
```

2. Go to the AMP page
3. Verify the word `hello` can be seen on the page

## Screenshots

![image](https://user-images.githubusercontent.com/16200219/77221325-b52e2280-6b40-11ea-9dba-26d478632611.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This is actually behaving exactly as intended. If a theme has `noscript` fallbacks for when JS is disabled, the `AMP_Script_Santitizer` unwraps those elements so that they become the AMP version by default.
