### ISSUE TITLE
Custom Logo in Twenty Twenty lacks visual parity

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4418]
## Bug Description

Setting a Custom Logo in Twenty Twenty results in the image having excessive width:

![image](https://user-images.githubusercontent.com/134745/77285006-43172400-6c8d-11ea-8678-9efe243ca055.png)

## Expected Behaviour

The image should have the same dimensions between AMP and non-AMP.

## Steps to reproduce

0. Activate Transitional mode.
1. Activate Twenty Twenty
2. Select a 1600x1200 image as the Custom Logo
3. Enter paired browsing
4. Note difference in logo.

## Screenshots

![image](https://user-images.githubusercontent.com/134745/77284964-2aa70980-6c8d-11ea-81de-9c41ee13af81.png)

## Additional context

Version: 1.5.0-RC1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This is not a regression in 1.5-alpha. I tested in WordPress 5.0 with AMP plugin v1.4.x and it happens there as well.

**Comment by kienstra** [comment]
>This is not a regression in 1.5-alpha. I tested in WordPress 5.0 with AMP plugin v1.4.x and it happens there as well.

Ah, interesting.

This looks to be related to https://github.com/ampproject/amphtml/issues/21371#issue-419747971

Like in that issue, the `<amp-img>` for the Custom Logo has `display: block`

![has-display-block](https://user-images.githubusercontent.com/4063887/77361356-be6fe880-6d14-11ea-9130-d215ea487243.png)

Somebody better than me at CSS might figure this out, but I'm not sure if there is a solution to this.

There [was a workaround](https://github.com/ampproject/amp-wp/pull/2036/files#diff-0de6cf97122c9c2eb74c0bd358702aa2R8) for the image of `object-fit: contain`. Without that, this looks worse:

![without-object-fit-contain](https://user-images.githubusercontent.com/4063887/77361652-4d7d0080-6d15-11ea-89c8-b48b10aa5a28.png)

This slightly improves the image in a full desktop display:

```css
.site-logo img {
        object-position: left;
}

```

...but that moves the image to the wrong place on tablets and mobile:

![custom-logo-here](https://user-images.githubusercontent.com/4063887/77362149-16f3b580-6d16-11ea-91d4-0ba43c14bf91.png)

**Comment by westonruter** [comment]
It appears that adding `\AMP_Core_Theme_Sanitizer::add_twentyseventeen_attachment_image_attributes()` to run in Twenty Twenty fixes this issue.

**Comment by westonruter** [comment]
Except it actually introduces an AMP validation error due to the Optimizer output:

> `The attribute 'src' in tag 'IMG-I-AMPHTML-INTRINSIC-SIZER' is set to the invalid value 'data:image/svg+xml;charset=utf-8,<svg height="80" width="106.66666666667" xmlns="http://www.w3.org/2000/svg" version="1.1"/>'.`

**Comment by kienstra** [comment]
Hm...

**Comment by westonruter** [comment]
> This slightly improves the image in a full desktop display:

Except the `amp-img` is still too wide, causing wrapping of the nav menu:

![image](https://user-images.githubusercontent.com/134745/77364884-58826180-6d12-11ea-8fe7-0cc69541a537.png)

I'm looking into this.

**Comment by kienstra** [comment]
Yeah, `object-position: left;` isn't really a solution.

**Comment by westonruter** [comment]
OK, the issue is that `img` has intrinsic sizing in the browser whereas `amp-img` does not. 

This is demonstrated in this Pen: https://codepen.io/westonruter/pen/rNVqadv

When `img` has a `width:auto` it retains the aspect ratio depending on the `height`. However, a `span` (or an `amp-img`) has no intrinsic aspect ratio so when `width:auto` then it just fills as much width as the container provides.

So the fix I came up with in #4422 is to calculate the specific `width` for the desktop and mobile in `rem` units to apply for the specific image chosen.

In the future this problem should be solved by means of the [`aspect-ratio`](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) CSS property, which I presume AMP will set directly on `amp-img` and there'd be nothing to do here. However, this is not yet supported by browsers. So this is something to revisit in the future.
