### ISSUE TITLE
Ensure that Mustache templates in text/plain scripts are accounted for the same as those in template tags

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4446]
## Bug Description

The following logic in `\AMP_Tag_And_Attribute_Sanitizer::sanitize_disallowed_attribute_values_in_node()` is lacking:

https://github.com/ampproject/amp-wp/blob/2549ca3e154e6efc46ab1864335af627b84732de/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L1247-L1251

Namely, a Mustache template can also be in a `script` tag that has `type=text/plain` and `template=amp-mustache` (see [docs](https://amp.dev/documentation/components/amp-mustache/?format=websites#tables)). 

So anywhere that we are checking for a `template` tag we should also check for `script` with the required attributes. For example, in the form sanitizer:

https://github.com/ampproject/amp-wp/blob/2549ca3e154e6efc46ab1864335af627b84732de/includes/sanitizers/class-amp-form-sanitizer.php#L204

## Expected Behaviour

Mustache templates in `template` tags are treated the same as templates in `script` tags.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kienstra** [comment]
If it's alright, I'm going to work on this.

**Comment by westonruter** [comment]
This isn't a priority so let's leave for later.

**Comment by kienstra** [comment]
OK

**Comment by westonruter** [comment]
Actually, this is going to be fixed with #4583.
