### ISSUE TITLE
Other plugins erroneously add row actions and metaboxes to validation screens

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4448]
## Bug Description

When looking at a user's WordPress install to debug some issues, I saw that a plugin was adding row actions unexpectedly for the `amp_validated_url` post type:

![image](https://user-images.githubusercontent.com/134745/77681358-73431900-6f52-11ea-9c9b-740a7a420b60.png)

We should modify any row action filtering we are doing to increase the priority and only allow passing through the explicit keys we expect. For example:

```diff
--- a/includes/validation/class-amp-validated-url-post-type.php
+++ b/includes/validation/class-amp-validated-url-post-type.php
@@ -226,7 +226,7 @@ class AMP_Validated_URL_Post_Type {
 		add_action( 'admin_action_' . self::VALIDATE_ACTION, [ __CLASS__, 'handle_validate_request' ] );
 		add_action( 'post_action_' . self::UPDATE_POST_TERM_STATUS_ACTION, [ __CLASS__, 'handle_validation_error_status_update' ] );
 		add_action( 'admin_menu', [ __CLASS__, 'add_admin_menu_new_invalid_url_count' ] );
-		add_filter( 'post_row_actions', [ __CLASS__, 'filter_post_row_actions' ], 10, 2 );
+		add_filter( 'post_row_actions', [ __CLASS__, 'filter_post_row_actions' ], PHP_INT_MAX, 2 );
 		add_filter( sprintf( 'views_edit-%s', self::POST_TYPE_SLUG ), [ __CLASS__, 'filter_table_views' ] );
 		add_filter( 'bulk_post_updated_messages', [ __CLASS__, 'filter_bulk_post_updated_messages' ], 10, 2 );
 		add_filter( 'admin_title', [ __CLASS__, 'filter_admin_title' ] );
@@ -2808,6 +2808,11 @@ class AMP_Validated_URL_Post_Type {
 			);
 		}
 
+		$actions = wp_array_slice_assoc(
+			$actions,
+			[ 'edit', 'view', 'delete' ]
+		);
+
 		return $actions;
 	}
```

Similarly, I've seen plugins add metaboxes to the edit screen for this post type. (Related: #1011)

We should consider removing all metaboxes other than the ones we explicitly want. Either this means unhooking all `add_meta_boxes` actions, or deferring our call to `add_meta_boxes` to later and then removing all the ones we don't want.

This goes for all screens of both the `amp_validated_url` post type and the `amp_validation_error` taxonomy.

## Expected Behaviour

Only the expected row actions and meta boxes should be displayed.

## Steps to reproduce

1. Install and activate the WP Rocket plugin (this is a premium plugin, do we know of a different one to use here?)
2. Go to the `AMP`-> `Validated URLs` screen
3. Hover over an entry on this screen
4. The row contains the action `Clear this cache`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Only the expected row actions and meta boxes should be displayed.

## Implementation brief

* 

## QA testing instructions

1. Install and activate the below plugin.
2. Go to the `AMP`-> `Validated URLs` screen
3. Hover over an entry on this screen
4. **Verify:** The row contains at least actions `Details`, `Recheck` and `View`
5. **Verify:** The row does _not_ contain the action `Clear this cache`
6. **Verify** that the validation errors screen has only row actions for Details, Remove, and Keep.
7. **Verify** that no extraneous metaboxes appear on the Validated URL screen (only validation errors, stylesheets, and status metaboxes).

Consider adding this plugin for testing:

```php
<?php
/**
 * Plugin Name: Add Row Actions and Metaboxes
 */

function add_bad_row_action( $actions ) {
	$actions['bad'] = '<span style="color:red">SHOULD NOT BE HERE!</span>';
	return $actions;
}

add_filter( 'post_row_actions', 'add_bad_row_action' );
add_filter( 'amp_validation_error_row_actions', 'add_bad_row_action' );


/**
 * Register meta box(es).
 */
function wpdocs_register_meta_boxes() {
	add_meta_box( 'meta-box-id', __( 'My Meta Box', 'textdomain' ), 'wpdocs_my_display_callback', [ 'post', AMP_Validated_URL_Post_Type::POST_TYPE_SLUG ] );
}
add_action( 'add_meta_boxes', 'wpdocs_register_meta_boxes' );

/**
 * Meta box display callback.
 *
 * @param WP_Post $post Current post object.
 */
function wpdocs_my_display_callback( $post ) {
	?>
	Hello metabox!!
	<?php
}

```

#### Before:
![Image 2020-04-06 at 10 05 07 AM](https://user-images.githubusercontent.com/83631/78536855-c6d52280-77ee-11ea-99e1-8abf91921221.png)

#### After:
![Image 2020-04-06 at 9 22 25 AM](https://user-images.githubusercontent.com/83631/78536847-c472c880-77ee-11ea-8212-c89f1c224da2.png)

## Changelog entry

*

**Comment by pierlon** [comment]
**QA passed**

With the demo plugin given in the QA testing instructions above:

- No extraneous row actions on "Validated URLs" screen:
![image](https://user-images.githubusercontent.com/16200219/82341158-9680c680-99df-11ea-8b27-4dfb06fa6c8e.png)

- No extraneous actions on "Validated URL" screen:
![image](https://user-images.githubusercontent.com/16200219/82341544-19a21c80-99e0-11ea-86b0-9a373b304e10.png)

- No extraneous meta boxes on "Validated URL" screen:
![image](https://user-images.githubusercontent.com/16200219/82341601-2cb4ec80-99e0-11ea-858a-cbb552c4a1d8.png)

- No extraneous actions on "Validation Error Index" screen:
![image](https://user-images.githubusercontent.com/16200219/82341665-3ccccc00-99e0-11ea-88e4-1e327f332387.png)

**Comment by westonruter** [comment]
QA Passed

Screen | Before | After
--------|-------|-----
Post List Table | ![image](https://user-images.githubusercontent.com/134745/87613773-2337c000-c6c3-11ea-97c2-7270d6e42783.png) | ![image](https://user-images.githubusercontent.com/134745/87613781-2d59be80-c6c3-11ea-85c3-b0b96b1f7921.png)
Term List Table | ![image](https://user-images.githubusercontent.com/134745/87613852-5a0dd600-c6c3-11ea-8d40-91dbe4318553.png) | ![image](https://user-images.githubusercontent.com/134745/87613870-67c35b80-c6c3-11ea-8178-af42b2693a81.png)
Edit Post Screen | ![image](https://user-images.githubusercontent.com/134745/87613931-93dedc80-c6c3-11ea-97f0-d3eb1873de89.png) | n/a
