### ISSUE TITLE
Show a preview of AMP in AMP Settings page

### ISSUE THREAD

**Issue by kienstra** [ampproject/amp-wp#4452]
## Feature description

Maybe one of the biggest questions a new user would have is 'How will my site look with AMP?'

We could answer this by showing a preview on the AMP Settings page.

Still, it might be hard to make the previews wide enough to give a real preview. Having 2 iframes might be too much.

And it might reinforce the misconception that AMP is just for mobile, as it'll be a narrow display.

Maybe this would just be in the onboarding: https://github.com/ampproject/amp-wp/issues/1288

1. Each mode could have a 'Preview' button. 
2. On clicking it, a preview section would display

![preview-here](https://user-images.githubusercontent.com/4063887/77697478-8d8dee80-6f74-11ea-895a-f0507498ff95.png)

3. In Standard mode, there's probably no need for non-AMP
4. This could be like 'Paired Browsing', using iframes
5. In case some templates are disabled, this would find an eligible AMP endpoint to use in the preview

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by amedina** [comment]
Could we add a link to the new `Pair Browsing` feature? (The same that appears in the Admin bar)

![Pair-Browsing](https://user-images.githubusercontent.com/506089/78088421-fa402900-7378-11ea-8a32-c71e82c31aee.jpg)

**Comment by westonruter** [comment]
Paired browsing requires the Transitional mode to be enabled. So it wouldn't be appropriate to preview the mode.

I don't think we can have live site previews here. Best we could have is image representations showing theme's `screenshot.png` alongside the screenshot of the the theme chosen for Reader mode.

**Comment by amedina** [comment]
I don't like the idea of a static screenshot as it does not add any real value to just opening the content, and the UI effort to make it useful and nice is not trivial. 

Is there a way that we can have pair browsing in Reader mode? That would be neat. The use case is different from that of pair browsing in Transitional mode.

**Comment by amedina** [comment]
As discussed:
- We could have a variant of pair browsing for Reader Mode, but we would not be able to take advantage of scrolling position, etc.
- We can account for the capability of the plugin to give users an initial preview know how their AMP content will look like, as part of the onboarding flows (#1288)
- Settings modes can encompass some depiction of the differences between the the AMP and non AMP versions of the content

Closing this issue in favor of #1288.
