### ISSUE TITLE
Error in required structured data element

### ISSUE THREAD

**Issue by DanielCryptoK** [ampproject/amp-wp#4459]
I have got the below error showing in my webmaster tools for most of my pages and do not understand why?

Error in required structured data element
![Structured Data Testing Tool](https://user-images.githubusercontent.com/45933242/77744906-f183e600-704c-11ea-9840-f495c20e155a.png)

I have carried out a structured data test on the URL and AMP page with no errors showing. See example page below:

Error in required structured data element

https://bitcoin-casino-no-deposit-bonus.com/bitcoin-poker/amp/

I have asked in google webmaster forum but there answer makes no sense to me

https://support.google.com/webmasters/thread/35874709?hl=en

**Comment by westonruter** [comment]
Your Schema.org metadata is being added to the page by the Yoast SEO plugin.  Please reach out to the support for that plugin: https://yoast.com/help/support/
