### ISSUE TITLE
Leaked validation errors for implicit layout "container" without width/height

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4465]
## Bug Description

Given this markup in a Custom HTML block:

```html
<amp-ad type="adsense" data-ad-client="ca-pub-123" data-ad-slot="456" data-ad-format="auto" data-full-width-responsive="true"><span overflow=""></span></amp-ad>
```

This is leaking a validation error to the frontend:

> Incomplete layout attributes specified for tag 'amp-ad'. For example, provide attributes 'width' and 'height'.

I thought that this would have been prevented by #3728.

This was discovered in a [support topic](https://wordpress.org/support/topic/google-amp-4/).

## Expected Behaviour

AMP components that have neither a `layout` nor `width`/`height` attributes should be removed entirely. An appropriate validation error should be raised in the plugin.

The corresponding AMP validation error constant is `MISSING_LAYOUT_ATTRIBUTES`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

1. Create a new post.
2. Add the following markup into a "Custom HTML" block on the page:
	```html
	<amp-img src="https://placeholder.com/350"></amp-img>
	```
3. Publish the page and visit its AMP version.
4. **Verify:** The page should not show any validation errors (except for the "dev-mode" one) for the page.
5. Go to the "Validate" screen for the page.
6. **Verify:** The page should have 1 validation error with the following text:
	> Incomplete layout attributes specified for tag `amp-img`. For example, provide attributes `width` and `height`.

#### Before

![Image 2020-04-07 at 5 44 53 AM](https://user-images.githubusercontent.com/83631/78627963-1cfba180-7893-11ea-8243-aa5eb2721827.png)
The plugin's validation doesn't show any errors for the post.

![Image 2020-04-07 at 5 45 30 AM](https://user-images.githubusercontent.com/83631/78627982-27b63680-7893-11ea-8bcd-27faa2d301e3.png)
However, the AMP validator complains about the post.

#### After

![Image 2020-04-07 at 5 45 52 AM](https://user-images.githubusercontent.com/83631/78628004-38ff4300-7893-11ea-809b-ed2cbb286b00.png)
The plugin's validation catches the two offending elements and removes them.

![Image 2020-04-07 at 5 46 04 AM](https://user-images.githubusercontent.com/83631/78628019-45839b80-7893-11ea-93ec-b5c89c7e82fb.png)
The validation issues are not leaked into the AMP validator anymore.

## Changelog entry

*

**Comment by schlessera** [comment]
It looks like this is not part of the protoascii specs, but hard-coded logic within the validator(s): https://github.com/ampproject/amphtml/blob/6eb58814bebd917d3665ccf81f9db4cf641415c5/validator/engine/validator.js#L4124

**Comment by schlessera** [comment]
This has nothing to do with `amp-ad`, as you get the exact same error for an `<amp-img>` that is missing both the layout and the width/height attributes.

The reason for the validation error is that a missing layout falls back to the implicit layout "container", and that implicit layout requires `width` and `height` attributes to be set.

**Comment by westonruter** [comment]
> The reason for the validation error is that a missing layout falls back to the implicit layout "container", and that implicit layout requires `width` and `height` attributes to be set.

That doesn't seem to be quite right, as `container` layout actually does _not_ require `width`/`height` per the [docs](https://amp.dev/documentation/guides-and-tutorials/learn/amp-html-layout/#(tl;dr)-summary-of-layout-requirements-&-behaviors):

![image](https://user-images.githubusercontent.com/134745/78581093-3e538380-77e8-11ea-9dd4-004557c77012.png)

**Comment by schlessera** [comment]
Yes, I misphrased this. From the validator:
```
// Special case. If no layout related attributes were provided, this implies
// the CONTAINER layout. However, telling the user that the implied layout
// is unsupported for this tag is confusing if all they need is to provide
// width and height in, for example, the common case of creating
// an AMP-IMG without specifying dimensions. In this case, we emit a
// less correct, but simpler error message that could be more useful to
// the average user.
```

**Comment by westonruter** [comment]
It seems we need to implement that entire code block in `\AMP_Tag_And_Attribute_Sanitizer::is_valid_layout()`: https://github.com/ampproject/amphtml/blob/6eb58814bebd917d3665ccf81f9db4cf641415c5/validator/engine/validator.js#L4107-L4134

**Comment by schlessera** [comment]
Fixing this bug actually creates lots of failures in our test suite. I have 17 test failures right now. I haven't verified them all, yet, but it seems they are legit.

Here's an example:
```
3) AMP_Tag_And_Attribute_Sanitizer_Test::test_sanitize with data set "attribute_requirements_overriden_by_placeholders_within_template" ('<html amp><head><meta charset.../html>', null, array('amp-mustache', 'amp-timeago'))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     9 => '<body>'
     11 => '<!-- before -->'
     13 => '<template type="amp-mustache">'
-    15 => '<amp-timeago datetime="{{iso}}">'
-    17 => '</amp-timeago>'
-    19 => '</template>'
-    21 => '<!-- after -->'
-    23 => '</body>'
-    25 => '</html>'
+    15 => '</template>'
+    17 => '<!-- after -->'
+    19 => '</body>'
+    21 => '</html>'
 )
```

This is what the official validator shows for this test case:
![Image 2020-04-07 at 3 50 54 AM](https://user-images.githubusercontent.com/83631/78621503-09e0d580-7883-11ea-8cef-63ae52428f65.png)

**Comment by schlessera** [comment]
I could reproduce 15 out of 17 test failures in the official validator and fix by adding `width="100" height="100"`.

The two remaining test failures are related to `<amp-list>`, which doesn't seem to fall into this case according to the official validator. I'll push the current code for now as a WIP PR while I'm investigating the 2 remaining failures.

**Comment by schlessera** [comment]
I think the two remaining test failures are because we are also missing this part of the logic: https://github.com/ampproject/amphtml/blob/6eb58814bebd917d3665ccf81f9db4cf641415c5/validator/engine/validator.js#L4045-L4054

So, validating the layout should be skipped as soon as template syntax is discovered.

**Comment by schlessera** [comment]
Ah, I forgot we already skip sanitization completely through this code: https://github.com/ampproject/amp-wp/pull/3243/files#diff-ee41b32e64c90445a71328ca93cfa799R1005-R1009

I'll have to find another culprit then...

**Comment by schlessera** [comment]
Here's what I've got for the two remaining test failures.
- They seem to have the exact same cause: `<amp-list>` being detected as falling back to implicit `container` layout and missing `width` and `height`.
- According to our current spec version active in the plugin, `<amp-list>` does _*not*_ support the `container` layout.
- Therefore, we compute the `MISSING_LAYOUT_ATTRIBUTES` validation error and strip it.
- However, in the [AMP Validator](https://validator.ampproject.org/), the same AMP markup passes without validation errors.
- In the [documentation for the `amp-list` component](https://amp.dev/documentation/components/amp-list/?format=websites), it states that `<amp-list>` _*does*_ support the `container` layout.
- There was [a very recent effort](https://github.com/ampproject/amphtml/pull/27159) to add support for the `container` layout to the `amp-list` component, but it was [reverted recently afterwards](https://github.com/ampproject/amphtml/issues/27554) because it broke existing sites.

My current conclusion is that our interpretation (throw a `MISSING_LAYOUT_ATTRIBUTES` validation error if `width` & `height` are missing) is currently the correct one, and the official AMP validator is stuck between the PR for adding support and the PR for reverting it again, making the `container` layout supported and thus eliminating one of the prerequisites for issuing the `MISSING_LAYOUT_ATTRIBUTES` validation error.

@westonruter, @sebastianbenz Is this plausible? Are you able to confirm this internally?

**Comment by sebastianbenz** [comment]
@schlessera sounds reasonable. @caroqliu to confirm.

**Comment by caroqliu** [comment]
Looks like `amp-list` with `[layout="container"]` is passing the validation at https://validator.ampproject.org/ This should have been reverted as cited [earlier](https://github.com/ampproject/amp-wp/issues/4465#issuecomment-610174532).

cc @ampproject/wg-caching

**Comment by westonruter** [comment]
> * According to our current spec version active in the plugin, `<amp-list>` does __not__ support the `container` layout.

Correct. But the spec in the plugin is a bit stale. I have a pending PR to update it to 2004041903580 which will add this `layout`: https://github.com/ampproject/amp-wp/pull/4548#discussion_r405259030

So the validator spec should actually be deleting [`supported_layouts: CONTAINER`](https://github.com/ampproject/amphtml/blob/2e097a66e7790d6ed9c0f799613b1a961f40b176/extensions/amp-list/validator-amp-list.protoascii#L120) from `amp-list`?

**Comment by caroqliu** [comment]
> So the validator spec should actually be deleting `supported_layouts: CONTAINER` from `amp-list`?

Yes, in the line referenced above as well as [here](https://github.com/ampproject/amphtml/blob/2e097a66e7790d6ed9c0f799613b1a961f40b176/extensions/amp-list/validator-amp-list.protoascii#L245) and [here](https://github.com/ampproject/amphtml/blob/2e097a66e7790d6ed9c0f799613b1a961f40b176/extensions/amp-list/validator-amp-list.protoascii#L311). [This commit ](https://github.com/ampproject/amphtml/pull/27159/commits/335d1453aedb255c3fdb278b0446c6ac132b9e1d)specifically covers the extent of the validator changes that should be undone.

**Comment by pierlon** [comment]
**QA passed:**

With the following markup on the AMP page:
```html
<amp-img src="https://placeholder.com/350"></amp-img>
```

- The AMP Validator only complains of dev mode being enabled:
![image](https://user-images.githubusercontent.com/16200219/82349408-92f23d00-99e9-11ea-94e6-8f15bc5970b3.png)

- The only validation error shown is for incomplete layout attributes not being specified:
![image](https://user-images.githubusercontent.com/16200219/82349497-adc4b180-99e9-11ea-9560-da7c78a2c446.png)
