### ISSUE TITLE
CDN issue with 1.5.0-RC2-built.

### ISSUE THREAD

**Issue by askmeoffers** [ampproject/amp-wp#4468]
Hi , 

I was curious to use amp optimiser for SSR and it improved FCP a lot . 

But I am not able to use amazon cloud-front cdn for images delivery .  

when i am trying to use it the layout is broken 

thanks

**Comment by askmeoffers** [comment]
my website is coupons site built on custom wordpress theme 
we offers working coupons amazon , aliexpress coupons and many more 
https://askmeoffers.com/coupon-deal-offer-promo-store/aliexpress-com/

**Comment by westonruter** [comment]
What is the difference in behavior between 1.4.4 and 1.5.0-RC2 in regards to images?

**Comment by westonruter** [comment]
To best demonstrate issues, it is best to switch the site to Transitional mode so that the AMP and non-AMP versions can be compared. Nevertheless, I don't see how AMP SSR would interfere with CloudFront.

**Comment by askmeoffers** [comment]
Not sure on this may be its hosting provider issue will check and let you know .

meanwhile what i see is today is planned released for 1.5 which will have optimiser is it true ?

thanks

**Comment by westonruter** [comment]
Yes. Monday is the planned release day for 1.5.

**Comment by askmeoffers** [comment]
closing the ticket as the issue is wrt to cdn plugin i was using and its not related to amp plugin or framework
