### ISSUE TITLE
Improve handling of validation errors in Reader Mode

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#4480]
In Reader Mode validation errors are silently suppressed so users have no idea when something is being removed for being invalid. 

**Note**: that validation error messages used to be present in Reader mode, but they were removed in https://github.com/ampproject/amp-wp/pull/1132 because users were complaining about seeing undesired warnings (apparently ignorance is bliss).

The new Reader mode theme will need to trigger the standard theme hooks including wp_head and `wp_footer` so that scripts and stylesheets that a plugin may be trying to the page will be included and then reported as validation errors. This would have illuminated the reason for breakages such as https://github.com/ampproject/amphtml/issues/26622.

Of course, there is still going to be the need to suppress validation errors from certain user roles or on certain site configurations (e.g. WordPress.com). This is needed for Standard/Transitional mode already. 

It would also need to be available in Reader mode. See https://github.com/ampproject/amp-wp/issues/2673.

**Comment by westonruter** [comment]
Closely related to https://github.com/ampproject/amp-wp/issues/3821
