### ISSUE TITLE
Enable Async Validations

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#4481]
- Every time a post is saved in the editor, the AMP plugin performs a loopback request to that post's permalink URL on the frontend to then check it for validation errors. 
- In the block editor, this loopback request is done during the handling of the PUT request; this is done so that the PUT response can include all of the validation error data, but it also means that the PUT request takes much longer than it would normally. 
- To rectify this, it's important that validation be performed asynchronously to not block the normal authoring workflow as much as possible, but at the same time ensure the validation information is presented to the user when publishing.

**Comment by westonruter** [comment]
Is this the same as #2069?

**Comment by amedina** [comment]
Duplicate: #2069
