### ISSUE TITLE
Invalid src value in SSR image sizer element

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#4483]
## Bug Description

From https://wordpress.org/support/topic/error-images-4/ :

>The attribute ‘src’ in tag ‘IMG-I-AMPHTML-INTRINSIC-SIZER’ is set to the invalid value ‘data:image/svg+xml;charset=utf-8,<svg height=”704″ width=”500″ xmlns=”http://www.w3.org/2000/svg&#8221; version=”1.1″>’.UNKNOWN
line 39, column 2650

It seems like this is an error from the validator?

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Closing in favor of #4491.
