### ISSUE TITLE
Bad usage of `tax_query` param deletes a lot more than it should

### ISSUE THREAD

**Issue by aidvu** [ampproject/amp-wp#4489]
## Bug Description

Wrong usage of tax_query. Please check: https://developer.wordpress.org/reference/classes/wp_query/#taxonomy-parameters. This ended up deleting all reusable blocks for our customers. A hotfix release would be good.

## Expected Behaviour

The query should only fetch the taxonomy specified. Instead, it completely skips the `tax_query` param because it is used incorrectly.

## Steps to reproduce

1. Install an old AMP version. e.g. 1.4.4
2. Create a few reusable blocks on your site
3. Add them to pages, confirm they work
4. Updated to 1.5
5. Reusable blocks gone...

## Additional context

 - WordPress version: 5.3
 - Plugin version: upgrade to 1.5.0
 - PHP version: 7.*
 - OS: Linux

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@aidvu Hotfix 1.5.1 is now published on WordPress.org. 

Release notes: https://github.com/ampproject/amp-wp/releases/tag/1.5.1

Thank you _very much_ for reporting and opening a fix! 🙇

**Comment by aidvu** [comment]
> Thank you very much for reporting and opening a fix! bowing_man

Thank you for handling it. Based on the [graphs](https://wordpress.org/plugins/amp/advanced/), it was timely.

**Comment by westonruter** [comment]
Indeed:

![image](https://user-images.githubusercontent.com/134745/78056796-8717c200-733a-11ea-8e66-0869e8be8f54.png)
