### ISSUE TITLE
Image with decimal dimensions causes Optimizer to emit AMP Validation error 

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4493]
## Bug Description

Given input HTML like so:

```html
<amp-img src="https://blog.amp.dev/wp-content/uploads/2020/03/AMP_camp_Blog.png" alt="" height="938" width="1333.8226950355" layout="intrinsic"></amp-img>
```

Take note of the decimal value in the `width`. This is valid AMP.

When the Optimizer is enabled, this gets optimized as:

```html
<amp-img src="https://blog.amp.dev/wp-content/uploads/2020/03/AMP_camp_Blog.png" alt="" height="938" width="1333.8226950355" layout="intrinsic" class="i-amphtml-layout-intrinsic i-amphtml-layout-size-defined" i-amphtml-layout="intrinsic">
    <i-amphtml-sizer class="i-amphtml-sizer">
        <img alt="" aria-hidden="true" class="i-amphtml-intrinsic-sizer" role="presentation" src="data:image/svg+xml;charset=utf-8,<svg height=&quot;938&quot; width=&quot;1333.8226950355&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; version=&quot;1.1&quot;/>">
    </i-amphtml-sizer>
</amp-img>
```

Which is _not_ valid AMP. A validation error is raised:

> `The attribute 'src' in tag 'IMG-I-AMPHTML-INTRINSIC-SIZER' is set to the invalid value 'data:image/svg+xml;charset=utf-8,<svg height="938" width="1333.8226950355" xmlns="http://www.w3.org/2000/svg" version="1.1"/>'.`

When the AMP optimizer is disabled, the AMP runtime is generating constructing the DOM as follows:

```html
<amp-img src="https://blog.amp.dev/wp-content/uploads/2020/03/AMP_camp_Blog.png" alt="" height="938" width="1333.8226950355" layout="intrinsic" class="i-amphtml-element i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-layout" i-amphtml-layout="intrinsic" style="--loader-delay-offset:119ms !important;">
	<i-amphtml-sizer class="i-amphtml-sizer">
		<img alt="" role="presentation" aria-hidden="true" class="i-amphtml-intrinsic-sizer" src="data:image/svg+xml;charset=utf-8,<svg height=&quot;938px&quot; width=&quot;1333.8226950355px&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; version=&quot;1.1&quot;/>">
	</i-amphtml-sizer>
	<img decoding="async" alt="" src="https://blog.amp.dev/wp-content/uploads/2020/03/AMP_camp_Blog.png" class="i-amphtml-fill-content i-amphtml-replaced-content">
</amp-img>
```

Note that the decimal width is used here as well. This indicates that the validator spec is at fault here, namely the [`IMG-I-AMPHTML-INTRINSIC-SIZER` spec](https://github.com/ampproject/amphtml/blob/29848942cad3bf8909c30d912438f72dab661183/validator/validator-main.protoascii#L4856-L4882) which defines the `src` attribute to have a [`value_regex`](https://github.com/ampproject/amphtml/blob/29848942cad3bf8909c30d912438f72dab661183/validator/validator-main.protoascii#L4879) as follows:  

```
"data:image\\/svg\\+xml;charset=utf-8,<svg height=\"\\d+\" width=\"\\d+\" xmlns=\"http:\\/\\/www\\.w3\\.org\\/2000\\/svg\" version=\"1\\.1\"\\/>|data:image\\/svg\\+xml;charset=utf-8,<svg height='100' width='300' xmlns='http:\\/\\/www\\.w3\\.org\\/2000\\/svg' version='1\\.1'\\/>"
```

This needs to be changed to allow for decimal values, for example:

```
"data:image\\/svg\\+xml;charset=utf-8,<svg height=\"\\d+(\.\\d+)?\" width=\"\\d+(\.\\d+)?\" xmlns=\"http:\\/\\/www\\.w3\\.org\\/2000\\/svg\" version=\"1\\.1\"\\/>|data:image\\/svg\\+xml;charset=utf-8,<svg height='100' width='300' xmlns='http:\\/\\/www\\.w3\\.org\\/2000\\/svg' version='1\\.1'\\/>"
```

In the time being, should the AMP plugin hotfix by rounding the decimal value to an integer when generating the sizer image?

## Expected Behaviour

Validation errors should not be raised when an `amp-img` has a decimal width or height.

## Steps to reproduce

1. Paste the above `amp-img` into a Custom HTML block
2. View an Optimized AMP page.
3. Look for validation error.

## Additional context

 - WordPress version: 5.4
 - Plugin version: 1.5.1

Support forum topics:

* https://wordpress.org/support/topic/error-in-inline-images/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
cc @sebastianbenz

**Comment by westonruter** [comment]
Validator spec change may be fixed with this PR: https://github.com/ampproject/amphtml/pull/27518

**Comment by westonruter** [comment]
First encountered here: https://github.com/ampproject/amp-wp/issues/4418#issuecomment-602858087

**Comment by westonruter** [comment]
Quick fix for 1.5.2 is to cast the dimensions to integers. Ready for review: https://github.com/ampproject/amp-wp/pull/4506

**Comment by netnaps** [comment]
Hi, 

After I updated the Plugin I Got the same error on Lighthouse, Previously this was fine. 
Test Here is the error that I get :

Screenshot Attached : 

**Image elements do not have explicit width and height**

<img alt="" aria-hidden="true" class="i-amphtml-intrinsic-sizer" role="presentation" src="data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9JzMwJyB3aWR0aD0nMTUwJyB4bWxucz0n…">

![Screenshot 2020-10-16 at 4 50 17 PM](https://user-images.githubusercontent.com/67054369/96252678-f8198100-0fcf-11eb-83cf-21b8041adfde.png)

**Comment by westonruter** [comment]
@netnaps This is not the same issue.

**Comment by netnaps** [comment]
Ok
