### ISSUE TITLE
Required component for amp-form not detected when invalid <amp-form> is removed from wrapped <form> element

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4511]
## Bug Description

Given this invalid AMP markup:

```html
<amp-form>
	<form method="GET" id="a_string" class="a_string" action="https://example.com" target="_blank">
		<input type=text value="test" name="hello">
	</form>
</amp-form>
```

The `amp-form` is invalid and gets removed, being replaced with its children:

```html
<form method="GET" id="a_string" class="a_string" action="https://example.com" target="_blank">
	<input type="text" value="test" name="hello">
</form>
```

However, as part of this process the `amp-form` component script is not being detected as being required for the page.

Originally reported at https://wordpress.org/support/topic/custom-element-scripts-being-removed/

## Expected Behaviour

When `amp-form > form` is on the page, the `amp-form` component script should be added.

## Additional context

 - WordPress version: 5.4
 - Plugin version: 1.5.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by amedina** [comment]
QA:

- **Invalid tag `amp-form` being removed by the plugin**

![Screen Shot 2020-04-03 at 9 47 18 AM](https://user-images.githubusercontent.com/506089/78385383-9a23cf80-7590-11ea-97ac-be274a435d68.png)

- **`amp-form-0.1.js` script added**  

![Screen Shot 2020-04-03 at 9 47 59 AM](https://user-images.githubusercontent.com/506089/78385315-7fe9f180-7590-11ea-995b-cfe778228d22.png)

- **AMP compatibility preserved**

![Screen Shot 2020-04-03 at 9 49 02 AM](https://user-images.githubusercontent.com/506089/78385321-824c4b80-7590-11ea-8058-7d4aa938ddd1.png)

**Comment by westonruter** [comment]
Build for testing: [amp.zip](https://github.com/ampproject/amp-wp/files/4429512/amp.zip) (v1.5.2-RC1-20200403T193031Z-3102c5dea)
