### ISSUE TITLE
Integrate AMP Plugin with Query Monitor

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#4516]
## Feature description

Would it be possible to integrate the AMP plugin with [Query Monitor](https://wordpress.org/plugins/query-monitor/) so that some aspects of the AMP content generation and validation execution can exposed via Query Monitor?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
See also https://github.com/johnbillion/query-monitor/pull/535
