### ISSUE TITLE
Add Requires plugin header information

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#4520]
## Feature description

We should add the requirements into the plugin's file header to let WordPress know what is expected:

```php
 * Requires at least: 5.0
 * Requires PHP:      5.6
```

Note: I'm not sure which version of WordPress we actually do require since we stripped the AMP Stories component...

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The plugin advertises the correct requirements to WordPress.

## Implementation brief

* Add the following to the plugin file header metadata:
	```php
	 * Requires at least: 5.0
	 * Requires PHP:      5.6
	```

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@schlessera Isn't this already present? See:

https://github.com/ampproject/amp-wp/blob/4193dbc5d83c295a3f1595e96108984a48673f00/readme.txt#L4-L9

It needs to be in the `readme.txt` not the plugin bootstrap file, AFAIK. See https://make.wordpress.org/plugins/2017/08/29/minimum-php-version-requirement/

**Comment by swissspidy** [comment]
Support for this in the main plugin file was added rather recently. Because in some cases WP only checks that, not the readme.

**Comment by westonruter** [comment]
Of _course_ it does! 🤦‍♂
