### ISSUE TITLE
Add button to reenable CSS transient cache

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#4523]
## Feature description

As the CSS transient cache can be automatically disabled, we should add a button to the Site Health panel for a user to re-enable it.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A user can re-enable the CSS transient caching via a button on the Site Health screen.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Let's add this in 1.5.3
