### ISSUE TITLE
https://github.com/ampproject/amp-wp/issues/4386#issue-581243326

### ISSUE THREAD

**Issue by bagusparmadani** [ampproject/amp-wp#4646]
## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Please supply all requested information when filing issues.
