### ISSUE TITLE
CSS in Reader mode is not minified

### ISSUE THREAD

**Issue by paulschreiber** [ampproject/amp-wp#688]
The AMP CSS inserting by the plugin (`.alignright` through `.back-to-top`) is not minified.
![screen shot 2017-04-24 at 4 48 15 pm](https://cloud.githubusercontent.com/assets/86784/25357999/dc44b9ec-290d-11e7-8c06-a28effe57aee.png)

**Comment by mjangda** [comment]
We don't minify anything right now. @amedina has some code in #668 for minification that we can probably generalize and re-use for this.

**Comment by amedina** [comment]
Yes; we should do this. Will try to get to it asap.

**Comment by westonruter** [comment]
Minifying CSS with PHP can lead to unexpected results, especially considering that the `content` property can reference any string at all. Maybe the occurrence of such problems would be rare, but in order to do it properly we'd need to use an actual CSS tokenizer rather than use regular expressions for search and replace.

**Comment by paulschreiber** [comment]
It should be minified with an existing tool, such as cssmin. Don't write your own minifier. If this CSS is static, it can be done at build time, not runtime.

**Comment by westonruter** [comment]
CSS in Classic/Reader mode is still not minified. See #2202 for how we can extend the minification and tree shaking to this mode.

**Comment by kienstra** [comment]
**Steps To Test**

1. Select Reader mode
2. Create a new post with any title or content
3. Go to the front-end, and inspect the source
4. Expected: the `<style amp-custom>` is minified. There shouldn't be large spaces inside the style rules.

<img width="937" alt="style-amp" src="https://user-images.githubusercontent.com/4063887/73766252-6583cb00-473b-11ea-8324-97f873af10a8.png">

**Comment by csossi** [comment]
Verified in QA
