### ISSUE TITLE
Lazy Load on Featured Image

### ISSUE THREAD

**Issue by Blackbaud-WillHull** [ampproject/amp-wp#711]
Greetings, I have this plugin enabled on WindyPinwheel.com and the lazy load does not load the featured image.  Is there a way to disable lazy load on the featured image? 

Thanks,
Will Hull
Reno, NV, USA

**Comment by amedina** [comment]
Hi @Blackbaud-WillHull, do you have an URL where we can see the problem?

**Comment by Blackbaud-WillHull** [comment]
Here is an example where I had to add data-no-lazy="1" to my Wordpress post template on the featured image to bypass the lazy load: [http://windypinwheel.com/guest-post-5-ways-to-get-your-kids-to-drink-more-water-each-day/ ](http://windypinwheel.com/guest-post-5-ways-to-get-your-kids-to-drink-more-water-each-day/)

Because the site is live, I couldn't load it without it.  But if you take out the data-lazy-load="1" it will not render the featured image.  Thanks for following up.

**Comment by westonruter** [comment]
Can you please share the source code for your post template?
