### ISSUE TITLE
build_post_featured_image() runs unnecessarily

### ISSUE THREAD

**Issue by paulschreiber** [ampproject/amp-wp#732]
`build_post_featured_image()` runs unnecessarily, whether or not the featured image is shown in the template.

We have postmeta that determines whether to hide/show the image.

Result: if the featured image is a gif, `amp-anim` gets added to `amp_component_scripts`, which generates a warning in the AMP validator.

**Comment by paulschreiber** [comment]
It would be helpful to be able to filter this i.e. `if ( apply_filters( 'amp_featured_image_is_visible', true ) ) { ... } `.

**Comment by westonruter** [comment]
How are you turning off a featured image from being displayed? Are you doing something like:

```php
add_filter( 'amp_post_template_data', function( $data ) {
    $data['featured_image'] = false;
    return $data;
} );
```

If so, then it would seem to me that the scripts returned by `AMP_Img_Sanitizer` should get queued up _after_ the filter applies, not before.

**Comment by paulschreiber** [comment]
>How are you turning off a featured image from being displayed? Are you doing something like:

We have a metabox with a checkbox titled "Show image on article page." When the box is _not_ checked, we save some postmeta to indicate suppression.

In the template itself, we retrieve the value of the postmeta, put it in `$show_featured_image`, and call something like this:
```
if ( $show_featured_image ) {
   get_template_part( 'template-parts/featured-image-embed' );
}
```

In the `amp_post_template_data` filter, we have code like this:
```
// Workaround for https://github.com/Automattic/amp-wp/issues/732
//
// Suppress amp-anim if:
// (a) no GIFs in body
// (b) featured image is a GIF
// (c) suppress featured image checkbox is checked
//
if ( ! preg_match( '/<amp-anim.+src=".+\.gif/', $data['post_amp_content'] ) ) { // query params may be present after gif; no close quote
	$featured_image_url = get_the_post_thumbnail_url( $post->ID );
	$url_parts = wp_parse_url( $featured_image_url );
	$file_extension = strtolower( pathinfo( $url_parts['path'], PATHINFO_EXTENSION ) );
	if ( 'gif' === $file_extension ) {
		$show_featured_image  = get_post_meta( $post->ID, ...

		if ( ! $show_featured_image ) {
			unset( $data['amp_component_scripts']['amp-anim'] );
		}
	}
}
```

**Comment by westonruter** [comment]
This should be made obsolete by #2202 in that we can move to constructing the Reader mode templates in a more traditional way, and then only the AMP components that are actually used in the page will then be among the scripts included on the page.

**Comment by westonruter** [comment]
Made obsolete via #3781.
