### ISSUE TITLE
Add support for Google AMP Client ID API

### ISSUE THREAD

**Issue by nekromoff** [ampproject/amp-wp#775]
https://support.google.com/analytics/answer/7486764

**Comment by nekromoff** [comment]
https://support.google.com/analytics/answer/7486764

**Comment by westonruter** [comment]
This is what the plugin currently provides for analytics entries.

![image](https://user-images.githubusercontent.com/134745/44488213-0399d900-a60d-11e8-9741-2f9e24c86ec4.png)

What we could do is if a user supplies `googleanalytics` as the type, that an additional checkbox appears to opt-in to client ID.

**Comment by westonruter** [comment]
Really it would be ideal if this was all done automatically based on the script sanitizer described in #1032. For example, if the script sanitizer came across a script like: 

```html
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXXX-Y', 'auto', {'useAmpClientId': true});
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->
```

Then it should automatically convert this into:

```html
<meta name="amp-google-client-id-api" content="googleanalytics">
<script src="https://cdn.ampproject.org/v0/amp-analytics-latest.js" async="" custom-element="amp-analytics"></script>
...
<amp-analytics id="f27ffc1d4690" type="googleanalytics"><script type="application/json">{"vars":{"account":"UA-XXXXX-Y"},"triggers":{"trackPageview":{"on":"visible","request":"pageview"}}}</script>
```

**Comment by amedina** [comment]
Reopening this issue to add option to admin panel.

**Comment by westonruter** [comment]
I suggest we reveal a checkbox to opt-in to client ID specifically when `googleanalytics` is specified as the Type.

**Comment by christianoliveira** [comment]
Is it possible to activate the client ID option in Wordpress somehow right now?

**Comment by westonruter** [comment]
@nekromoff Try this plugin: https://gist.github.com/westonruter/a11b2c9321374c993286c01bab21bbc2

**Comment by felixarntz** [comment]
@westonruter @nekromoff @christianoliveira The [Google Site Kit plugin](https://sitekit.withgoogle.com/) supports AMP client ID on both sides, covering the [non-AMP part](https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics.php#L262) as well as the [AMP part](https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics.php#L342).

**Comment by westonruter** [comment]
Awesome. I think we're done here then. The next step is to soft-deprecate the Analytics admin screen by encouraging users to install one of the AMP-compatible ecosystem plugins that tailor the given analytics product to their site. See #2317.
