### ISSUE TITLE
Add support for mandatory_oneof and mandatory_anyof attribute constraints

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#938]
## Feature description

Someone had a `<iframe src="about:blank">` in a post on https://wordpress.org/support/topic/google-console-error/#post-9946202

This is resulting in an `<amp-iframe>` being rendered but without a `src` attribute. The result is in valid AMP because `src` is mandatory.

The whitelist sanitizer should be removing the `<amp-iframe>` in this case I should think. But otherwise, the iframe sanitizer itself can preemptively remove the iframe to ensure validity. Perhaps a placeholder could be put there in its place.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. The iframe sanitizer should preemptively remove the iframe to ensure validity
2. When `<iframe src="about:blank">`is  in a post the whitelist sanitizer should be removing the `<amp-iframe>`

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This will be fixed by implementing support for `mandatory_oneof`: https://github.com/ampproject/amphtml/blob/2db6d704364343057dbdbb1e2347973a54faae94/validator/validator-main.protoascii#L1508

See:

https://github.com/Automattic/amp-wp/blob/79b8b839f1922d3ccaddc36cf3ffddfc1a94f207/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L23-L24

**Comment by westonruter** [comment]
This has come up again: https://wordpress.org/support/topic/how-to-add-allow-presentation-attribute-to-amp-iframe/

**Comment by westonruter** [comment]
This came up yet again, but for a different reason: https://wordpress.org/support/topic/the-tag-iframe-is-missing-a-mandatory-attribute/

**Comment by westonruter** [comment]
`amp-script` [has `mandatory_anyof`](https://github.com/ampproject/amphtml/blob/acf82b01bb68d30921bf5932264bc9d515a23a70/extensions/amp-script/validator-amp-script.protoascii#L64-L74) (as of #3003):

```
  attrs: {
    name: "script"
    mandatory_anyof: "['script', 'src']"
  }
  attrs: {
    name: "src"
    mandatory_anyof: "['script', 'src']"
    value_url: {
      protocol: "https"
      allow_relative: false
    }
    blacklisted_value_regex: "__amp_source_origin"
  }
```

Compare with `amp-iframe` which [has `mandatory_oneof`](https://github.com/ampproject/amphtml/blob/acf82b01bb68d30921bf5932264bc9d515a23a70/extensions/amp-iframe/validator-amp-iframe.protoascii#L67-L69):

```
  attrs: {
    name: "src"
    mandatory_oneof: "['src', 'srcdoc']"
    value_url: {
      protocol: "data"
      protocol: "https"
      allow_relative: true  # Will be set to false at a future date.
    }
    blacklisted_value_regex: "__amp_source_origin"
  }
```

Neither of these constraints are being applied currently.

**Comment by choumx** [comment]
Good catch that amp-script should use `mandatory_oneof`.

**Comment by westonruter** [comment]
@choumx Should it? I thought this made sense because `amp-script` should be configured to use a script _either_ in an external location (via `src` attribute) _or_ locally (via `script` attribute pointing to a `script[type=text/plain]`). No?

**Comment by choumx** [comment]
Correct, so an amp-script that has both `src` and `script` should be invalid. Which is what `mandatory_oneof` enforces.

**Comment by westonruter** [comment]
So then should `amp-iframe` actually use `mandatory_anyof` because both `src` and `srcdoc` should be allowed? Per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe):

> ![image](https://user-images.githubusercontent.com/134745/62800089-588d6400-ba97-11e9-8b74-00fe06009289.png)

So this should be valid AMP:

```html
<amp-iframe 
    width="640" 
    height="480" 
    layout="responsive" 
    src="https://example.com"
    srcdoc="&lt;!doctype html&gt; &lt;html&gt; &lt;head&gt; &lt;title&gt;Example Domain&lt;/title&gt; &lt;meta charset=&quot;utf-8&quot; /&gt; &lt;meta http-equiv=&quot;Content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt; &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt; &lt;style type=&quot;text/css&quot;&gt; body { background-color: #f0f0f2; margin: 0; padding: 0; font-family: &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; } div { width: 600px; margin: 5em auto; padding: 50px; background-color: #fff; border-radius: 1em; } a:link, a:visited { color: #38488f; text-decoration: none; } @media (max-width: 700px) { body { background-color: #fff; } div { width: auto; margin: 0 auto; border-radius: 0; padding: 1em; } } &lt;/style&gt; &lt;/head&gt; &lt;body&gt; &lt;div&gt; &lt;h1&gt;Example Domain&lt;/h1&gt; &lt;p&gt;This domain is established to be used for illustrative examples in documents. You may use this domain in examples without prior coordination or asking for permission.&lt;/p&gt; &lt;p&gt;&lt;a href=&quot;http://www.iana.org/domains/example&quot;&gt;More information...&lt;/a&gt;&lt;/p&gt; &lt;/div&gt; &lt;/body&gt; &lt;/html&gt;"
    >
  <span placeholder>...</span>
</amp-iframe>
```

But it is not.

**Comment by choumx** [comment]
Do you know if there's a related bug on such browsers? Asking because it looks like amp-iframe converts srcdoc to a data URI under the hood: https://github.com/ampproject/amphtml/blob/a033bc12b94cde56887bdde7ea543c089d3502de/extensions/amp-iframe/0.1/amp-iframe.js#L255-L262

**Comment by westonruter** [comment]
Interesting. I wasn't aware of that. If that's the case, where `srcdoc` is pushed into `src` with a `data:` URL, then indeed `mandatory_oneof` seems fine.

**Comment by kienstra** [comment]
**Implementation**

Hi @westonruter, 
Hope your week's off to a great start!

What do you think about:

```diff
diff --git a/bin/amphtml-update.py b/bin/amphtml-update.py
index 469d74469..7d9bf7d42 100644
--- a/bin/amphtml-update.py
+++ b/bin/amphtml-update.py
@@ -708,6 +708,10 @@ def GetValues(attr_spec):
        if attr_spec.HasField('mandatory'):
                value_dict['mandatory'] = attr_spec.mandatory
 
+       if attr_spec.HasField('mandatory_oneof'):
+               mandatory_oneof = attr_spec.mandatory_oneof.lstrip('[').rstrip(']').split(', ')
+               value_dict['mandatory_oneof'] = [oneof.strip("'") for oneof in mandatory_oneof]
+
        # Add allowed value
        if attr_spec.value:

diff --git a/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php b/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
index 6786a213d..b3c6a0540 100644
--- a/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
+++ b/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
@@ -57,6 +57,7 @@ class AMP_Tag_And_Attribute_Sanitizer extends AMP_Base_Sanitizer {
        const INVALID_BLACKLISTED_VALUE_REGEX      = 'INVALID_BLACKLISTED_VALUE_REGEX';
        const DISALLOWED_PROPERTY_IN_ATTR_VALUE    = 'DISALLOWED_PROPERTY_IN_ATTR_VALUE';
        const ATTR_REQUIRED_BUT_MISSING            = 'ATTR_REQUIRED_BUT_MISSING';
+       const MANDATORY_ONEOF_ATTR_MISSING         = 'MANDATORY_ONEOF_ATTR_MISSING';
        const INVALID_LAYOUT_WIDTH                 = 'INVALID_LAYOUT_WIDTH';
        const INVALID_LAYOUT_HEIGHT                = 'INVALID_LAYOUT_HEIGHT';
        const INVALID_LAYOUT_AUTO_HEIGHT           = 'INVALID_LAYOUT_AUTO_HEIGHT';
@@ -729,6 +730,19 @@ class AMP_Tag_And_Attribute_Sanitizer extends AMP_Base_Sanitizer {
                        return null;
                }
 
+               // If there is a 'mandatory_oneof' value and exactly one of the required attributes isn't present, remove the element.
+               if ( $this->is_missing_mandatory_oneof_attribute( $merged_attr_spec_list, $node ) ) {
+                       $this->remove_invalid_child(
+                               $node,
+                               [
+                                       'code'       => self::MANDATORY_ONEOF_ATTR_MISSING,
+                                       // Maybe also include an 'attributes' value.
+                                       'spec_name'  => $this->get_spec_name( $node, $tag_spec ),
+                               ]
+                       );
+                       return null;
+               }
+
                // Add required AMP component scripts.
                $script_components = [];
                if ( ! empty( $tag_spec['requires_extension'] ) ) {
@@ -774,6 +788,8 @@ class AMP_Tag_And_Attribute_Sanitizer extends AMP_Base_Sanitizer {
                return 0 !== count( $this->get_missing_mandatory_attributes( $attr_spec, $node ) );
        }
 
+       private function is_missing_mandatory_oneof_attribute( $attr_spec, DOMElement $node ) {}
+
        /**
         * Get list of mandatory missing mandatory attributes.
         *
```

Also, It'll be good to avoid checking the same `mandatory_oneof` values multiple times.

For example, the same `mandatory_oneof` value `"['end-date', 'timeleft-ms', 'timestamp-ms', 'timestamp-seconds']"` [appears multiple times](https://github.com/ampproject/amphtml/blob/45c1eb0f4e41d84574a96ffd4b37c55ffaea335d/extensions/amp-date-countdown/validator-amp-date-countdown.protoascii#L71-L85):

```
attrs: {
    name: "timeleft-ms"
    mandatory_oneof: "['end-date', 'timeleft-ms', 'timestamp-ms', 'timestamp-seconds']"
    value_regex: "\\d+"
  }
  attrs: {
    name: "timestamp-ms"
    mandatory_oneof: "['end-date', 'timeleft-ms', 'timestamp-ms', 'timestamp-seconds']"
    value_regex: "\\d{13}"
  }
  attrs: {
    name: "timestamp-seconds"
    mandatory_oneof: "['end-date', 'timeleft-ms', 'timestamp-ms', 'timestamp-seconds']"
    value_regex: "\\d{10}"
  }
```

**Comment by westonruter** [comment]
Seems like a good approach at first glance.

**Comment by kienstra** [comment]
Thanks!

**Comment by kienstra** [comment]
Whenever this is ready for QA, these testing instructions should be fine: https://github.com/ampproject/amp-wp/pull/4285#issue-374115799

**Comment by kienstra** [comment]
**Updated Testing Instruction**

Please use these instead.

1. As the description of #938 mentions, adding this to a Custom HTML block:

```html
<iframe src="about:blank">
```

...should result in the `<amp-iframe>` being stripped, and the validation errors now include:

![mandatory-oneof](https://user-images.githubusercontent.com/4063887/74404442-1fd89980-4df0-11ea-84cc-ff73bac59eea.png)

2. And adding this to a Custom HTML block:
```html
<amp-list width="400" height="400"></amp-list>
```
...should result in this validation error:
![amp-list-here](https://user-images.githubusercontent.com/4063887/74594145-a8c22180-4ff8-11ea-8bee-20a41dec59e4.png)

**Comment by csossi** [comment]
Hi @kienstra - seeing the validation error as described above for the 2nd case, but looks different for the first. What I'm seeing is:
![image](https://user-images.githubusercontent.com/16945664/75255880-a3ab6200-57b0-11ea-8d8f-2461d1cbedf9.png)

**Comment by kienstra** [comment]
Hi @csossi,
Sorry for the delay.

Maybe there was a recent deployment that fixed this.

But it looks like adding the markup from [case 2 above](https://github.com/ampproject/amp-wp/issues/938#issuecomment-586640154) to a Custom HTML block:

```html
<amp-list width="400" height="400"></amp-list>
```

...[results in](https://story-test-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=5783&action=edit) the expected message:

<img width="858" alt="expected-message" src="https://user-images.githubusercontent.com/4063887/75811621-5f8d0400-5d52-11ea-9b9d-d02739015b93.png">

Do you see that also?

Thanks, Claudio!

**Comment by csossi** [comment]
Verified in QA (able to replicate message above)

**Comment by kienstra** [comment]
Nice, thanks!
