### ISSUE TITLE
Enable generation of Optimized (aka Transformed) AMP pages

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#958]
We can speed up the serving of AMP pages by pre-rendering them and serving them in the same way they are served from an AMP cache. In short, the processes performed by the [AMP Optimizer](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer) should be ported into the plugin. Something important to note here that when pre-rendering is performed, there will somewhat counter-intuitively need to be a paired mode even when a site is AMP Canonical. The reason is:

> Warning: optimized AMPs will no longer be valid AMPHTML. Don't use this to optimize AMPs meant for being used by platforms such as Google Search.

So the pre-rendered AMP version of a page would would be canonical URL, and there would be an `amphtml` link to the same exact content without the pre-rendering logic applied. This is similar to the existing paired mode works, _except_ here the canonical version is generated _from_ the AMP version via pre-rendering. So it's important to note that this pre-rendering should not be offered on sites that are not using Canonical AMP, as it would not make sense to have a pre-rendered AMP version alongside the valid AMP and the non-AMP content.

As for where the pre-rendering should be performed, it should be done right after the call to `AMP_Content_Sanitizer::sanitize_document()` in `AMP_Theme_Support::prepare_response()`:

https://github.com/Automattic/amp-wp/blob/1ab37c654d8c36cb1e17f1c997a6a2f00002273c/includes/class-amp-theme-support.php#L813-L815

For example:

```php
$assets = AMP_Content_Sanitizer::sanitize_document( $dom, self::$sanitizer_classes, $args );
self::ensure_required_markup( $dom );
if ( ! is_amp_endpoint() ) {
    do_the_function_that_runs_amp_prerendering( $dom ); // 👈
}
```

Since `is_amp_endpoint()` currently always returns `true` if `amp_is_canonical()` then this will need to be amended to support the case for pre-rendering. In other words, even on a canonical-site there will be the need for separate AMP endpoint URLs. So the `if ( amp_is_canonical() ) { return true; }` conditional may need to be removed here. Related to #934.

👉 For more on server-side rendering, see [Faster AMP on the origin: AMP + SSR = ⚡](https://blog.amp.dev/2019/08/07/faster-amp-on-the-origin-amp-ssr/).

👉  For implementation notes, refer to [AMP SSR Toolkit Implementation Guide](https://docs.google.com/document/d/1lZl7UJ5eUrhwTmfbOZ7g-HFIgMnTeqGwfUxE98kALzU/edit).

**Comment by westonruter** [comment]
In AMP the SSR is also termed “transformed”. The validator has just landed with some recognition of this which we're not explicitly skipping from the generated spec: https://github.com/ampproject/amp-wp/pull/1891/commits/51d81abf7ffa3897dbc7fd4c991eb407d14eb942.

We'll potentially need to revert that and add some awareness of a `transformed` mode. Or potentially we'd still not care about the transformed rules since we'd apply them in a sanitizer after the whitelist runs.

**Comment by westonruter** [comment]
See also https://twitter.com/westonruter/status/1120061001443893248

We need to make sure the Transformed AMP sanitizer, along with the other sanitizers, are turned into a separate package which can be used standalone.

**Comment by westonruter** [comment]
Depends on `layout=intrinsic` being server-side renderable. See https://github.com/ampproject/amphtml/pull/24119

**Comment by westonruter** [comment]
An important blocker for SSR (transformed intrinsic layout support) has been lifted: https://github.com/ampproject/amphtml/pull/24119. For pending reference implementation of SSR intrinsic layout, see https://github.com/ampproject/amp-toolbox/pull/443.

**Comment by csossi** [comment]
Any QA instructions to be added here, @schlessera ?

**Comment by schlessera** [comment]
**Testing instructions:**

1. Make sure the Optimizer is enabled (this is the case on the test site)
2. Go to the AMP-version of a page
3. Look at the generated markup of the page via `View Source...`
4. **Verify:** **(Optimizer active)** The `html` tag has the attribute `transformed="self;v=1"` (at the very beginning of the document)
5. **Verify:** **(Serverside rendering active)** There's a `<style amp-runtime="" i-amphtml-version="XXX">` tag that contains the entire AMP runtime stylesheet

/cc @csossi

**Comment by westonruter** [comment]
Also verify that the result is Valid AMP (aside for dev mode when logged in).

**Comment by schlessera** [comment]
Good point, updated the instructions.

**Comment by csossi** [comment]
Verified in qa:
![image](https://user-images.githubusercontent.com/16945664/76713902-501a9d00-66fa-11ea-88ab-4719b02158e0.png)
